/**
 * Shared label set for /calendar root page.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/calendar-labels-overlay.json`, generated by
 * `scripts/translate-calendar-via-gemini.py`.
 *
 * The "Regional Calendar Traditions" paragraph wraps four inline
 * <Link> nodes — translation is decomposed into Pre / Sep / Post
 * fragments so the JSX structure stays intact across locales.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/calendar-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // 3-letter month abbreviations for the SSR festival list
    monthShort1:  'Jan', monthShort2:  'Feb', monthShort3:  'Mar',
    monthShort4:  'Apr', monthShort5:  'May', monthShort6:  'Jun',
    monthShort7:  'Jul', monthShort8:  'Aug', monthShort9:  'Sep',
    monthShort10: 'Oct', monthShort11: 'Nov', monthShort12: 'Dec',
    // ItemList LD + main h2
    ssrListName: 'Upcoming Hindu Festivals',
    mainHeading: 'Hindu Festival Calendar 2026',
    // Intro paragraphs
    introPara1: 'The Hindu calendar (Panchang) follows a lunisolar system where months, tithis (lunar days), nakshatras (lunar mansions), yogas, and karanas form the five limbs of timekeeping. Every festival and vrat date is determined by the Moon’s phase (tithi) and the lunar month (Amanta or Purnimanta convention), which is why Gregorian dates shift each year.',
    introPara2: 'This calendar provides location-accurate dates for all major festivals, Ekadashi fasting days with Parana (fast-breaking) times, Purnima, Amavasya, Chaturthi, Pradosham, and eclipses. Click on any festival to see detailed puja vidhi, significance, and observance instructions.',
    // Features section
    featuresHeading: 'Calendar Features',
    featuresPara: 'Our calendar is location-aware — all tithi timings, sunrise/sunset, and Ekadashi Parana windows are computed for your city. Switch between Western months (January–December), Hindu lunar months (Chaitra–Phalguna), or a visual Tithi Grid view. Filter by category: festivals only, Ekadashi, Purnima, Amavasya, Chaturthi, Pradosham, or eclipses. Export to your Apple or Google Calendar via ICS download.',
    // Regional section (paragraph with 4 inline links)
    regionalHeading: 'Regional Calendar Traditions',
    regionalPart1: 'India does not follow a single uniform calendar. The ',
    regionalAnchorBengali: 'Bengali calendar (Bangabda)',
    regionalPart2: ' is solar and starts its year with Boishakh (around April 14). The ',
    regionalAnchorTamil: 'Tamil calendar (Thiruvalluvar)',
    regionalPart3: ' is also solar, beginning the year with Chithirai at Mesha Sankranti. The ',
    regionalAnchorGujarati: 'Gujarati calendar (Vikram Samvat)',
    regionalPart4: ' is uniquely lunisolar and starts its new year (Bestu Varas) the day after Diwali on Kartik Shukla Pratipada. Telugu, Kannada, Marathi, and Odia calendars follow the lunisolar Amanta system beginning with Chaitra. See month names, new year dates, and key regional festivals for all traditions on our ',
    regionalAnchorRegional: 'Regional Calendars page',
    regionalPart5: '.',
    // Cross-links
    linkPanchangToday: 'Today’s Panchang →',
    linkLearnTithis: 'Learn about Tithis →',
    linkLearnMuhurtas: 'Learn about Muhurtas →',
    linkVedicTime: 'Vedic Time →',
    // Upcoming festivals table
    upcomingHeading: 'Upcoming Major Festivals',
    tableFestivalCol: 'Festival',
    tableDateCol: 'Date',
    tableDescCol: 'Description',
    ujjainFootnote: '* Dates are computed for Ujjain (Indian reference). Use the location selector in the calendar above for your city’s exact timings.',
  },
  hi: {
    monthShort1:  'जन.',  monthShort2:  'फर.',   monthShort3:  'मार्च',
    monthShort4:  'अप्रै.', monthShort5: 'मई',   monthShort6:  'जून',
    monthShort7:  'जुला.', monthShort8: 'अग.',  monthShort9:  'सित.',
    monthShort10: 'अक्टू.', monthShort11: 'नव.', monthShort12: 'दिस.',
    ssrListName: 'आगामी प्रमुख त्योहार',
    mainHeading: 'हिन्दू त्योहार कैलेंडर 2026',
    introPara1: 'हिन्दू कैलेंडर (पंचांग) चन्द्र-सौर प्रणाली पर आधारित है जिसमें मास, तिथि, नक्षत्र, योग और करण पाँच अंगों से मिलकर बनते हैं। प्रत्येक त्योहार और व्रत की तिथि चन्द्रमा की कला (तिथि) और मास (अमान्त या पूर्णिमान्त) से निर्धारित होती है। यही कारण है कि ग्रेगोरियन कैलेंडर पर तारीखें प्रतिवर्ष बदलती हैं।',
    introPara2: 'यह कैलेंडर आपके स्थान के अनुसार सटीक तिथि, एकादशी पारण समय, पूर्णिमा, अमावस्या, चतुर्थी, प्रदोष और ग्रहण सहित सम्पूर्ण पंचांग प्रदान करता है। प्रत्येक त्योहार पर क्लिक करें — विस्तृत विधि, महत्व और पूजा पद्धति देखें।',
    featuresHeading: 'कैलेंडर की विशेषताएँ',
    featuresPara: 'हमारा कैलेंडर स्थान-आधारित है — सभी तिथि समय, सूर्योदय/सूर्यास्त, और एकादशी पारण खिड़कियाँ आपके शहर के अनुसार गणना की जाती हैं। आप पश्चिमी मास (जनवरी-दिसम्बर), हिन्दू चन्द्र मास (चैत्र-फाल्गुन), या तिथि ग्रिड दृश्य में देख सकते हैं। फ़िल्टर करें: केवल त्योहार, एकादशी, पूर्णिमा, अमावस्या, चतुर्थी, प्रदोष, या ग्रहण। ICS निर्यात से अपने Apple/Google कैलेंडर में जोड़ें।',
    regionalHeading: 'क्षेत्रीय पंचांग परम्पराएँ',
    regionalPart1: 'भारत में एक ही मानक पंचांग नहीं है। ',
    regionalAnchorBengali: 'बंगाली कैलेंडर (बंगाब्द)',
    regionalPart2: ' सौर पद्धति से चलता है और बोइशाख से वर्ष आरम्भ होता है। ',
    regionalAnchorTamil: 'तमिल पंचांग (तिरुवल्लुवर)',
    regionalPart3: ' भी सौर है और चित्तिरै (मेष संक्रान्ति) से शुरू होता है। ',
    regionalAnchorGujarati: 'गुजराती पंचांग (विक्रम संवत)',
    regionalPart4: ' अनूठा है — इसका नववर्ष (बेस्तु वरस) दीपावली के अगले दिन कार्तिक शुक्ल प्रतिपदा से आरम्भ होता है। तेलुगु, कन्नड़, मराठी और ओड़िया पंचांग चान्द्र-सौर (लूनिसोलर) पद्धति से चलते हैं। इन सभी क्षेत्रीय परम्पराओं की विस्तृत जानकारी, मास-नाम और प्रमुख त्योहार ',
    regionalAnchorRegional: 'क्षेत्रीय पंचांग पृष्ठ',
    regionalPart5: ' पर देखें।',
    linkPanchangToday: 'आज का पंचांग →',
    linkLearnTithis: 'तिथियों के बारे में जानें →',
    linkLearnMuhurtas: 'मुहूर्त सीखें →',
    linkVedicTime: 'वैदिक समय →',
    upcomingHeading: 'आगामी प्रमुख त्योहार',
    tableFestivalCol: 'त्योहार',
    tableDateCol: 'तिथि',
    tableDescCol: 'विवरण',
    ujjainFootnote: '* तारीखें उज्जैन (भारतीय मानक) के लिए हैं। अपने शहर की सटीक तिथि के लिए ऊपर दिए गए कैलेंडर में स्थान चुनें।',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickCalendarLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function calendarMonthShort(monthIndex0Based: number, locale: string): string {
  return pickCalendarLabel(`monthShort${monthIndex0Based + 1}`, locale);
}
