/**
 * Shared label set for /festivals/[slug]/[year] + /[city] pages.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/festivals-labels-overlay.json`, generated by
 * `scripts/translate-festivals-via-gemini.py`.
 *
 * Scope: chrome only — field labels, section headings, breadcrumb
 * crumbs, cross-link labels. The actual BODY content (significance,
 * vidhi, mantras, phala prose) ships via FESTIVAL_DETAILS overlay
 * which is already 9-locale (per layout.tsx canonical comment).
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/festivals-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Breadcrumbs
    crumbHome: 'Home',
    crumbFestivals: 'Festivals',
    // Subtitle template (year page hero)
    subtitleTemplate: 'Exact date, puja muhurat & city-wise timings for {NAME} {YEAR}',
    yearCalendarContextTemplate: '{YEAR} Calendar Context',
    inCityTemplate: 'in {CITY}',
    // Cross-link chips (year + city pages share these)
    linkTodaysPanchang: "Today's Panchang",
    linkEkadashi2026: 'Ekadashi 2026',
    linkFindMuhurta: 'Find Auspicious Muhurta',
    linkGenerateKundali: 'Generate Kundali',
    // Section / card headings
    keyInformation: 'Key Information',
    keyTimings: 'Key Timings',
    festivalDate: 'Festival Date',
    weekday: 'Weekday',
    tithi: 'Tithi',
    observationRule: 'Observation Rule',
    vikramSamvat: 'Vikram Samvat',
    shakaSamvat: 'Shaka Samvat',
    city: 'City',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    pujaMuhurat: 'Puja Muhurat',
    pujaWindow: 'Puja Window',
    whyThisDate: 'Why This Date?',
    tithiDeterminationRule: 'Tithi Determination Rule',
    pujaVidhi: 'Puja Vidhi',
    materialsRequired: 'Materials Required',
    pujaSteps: 'Puja Steps',
    vratPhalaFastingBenefits: 'Vrat Phala (Fasting Benefits)',
    phalaBenefits: 'Phala (Benefits)',
    deity: 'Deity',
    festivalSingular: 'Festival',
    festivalsPlural: 'Festivals',
    howToObserve: 'How to Observe',
    legendHistory: 'Legend & History',
    readFullLegend: 'Read full legend →',
    significance: 'Significance',
    fasting: 'Fasting',
    festivalTimingRules: 'Festival Timing Rules',
    kalaRule: 'Kala Rule',
    lunarMonthsExplained: 'Lunar Months Explained',
    smartaVaishnava: 'Smarta & Vaishnava Calendars',
    understandingTithis: 'Understanding Tithis',
    calculationProof: 'Calculation Proof  –  Transparent Audit Trail',
    timezone: 'Timezone',
    coordinates: 'Coordinates',
    viewAllFestivalsVrats: 'View All Festivals & Vrats',
    showLessUp: 'Show less ↑',
    learnMore: 'Learn more',
  },
  hi: {
    crumbHome: 'मुख्य',
    crumbFestivals: 'त्योहार',
    subtitleTemplate: '{NAME} {YEAR} की सटीक तिथि, पूजा मुहूर्त व शहर-वार समय',
    yearCalendarContextTemplate: '{YEAR} पंचांग संदर्भ',
    inCityTemplate: '{CITY} में',
    linkTodaysPanchang: 'आज का पंचांग',
    linkEkadashi2026: 'एकादशी 2026',
    linkFindMuhurta: 'शुभ मुहूर्त खोजें',
    linkGenerateKundali: 'कुण्डली बनाएँ',
    keyInformation: 'प्रमुख जानकारी',
    keyTimings: 'प्रमुख समय',
    festivalDate: 'त्योहार की तिथि',
    weekday: 'वार',
    tithi: 'तिथि',
    observationRule: 'पालन नियम',
    vikramSamvat: 'विक्रम संवत्',
    shakaSamvat: 'शक संवत्',
    city: 'शहर',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    pujaMuhurat: 'पूजा मुहूर्त',
    pujaWindow: 'पूजा समय',
    whyThisDate: 'यह तिथि क्यों?',
    tithiDeterminationRule: 'तिथि निर्धारण नियम',
    pujaVidhi: 'पूजा विधि',
    materialsRequired: 'आवश्यक सामग्री',
    pujaSteps: 'पूजा के चरण',
    vratPhalaFastingBenefits: 'व्रत फल (उपवास के लाभ)',
    phalaBenefits: 'फल (लाभ)',
    deity: 'देवता',
    festivalSingular: 'त्योहार',
    festivalsPlural: 'त्योहार',
    howToObserve: 'कैसे मनाएँ',
    legendHistory: 'कथा एवं इतिहास',
    readFullLegend: 'पूरी कथा पढ़ें →',
    significance: 'महत्व',
    fasting: 'व्रत',
    festivalTimingRules: 'उत्सव काल नियम',
    kalaRule: 'काल नियम',
    lunarMonthsExplained: 'चंद्र मास विवरण',
    smartaVaishnava: 'स्मार्त और वैष्णव पंचांग',
    understandingTithis: 'तिथि को समझें',
    calculationProof: 'गणना प्रमाण  –  पारदर्शी लेखा परीक्षा',
    timezone: 'समय क्षेत्र',
    coordinates: 'निर्देशांक',
    viewAllFestivalsVrats: 'सभी त्योहार और व्रत देखें',
    showLessUp: 'कम दिखाएँ ↑',
    learnMore: 'और जानें',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickFestivalLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatFestivalLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickFestivalLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}
