/**
 * Shared label set for /horoscope/[rashi] hub + daily/weekly/monthly
 * variants + HubClient/HoroscopeClient/RashiArticle.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/horoscope-labels-overlay.json`, generated by
 * `scripts/translate-horoscope-via-gemini.py`.
 *
 * High-leverage SEO: rashi × locale × daily/weekly/monthly =
 * 12 × 9 × 3 distinct H1+description pairs. Per-locale H1 templates
 * carry {NAME} (rashi name) + {WESTERN_NAME} + {RANGE} or {MONTH} or
 * {WEEKDAY},{DATE} placeholders.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/horoscope-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Weekly H1 + description templates (NAME = rashi vedic name,
    // WESTERN_NAME = English/zodiac name, RANGE = "12-18 Jun, 2026")
    weeklyH1Template: '{NAME} ({WESTERN_NAME}) Weekly Horoscope  –  {RANGE}',
    weeklyDescTemplate: '{WESTERN_NAME} ({NAME}) weekly horoscope for {RANGE}. Day-by-day scores, career, love, health and finance predictions based on actual Vedic planetary transits.',
    // Monthly H1 + description templates (MONTH = "June 2026")
    monthlyH1Template: '{NAME} ({WESTERN_NAME}) Monthly Horoscope  –  {MONTH}',
    monthlyDescTemplate: '{WESTERN_NAME} ({NAME}) monthly horoscope for {MONTH}. Calendar heatmap, career, love, health and finance predictions based on actual Vedic planetary transits.',
    // Daily-date H1 (WEEKDAY = "Tuesday", DATE = "12 Jun 2026")
    dailyDateH1Template: '{NAME} ({WESTERN_NAME}) Horoscope  –  {WEEKDAY}, {DATE}',
    // Daily-date overall-score line
    overallScoreTemplate: 'Overall score: {SCORE}/10',
    // 5 area labels (used in both daily and [date] surfaces)
    areaCareer: 'Career',
    areaLove: 'Love',
    areaHealth: 'Health',
    areaFinance: 'Finance',
    areaSpirituality: 'Spirituality',
    // Period-tab labels (HoroscopeClient)
    tabDaily: 'Daily',
    tabWeekly: 'Weekly',
    tabMonthly: 'Monthly',
    tabDasha: 'Dasha',
    // HubClient
    featuredSignOfTheDay: 'Featured Sign of the Day',
    me: 'Me',
    // WeeklyClient
    noStandoutStrongDays: 'No standout strong days',
    noChallengingDays: 'No especially challenging days',
    // Festivals headings (weekly + monthly pages)
    festivalsThisWeek: 'Festivals & Vrats This Week',
    festivalsThisMonth: 'Festivals & Vrats This Month',
    // CTA
    signUpFree: 'Sign Up Free',
    // RashiArticle H2
    aboutRashiTemplate: 'About {WESTERN_NAME} ({NAME})  –  Personality & Traits',
  },
  hi: {
    weeklyH1Template: '{NAME} साप्ताहिक राशिफल  –  {RANGE}',
    weeklyDescTemplate: '{NAME} राशि का साप्ताहिक राशिफल {RANGE} के लिए। वास्तविक ग्रह गोचर पर आधारित दैनिक स्कोर, करियर, प्रेम, स्वास्थ्य एवं वित्त भविष्यवाणी।',
    monthlyH1Template: '{NAME} मासिक राशिफल  –  {MONTH}',
    monthlyDescTemplate: '{NAME} राशि का मासिक राशिफल {MONTH} के लिए। कैलेंडर हीटमैप, करियर, प्रेम, स्वास्थ्य एवं वित्त भविष्यवाणी। वैदिक ग्रह गोचर पर आधारित।',
    dailyDateH1Template: '{NAME} राशिफल  –  {WEEKDAY}, {DATE}',
    overallScoreTemplate: 'समग्र स्कोर: {SCORE}/10',
    areaCareer: 'करियर',
    areaLove: 'प्रेम',
    areaHealth: 'स्वास्थ्य',
    areaFinance: 'वित्त',
    areaSpirituality: 'आध्यात्म',
    tabDaily: 'दैनिक',
    tabWeekly: 'साप्ताहिक',
    tabMonthly: 'मासिक',
    tabDasha: 'दशा',
    featuredSignOfTheDay: 'आज की विशेष राशि',
    me: 'स्वयं',
    noStandoutStrongDays: 'कोई विशेष प्रबल दिन नहीं',
    noChallengingDays: 'कोई चुनौतीपूर्ण दिन नहीं',
    festivalsThisWeek: 'इस सप्ताह के पर्व एवं व्रत',
    festivalsThisMonth: 'इस माह के पर्व एवं व्रत',
    signUpFree: 'निःशुल्क खाता बनाएँ',
    aboutRashiTemplate: '{NAME} राशि  –  व्यक्तित्व और लक्षण',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickHoroscopeLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatHoroscopeLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickHoroscopeLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}
