/**
 * Shared label set for /kundali (root page + Client + compare + HowTo schema).
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (sa + mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/kundali-page-labels-overlay.json`, generated by
 * `scripts/translate-kundali-page-via-gemini.py`.
 *
 * `sa` is no longer indexed (HTTP 410) but legacy crawlers may hit it,
 * so we still serve translated text there.
 *
 * Article paragraphs that wrap inline <strong>/<em>/<Link> markup are
 * decomposed into label fragments (heading + label/text pairs) so the
 * JSX structure stays intact and Gemini only translates plain text.
 *
 * Resolution order:
 *   1. AUTHORED[locale]?.[key]
 *   2. OVERLAY[locale]?.[key]
 *   3. AUTHORED.hi[key]
 *   4. AUTHORED.en[key]
 */
import overlay from '@/lib/constants/kundali-page-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // ── /kundali/page.tsx article ──
    introHeading: 'What is a Kundali (Birth Chart)?',
    intro: 'A Kundali (also called Janam Patrika, Janam Kundli, or natal chart) is the foundational tool of Vedic astrology. It is a map of the sky at the exact moment and location of your birth, showing the positions of 9 celestial bodies (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu) across 12 houses. Each house governs a specific domain of life — health, career, marriage, children, wealth, spirituality — and the planets placed there reveal the karmic patterns and potential of that domain.',
    requirementsHeading: 'What Do You Need to Generate a Kundali?',
    requirementsLead: 'Three essential inputs:',
    req1Label: 'Date of birth:',
    req1Text: 'Day, month, and year',
    req2Label: 'Time of birth:',
    req2Text: 'As precise as possible (the Ascendant changes every ~2 hours; nakshatra pada shifts every ~3.2 hours)',
    req3Label: 'Place of birth:',
    req3Text: 'Latitude and longitude (entering a city name is sufficient — we resolve the coordinates automatically)',
    requirementsExplain: 'Birth time accuracy is critical because the Ascendant (Lagna) changes approximately every 2 hours. House lordships, planetary strengths, and dasha periods are all calculated from the Ascendant, so even a 4–5 minute error can shift the entire chart interpretation.',
    stylesHeading: 'North Indian vs South Indian Chart Styles',
    stylesNorthLabel: 'North Indian (Diamond/Kendra):',
    stylesNorthText: 'Houses are fixed in position; signs rotate. The Ascendant is always at the top-centre diamond. This style is used across North India, Nepal, and Sri Lanka.',
    stylesSouthLabel: 'South Indian (Grid):',
    stylesSouthText: 'Signs are fixed in position; planets move between them. Aries is always in the top-left cell. Used in Tamil Nadu, Karnataka, Kerala, and Andhra Pradesh. Our tool supports both styles — toggle between them after generating your chart.',
    tableHeading: 'The 12 Houses at a Glance',
    tableHouseCol: 'House',
    tableAreaCol: 'Life Area',
    formIntroBelow: 'Enter your birth details in the form below. Our engine will compute planetary positions, Ascendant, Vimshottari dasha periods, yogas, doshas, Shadbala, Ashtakavarga, and a comprehensive interpretive commentary (Tippanni) — all computed locally in your browser using Meeus algorithms, with no external APIs.',
    exploreLagnaHeading: 'Explore by Ascendant (Lagna)',
    lagnaSuffix: 'Ascendant',
    featuredYogasHeading: 'Featured Yogas',
    yogaSuffix: 'Yoga',
    linkMatching: 'Kundali Matching →',
    linkSadeSati: 'Sade Sati Check →',
    linkLearnKundali: 'Learn to Read a Kundali →',
    linkLearnGrahas: 'Nine Planets →',
    // ── 12 houses table data ──
    h1Name: 'Lagna / Ascendant',
    h1Area: 'Self, personality, physical body, general temperament',
    h2Name: '2nd House (Dhana)',
    h2Area: 'Wealth, family, speech, food habits, early education',
    h3Name: '3rd House (Sahaja)',
    h3Area: 'Siblings, courage, short journeys, communication, skills',
    h4Name: '4th House (Sukha)',
    h4Area: 'Mother, home, vehicles, property, domestic happiness',
    h5Name: '5th House (Putra)',
    h5Area: 'Children, intelligence, creativity, romance, past-life merit',
    h6Name: '6th House (Ripu)',
    h6Area: 'Enemies, disease, debts, daily work, service, litigation',
    h7Name: '7th House (Kalatra)',
    h7Area: 'Marriage, partnerships, business associates, public dealings',
    h8Name: '8th House (Ayu)',
    h8Area: 'Longevity, transformation, inheritance, occult, sudden events',
    h9Name: '9th House (Dharma)',
    h9Area: 'Fortune, father, guru, long journeys, higher learning, dharma',
    h10Name: '10th House (Karma)',
    h10Area: 'Career, reputation, authority, public image, government',
    h11Name: '11th House (Labha)',
    h11Area: 'Gains, income, elder siblings, social networks, aspirations',
    h12Name: '12th House (Vyaya)',
    h12Area: 'Losses, expenses, foreign lands, spirituality, liberation',
    // ── Client.tsx ──
    generateError: 'Failed to generate chart. Please check your inputs and try again.',
    generateErrorRetry: 'Failed to generate chart. Please try again.',
    viewFullPoster: 'View Full Poster',
    shareYourChart: 'Share Your Chart',
    intensityIntense: 'Intense',
    intensityModerate: 'Moderate',
    intensityMild: 'Mild',
    // ── compare/page.tsx ──
    pickSavedChart: 'Pick a saved chart...',
    orNewDetails: 'or enter new details below',
    // ── layout.tsx HowTo schema ──
    schemaName: 'How to Generate a Vedic Birth Chart (Kundali)',
    schemaDescription: 'Step-by-step guide to creating an accurate Kundali (Janam Patrika) using your birth date, time, and place. Get planetary positions, dashas, yogas, doshas, and 20+ interpretive analyses computed via Swiss Ephemeris.',
    schemaStep1Name: 'Enter Name',
    schemaStep1Text: 'Enter the name of the person whose chart you want to generate.',
    schemaStep2Name: 'Enter Birth Date and Time',
    schemaStep2Text: 'Enter the exact birth date and time. The more precise the time, the more accurate the Lagna and house positions.',
    schemaStep3Name: 'Select Birth Place',
    schemaStep3Text: 'Search and select the birth city. Latitude, longitude, and timezone are determined automatically.',
    schemaStep4Name: 'Generate Kundali',
    schemaStep4Text: 'Click "Generate Kundali". Swiss Ephemeris computes precise planetary positions, dashas, yogas, doshas, and 20+ analysis tabs instantly.',
  },
  hi: {
    introHeading: 'कुण्डली (जन्म कुण्डली) क्या है?',
    intro: 'कुण्डली (जन्म पत्रिका या जातक चार्ट) वैदिक ज्योतिष का मूल आधार है। यह जन्म के सटीक समय और स्थान पर आकाश में ग्रहों की स्थिति का मानचित्र है। 12 भावों (houses) में 9 ग्रहों (सूर्य, चन्द्र, मंगल, बुध, गुरु, शुक्र, शनि, राहु, केतु) का स्थान यह दर्शाता है कि जीवन के विभिन्न क्षेत्रों — स्वास्थ्य, करियर, विवाह, सन्तान, धन — पर किन ग्रहों का प्रभाव है।',
    requirementsHeading: 'कुण्डली बनाने के लिए क्या चाहिए?',
    requirementsLead: 'तीन आवश्यक जानकारी:',
    req1Label: 'जन्म तिथि:',
    req1Text: 'दिन, मास, वर्ष',
    req2Label: 'जन्म समय:',
    req2Text: 'जितना सटीक हो उतना अच्छा (लग्न हर 2 घंटे में बदलता है, नक्षत्र पाद ~3.2 घंटे)',
    req3Label: 'जन्म स्थान:',
    req3Text: 'अक्षांश और देशान्तर (शहर का नाम पर्याप्त है — हम स्वतः निर्देशांक ज्ञात कर लेते हैं)',
    requirementsExplain: 'जन्म समय महत्वपूर्ण है क्योंकि लग्न (Ascendant) प्रत्येक ~2 घंटे में बदलता है, और भाव-स्वामित्व, ग्रह-बल तथा दशा-काल की गणना लग्न पर निर्भर करती है। 4-5 मिनट की त्रुटि भी परिणाम बदल सकती है।',
    stylesHeading: 'उत्तर भारतीय बनाम दक्षिण भारतीय चार्ट',
    stylesNorthLabel: 'उत्तर भारतीय (हीरा/डायमंड):',
    stylesNorthText: 'भाव स्थिर रहते हैं, राशियाँ बदलती हैं। लग्न सदा शीर्ष-मध्य (हीरा) में। यह पद्धति उत्तर भारत, नेपाल और श्रीलंका में प्रचलित है।',
    stylesSouthLabel: 'दक्षिण भारतीय (ग्रिड):',
    stylesSouthText: 'राशियाँ स्थिर रहती हैं, ग्रह बदलते हैं। मेष सदा ऊपर-बाँयें। तमिलनाडु, कर्नाटक, केरल और आन्ध्र प्रदेश में प्रचलित। हमारा गणक दोनों शैलियों का समर्थन करता है।',
    tableHeading: '12 भावों का संक्षिप्त विवरण',
    tableHouseCol: 'भाव',
    tableAreaCol: 'जीवन क्षेत्र',
    formIntroBelow: 'नीचे दिए गए फॉर्म में अपनी जन्म जानकारी भरें। हमारा गणक स्वतः ग्रह स्थिति, लग्न, दशा-अन्तर्दशा, योग, दोष, शडबल, अष्टकवर्ग और सम्पूर्ण विश्लेषण (टिप्पणी) उत्पन्न करेगा — सब कुछ आपके ब्राउज़र में, बिना किसी बाहरी API के।',
    exploreLagnaHeading: 'लग्न के अनुसार पढ़ें',
    lagnaSuffix: 'लग्न',
    featuredYogasHeading: 'प्रमुख योग',
    yogaSuffix: 'योग',
    linkMatching: 'कुण्डली मिलान →',
    linkSadeSati: 'साढ़े साती जाँच →',
    linkLearnKundali: 'कुण्डली पढ़ना सीखें →',
    linkLearnGrahas: 'नवग्रह →',
    h1Name: 'लग्न / प्रथम भाव',
    h1Area: 'व्यक्तित्व, शरीर, सामान्य स्वभाव',
    h2Name: 'द्वितीय भाव (धन)',
    h2Area: 'धन, परिवार, वाणी, भोजन, प्रारम्भिक शिक्षा',
    h3Name: 'तृतीय भाव (सहज)',
    h3Area: 'भाई-बहन, साहस, लघु यात्रा, संवाद, कौशल',
    h4Name: 'चतुर्थ भाव (सुख)',
    h4Area: 'माता, गृह, वाहन, सम्पत्ति, गृहस्थ सुख',
    h5Name: 'पंचम भाव (पुत्र)',
    h5Area: 'सन्तान, बुद्धि, सृजनशीलता, प्रेम, पूर्वजन्म पुण्य',
    h6Name: 'षष्ठ भाव (रिपु)',
    h6Area: 'शत्रु, रोग, ऋण, दैनिक कार्य, सेवा, मुकदमे',
    h7Name: 'सप्तम भाव (कलत्र)',
    h7Area: 'विवाह, साझेदारी, व्यापार सहयोगी, सार्वजनिक व्यवहार',
    h8Name: 'अष्टम भाव (आयु)',
    h8Area: 'आयु, परिवर्तन, विरासत, गुप्त विद्या, अचानक घटनाएँ',
    h9Name: 'नवम भाव (धर्म)',
    h9Area: 'भाग्य, पिता, गुरु, दीर्घ यात्रा, उच्च शिक्षा, धर्म',
    h10Name: 'दशम भाव (कर्म)',
    h10Area: 'करियर, प्रतिष्ठा, अधिकार, सार्वजनिक छवि, शासन',
    h11Name: 'एकादश भाव (लाभ)',
    h11Area: 'लाभ, आय, बड़े भाई-बहन, सामाजिक नेटवर्क, आकांक्षाएँ',
    h12Name: 'द्वादश भाव (व्यय)',
    h12Area: 'व्यय, हानि, विदेश, आध्यात्मिकता, मोक्ष',
    generateError: 'कुण्डली बनाने में त्रुटि। कृपया पुनः प्रयास करें।',
    generateErrorRetry: 'कुण्डली बनाने में त्रुटि। कृपया पुनः प्रयास करें।',
    viewFullPoster: 'पूरा पोस्टर देखें',
    shareYourChart: 'चार्ट शेयर करें',
    intensityIntense: 'तीव्र',
    intensityModerate: 'मध्यम',
    intensityMild: 'सौम्य',
    pickSavedChart: 'सहेजी कुण्डली चुनें...',
    orNewDetails: 'या नीचे नए विवरण भरें',
    schemaName: 'वैदिक जन्म कुण्डली कैसे बनाएं',
    schemaDescription: 'अपनी जन्म तिथि, समय और स्थान से सटीक कुण्डली (जन्म पत्रिका) बनाने के लिए चरण-दर-चरण गाइड। Swiss Ephemeris से ग्रह स्थिति, दशाएँ, योग, दोष और 20+ विश्लेषण।',
    schemaStep1Name: 'नाम दर्ज करें',
    schemaStep1Text: 'जिस व्यक्ति की कुण्डली बनानी है उसका नाम दर्ज करें।',
    schemaStep2Name: 'जन्म तिथि और समय दर्ज करें',
    schemaStep2Text: 'सटीक जन्म तिथि और समय दर्ज करें। समय जितना सटीक होगा, लग्न और भाव उतने सही होंगे।',
    schemaStep3Name: 'जन्म स्थान चुनें',
    schemaStep3Text: 'जन्म शहर खोजें और चुनें। अक्षांश, देशांतर और समय क्षेत्र स्वतः निर्धारित होंगे।',
    schemaStep4Name: 'कुण्डली बनाएं',
    schemaStep4Text: '"कुण्डली बनाएं" बटन दबाएं। Swiss Ephemeris द्वारा सटीक ग्रह स्थिति, दशा, योग, दोष और 20+ विश्लेषण टैब तुरन्त प्रदर्शित होंगे।',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickKundaliLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}
