/**
 * Shared label set for /panchang/auspicious sub-route.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/panchang-auspicious-labels-overlay.json`,
 * generated by `scripts/translate-panchang-auspicious-via-gemini.py`.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/panchang-auspicious-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Weekdays (Sunday = 0)
    weekday0: 'Sunday', weekday1: 'Monday', weekday2: 'Tuesday',
    weekday3: 'Wednesday', weekday4: 'Thursday', weekday5: 'Friday',
    weekday6: 'Saturday',
    // H1 + intro
    h1Template: '{CITY} Auspicious & Inauspicious Timings Today — {WEEKDAY}, {DATE}',
    introTemplate: "Today's auspicious and inauspicious time windows for {CITY} on {WEEKDAY}. Includes Abhijit Muhurta, Brahma Muhurta, Amrit Kalam, Rahu Kaal, Yamaganda, and other important muhurtas.",
    // Section headings (with {CITY} placeholder)
    auspiciousSectionTemplate: 'Auspicious Timings ({CITY})',
    inauspiciousSectionTemplate: 'Inauspicious Periods ({CITY})',
    // Table column headers
    colMuhurta: 'Muhurta',
    colPeriod: 'Period',
    colTime: 'Time',
    colDescription: 'Description',
    // Muhurta rows — names + descriptions
    brahmaName: 'Brahma Muhurta',
    brahmaDesc: 'Pre-dawn sacred period (~96 min before sunrise). Ideal for meditation, study, and spiritual practice.',
    abhijitName: 'Abhijit Muhurta',
    abhijitDesc: 'The 8th muhurta of the day — the most auspicious time window. Named after Nakshatra Abhijit (Vega). Ideal for all important activities.',
    abhijitDescWed: 'Abhijit Muhurta is NOT auspicious on Wednesdays. The 8th muhurta of the day is otherwise the most powerful auspicious window.',
    amritKalamName: 'Amrit Kalam',
    amritKalamDesc: 'Nakshatra-based nectar period — the most auspicious window of the day. Perfect for new beginnings, worship, and important decisions.',
    amritKalamDescShort: 'Nakshatra-based nectar period — the most auspicious window of the day.',
    rahuKaalName: 'Rahu Kaal',
    rahuKaalDesc: '~90-minute inauspicious period ruled by Rahu. Avoid new ventures, travel, and important decisions.',
    yamagandaName: 'Yamaganda',
    yamagandaDesc: 'Inauspicious period ruled by Yama, lord of death. Particularly unfavourable for travel.',
    gulikaKaalName: 'Gulika Kaal',
    gulikaKaalDesc: 'Period ruled by Gulika (son of Saturn). Unfavourable for financial decisions and new beginnings.',
    varjyamName: 'Varjyam',
    varjyamDesc: 'Nakshatra-based forbidden period. Avoid all auspicious activities during this window.',
    durMuhurtamName: 'Dur Muhurtam',
    durMuhurtamDesc: 'An inauspicious muhurta. Avoid starting any new work or important activity.',
    // Educational sections
    whatAreHeading: 'What Are Auspicious & Inauspicious Timings?',
    whatArePara: 'In Vedic astrology, each day contains both auspicious and inauspicious time windows. These are calculated based on sunrise, sunset, nakshatra positions, and planetary configurations. Auspicious muhurtas like Abhijit Muhurta and Amrit Kalam are ideal for new ventures, worship, and important decisions. Inauspicious periods like Rahu Kaal, Yamaganda, and Varjyam should be avoided for initiating new activities.',
    abhijitHeading: 'Abhijit Muhurta — The Most Auspicious Time of Day',
    abhijitPara: 'Abhijit Muhurta is the 8th muhurta of the day, falling around midday. Named after the 28th nakshatra Abhijit (the star Vega), it is considered the muhurta of victory and is ideal for all auspicious activities. Note that Abhijit Muhurta is NOT considered auspicious on Wednesdays.',
    rahuYamaGulikaHeading: 'Rahu Kaal, Yamaganda & Gulika Kaal',
    rahuYamaGulikaPara: 'These three major inauspicious periods are derived by dividing the time between sunrise and sunset into 8 equal parts. Rahu Kaal is the most inauspicious — new ventures, contracts, and travel should be avoided. Yamaganda is associated with Yama (lord of death) and is particularly unfavourable for travel. Gulika Kaal is ruled by Gulika, son of Saturn. Each rotates to a different segment of the day depending on the weekday.',
    varjyamAmritHeading: 'Varjyam & Amrit Kalam',
    varjyamAmritPara: 'Varjyam and Amrit Kalam are nakshatra-based time windows. Each nakshatra has a specific ghati span that is varjya (forbidden) and one that is amrit (highly auspicious). Varjyam should be avoided for all auspicious activities, while Amrit Kalam is the most auspicious window of the day — ideal for new beginnings, worship, and important decisions.',
    // Cross-links
    linkTodaysPanchang: "Today's Panchang",
    linkRahuKaal: 'Rahu Kaal',
    linkChoghadiya: 'Choghadiya',
    linkHoraChart: 'Hora Chart',
    linkMuhurtaAi: 'Auspicious Muhurat AI',
    linkFestivalCalendar: 'Festival Calendar',
  },
  hi: {
    weekday0: 'रविवार', weekday1: 'सोमवार', weekday2: 'मंगलवार',
    weekday3: 'बुधवार', weekday4: 'गुरुवार', weekday5: 'शुक्रवार',
    weekday6: 'शनिवार',
    h1Template: '{CITY} के शुभ-अशुभ मुहूर्त आज — {WEEKDAY}, {DATE}',
    introTemplate: 'आज {WEEKDAY} को {CITY} के लिए शुभ और अशुभ समय। अभिजित मुहूर्त, ब्रह्म मुहूर्त, अमृत काल, राहु काल, यमगण्ड और अन्य महत्वपूर्ण मुहूर्तों का विवरण।',
    auspiciousSectionTemplate: 'शुभ मुहूर्त ({CITY})',
    inauspiciousSectionTemplate: 'अशुभ काल ({CITY})',
    colMuhurta: 'मुहूर्त',
    colPeriod: 'काल',
    colTime: 'समय',
    colDescription: 'विवरण',
    brahmaName: 'ब्रह्म मुहूर्त',
    brahmaDesc: 'सूर्योदय से ~96 मिनट पहले का पवित्र काल। ध्यान, अध्ययन और आध्यात्मिक साधना के लिए श्रेष्ठ।',
    abhijitName: 'अभिजित मुहूर्त',
    abhijitDesc: 'दिन का 8वाँ मुहूर्त — सबसे शुभ समय खण्ड। नक्षत्र अभिजित (वेगा) के नाम पर। सभी महत्वपूर्ण कार्यों के लिए उत्तम।',
    abhijitDescWed: 'बुधवार को अभिजित मुहूर्त शुभ नहीं माना जाता। अन्य दिनों में यह दिन का सबसे शक्तिशाली शुभ काल है।',
    amritKalamName: 'अमृत काल',
    amritKalamDesc: 'नक्षत्र-आधारित अमृत काल — दिन का सबसे शुभ खण्ड। नए कार्य, पूजा और महत्वपूर्ण निर्णयों के लिए उत्तम।',
    amritKalamDescShort: 'नक्षत्र-आधारित अमृत काल — दिन का सबसे शुभ खण्ड।',
    rahuKaalName: 'राहु काल',
    rahuKaalDesc: 'राहु द्वारा शासित ~90 मिनट की अशुभ अवधि। नए कार्य, यात्रा और महत्वपूर्ण निर्णय टालें।',
    yamagandaName: 'यमगण्ड',
    yamagandaDesc: 'यम (मृत्यु देव) द्वारा शासित अशुभ काल। यात्रा के लिए विशेष रूप से प्रतिकूल।',
    gulikaKaalName: 'गुलिक काल',
    gulikaKaalDesc: 'शनि-पुत्र गुलिक द्वारा शासित अवधि। वित्तीय निर्णयों और नए कार्यों के लिए प्रतिकूल।',
    varjyamName: 'वर्ज्यम्',
    varjyamDesc: 'नक्षत्र-आधारित अशुभ काल। इस समय शुभ कार्य टालें।',
    durMuhurtamName: 'दुर्मुहूर्त',
    durMuhurtamDesc: 'अशुभ मुहूर्त। नया कार्य या महत्वपूर्ण गतिविधि आरंभ न करें।',
    whatAreHeading: 'शुभ-अशुभ मुहूर्त क्या हैं?',
    whatArePara: 'वैदिक ज्योतिष में प्रत्येक दिन कुछ समय शुभ और कुछ अशुभ माने जाते हैं। ये समय सूर्योदय, सूर्यास्त, नक्षत्र और ग्रहों की स्थिति के आधार पर गणना किए जाते हैं। शुभ मुहूर्त में नए कार्य, पूजा, और महत्वपूर्ण निर्णय लेने चाहिए। अशुभ काल में नए कार्य आरंभ करने से बचना चाहिए।',
    abhijitHeading: 'अभिजित मुहूर्त — दिन का सबसे शुभ समय',
    abhijitPara: 'अभिजित मुहूर्त दिन का 8वाँ मुहूर्त है, जो मध्याह्न के आसपास आता है। इसका नाम 28वें नक्षत्र अभिजित (वेगा तारा) के नाम पर है। यह विजय का मुहूर्त माना जाता है और सभी शुभ कार्यों के लिए उत्तम है। ध्यान दें कि बुधवार को अभिजित मुहूर्त शुभ नहीं माना जाता।',
    rahuYamaGulikaHeading: 'राहु काल, यमगण्ड और गुलिक काल',
    rahuYamaGulikaPara: 'ये तीन प्रमुख अशुभ काल हैं जो सूर्योदय से सूर्यास्त तक के समय को 8 भागों में विभाजित करके निकाले जाते हैं। राहु काल सबसे अशुभ माना जाता है — इसमें नए कार्य, अनुबंध और यात्रा वर्जित हैं। यमगण्ड यम (मृत्यु देव) से संबंधित है और यात्रा के लिए विशेष रूप से प्रतिकूल है। गुलिक काल शनि-पुत्र गुलिक द्वारा शासित है।',
    varjyamAmritHeading: 'वर्ज्यम् और अमृत काल',
    varjyamAmritPara: 'वर्ज्यम् और अमृत काल नक्षत्र-आधारित समय खण्ड हैं। प्रत्येक नक्षत्र में एक विशिष्ट घटी-खण्ड वर्ज्य (निषिद्ध) होता है और एक अमृत (अत्यन्त शुभ) होता है। वर्ज्यम् में शुभ कार्य वर्जित हैं, जबकि अमृत काल दिन का सबसे शुभ समय है — नए कार्य, पूजा और महत्वपूर्ण निर्णयों के लिए आदर्श।',
    linkTodaysPanchang: 'आज का पंचांग',
    linkRahuKaal: 'राहु काल',
    linkChoghadiya: 'चौघड़िया',
    linkHoraChart: 'होरा',
    linkMuhurtaAi: 'शुभ मुहूर्त AI',
    linkFestivalCalendar: 'त्योहार कैलेंडर',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickAuspiciousLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatAuspiciousLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickAuspiciousLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}

export function auspiciousWeekday(idx0to6: number, locale: string): string {
  return pickAuspiciousLabel(`weekday${idx0to6}`, locale);
}
