/**
 * Shared label set for /panchang/[city] sub-route.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/panchang-city-labels-overlay.json`, generated by
 * `scripts/translate-panchang-city-via-gemini.py`.
 *
 * Templates use `{CITY}`/`{STATE}`/`{TZ}`/`{LAT}`/`{LNG}`/`{TITHI}`/
 * `{NAK}`/`{DATE}`/`{SR}` placeholders. The intro paragraph + the
 * About-this-city paragraphs sit out of `msg()` because they need
 * city-specific interpolation.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/panchang-city-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Title / description templates used by generateMetadata
    titleDiasporaTemplate: '{CITY} Panchang Today ({TZ}) — {TITHI}, {NAK} | {DATE}',
    titleDomesticTemplate: '{CITY} Panchang Today — {TITHI}, {NAK} | {DATE}',
    descDiasporaTemplate: 'Daily Vedic Panchang for Hindus in {CITY}. Accurate Tithi, Nakshatra, Muhurta times{TZ_SUFFIX}. Swiss Ephemeris precision.',
    descDomesticTemplate: "Today's Panchang for {CITY}, {STATE} — accurate sunrise, sunset, tithi, nakshatra, yoga, karana, Rahu Kaal, Yamaganda & Gulika timings. Vedic calculations using Lahiri Ayanamsha.",
    tzSuffixTemplate: ' in {TZ}',
    // SEO intro card
    introTemplate: "Today's Panchang for {CITY}, {STATE} — accurate sunrise, sunset, tithi, nakshatra, yoga, and karana timings computed for {CITY}'s exact coordinates ({LAT}, {LNG}). Computed with Swiss Ephemeris (based on NASA JPL DE ephemerides) using Lahiri Ayanamsha (Chitrapaksha) — sub-arcsecond accuracy on planetary positions. This page updates daily with {CITY}'s local timings, including Rahu Kaal, Yamaganda Kaal, and Gulika Kaal — essential for planning auspicious activities.",
    // WhatsApp share
    shareTextTemplate: '{CITY} Panchang Today: {TITHI}, {NAK} | Sunrise {SR}',
    // Calculation Proof block
    calcProofHeader: 'Calculation Proof — How These Values Were Computed',
    calcProofIntroTemplate: "All values computed from {CITY}'s exact coordinates using Swiss Ephemeris precision. No approximations or defaults.",
    calcLatitude: 'Latitude',
    calcLongitude: 'Longitude',
    calcTimezone: 'Timezone',
    calcAyanamsha: 'Ayanamsha',
    calcSunDepression: 'Sun Depression',
    calcTithiFormula: 'Tithi Formula',
    calcRahuKaalRow: 'Rahu Kaal',
    calcRahuKaalFormula: '1/8th of daytime, weekday-indexed segment',
    calcProofFootnote: 'Tithi transitions determined by 30-iteration binary search on Moon-Sun elongation (~1-second precision). Sunrise/sunset via Swiss Ephemeris with atmospheric refraction. See our methodology page for the full pipeline.',
    // Special Yogas
    specialYogasHeading: 'Special Yogas Today',
    // CTA detailed panchang
    ctaSubtextTemplate: 'Planetary positions, Choghadiya, Hora, Disha Shool — everything for {CITY}',
    // About this city
    aboutPara1Template: 'Daily Vedic Panchang for {CITY}, {STATE} — calculated each day for the exact latitude {LAT} and longitude {LNG}. The five limbs of the Panchang — Tithi (lunar day), Vara (weekday), Nakshatra (lunar mansion), Yoga (luni-solar combination), and Karana (half-tithi) — are essential for selecting auspicious timings and daily religious observances.',
    aboutPara2Template: 'All calculations use the Lahiri Ayanamsha (Chitrapaksha), the most widely used ayanamsha in Indian astrology. Sunrise and sunset times are computed for {CITY}\'s geographic coordinates using the {TZ} timezone, accounting for daylight saving transitions where applicable. Rahu Kaal, Yamaganda Kaal, and Gulika Kaal are derived from the classical Vara-based formula.',
    aboutPara3: 'This page is server-rendered and updated daily. For personalized readings including planetary transit effects on your birth chart, use the interactive Panchang with your exact location.',
    // Email CTA
    emailHeadline: 'Get this delivered to your inbox every morning',
    emailSubtext: 'Free account — daily panchang, Rahu Kaal, and rashifal at sunrise',
    emailButtonLabel: 'Sign Up Free',
    // Month abbreviations (for formatTransitionEnd helper)
    monthShort1: 'Jan', monthShort2: 'Feb', monthShort3: 'Mar', monthShort4: 'Apr',
    monthShort5: 'May', monthShort6: 'Jun', monthShort7: 'Jul', monthShort8: 'Aug',
    monthShort9: 'Sep', monthShort10: 'Oct', monthShort11: 'Nov', monthShort12: 'Dec',
  },
  hi: {
    titleDiasporaTemplate: '{CITY} पंचांग आज ({TZ}) — {TITHI}, {NAK} | {DATE}',
    titleDomesticTemplate: '{CITY} पंचांग आज — {TITHI}, {NAK} | {DATE}',
    descDiasporaTemplate: '{CITY} में हिन्दू समुदाय के लिए दैनिक वैदिक पंचांग। सटीक तिथि, नक्षत्र और मुहूर्त समय{TZ_SUFFIX}। स्विस इफेमेरिस सटीकता।',
    descDomesticTemplate: '{CITY}, {STATE} का आज का पंचांग — सटीक सूर्योदय, सूर्यास्त, तिथि, नक्षत्र, योग, करण, राहुकाल, यमगण्ड और गुलिक काल। लाहिरी अयनांश पर आधारित वैदिक गणना।',
    tzSuffixTemplate: ' ({TZ} में)',
    introTemplate: '{CITY}, {STATE} के लिए आज का पंचांग — {CITY} के सटीक निर्देशांक ({LAT}, {LNG}) के अनुसार गणना किए गए सूर्योदय, सूर्यास्त, तिथि, नक्षत्र, योग, और करण का समय। स्विस एफेमेरिस (NASA JPL DE एफेमेरिस पर आधारित) और लाहिरी अयनांश (चित्रपक्ष) से गणना — ग्रह स्थिति पर उप-आर्क-सेकंड सटीकता। यह पृष्ठ प्रतिदिन {CITY} के स्थानीय समय के अनुसार अपडेट होता है, जिसमें राहुकाल, यमगण्ड और गुलिक काल शामिल हैं।',
    shareTextTemplate: '{CITY} पंचांग आज: {TITHI}, {NAK} | सूर्योदय {SR}',
    calcProofHeader: 'गणना प्रमाण — पारदर्शी लेखा परीक्षा',
    calcProofIntroTemplate: 'सभी मान {CITY} के सटीक निर्देशांकों से गणना किए गए हैं। कोई सन्निकटन या डिफ़ॉल्ट नहीं।',
    calcLatitude: 'अक्षांश',
    calcLongitude: 'देशांतर',
    calcTimezone: 'समय क्षेत्र',
    calcAyanamsha: 'अयनांश',
    calcSunDepression: 'सूर्य अवनति',
    calcTithiFormula: 'तिथि सूत्र',
    calcRahuKaalRow: 'राहुकाल सूत्र',
    calcRahuKaalFormula: 'दिन का 1/8 भाग, वार-अनुसार',
    calcProofFootnote: 'तिथि संक्रमण समय 30-पुनरावृत्ति द्विभाजन खोज से निर्धारित, ~1 सेकंड सटीकता। सूर्योदय/सूर्यास्त स्विस एफेमेरिस + वायुमण्डलीय अपवर्तन से। सम्पूर्ण गणना पद्धति के लिए पद्धति पृष्ठ देखें।',
    specialYogasHeading: 'आज के विशेष योग',
    ctaSubtextTemplate: 'ग्रह स्थिति, चौघड़िया, होरा, दिशा शूल — {CITY} के लिए सब कुछ',
    aboutPara1Template: '{CITY} ({STATE}) के लिए दैनिक वैदिक पंचांग — प्रत्येक दिन {CITY} के अक्षांश {LAT} और देशांतर {LNG} के अनुसार सटीक गणना। पंचांग के पाँच अंग — तिथि, वार, नक्षत्र, योग, और करण — शुभ मुहूर्त चयन और दैनिक धार्मिक कृत्यों के लिए अनिवार्य हैं।',
    aboutPara2Template: 'सभी गणनाएँ लाहिरी अयनांश (चित्रपक्ष) पर आधारित हैं, जो भारत के अधिकांश पंचांग कर्ताओं द्वारा प्रयुक्त होता है। सूर्योदय और सूर्यास्त का समय {CITY} के भौगोलिक निर्देशांक और {TZ} समय क्षेत्र के अनुसार गणना किया गया है।',
    aboutPara3: 'यह पृष्ठ सर्वर-रेंडर है और प्रतिदिन अपडेट होता है। अपनी जन्मकुंडली पर ग्रह गोचर के प्रभाव सहित व्यक्तिगत पठन के लिए, अपने सटीक स्थान के साथ इंटरैक्टिव पंचांग का उपयोग करें।',
    emailHeadline: 'हर सुबह ईमेल पर यह पंचांग पाएँ',
    emailSubtext: 'मुफ़्त खाता — सूर्योदय पर दैनिक पंचांग, राहु काल, और राशिफल',
    emailButtonLabel: 'निःशुल्क खाता बनाएँ',
    monthShort1: 'जन.', monthShort2: 'फर.', monthShort3: 'मार्च', monthShort4: 'अप्रै.',
    monthShort5: 'मई', monthShort6: 'जून', monthShort7: 'जुला.', monthShort8: 'अग.',
    monthShort9: 'सित.', monthShort10: 'अक्टू.', monthShort11: 'नव.', monthShort12: 'दिस.',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickPanchangCityLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatPanchangCityLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickPanchangCityLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}

export function panchangCityMonthShort(monthIndex1Based: number, locale: string): string {
  return pickPanchangCityLabel(`monthShort${monthIndex1Based}`, locale);
}
