/**
 * Shared label set for /panchang/date/[date] sub-route.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/panchang-date-labels-overlay.json`, generated by
 * `scripts/translate-panchang-date-via-gemini.py`.
 *
 * `h1Template` and `summaryTemplate` carry `{CITY}`, `{WEEKDAY}`, `{DATE}`,
 * `{TITHI}`, `{NAK}`, `{YOGA}`, `{KARANA}`, `{SUNRISE}`, `{SUNSET}`,
 * `{RK_START}`, `{RK_END}` placeholders.
 *
 * The summary paragraph wraps 5 inline `<Link>` nodes — translation
 * carries the special `[[1]]`..`[[5]]` markers; the page splits the
 * formatted output on those markers and interleaves the 5 anchor texts
 * (`linkText1`..`linkText5`) in their own `<Link>` wrappers.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/panchang-date-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Date nav
    prevDay: 'Previous day',
    today: 'Today',
    nextDay: 'Next day',
    dateNavAria: 'Date navigation',
    relatedPagesAria: 'Related pages',
    // Festival callout
    festivalTodayTemplate: 'Today is {NAME}.',
    seeMuhurat: 'See muhurat',
    // H1 — translation may rearrange word order; placeholders mandatory.
    h1Template: '{CITY} Panchang for {WEEKDAY}, {DATE}',
    // SEO summary paragraph (with [[1]]..[[5]] link markers for Tithi /
    // Nakshatra / Yoga / Karana / Rahu Kaal anchors).
    summaryTemplate: 'In {CITY} on {WEEKDAY}, {DATE} the [[1]] is {TITHI}, [[2]] is {NAK}, [[3]] is {YOGA} and [[4]] is {KARANA}. Sunrise {SUNRISE}, sunset {SUNSET}. [[5]] runs {RK_START}–{RK_END} — avoid starting new auspicious work during this window.',
    linkText1: 'Tithi',
    linkText2: 'Nakshatra',
    linkText3: 'Yoga',
    linkText4: 'Karana',
    linkText5: 'Rahu Kaal',
    // InfoRow labels (single-noun panchang terms)
    rowTithi: 'Tithi',
    rowNakshatra: 'Nakshatra',
    rowYoga: 'Yoga',
    rowKarana: 'Karana',
    rowVara: 'Vara',
    rowSunrise: 'Sunrise',
    rowSunset: 'Sunset',
    rowRahuKaal: 'Rahu Kaal',
    rowAbhijitMuhurta: 'Abhijit Muhurta',
    // Computed-for footnote
    computedForTemplate: 'Computed for {CITY}. For your city, visit the main Panchang page.',
    // Related links
    linkChoghadiyaTemplate: '{DATE} Choghadiya',
    linkTodaysPanchang: "Today's Panchang",
    linkFestivalCalendar: 'Festival Calendar',
    linkKundali: 'Kundali',
  },
  hi: {
    prevDay: 'पिछला दिन',
    today: 'आज',
    nextDay: 'अगला दिन',
    dateNavAria: 'दिनांक नेविगेशन',
    relatedPagesAria: 'सम्बन्धित पृष्ठ',
    festivalTodayTemplate: 'आज {NAME} है।',
    seeMuhurat: 'मुहूर्त देखें',
    h1Template: '{WEEKDAY}, {DATE} को {CITY} पंचांग',
    summaryTemplate: '{CITY} में {WEEKDAY}, {DATE} को [[1]] {TITHI}, [[2]] {NAK}, [[3]] {YOGA} और [[4]] {KARANA} है। सूर्योदय {SUNRISE}, सूर्यास्त {SUNSET}। [[5]] {RK_START} से {RK_END}, इस दौरान नए शुभ कार्य न आरम्भ करें।',
    linkText1: 'तिथि',
    linkText2: 'नक्षत्र',
    linkText3: 'योग',
    linkText4: 'करण',
    linkText5: 'राहु काल',
    rowTithi: 'तिथि',
    rowNakshatra: 'नक्षत्र',
    rowYoga: 'योग',
    rowKarana: 'करण',
    rowVara: 'वार',
    rowSunrise: 'सूर्योदय',
    rowSunset: 'सूर्यास्त',
    rowRahuKaal: 'राहु काल',
    rowAbhijitMuhurta: 'अभिजित मुहूर्त',
    computedForTemplate: '{CITY} के लिए गणना। अपने शहर के अनुसार पंचांग देखने के लिए मुख्य पंचांग पेज पर जाएँ।',
    linkChoghadiyaTemplate: '{DATE} का चौघड़िया',
    linkTodaysPanchang: 'आज का पंचांग',
    linkFestivalCalendar: 'त्योहार कैलेंडर',
    linkKundali: 'कुंडली',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickPanchangDateLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatPanchangDateLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickPanchangDateLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}
