/**
 * Shared label set for /panchang (root page + PanchangClient).
 *
 * Authored locales: en, hi, sa.
 * Gemini-translated overlay (mai, mr, ta, te, kn, gu, bn) lives in
 * `src/lib/constants/panchang-page-labels-overlay.json`, generated by
 * `scripts/translate-panchang-page-via-gemini.py`.
 *
 * Resolution order at runtime:
 *   1. AUTHORED[locale]?.[key]
 *   2. OVERLAY[locale]?.[key]
 *   3. AUTHORED.hi?.[key]    (Indo-Aryan fallback)
 *   4. AUTHORED.en[key]
 *
 * Templates use `{NAME}` placeholders substituted by formatPanchangLabel.
 */
import overlay from '@/lib/constants/panchang-page-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Navigation chrome
    generateKundali: 'Generate Kundali',
    festivalCalendar: 'Festival Calendar',
    muhuratCalendar: 'Muhurat Calendar',
    planetaryTransits: 'Planetary Transits',
    choghadiya: 'Choghadiya',
    rahuKaal: 'Rahu Kaal',
    dailyHoroscope: 'Daily Horoscope',
    babyNames: 'Baby Names',
    tomorrowsPanchang: "Tomorrow's Panchang",
    // Nakshatra-activity guidance heading
    todaysGuidance: "Today's Guidance",
    // Auspiciousness labels
    auspicious: 'auspicious',
    moderatelyAuspicious: 'moderately auspicious',
    // Direct-answer paragraphs (templates)
    snippetIntro: 'This {VARA} brings {TITHI} Tithi under {NAK} Nakshatra, with {YOGA} Yoga.',
    snippetActivities: 'The day is {AUSP} — {NAK} favors {ACTIVITIES}.',
    snippetActivitiesFallback: 'general activities',
    snippetRahu: 'Rahu Kaal runs {START}–{END}; hold off on new beginnings during that window.',
    // Why-Five-Elements section
    whyFiveElementsHeading: 'Why Five Elements?',
    whyFiveElementsPara1Pre: 'The Panchang (pancha + anga = five limbs) captures the five — and only five — observable relationships between the Sun, Moon, and the cosmos. Tithi measures the Sun-Moon angular separation (see year-round dates for ',
    whyFiveElementsPara1Sep: ', ',
    whyFiveElementsPara1And: ', and ',
    whyFiveElementsPara1Post: '). Nakshatra tracks the Moon against the fixed stars. Yoga combines the solar and lunar longitudes. Karana divides the tithi into finer pulses. Vara (weekday) follows the planetary hour sequence.',
    whyFiveElementsPara2: 'These are not arbitrary divisions — they are the complete set of independent astronomical observables in this three-body system. The ancient astronomers did not choose five — five is all there is. Each calculation is computed from real planetary positions using Surya Siddhanta algorithms, whose precision modern instruments have confirmed.',
    // Popular Cities section
    panchangByCity: 'Panchang by City',
    panchangByCityIntro: 'View accurate sunrise, sunset, tithi, nakshatra, and Rahu Kaal timings for your city.',
    indianCities: 'Indian Cities',
    internationalCities: 'International Cities',
    viewAll800Cities: 'View all 800+ cities →',
    // Tithi anomalies (PanchangClient)
    kshayaTithi: 'Kshaya Tithi',
    vriddhiTithi: 'Vriddhi Tithi',
    spansTwoSunrises: 'spans two sunrises',
    more: 'more',
  },
  hi: {
    generateKundali: 'कुंडली बनाएं',
    festivalCalendar: 'त्योहार कैलेंडर',
    muhuratCalendar: 'मुहूर्त कैलेंडर',
    planetaryTransits: 'ग्रह गोचर',
    choghadiya: 'चौघड़िया',
    rahuKaal: 'राहु काल',
    dailyHoroscope: 'राशिफल',
    babyNames: 'शिशु नाम',
    tomorrowsPanchang: 'कल का पंचांग',
    todaysGuidance: 'आज का मार्गदर्शन',
    auspicious: 'शुभ',
    moderatelyAuspicious: 'सामान्य',
    snippetIntro: 'इस {VARA} को तिथि {TITHI}, नक्षत्र {NAK}, और योग {YOGA} है।',
    snippetActivities: 'दिन {AUSP} है — {NAK} नक्षत्र {ACTIVITIES} के लिए अनुकूल रहता है।',
    snippetActivitiesFallback: 'सामान्य कार्यों',
    snippetRahu: 'राहु काल {START} से {END} तक रहेगा, इस दौरान नए शुभ कार्य न आरम्भ करें।',
    whyFiveElementsHeading: 'पाँच तत्व क्यों?',
    whyFiveElementsPara1Pre: 'पंचांग (पञ्च + अङ्ग = पाँच अंग) सूर्य, चन्द्रमा और ब्रह्माण्ड के बीच पाँच — और केवल पाँच — प्रेक्षणीय सम्बन्धों को पकड़ता है। तिथि सूर्य-चन्द्र कोणीय अन्तर मापती है (वर्ष-वार सूची देखें: ',
    whyFiveElementsPara1Sep: ', ',
    whyFiveElementsPara1And: ', ',
    whyFiveElementsPara1Post: ')। नक्षत्र स्थिर तारों के सापेक्ष चन्द्रमा को ट्रैक करता है। योग सूर्य और चन्द्र के देशान्तरों को संयोजित करता है। करण तिथि को सूक्ष्मतर स्पन्दनों में विभाजित करता है। वार (सप्ताह दिवस) ग्रह होरा क्रम का पालन करता है।',
    whyFiveElementsPara2: 'ये मनमाने विभाजन नहीं हैं — ये इस त्रिकाय प्रणाली में स्वतन्त्र खगोलीय प्रेक्षणों का सम्पूर्ण समुच्चय हैं। प्राचीन खगोलविदों ने पाँच नहीं चुने — पाँच ही सम्भव हैं। प्रत्येक गणना सूर्य सिद्धान्त के एल्गोरिदम पर आधारित है, जिनकी सटीकता आधुनिक उपकरणों ने पुष्ट की है।',
    panchangByCity: 'शहर के अनुसार पंचांग',
    panchangByCityIntro: 'अपने शहर के लिए सटीक सूर्योदय, सूर्यास्त, तिथि, नक्षत्र और राहु काल का समय देखें।',
    indianCities: 'भारतीय शहर',
    internationalCities: 'अंतर्राष्ट्रीय शहर',
    viewAll800Cities: 'सभी 800+ शहर देखें →',
    kshayaTithi: 'क्षय तिथि',
    vriddhiTithi: 'वृद्धि तिथि',
    spansTwoSunrises: 'दो सूर्योदय तक',
    more: 'और',
  },
  // sa retired (HTTP 410) but a couple of legacy crawls may still hit it.
  // Inherit hi text for chrome; the SEO surface is en/hi/9-locale.
  sa: {
    generateKundali: 'कुण्डली रचना',
    festivalCalendar: 'पर्व पञ्चाङ्ग',
    muhuratCalendar: 'मुहूर्त पञ्चाङ्ग',
    planetaryTransits: 'ग्रह गोचरम्',
    choghadiya: 'चौघडिया',
    rahuKaal: 'राहु कालः',
    dailyHoroscope: 'राशिफलम्',
    babyNames: 'शिशुनामानि',
    tomorrowsPanchang: 'श्वः पञ्चाङ्गम्',
    todaysGuidance: 'अद्यतनं मार्गदर्शनम्',
    auspicious: 'शुभम्',
    moderatelyAuspicious: 'सामान्यम्',
    snippetIntro: 'अस्मिन् {VARA} वासरे {TITHI} तिथिः {NAK} नक्षत्रे {YOGA} योगे च।',
    snippetActivities: 'दिनं {AUSP} — {NAK} नक्षत्रं {ACTIVITIES} कार्येषु अनुकूलम्।',
    snippetActivitiesFallback: 'सामान्यकार्येषु',
    snippetRahu: 'राहुकालः {START} तः {END} पर्यन्तं भविष्यति; एतस्मिन् काले नूतनशुभकार्याणि न आरभेत्।',
    whyFiveElementsHeading: 'पञ्च अङ्गानि कुतः?',
    whyFiveElementsPara1Pre: 'पञ्चाङ्गं (पञ्च + अङ्गम् = पञ्च अङ्गानि) सूर्य-चन्द्र-ब्रह्माण्डयोः मध्ये पञ्च प्रेक्षणीय-सम्बन्धान् गृह्णाति। तिथिः सूर्य-चन्द्र-कोणीयान्तरं मापयति (दृश्यतां ',
    whyFiveElementsPara1Sep: ', ',
    whyFiveElementsPara1And: ', ',
    whyFiveElementsPara1Post: ')। नक्षत्रं स्थिरतारकाभ्यः सापेक्षं चन्द्रं ट्रकति। योगः सूर्य-चन्द्र-देशान्तरयोः योगम्। करणं तिथिं सूक्ष्मेषु स्पन्देषु विभजति। वारः ग्रहहोराक्रमं पालयति।',
    whyFiveElementsPara2: 'एते स्वैरविभागाः न सन्ति — एते अस्मिन् त्रिकाये स्वतन्त्रखगोलीयप्रेक्षणानां सम्पूर्णसमुच्चयाः। प्राचीनखगोलविदः पञ्च न अचयित्वा अकरोत्, पञ्च एव सम्भवाः। प्रत्येकगणना सूर्यसिद्धान्तस्य आल्गोरिदमेषु आश्रिता।',
    panchangByCity: 'नगरानुसारं पञ्चाङ्गम्',
    panchangByCityIntro: 'भवतः नगरस्य कृते सटीकं सूर्योदय-सूर्यास्त-तिथि-नक्षत्र-राहुकाल-समयं पश्यन्तु।',
    indianCities: 'भारतीयनगराणि',
    internationalCities: 'अन्तरराष्ट्रीयनगराणि',
    viewAll800Cities: 'सर्वाणि 800+ नगराणि पश्यन्तु →',
    kshayaTithi: 'क्षयतिथिः',
    vriddhiTithi: 'वृद्धितिथिः',
    spansTwoSunrises: 'द्वौ सूर्योदयौ अधिकरोति',
    more: 'अधिकम्',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickPanchangLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi?.[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatPanchangLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickPanchangLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}
