/**
 * Shared chrome label set for ALL /calendar/regional/<slug> pages.
 *
 * These keys appear identically across every regional page (month/rashi/
 * Gregorian table column headers, the "Related Regional Calendars"
 * section heading, and link labels for the 8 other regional pages).
 * Centralising avoids duplicating ~10 keys × 9 locales = 90 strings
 * across 9 nearly-identical regional landing pages.
 *
 * Page-specific prose (intro paragraph, month-name lists, festival
 * descriptions, calendar-characteristics body) stays in each page's
 * own LABELS dict — those texts ARE region-specific and don't repeat.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/regional-chrome-labels-overlay.json`, generated by
 * `scripts/translate-regional-chrome-via-gemini.py`.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/regional-chrome-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    // Table column headers (shared across every regional months table)
    colMonth: 'Month',
    colRashi: 'Rashi (Zodiac)',
    colGregorian: 'Gregorian',
    // Related Regional Calendars cross-links section
    relatedHeading: 'Related Regional Calendars',
    linkTamil: 'Tamil Calendar (Panchangam)',
    linkTelugu: 'Telugu Calendar (Panchangam)',
    linkKannada: 'Kannada Calendar (Panchangam)',
    linkMalayalam: 'Malayalam Calendar (Kollavarsham)',
    linkBengali: 'Bengali Calendar (Bangabda)',
    linkGujarati: 'Gujarati Calendar (Vikram Samvat)',
    linkOdia: 'Odia Calendar (Panji)',
    linkMithila: 'Mithila Panchang (Maithili Tirhuta)',
    linkFestivalCalendar: 'Festival Calendar 2026',
  },
  hi: {
    colMonth: 'मास',
    colRashi: 'राशि',
    colGregorian: 'ग्रेगोरियन',
    relatedHeading: 'सम्बन्धित कैलेंडर',
    linkTamil: 'तमिल कैलेंडर',
    linkTelugu: 'तेलुगु कैलेंडर',
    linkKannada: 'कन्नड़ कैलेंडर',
    linkMalayalam: 'मलयालम कैलेंडर',
    linkBengali: 'बंगाली कैलेंडर',
    linkGujarati: 'गुजराती कैलेंडर',
    linkOdia: 'ओड़िया कैलेंडर',
    linkMithila: 'मिथिला पंचांग',
    linkFestivalCalendar: 'त्योहार कैलेंडर 2026',
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickRegionalChrome(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}
