/**
 * Shared label set for standalone tool/explainer pages:
 * /dates/[category], /sade-sati, /matching, /vedic-time, /upagraha,
 * /gauri-panchang, /hora.
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/tool-pages-labels-overlay.json`.
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/tool-pages-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    somvatiAmavasya: "Somvati Amavasya",
    shaniAmavasya: "Shani Amavasya",
    diwaliAmavasya: "Diwali Amavasya",
    mauniAmavasya: "Mauni Amavasya",
    amavasya: "Amavasya",
    shaniPradosham: "Shani Pradosham",
    somaPradosham: "Soma Pradosham",
    pradosham: "Pradosham",
    sankashtiChaturthi: "Sankashti Chaturthi",
    vinayakaChaturthi: "Vinayaka Chaturthi",
    date: "Date",
    day: "Day",
    hinduMonth: "Hindu Month",
    paksha: "Paksha",
    nameSignificance: "Name / Significance",
    shukla: "Shukla",
    krishna: "Krishna",
    saturnTransit2026: "Saturn Transit 2026",
    saturnTransitSchedule2023u20132032: "Saturn Transit Schedule (2023\\u20132032)",
    sign: "Sign",
    enters: "Enters",
    exits: "Exits",
    whichMoonSignsAre: "Which Moon Signs Are Currently in Sade Sati?",
    risingPhase: "Rising Phase",
    financialPressureHiddenAnxieties: "Financial pressure, hidden anxieties",
    peakPhase: "Peak Phase",
    mostIntenseU2014Mental: "Most intense \\u2014 mental pressure, transformation",
    settingPhase: "Setting Phase",
    familyMattersSpeechrelatedIssues: "Family matters, speech-related issues",
    learnAboutGrahasU2192: "Learn about Grahas \\u2192",
    generateBirthChartU2192: "Generate Birth Chart \\u2192",
    kuta: "Kuta",
    points: "Points",
    whatItMeasures: "What It Measures",
    rashiCompatibilityChartU2192: "Rashi Compatibility Chart \\u2192",
    learnAboutMatchingU2192: "Learn about Matching \\u2192",
    learnAboutNakshatrasU2192: "Learn about Nakshatras \\u2192",
    theAncientIndianTime: "The ancient Indian time system — Ghati, Pala, Muhurta, Prahar. The Vedic day begins at sunrise and is divided into 60 Ghatis, 30 Muhurtas, and 8 Prahars.",
    whatIsVedicTime: "What is Vedic Time?",
    theVedicTimeSystem: "The Vedic time system is an ancient Indian method of time measurement described in the Surya Siddhanta and other astronomical texts. Unlike the modern 24-hour clock which starts at midnight, the Vedic day begins at sunrise. This means Ghati-Pala timings shift every day and by location, because sunrise varies with season and latitude.",
    theFundamentalUnitIs: "The fundamental unit is the \"Ghati\" (or \"Nadika\"), equal to 24 modern minutes. Each Ghati contains 60 Palas (each 24 seconds). Sixty Ghatis make one Ahoratra (full day-night cycle). These units were measured using water clocks (Ghati Yantra) — a copper vessel with a small hole through which water flowed at a calibrated rate.",
    theGhatiSystem: "The Ghati System",
    theGhatiSystemIs: "The Ghati system is sexagesimal (base-60), mirroring the modern convention of 60 seconds = 1 minute, 60 minutes = 1 hour. In the Vedic system: 60 Palas = 1 Ghati, 60 Ghatis = 1 day. This likely reflects an ancient mathematical connection between Sumerian and Indian civilisations. The Muhurta (2 Ghatis = 48 minutes) and Prahar (7.5 Ghatis = 3 hours) are larger units used for daily rituals and ceremonies.",
    inJyotishTheMuhurta: "In Jyotish, the Muhurta is of special significance. Each of the day\\",
    vedicTimeConversionTable: "Vedic Time Conversion Table",
    vedicUnit: "Vedic Unit",
    duration: "Duration",
    perDay: "Per Day",
    description: "Description",
    _30MuhurtasOfThe: "30 Muhurtas of the Day",
    eachMuhurtaSpans48: "Each Muhurta spans 48 minutes. Starting from sunrise, 15 belong to the daytime and 15 to nighttime. Auspicious Muhurtas are marked green, inauspicious in red.",
    keyRelationships: "Key Relationships",
    practicalUseToday: "Practical Use Today",
    vedicTimeUnitsAre: "Vedic time units are still used in Muhurta Shastra (electional astrology), Panchang computation, Hora charts, and astrological consultations. When selecting auspicious times for weddings, housewarming (Griha Pravesh), or naming ceremonies, timings are often given in Ghati-Pala notation. Every Panchang records tithi, nakshatra, and yoga start/end times in Ghati-Pala format.",
    theInteractiveToolBelow: "The interactive tool below shows the current Vedic time (Ghati, Pala, Vipala), running Muhurta, and Prahar based on your location\\",
    horaChart: "Hora Chart",
    choghadiya: "Choghadiya",
    auspiciousMuhurat: "Auspicious Muhurat",
    upagraha: "Upagraha",
    degrees: "Degrees",
    nature: "Nature",
    malefic: "Malefic",
    benefic: "Benefic",
    mixed: "Mixed",
    detailedUpagrahaGuide: "Detailed Upagraha Guide",
    effects: "Effects: ",
    calculationMethod: "Calculation Method",
    gulikaMandiIsComputed: "Gulika (Mandi) is computed differently -- from Saturn\\",
    rahuKaal: "Rahu Kaal",
    vedicTime: "Vedic Time",
    kundali: "Kundali",
    gauriPeriod: "Gauri Period",
    time: "Time",
    gauriPanchangSlotsAre: "Gauri Panchang slots are computed from sunrise and sunset, so timings vary by city. Use the interactive tool below to select your location for precise Gowri Nalla Neram timings.",
    whatIsGauriPanchang: "What is Gauri Panchang?",
    gauriPanchangGowriNalla: "Gauri Panchang (Gowri Nalla Neram) is a Vedic time-division system widely used across South India — Tamil Nadu, Karnataka, Andhra Pradesh, Telangana and Kerala. It is the South-Indian counterpart of Choghadiya, which is more common in North India. Each day and night is divided into 8 equal parts, yielding 16 named periods in total.",
    theEightGauriPeriods: "The Eight Gauri Periods",
    theEightPeriodsAre: "The eight periods are: Amritha (nectar, most auspicious), Siddha (achievement), Laabha (gain), Dhanam (wealth), Sugam (comfort) — five auspicious; and Marana (death), Rogam (disease), Sokam (sorrow) — three inauspicious. Unlike Choghadiya, Gauri has no \"neutral\" tier — every period is either clearly auspicious or inauspicious.",
    howIsGauriPanchang: "How is Gauri Panchang Calculated?",
    dayGauriTheTime: "Day Gauri: the time between sunrise and sunset is divided into 8 equal parts (each ~90 minutes). Night Gauri: sunset to next sunrise, also 8 parts. The starting period rotates by weekday — Sunday starts with Sokam, Monday with Amritha (the Moon\\",
    gauriPanchangVsChoghadiya: "Gauri Panchang vs Choghadiya",
    bothAreVedicTimedivision: "Both are Vedic time-division systems, but they differ: (1) Gauri has 8 distinct period names; Choghadiya has 7 (Char repeats). (2) Gauri has no \"neutral\" category — every period is auspicious or inauspicious. (3) The weekday rotation is different — weekdays start with different periods. (4) Gauri is the traditional South-Indian system; Choghadiya is more common in Gujarat, Rajasthan, and Madhya Pradesh.",
    auspiciousTimings: "Auspicious Timings",
    learnMore: "Learn More",
    horaSlotsAreCalculated: "Hora slots are calculated from sunrise and sunset, so times vary by city. Use the interactive tool below to select your city.",
    planet: "Planet",
    bestFor: "Best For",
    whatIsHora: "What is Hora?",
    horaIsTheVedic: "Hora is the Vedic astrology system of planetary hours. Each day and night is divided into 12 horas each, totalling 24 horas per day. Each hora is ruled by one of the seven classical planets (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn) in the \"Chaldean order\" — planets ordered by their orbital period from slowest to fastest.",
    whichHoraIsGood: "Which Hora is Good for Which Activity?",
    sunHoraGovernmentWork: "Sun Hora: government work, authority, health matters. Moon Hora: travel, public relations, creative work. Mars Hora: property, legal matters, surgery, courageous acts. Mercury Hora: education, communication, writing, trade. Jupiter Hora: finance, teaching, religious ceremonies, marriage (most auspicious). Venus Hora: arts, entertainment, romance, luxury purchases. Saturn Hora: agriculture, iron/steel work, disciplined labour.",
    howIsHoraCalculated: "How is Hora Calculated?",
    dayHorasSunriseTo: "Day horas: sunrise to sunset divided into 12 equal parts. Night horas: sunset to next sunrise divided into 12 parts. The first hora belongs to the weekday lord (Sunday = Sun, Monday = Moon, etc.). Subsequent horas follow the Chaldean sequence: Saturn → Jupiter → Mars → Sun → Venus → Mercury → Moon, cycling repeatedly.",
    muhuratAi: "Muhurat AI",
    festivalCalendar: "Festival Calendar",
  },
  hi: {
    somvatiAmavasya: "सोमवती अमावस्या",
    shaniAmavasya: "शनि अमावस्या",
    diwaliAmavasya: "दीपावली अमावस्या",
    mauniAmavasya: "मौनी अमावस्या",
    amavasya: "अमावस्या",
    shaniPradosham: "शनि प्रदोष",
    somaPradosham: "सोम प्रदोष",
    pradosham: "प्रदोष",
    sankashtiChaturthi: "संकष्टी चतुर्थी",
    vinayakaChaturthi: "विनायक चतुर्थी",
    date: "तारीख",
    day: "वार",
    hinduMonth: "हिन्दू मास",
    paksha: "पक्ष",
    nameSignificance: "विशेष / नाम",
    shukla: "शुक्ल",
    krishna: "कृष्ण",
    saturnTransit2026: "शनि गोचर 2026",
    saturnTransitSchedule2023u20132032: "शनि गोचर अनुसूची (2023-2032)",
    sign: "राशि",
    enters: "प्रवेश",
    exits: "निर्गमन",
    whichMoonSignsAre: "वर्तमान में कौन सी चन्द्र राशियाँ प्रभावित हैं?",
    risingPhase: "उदय चरण",
    financialPressureHiddenAnxieties: "आर्थिक दबाव, छिपी चिन्ताएँ",
    peakPhase: "चरम चरण",
    mostIntenseU2014Mental: "सर्वाधिक तीव्र — मानसिक दबाव, परिवर्तन",
    settingPhase: "अवसान चरण",
    familyMattersSpeechrelatedIssues: "पारिवारिक विषय, वाणी सम्बन्धी",
    learnAboutGrahasU2192: "ग्रह के बारे में जानें \\u2192",
    generateBirthChartU2192: "कुण्डली बनाएँ \\u2192",
    kuta: "कूट",
    points: "अंक",
    whatItMeasures: "विवरण",
    rashiCompatibilityChartU2192: "राशि संगतता चार्ट \\u2192",
    learnAboutMatchingU2192: "गुण मिलान के बारे में जानें \\u2192",
    learnAboutNakshatrasU2192: "नक्षत्रों के बारे में जानें \\u2192",
    theAncientIndianTime: "प्राचीन भारतीय समय पद्धति — घटी, पल, मुहूर्त, प्रहर। वैदिक दिन सूर्योदय से प्रारम्भ होता है और 60 घटियों, 30 मुहूर्तों और 8 प्रहरों में विभाजित होता है।",
    whatIsVedicTime: "वैदिक समय क्या है?",
    theVedicTimeSystem: "वैदिक समय पद्धति सूर्य सिद्धान्त और अन्य ज्योतिष ग्रन्थों में वर्णित प्राचीन भारतीय समय मापन प्रणाली है। आधुनिक 24-घण्टे की घड़ी के विपरीत, वैदिक दिन अर्धरात्रि से नहीं बल्कि सूर्योदय से प्रारम्भ होता है। इसका अर्थ है कि घटी-पल का समय प्रत्येक दिन और स्थान के अनुसार बदलता है क्योंकि सूर्योदय का समय ऋतु और अक्षांश पर निर्भर करता है।",
    theFundamentalUnitIs: "इस प्रणाली की मूल इकाई \"घटी\" (या \"नाडिका\") है जो 24 आधुनिक मिनटों के बराबर है। प्रत्येक घटी में 60 पल (प्रत्येक 24 सेकन्ड) होते हैं। 60 घटियाँ मिलकर एक अहोरात्र (पूर्ण दिवस-रात्रि चक्र) बनाती हैं। जल-घड़ी (घटी यन्त्र) से इन इकाइयों को मापा जाता था — तांबे के पात्र में छोटा छेद करके जल के प्रवाह से समय मापन होता था।",
    theGhatiSystem: "घटी पद्धति",
    theGhatiSystemIs: "घटी प्रणाली का आधार षष्टि (60) है — ठीक वैसे ही जैसे आधुनिक कालगणना में 60 सेकन्ड = 1 मिनट और 60 मिनट = 1 घण्टा। 60 पल = 1 घटी, 60 घटी = 1 दिन। यह सम्भवतः सुमेरी और भारतीय सभ्यताओं के बीच प्राचीन गणितीय सम्बन्ध को दर्शाता है। मुहूर्त (2 घटी = 48 मिनट) और प्रहर (7.5 घटी = 3 घण्टे) बड़ी इकाइयाँ हैं जो दैनिक अनुष्ठानों और कर्मकाण्डों के लिए प्रयुक्त होती हैं।",
    inJyotishTheMuhurta: "ज्योतिष शास्त्र में मुहूर्त का विशेष महत्व है। दिन के 30 मुहूर्तों में से प्रत्येक का एक अधिष्ठाता देवता और गुण (शुभ/अशुभ) है। अभिजित मुहूर्त (दिन का मध्य मुहूर्त, लगभग दोपहर 11:36 से 12:24) सभी शुभ कार्यों के लिए सर्वश्रेष्ठ माना जाता है — बुधवार को छोड़कर जब इसका प्रभाव कम होता है।",
    vedicTimeConversionTable: "वैदिक समय रूपान्तरण तालिका",
    vedicUnit: "वैदिक इकाई",
    duration: "अवधि",
    perDay: "प्रति दिन",
    description: "विवरण",
    _30MuhurtasOfThe: "दिन के 30 मुहूर्त",
    eachMuhurtaSpans48: "प्रत्येक मुहूर्त 48 मिनट का होता है। सूर्योदय से प्रारम्भ होकर 15 दिन के और 15 रात्रि के मुहूर्त होते हैं। शुभ मुहूर्तों को हरे और अशुभ को लाल रंग से दर्शाया गया है।",
    keyRelationships: "प्रमुख सम्बन्ध",
    practicalUseToday: "व्यावहारिक उपयोग",
    vedicTimeUnitsAre: "आज भी वैदिक समय का उपयोग मुहूर्त शास्त्र (शुभ समय चयन), पंचांग गणना, होरा चार्ट और ज्योतिषीय परामर्श में होता है। विवाह, गृहप्रवेश, नामकरण जैसे संस्कारों के लिए मुहूर्त निकालते समय घटी-पल में समय दिया जाता है। पंचांग में प्रत्येक तिथि, नक्षत्र और योग का प्रारम्भ और समाप्ति घटी-पल में अंकित होता है।",
    theInteractiveToolBelow: "नीचे दिया गया इण्टरैक्टिव उपकरण आपके स्थान के सूर्योदय के आधार पर वर्तमान वैदिक समय (घटी, पल, विपल), चालू मुहूर्त और प्रहर दिखाता है। यह प्रत्येक सेकन्ड अपडेट होता है।",
    horaChart: "होरा",
    choghadiya: "चौघड़िया",
    auspiciousMuhurat: "शुभ मुहूर्त",
    upagraha: "उपग्रह",
    degrees: "अंश",
    nature: "प्रकृति",
    malefic: "पापी",
    benefic: "शुभ",
    mixed: "मिश्र",
    detailedUpagrahaGuide: "उपग्रहों का विस्तृत विवरण",
    effects: "प्रभाव: ",
    calculationMethod: "गणना विधि",
    gulikaMandiIsComputed: "गुलिक (मान्दि) की गणना भिन्न है -- यह शनि के दैनिक भाग से निकलता है। सूर्योदय से सूर्यास्त तक के समय को 8 भागों में बाँटा जाता है, प्रत्येक भाग पर एक ग्रह का शासन होता है। शनि का भाग गुलिक काल है। उस समय पर लग्न (उदय राशि) ही गुलिक की राशि और अंश है।",
    rahuKaal: "राहु काल",
    vedicTime: "वैदिक समय",
    kundali: "कुण्डली",
    gauriPeriod: "गौरी पंचांग",
    time: "समय",
    gauriPanchangSlotsAre: "गौरी पंचांग सूर्योदय और सूर्यास्त के आधार पर गणना किया जाता है, इसलिए प्रत्येक शहर के लिए समय भिन्न होता है। नीचे इंटरैक्टिव टूल में अपना शहर चुनें।",
    whatIsGauriPanchang: "गौरी पंचांग क्या है?",
    gauriPanchangGowriNalla: "गौरी पंचांग (गौरी नल्ल नेरम) दक्षिण भारत में — तमिलनाडु, कर्नाटक, आंध्र प्रदेश, तेलंगाना और केरल — व्यापक रूप से प्रयुक्त वैदिक काल-विभाजन प्रणाली है। यह उत्तरी भारत में प्रचलित चौघड़िया का दक्षिण भारतीय समकक्ष है। प्रत्येक दिन और रात को 8 बराबर भागों में बाँटा जाता है, कुल 16 काल-खण्ड।",
    theEightGauriPeriods: "गौरी पंचांग के आठ काल",
    theEightPeriodsAre: "अमृत (अत्यन्त शुभ — अमृत), सिद्ध (कार्य-सिद्धि), लाभ (लाभ), धन (धन), सुगम (सुख-सुविधा) — ये पाँच शुभ गौरी काल हैं। मरण (मृत्यु-सूचक), रोग (रोग), शोक (दुःख) — ये तीन अशुभ हैं। चौघड़िया की भाँति कोई \"चर\" (तटस्थ) काल नहीं — गौरी में प्रत्येक काल शुभ या अशुभ।",
    howIsGauriPanchang: "गौरी पंचांग की गणना कैसे होती है?",
    dayGauriTheTime: "दिन का गौरी: सूर्योदय से सूर्यास्त तक के समय को 8 बराबर भागों में बाँटा जाता है (प्रत्येक लगभग 90 मिनट)। रात का गौरी: सूर्यास्त से अगले दिन के सूर्योदय तक 8 भागों में। प्रत्येक वार के लिए प्रारम्भिक काल अलग होता है — यह उस वार के ग्रह स्वामी पर निर्भर करता है।",
    gauriPanchangVsChoghadiya: "गौरी पंचांग और चौघड़िया में अंतर",
    bothAreVedicTimedivision: "दोनों ही वैदिक काल-विभाजन प्रणालियाँ हैं, परन्तु अंतर हैं: (1) गौरी में 8 भिन्न काल-नाम, चौघड़िया में 7 (चर दो बार)। (2) गौरी में कोई \"तटस्थ\" वर्ग नहीं। (3) गौरी का वार-चक्र अलग है। (4) गौरी दक्षिण भारत की पारम्परिक प्रणाली; चौघड़िया उत्तर-पश्चिम भारत में अधिक प्रचलित।",
    auspiciousTimings: "शुभ मुहूर्त",
    learnMore: "विस्तृत जानकारी",
    horaSlotsAreCalculated: "होरा सूर्योदय और सूर्यास्त के आधार पर गणना किए जाते हैं। प्रत्येक शहर के लिए समय भिन्न होता है। नीचे इंटरैक्टिव टूल में अपना शहर चुनें।",
    planet: "ग्रह",
    bestFor: "उपयुक्त कार्य",
    whatIsHora: "होरा क्या है?",
    horaIsTheVedic: "होरा (Hora) वैदिक ज्योतिष में ग्रहों के घंटों की प्रणाली है। दिन और रात को 12-12 होरा में विभाजित किया जाता है, कुल 24 होरा प्रतिदिन। प्रत्येक होरा एक ग्रह (सूर्य, चन्द्र, मंगल, बुध, गुरु, शुक्र, शनि) द्वारा शासित होता है। यह \"कैल्डियन क्रम\" (Chaldean order) पर आधारित है — ग्रहों को उनकी कक्षीय अवधि के अनुसार क्रमबद्ध किया गया है।",
    whichHoraIsGood: "कौन सा होरा किस कार्य के लिए?",
    sunHoraGovernmentWork: "सूर्य होरा: सरकारी कार्य, अधिकार और स्वास्थ्य। चन्द्र होरा: यात्रा, जनसंपर्क और रचनात्मकता। मंगल होरा: संपत्ति, कानूनी विवाद और साहसिक कार्य। बुध होरा: शिक्षा, संचार, लेखन और व्यापार। गुरु होरा: वित्त, धार्मिक कार्य और विवाह (सबसे शुभ)। शुक्र होरा: कला, मनोरंजन, प्रेम और विलासिता। शनि होरा: कृषि, लोहा/इस्पात कार्य और श्रम।",
    howIsHoraCalculated: "होरा की गणना कैसे होती है?",
    dayHorasSunriseTo: "दिन के 12 होरा: सूर्योदय से सूर्यास्त तक का समय 12 बराबर भागों में विभाजित। रात के 12 होरा: सूर्यास्त से अगले सूर्योदय तक 12 भागों में। पहला होरा वार के स्वामी ग्रह का होता है (रविवार = सूर्य, सोमवार = चन्द्र, आदि)। उसके बाद कैल्डियन क्रम में अगले ग्रह आते हैं: शनि → गुरु → मंगल → सूर्य → शुक्र → बुध → चन्द्र।",
    muhuratAi: "मुहूर्त AI",
    festivalCalendar: "त्योहार कैलेंडर",
  },
};

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickToolPageLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}
