/**
 * Localised overlay layer for TRANSIT_ARTICLES.
 *
 * The raw articles in `transit-articles/*.ts` predate the translation
 * pipeline and mix two field shapes:
 *   - `title`, `metaDescription`, `overview`, `generalThemes` → `{ en, hi }`
 *   - `duration`, `retrogradeNote`, all `moonSignEffects.*` strings,
 *     all `keyDates.event` / `keyDates.significance` → plain `string`
 *
 * Touching every raw article file to standardise on LocaleText would
 * blow the diff up and risk JSX/template-literal corruption. Instead
 * this module:
 *   1. Lifts every raw string into `{ en: string }` at module load
 *   2. Applies per-locale overlay JSONs onto the wrapped tree
 *   3. Exports `LOCALIZED_TRANSIT_ARTICLES` with all fields as LocaleText,
 *      ready for `tl()` consumption
 *
 * Overlay JSONs are generated by scripts/translate-transit-articles-via-gemini.py
 * and live at src/lib/content/transit-articles-{locale}-overlay.json,
 * keyed by `${slug}.${path}` — same notation the puja-vidhi merger uses.
 *
 * Sacred Devanagari / IAST does not appear in transit articles, so no
 * AS-IS preservation logic is needed (cf. puja-vidhi-with-overlay.ts).
 */

import type { LocaleText } from '@/types/panchang';
import { TRANSIT_ARTICLES as RAW_TRANSIT_ARTICLES } from './transit-articles';
import type { TransitArticle } from './transit-articles/types';

import taOverlayRaw from './transit-articles-ta-overlay.json';
import teOverlayRaw from './transit-articles-te-overlay.json';
import bnOverlayRaw from './transit-articles-bn-overlay.json';
import guOverlayRaw from './transit-articles-gu-overlay.json';
import knOverlayRaw from './transit-articles-kn-overlay.json';
import maiOverlayRaw from './transit-articles-mai-overlay.json';
import mrOverlayRaw from './transit-articles-mr-overlay.json';

type OverlayLocale = 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mai' | 'mr';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['ta', 'te', 'bn', 'gu', 'kn', 'mai', 'mr'];

/* Localised shapes — all LocaleText where the raw shape mixed strings + {en,hi} */

export interface LocalizedMoonSignEffect {
  rashiId: number;
  house: number;
  headline: LocaleText;
  body: LocaleText;
  dosAndDonts: LocaleText[];
  remedy: LocaleText;
}

export interface LocalizedKeyDate {
  date: string;
  event: LocaleText;
  significance: LocaleText;
}

export interface LocalizedTransitArticle {
  slug: string;
  planetId: number;
  fromSignId: number;
  toSignId: number;
  year: number;
  exactDate: string;
  endDate: string;
  duration: LocaleText;
  title: LocaleText;
  metaDescription: LocaleText;
  overview: LocaleText;
  generalThemes: LocaleText[];
  moonSignEffects: LocalizedMoonSignEffect[];
  keyDates: LocalizedKeyDate[];
  retrogradeNote?: LocaleText;
  publishDate: string;
}

function wrap(s: string): LocaleText {
  return { en: s } as LocaleText;
}

function wrapArticle(raw: TransitArticle): LocalizedTransitArticle {
  return {
    slug: raw.slug,
    planetId: raw.planetId,
    fromSignId: raw.fromSignId,
    toSignId: raw.toSignId,
    year: raw.year,
    exactDate: raw.exactDate,
    endDate: raw.endDate,
    duration: wrap(raw.duration),
    // Already-LocaleText-shaped fields — pass through (cast widens hi
    // to LocaleText's optional non-en keys).
    title: { ...raw.title } as LocaleText,
    metaDescription: { ...raw.metaDescription } as LocaleText,
    overview: { ...raw.overview } as LocaleText,
    generalThemes: raw.generalThemes.map((g) => ({ ...g }) as LocaleText),
    moonSignEffects: raw.moonSignEffects.map((e) => ({
      rashiId: e.rashiId,
      house: e.house,
      headline: wrap(e.headline),
      body: wrap(e.body),
      dosAndDonts: e.dosAndDonts.map((d) => wrap(d)),
      remedy: wrap(e.remedy),
    })),
    keyDates: raw.keyDates.map((k) => ({
      date: k.date,
      event: wrap(k.event),
      significance: wrap(k.significance),
    })),
    retrogradeNote: raw.retrogradeNote ? wrap(raw.retrogradeNote) : undefined,
    publishDate: raw.publishDate,
  };
}

/**
 * Walk `samagri[3].name`-style dotted+bracketed paths. Returns the
 * leaf LocaleText object (so the caller can attach a new locale key),
 * or null if any segment misses — keeps a stale overlay key from
 * silently corrupting an unrelated node.
 */
function resolveLocaleText(root: unknown, path: string): Record<string, string> | null {
  const tokens = path.match(/[^.[\]]+|\[\d+\]/g);
  if (!tokens) return null;
  let cur: unknown = root;
  for (const tok of tokens) {
    if (cur === null || typeof cur !== 'object') return null;
    if (tok.startsWith('[')) {
      const idx = Number(tok.slice(1, -1));
      if (!Array.isArray(cur) || idx >= cur.length) return null;
      cur = cur[idx];
    } else {
      cur = (cur as Record<string, unknown>)[tok];
    }
  }
  if (cur === null || typeof cur !== 'object' || Array.isArray(cur)) return null;
  const obj = cur as Record<string, unknown>;
  if (typeof obj.en !== 'string') return null;
  return obj as Record<string, string>;
}

function applyOverlays(slug: string, article: LocalizedTransitArticle): LocalizedTransitArticle {
  for (const locale of OVERLAY_LOCALES) {
    const overlay = OVERLAYS[locale];
    for (const [key, value] of Object.entries(overlay)) {
      if (!key.startsWith(`${slug}.`)) continue;
      if (typeof value !== 'string' || !value.trim()) continue;
      const path = key.slice(slug.length + 1);
      const target = resolveLocaleText(article, path);
      if (!target) continue;
      if (typeof target[locale] === 'string' && target[locale].trim()) continue;
      target[locale] = value;
    }
  }
  return article;
}

const merged: Record<string, LocalizedTransitArticle> = {};
for (const [slug, raw] of Object.entries(RAW_TRANSIT_ARTICLES)) {
  merged[slug] = applyOverlays(slug, wrapArticle(raw));
}

export const LOCALIZED_TRANSIT_ARTICLES: Readonly<Record<string, LocalizedTransitArticle>> = merged;

export function getLocalizedTransitArticle(slug: string): LocalizedTransitArticle | undefined {
  return merged[slug];
}

/** Slug list — re-exported from raw so callers don't need a second import. */
export function getTransitArticleSlugs(): string[] {
  return Object.keys(RAW_TRANSIT_ARTICLES);
}
