/**
 * Shared label set for /transits (page + layout metadata).
 *
 * Authored locales: en, hi.
 * Gemini-translated overlay (mai/mr/ta/te/kn/gu/bn) lives in
 * `src/lib/constants/transits-labels-overlay.json`, generated by
 * `scripts/translate-transits-via-gemini.py`.
 *
 * The titleTemplate / descTemplate keys carry {DATE} placeholders;
 * jupiterInHouseTemplate carries {ORDINAL}. ordH1..ordH12 are the
 * locale-canonical house ordinals (1st/2nd/3rd in English, १ले/२रे
 * /३रे in Marathi, etc.).
 *
 * Resolution: AUTHORED[locale] → OVERLAY[locale] → AUTHORED.hi → AUTHORED.en
 */
import overlay from '@/lib/constants/transits-labels-overlay.json';

const AUTHORED: Record<string, Record<string, string>> = {
  en: {
    titleTemplate: 'Planet Transits Today {DATE} – Live Navagraha Positions',
    descTemplate: '{DATE} transits: all 9 planets\' current signs, nakshatras & retrograde status. Transit effects & predictions. Free, updated daily.',
    daysLabel: 'days',
    nextMajorTransit: 'Next Major Transit',
    jupiterInHouseTemplate: 'Jupiter in your {ORDINAL} house',
    todayBadge: 'TODAY',
    sankrantiSuffix: 'Sankranti',
    jupiterVedhaTemplate: 'Jupiter in {SIGN_A} is Vedha-blocked by Saturn in {SIGN_B}.',
    ashtamaShaniTemplate: 'Saturn in {SIGN} is 8th from your Moon — intense karmic pressure.',
    sunEntersTemplate: 'Sun enters 0° sidereal {SIGN}',
    astroNewYearSuffix: 'the astrological new year (Brihat Samhita)',
    ordH1: '1st', ordH2: '2nd', ordH3: '3rd', ordH4: '4th',
    ordH5: '5th', ordH6: '6th', ordH7: '7th', ordH8: '8th',
    ordH9: '9th', ordH10: '10th', ordH11: '11th', ordH12: '12th',
  },
  hi: {
    titleTemplate: 'ग्रह गोचर आज {DATE} – नवग्रह की वर्तमान स्थिति',
    descTemplate: '{DATE} गोचर: सभी 9 ग्रहों की वर्तमान राशि, नक्षत्र, वक्री स्थिति। गोचर फल व प्रभाव। निःशुल्क, प्रतिदिन अपडेट।',
    daysLabel: 'दिन',
    nextMajorTransit: 'अगला प्रमुख गोचर',
    jupiterInHouseTemplate: 'गुरु आपके {ORDINAL} भाव में',
    todayBadge: 'आज',
    sankrantiSuffix: 'संक्रान्ति',
    jupiterVedhaTemplate: '{SIGN_A} में गुरु को {SIGN_B} में शनि का वेध है।',
    ashtamaShaniTemplate: 'शनि {SIGN} में आपके चन्द्र से 8वें भाव में — गहन कार्मिक दबाव।',
    sunEntersTemplate: 'सूर्य {SIGN} राशि में प्रवेश',
    astroNewYearSuffix: 'ज्योतिषीय नव वर्ष (बृहत्संहिता)',
    ordH1: 'प्रथम', ordH2: 'द्वितीय', ordH3: 'तृतीय', ordH4: 'चतुर्थ',
    ordH5: 'पंचम', ordH6: 'षष्ठ', ordH7: 'सप्तम', ordH8: 'अष्टम',
    ordH9: 'नवम', ordH10: 'दशम', ordH11: 'एकादश', ordH12: 'द्वादश',
  },
};

// BCP-47 date-tag map. Maithili (mai) has no ICU locale → use Devanagari
// fallback (hi-IN) for date formatting; same for retired sa.
const DATE_TAGS: Record<string, string> = {
  en: 'en-US', hi: 'hi-IN', ta: 'ta-IN', te: 'te-IN', bn: 'bn-IN',
  gu: 'gu-IN', kn: 'kn-IN', mr: 'mr-IN', mai: 'hi-IN', sa: 'hi-IN',
};

export function transitsDateTag(locale: string): string {
  return DATE_TAGS[locale] ?? 'en-US';
}

const OVERLAY = overlay as Record<string, Record<string, string>>;

export function pickTransitLabel(key: string, locale: string): string {
  return (
    AUTHORED[locale]?.[key]
    ?? OVERLAY[locale]?.[key]
    ?? AUTHORED.hi[key]
    ?? AUTHORED.en[key]
    ?? ''
  );
}

export function formatTransitLabel(
  key: string,
  locale: string,
  vars: Record<string, string>,
): string {
  let out = pickTransitLabel(key, locale);
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{${k}}`).join(v);
  }
  return out;
}

export function ordinalHouse(n: number, locale: string): string {
  return pickTransitLabel(`ordH${n}`, locale) || String(n);
}
