/**
 * Planet-in-Sign Interpretations (108 entries)
 * Based on Saravali Ch.21-33, BPHS Ch.22-24
 *
 * 9 planets x 12 signs = 108 trilingual interpretations
 * Each entry covers the personality effects, strengths/weaknesses
 * of a planet placed in that particular sign.
 */

import type { Locale } from '@/types/panchang';
import type { Tri } from './utils';

// Sign names for reference:
// 1=Aries, 2=Taurus, 3=Gemini, 4=Cancer, 5=Leo, 6=Virgo,
// 7=Libra, 8=Scorpio, 9=Sagittarius, 10=Capricorn, 11=Aquarius, 12=Pisces

/**
 * PLANET_IN_SIGN[planetId][signIndex] = Tri
 * planetId: 0=Sun through 8=Ketu (0-based)
 * signIndex: 1-based (1=Aries through 12=Pisces)
 */
export const PLANET_IN_SIGN: Record<number, Record<number, Tri>> = {
  // SUN (0)
  0: {
    1: { en: 'Sun exalted in Aries: commanding presence, natural authority, and pioneering spirit. Leadership comes instinctively, with strong willpower and initiative. Government favor and recognition are likely.', hi: 'मेष में उच्च सूर्य: आज्ञाकारी उपस्थिति, प्राकृतिक अधिकार और अग्रणी भावना। नेतृत्व सहज रूप से आता है। सरकारी कृपा और मान्यता सम्भव।', sa: 'मेषे उच्चसूर्यः: आज्ञाकारी उपस्थितिः, स्वाभाविकम् अधिकारं, अग्रगामी भावना च। नेतृत्वं सहजम्।' },
    2: { en: 'Sun in Taurus: steady determination and practical authority. Wealth accumulation through leadership. Values material security and takes a methodical approach to power.', hi: 'वृषभ में सूर्य: स्थिर दृढ़ता और व्यावहारिक अधिकार। नेतृत्व से धन संचय। भौतिक सुरक्षा को महत्व देता है।', sa: 'वृषभे सूर्यः: स्थिरा दृढता व्यावहारिकम् अधिकारं च। नेतृत्वात् धनसञ्चयः।' },
    3: { en: 'Sun in Gemini: intellectual authority and communicative leadership. Multiple talents and versatile self-expression. May scatter energy across too many interests.', hi: 'मिथुन में सूर्य: बौद्धिक अधिकार और संवाद नेतृत्व। विविध प्रतिभा। ऊर्जा अनेक रुचियों में बिखर सकती है।', sa: 'मिथुने सूर्यः: बौद्धिकम् अधिकारं संवादनेतृत्वं च। बहुप्रतिभाः।' },
    4: { en: 'Sun in Cancer: emotional leadership and nurturing authority. Protective of family and nation. Ego tied to emotional security. Government service with a caring approach.', hi: 'कर्क में सूर्य: भावनात्मक नेतृत्व। परिवार और राष्ट्र के प्रति सुरक्षात्मक। भावनात्मक सुरक्षा से अहम् जुड़ा है।', sa: 'कर्के सूर्यः: भावनात्मिकं नेतृत्वं पोषकम् अधिकारं च। कुटुम्बस्य राष्ट्रस्य च रक्षकः।' },
    5: { en: 'Sun in Leo (own sign): maximum regal presence, natural authority, and creative power. Born leader with generosity and dignity. Government, politics, and entertainment excel.', hi: 'सिंह में सूर्य (स्वगृह): अधिकतम राजसी उपस्थिति, प्राकृतिक अधिकार। जन्मजात नेता। सरकार, राजनीति में उत्कृष्ट।', sa: 'सिंहे सूर्यः (स्वगृहे): परमं राजसी प्रभावः, स्वाभाविकम् अधिकारम्। जन्मजातः नेता।' },
    6: { en: 'Sun in Virgo: analytical authority and service-oriented leadership. Skill in administration and detail work. Health consciousness and disciplined approach to responsibilities.', hi: 'कन्या में सूर्य: विश्लेषणात्मक अधिकार और सेवा-उन्मुख नेतृत्व। प्रशासन में कुशल। स्वास्थ्य सचेत और अनुशासित।', sa: 'कन्यायां सूर्यः: विश्लेषणात्मिकम् अधिकारं सेवोन्मुखं नेतृत्वं च। प्रशासने कुशलः।' },
    7: { en: 'Sun debilitated in Libra: ego struggles with compromise and partnership. Leadership through diplomacy rather than command. Must learn to balance personal will with others\' needs.', hi: 'तुला में नीच सूर्य: अहम् समझौते और साझेदारी से जूझता है। कूटनीति से नेतृत्व। व्यक्तिगत इच्छा और दूसरों की आवश्यकताओं में सन्तुलन सीखना होगा।', sa: 'तुलायां नीचसूर्यः: अहङ्कारः समाधाने साझेदार्यां च संघर्षम् अनुभवति।' },
    8: { en: 'Sun in Scorpio: intense willpower and transformative authority. Deep insight into power dynamics. Leadership through crisis management and investigation.', hi: 'वृश्चिक में सूर्य: तीव्र इच्छाशक्ति और परिवर्तनकारी अधिकार। शक्ति गतिशीलता में गहरी अन्तर्दृष्टि। संकट प्रबन्धन से नेतृत्व।', sa: 'वृश्चिके सूर्यः: तीव्रा इच्छाशक्तिः परिवर्तनकारी अधिकारम् च।' },
    9: { en: 'Sun in Sagittarius: philosophical authority and righteous leadership. Teaching, law, and spiritual guidance. Strong moral compass with expansive vision.', hi: 'धनु में सूर्य: दार्शनिक अधिकार और धार्मिक नेतृत्व। शिक्षण, कानून, आध्यात्मिक मार्गदर्शन। विस्तृत दृष्टि के साथ मजबूत नैतिक दिशा।', sa: 'धनुषि सूर्यः: दार्शनिकम् अधिकारं धार्मिकं नेतृत्वं च। शिक्षणं विधिः आध्यात्मिकमार्गदर्शनं च।' },
    10: { en: 'Sun in Capricorn: disciplined authority and institutional leadership. Steady rise through hierarchies. Father may be strict but respected. Government service and corporate leadership.', hi: 'मकर में सूर्य: अनुशासित अधिकार और संस्थागत नेतृत्व। पदानुक्रम में स्थिर उन्नति। सरकारी और कॉर्पोरेट नेतृत्व।', sa: 'मकरे सूर्यः: अनुशासितम् अधिकारं सांस्थानिकं नेतृत्वं च।' },
    11: { en: 'Sun in Aquarius: humanitarian authority and innovative leadership. Leading social reform and technological progress. Unconventional ego expression. Group leadership over individual command.', hi: 'कुम्भ में सूर्य: मानवतावादी अधिकार और नवीन नेतृत्व। सामाजिक सुधार और तकनीकी प्रगति का नेतृत्व। अपरम्परागत अहम् अभिव्यक्ति।', sa: 'कुम्भे सूर्यः: मानवतावादी अधिकारं नवीनं नेतृत्वं च।' },
    12: { en: 'Sun in Pisces: spiritual authority and compassionate leadership. Ego dissolves into service to others. Artistic and healing vocations. Power through surrender and devotion.', hi: 'मीन में सूर्य: आध्यात्मिक अधिकार और करुणामय नेतृत्व। अहम् दूसरों की सेवा में विलीन। कलात्मक और उपचार व्यवसाय।', sa: 'मीने सूर्यः: आध्यात्मिकम् अधिकारं करुणामयं नेतृत्वं च।' },
  },
  // MOON (1)
  1: {
    1: { en: 'Moon in Aries: quick emotions, impulsive reactions, and fiery moods. Emotionally courageous and independent. Needs excitement and action for emotional security.', hi: 'मेष में चन्द्रमा: त्वरित भावनाएँ, आवेगपूर्ण प्रतिक्रियाएँ। भावनात्मक रूप से साहसी और स्वतन्त्र।', sa: 'मेषे चन्द्रः: त्वरिताः भावनाः, आवेगपूर्णाः प्रतिक्रियाः। भावनात्मिकशौर्यम्।' },
    2: { en: 'Moon exalted in Taurus: deep emotional stability, strong attachment to comfort, and sensual appreciation. The most grounded and steady emotional nature. Loyalty runs deep.', hi: 'वृषभ में उच्च चन्द्रमा: गहरी भावनात्मक स्थिरता, सुख-सुविधा से गहरा लगाव। सबसे स्थिर भावनात्मक प्रकृति। निष्ठा गहरी।', sa: 'वृषभे उच्चचन्द्रः: गहना भावनात्मिका स्थिरता, सुखसुविधासु गहनम् अनुरक्तिः।' },
    3: { en: 'Moon in Gemini: intellectualized emotions, curious and communicative inner life. Emotional need for mental stimulation. Moods change quickly. Witty and sociable emotional expression.', hi: 'मिथुन में चन्द्रमा: बौद्धिक भावनाएँ, जिज्ञासु। मानसिक उत्तेजना की भावनात्मक आवश्यकता। मनोदशा तेजी से बदलती है।', sa: 'मिथुने चन्द्रः: बौद्धिकभावनाः, जिज्ञासुः। मानसिकोत्तेजनायाः भावनात्मिकावश्यकता।' },
    4: { en: 'Moon in Cancer (own sign): supreme emotional depth, powerful nurturing instincts, and psychic sensitivity. Mother is deeply influential. Home is the emotional sanctuary.', hi: 'कर्क में चन्द्रमा (स्वगृह): परम भावनात्मक गहराई, शक्तिशाली पोषण वृत्ति। माता का गहरा प्रभाव। घर भावनात्मक अभयारण्य।', sa: 'कर्के चन्द्रः (स्वगृहे): परमा भावनात्मिका गहनता, शक्तिमती पोषणवृत्तिः।' },
    5: { en: 'Moon in Leo: dramatic emotional expression, generous heart, and need for admiration. Creative and warm inner life. Children bring great emotional fulfillment.', hi: 'सिंह में चन्द्रमा: नाटकीय भावनात्मक अभिव्यक्ति, उदार हृदय। रचनात्मक और उष्ण अन्तरिक्ष जीवन। सन्तान से भावनात्मक पूर्ति।', sa: 'सिंहे चन्द्रः: नाटकीया भावनात्मिका अभिव्यक्तिः, उदारं हृदयम्।' },
    6: { en: 'Moon in Virgo: analytical emotional processing, worrying tendency, and service-oriented care. Health-conscious emotionally. Needs order and routine for inner peace.', hi: 'कन्या में चन्द्रमा: विश्लेषणात्मक भावनात्मक प्रक्रिया, चिन्ता प्रवृत्ति। भावनात्मक रूप से स्वास्थ्य सचेत। आन्तरिक शान्ति के लिए व्यवस्था आवश्यक।', sa: 'कन्यायां चन्द्रः: विश्लेषणात्मिकी भावनात्मिकी प्रक्रिया।' },
    7: { en: 'Moon in Libra: balanced emotional nature, need for partnership, and aesthetic sensitivity. Harmony in relationships is essential. Diplomatic and charming emotional expression.', hi: 'तुला में चन्द्रमा: सन्तुलित भावनात्मक प्रकृति, साझेदारी की आवश्यकता। सम्बन्धों में सामंजस्य आवश्यक। कूटनीतिक और मनोहर।', sa: 'तुलायां चन्द्रः: सन्तुलिता भावनात्मिका प्रकृतिः, साझेदार्याः आवश्यकता।' },
    8: { en: 'Moon debilitated in Scorpio: intense, penetrating emotions and emotional extremes. Psychic depth but emotional turbulence. Transformative emotional experiences drive growth.', hi: 'वृश्चिक में नीच चन्द्रमा: तीव्र, भेदक भावनाएँ और भावनात्मक चरम। मानसिक गहराई पर भावनात्मक अशान्ति। परिवर्तनकारी अनुभव विकास प्रेरित करते हैं।', sa: 'वृश्चिके नीचचन्द्रः: तीव्राः भेदकाः भावनाः, भावनात्मिकचरमाणि च।' },
    9: { en: 'Moon in Sagittarius: optimistic emotional nature, philosophical inner life, and love of freedom. Emotional growth through travel, learning, and philosophical exploration.', hi: 'धनु में चन्द्रमा: आशावादी भावनात्मक प्रकृति, दार्शनिक अन्तर्जगत। यात्रा और दर्शन से भावनात्मक विकास।', sa: 'धनुषि चन्द्रः: आशावादी भावनात्मिका प्रकृतिः, दार्शनिकम् अन्तर्जगत्।' },
    10: { en: 'Moon in Capricorn: controlled emotions, practical emotional needs, and disciplined inner life. Emotional maturity comes early. May suppress feelings for duty.', hi: 'मकर में चन्द्रमा: नियन्त्रित भावनाएँ, व्यावहारिक भावनात्मक आवश्यकताएँ। भावनात्मक परिपक्वता शीघ्र आती है। कर्तव्य के लिए भावनाएँ दबा सकते हैं।', sa: 'मकरे चन्द्रः: नियन्त्रिताः भावनाः, व्यावहारिकाः भावनात्मिकावश्यकताः।' },
    11: { en: 'Moon in Aquarius: detached emotional processing, humanitarian feelings, and unconventional inner life. Emotional fulfillment through social causes and group connections.', hi: 'कुम्भ में चन्द्रमा: विलग भावनात्मक प्रक्रिया, मानवतावादी भावनाएँ। सामाजिक कार्यों और सामूहिक सम्बन्धों से भावनात्मक पूर्ति।', sa: 'कुम्भे चन्द्रः: विलग्ना भावनात्मिकी प्रक्रिया, मानवतावादिन्यः भावनाः।' },
    12: { en: 'Moon in Pisces: deeply intuitive, compassionate, and dreamy emotional nature. Psychic sensitivity and rich imagination. Empathic absorption of others\' feelings. Artistic and spiritual emotional outlet.', hi: 'मीन में चन्द्रमा: गहन सहज ज्ञान, करुणामय और स्वप्नशील। मानसिक संवेदनशीलता और समृद्ध कल्पना। कलात्मक और आध्यात्मिक भावनात्मक अभिव्यक्ति।', sa: 'मीने चन्द्रः: गहनं सहजज्ञानं, करुणामयः स्वप्नशीलश्च।' },
  },
  // MARS (2)
  2: {
    1: { en: 'Mars in Aries (own sign): maximum courage, physical strength, and competitive drive. Born warrior and leader. Impulsive but decisive. Athletic and independent.', hi: 'मेष में मंगल (स्वगृह): अधिकतम साहस, शारीरिक बल। जन्मजात योद्धा और नेता। आवेगी पर निर्णायक।', sa: 'मेषे मङ्गलः (स्वगृहे): परमं शौर्यं शारीरिकबलं च। जन्मजातः योद्धा नेता च।' },
    2: { en: 'Mars in Taurus: persistent energy directed toward material goals. Determined and enduring effort. Strong sensual drive. May be stubborn in pursuits.', hi: 'वृषभ में मंगल: भौतिक लक्ष्यों की ओर निरन्तर ऊर्जा। दृढ़ और सहनशील प्रयास। हठी हो सकते हैं।', sa: 'वृषभे मङ्गलः: भौतिकलक्ष्यान् प्रति निरन्तरा ऊर्जा। दृढः सहनशीलश्च।' },
    3: { en: 'Mars in Gemini: mental aggressiveness and sharp debate skills. Versatile energy applied to multiple pursuits. Communication with force and conviction.', hi: 'मिथुन में मंगल: मानसिक आक्रामकता और तीक्ष्ण वाद कौशल। विविध लक्ष्यों में ऊर्जा। बल और विश्वास के साथ संवाद।', sa: 'मिथुने मङ्गलः: मानसिकी आक्रामकता तीक्ष्णवादकौशलं च।' },
    4: { en: 'Mars debilitated in Cancer: emotional energy and domestic assertiveness. Courage comes through protecting loved ones. Physical vitality affected by emotional state.', hi: 'कर्क में नीच मंगल: भावनात्मक ऊर्जा। प्रियजनों की रक्षा से साहस। भावनात्मक अवस्था शारीरिक जीवन शक्ति प्रभावित करती है।', sa: 'कर्के नीचमङ्गलः: भावनात्मिकी ऊर्जा। प्रियजनरक्षणात् शौर्यम्।' },
    5: { en: 'Mars in Leo: heroic courage and dramatic action. Natural commander with pride and magnanimity. Creative energy channeled through bold expression.', hi: 'सिंह में मंगल: वीरोचित साहस और नाटकीय कार्रवाई। गर्व और उदारता के साथ स्वाभाविक सेनापति।', sa: 'सिंहे मङ्गलः: वीरोचितं शौर्यं नाटकीयं कर्म च। स्वाभाविकः सेनापतिः।' },
    6: { en: 'Mars in Virgo: precise, methodical energy. Excellent for surgery, engineering, and technical work. Critical and analytical in conflict. Tactical rather than strategic.', hi: 'कन्या में मंगल: सटीक, व्यवस्थित ऊर्जा। शल्यचिकित्सा, अभियान्त्रिकी में उत्कृष्ट। सामरिक दृष्टिकोण।', sa: 'कन्यायां मङ्गलः: सूक्ष्मा व्यवस्थिता ऊर्जा। शल्यचिकित्सायाम् अभियान्त्रिक्यां च उत्कृष्टः।' },
    7: { en: 'Mars in Libra: energy directed toward partnerships and justice. Competitive in relationships. Diplomatic warrior. May struggle with decision-making in action.', hi: 'तुला में मंगल: साझेदारी और न्याय की ओर ऊर्जा। सम्बन्धों में प्रतिस्पर्धी। कूटनीतिक योद्धा।', sa: 'तुलायां मङ्गलः: साझेदार्यां न्याये च ऊर्जा। कूटनीतिकः योद्धा।' },
    8: { en: 'Mars in Scorpio (own sign): maximum intensity, strategic power, and transformative energy. Fearless researcher and crisis manager. Formidable in opposition.', hi: 'वृश्चिक में मंगल (स्वगृह): अधिकतम तीव्रता, रणनीतिक शक्ति। निडर शोधकर्ता और संकट प्रबन्धक।', sa: 'वृश्चिके मङ्गलः (स्वगृहे): परमा तीव्रता, रणनीतिकी शक्तिः।' },
    9: { en: 'Mars in Sagittarius: adventurous energy directed toward ideals. Warrior for principles and beliefs. Enthusiasm for physical exploration and philosophical debate.', hi: 'धनु में मंगल: आदर्शों की ओर साहसिक ऊर्जा। सिद्धान्तों और विश्वासों का योद्धा। शारीरिक अन्वेषण का उत्साह।', sa: 'धनुषि मङ्गलः: आदर्शान् प्रति साहसिकी ऊर्जा। सिद्धान्तानां योद्धा।' },
    10: { en: 'Mars exalted in Capricorn: maximum disciplined energy and strategic execution. Military excellence and institutional power. Patience strengthens courage. Career achievement through sustained effort.', hi: 'मकर में उच्च मंगल: अधिकतम अनुशासित ऊर्जा और रणनीतिक कार्यान्वयन। सैन्य उत्कृष्टता। धैर्य साहस को मजबूत करता है।', sa: 'मकरे उच्चमङ्गलः: परमम् अनुशासितम् ऊर्जा रणनीतिककार्यान्वयनं च।' },
    11: { en: 'Mars in Aquarius: unconventional energy and innovative action. Fighting for social causes and humanitarian goals. Technology-driven assertiveness.', hi: 'कुम्भ में मंगल: अपरम्परागत ऊर्जा और नवीन कार्रवाई। सामाजिक कारणों के लिए संघर्ष। प्रौद्योगिकी-प्रेरित दृढ़ता।', sa: 'कुम्भे मङ्गलः: अपरम्परागती ऊर्जा नवीनं कर्म च।' },
    12: { en: 'Mars in Pisces: spiritual courage and compassionate action. Energy directed toward healing and service. Hidden strength that emerges in crisis. Martial arts and meditation combined.', hi: 'मीन में मंगल: आध्यात्मिक साहस और करुणामय कार्रवाई। उपचार और सेवा की ओर ऊर्जा। संकट में प्रकट होने वाली छिपी शक्ति।', sa: 'मीने मङ्गलः: आध्यात्मिकं शौर्यं करुणामयं कर्म च।' },
  },
  // MERCURY (3)
  3: {
    1: { en: 'Mercury in Aries: quick thinking, impulsive communication, and sharp wit. Direct speech that can be blunt. Fast learner but may lack patience for deep study.', hi: 'मेष में बुध: त्वरित चिन्तन, आवेगपूर्ण संवाद, तीक्ष्ण बुद्धि। प्रत्यक्ष वाणी। तेज सीखने वाला पर गहन अध्ययन में धैर्य की कमी।', sa: 'मेषे बुधः: त्वरितं चिन्तनं, आवेगपूर्णः संवादः, तीक्ष्णा बुद्धिः।' },
    2: { en: 'Mercury in Taurus: practical intelligence, steady communication, and good financial sense. Slow but thorough thinker. Musical and artistic appreciation.', hi: 'वृषभ में बुध: व्यावहारिक बुद्धि, स्थिर संवाद, अच्छी वित्तीय समझ। धीमा पर पूर्ण विचारक। संगीत और कला में रुचि।', sa: 'वृषभे बुधः: व्यावहारिकी बुद्धिः, स्थिरः संवादः।' },
    3: { en: 'Mercury in Gemini (own sign): brilliant communicator, versatile intellect, and quick wit. Multiple talents in writing, speaking, and media. The most mentally agile placement.', hi: 'मिथुन में बुध (स्वगृह): प्रतिभाशाली संवादक, बहुमुखी बुद्धि। लेखन, वक्तृत्व और मीडिया में विविध प्रतिभा। सर्वाधिक मानसिक चपलता।', sa: 'मिथुने बुधः (स्वगृहे): प्रतिभाशाली संवादकः, बहुमुखी बुद्धिः।' },
    4: { en: 'Mercury in Cancer: emotionally intelligent communication and intuitive thinking. Good memory and storytelling ability. Thoughts colored by feelings.', hi: 'कर्क में बुध: भावनात्मक बुद्धिमत्ता, सहज चिन्तन। अच्छी स्मृति और कथावाचन क्षमता। भावनाओं से रंगे विचार।', sa: 'कर्के बुधः: भावनात्मिकी बुद्धिमत्ता सहजं चिन्तनं च।' },
    5: { en: 'Mercury in Leo: dramatic communication, creative intellect, and authoritative speech. Natural teacher and presenter. May be intellectually proud.', hi: 'सिंह में बुध: नाटकीय संवाद, रचनात्मक बुद्धि, आधिकारिक वाणी। स्वाभाविक शिक्षक और प्रस्तुतकर्ता।', sa: 'सिंहे बुधः: नाटकीयः संवादः, रचनात्मिकी बुद्धिः।' },
    6: { en: 'Mercury exalted in Virgo: peak analytical ability, precision in communication, and methodical intelligence. Exceptional in research, editing, and healthcare. Detail mastery.', hi: 'कन्या में उच्च बुध: शिखर विश्लेषणात्मक क्षमता, संवाद में सटीकता। शोध, सम्पादन और स्वास्थ्य सेवा में असाधारण।', sa: 'कन्यायां उच्चबुधः: शिखरविश्लेषणात्मिकी क्षमता, संवादे सूक्ष्मता।' },
    7: { en: 'Mercury in Libra: balanced, fair-minded intellect. Excellent in law, diplomacy, and negotiation. Aesthetic appreciation in communication. Indecisive when weighing options.', hi: 'तुला में बुध: सन्तुलित, निष्पक्ष बुद्धि। कानून, कूटनीति और बातचीत में उत्कृष्ट। विकल्प तौलते समय अनिर्णय।', sa: 'तुलायां बुधः: सन्तुलिता निष्पक्षा बुद्धिः। विधौ कूटनीतौ च उत्कृष्टः।' },
    8: { en: 'Mercury in Scorpio: penetrating intellect, research ability, and strategic communication. Investigative mind that uncovers secrets. Speech can be sharp and cutting.', hi: 'वृश्चिक में बुध: भेदक बुद्धि, शोध क्षमता, रणनीतिक संवाद। रहस्य उजागर करने वाला अन्वेषणात्मक मन।', sa: 'वृश्चिके बुधः: भेदकी बुद्धिः, शोधक्षमता, रणनीतिकः संवादः।' },
    9: { en: 'Mercury in Sagittarius: philosophical intellect, broad-minded thinking, and teaching ability. Grand ideas and visionary communication. May neglect details.', hi: 'धनु में बुध: दार्शनिक बुद्धि, विशाल सोच, शिक्षण क्षमता। भव्य विचार और दूरदर्शी संवाद। विवरण उपेक्षित हो सकते हैं।', sa: 'धनुषि बुधः: दार्शनिकी बुद्धिः, विशालं चिन्तनम्।' },
    10: { en: 'Mercury in Capricorn: structured, disciplined thinking and practical communication. Business intelligence and administrative skill. Conservative but effective communicator.', hi: 'मकर में बुध: संरचित, अनुशासित चिन्तन। व्यापार बुद्धि और प्रशासनिक कौशल। रूढ़िवादी पर प्रभावी संवादक।', sa: 'मकरे बुधः: संरचितं अनुशासितं चिन्तनम्।' },
    11: { en: 'Mercury in Aquarius: innovative, unconventional intellect. Technology aptitude and progressive ideas. Communication through modern media. Group-oriented thinking.', hi: 'कुम्भ में बुध: नवीन, अपरम्परागत बुद्धि। प्रौद्योगिकी योग्यता और प्रगतिशील विचार। आधुनिक मीडिया से संवाद।', sa: 'कुम्भे बुधः: नवीना अपरम्परागती बुद्धिः। प्रौद्योगिकीयोग्यता।' },
    12: { en: 'Mercury debilitated in Pisces: intuitive rather than analytical thinking. Poetic and imaginative communication. Logical mind dissolves into intuitive knowing. May struggle with practical details.', hi: 'मीन में नीच बुध: विश्लेषणात्मक से अधिक सहज चिन्तन। काव्यात्मक और कल्पनाशील संवाद। तार्किक मन सहज ज्ञान में विलीन।', sa: 'मीने नीचबुधः: विश्लेषणात्मिकात् अधिकं सहजं चिन्तनम्।' },
  },
  // JUPITER (4)
  4: {
    1: { en: 'Jupiter in Aries: enthusiastic wisdom, pioneering philosophy, and active faith. Teaching through action and example. Impulsive generosity.', hi: 'मेष में बृहस्पति: उत्साही ज्ञान, अग्रणी दर्शन। कर्म और उदाहरण से शिक्षण। आवेगपूर्ण उदारता।', sa: 'मेषे बृहस्पतिः: उत्साही ज्ञानं, अग्रगामी दर्शनम्।' },
    2: { en: 'Jupiter in Taurus: practical wisdom applied to wealth building. Material abundance through ethical means. Teaching through steady example. Generous but grounded.', hi: 'वृषभ में बृहस्पति: धन निर्माण में व्यावहारिक ज्ञान। नैतिक साधनों से भौतिक प्रचुरता। स्थिर उदाहरण से शिक्षण।', sa: 'वृषभे बृहस्पतिः: धननिर्माणे व्यावहारिकं ज्ञानम्।' },
    3: { en: 'Jupiter in Gemini: intellectual expansion, diverse knowledge, and communicative wisdom. Publishing and teaching multiple subjects. May scatter philosophical focus.', hi: 'मिथुन में बृहस्पति: बौद्धिक विस्तार, विविध ज्ञान। प्रकाशन और बहु-विषय शिक्षण। दार्शनिक ध्यान बिखर सकता है।', sa: 'मिथुने बृहस्पतिः: बौद्धिकविस्तारः, विविधं ज्ञानम्।' },
    4: { en: 'Jupiter exalted in Cancer: supreme wisdom nourished by emotional depth. Greatest capacity for compassion and nurturing. Home becomes temple. Children are blessed.', hi: 'कर्क में उच्च बृहस्पति: भावनात्मक गहराई से पोषित परम ज्ञान। करुणा की सर्वोच्च क्षमता। घर मन्दिर बनता है। सन्तान भाग्यशाली।', sa: 'कर्के उच्चबृहस्पतिः: भावनात्मिकगहनतया पोषितं परमं ज्ञानम्।' },
    5: { en: 'Jupiter in Leo: royal wisdom, generous teaching, and creative philosophy. Natural spiritual authority. Children are gifted. Grand vision in education.', hi: 'सिंह में बृहस्पति: राजसी ज्ञान, उदार शिक्षण। स्वाभाविक आध्यात्मिक अधिकार। सन्तान प्रतिभाशाली।', sa: 'सिंहे बृहस्पतिः: राजसी ज्ञानम्, उदारं शिक्षणम्।' },
    6: { en: 'Jupiter in Virgo: detailed, analytical wisdom and service-oriented philosophy. Healing through knowledge. Teaching through practical service. May be overly critical in beliefs.', hi: 'कन्या में बृहस्पति: विस्तृत, विश्लेषणात्मक ज्ञान। ज्ञान से उपचार। व्यावहारिक सेवा से शिक्षण।', sa: 'कन्यायां बृहस्पतिः: विस्तृतं विश्लेषणात्मिकं ज्ञानम्।' },
    7: { en: 'Jupiter in Libra: balanced wisdom, fair-minded philosophy, and partnership-oriented expansion. Justice and ethics in relationships. Marriage brings growth.', hi: 'तुला में बृहस्पति: सन्तुलित ज्ञान, निष्पक्ष दर्शन। सम्बन्धों में न्याय और नैतिकता। विवाह से विकास।', sa: 'तुलायां बृहस्पतिः: सन्तुलितं ज्ञानं, निष्पक्षं दर्शनम्।' },
    8: { en: 'Jupiter in Scorpio: deep occult wisdom, transformative philosophy, and healing knowledge. Research into hidden matters brings profound insight.', hi: 'वृश्चिक में बृहस्पति: गहरा गूढ़ ज्ञान, परिवर्तनकारी दर्शन। छिपे मामलों में शोध गहन अन्तर्दृष्टि लाता है।', sa: 'वृश्चिके बृहस्पतिः: गहनं गूढज्ञानं, परिवर्तनकारी दर्शनम्।' },
    9: { en: 'Jupiter in Sagittarius (own sign): natural philosopher, teacher, and spiritual guide. Fortune through wisdom and travel. Higher education brings greatest fulfillment.', hi: 'धनु में बृहस्पति (स्वगृह): स्वाभाविक दार्शनिक, शिक्षक और आध्यात्मिक मार्गदर्शक। ज्ञान और यात्रा से भाग्य।', sa: 'धनुषि बृहस्पतिः (स्वगृहे): स्वाभाविकः दार्शनिकः शिक्षकः मार्गदर्शकश्च।' },
    10: { en: 'Jupiter debilitated in Capricorn: wisdom constrained by practicality. Faith tested by material challenges. Slow but steady spiritual growth through discipline.', hi: 'मकर में नीच बृहस्पति: व्यावहारिकता से बाधित ज्ञान। भौतिक चुनौतियों से विश्वास की परीक्षा। अनुशासन से धीमा पर स्थिर आध्यात्मिक विकास।', sa: 'मकरे नीचबृहस्पतिः: व्यावहारिकतया बाधितं ज्ञानम्।' },
    11: { en: 'Jupiter in Aquarius: humanitarian wisdom, progressive philosophy, and group-oriented expansion. Social reform through knowledge. Technology and spirituality combined.', hi: 'कुम्भ में बृहस्पति: मानवतावादी ज्ञान, प्रगतिशील दर्शन। ज्ञान से सामाजिक सुधार। प्रौद्योगिकी और आध्यात्मिकता का संयोग।', sa: 'कुम्भे बृहस्पतिः: मानवतावादी ज्ञानं, प्रगतिशीलं दर्शनम्।' },
    12: { en: 'Jupiter in Pisces (own sign): supreme spiritual wisdom, devotional philosophy, and liberation-oriented knowledge. Moksha through compassion. Guru\'s blessings flow abundantly.', hi: 'मीन में बृहस्पति (स्वगृह): परम आध्यात्मिक ज्ञान, भक्ति दर्शन। करुणा से मोक्ष। गुरु कृपा प्रचुर मात्रा में।', sa: 'मीने बृहस्पतिः (स्वगृहे): परमम् आध्यात्मिकं ज्ञानं, भक्तिदर्शनम्।' },
  },
  // VENUS (5)
  5: {
    1: { en: 'Venus in Aries: passionate love, bold aesthetics, and impulsive pleasures. Attracts through courage and directness. Romance is fiery and spontaneous.', hi: 'मेष में शुक्र: उत्कट प्रेम, साहसिक सौन्दर्य। साहस और प्रत्यक्षता से आकर्षण। प्रेम अग्निमय और स्वतःस्फूर्त।', sa: 'मेषे शुक्रः: उत्कटं प्रेम, साहसिकं सौन्दर्यम्।' },
    2: { en: 'Venus in Taurus (own sign): supreme sensuality, material comfort, and artistic refinement. Maximum capacity for pleasure. Loyal, devoted, and possessive in love.', hi: 'वृषभ में शुक्र (स्वगृह): परम कामुकता, भौतिक सुख, कलात्मक परिष्कार। प्रेम में निष्ठावान, समर्पित और अधिकारी।', sa: 'वृषभे शुक्रः (स्वगृहे): परमा कामुकता, भौतिकं सुखम्।' },
    3: { en: 'Venus in Gemini: intellectual romance, versatile artistic expression, and charming communication. May have multiple love interests. Wit and humor in relationships.', hi: 'मिथुन में शुक्र: बौद्धिक प्रेम, बहुमुखी कलात्मक अभिव्यक्ति। एकाधिक प्रेम रुचियाँ सम्भव। सम्बन्धों में बुद्धि और हास्य।', sa: 'मिथुने शुक्रः: बौद्धिकं प्रेम, बहुमुखी कलात्मिका अभिव्यक्तिः।' },
    4: { en: 'Venus in Cancer: nurturing love, domestic beauty, and emotional art. Home is beautifully decorated. Romance intertwined with family. Protective in love.', hi: 'कर्क में शुक्र: पोषक प्रेम, घरेलू सौन्दर्य। घर सुन्दर सजा। प्रेम परिवार से जुड़ा। प्रेम में सुरक्षात्मक।', sa: 'कर्के शुक्रः: पोषकं प्रेम, गृहसौन्दर्यम्।' },
    5: { en: 'Venus in Leo: grand, dramatic love expression and royal aesthetic sense. Generous and proud in romance. Creative arts and entertainment favored.', hi: 'सिंह में शुक्र: भव्य, नाटकीय प्रेम अभिव्यक्ति। प्रेम में उदार और गर्वित। रचनात्मक कला और मनोरंजन अनुकूल।', sa: 'सिंहे शुक्रः: भव्या नाटकीया प्रेमाभिव्यक्तिः।' },
    6: { en: 'Venus debilitated in Virgo: love complicated by analysis and criticism. Perfectionism in relationships. Artistic precision but may lack spontaneity. Service-oriented love.', hi: 'कन्या में नीच शुक्र: विश्लेषण और आलोचना से जटिल प्रेम। सम्बन्धों में पूर्णतावाद। सेवा-उन्मुख प्रेम।', sa: 'कन्यायां नीचशुक्रः: विश्लेषणेन आलोचनेन च जटिलं प्रेम।' },
    7: { en: 'Venus in Libra (own sign): perfect balance of beauty, harmony, and partnership. Supreme relationship ability. Aesthetics, art, and design at their finest. Marriage brings joy.', hi: 'तुला में शुक्र (स्वगृह): सौन्दर्य, सामंजस्य और साझेदारी का पूर्ण सन्तुलन। सर्वोच्च सम्बन्ध क्षमता। विवाह आनन्द लाता है।', sa: 'तुलायां शुक्रः (स्वगृहे): सौन्दर्यस्य सामञ्जस्यस्य साझेदार्याश्च पूर्णं सन्तुलनम्।' },
    8: { en: 'Venus in Scorpio: intense, transformative love and deep sensual experiences. Passionate and possessive relationships. Beauty found in darkness and mystery.', hi: 'वृश्चिक में शुक्र: तीव्र, परिवर्तनकारी प्रेम। उत्कट और अधिकारी सम्बन्ध। अन्धकार और रहस्य में सौन्दर्य।', sa: 'वृश्चिके शुक्रः: तीव्रं परिवर्तनकारि प्रेम।' },
    9: { en: 'Venus in Sagittarius: philosophical love, foreign romance, and adventurous aesthetics. Travel brings love. Cross-cultural relationships. Freedom in partnership.', hi: 'धनु में शुक्र: दार्शनिक प्रेम, विदेशी रोमांस। यात्रा प्रेम लाती है। अन्तरसांस्कृतिक सम्बन्ध। साझेदारी में स्वतन्त्रता।', sa: 'धनुषि शुक्रः: दार्शनिकं प्रेम, विदेशीरोमाञ्चः।' },
    10: { en: 'Venus in Capricorn: mature, disciplined love and practical aesthetics. Career in arts brings status. Marriage for stability. Beauty through structure and form.', hi: 'मकर में शुक्र: परिपक्व, अनुशासित प्रेम। कला में कैरियर प्रतिष्ठा लाता है। स्थिरता के लिए विवाह।', sa: 'मकरे शुक्रः: परिपक्वं अनुशासितं प्रेम।' },
    11: { en: 'Venus in Aquarius: unconventional love, group aesthetics, and humanitarian beauty. Technology in art. Friendship-based romance. Progressive relationship values.', hi: 'कुम्भ में शुक्र: अपरम्परागत प्रेम, मानवतावादी सौन्दर्य। कला में प्रौद्योगिकी। मित्रता-आधारित रोमांस।', sa: 'कुम्भे शुक्रः: अपरम्परागतं प्रेम, मानवतावादी सौन्दर्यम्।' },
    12: { en: 'Venus exalted in Pisces: supreme devotional love, transcendent beauty, and artistic inspiration from the divine. Spiritual love transcends physical. Arts reach their highest expression.', hi: 'मीन में उच्च शुक्र: परम भक्ति प्रेम, दिव्य सौन्दर्य। आध्यात्मिक प्रेम शारीरिक से परे। कला अपनी उच्चतम अभिव्यक्ति पाती है।', sa: 'मीने उच्चशुक्रः: परमं भक्तिप्रेम, दिव्यं सौन्दर्यम्।' },
  },
  // SATURN (6)
  6: {
    1: { en: 'Saturn debilitated in Aries: discipline conflicts with impulsiveness. Early life challenges build character. Must learn patience in action. Delayed but lasting achievements.', hi: 'मेष में नीच शनि: अनुशासन आवेगशीलता से टकराता है। प्रारम्भिक जीवन की चुनौतियाँ चरित्र निर्माण करती हैं। विलम्बित पर स्थायी उपलब्धियाँ।', sa: 'मेषे नीचशनिः: अनुशासनं आवेगशीलतया सह संघर्षम् अनुभवति।' },
    2: { en: 'Saturn in Taurus: patient wealth building and methodical accumulation. Frugal nature ensures lasting prosperity. May fear poverty even when secure. Values tradition in material matters.', hi: 'वृषभ में शनि: धैर्यपूर्ण धन निर्माण। मितव्ययी स्वभाव स्थायी समृद्धि सुनिश्चित करता है। सुरक्षित होने पर भी गरीबी का डर हो सकता है।', sa: 'वृषभे शनिः: धैर्यपूर्णं धननिर्माणं व्यवस्थितसञ्चयश्च।' },
    3: { en: 'Saturn in Gemini: structured thinking, disciplined communication, and serious intellectual pursuits. Writing talent that matures with age. Sibling relationships require patience.', hi: 'मिथुन में शनि: संरचित चिन्तन, अनुशासित संवाद। उम्र के साथ परिपक्व होने वाली लेखन प्रतिभा।', sa: 'मिथुने शनिः: संरचितं चिन्तनम्, अनुशासितः संवादः।' },
    4: { en: 'Saturn in Cancer: emotional restriction and disciplined domestic life. Delayed domestic happiness but eventual lasting stability. Deep sense of duty toward family.', hi: 'कर्क में शनि: भावनात्मक प्रतिबन्ध। विलम्बित पर अन्ततः स्थायी घरेलू सुख। परिवार के प्रति गहरा कर्तव्य बोध।', sa: 'कर्के शनिः: भावनात्मिकः प्रतिबन्धः, अनुशासितं गृहजीवनम्।' },
    5: { en: 'Saturn in Leo: authority conflicts with ego. Creative expression matures late. Disciplined approach to leadership. Children may come late but are responsible.', hi: 'सिंह में शनि: अहम् के साथ अधिकार संघर्ष। रचनात्मक अभिव्यक्ति देर से परिपक्व। सन्तान देर से पर जिम्मेदार।', sa: 'सिंहे शनिः: अहङ्कारेण सह अधिकारसंघर्षः।' },
    6: { en: 'Saturn in Virgo: meticulous work ethic, disciplined service, and structured health management. Victory over long-term obstacles through persistent effort.', hi: 'कन्या में शनि: सूक्ष्म कार्य नीति, अनुशासित सेवा। निरन्तर प्रयास से दीर्घकालिक बाधाओं पर विजय।', sa: 'कन्यायां शनिः: सूक्ष्मा कार्यनीतिः, अनुशासिता सेवा।' },
    7: { en: 'Saturn exalted in Libra: justice, structured partnerships, and disciplined balance. Authority through fairness. Marriage to a responsible partner. Legal profession strongly favored.', hi: 'तुला में उच्च शनि: न्याय, संरचित साझेदारी। निष्पक्षता से अधिकार। जिम्मेदार साथी से विवाह। कानूनी पेशा अत्यन्त अनुकूल।', sa: 'तुलायां उच्चशनिः: न्यायः, संरचिताः साझेदार्यः।' },
    8: { en: 'Saturn in Scorpio: deep transformation through discipline. Research into hidden matters. Longevity through careful living. Chronic conditions managed through persistent effort.', hi: 'वृश्चिक में शनि: अनुशासन से गहरा परिवर्तन। छिपे मामलों में शोध। सावधान जीवन से दीर्घायु।', sa: 'वृश्चिके शनिः: अनुशासनेन गहनं परिवर्तनम्।' },
    9: { en: 'Saturn in Sagittarius: disciplined philosophy, structured higher education, and traditional spiritual practice. Wisdom earned through hardship. Teaching with authority.', hi: 'धनु में शनि: अनुशासित दर्शन, संरचित उच्च शिक्षा। कठिनाई से अर्जित ज्ञान। अधिकारपूर्ण शिक्षण।', sa: 'धनुषि शनिः: अनुशासितं दर्शनं, संरचिता उच्चशिक्षा।' },
    10: { en: 'Saturn in Capricorn (own sign): maximum career discipline, institutional authority, and patient ambition. Steady climb to the top. Government and corporate power positions.', hi: 'मकर में शनि (स्वगृह): अधिकतम कैरियर अनुशासन, संस्थागत अधिकार। शीर्ष तक स्थिर चढ़ाई। सरकारी और कॉर्पोरेट शक्ति पद।', sa: 'मकरे शनिः (स्वगृहे): परमम् कैरियरानुशासनम्, सांस्थानिकम् अधिकारम्।' },
    11: { en: 'Saturn in Aquarius (own sign): structured social reform, disciplined group leadership, and systematic achievement of goals. Technology and humanitarian service combined.', hi: 'कुम्भ में शनि (स्वगृह): संरचित सामाजिक सुधार, अनुशासित सामूहिक नेतृत्व। प्रौद्योगिकी और मानवतावादी सेवा का संयोग।', sa: 'कुम्भे शनिः (स्वगृहे): संरचितः सामाजिकसुधारः।' },
    12: { en: 'Saturn in Pisces: spiritual discipline, structured meditation, and service in isolation. Foreign residence through persistent effort. Liberation through sustained practice.', hi: 'मीन में शनि: आध्यात्मिक अनुशासन, संरचित ध्यान। निरन्तर प्रयास से विदेश निवास। निरन्तर साधना से मुक्ति।', sa: 'मीने शनिः: आध्यात्मिकम् अनुशासनं, संरचितं ध्यानम्।' },
  },
  // RAHU (7)
  7: {
    1: { en: 'Rahu in Aries: obsessive ambition and unconventional courage. Driven by worldly desires for identity and recognition. May adopt foreign customs.', hi: 'मेष में राहु: जुनूनी महत्वाकांक्षा और अपरम्परागत साहस। पहचान और मान्यता की सांसारिक इच्छाओं से प्रेरित।', sa: 'मेषे राहुः: जुनूनी महत्त्वाकाङ्क्षा अपरम्परागतं शौर्यं च।' },
    2: { en: 'Rahu in Taurus: intense material desires and unconventional wealth acquisition. Foreign food and luxury fascination. Speech may be deceptive or unusual.', hi: 'वृषभ में राहु: तीव्र भौतिक इच्छाएँ। अपरम्परागत धन अर्जन। विदेशी भोजन और विलासिता का आकर्षण।', sa: 'वृषभे राहुः: तीव्राः भौतिकेच्छाः, अपरम्परागतं धनार्जनम्।' },
    3: { en: 'Rahu in Gemini: obsessive communication and information gathering. Media and technology excellence. Bold, unconventional messaging. Multiple identities possible.', hi: 'मिथुन में राहु: जुनूनी संवाद और सूचना संग्रह। मीडिया और प्रौद्योगिकी में उत्कृष्टता। साहसिक, अपरम्परागत सन्देश।', sa: 'मिथुने राहुः: जुनूनी संवादः सूचनासङ्ग्रहश्च।' },
    4: { en: 'Rahu in Cancer: unusual domestic life and unconventional mother relationship. Foreign property possible. Emotional intensity bordering on obsession.', hi: 'कर्क में राहु: असामान्य घरेलू जीवन। विदेशी सम्पत्ति सम्भव। जुनून की सीमा पर भावनात्मक तीव्रता।', sa: 'कर्के राहुः: असामान्यं गृहजीवनम्।' },
    5: { en: 'Rahu in Leo: obsessive desire for recognition and creative power. Unconventional approach to authority. Children may be exceptional or unusual.', hi: 'सिंह में राहु: मान्यता और रचनात्मक शक्ति की जुनूनी इच्छा। सन्तान असाधारण हो सकती है।', sa: 'सिंहे राहुः: मान्यतायाः रचनात्मिकशक्तेश्च जुनूनी इच्छा।' },
    6: { en: 'Rahu in Virgo: unconventional healing and service methods. Technology in healthcare. Defeating enemies through unusual tactics. Foreign medical practices.', hi: 'कन्या में राहु: अपरम्परागत उपचार और सेवा पद्धतियाँ। स्वास्थ्य सेवा में प्रौद्योगिकी। असामान्य युक्तियों से शत्रुओं की पराजय।', sa: 'कन्यायां राहुः: अपरम्परागताः उपचारसेवापद्धतयः।' },
    7: { en: 'Rahu in Libra: obsessive desire for partnership and social status. Foreign or unconventional spouse. Business success through international connections.', hi: 'तुला में राहु: साझेदारी और सामाजिक प्रतिष्ठा की जुनूनी इच्छा। विदेशी या अपरम्परागत जीवनसाथी।', sa: 'तुलायां राहुः: साझेदार्याः सामाजिकप्रतिष्ठायाश्च जुनूनी इच्छा।' },
    8: { en: 'Rahu in Scorpio: deep obsession with hidden knowledge and power. Sudden transformations. Research into occult and forbidden subjects. Crisis as catalyst for growth.', hi: 'वृश्चिक में राहु: छिपे ज्ञान और शक्ति का गहरा जुनून। अचानक परिवर्तन। गूढ़ विषयों में शोध।', sa: 'वृश्चिके राहुः: गूढज्ञानस्य शक्तेश्च गहनः जुनूनः।' },
    9: { en: 'Rahu in Sagittarius: unconventional philosophy and foreign religious interests. Breaking traditional beliefs. International travel for spiritual exploration.', hi: 'धनु में राहु: अपरम्परागत दर्शन और विदेशी धार्मिक रुचियाँ। पारम्परिक विश्वासों को तोड़ना। आध्यात्मिक अन्वेषण के लिए अन्तरराष्ट्रीय यात्रा।', sa: 'धनुषि राहुः: अपरम्परागतं दर्शनं विदेशीधार्मिकरुचयश्च।' },
    10: { en: 'Rahu in Capricorn: obsessive career ambition and unconventional rise to power. Political success through foreign connections. Fame through innovation.', hi: 'मकर में राहु: जुनूनी कैरियर महत्वाकांक्षा। विदेशी सम्बन्धों से राजनीतिक सफलता। नवाचार से प्रसिद्धि।', sa: 'मकरे राहुः: जुनूनी जीविकामहत्त्वाकाङ्क्षा।' },
    11: { en: 'Rahu in Aquarius: massive gains through technology and networking. Fulfillment of worldly desires through unconventional means. Large social circle with foreign connections.', hi: 'कुम्भ में राहु: प्रौद्योगिकी और नेटवर्किंग से विशाल लाभ। अपरम्परागत साधनों से सांसारिक इच्छाओं की पूर्ति।', sa: 'कुम्भे राहुः: प्रौद्योगिक्या नेटवर्किंगेन च विशालं लाभम्।' },
    12: { en: 'Rahu in Pisces: obsessive spiritual seeking and foreign residence. Vivid dreams and psychic experiences. Liberation through embracing the unknown.', hi: 'मीन में राहु: जुनूनी आध्यात्मिक खोज और विदेश निवास। विविध स्वप्न और मानसिक अनुभव।', sa: 'मीने राहुः: जुनूनी आध्यात्मिकान्वेषणं विदेशनिवासश्च।' },
  },
  // KETU (8)
  8: {
    1: { en: 'Ketu in Aries: past-life warrior energy and spiritual courage. Detached from ego identity. Natural meditation abilities. Mysterious, quiet strength.', hi: 'मेष में केतु: पूर्वजन्म योद्धा ऊर्जा और आध्यात्मिक साहस। अहम् पहचान से विरक्ति। स्वाभाविक ध्यान क्षमता।', sa: 'मेषे केतुः: पूर्वजन्मयोद्धूर्जा आध्यात्मिकशौर्यं च।' },
    2: { en: 'Ketu in Taurus: detachment from material wealth and physical comforts. Past-life mastery over resources. Speech has mystical quality. Family bonds carry karmic weight.', hi: 'वृषभ में केतु: भौतिक धन और शारीरिक सुखों से विरक्ति। वाणी में रहस्यमय गुण। पारिवारिक बन्धनों में कार्मिक भार।', sa: 'वृषभे केतुः: भौतिकधनात् शारीरिकसुखात् च वैराग्यम्।' },
    3: { en: 'Ketu in Gemini: intuitive communication beyond intellectual processing. Past-life writing and speaking skills. Detached from conventional learning.', hi: 'मिथुन में केतु: बौद्धिक प्रक्रिया से परे सहज संवाद। पूर्वजन्म लेखन और वक्तृत्व कौशल।', sa: 'मिथुने केतुः: बौद्धिकप्रक्रियात् परः सहजसंवादः।' },
    4: { en: 'Ketu in Cancer: detachment from conventional home life and emotional dependencies. Past-life mastery over nurturing. Spiritual home practices bring peace.', hi: 'कर्क में केतु: पारम्परिक गृहजीवन और भावनात्मक निर्भरता से विरक्ति। आध्यात्मिक गृह साधनाएँ शान्ति लाती हैं।', sa: 'कर्के केतुः: पारम्परिकगृहजीवनात् भावनात्मिकनिर्भरतातश्च वैराग्यम्।' },
    5: { en: 'Ketu in Leo: detachment from ego recognition and creative spotlight. Past-life spiritual merit manifests as unexpected blessings. Children are old souls.', hi: 'सिंह में केतु: अहम् मान्यता और रचनात्मक प्रकाश से विरक्ति। पूर्वजन्म आध्यात्मिक पुण्य अप्रत्याशित आशीर्वाद के रूप में प्रकट।', sa: 'सिंहे केतुः: अहंमान्यतातः रचनात्मिकप्रकाशातश्च वैराग्यम्।' },
    6: { en: 'Ketu in Virgo: natural healing abilities and past-life service mastery. Overcomes enemies through non-engagement. Detached from petty conflicts.', hi: 'कन्या में केतु: स्वाभाविक उपचार क्षमताएँ। अ-संलग्नता से शत्रुओं पर विजय। छोटे संघर्षों से विरक्ति।', sa: 'कन्यायां केतुः: स्वाभाविक्यः उपचारक्षमताः। असंलग्नतया शत्रुपराजयः।' },
    7: { en: 'Ketu in Libra: detachment from partnership desires. Past-life mastery over relationships. Karmic unions that teach spiritual lessons. Partnerships evolve toward companionship.', hi: 'तुला में केतु: साझेदारी इच्छाओं से विरक्ति। आध्यात्मिक पाठ सिखाने वाले कार्मिक सम्बन्ध।', sa: 'तुलायां केतुः: साझेदारीच्छाभ्यः वैराग्यम्।' },
    8: { en: 'Ketu in Scorpio: profound occult knowledge and natural psychic abilities. Past-life tantric mastery. Deep meditation comes naturally. Transformation without resistance.', hi: 'वृश्चिक में केतु: गहन गूढ़ ज्ञान और स्वाभाविक मानसिक क्षमताएँ। पूर्वजन्म तान्त्रिक प्रवीणता। गहन ध्यान स्वाभाविक।', sa: 'वृश्चिके केतुः: गहनं गूढज्ञानं स्वाभाविकमानसिकक्षमताश्च।' },
    9: { en: 'Ketu in Sagittarius: natural spiritual wisdom without formal education. Inner guru is strong. Detachment from organized religion. Philosophy lived rather than theorized.', hi: 'धनु में केतु: औपचारिक शिक्षा के बिना स्वाभाविक आध्यात्मिक ज्ञान। आन्तरिक गुरु प्रबल। संगठित धर्म से विरक्ति।', sa: 'धनुषि केतुः: औपचारिकशिक्षां विना स्वाभाविकम् आध्यात्मिकज्ञानम्।' },
    10: { en: 'Ketu in Capricorn: detachment from worldly ambition. Career transforms toward meaningful service. Past-life administrative mastery. Success comes through non-attachment.', hi: 'मकर में केतु: सांसारिक महत्वाकांक्षा से विरक्ति। कैरियर सार्थक सेवा की ओर परिवर्तित। अनासक्ति से सफलता।', sa: 'मकरे केतुः: सांसारिकमहत्त्वाकाङ्क्षातः वैराग्यम्।' },
    11: { en: 'Ketu in Aquarius: spiritual gains over material desires. Past-life social reform mastery. True fulfillment through service. Gains come when least expected.', hi: 'कुम्भ में केतु: भौतिक इच्छाओं से अधिक आध्यात्मिक लाभ। सेवा से सच्ची पूर्ति। लाभ जब सबसे कम अपेक्षित हो तब आते हैं।', sa: 'कुम्भे केतुः: भौतिकेच्छाभ्यः अधिकम् आध्यात्मिकं लाभम्।' },
    12: { en: 'Ketu in Pisces: supreme spiritual placement for liberation. Past-life moksha karma ripening. Meditation is natural state. Complete surrender to the divine. Dreams carry messages.', hi: 'मीन में केतु: मुक्ति के लिए सर्वोच्च आध्यात्मिक स्थिति। पूर्वजन्म मोक्ष कर्म पक रहा है। ध्यान स्वाभाविक अवस्था। दिव्य को पूर्ण समर्पण।', sa: 'मीने केतुः: मुक्त्यै सर्वोच्चा आध्यात्मिकस्थितिः। ध्यानं स्वाभाविका अवस्था।' },
  },
};

/** Get planet-in-sign interpretation text for a specific locale */
export function getPlanetInSignText(planetId: number, signIndex: number, locale: Locale): string {
  const entry = PLANET_IN_SIGN[planetId]?.[signIndex];
  if (!entry) return '';
  if (locale === 'sa') return entry.sa || entry.hi;
  return locale === 'hi' ? entry.hi : entry.en;
}
