/**
 * Varga (Divisional Chart) Tippanni — comprehensive per-chart commentary
 * Two sections per chart: (1) Overall Commentary, (2) 1-2 Year Prognosis
 * Reference: BPHS Ch.6-7, Jataka Parijata, Saravali, Phaladeepika
 */

import type { Locale , LocaleText} from '@/types/panchang';
import type { KundaliData, DivisionalChart, PlanetPosition, DashaEntry } from '@/types/kundali';
import { RASHIS } from '@/lib/constants/rashis';
import { generateDashaPrognosis } from './dasha-prognosis';

type Bi = LocaleText;

export interface VargaChartTippanni {
  chart: string;
  label: Bi;
  meaning: Bi;
  strength: 'strong' | 'moderate' | 'weak';
  overallCommentary: Bi;     // Detailed interpretation of this chart
  prognosis: Bi;             // Next 1-2 year forecast
  keyFindings: Bi[];         // Bullet points
}

export interface VargaSynthesis {
  overall: Bi;
  strongAreas: Bi[];
  weakAreas: Bi[];
  vargaInsights: VargaChartTippanni[];
}

// ─── Helpers ────────────────────────────────────────────────────────────────

const PN: Record<number, Bi> = {
  0: { en: 'Sun', hi: 'सूर्य', sa: 'सूर्य', mai: 'सूर्य', mr: 'सूर्य', ta: 'சூரியன்', te: 'సూర్యుడు', bn: 'সূর্য', kn: 'ಸೂರ್ಯ', gu: 'સૂર્ય' }, 1: { en: 'Moon', hi: 'चन्द्र', sa: 'चन्द्र', mai: 'चन्द्र', mr: 'चन्द्र', ta: 'சந்திரன்', te: 'చంద్రుడు', bn: 'চন্দ্র', kn: 'ಚಂದ್ರ', gu: 'ચંદ્ર' },
  2: { en: 'Mars', hi: 'मंगल', sa: 'मंगल', mai: 'मंगल', mr: 'मंगल', ta: 'செவ்வாய்', te: 'కుజుడు', bn: 'মঙ্গল', kn: 'ಮಂಗಳ', gu: 'મંગળ' }, 3: { en: 'Mercury', hi: 'बुध', sa: 'बुध', mai: 'बुध', mr: 'बुध', ta: 'புதன்', te: 'బుధుడు', bn: 'বুধ', kn: 'ಬುಧ', gu: 'બુધ' },
  4: { en: 'Jupiter', hi: 'गुरु', sa: 'गुरु', mai: 'गुरु', mr: 'गुरु', ta: 'குரு', te: 'గురుడు', bn: 'বৃহস্পতি', kn: 'ಗುರು', gu: 'ગુરુ' }, 5: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्र', mai: 'शुक्र', mr: 'शुक्र', ta: 'சுக்கிரன்', te: 'శుక్రుడు', bn: 'শুক্র', kn: 'ಶುಕ್ರ', gu: 'શુક્ર' },
  6: { en: 'Saturn', hi: 'शनि', sa: 'शनि', mai: 'शनि', mr: 'शनि', ta: 'சனி', te: 'శని', bn: 'শনি', kn: 'ಶನಿ', gu: 'શનિ' }, 7: { en: 'Rahu', hi: 'राहु', sa: 'राहु', mai: 'राहु', mr: 'राहु', ta: 'ராகு', te: 'రాహువు', bn: 'রাহু', kn: 'ರಾಹು', gu: 'રાહુ' },
  8: { en: 'Ketu', hi: 'केतु', sa: 'केतु', mai: 'केतु', mr: 'केतु', ta: 'கேது', te: 'కేతువు', bn: 'কেতু', kn: 'ಕೇತು', gu: 'કેતુ' },
};

const BENEFICS = new Set([1, 3, 4, 5]);
const MALEFICS = new Set([0, 2, 6, 7, 8]);
const KENDRAS = new Set([1, 4, 7, 10]);
const TRIKONAS = new Set([1, 5, 9]);
const DUSTHANAS = new Set([6, 8, 12]);
const GOOD = new Set([1, 2, 3, 4, 5, 7, 9, 10, 11]);

function signLord(sign: number): number {
  return ({ 1: 2, 2: 5, 3: 3, 4: 1, 5: 0, 6: 3, 7: 5, 8: 2, 9: 4, 10: 6, 11: 6, 12: 4 } as Record<number, number>)[sign] ?? 0;
}

function planetsIn(chart: { houses: number[][] }, house: number): number[] {
  return chart.houses[(house - 1) % 12] || [];
}

function ord(n: number): string {
  const s = ['th', 'st', 'nd', 'rd'];
  return n + (s[(n - 20) % 10] || s[n] || s[0]);
}

function rashiName(sign: number, locale: string): string {
  return RASHIS[(sign - 1) % 12]?.name[locale as Locale] || '';
}

function findCurrentDasha(dashas: DashaEntry[]): { maha: DashaEntry; antar?: DashaEntry } | null {
  const now = new Date();
  for (const d of dashas) {
    if (now >= new Date(d.startDate) && now <= new Date(d.endDate)) {
      let antar: DashaEntry | undefined;
      if (d.subPeriods) {
        antar = d.subPeriods.find(s => now >= new Date(s.startDate) && now <= new Date(s.endDate));
      }
      return { maha: d, antar };
    }
  }
  return null;
}

// Planet name -> id mapping
function planetId(name: string): number {
  const map: Record<string, number> = { Sun: 0, Moon: 1, Mars: 2, Mercury: 3, Jupiter: 4, Venus: 5, Saturn: 6, Rahu: 7, Ketu: 8 };
  return map[name] ?? -1;
}

// ─── Drekkana faces (36 archetypes — Varahamihira, Brihat Jataka Ch.27) ────
// Index = (sign-1)*3 + (face-1), face = floor((longitude%30)/10)+1, sign = floor(longitude/30)+1

const DREKKANA_FACES: Array<{ archetype: Bi; quality: Bi }> = [
  // Aries: faces 1-3 (index 0-2)
  { archetype: { en: 'The Warrior', hi: 'योद्धा', sa: 'योद्धा', mai: 'योद्धा', mr: 'योद्धा', ta: 'போர்வீரன்', te: 'యోధుడు', bn: 'যোদ্ধা', kn: 'ಯೋಧ', gu: 'યોદ્ધા' }, quality: { en: 'Aggressive pioneer; bold, impulsive, initiating force — planet here gains martial vigour and competitive drive.', hi: 'आक्रामक अग्रदूत; साहसी, आवेगशील, प्रारंभ-शक्ति — यहाँ ग्रह युद्ध-वृत्ति और प्रतिस्पर्धी प्रेरणा पाता है।', sa: 'आक्रामक अग्रदूत; साहसी, आवेगशील, प्रारंभ-शक्ति — यहाँ ग्रह युद्ध-वृत्ति और प्रतिस्पर्धी प्रेरणा पाता है।', mai: 'आक्रामक अग्रदूत; साहसी, आवेगशील, प्रारंभ-शक्ति — यहाँ ग्रह युद्ध-वृत्ति और प्रतिस्पर्धी प्रेरणा पाता है।', mr: 'आक्रामक अग्रदूत; साहसी, आवेगशील, प्रारंभ-शक्ति — यहाँ ग्रह युद्ध-वृत्ति और प्रतिस्पर्धी प्रेरणा पाता है।', ta: 'ஆக்ரமிப்பு முன்னோடி; துணிச்சலான, அவசரமான, தொடக்க சக்தி — இங்கு கிரகம் போர் வீரியமும் போட்டி உந்துதலும் பெறும்.', te: 'దూకుడు అగ్రగామి; సాహసి, ఆవేశపూరిత, ప్రారంభ శక్తి — ఇక్కడ గ్రహం యుద్ధ శక్తి మరియు పోటీ ఉత్సాహం పొందుతుంది.', bn: 'আক্রমণাত্মক অগ্রদূত; সাহসী, আবেগপ্রবণ, সূচনাকারী শক্তি — এখানে গ্রহ যুদ্ধ বীর্য ও প্রতিযোগী প্রেরণা লাভ করে।', kn: 'ಆಕ್ರಮಣಕಾರಿ ಮುಂಚೂಣಿ; ಧೈರ್ಯಶಾಲಿ, ಆವೇಶಪೂರ್ಣ, ಪ್ರಾರಂಭ ಶಕ್ತಿ — ಇಲ್ಲಿ ಗ್ರಹ ಯುದ್ಧ ವೀರ್ಯ ಮತ್ತು ಸ್ಪರ್ಧಾತ್ಮಕ ಚಾಲನೆ ಪಡೆಯುತ್ತದೆ.', gu: 'આક્રમક અગ્રદૂત; સાહસી, આવેગપૂર્ણ, પ્રારંભ શક્તિ — અહીં ગ્રહ યુદ્ધ વીર્ય અને સ્પર્ધાત્મક પ્રેરણા મેળવે છે.' } },
  { archetype: { en: 'The Amazon', hi: 'योद्धा-स्त्री', sa: 'योद्धा-स्त्री', mai: 'योद्धा-स्त्री', mr: 'योद्धा-स्त्री', ta: 'அமேசான் போர்வீரி', te: 'అమెజాన్ యోధురాలు', bn: 'অ্যামাজন যোদ্ধা', kn: 'ಅಮೆಜಾನ್ ಯೋಧೆ', gu: 'એમેઝોન યોદ્ધા' }, quality: { en: 'Fierce feminine energy in conflict; emotional battles, protective instincts, warrior-mother archetype.', hi: 'संघर्ष में तीव्र स्त्री-ऊर्जा; भावनात्मक युद्ध, सुरक्षात्मक वृत्ति, योद्धा-माता आदर्श।', sa: 'संघर्ष में तीव्र स्त्री-ऊर्जा; भावनात्मक युद्ध, सुरक्षात्मक वृत्ति, योद्धा-माता आदर्श।', mai: 'संघर्ष में तीव्र स्त्री-ऊर्जा; भावनात्मक युद्ध, सुरक्षात्मक वृत्ति, योद्धा-माता आदर्श।', mr: 'संघर्ष में तीव्र स्त्री-ऊर्जा; भावनात्मक युद्ध, सुरक्षात्मक वृत्ति, योद्धा-माता आदर्श।', ta: 'போரில் கடும் பெண் ஆற்றல்; உணர்ச்சிப் போர்கள், பாதுகாப்பு உள்ளுணர்வுகள், போர்வீர-தாய் முன்மாதிரி.', te: 'సంఘర్షణలో తీవ్ర స్త్రీ శక్తి; భావోద్వేగ యుద్ధాలు, రక్షణ ప్రేరణలు, యోధ-తల్లి ఆదర్శం.', bn: 'সংঘর্ষে তীব্র নারী শক্তি; আবেগপূর্ণ যুদ্ধ, রক্ষণাত্মক সহজাত, যোদ্ধা-মাতা আদর্শ।', kn: 'ಸಂಘರ್ಷದಲ್ಲಿ ತೀವ್ರ ಸ್ತ್ರೀ ಶಕ್ತಿ; ಭಾವನಾತ್ಮಕ ಯುದ್ಧ, ರಕ್ಷಣಾತ್ಮಕ ಪ್ರವೃತ್ತಿ, ಯೋಧ-ತಾಯಿ ಮಾದರಿ.', gu: 'સંઘર્ષમાં તીવ્ર સ્ત્રી ઊર્જા; ભાવનાત્મક યુદ્ધો, રક્ષણાત્મક સહજવૃત્તિ, યોદ્ધા-માતા આદર્શ.' } },
  { archetype: { en: 'The Armed Noble', hi: 'सशस्त्र अभिजात', sa: 'सशस्त्र अभिजात', mai: 'सशस्त्र अभिजात', mr: 'सशस्त्र अभिजात', ta: 'ஆயுதம் ஏந்திய பிரபு', te: 'సాయుధ ప్రభువు', bn: 'সশস্ত্র আভিজাত্য', kn: 'ಸಶಸ್ತ್ರ ಶ್ರೀಮಂತ', gu: 'સશસ્ત્ર કુલીન' }, quality: { en: 'Disciplined martial authority; force combined with status — leadership through demonstrated courage.', hi: 'अनुशासित सैन्य-अधिकार; बल और प्रतिष्ठा का संयोग — सिद्ध साहस द्वारा नेतृत्व।', sa: 'अनुशासित सैन्य-अधिकार; बल और प्रतिष्ठा का संयोग — सिद्ध साहस द्वारा नेतृत्व।', mai: 'अनुशासित सैन्य-अधिकार; बल और प्रतिष्ठा का संयोग — सिद्ध साहस द्वारा नेतृत्व।', mr: 'अनुशासित सैन्य-अधिकार; बल और प्रतिष्ठा का संयोग — सिद्ध साहस द्वारा नेतृत्व।', ta: 'ஒழுக்கமான போர் அதிகாரம்; பலமும் அந்தஸ்தும் இணைந்தது — நிரூபிக்கப்பட்ட தைரியத்தின் மூலம் தலைமை.', te: 'క్రమశిక్షణతో కూడిన సైనిక అధికారం; బలం మరియు హోదా కలయిక — నిరూపిత ధైర్యం ద్వారా నాయకత్వం.', bn: 'সুশৃঙ্খল সামরিক কর্তৃত্ব; বল ও মর্যাদার সমন্বয় — প্রমাণিত সাহসের মাধ্যমে নেতৃত্ব।', kn: 'ಶಿಸ್ತಿನ ಸೈನಿಕ ಅಧಿಕಾರ; ಬಲ ಮತ್ತು ಸ್ಥಾನಮಾನದ ಸಂಯೋಜನೆ — ಸಾಬೀತಾದ ಧೈರ್ಯದ ಮೂಲಕ ನಾಯಕತ್ವ.', gu: 'અનુશાસિત લશ્કરી સત્તા; બળ અને દરજ્જાનું મિશ્રણ — સાબિત હિંમત દ્વારા નેતૃત્વ.' } },
  // Taurus: faces 1-3 (index 3-5)
  { archetype: { en: 'The Adorned Beauty', hi: 'अलंकृत सौंदर्य', sa: 'अलंकृत सौंदर्य', mai: 'अलंकृत सौंदर्य', mr: 'अलंकृत सौंदर्य', ta: 'அலங்கரிக்கப்பட்ட அழகி', te: 'అలంకరించబడిన సుందరి', bn: 'অলংকৃত সুন্দরী', kn: 'ಅಲಂಕೃತ ಸುಂದರಿ', gu: 'અલંકૃત સુંદરી' }, quality: { en: 'Sensual abundance; love of beauty, art, and pleasure — planet here gains receptivity and magnetic attraction.', hi: 'इंद्रिय-प्राचुर्य; सौंदर्य, कला और आनंद-प्रेम — यहाँ ग्रह ग्रहणशीलता और आकर्षण पाता है।', sa: 'इंद्रिय-प्राचुर्य; सौंदर्य, कला और आनंद-प्रेम — यहाँ ग्रह ग्रहणशीलता और आकर्षण पाता है।', mai: 'इंद्रिय-प्राचुर्य; सौंदर्य, कला और आनंद-प्रेम — यहाँ ग्रह ग्रहणशीलता और आकर्षण पाता है।', mr: 'इंद्रिय-प्राचुर्य; सौंदर्य, कला और आनंद-प्रेम — यहाँ ग्रह ग्रहणशीलता और आकर्षण पाता है।', ta: 'புலன் நிறைவு; அழகு, கலை மற்றும் இன்பத்தின் மீது காதல் — இங்கு கிரகம் ஏற்புத்திறனும் காந்த ஈர்ப்பும் பெறும்.', te: 'ఇంద్రియ సమృద్ధి; అందం, కళ మరియు ఆనందం పట్ల ప్రేమ — ఇక్కడ గ్రహం గ్రహణశీలత మరియు ఆకర్షణ శక్తి పొందుతుంది.', bn: 'ইন্দ্রিয় প্রাচুর্য; সৌন্দর্য, কলা ও আনন্দ প্রেম — এখানে গ্রহ গ্রহণশীলতা ও চৌম্বকীয় আকর্ষণ লাভ করে।', kn: 'ಇಂದ್ರಿಯ ಸಮೃದ್ಧಿ; ಸೌಂದರ್ಯ, ಕಲೆ ಮತ್ತು ಸುಖದ ಪ್ರೀತಿ — ಇಲ್ಲಿ ಗ್ರಹ ಗ್ರಹಣಶೀಲತೆ ಮತ್ತು ಆಕರ್ಷಣೆ ಪಡೆಯುತ್ತದೆ.', gu: 'ઇન્દ્રિય સમૃદ્ધિ; સૌંદર્ય, કલા અને આનંદનો પ્રેમ — અહીં ગ્રહ ગ્રહણશીલતા અને ચુંબકીય આકર્ષણ મેળવે છે.' } },
  { archetype: { en: 'The Toiler', hi: 'परिश्रमी', sa: 'परिश्रमी', mai: 'परिश्रमी', mr: 'परिश्रमी', ta: 'உழைப்பாளி', te: 'శ్రమజీవి', bn: 'পরিশ্রমী', kn: 'ಶ್ರಮಜೀವಿ', gu: 'પરિશ્રમી' }, quality: { en: 'Patient builder; steady accumulation through persistent, earthy effort — productive and reliable.', hi: 'धैर्यवान निर्माता; निरंतर भूमिगत प्रयास से संचय — उत्पादक और विश्वसनीय।', sa: 'धैर्यवान निर्माता; निरंतर भूमिगत प्रयास से संचय — उत्पादक और विश्वसनीय।', mai: 'धैर्यवान निर्माता; निरंतर भूमिगत प्रयास से संचय — उत्पादक और विश्वसनीय।', mr: 'धैर्यवान निर्माता; निरंतर भूमिगत प्रयास से संचय — उत्पादक और विश्वसनीय।', ta: 'பொறுமையான கட்டுமானகர்; நிலையான, நிலம் சார்ந்த முயற்சியின் மூலம் நிலையான சேர்க்கை — உற்பத்தி மற்றும் நம்பகமான.', te: 'ఓపికగల నిర్మాత; నిరంతర, భూమి సంబంధ ప్రయత్నం ద్వారా స్థిర సంచయం — ఉత్పాదక మరియు నమ్మదగిన.', bn: 'ধৈর্যশীল নির্মাতা; অবিচল, মাটি-সংলগ্ন প্রচেষ্টায় স্থিতিশীল সঞ্চয় — উৎপাদনশীল ও নির্ভরযোগ্য।', kn: 'ತಾಳ್ಮೆಯ ನಿರ್ಮಾತ; ನಿರಂತರ, ಭೂಮಿ ಸಂಬಂಧಿ ಪ್ರಯತ್ನದ ಮೂಲಕ ಸ್ಥಿರ ಸಂಗ್ರಹ — ಉತ್ಪಾದಕ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ.', gu: 'ધીરજવાન નિર્માતા; સતત, પૃથ્વી તત્વ મહેનતથી સ્થિર સંચય — ઉત્પાદક અને વિશ્વસનીય.' } },
  { archetype: { en: 'The Steadfast Guardian', hi: 'अटल संरक्षक', sa: 'अटल संरक्षक', mai: 'अटल संरक्षक', mr: 'अटल संरक्षक', ta: 'உறுதியான காவலர்', te: 'స్థిర సంరక్షకుడు', bn: 'অটল অভিভাবক', kn: 'ಸ್ಥಿರ ಸಂರಕ್ಷಕ', gu: 'અટલ રક્ષક' }, quality: { en: 'Stubborn protector of resources; fierce when provoked, immovable in defence of what is valued.', hi: 'संसाधनों का जिद्दी रक्षक; उकसाने पर भयंकर, मूल्यवान वस्तु की रक्षा में अडिग।', sa: 'संसाधनों का जिद्दी रक्षक; उकसाने पर भयंकर, मूल्यवान वस्तु की रक्षा में अडिग।', mai: 'संसाधनों का जिद्दी रक्षक; उकसाने पर भयंकर, मूल्यवान वस्तु की रक्षा में अडिग।', mr: 'संसाधनों का जिद्दी रक्षक; उकसाने पर भयंकर, मूल्यवान वस्तु की रक्षा में अडिग।', ta: 'வளங்களின் பிடிவாத பாதுகாவலர்; தூண்டப்பட்டால் கடும், மதிக்கப்படுவதன் பாதுகாப்பில் அசையாத.', te: 'వనరుల మొండి రక్షకుడు; రెచ్చగొట్టినప్పుడు భయంకరమైన, విలువైన వాటి రక్షణలో చలించని.', bn: 'সম্পদের জেদি রক্ষক; উত্তেজিত হলে ভয়ংকর, মূল্যবান বস্তুর রক্ষায় অটল।', kn: 'ಸಂಪನ್ಮೂಲಗಳ ಹಠಮಾರಿ ರಕ್ಷಕ; ಕೆರಳಿಸಿದಾಗ ಉಗ್ರ, ಮೌಲ್ಯಯುತ ವಸ್ತುಗಳ ರಕ್ಷಣೆಯಲ್ಲಿ ಅಚಲ.', gu: 'સંસાધનોના જિદ્દી રક્ષક; ઉશ્કેરાયેલ ત્યારે ઉગ્ર, મૂલ્યવાન વસ્તુના રક્ષણમાં અડગ.' } },
  // Gemini: faces 1-3 (index 6-8)
  { archetype: { en: 'The Learned Maiden', hi: 'विद्वान कन्या', sa: 'विद्वान कन्या', mai: 'विद्वान कन्या', mr: 'विद्वान कन्या', ta: 'கற்ற கன்னி', te: 'విద్యావతి కన్య', bn: 'বিদুষী কন্যা', kn: 'ವಿದ್ಯಾವಂತ ಕನ್ಯೆ', gu: 'વિદુષી કન્યા' }, quality: { en: 'Intellectual beauty; writing, communication, and mental agility — charm combined with quick wit.', hi: 'बौद्धिक सौंदर्य; लेखन, संचार और मानसिक चपलता — आकर्षण और तीव्र बुद्धि का संयोग।', sa: 'बौद्धिक सौंदर्य; लेखन, संचार और मानसिक चपलता — आकर्षण और तीव्र बुद्धि का संयोग।', mai: 'बौद्धिक सौंदर्य; लेखन, संचार और मानसिक चपलता — आकर्षण और तीव्र बुद्धि का संयोग।', mr: 'बौद्धिक सौंदर्य; लेखन, संचार और मानसिक चपलता — आकर्षण और तीव्र बुद्धि का संयोग।', ta: 'அறிவார்ந்த அழகு; எழுத்து, தொடர்பு மற்றும் மன சுறுசுறுப்பு — கவர்ச்சியும் விரைவான புத்தியும் இணைந்தது.', te: 'బౌద్ధిక సౌందర్యం; రాత, సమాచారం మరియు మానసిక చురుకుదనం — మోహం మరియు త్వరిత బుద్ధి కలయిక.', bn: 'বৌদ্ধিক সৌন্দর্য; লেখা, যোগাযোগ ও মানসিক চপলতা — আকর্ষণ ও দ্রুত বুদ্ধির সমন্বয়।', kn: 'ಬೌದ್ಧಿಕ ಸೌಂದರ್ಯ; ಬರವಣಿಗೆ, ಸಂವಹನ ಮತ್ತು ಮಾನಸಿಕ ಚುರುಕುತನ — ಆಕರ್ಷಣೆ ಮತ್ತು ಕ್ಷಿಪ್ರ ಬುದ್ಧಿಯ ಸಂಯೋಜನೆ.', gu: 'બૌદ્ધિક સૌંદર્ય; લેખન, સંવાદ અને માનસિક ચપળતા — આકર્ષણ અને ત્વરિત બુદ્ધિનું મિશ્રણ.' } },
  { archetype: { en: 'The Merchant-Scholar', hi: 'व्यापारी-विद्वान', sa: 'व्यापारी-विद्वान', mai: 'व्यापारी-विद्वान', mr: 'व्यापारी-विद्वान', ta: 'வணிக-அறிஞர்', te: 'వ్యాపారి-విద్వాంసుడు', bn: 'বণিক-বিদ্বান', kn: 'ವ್ಯಾಪಾರಿ-ವಿದ್ವಾಂಸ', gu: 'વેપારી-વિદ્વાન' }, quality: { en: 'Commercial intelligence; knowledge united with practical exchange — versatile communicator and trader.', hi: 'वाणिज्यिक बुद्धि; ज्ञान और व्यावहारिक विनिमय का एकीकरण — बहुमुखी संचारक।', sa: 'वाणिज्यिक बुद्धि; ज्ञान और व्यावहारिक विनिमय का एकीकरण — बहुमुखी संचारक।', mai: 'वाणिज्यिक बुद्धि; ज्ञान और व्यावहारिक विनिमय का एकीकरण — बहुमुखी संचारक।', mr: 'वाणिज्यिक बुद्धि; ज्ञान और व्यावहारिक विनिमय का एकीकरण — बहुमुखी संचारक।', ta: 'வணிக அறிவு; நடைமுறை பரிமாற்றத்துடன் இணைந்த ஞானம் — பல்திறன் தொடர்பாளர் மற்றும் வணிகர்.', te: 'వాణిజ్య బుద్ధి; ఆచరణాత్మక వినిమయంతో జ్ఞానం — బహుముఖ సంభాషకుడు మరియు వ్యాపారి.', bn: 'বাণিজ্যিক বুদ্ধি; ব্যবহারিক বিনিময়ের সাথে জ্ঞান — বহুমুখী যোগাযোগকারী ও বণিক।', kn: 'ವಾಣಿಜ್ಯ ಬುದ್ಧಿ; ಪ್ರಾಯೋಗಿಕ ವಿನಿಮಯದೊಂದಿಗೆ ಜ್ಞಾನ — ಬಹುಮುಖ ಸಂವಹನಕಾರ ಮತ್ತು ವ್ಯಾಪಾರಿ.', gu: 'વાણિજ્યિક બુદ્ધિ; વ્યવહારિક વિનિમય સાથે જ્ઞાન — બહુમુખી સંવાદકાર અને વેપારી.' } },
  { archetype: { en: 'The Focused Archer', hi: 'एकाग्र धनुर्धर', sa: 'एकाग्र धनुर्धर', mai: 'एकाग्र धनुर्धर', mr: 'एकाग्र धनुर्धर', ta: 'கவனமிக்க வில்லாளன்', te: 'ఏకాగ్ర విలుకాడు', bn: 'একাগ্র ধনুর্ধর', kn: 'ಏಕಾಗ್ರ ಧನುರ್ಧಾರಿ', gu: 'એકાગ્ર ધનુર્ધર' }, quality: { en: 'Sharp mental aim; precision in argument and analysis — debates skillfully, cuts to the truth.', hi: 'तीव्र मानसिक लक्ष्य; तर्क और विश्लेषण में सटीकता — कुशल वाद-विवाद, सत्य की खोज।', sa: 'तीव्र मानसिक लक्ष्य; तर्क और विश्लेषण में सटीकता — कुशल वाद-विवाद, सत्य की खोज।', mai: 'तीव्र मानसिक लक्ष्य; तर्क और विश्लेषण में सटीकता — कुशल वाद-विवाद, सत्य की खोज।', mr: 'तीव्र मानसिक लक्ष्य; तर्क और विश्लेषण में सटीकता — कुशल वाद-विवाद, सत्य की खोज।', ta: 'கூர்மையான மன இலக்கு; வாதம் மற்றும் பகுப்பாய்வில் துல்லியம் — திறமையாக விவாதிக்கும், உண்மையை அடையும்.', te: 'తీక్షణమైన మానసిక లక్ష్యం; వాదన మరియు విశ్లేషణలో ఖచ్చితత్వం — నైపుణ్యంగా చర్చిస్తుంది, సత్యాన్ని చేరుకుంటుంది.', bn: 'তীক্ষ্ণ মানসিক লক্ষ্য; যুক্তি ও বিশ্লেষণে নির্ভুলতা — দক্ষভাবে বিতর্ক করে, সত্যে পৌঁছায়।', kn: 'ತೀಕ್ಷ್ಣ ಮಾನಸಿಕ ಗುರಿ; ವಾದ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿ ನಿಖರತೆ — ಕುಶಲವಾಗಿ ಚರ್ಚಿಸುತ್ತದೆ, ಸತ್ಯವನ್ನು ತಲುಪುತ್ತದೆ.', gu: 'તીક્ષ્ણ માનસિક લક્ષ્ય; તર્ક અને વિશ્લેષણમાં ચોકસાઈ — કુશળતાથી ચર્ચા કરે છે, સત્ય સુધી પહોંચે છે.' } },
  // Cancer: faces 1-3 (index 9-11)
  { archetype: { en: 'The Nurturing Mother', hi: 'पोषण-माता', sa: 'पोषण-माता', mai: 'पोषण-माता', mr: 'पोषण-माता', ta: 'பராமரிக்கும் தாய்', te: 'పోషించే తల్లి', bn: 'পালনকারিণী মাতা', kn: 'ಪೋಷಿಸುವ ತಾಯಿ', gu: 'પાલનકારી માતા' }, quality: { en: 'Deep nourishment and care; emotional intuition, psychic receptivity, and protective love.', hi: 'गहरा पोषण और देखभाल; भावनात्मक अंतर्ज्ञान, मानसिक ग्रहणशीलता और सुरक्षात्मक प्रेम।', sa: 'गहरा पोषण और देखभाल; भावनात्मक अंतर्ज्ञान, मानसिक ग्रहणशीलता और सुरक्षात्मक प्रेम।', mai: 'गहरा पोषण और देखभाल; भावनात्मक अंतर्ज्ञान, मानसिक ग्रहणशीलता और सुरक्षात्मक प्रेम।', mr: 'गहरा पोषण और देखभाल; भावनात्मक अंतर्ज्ञान, मानसिक ग्रहणशीलता और सुरक्षात्मक प्रेम।', ta: 'ஆழ்ந்த போஷாக்கு மற்றும் பராமரிப்பு; உணர்ச்சி உள்ளுணர்வு, மன ஏற்புத்திறன் மற்றும் பாதுகாப்பு அன்பு.', te: 'లోతైన పోషణ మరియు సంరక్షణ; భావోద్వేగ సహజ జ్ఞానం, మానసిక గ్రహణశీలత మరియు రక్షణాత్మక ప్రేమ.', bn: 'গভীর পোষণ ও যত্ন; আবেগীয় অন্তর্দৃষ্টি, মানসিক গ্রহণশীলতা ও রক্ষণাত্মক প্রেম।', kn: 'ಆಳವಾದ ಪೋಷಣೆ ಮತ್ತು ಆರೈಕೆ; ಭಾವನಾತ್ಮಕ ಅಂತಃಪ್ರಜ್ಞೆ, ಮಾನಸಿಕ ಗ್ರಹಣಶೀಲತೆ ಮತ್ತು ರಕ್ಷಣಾತ್ಮಕ ಪ್ರೀತಿ.', gu: 'ઊંડું પોષણ અને સંભાળ; ભાવનાત્મક અંતર્જ્ઞાન, માનસિક ગ્રહણશીલતા અને રક્ષણાત્મક પ્રેમ.' } },
  { archetype: { en: 'The Serpent Keeper', hi: 'नाग-पालक', sa: 'नाग-पालक', mai: 'नाग-पालक', mr: 'नाग-पालक', ta: 'நாக பாதுகாவலர்', te: 'నాగ రక్షకుడు', bn: 'নাগ পালক', kn: 'ನಾಗ ಪಾಲಕ', gu: 'નાગ પાલક' }, quality: { en: 'Holder of hidden emotional power; karmic wisdom through suffering, occult sensitivity.', hi: 'छिपी भावनात्मक शक्ति का धारक; कष्ट से कार्मिक ज्ञान, गुप्त संवेदनशीलता।', sa: 'छिपी भावनात्मक शक्ति का धारक; कष्ट से कार्मिक ज्ञान, गुप्त संवेदनशीलता।', mai: 'छिपी भावनात्मक शक्ति का धारक; कष्ट से कार्मिक ज्ञान, गुप्त संवेदनशीलता।', mr: 'छिपी भावनात्मक शक्ति का धारक; कष्ट से कार्मिक ज्ञान, गुप्त संवेदनशीलता।', ta: 'மறைக்கப்பட்ட உணர்ச்சி சக்தியின் உரிமையாளர்; துன்பத்தின் மூலம் வினை ஞானம், மறைபொருள் உணர்திறன்.', te: 'దాచిన భావోద్వేగ శక్తి యొక్క ధారి; బాధ ద్వారా కర్మ జ్ఞానం, గూఢ సున్నితత్వం.', bn: 'লুকানো আবেগের শক্তির ধারক; কষ্টের মাধ্যমে কার্মিক জ্ঞান, গুপ্ত সংবেদনশীলতা।', kn: 'ಅಡಗಿರುವ ಭಾವನಾತ್ಮಕ ಶಕ್ತಿಯ ಧಾರಕ; ನೋವಿನ ಮೂಲಕ ಕಾರ್ಮಿಕ ಜ್ಞಾನ, ಗೂಢ ಸಂವೇದನೆ.', gu: 'છુપાયેલી ભાવનાત્મક શક્તિનો ધારક; દુઃખ દ્વારા કાર્મિક જ્ઞાન, ગૂઢ સંવેદનશીલતા.' } },
  { archetype: { en: 'The Weeping Woman', hi: 'करुणा-नारी', sa: 'करुणा-नारी', mai: 'करुणा-नारी', mr: 'करुणा-नारी', ta: 'The Weeping Woman', te: 'The Weeping Woman', bn: 'The Weeping Woman', kn: 'The Weeping Woman', gu: 'The Weeping Woman' }, quality: { en: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.', hi: 'गहरी भावनात्मक संवेदनशीलता; शोक से करुणा — गहरी सहानुभूति और भावनात्मक बुद्धि।', sa: 'गहरी भावनात्मक संवेदनशीलता; शोक से करुणा — गहरी सहानुभूति और भावनात्मक बुद्धि।', mai: 'गहरी भावनात्मक संवेदनशीलता; शोक से करुणा — गहरी सहानुभूति और भावनात्मक बुद्धि।', mr: 'गहरी भावनात्मक संवेदनशीलता; शोक से करुणा — गहरी सहानुभूति और भावनात्मक बुद्धि।', ta: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.', te: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.', bn: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.', kn: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.', gu: 'Deep emotional sensitivity; grief transformed into compassion — profound empathy and emotional intelligence.' } },
  // Leo: faces 1-3 (index 12-14)
  { archetype: { en: 'The Crowned King', hi: 'मुकुटधारी राजा', sa: 'मुकुटधारी राजा', mai: 'मुकुटधारी राजा', mr: 'मुकुटधारी राजा', ta: 'The Crowned King', te: 'The Crowned King', bn: 'The Crowned King', kn: 'The Crowned King', gu: 'The Crowned King' }, quality: { en: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.', hi: 'राजसी प्राकृतिक अधिकार; नेतृत्व, प्रकाश और प्रेरणा के लिए जन्मे — प्रभावशाली उपस्थिति।', sa: 'राजसी प्राकृतिक अधिकार; नेतृत्व, प्रकाश और प्रेरणा के लिए जन्मे — प्रभावशाली उपस्थिति।', mai: 'राजसी प्राकृतिक अधिकार; नेतृत्व, प्रकाश और प्रेरणा के लिए जन्मे — प्रभावशाली उपस्थिति।', mr: 'राजसी प्राकृतिक अधिकार; नेतृत्व, प्रकाश और प्रेरणा के लिए जन्मे — प्रभावशाली उपस्थिति।', ta: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.', te: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.', bn: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.', kn: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.', gu: 'Regal natural authority; born to lead, radiate, and inspire — commanding presence and dignity.' } },
  { archetype: { en: 'The Blazing Champion', hi: 'ज्वलंत योद्धा', sa: 'ज्वलंत योद्धा', mai: 'ज्वलंत योद्धा', mr: 'ज्वलंत योद्धा', ta: 'The Blazing Champion', te: 'The Blazing Champion', bn: 'The Blazing Champion', kn: 'The Blazing Champion', gu: 'The Blazing Champion' }, quality: { en: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.', hi: 'तीव्र सौर-गर्व; नाटकीय कार्य और सम्मान की भावुक रक्षा में व्यक्त शक्ति।', sa: 'तीव्र सौर-गर्व; नाटकीय कार्य और सम्मान की भावुक रक्षा में व्यक्त शक्ति।', mai: 'तीव्र सौर-गर्व; नाटकीय कार्य और सम्मान की भावुक रक्षा में व्यक्त शक्ति।', mr: 'तीव्र सौर-गर्व; नाटकीय कार्य और सम्मान की भावुक रक्षा में व्यक्त शक्ति।', ta: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.', te: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.', bn: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.', kn: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.', gu: 'Fierce solar pride; power expressed through dramatic action, passionate defence of honour.' } },
  { archetype: { en: 'The Ritual King', hi: 'अनुष्ठान-राजा', sa: 'अनुष्ठान-राजा', mai: 'अनुष्ठान-राजा', mr: 'अनुष्ठान-राजा', ta: 'The Ritual King', te: 'The Ritual King', bn: 'The Ritual King', kn: 'The Ritual King', gu: 'The Ritual King' }, quality: { en: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.', hi: 'धर्म द्वारा पवित्र शक्ति; समारोह, परंपरा और दिव्य-आदेश से शासन — राजकीय उदारता।', sa: 'धर्म द्वारा पवित्र शक्ति; समारोह, परंपरा और दिव्य-आदेश से शासन — राजकीय उदारता।', mai: 'धर्म द्वारा पवित्र शक्ति; समारोह, परंपरा और दिव्य-आदेश से शासन — राजकीय उदारता।', mr: 'धर्म द्वारा पवित्र शक्ति; समारोह, परंपरा और दिव्य-आदेश से शासन — राजकीय उदारता।', ta: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.', te: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.', bn: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.', kn: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.', gu: 'Power sanctified by dharma; rulership through ceremony, tradition, and divine mandate — kingly magnanimity.' } },
  // Virgo: faces 1-3 (index 15-17)
  { archetype: { en: 'The Grain Maiden', hi: 'धान्य-कन्या', sa: 'धान्य-कन्या', mai: 'धान्य-कन्या', mr: 'धान्य-कन्या', ta: 'The Grain Maiden', te: 'The Grain Maiden', bn: 'The Grain Maiden', kn: 'The Grain Maiden', gu: 'The Grain Maiden' }, quality: { en: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.', hi: 'विनम्र व्यावहारिक सेवा; शुद्ध-अशुद्ध का विवेक, विस्तार और परिश्रम से उपचार।', sa: 'विनम्र व्यावहारिक सेवा; शुद्ध-अशुद्ध का विवेक, विस्तार और परिश्रम से उपचार।', mai: 'विनम्र व्यावहारिक सेवा; शुद्ध-अशुद्ध का विवेक, विस्तार और परिश्रम से उपचार।', mr: 'विनम्र व्यावहारिक सेवा; शुद्ध-अशुद्ध का विवेक, विस्तार और परिश्रम से उपचार।', ta: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.', te: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.', bn: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.', kn: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.', gu: 'Humble practical service; discrimination between pure and impure, healing through detail and diligence.' } },
  { archetype: { en: 'The Analyst', hi: 'विश्लेषक', sa: 'विश्लेषक', mai: 'विश्लेषक', mr: 'विश्लेषक', ta: 'The Analyst', te: 'The Analyst', bn: 'The Analyst', kn: 'The Analyst', gu: 'The Analyst' }, quality: { en: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.', hi: 'क्रमबद्ध बुद्धि; लेखा, वर्गीकरण और व्यवस्थित समस्या-समाधान — जो छूता है उसे परिष्कृत करता है।', sa: 'क्रमबद्ध बुद्धि; लेखा, वर्गीकरण और व्यवस्थित समस्या-समाधान — जो छूता है उसे परिष्कृत करता है।', mai: 'क्रमबद्ध बुद्धि; लेखा, वर्गीकरण और व्यवस्थित समस्या-समाधान — जो छूता है उसे परिष्कृत करता है।', mr: 'क्रमबद्ध बुद्धि; लेखा, वर्गीकरण और व्यवस्थित समस्या-समाधान — जो छूता है उसे परिष्कृत करता है।', ta: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.', te: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.', bn: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.', kn: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.', gu: 'Methodical intelligence; accounting, classification, and systematic problem-solving — perfects what it touches.' } },
  { archetype: { en: 'The Discerning Traveller', hi: 'विवेकशील यात्री', sa: 'विवेकशील यात्री', mai: 'विवेकशील यात्री', mr: 'विवेकशील यात्री', ta: 'The Discerning Traveller', te: 'The Discerning Traveller', bn: 'The Discerning Traveller', kn: 'The Discerning Traveller', gu: 'The Discerning Traveller' }, quality: { en: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.', hi: 'विवेकशील गति; ज्ञान और सुधार की खोज में रणनीतिक यात्राएं — आलोचनात्मक पर्यवेक्षक।', sa: 'विवेकशील गति; ज्ञान और सुधार की खोज में रणनीतिक यात्राएं — आलोचनात्मक पर्यवेक्षक।', mai: 'विवेकशील गति; ज्ञान और सुधार की खोज में रणनीतिक यात्राएं — आलोचनात्मक पर्यवेक्षक।', mr: 'विवेकशील गति; ज्ञान और सुधार की खोज में रणनीतिक यात्राएं — आलोचनात्मक पर्यवेक्षक।', ta: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.', te: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.', bn: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.', kn: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.', gu: 'Discriminating movement; strategic journeys in search of knowledge and improvement — critical observer.' } },
  // Libra: faces 1-3 (index 18-20)
  { archetype: { en: 'The Just Judge', hi: 'न्यायी न्यायाधीश', sa: 'न्यायी न्यायाधीश', mai: 'न्यायी न्यायाधीश', mr: 'न्यायी न्यायाधीश', ta: 'The Just Judge', te: 'The Just Judge', bn: 'The Just Judge', kn: 'The Just Judge', gu: 'The Just Judge' }, quality: { en: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.', hi: 'विपरीतताओं का न्यायपूर्ण तुलाकार; कूटनीतिक, संतुलित, तर्कसंगत विचार-विमर्श से सौहार्द।', sa: 'विपरीतताओं का न्यायपूर्ण तुलाकार; कूटनीतिक, संतुलित, तर्कसंगत विचार-विमर्श से सौहार्द।', mai: 'विपरीतताओं का न्यायपूर्ण तुलाकार; कूटनीतिक, संतुलित, तर्कसंगत विचार-विमर्श से सौहार्द।', mr: 'विपरीतताओं का न्यायपूर्ण तुलाकार; कूटनीतिक, संतुलित, तर्कसंगत विचार-विमर्श से सौहार्द।', ta: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.', te: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.', bn: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.', kn: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.', gu: 'Fair weigher of opposites; diplomatic, balanced, seeking harmony through rational deliberation.' } },
  { archetype: { en: 'The Social Grace', hi: 'सामाजिक सौजन्य', sa: 'सामाजिक सौजन्य', mai: 'सामाजिक सौजन्य', mr: 'सामाजिक सौजन्य', ta: 'The Social Grace', te: 'The Social Grace', bn: 'The Social Grace', kn: 'The Social Grace', gu: 'The Social Grace' }, quality: { en: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.', hi: 'सौंदर्य और सामाजिक निपुणता; कला, सौंदर्य, संबंध-सौहार्द — प्राकृतिक चुंबकत्व।', sa: 'सौंदर्य और सामाजिक निपुणता; कला, सौंदर्य, संबंध-सौहार्द — प्राकृतिक चुंबकत्व।', mai: 'सौंदर्य और सामाजिक निपुणता; कला, सौंदर्य, संबंध-सौहार्द — प्राकृतिक चुंबकत्व।', mr: 'सौंदर्य और सामाजिक निपुणता; कला, सौंदर्य, संबंध-सौहार्द — प्राकृतिक चुंबकत्व।', ta: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.', te: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.', bn: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.', kn: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.', gu: 'Aesthetic and social mastery; arts, beauty, relationship harmony — natural magnetism and charm.' } },
  { archetype: { en: 'The Righteous Sword', hi: 'धर्मी तलवार', sa: 'धर्मी तलवार', mai: 'धर्मी तलवार', mr: 'धर्मी तलवार', ta: 'The Righteous Sword', te: 'The Righteous Sword', bn: 'The Righteous Sword', kn: 'The Righteous Sword', gu: 'The Righteous Sword' }, quality: { en: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.', hi: 'न्याय का प्रवर्तन; निर्णायक कार्य से संतुलन — निष्पक्षता के लिए लड़ता है, कपट काटता है।', sa: 'न्याय का प्रवर्तन; निर्णायक कार्य से संतुलन — निष्पक्षता के लिए लड़ता है, कपट काटता है।', mai: 'न्याय का प्रवर्तन; निर्णायक कार्य से संतुलन — निष्पक्षता के लिए लड़ता है, कपट काटता है।', mr: 'न्याय का प्रवर्तन; निर्णायक कार्य से संतुलन — निष्पक्षता के लिए लड़ता है, कपट काटता है।', ta: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.', te: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.', bn: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.', kn: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.', gu: 'Justice enforced; balance restored through decisive action — fights for fairness, cuts through deception.' } },
  // Scorpio: faces 1-3 (index 21-23)
  { archetype: { en: 'The Serpent Queen', hi: 'नागिन रानी', sa: 'नागिन रानी', mai: 'नागिन रानी', mr: 'नागिन रानी', ta: 'The Serpent Queen', te: 'The Serpent Queen', bn: 'The Serpent Queen', kn: 'The Serpent Queen', gu: 'The Serpent Queen' }, quality: { en: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.', hi: 'गुप्त शक्ति और छिपा नियंत्रण; मूल सत्य तक पहुँचने के लिए सतह भेदना — चुंबकीय और घातक।', sa: 'गुप्त शक्ति और छिपा नियंत्रण; मूल सत्य तक पहुँचने के लिए सतह भेदना — चुंबकीय और घातक।', mai: 'गुप्त शक्ति और छिपा नियंत्रण; मूल सत्य तक पहुँचने के लिए सतह भेदना — चुंबकीय और घातक।', mr: 'गुप्त शक्ति और छिपा नियंत्रण; मूल सत्य तक पहुँचने के लिए सतह भेदना — चुंबकीय और घातक।', ta: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.', te: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.', bn: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.', kn: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.', gu: 'Occult power and hidden control; penetrates surface to reach core truth — magnetic and dangerous.' } },
  { archetype: { en: 'The Investigator', hi: 'जांचकर्ता', sa: 'जांचकर्ता', mai: 'जांचकर्ता', mr: 'जांचकर्ता', ta: 'The Investigator', te: 'The Investigator', bn: 'The Investigator', kn: 'The Investigator', gu: 'The Investigator' }, quality: { en: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.', hi: 'छिपे की अथक खोज; अनुसंधान, जांच और रहस्य उद्घाटन — मनोवैज्ञानिक गहराई।', sa: 'छिपे की अथक खोज; अनुसंधान, जांच और रहस्य उद्घाटन — मनोवैज्ञानिक गहराई।', mai: 'छिपे की अथक खोज; अनुसंधान, जांच और रहस्य उद्घाटन — मनोवैज्ञानिक गहराई।', mr: 'छिपे की अथक खोज; अनुसंधान, जांच और रहस्य उद्घाटन — मनोवैज्ञानिक गहराई।', ta: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.', te: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.', bn: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.', kn: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.', gu: 'Relentless seeker of the hidden; research, investigation, and exposure of secrets — psychological depth.' } },
  { archetype: { en: 'The Transformer', hi: 'परिवर्तक', sa: 'परिवर्तक', mai: 'परिवर्तक', mr: 'परिवर्तक', ta: 'மாற்றுபவர்', te: 'పరివర్తకుడు', bn: 'রূপান্তরকারী', kn: 'ಪರಿವರ್ತಕ', gu: 'પરિવર્તક' }, quality: { en: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.', hi: 'मृत्यु-पुनर्जन्म चक्र; विनाश से गहरा कायाकल्प और आध्यात्मिक पुनर्जन्म।', sa: 'मृत्यु-पुनर्जन्म चक्र; विनाश से गहरा कायाकल्प और आध्यात्मिक पुनर्जन्म।', mai: 'मृत्यु-पुनर्जन्म चक्र; विनाश से गहरा कायाकल्प और आध्यात्मिक पुनर्जन्म।', mr: 'मृत्यु-पुनर्जन्म चक्र; विनाश से गहरा कायाकल्प और आध्यात्मिक पुनर्जन्म।', ta: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.', te: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.', bn: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.', kn: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.', gu: 'Death-and-rebirth cycle; profound alchemical transformation and spiritual regeneration from destruction.' } },
  // Sagittarius: faces 1-3 (index 24-26)
  { archetype: { en: 'The Centaur Archer', hi: 'अश्व-धनुर्धर', sa: 'अश्व-धनुर्धर', mai: 'अश्व-धनुर्धर', mr: 'अश्व-धनुर्धर', ta: 'The Centaur Archer', te: 'The Centaur Archer', bn: 'The Centaur Archer', kn: 'The Centaur Archer', gu: 'The Centaur Archer' }, quality: { en: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.', hi: 'साहसिक सत्य-साधक; ऊँचा लक्ष्य, दूर-क्षितिज अन्वेषण — साहसी दार्शनिक प्रश्न।', sa: 'साहसिक सत्य-साधक; ऊँचा लक्ष्य, दूर-क्षितिज अन्वेषण — साहसी दार्शनिक प्रश्न।', mai: 'साहसिक सत्य-साधक; ऊँचा लक्ष्य, दूर-क्षितिज अन्वेषण — साहसी दार्शनिक प्रश्न।', mr: 'साहसिक सत्य-साधक; ऊँचा लक्ष्य, दूर-क्षितिज अन्वेषण — साहसी दार्शनिक प्रश्न।', ta: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.', te: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.', bn: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.', kn: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.', gu: 'Adventurous truth-seeker; aims high, explores distant horizons — bold philosophical questioning.' } },
  { archetype: { en: 'The Dharma Teacher', hi: 'धर्म-गुरु', sa: 'धर्म-गुरु', mai: 'धर्म-गुरु', mr: 'धर्म-गुरु', ta: 'The Dharma Teacher', te: 'The Dharma Teacher', bn: 'The Dharma Teacher', kn: 'The Dharma Teacher', gu: 'The Dharma Teacher' }, quality: { en: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.', hi: 'दार्शनिक मार्गदर्शक और गुरु; शिक्षण, शास्त्र और जीवन-उदाहरण से ज्ञान-प्रसार।', sa: 'दार्शनिक मार्गदर्शक और गुरु; शिक्षण, शास्त्र और जीवन-उदाहरण से ज्ञान-प्रसार।', mai: 'दार्शनिक मार्गदर्शक और गुरु; शिक्षण, शास्त्र और जीवन-उदाहरण से ज्ञान-प्रसार।', mr: 'दार्शनिक मार्गदर्शक और गुरु; शिक्षण, शास्त्र और जीवन-उदाहरण से ज्ञान-प्रसार।', ta: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.', te: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.', bn: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.', kn: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.', gu: 'Philosophical guide and guru; wisdom transmitted through teaching, scripture, and lived example.' } },
  { archetype: { en: 'The Summit Seeker', hi: 'शिखर-अन्वेषक', sa: 'शिखर-अन्वेषक', mai: 'शिखर-अन्वेषक', mr: 'शिखर-अन्वेषक', ta: 'The Summit Seeker', te: 'The Summit Seeker', bn: 'The Summit Seeker', kn: 'The Summit Seeker', gu: 'The Summit Seeker' }, quality: { en: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.', hi: 'उच्चतम सत्य की ओर आकांक्षा; अतिक्रामक ज्ञान के लिए आध्यात्मिक पर्वतारोहण।', sa: 'उच्चतम सत्य की ओर आकांक्षा; अतिक्रामक ज्ञान के लिए आध्यात्मिक पर्वतारोहण।', mai: 'उच्चतम सत्य की ओर आकांक्षा; अतिक्रामक ज्ञान के लिए आध्यात्मिक पर्वतारोहण।', mr: 'उच्चतम सत्य की ओर आकांक्षा; अतिक्रामक ज्ञान के लिए आध्यात्मिक पर्वतारोहण।', ta: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.', te: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.', bn: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.', kn: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.', gu: 'Aspiring toward the highest truth; spiritual mountain-climber reaching for transcendent knowledge.' } },
  // Capricorn: faces 1-3 (index 27-29)
  { archetype: { en: 'The Crocodile', hi: 'मगरमच्छ', sa: 'मगरमच्छ', mai: 'मगरमच्छ', mr: 'मगरमच्छ', ta: 'The Crocodile', te: 'The Crocodile', bn: 'The Crocodile', kn: 'The Crocodile', gu: 'The Crocodile' }, quality: { en: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.', hi: 'उपलब्धि का धैर्यवान शिकारी; सतह के नीचे इंतजार, सही समय पर दृढ़ता से ग्रहण।', sa: 'उपलब्धि का धैर्यवान शिकारी; सतह के नीचे इंतजार, सही समय पर दृढ़ता से ग्रहण।', mai: 'उपलब्धि का धैर्यवान शिकारी; सतह के नीचे इंतजार, सही समय पर दृढ़ता से ग्रहण।', mr: 'उपलब्धि का धैर्यवान शिकारी; सतह के नीचे इंतजार, सही समय पर दृढ़ता से ग्रहण।', ta: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.', te: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.', bn: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.', kn: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.', gu: 'Patient predator of achievement; lurks below the surface, waits for the right moment, seizes decisively.' } },
  { archetype: { en: 'The Mountain Climber', hi: 'पर्वतारोही', sa: 'पर्वतारोही', mai: 'पर्वतारोही', mr: 'पर्वतारोही', ta: 'The Mountain Climber', te: 'The Mountain Climber', bn: 'The Mountain Climber', kn: 'The Mountain Climber', gu: 'The Mountain Climber' }, quality: { en: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.', hi: 'परिश्रम से दृढ़ आरोहण; भूमिगत महत्वाकांक्षा, क्रमशः महारत — स्थायित्व के लिए निर्मित।', sa: 'परिश्रम से दृढ़ आरोहण; भूमिगत महत्वाकांक्षा, क्रमशः महारत — स्थायित्व के लिए निर्मित।', mai: 'परिश्रम से दृढ़ आरोहण; भूमिगत महत्वाकांक्षा, क्रमशः महारत — स्थायित्व के लिए निर्मित।', mr: 'परिश्रम से दृढ़ आरोहण; भूमिगत महत्वाकांक्षा, क्रमशः महारत — स्थायित्व के लिए निर्मित।', ta: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.', te: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.', bn: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.', kn: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.', gu: 'Determined ascent through toil; earthy ambition, step-by-step mastery — built to last.' } },
  { archetype: { en: 'The Enduring Sovereign', hi: 'चिरस्थायी संप्रभु', sa: 'चिरस्थायी संप्रभु', mai: 'चिरस्थायी संप्रभु', mr: 'चिरस्थायी संप्रभु', ta: 'The Enduring Sovereign', te: 'The Enduring Sovereign', bn: 'The Enduring Sovereign', kn: 'The Enduring Sovereign', gu: 'The Enduring Sovereign' }, quality: { en: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.', hi: 'परखी सहनशक्ति से अधिकार; गंभीरता और कठिन अनुभव के भार से शासन।', sa: 'परखी सहनशक्ति से अधिकार; गंभीरता और कठिन अनुभव के भार से शासन।', mai: 'परखी सहनशक्ति से अधिकार; गंभीरता और कठिन अनुभव के भार से शासन।', mr: 'परखी सहनशक्ति से अधिकार; गंभीरता और कठिन अनुभव के भार से शासन।', ta: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.', te: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.', bn: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.', kn: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.', gu: 'Authority through tested endurance; rules with gravitas and the weight of hard-won experience.' } },
  // Aquarius: faces 1-3 (index 30-32)
  { archetype: { en: 'The Water Bearer', hi: 'जल-वाहक', sa: 'जल-वाहक', mai: 'जल-वाहक', mr: 'जल-वाहक', ta: 'The Water Bearer', te: 'The Water Bearer', bn: 'The Water Bearer', kn: 'The Water Bearer', gu: 'The Water Bearer' }, quality: { en: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.', hi: 'ज्ञान का सार्वभौमिक वितरक; प्रगतिशील, परोपकारी, सामूहिक लाभ के लिए ज्ञान प्रदान।', sa: 'ज्ञान का सार्वभौमिक वितरक; प्रगतिशील, परोपकारी, सामूहिक लाभ के लिए ज्ञान प्रदान।', mai: 'ज्ञान का सार्वभौमिक वितरक; प्रगतिशील, परोपकारी, सामूहिक लाभ के लिए ज्ञान प्रदान।', mr: 'ज्ञान का सार्वभौमिक वितरक; प्रगतिशील, परोपकारी, सामूहिक लाभ के लिए ज्ञान प्रदान।', ta: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.', te: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.', bn: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.', kn: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.', gu: 'Universal distributor of wisdom; progressive, altruistic, pouring knowledge for collective benefit.' } },
  { archetype: { en: 'The Innovator', hi: 'नवप्रवर्तक', sa: 'नवप्रवर्तक', mai: 'नवप्रवर्तक', mr: 'नवप्रवर्तक', ta: 'The Innovator', te: 'The Innovator', bn: 'The Innovator', kn: 'The Innovator', gu: 'The Innovator' }, quality: { en: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.', hi: 'कट्टरपंथी विचारक और आविष्कारक; नई प्रणालियाँ, प्रौद्योगिकियाँ और सामाजिक संरचनाएं।', sa: 'कट्टरपंथी विचारक और आविष्कारक; नई प्रणालियाँ, प्रौद्योगिकियाँ और सामाजिक संरचनाएं।', mai: 'कट्टरपंथी विचारक और आविष्कारक; नई प्रणालियाँ, प्रौद्योगिकियाँ और सामाजिक संरचनाएं।', mr: 'कट्टरपंथी विचारक और आविष्कारक; नई प्रणालियाँ, प्रौद्योगिकियाँ और सामाजिक संरचनाएं।', ta: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.', te: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.', bn: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.', kn: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.', gu: 'Radical thinker and inventor; breaks existing forms to create new systems, technologies, and social structures.' } },
  { archetype: { en: 'The Humanitarian Healer', hi: 'मानवतावादी उपचारक', sa: 'मानवतावादी उपचारक', mai: 'मानवतावादी उपचारक', mr: 'मानवतावादी उपचारक', ta: 'The Humanitarian Healer', te: 'The Humanitarian Healer', bn: 'The Humanitarian Healer', kn: 'The Humanitarian Healer', gu: 'The Humanitarian Healer' }, quality: { en: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.', hi: 'बड़े पैमाने पर मानवता-सेवा; वैज्ञानिक समझ और सर्वहित करुणापूर्ण कार्य का संयोग।', sa: 'बड़े पैमाने पर मानवता-सेवा; वैज्ञानिक समझ और सर्वहित करुणापूर्ण कार्य का संयोग।', mai: 'बड़े पैमाने पर मानवता-सेवा; वैज्ञानिक समझ और सर्वहित करुणापूर्ण कार्य का संयोग।', mr: 'बड़े पैमाने पर मानवता-सेवा; वैज्ञानिक समझ और सर्वहित करुणापूर्ण कार्य का संयोग।', ta: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.', te: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.', bn: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.', kn: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.', gu: 'Service to humanity at scale; combines scientific understanding with compassionate action for all.' } },
  // Pisces: faces 1-3 (index 33-35)
  { archetype: { en: 'The Dreaming Fish', hi: 'स्वप्न-मछली', sa: 'स्वप्न-मछली', mai: 'स्वप्न-मछली', mr: 'स्वप्न-मछली', ta: 'The Dreaming Fish', te: 'The Dreaming Fish', bn: 'The Dreaming Fish', kn: 'The Dreaming Fish', gu: 'The Dreaming Fish' }, quality: { en: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.', hi: 'असीमित कल्पना और आध्यात्मिक ग्रहणशीलता; मानसिक, द्रष्टा, ब्रह्मांडीय सागर में विलीन।', sa: 'असीमित कल्पना और आध्यात्मिक ग्रहणशीलता; मानसिक, द्रष्टा, ब्रह्मांडीय सागर में विलीन।', mai: 'असीमित कल्पना और आध्यात्मिक ग्रहणशीलता; मानसिक, द्रष्टा, ब्रह्मांडीय सागर में विलीन।', mr: 'असीमित कल्पना और आध्यात्मिक ग्रहणशीलता; मानसिक, द्रष्टा, ब्रह्मांडीय सागर में विलीन।', ta: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.', te: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.', bn: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.', kn: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.', gu: 'Boundless imagination and spiritual receptivity; psychic, visionary, dissolving into the cosmic ocean.' } },
  { archetype: { en: 'The Mystic Meditator', hi: 'रहस्यमय ध्यानी', sa: 'रहस्यमय ध्यानी', mai: 'रहस्यमय ध्यानी', mr: 'रहस्यमय ध्यानी', ta: 'The Mystic Meditator', te: 'The Mystic Meditator', bn: 'The Mystic Meditator', kn: 'The Mystic Meditator', gu: 'The Mystic Meditator' }, quality: { en: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.', hi: 'निराकार का चिंतनशील साधक; सांसारिक वास्तविकता से परे मुक्ति की ओर अंतर्यात्रा।', sa: 'निराकार का चिंतनशील साधक; सांसारिक वास्तविकता से परे मुक्ति की ओर अंतर्यात्रा।', mai: 'निराकार का चिंतनशील साधक; सांसारिक वास्तविकता से परे मुक्ति की ओर अंतर्यात्रा।', mr: 'निराकार का चिंतनशील साधक; सांसारिक वास्तविकता से परे मुक्ति की ओर अंतर्यात्रा।', ta: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.', te: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.', bn: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.', kn: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.', gu: 'Contemplative seeker of the formless; inward journey transcending mundane reality toward liberation.' } },
  { archetype: { en: 'The Liberated Soul', hi: 'मुक्त आत्मा', sa: 'मुक्त आत्मा', mai: 'मुक्त आत्मा', mr: 'मुक्त आत्मा', ta: 'The Liberated Soul', te: 'The Liberated Soul', bn: 'The Liberated Soul', kn: 'The Liberated Soul', gu: 'The Liberated Soul' }, quality: { en: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.', hi: 'मोक्ष-साधना चेतना; आध्यात्मिक मुक्ति, अहंकार का पूर्ण विसर्जन, स्रोत में वापसी।', sa: 'मोक्ष-साधना चेतना; आध्यात्मिक मुक्ति, अहंकार का पूर्ण विसर्जन, स्रोत में वापसी।', mai: 'मोक्ष-साधना चेतना; आध्यात्मिक मुक्ति, अहंकार का पूर्ण विसर्जन, स्रोत में वापसी।', mr: 'मोक्ष-साधना चेतना; आध्यात्मिक मुक्ति, अहंकार का पूर्ण विसर्जन, स्रोत में वापसी।', ta: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.', te: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.', bn: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.', kn: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.', gu: 'Moksha-seeking consciousness; spiritual liberation, complete dissolution of ego, return to the source.' } },
];

/** Return the Drekkana face (0-35) from sidereal longitude (0-360) */
function getDrekkanaFace(longitude: number): { faceIndex: number; sign: number; face: number } {
  const norm = ((longitude % 360) + 360) % 360;
  const sign = Math.floor(norm / 30) + 1;          // 1-12
  const face = Math.floor((norm % 30) / 10) + 1;   // 1-3
  const faceIndex = (sign - 1) * 3 + (face - 1);   // 0-35
  return { faceIndex, sign, face };
}

// ─── Chart-specific commentary generators ──────────────────────────────────

// Domain descriptions for each varga
const VARGA_DOMAINS: Record<string, { domain: Bi; desc: Bi }> = {
  D1: { domain: { en: 'Overall Life & Personality', hi: 'समग्र जीवन एवं व्यक्तित्व', sa: 'समग्र जीवन एवं व्यक्तित्व', mai: 'समग्र जीवन एवं व्यक्तित्व', mr: 'समग्र जीवन एवं व्यक्तित्व', ta: 'Overall Life & Personality', te: 'Overall Life & Personality', bn: 'Overall Life & Personality', kn: 'Overall Life & Personality', gu: 'Overall Life & Personality' }, desc: { en: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.', hi: 'राशि चार्ट मास्टर चार्ट है जिससे अन्य सभी विभागीय चार्ट व्युत्पन्न होते हैं। यह जातक के समग्र जीवन पथ, शारीरिक संरचना, स्वभाव और सामान्य कार्मिक प्रारूप को दर्शाता है।', sa: 'राशि चार्ट मास्टर चार्ट है जिससे अन्य सभी विभागीय चार्ट व्युत्पन्न होते हैं। यह जातक के समग्र जीवन पथ, शारीरिक संरचना, स्वभाव और सामान्य कार्मिक प्रारूप को दर्शाता है।', mai: 'राशि चार्ट मास्टर चार्ट है जिससे अन्य सभी विभागीय चार्ट व्युत्पन्न होते हैं। यह जातक के समग्र जीवन पथ, शारीरिक संरचना, स्वभाव और सामान्य कार्मिक प्रारूप को दर्शाता है।', mr: 'राशि चार्ट मास्टर चार्ट है जिससे अन्य सभी विभागीय चार्ट व्युत्पन्न होते हैं। यह जातक के समग्र जीवन पथ, शारीरिक संरचना, स्वभाव और सामान्य कार्मिक प्रारूप को दर्शाता है।', ta: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.', te: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.', bn: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.', kn: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.', gu: 'The Rashi chart is the master chart from which all other divisional charts are derived. It shows the overall life trajectory, physical constitution, temperament, and general karmic pattern of the native.' } },
  BC: { domain: { en: 'Actual House Occupancy', hi: 'वास्तविक भाव अधिवास', sa: 'वास्तविक भाव अधिवास', mai: 'वास्तविक भाव अधिवास', mr: 'वास्तविक भाव अधिवास', ta: 'Actual House Occupancy', te: 'Actual House Occupancy', bn: 'Actual House Occupancy', kn: 'Actual House Occupancy', gu: 'Actual House Occupancy' }, desc: { en: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.', hi: 'भाव चलित चार्ट दर्शाता है कि ग्रह वास्तव में किस भाव में कार्य करते हैं। संधि के निकट ग्रह D1 से भाव बदल सकते हैं।', sa: 'भाव चलित चार्ट दर्शाता है कि ग्रह वास्तव में किस भाव में कार्य करते हैं। संधि के निकट ग्रह D1 से भाव बदल सकते हैं।', mai: 'भाव चलित चार्ट दर्शाता है कि ग्रह वास्तव में किस भाव में कार्य करते हैं। संधि के निकट ग्रह D1 से भाव बदल सकते हैं।', mr: 'भाव चलित चार्ट दर्शाता है कि ग्रह वास्तव में किस भाव में कार्य करते हैं। संधि के निकट ग्रह D1 से भाव बदल सकते हैं।', ta: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.', te: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.', bn: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.', kn: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.', gu: 'The Bhav Chalit chart shows where planets actually function in terms of house significations. Planets near cusp boundaries may shift houses from D1, revealing their true house influence. This is critical for prediction accuracy.' } },
  D2: { domain: { en: 'Wealth & Financial Prosperity', hi: 'धन एवं वित्तीय समृद्धि', sa: 'धन एवं वित्तीय समृद्धि', mai: 'धन एवं वित्तीय समृद्धि', mr: 'धन एवं वित्तीय समृद्धि', ta: 'Wealth & Financial Prosperity', te: 'Wealth & Financial Prosperity', bn: 'Wealth & Financial Prosperity', kn: 'Wealth & Financial Prosperity', gu: 'Wealth & Financial Prosperity' }, desc: { en: 'The Hora chart divides each sign into Solar and Lunar halves. Sun\'s hora indicates wealth through effort, authority, and government. Moon\'s hora indicates wealth through public dealings, trade, and emotional intelligence. The balance of planets between these two horas reveals the native\'s wealth potential and earning style.', hi: 'होरा चार्ट प्रत्येक राशि को सौर और चंद्र अर्ध में विभाजित करता है। सूर्य होरा प्रयास, अधिकार से धन दर्शाता है। चंद्र होरा व्यापार, सार्वजनिक व्यवहार से।' } },
  D3: { domain: { en: 'Siblings, Courage & Initiative', hi: 'भाई-बहन, साहस एवं पहल', sa: 'भाई-बहन, साहस एवं पहल', mai: 'भाई-बहन, साहस एवं पहल', mr: 'भाई-बहन, साहस एवं पहल', ta: 'Siblings, Courage & Initiative', te: 'Siblings, Courage & Initiative', bn: 'Siblings, Courage & Initiative', kn: 'Siblings, Courage & Initiative', gu: 'Siblings, Courage & Initiative' }, desc: { en: 'The Drekkana chart reveals the native\'s relationship with siblings, courage in adversity, and capacity for self-initiative. Strong benefics in D3 kendras indicate supportive siblings and innate bravery. The 3rd house of D3 is especially significant for younger siblings.', hi: 'द्रेष्काण चार्ट भाई-बहनों से संबंध, विपत्ति में साहस और आत्म-पहल की क्षमता दर्शाता है। D3 केंद्र में शुभ ग्रह सहायक सहोदर और जन्मजात वीरता दर्शाते हैं।' } },
  D4: { domain: { en: 'Property, Fortune & Fixed Assets', hi: 'संपत्ति, भाग्य एवं स्थावर संपदा', sa: 'संपत्ति, भाग्य एवं स्थावर संपदा', mai: 'संपत्ति, भाग्य एवं स्थावर संपदा', mr: 'संपत्ति, भाग्य एवं स्थावर संपदा', ta: 'Property, Fortune & Fixed Assets', te: 'Property, Fortune & Fixed Assets', bn: 'Property, Fortune & Fixed Assets', kn: 'Property, Fortune & Fixed Assets', gu: 'Property, Fortune & Fixed Assets' }, desc: { en: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.', hi: 'चतुर्थांश चार्ट अचल संपत्ति, भूमि, वाहन और सामान्य भाग्य को नियंत्रित करता है। मजबूत D4 संपत्ति विरासत और सुखद जीवन स्थिति दर्शाता है।', sa: 'चतुर्थांश चार्ट अचल संपत्ति, भूमि, वाहन और सामान्य भाग्य को नियंत्रित करता है। मजबूत D4 संपत्ति विरासत और सुखद जीवन स्थिति दर्शाता है।', mai: 'चतुर्थांश चार्ट अचल संपत्ति, भूमि, वाहन और सामान्य भाग्य को नियंत्रित करता है। मजबूत D4 संपत्ति विरासत और सुखद जीवन स्थिति दर्शाता है।', mr: 'चतुर्थांश चार्ट अचल संपत्ति, भूमि, वाहन और सामान्य भाग्य को नियंत्रित करता है। मजबूत D4 संपत्ति विरासत और सुखद जीवन स्थिति दर्शाता है।', ta: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.', te: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.', bn: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.', kn: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.', gu: 'The Chaturthamsha chart governs immovable property, landed assets, vehicles, and general fortune (bhagya). A strong D4 indicates inheritance of property, successful real estate ventures, and comfortable living conditions. The 4th house here shows the home environment.' } },
  D5: { domain: { en: 'Fame, Authority & Spiritual Merit', hi: 'यश, अधिकार एवं पुण्य', sa: 'यश, अधिकार एवं पुण्य', mai: 'यश, अधिकार एवं पुण्य', mr: 'यश, अधिकार एवं पुण्य', ta: 'Fame, Authority & Spiritual Merit', te: 'Fame, Authority & Spiritual Merit', bn: 'Fame, Authority & Spiritual Merit', kn: 'Fame, Authority & Spiritual Merit', gu: 'Fame, Authority & Spiritual Merit' }, desc: { en: 'The Panchamsha chart relates to fame, dignity, authority, and accumulated spiritual merit (poorva punya). It shows the native\'s capacity to command respect and exercise power with wisdom. Strong D5 indicates recognition and honor in society.', hi: 'पंचमांश चार्ट यश, प्रतिष्ठा, अधिकार और संचित पूर्व पुण्य से संबंधित है। यह सम्मान और बुद्धिमत्ता से शक्ति प्रयोग की क्षमता दर्शाता है।' } },
  D6: { domain: { en: 'Health, Disease & Enemies', hi: 'स्वास्थ्य, रोग एवं शत्रु', sa: 'स्वास्थ्य, रोग एवं शत्रु', mai: 'स्वास्थ्य, रोग एवं शत्रु', mr: 'स्वास्थ्य, रोग एवं शत्रु', ta: 'Health, Disease & Enemies', te: 'Health, Disease & Enemies', bn: 'Health, Disease & Enemies', kn: 'Health, Disease & Enemies', gu: 'Health, Disease & Enemies' }, desc: { en: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.', hi: 'षष्ठांश चार्ट रोग, शत्रुओं और कानूनी विवादों की प्रवृत्ति दर्शाता है। D6 केंद्र में पाप ग्रह दीर्घकालिक स्वास्थ्य समस्याओं का संकेत दे सकते हैं।', sa: 'षष्ठांश चार्ट रोग, शत्रुओं और कानूनी विवादों की प्रवृत्ति दर्शाता है। D6 केंद्र में पाप ग्रह दीर्घकालिक स्वास्थ्य समस्याओं का संकेत दे सकते हैं।', mai: 'षष्ठांश चार्ट रोग, शत्रुओं और कानूनी विवादों की प्रवृत्ति दर्शाता है। D6 केंद्र में पाप ग्रह दीर्घकालिक स्वास्थ्य समस्याओं का संकेत दे सकते हैं।', mr: 'षष्ठांश चार्ट रोग, शत्रुओं और कानूनी विवादों की प्रवृत्ति दर्शाता है। D6 केंद्र में पाप ग्रह दीर्घकालिक स्वास्थ्य समस्याओं का संकेत दे सकते हैं।', ta: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.', te: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.', bn: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.', kn: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.', gu: 'The Shashthamsha chart reveals vulnerability to diseases, the nature of enemies, and legal disputes. Malefics in D6 kendras can indicate chronic health issues. Benefics in the 6th house of D6 actually give strength to overcome enemies and disease.' } },
  D7: { domain: { en: 'Children & Progeny', hi: 'संतान एवं वंशवृद्धि', sa: 'संतान एवं वंशवृद्धि', mai: 'संतान एवं वंशवृद्धि', mr: 'संतान एवं वंशवृद्धि', ta: 'Children & Progeny', te: 'Children & Progeny', bn: 'Children & Progeny', kn: 'Children & Progeny', gu: 'Children & Progeny' }, desc: { en: 'The Saptamsha chart is the primary indicator for children — their number, nature, relationship with the native, and their success. The 5th house of D7 shows the first child, 7th shows the second. Jupiter\'s placement is crucial here.', hi: 'सप्तमांश चार्ट संतान का प्राथमिक सूचक है — उनकी संख्या, स्वभाव, जातक से संबंध और उनकी सफलता। D7 का 5वां भाव प्रथम संतान दर्शाता है।' } },
  D8: { domain: { en: 'Longevity & Sudden Events', hi: 'दीर्घायु एवं अप्रत्याशित घटनाएं', sa: 'दीर्घायु एवं अप्रत्याशित घटनाएं', mai: 'दीर्घायु एवं अप्रत्याशित घटनाएं', mr: 'दीर्घायु एवं अप्रत्याशित घटनाएं', ta: 'Longevity & Sudden Events', te: 'Longevity & Sudden Events', bn: 'Longevity & Sudden Events', kn: 'Longevity & Sudden Events', gu: 'Longevity & Sudden Events' }, desc: { en: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.', hi: 'अष्टमांश चार्ट दीर्घायु, आकस्मिक घटनाएं, दुर्घटनाएं और परिवर्तनकारी अनुभव दर्शाता है। केंद्र में शुभ ग्रहों वाला मजबूत D8 दीर्घ जीवन दर्शाता है।', sa: 'अष्टमांश चार्ट दीर्घायु, आकस्मिक घटनाएं, दुर्घटनाएं और परिवर्तनकारी अनुभव दर्शाता है। केंद्र में शुभ ग्रहों वाला मजबूत D8 दीर्घ जीवन दर्शाता है।', mai: 'अष्टमांश चार्ट दीर्घायु, आकस्मिक घटनाएं, दुर्घटनाएं और परिवर्तनकारी अनुभव दर्शाता है। केंद्र में शुभ ग्रहों वाला मजबूत D8 दीर्घ जीवन दर्शाता है।', mr: 'अष्टमांश चार्ट दीर्घायु, आकस्मिक घटनाएं, दुर्घटनाएं और परिवर्तनकारी अनुभव दर्शाता है। केंद्र में शुभ ग्रहों वाला मजबूत D8 दीर्घ जीवन दर्शाता है।', ta: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.', te: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.', bn: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.', kn: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.', gu: 'The Ashtamsha chart reveals longevity, sudden events, accidents, and transformative experiences. A strong D8 with benefics in kendras indicates long life and the ability to weather crises. The 8th house here shows the nature of the end.' } },
  D9: { domain: { en: 'Marriage, Dharma & Soul Nature', hi: 'विवाह, धर्म एवं आत्म स्वरूप', sa: 'विवाह, धर्म एवं आत्म स्वरूप', mai: 'विवाह, धर्म एवं आत्म स्वरूप', mr: 'विवाह, धर्म एवं आत्म स्वरूप', ta: 'Marriage, Dharma & Soul Nature', te: 'Marriage, Dharma & Soul Nature', bn: 'Marriage, Dharma & Soul Nature', kn: 'Marriage, Dharma & Soul Nature', gu: 'Marriage, Dharma & Soul Nature' }, desc: { en: 'The Navamsha is the most important divisional chart after D1. It reveals the soul\'s true nature (dharma), the quality of marriage and partnerships, spiritual evolution, and confirms or denies the promises of the birth chart. Planets that are strong in both D1 and D9 deliver powerful results. The D9 lagna shows your inner self — who you become after midlife. The 7th house of D9 is the primary indicator of spouse nature.', hi: 'नवांश D1 के बाद सबसे महत्वपूर्ण विभागीय चार्ट है। यह आत्मा का सच्चा स्वरूप (धर्म), विवाह की गुणवत्ता, आध्यात्मिक विकास दर्शाता है। D1 और D9 दोनों में बलवान ग्रह शक्तिशाली फल देते हैं। D9 लग्न आपका आन्तरिक स्व दर्शाता है। D9 का 7वाँ भाव जीवनसाथी का प्राथमिक सूचक है।' } },
  D10: { domain: { en: 'Career, Profession & Public Life', hi: 'करियर, व्यवसाय एवं सार्वजनिक जीवन', sa: 'करियर, व्यवसाय एवं सार्वजनिक जीवन', mai: 'करियर, व्यवसाय एवं सार्वजनिक जीवन', mr: 'करियर, व्यवसाय एवं सार्वजनिक जीवन', ta: 'Career, Profession & Public Life', te: 'Career, Profession & Public Life', bn: 'Career, Profession & Public Life', kn: 'Career, Profession & Public Life', gu: 'Career, Profession & Public Life' }, desc: { en: 'The Dasamsha is one of the most important divisional charts. It reveals the nature of career, professional achievements, fame in one\'s field, and relationship with authority figures. The 10th house and its lord in D10 are paramount for career success.', hi: 'दशांश सबसे महत्वपूर्ण विभागीय चार्टों में से एक है। यह करियर, व्यावसायिक उपलब्धियाँ, क्षेत्र में प्रसिद्धि और अधिकारियों से संबंध दर्शाता है।' } },
  D12: { domain: { en: 'Parents, Ancestry & Lineage', hi: 'माता-पिता, वंशावली', sa: 'माता-पिता, वंशावली', mai: 'माता-पिता, वंशावली', mr: 'माता-पिता, वंशावली', ta: 'Parents, Ancestry & Lineage', te: 'Parents, Ancestry & Lineage', bn: 'Parents, Ancestry & Lineage', kn: 'Parents, Ancestry & Lineage', gu: 'Parents, Ancestry & Lineage' }, desc: { en: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.', hi: 'द्वादशांश चार्ट माता-पिता से संबंध, पारिवारिक वंशावली और विरासत में मिले गुण दर्शाता है। 4वां भाव माता और 9वां/10वां पिता का प्रतिनिधित्व करता है।', sa: 'द्वादशांश चार्ट माता-पिता से संबंध, पारिवारिक वंशावली और विरासत में मिले गुण दर्शाता है। 4वां भाव माता और 9वां/10वां पिता का प्रतिनिधित्व करता है।', mai: 'द्वादशांश चार्ट माता-पिता से संबंध, पारिवारिक वंशावली और विरासत में मिले गुण दर्शाता है। 4वां भाव माता और 9वां/10वां पिता का प्रतिनिधित्व करता है।', mr: 'द्वादशांश चार्ट माता-पिता से संबंध, पारिवारिक वंशावली और विरासत में मिले गुण दर्शाता है। 4वां भाव माता और 9वां/10वां पिता का प्रतिनिधित्व करता है।', ta: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.', te: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.', bn: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.', kn: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.', gu: 'The Dwadasamsha chart shows the relationship with parents, family lineage, and inherited traits. The 4th house represents the mother and the 9th/10th the father. Strong D12 indicates a distinguished family background and good relationship with parents.' } },
  D16: { domain: { en: 'Vehicles, Comforts & Luxuries', hi: 'वाहन, सुख एवं विलासिता', sa: 'वाहन, सुख एवं विलासिता', mai: 'वाहन, सुख एवं विलासिता', mr: 'वाहन, सुख एवं विलासिता', ta: 'Vehicles, Comforts & Luxuries', te: 'Vehicles, Comforts & Luxuries', bn: 'Vehicles, Comforts & Luxuries', kn: 'Vehicles, Comforts & Luxuries', gu: 'Vehicles, Comforts & Luxuries' }, desc: { en: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.', hi: 'षोडशांश चार्ट वाहन, यातायात साधन और भौतिक सुखों को नियंत्रित करता है। आधुनिक संदर्भ में यह कार, सुख-संपत्ति और तकनीकी उपकरणों तक विस्तृत है।', sa: 'षोडशांश चार्ट वाहन, यातायात साधन और भौतिक सुखों को नियंत्रित करता है। आधुनिक संदर्भ में यह कार, सुख-संपत्ति और तकनीकी उपकरणों तक विस्तृत है।', mai: 'षोडशांश चार्ट वाहन, यातायात साधन और भौतिक सुखों को नियंत्रित करता है। आधुनिक संदर्भ में यह कार, सुख-संपत्ति और तकनीकी उपकरणों तक विस्तृत है।', mr: 'षोडशांश चार्ट वाहन, यातायात साधन और भौतिक सुखों को नियंत्रित करता है। आधुनिक संदर्भ में यह कार, सुख-संपत्ति और तकनीकी उपकरणों तक विस्तृत है।', ta: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.', te: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.', bn: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.', kn: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.', gu: 'The Shodasamsha chart governs vehicles, conveyances, and material comforts. In the modern context, this extends to cars, properties used for pleasure, and technological devices. Strong Venus or Jupiter in D16 indicates acquisition of luxurious items.' } },
  D20: { domain: { en: 'Spiritual Progress & Upasana', hi: 'आध्यात्मिक प्रगति एवं उपासना', sa: 'आध्यात्मिक प्रगति एवं उपासना', mai: 'आध्यात्मिक प्रगति एवं उपासना', mr: 'आध्यात्मिक प्रगति एवं उपासना', ta: 'Spiritual Progress & Upasana', te: 'Spiritual Progress & Upasana', bn: 'Spiritual Progress & Upasana', kn: 'Spiritual Progress & Upasana', gu: 'Spiritual Progress & Upasana' }, desc: { en: 'The Vimshamsha chart reveals spiritual inclinations, devotional practices (upasana), and progress on the spiritual path. Jupiter and Ketu\'s placement here is crucial. A strong D20 indicates natural inclination toward meditation, mantra, and spiritual wisdom.', hi: 'विंशांश चार्ट आध्यात्मिक प्रवृत्तियों, भक्ति साधनाओं और आध्यात्मिक मार्ग पर प्रगति दर्शाता है। गुरु और केतु की स्थिति यहाँ महत्वपूर्ण है।' } },
  D24: { domain: { en: 'Education, Learning & Knowledge', hi: 'शिक्षा, विद्या एवं ज्ञान', sa: 'शिक्षा, विद्या एवं ज्ञान', mai: 'शिक्षा, विद्या एवं ज्ञान', mr: 'शिक्षा, विद्या एवं ज्ञान', ta: 'Education, Learning & Knowledge', te: 'Education, Learning & Knowledge', bn: 'Education, Learning & Knowledge', kn: 'Education, Learning & Knowledge', gu: 'Education, Learning & Knowledge' }, desc: { en: 'The Chaturvimshamsha chart governs education, academic achievements, and the nature of knowledge the native acquires. Mercury and Jupiter\'s strength here determines intellectual capacity. The 4th house shows formal education, 5th shows creative intelligence.', hi: 'चतुर्विंशांश चार्ट शिक्षा, शैक्षणिक उपलब्धियों और ज्ञान की प्रकृति को नियंत्रित करता है। बुध और गुरु की शक्ति बौद्धिक क्षमता निर्धारित करती है।' } },
  D27: { domain: { en: 'Strengths, Vitality & Stamina', hi: 'बल, ओज एवं सहनशक्ति', sa: 'बल, ओज एवं सहनशक्ति', mai: 'बल, ओज एवं सहनशक्ति', mr: 'बल, ओज एवं सहनशक्ति', ta: 'Strengths, Vitality & Stamina', te: 'Strengths, Vitality & Stamina', bn: 'Strengths, Vitality & Stamina', kn: 'Strengths, Vitality & Stamina', gu: 'Strengths, Vitality & Stamina' }, desc: { en: 'The Nakshatramsha chart indicates physical and mental strength, vitality, and endurance. Mars and Sun\'s placement here reveals the native\'s stamina and fighting spirit. A strong D27 indicates robust health and the ability to sustain effort.', hi: 'नक्षत्रांश चार्ट शारीरिक और मानसिक बल, ओज और सहनशक्ति दर्शाता है। मंगल और सूर्य की स्थिति जातक की सहनशीलता और लड़ाकू भावना दर्शाती है।' } },
  D30: { domain: { en: 'Misfortunes, Evils & Suffering', hi: 'दुर्भाग्य, पाप एवं कष्ट', sa: 'दुर्भाग्य, पाप एवं कष्ट', mai: 'दुर्भाग्य, पाप एवं कष्ट', mr: 'दुर्भाग्य, पाप एवं कष्ट', ta: 'Misfortunes, Evils & Suffering', te: 'Misfortunes, Evils & Suffering', bn: 'Misfortunes, Evils & Suffering', kn: 'Misfortunes, Evils & Suffering', gu: 'Misfortunes, Evils & Suffering' }, desc: { en: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.', hi: 'त्रिंशांश चार्ट दुर्भाग्य, बुरे प्रभावों और कष्टों के प्रति संवेदनशीलता दर्शाता है। D30 केंद्र में शुभ ग्रह ऐसे प्रभावों से रक्षा करते हैं।', sa: 'त्रिंशांश चार्ट दुर्भाग्य, बुरे प्रभावों और कष्टों के प्रति संवेदनशीलता दर्शाता है। D30 केंद्र में शुभ ग्रह ऐसे प्रभावों से रक्षा करते हैं।', mai: 'त्रिंशांश चार्ट दुर्भाग्य, बुरे प्रभावों और कष्टों के प्रति संवेदनशीलता दर्शाता है। D30 केंद्र में शुभ ग्रह ऐसे प्रभावों से रक्षा करते हैं।', mr: 'त्रिंशांश चार्ट दुर्भाग्य, बुरे प्रभावों और कष्टों के प्रति संवेदनशीलता दर्शाता है। D30 केंद्र में शुभ ग्रह ऐसे प्रभावों से रक्षा करते हैं।', ta: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.', te: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.', bn: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.', kn: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.', gu: 'The Trimshamsha chart reveals vulnerability to misfortune, evil influences, and suffering. It specifically shows dangers from hidden enemies, black magic, and negative karmic patterns. Benefics in D30 kendras protect against such influences.' } },
  D40: { domain: { en: 'Auspicious/Inauspicious Effects (Maternal)', hi: 'शुभाशुभ प्रभाव (मातृपक्ष)', sa: 'शुभाशुभ प्रभाव (मातृपक्ष)', mai: 'शुभाशुभ प्रभाव (मातृपक्ष)', mr: 'शुभाशुभ प्रभाव (मातृपक्ष)', ta: 'Auspicious/Inauspicious Effects (Maternal)', te: 'Auspicious/Inauspicious Effects (Maternal)', bn: 'Auspicious/Inauspicious Effects (Maternal)', kn: 'Auspicious/Inauspicious Effects (Maternal)', gu: 'Auspicious/Inauspicious Effects (Maternal)' }, desc: { en: 'The Khavedamsha chart shows auspicious and inauspicious effects inherited from the maternal side. It indicates the blessings or karmic debts from the mother\'s lineage and how they manifest in the native\'s life.', hi: 'खवेदांश चार्ट मातृपक्ष से विरासत में मिले शुभ और अशुभ प्रभाव दर्शाता है। यह माता के वंश से मिले आशीर्वाद या कार्मिक ऋण को दर्शाता है।' } },
  D45: { domain: { en: 'General Indications (Paternal)', hi: 'सामान्य संकेत (पितृपक्ष)', sa: 'सामान्य संकेत (पितृपक्ष)', mai: 'सामान्य संकेत (पितृपक्ष)', mr: 'सामान्य संकेत (पितृपक्ष)', ta: 'General Indications (Paternal)', te: 'General Indications (Paternal)', bn: 'General Indications (Paternal)', kn: 'General Indications (Paternal)', gu: 'General Indications (Paternal)' }, desc: { en: 'The Akshavedamsha chart reveals effects inherited from the paternal lineage. It shows the father\'s karmic legacy and how it shapes the native\'s destiny, character, and life opportunities.', hi: 'अक्षवेदांश चार्ट पितृवंश से विरासत में मिले प्रभावों को दर्शाता है। यह पिता की कार्मिक विरासत और जातक के भाग्य पर उसके प्रभाव को दर्शाता है।' } },
  D60: { domain: { en: 'Past Life Karma & Overall Assessment', hi: 'पूर्वजन्म कर्म एवं समग्र मूल्यांकन', sa: 'पूर्वजन्म कर्म एवं समग्र मूल्यांकन', mai: 'पूर्वजन्म कर्म एवं समग्र मूल्यांकन', mr: 'पूर्वजन्म कर्म एवं समग्र मूल्यांकन', ta: 'Past Life Karma & Overall Assessment', te: 'Past Life Karma & Overall Assessment', bn: 'Past Life Karma & Overall Assessment', kn: 'Past Life Karma & Overall Assessment', gu: 'Past Life Karma & Overall Assessment' }, desc: { en: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.', hi: 'षष्ट्यंश को पराशर द्वारा सबसे सूक्ष्म और महत्वपूर्ण विभागीय चार्ट माना गया है। यह पूर्वजन्म के कार्मिक प्रारूपों और उनके वर्तमान जीवन में फलित होने को दर्शाता है।', sa: 'षष्ट्यंश को पराशर द्वारा सबसे सूक्ष्म और महत्वपूर्ण विभागीय चार्ट माना गया है। यह पूर्वजन्म के कार्मिक प्रारूपों और उनके वर्तमान जीवन में फलित होने को दर्शाता है।', mai: 'षष्ट्यंश को पराशर द्वारा सबसे सूक्ष्म और महत्वपूर्ण विभागीय चार्ट माना गया है। यह पूर्वजन्म के कार्मिक प्रारूपों और उनके वर्तमान जीवन में फलित होने को दर्शाता है।', mr: 'षष्ट्यंश को पराशर द्वारा सबसे सूक्ष्म और महत्वपूर्ण विभागीय चार्ट माना गया है। यह पूर्वजन्म के कार्मिक प्रारूपों और उनके वर्तमान जीवन में फलित होने को दर्शाता है।', ta: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.', te: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.', bn: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.', kn: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.', gu: 'The Shashtiamsha is considered the most subtle and important divisional chart by Parashara. It reveals past life karmic patterns and their present-life fruition. Each of the 60 divisions has a specific deity and quality. Strong D60 confirms the promises of other charts.' } },
};

// ─── Core analysis ──────────────────────────────────────────────────────────

function analyzeChart(
  chartKey: string,
  chart: { houses: number[][]; ascendantSign: number },
  kundali: KundaliData,
  locale: string,
): VargaChartTippanni {
  const domain = VARGA_DOMAINS[chartKey] || { domain: { en: chartKey, hi: chartKey }, desc: { en: '', hi: '', sa: '', mai: '', mr: '', ta: '', te: '', bn: '', kn: '', gu: '' } };
  const ascLord = signLord(chart.ascendantSign);
  const ascLordName = PN[ascLord] || PN[0];
  const ascRashi = rashiName(chart.ascendantSign, locale);

  // Find lagna lord house
  let ascLordHouse = 1;
  for (let h = 0; h < 12; h++) {
    if (chart.houses[h].includes(ascLord)) { ascLordHouse = h + 1; break; }
  }

  // Count benefics/malefics in key houses
  let beneficInGood = 0, maleficInDusthana = 0, beneficInKendra = 0;
  const planetHouseMap: Record<number, number> = {};
  for (let h = 0; h < 12; h++) {
    for (const pid of chart.houses[h]) {
      planetHouseMap[pid] = h + 1;
      if (BENEFICS.has(pid) && GOOD.has(h + 1)) beneficInGood++;
      if (BENEFICS.has(pid) && KENDRAS.has(h + 1)) beneficInKendra++;
      if (MALEFICS.has(pid) && DUSTHANAS.has(h + 1)) maleficInDusthana++;
    }
  }

  const strength: 'strong' | 'moderate' | 'weak' = beneficInGood >= 3 ? 'strong' : beneficInGood >= 1 ? 'moderate' : 'weak';

  // ─── Key findings ────────────────────────────────────────────
  const findings: Bi[] = [];

  // Lagna lord
  findings.push({
    en: `${chartKey} Ascendant: ${rashiName(chart.ascendantSign, 'en')} — Lagna lord ${ascLordName.en} placed in the ${ord(ascLordHouse)} house${GOOD.has(ascLordHouse) ? ' (favorable position)' : DUSTHANAS.has(ascLordHouse) ? ' (challenging — dusthana placement)' : ''}.`,
    hi: `${chartKey} लग्न: ${rashiName(chart.ascendantSign, 'hi')} — लग्नेश ${ascLordName.hi} ${ascLordHouse}वें भाव में${GOOD.has(ascLordHouse) ? ' (अनुकूल स्थिति)' : DUSTHANAS.has(ascLordHouse) ? ' (चुनौतीपूर्ण — दुःस्थान)' : ''}।`,
  });

  // Planets in 1st house
  const h1 = planetsIn(chart, 1);
  if (h1.length > 0) {
    const names = h1.map(p => PN[p]?.en || '').join(', ');
    const namesHi = h1.map(p => PN[p]?.hi || '').join(', ');
    const hasBenefic = h1.some(p => BENEFICS.has(p));
    findings.push({
      en: `${names} in ${chartKey} lagna — ${hasBenefic ? 'benefic influence strengthens this domain naturally' : 'malefic influence brings challenges requiring conscious effort'}.`,
      hi: `${namesHi} ${chartKey} लग्न में — ${hasBenefic ? 'शुभ प्रभाव इस क्षेत्र को स्वाभाविक रूप से सशक्त करता है' : 'पाप प्रभाव चुनौतियाँ लाता है, सचेत प्रयास आवश्यक'}।`,
    });
  }

  // Jupiter check
  const jupHouse = planetHouseMap[4];
  if (jupHouse && KENDRAS.has(jupHouse)) {
    findings.push({
      en: `Jupiter in ${ord(jupHouse)} house of ${chartKey} — powerful protection and growth. Jupiter's grace is active in this life area.`,
      hi: `${chartKey} के ${jupHouse}वें भाव में गुरु — शक्तिशाली सुरक्षा और विकास। गुरु कृपा इस जीवन क्षेत्र में सक्रिय।`,
    });
  }

  // Venus check (for D2, D16, D4)
  const venHouse = planetHouseMap[5];
  if (venHouse && ['D2', 'D4', 'D16'].includes(chartKey)) {
    findings.push({
      en: `Venus in ${ord(venHouse)} house — ${GOOD.has(venHouse) ? 'enhances material comforts and aesthetic pleasures' : 'material desires may face obstacles'}.`,
      hi: `${venHouse}वें भाव में शुक्र — ${GOOD.has(venHouse) ? 'भौतिक सुख और सौंदर्य संवर्धन' : 'भौतिक इच्छाओं में बाधा संभव'}।`,
    });
  }

  // Saturn check
  const satHouse = planetHouseMap[6];
  if (satHouse) {
    findings.push({
      en: `Saturn in ${ord(satHouse)} house — ${DUSTHANAS.has(satHouse) ? 'karmic delays in this area; patience and perseverance yield eventual results' : KENDRAS.has(satHouse) ? 'structured approach brings steady, long-term success' : 'moderate Saturn influence, disciplined effort helps'}.`,
      hi: `${satHouse}वें भाव में शनि — ${DUSTHANAS.has(satHouse) ? 'इस क्षेत्र में कार्मिक विलंब; धैर्य और लगन से परिणाम' : KENDRAS.has(satHouse) ? 'व्यवस्थित दृष्टिकोण से दीर्घकालिक सफलता' : 'मध्यम शनि प्रभाव, अनुशासित प्रयास सहायक'}।`,
    });
  }

  // Rahu-Ketu axis
  const rahuH = planetHouseMap[7];
  const ketuH = planetHouseMap[8];
  if (rahuH && ketuH) {
    findings.push({
      en: `Rahu-Ketu axis in ${ord(rahuH)}-${ord(ketuH)} houses — karmic growth axis active in these domains. Rahu brings obsessive desire, Ketu brings detachment and spiritual insight.`,
      hi: `राहु-केतु अक्ष ${rahuH}-${ketuH} भावों में — इन क्षेत्रों में कार्मिक विकास अक्ष सक्रिय। राहु तीव्र इच्छा, केतु वैराग्य और आध्यात्मिक अंतर्दृष्टि लाता है।`,
    });
  }

  // ─── D3-specific: Drekkana face archetypes per planet ────────
  if (chartKey === 'D3' && kundali.planets && kundali.planets.length > 0) {
    const SIGN_NAMES: Record<number, Bi> = {
      1: { en: 'Aries', hi: 'मेष', sa: 'मेष', mai: 'मेष', mr: 'मेष', ta: 'மேஷம்', te: 'మేషం', bn: 'মেষ', kn: 'ಮೇಷ', gu: 'મેષ' }, 2: { en: 'Taurus', hi: 'वृष', sa: 'वृष', mai: 'वृष', mr: 'वृष', ta: 'ரிஷபம்', te: 'వృషభం', bn: 'বৃষ', kn: 'ವೃಷಭ', gu: 'વૃષભ' }, 3: { en: 'Gemini', hi: 'मिथुन', sa: 'मिथुन', mai: 'मिथुन', mr: 'मिथुन', ta: 'மிதுனம்', te: 'మిథునం', bn: 'মিথুন', kn: 'ಮಿಥುನ', gu: 'મિથુન' },
      4: { en: 'Cancer', hi: 'कर्क', sa: 'कर्क', mai: 'कर्क', mr: 'कर्क', ta: 'கடகம்', te: 'కర్కాటకం', bn: 'কর্কট', kn: 'ಕರ್ಕಾಟಕ', gu: 'કર્ક' }, 5: { en: 'Leo', hi: 'सिंह', sa: 'सिंह', mai: 'सिंह', mr: 'सिंह', ta: 'சிம்மம்', te: 'సింహం', bn: 'সিংহ', kn: 'ಸಿಂಹ', gu: 'સિંહ' }, 6: { en: 'Virgo', hi: 'कन्या', sa: 'कन्या', mai: 'कन्या', mr: 'कन्या', ta: 'கன்னி', te: 'కన్య', bn: 'কন্যা', kn: 'ಕನ್ಯಾ', gu: 'કન્યા' },
      7: { en: 'Libra', hi: 'तुला', sa: 'तुला', mai: 'तुला', mr: 'तुला', ta: 'துலாம்', te: 'తుల', bn: 'তুলা', kn: 'ತುಲಾ', gu: 'તુલા' }, 8: { en: 'Scorpio', hi: 'वृश्चिक', sa: 'वृश्चिक', mai: 'वृश्चिक', mr: 'वृश्चिक', ta: 'விருச்சிகம்', te: 'వృశ్చికం', bn: 'বৃশ্চিক', kn: 'ವೃಶ್ಚಿಕ', gu: 'વૃશ્ચિક' }, 9: { en: 'Sagittarius', hi: 'धनु', sa: 'धनु', mai: 'धनु', mr: 'धनु', ta: 'தனுசு', te: 'ధనుస్సు', bn: 'ধনু', kn: 'ಧನು', gu: 'ધન' },
      10: { en: 'Capricorn', hi: 'मकर', sa: 'मकर', mai: 'मकर', mr: 'मकर', ta: 'மகரம்', te: 'మకరం', bn: 'মকর', kn: 'ಮಕರ', gu: 'મકર' }, 11: { en: 'Aquarius', hi: 'कुंभ', sa: 'कुंभ', mai: 'कुंभ', mr: 'कुंभ', ta: 'கும்பம்', te: 'కుంభం', bn: 'কুম্ভ', kn: 'ಕುಂಭ', gu: 'કુંભ' }, 12: { en: 'Pisces', hi: 'मीन', sa: 'मीन', mai: 'मीन', mr: 'मीन', ta: 'மீனம்', te: 'మీనం', bn: 'মীন', kn: 'ಮೀನ', gu: 'મીન' },
    };
    // Add section header
    findings.push({
      en: '— Drekkana Face Archetypes (Varahamihira, Brihat Jataka Ch.27) —',
      hi: '— द्रेष्काण मुख आदर्श (वराहमिहिर, बृहज्जातक अ.27) —',
    });
    for (const pp of kundali.planets) {
      const pid = pp.planet.id;
      if (pid === 7 || pid === 8) continue; // skip Rahu/Ketu — shadow, no physical face
      const { faceIndex, sign, face } = getDrekkanaFace(pp.longitude);
      const df = DREKKANA_FACES[faceIndex];
      if (!df) continue;
      const signNameEn = SIGN_NAMES[sign]?.en || '';
      const signNameHi = SIGN_NAMES[sign]?.hi || '';
      const pName = PN[pid];
      if (!pName) continue;
      findings.push({
        en: `${pName.en} — "${df.archetype.en}" (${signNameEn} face ${face}): ${df.quality.en}`,
        hi: `${pName.hi} — "${df.archetype.hi}" (${signNameHi} मुख ${face}): ${df.quality.hi}`,
      });
    }
  }

  // ─── Overall Commentary ──────────────────────────────────────
  const strengthWord = { strong: { en: 'strong', hi: 'बलवान', sa: 'बलवान', mai: 'बलवान', mr: 'बलवान', ta: 'வலிமை', te: 'బలవంతం', bn: 'বলবান', kn: 'ಬಲವಂತ', gu: 'બળવાન' }, moderate: { en: 'moderate', hi: 'मध्यम', sa: 'मध्यम', mai: 'मध्यम', mr: 'मध्यम', ta: 'மத்திமம்', te: 'మధ్యమం', bn: 'মধ্যম', kn: 'ಮಧ್ಯಮ', gu: 'મધ્યમ' }, weak: { en: 'weak', hi: 'दुर्बल', sa: 'दुर्बल', mai: 'दुर्बल', mr: 'दुर्बल', ta: 'பலவீனம்', te: 'దుర్బలం', bn: 'দুর্বল', kn: 'ದುರ್ಬಲ', gu: 'દુર્બળ' } }[strength];

  const overallCommentary: Bi = {
    en: `${domain.desc.en}\n\nIn your chart, ${chartKey} shows ${strengthWord.en} strength with ${rashiName(chart.ascendantSign, 'en')} rising. The lagna lord ${ascLordName.en} is placed in the ${ord(ascLordHouse)} house${GOOD.has(ascLordHouse) ? ', which supports positive outcomes in this domain' : DUSTHANAS.has(ascLordHouse) ? ', suggesting challenges that require remedial measures and conscious effort' : ''}. ${beneficInKendra > 0 ? `With ${beneficInKendra} benefic(s) in kendras, there is inherent support for this area of life.` : 'The absence of benefics in kendras suggests that results in this domain come through sustained effort rather than natural fortune.'}${maleficInDusthana > 0 ? ` ${maleficInDusthana} malefic(s) in dusthanas here can actually be protective — malefics in the 6th house defeat enemies.` : ''}`,
    hi: `${domain.desc.hi}\n\nआपके चार्ट में, ${chartKey} ${strengthWord.hi} बल दर्शाता है, ${rashiName(chart.ascendantSign, 'hi')} उदय हो रहा है। लग्नेश ${ascLordName.hi} ${ascLordHouse}वें भाव में स्थित हैं${GOOD.has(ascLordHouse) ? ', जो इस क्षेत्र में अनुकूल परिणामों का समर्थन करता है' : DUSTHANAS.has(ascLordHouse) ? ', जो चुनौतियों का संकेत है जिनके लिए उपचारात्मक उपाय आवश्यक हैं' : ''}। ${beneficInKendra > 0 ? `केंद्र में ${beneficInKendra} शुभ ग्रह से इस जीवन क्षेत्र में स्वाभाविक समर्थन मिलता है।` : 'केंद्र में शुभ ग्रहों की अनुपस्थिति बताती है कि इस क्षेत्र में परिणाम निरंतर प्रयास से आते हैं।'}`,
  };

  // ─── Prognosis (next 1-2 years) — layered domain-specific engine ─
  const currentDasha = findCurrentDasha(kundali.dashas);
  let prognosis: Bi;

  if (currentDasha) {
    const mahaPid = planetId(currentDasha.maha.planet);
    const antarPid = currentDasha.antar ? planetId(currentDasha.antar.planet) : -1;
    const mahaHouseInChart = planetHouseMap[mahaPid];
    const antarHouseInChart = antarPid >= 0 ? planetHouseMap[antarPid] : undefined;

    const mahaName = currentDasha.maha.planetName;
    const antarName = currentDasha.antar?.planetName;

    prognosis = generateDashaPrognosis({
      chartKey,
      domainEn: domain.domain.en,
      domainHi: domain.domain.hi || "",
      mahaPlanetId: mahaPid,
      mahaPlanetNameEn: mahaName.en,
      mahaPlanetNameHi: mahaName.hi || "",
      mahaHouse: mahaHouseInChart,
      antarPlanetId: antarPid,
      antarPlanetNameEn: antarName?.en || '',
      antarPlanetNameHi: antarName?.hi || '',
      antarHouse: antarHouseInChart,
      antarEndDate: currentDasha.antar?.endDate,
      ascendantSign: chart.ascendantSign,
      beneficsInKendra: beneficInKendra,
      maleficsInDusthana: maleficInDusthana,
    });
  } else {
    prognosis = {
      en: `Dasha data not available for prognosis. Generate a kundali with accurate birth time for detailed timing predictions in ${domain.domain.en.toLowerCase()}.`,
      hi: `प्रगति के लिए दशा डेटा उपलब्ध नहीं। ${domain.domain.hi} में विस्तृत समय पूर्वानुमान के लिए सटीक जन्म समय के साथ कुण्डली बनाएं।`,
    };
  }

  // Determine chart meaning
  const dcMeaning = (VARGA_DOMAINS[chartKey]?.domain) || { en: chartKey, hi: chartKey };
  const dcLabel = VARGA_DOMAINS[chartKey]?.domain || { en: chartKey, hi: chartKey };

  return {
    chart: chartKey,
    label: dcLabel,
    meaning: dcMeaning,
    strength,
    overallCommentary,
    prognosis,
    keyFindings: findings,
  };
}

// ─── Main export ────────────────────────────────────────────────────────────

export function generateVargaTippanni(kundali: KundaliData, locale: Locale): VargaSynthesis {
  const vargaInsights: VargaChartTippanni[] = [];
  const strongAreas: Bi[] = [];
  const weakAreas: Bi[] = [];

  // D1
  vargaInsights.push(analyzeChart('D1', kundali.chart, kundali, locale));

  // Bhav Chalit
  if (kundali.bhavChalitChart) {
    vargaInsights.push(analyzeChart('BC', kundali.bhavChalitChart, kundali, locale));
  }

  // D9
  vargaInsights.push(analyzeChart('D9', kundali.navamshaChart, kundali, locale));

  // All other divisional charts
  if (kundali.divisionalCharts) {
    for (const [key, dc] of Object.entries(kundali.divisionalCharts)) {
      vargaInsights.push(analyzeChart(key, dc, kundali, locale));
    }
  }

  // Categorize
  for (const v of vargaInsights) {
    if (v.strength === 'strong') strongAreas.push(v.meaning);
    else if (v.strength === 'weak') weakAreas.push(v.meaning);
  }

  // Synthesis
  const strongCount = vargaInsights.filter(v => v.strength === 'strong').length;
  const weakCount = vargaInsights.filter(v => v.strength === 'weak').length;
  const total = vargaInsights.length;

  let overallEn: string, overallHi: string;
  if (strongCount > total * 0.5) {
    overallEn = `Across ${total} divisional charts analyzed, ${strongCount} show strong varga strength — this is an excellent overall chart. The native has accumulated significant positive karma across multiple life domains. Key benefic placements in kendras and trikonas provide natural support. Focus particularly on D9 (marriage/dharma) and D10 (career) for the most impactful life outcomes. The D60 (Shashtiamsha) confirms the overall karmic trajectory.`;
    overallHi = `विश्लेषित ${total} विभागीय चार्टों में ${strongCount} मजबूत वर्ग बल दिखाते हैं — यह उत्कृष्ट समग्र कुंडली है। जातक ने कई जीवन क्षेत्रों में महत्वपूर्ण सकारात्मक कर्म संचित किए हैं। D9 (विवाह/धर्म) और D10 (करियर) पर विशेष ध्यान दें।`;
  } else if (weakCount > total * 0.4) {
    overallEn = `The varga analysis reveals ${weakCount} out of ${total} charts showing weakness — this indicates karmic lessons across multiple areas. However, this is not deterministic; remedial measures, gemstones, mantras, and conscious effort can significantly mitigate challenges. The strong charts (${strongCount}) show areas of natural talent and support that can be leveraged. Past life karma (D60) shapes the foundation, but present actions (D1, D10) determine the outcome.`;
    overallHi = `वर्ग विश्लेषण ${total} में से ${weakCount} चार्ट में दुर्बलता दर्शाता है — यह कई क्षेत्रों में कार्मिक शिक्षा का संकेत है। हालांकि, उपचारात्मक उपाय, रत्न, मंत्र और सचेत प्रयास चुनौतियों को काफी हद तक कम कर सकते हैं। मजबूत चार्ट (${strongCount}) प्राकृतिक प्रतिभा के क्षेत्र दर्शाते हैं।`;
  } else {
    overallEn = `The varga analysis presents a balanced picture with ${strongCount} strong, ${total - strongCount - weakCount} moderate, and ${weakCount} weak charts out of ${total} total. This is a typical and workable configuration — most people have a mix of strengths and growth areas. The divisional charts that show strength indicate domains where results come naturally, while weaker charts point to areas requiring more conscious effort, remedial practices, or spiritual growth. The current dasha period will activate specific charts — check the prognosis section of each chart for timing insights.`;
    overallHi = `वर्ग विश्लेषण ${total} में से ${strongCount} बलवान, ${total - strongCount - weakCount} मध्यम और ${weakCount} दुर्बल चार्टों के साथ संतुलित चित्र प्रस्तुत करता है। यह एक विशिष्ट और साध्य विन्यास है। शक्तिशाली चार्ट स्वाभाविक परिणामों के क्षेत्र दर्शाते हैं, जबकि कमजोर चार्ट अधिक प्रयास की आवश्यकता वाले क्षेत्र इंगित करते हैं।`;
  }

  return {
    overall: { en: overallEn, hi: overallHi },
    strongAreas,
    weakAreas,
    vargaInsights,
  };
}
