/**
 * Interpretive commentary database
 * Structured text interpretations for Lagna, Moon sign, and planetary placements
 */

import type { GrahaId } from './types';

export const LAGNA_INTERPRETATIONS: Record<number, { title: string; personality: string; career: string; health: string }> = {
  0: {
    title: 'Aries Ascendant (Mesha Lagna)',
    personality: 'You are naturally courageous, energetic, and pioneering. Your approach to life is direct and assertive. You have strong leadership qualities and prefer to forge your own path rather than follow others.',
    career: 'You excel in roles requiring initiative — entrepreneurship, military, sports, surgery, or any field demanding decisive action and physical energy.',
    health: 'Watch for headaches, inflammation, and overexertion. Your fiery constitution benefits from cooling activities and adequate rest.',
  },
  1: {
    title: 'Taurus Ascendant (Vrishabha Lagna)',
    personality: 'You are grounded, patient, and value stability. With a deep appreciation for beauty and comfort, you build your life carefully and methodically. Your loyalty is unwavering.',
    career: 'Finance, agriculture, arts, music, luxury goods, real estate, and food industries align with your nature. You build wealth steadily over time.',
    health: 'Throat-related issues and weight management need attention. Your strong constitution benefits from regular, moderate exercise.',
  },
  2: {
    title: 'Gemini Ascendant (Mithuna Lagna)',
    personality: 'Quick-witted, communicative, and intellectually curious. You are adaptable and thrive on variety. Your dual nature allows you to see multiple perspectives simultaneously.',
    career: 'Writing, journalism, teaching, trading, communication, technology, and any field requiring mental agility suit you well.',
    health: 'Nervous system and respiratory health need attention. Mental relaxation techniques will benefit you greatly.',
  },
  3: {
    title: 'Cancer Ascendant (Karka Lagna)',
    personality: 'Deeply intuitive, nurturing, and emotionally intelligent. You have a strong connection to home and family. Your protective instincts make you a natural caregiver.',
    career: 'Healthcare, hospitality, real estate, counseling, food services, and caregiving roles align with your empathetic nature.',
    health: 'Digestive health and emotional well-being are key focus areas. Water-based activities provide therapeutic benefit.',
  },
  4: {
    title: 'Leo Ascendant (Simha Lagna)',
    personality: 'Regal, confident, and generous. You have a natural magnetism that draws others to you. Your warmth and creativity inspire those around you.',
    career: 'Leadership positions, entertainment, politics, education, and creative arts. You thrive when you can express your vision and inspire others.',
    health: 'Heart health and stress management deserve attention. Your robust constitution benefits from joyful physical activity.',
  },
  5: {
    title: 'Virgo Ascendant (Kanya Lagna)',
    personality: 'Analytical, detail-oriented, and service-minded. You have a keen eye for improvement and a practical approach to solving problems. Perfectionism is both your strength and challenge.',
    career: 'Healthcare, analytics, editing, accounting, research, quality control, and any precision-oriented profession suits your meticulous nature.',
    health: 'Digestive health and nervous tension need management. Regular routines and clean eating support your well-being.',
  },
  6: {
    title: 'Libra Ascendant (Tula Lagna)',
    personality: 'Diplomatic, aesthetic, and partnership-oriented. You seek balance and harmony in all things. Your social grace and fair-mindedness make you an excellent mediator.',
    career: 'Law, diplomacy, design, fashion, art curation, counseling, and partnership-based ventures align with your balanced approach.',
    health: 'Kidney health and lower back care need attention. Maintaining emotional balance directly supports physical well-being.',
  },
  7: {
    title: 'Scorpio Ascendant (Vrischika Lagna)',
    personality: 'Intense, perceptive, and transformative. You possess remarkable depth and determination. Your ability to see beneath surfaces gives you powerful insight into human nature.',
    career: 'Research, psychology, detective work, surgery, occult sciences, insurance, and crisis management harness your investigative depth.',
    health: 'Reproductive health and stress-related conditions need attention. Transformative practices like yoga profoundly benefit you.',
  },
  8: {
    title: 'Sagittarius Ascendant (Dhanu Lagna)',
    personality: 'Optimistic, philosophical, and adventurous. You are a natural teacher and explorer, always seeking higher meaning. Your enthusiasm is contagious.',
    career: 'Education, law, publishing, travel industry, philosophy, religion, international business, and any expansive field suits your broad vision.',
    health: 'Hip and liver health need monitoring. Active outdoor pursuits and moderation in indulgence support your well-being.',
  },
  9: {
    title: 'Capricorn Ascendant (Makara Lagna)',
    personality: 'Disciplined, ambitious, and responsible. You approach life with maturity and strategic thinking. Your patience and persistence lead to lasting achievements.',
    career: 'Government, management, construction, engineering, mining, and any structured hierarchy where you can climb to the top through dedication.',
    health: 'Joint health, especially knees, and bone density need attention. Regular, disciplined exercise suits your constitution perfectly.',
  },
  10: {
    title: 'Aquarius Ascendant (Kumbha Lagna)',
    personality: 'Innovative, humanitarian, and intellectually independent. You think ahead of your time and are drawn to social reform. Your unique perspective challenges convention.',
    career: 'Technology, social work, science, invention, networking, humanitarian organizations, and progressive fields that benefit from unconventional thinking.',
    health: 'Circulation and nervous system health need attention. Group activities and community involvement support emotional well-being.',
  },
  11: {
    title: 'Pisces Ascendant (Meena Lagna)',
    personality: 'Compassionate, imaginative, and spiritually attuned. You experience life through a lens of empathy and intuition. Your creative vision transcends the ordinary.',
    career: 'Healing arts, music, cinema, spirituality, marine industries, charitable work, and any field where imagination and compassion are valued.',
    health: 'Feet and immune system health need attention. Spiritual practices, swimming, and adequate rest are deeply beneficial.',
  },
};

export const PLANET_IN_HOUSE: Record<string, Record<number, string>> = {
  sun: {
    1: 'Sun in the 1st house gives a strong sense of self, leadership ability, and vitality. You are confident and have a commanding presence. Government and authority figures play an important role in your life.',
    2: 'Sun in the 2nd house indicates wealth through government or authority. Your speech carries weight. Family values and financial security are important to your identity.',
    3: 'Sun in the 3rd house gives courage, strong willpower, and good relationships with siblings. You excel in communication and short travels bring success.',
    4: 'Sun in the 4th house indicates a strong connection to home and mother. Property and vehicles may come through government connections. Inner happiness is linked to domestic stability.',
    5: 'Sun in the 5th house is excellent for intelligence, creativity, and connection with children. Education, speculation, and past-life merit bring success.',
    6: 'Sun in the 6th house gives ability to overcome enemies and competition. Service-oriented career suits you. Health needs attention but you recover well from illness.',
    7: 'Sun in the 7th house brings a powerful spouse but requires balancing ego in partnerships. Business partnerships with government or authority figures are possible.',
    8: 'Sun in the 8th house indicates transformation through challenges. Interest in occult, research, and hidden knowledge. Inheritance matters may be significant.',
    9: 'Sun in the 9th house is fortunate for higher education, long journeys, and spiritual pursuits. Father is influential. You may earn recognition for wisdom and righteousness.',
    10: 'Sun in the 10th house is powerful for career success, fame, and public recognition. Government service or leadership roles bring fulfillment. This is one of the best placements for professional achievement.',
    11: 'Sun in the 11th house brings gains through powerful connections. Your ambitions and desires find fulfillment. Elder siblings and influential friends support your goals.',
    12: 'Sun in the 12th house indicates expenses on good causes, spiritual growth, and possible foreign residence. Ego dissolution leads to spiritual advancement.',
  },
  moon: {
    1: 'Moon in the 1st house gives an emotional, intuitive, and receptive personality. You are deeply influenced by your environment and have strong nurturing instincts.',
    2: 'Moon in the 2nd house indicates fluctuating finances but good imagination. Family life is emotionally rich. Your speech has an emotional quality that touches others.',
    3: 'Moon in the 3rd house gives emotional courage and strong bonds with siblings. You may travel frequently and have a changeable mind that adapts quickly.',
    4: 'Moon in the 4th house is very strong — it brings emotional contentment, a comfortable home, and a loving relationship with your mother. Inner peace comes naturally.',
    5: 'Moon in the 5th house gives emotional intelligence, creative talent, and strong bonding with children. Romance is emotionally fulfilling. Intuition guides your speculations.',
    6: 'Moon in the 6th house indicates emotional challenges from enemies or health issues. Service to others is healing. Maternal relatives play a significant role.',
    7: 'Moon in the 7th house brings an emotionally nurturing partner. Partnerships are based on emotional connection. Public dealings are influenced by emotional intelligence.',
    8: 'Moon in the 8th house brings emotional depth and psychic sensitivity. Transformative experiences shape your emotional landscape. Interest in mystical subjects.',
    9: 'Moon in the 9th house gives religious and philosophical inclinations. Long journeys over water are likely. Your mother is a source of spiritual guidance.',
    10: 'Moon in the 10th house brings public popularity and a career involving the public. Emotions drive your professional ambitions. Fame may come through nurturing roles.',
    11: 'Moon in the 11th house fulfills desires and brings gains through women and public. Social circle is supportive and emotionally enriching.',
    12: 'Moon in the 12th house indicates spending on comfort, possible foreign settlement, and rich inner life. Dreams and subconscious patterns are powerful guides.',
  },
  jupiter: {
    1: 'Jupiter in the 1st house blesses the native with wisdom, optimism, and good fortune. You have a philosophical nature and attract opportunities naturally. Health is generally robust.',
    2: 'Jupiter in the 2nd house is excellent for wealth, family happiness, and eloquent speech. Your values are noble and you attract financial abundance through wisdom.',
    3: 'Jupiter in the 3rd house gives wise counsel, good relationships with siblings, and success through communication. Short journeys bring learning opportunities.',
    4: 'Jupiter in the 4th house brings domestic happiness, property, vehicles, and a comfortable home. Education is blessed and your mother is wise and supportive.',
    5: 'Jupiter in the 5th house is one of the best placements — it gives intelligence, good children, spiritual merit, and success in education and speculation.',
    6: 'Jupiter in the 6th house helps overcome obstacles through wisdom. You excel in service and healing. Legal matters generally resolve in your favor.',
    7: 'Jupiter in the 7th house brings a wise and noble spouse. Partnerships are fortunate and business ventures prosper through ethical dealing.',
    8: 'Jupiter in the 8th house protects from sudden harm and gives interest in occult wisdom. Longevity is favored and you may benefit from inheritance.',
    9: 'Jupiter in the 9th house is extremely fortunate — it indicates great wisdom, spiritual advancement, prosperity, and blessings from teachers and father.',
    10: 'Jupiter in the 10th house brings career success, ethical leadership, and social respect. Professional life is guided by higher principles and attracts prosperity.',
    11: 'Jupiter in the 11th house fulfills ambitions and brings gains through knowledge. Your social network includes wise and influential people.',
    12: 'Jupiter in the 12th house favors spiritual growth, foreign travel, and charitable deeds. Expenses go toward good causes and moksha is attainable.',
  },
  venus: {
    1: 'Venus in the 1st house gives charm, beauty, and artistic sensibility. You attract others naturally and have a refined aesthetic sense. Life has many pleasurable experiences.',
    2: 'Venus in the 2nd house is excellent for wealth, sweet speech, and family harmony. You accumulate beautiful possessions and enjoy fine food.',
    3: 'Venus in the 3rd house gives artistic talents, harmonious relationship with siblings, and success in communication-based creative fields.',
    4: 'Venus in the 4th house brings luxury at home, beautiful vehicles, and domestic happiness. Your living space is aesthetically pleasing and comfortable.',
    5: 'Venus in the 5th house gives romantic fulfillment, creative talent, and pleasure from children. Entertainment and arts bring joy and possibly income.',
    6: 'Venus in the 6th house indicates challenges in relationships but success in service-related fields. Artistic abilities may be applied in healing or service.',
    7: 'Venus in the 7th house is strong for marriage and partnerships. Your spouse is attractive and relationship-oriented. Business partnerships prosper.',
    8: 'Venus in the 8th house gives sensual depth, possible inheritance, and interest in tantric arts. Transformation comes through intimate relationships.',
    9: 'Venus in the 9th house brings fortune through arts, beauty, and culture. Foreign connections are pleasant. Spiritual life has a devotional quality.',
    10: 'Venus in the 10th house brings career success in arts, beauty, fashion, or entertainment. Public image is charming and career brings pleasure.',
    11: 'Venus in the 11th house fulfills desires for luxury and pleasure. Gains come through women, arts, and social connections.',
    12: 'Venus in the 12th house indicates pleasures in foreign lands, rich fantasy life, and spiritual love. Bedroom pleasures are emphasized.',
  },
  mars: {
    1: 'Mars in the 1st house gives courage, energy, and a competitive spirit. You are assertive and action-oriented. Physical vitality is strong but watch for impulsiveness.',
    2: 'Mars in the 2nd house indicates aggressive speech and fighting for financial security. Family life may have conflicts. Earnings come through effort and courage.',
    3: 'Mars in the 3rd house is excellent — it gives valor, adventurous spirit, and strong siblings. You excel in competitive fields and bold communication.',
    4: 'Mars in the 4th house brings energy to domestic life but possible property disputes. Real estate dealings are active. Relationship with mother may be intense.',
    5: 'Mars in the 5th house gives competitive intelligence, athletic children, and risk-taking in speculation. Education may be in technical or military fields.',
    6: 'Mars in the 6th house is powerful for defeating enemies and overcoming obstacles. Excellent placement for military, surgery, or competitive careers.',
    7: 'Mars in the 7th house (Manglik) brings an energetic spouse but requires patience in marriage. Passion is strong in partnerships.',
    8: 'Mars in the 8th house indicates accidents, surgery, or sudden events. Research ability is strong. Interest in martial arts and occult.',
    9: 'Mars in the 9th house gives fighting spirit for beliefs, active father, and courage in long journeys. You defend your philosophy vigorously.',
    10: 'Mars in the 10th house is powerful for career achievement through courage and effort. Military, police, engineering, and surgery are favored.',
    11: 'Mars in the 11th house brings gains through courage and competition. Friends are energetic. Ambitions are fulfilled through bold action.',
    12: 'Mars in the 12th house indicates expenses through conflict, foreign residence, and hidden enemies. Energy is directed toward spiritual practices or secret activities.',
  },
  saturn: {
    1: 'Saturn in the 1st house gives a serious, disciplined personality. Life lessons come through patience and hard work. Longevity is favored. Early life may have restrictions.',
    2: 'Saturn in the 2nd house delays wealth but ensures lasting prosperity through hard work. Speech is measured and authoritative. Family duties are taken seriously.',
    3: 'Saturn in the 3rd house gives determination and persistence. Siblings may face challenges. You succeed through disciplined effort and patient communication.',
    4: 'Saturn in the 4th house indicates delayed domestic happiness but eventual stability. Property comes through hard work. Relationship with mother teaches patience.',
    5: 'Saturn in the 5th house delays children or gives serious-minded offspring. Education requires persistence. Speculation should be approached cautiously.',
    6: 'Saturn in the 6th house is good for overcoming long-term obstacles. Service-oriented career brings gradual recognition. Health improves with age.',
    7: 'Saturn in the 7th house delays marriage or brings a mature spouse. Partnerships require patience but are lasting. Business deals need careful attention.',
    8: 'Saturn in the 8th house gives longevity and interest in deep research. Chronic health issues need management. Transformation comes slowly but thoroughly.',
    9: 'Saturn in the 9th house gives a disciplined spiritual practice. Higher education may be delayed but is thorough. Father teaches lessons of responsibility.',
    10: 'Saturn in the 10th house is powerful for career through steady effort. Government service, management, or any structured field brings success over time.',
    11: 'Saturn in the 11th house brings gains through persistent effort. Success comes after delays. Elder siblings are hardworking. Goals are achieved in the long run.',
    12: 'Saturn in the 12th house indicates foreign residence, spiritual discipline, and expenses on long-term projects. Liberation through persistent spiritual practice.',
  },
  mercury: {
    1: 'Mercury in the 1st house gives a youthful, communicative, and intellectually curious personality. You are witty, adaptable, and skilled in multiple areas.',
    2: 'Mercury in the 2nd house is excellent for wealth through intellect and communication. Your speech is clever and persuasive. Family values education.',
    3: 'Mercury in the 3rd house is very strong — it gives excellent communication skills, writing talent, and harmonious sibling relationships.',
    4: 'Mercury in the 4th house gives an educated home environment and intellectual interests. Real estate transactions are favorable. Learning continues at home.',
    5: 'Mercury in the 5th house gives sharp intelligence, skill in speculation, and intellectually gifted children. Creative writing and teaching abilities are strong.',
    6: 'Mercury in the 6th house helps solve problems analytically. Good for medical, legal, or service professions. You outthink your opponents.',
    7: 'Mercury in the 7th house brings an intelligent spouse and successful business partnerships. Communication is key to your relationship success.',
    8: 'Mercury in the 8th house gives research ability, interest in hidden knowledge, and analytical approach to mysteries. Financial acumen in joint resources.',
    9: 'Mercury in the 9th house gives interest in philosophy, teaching, and foreign cultures. Higher education is favored and you communicate wisdom effectively.',
    10: 'Mercury in the 10th house brings career success through intellect and communication. Business, writing, teaching, and technology are favored professions.',
    11: 'Mercury in the 11th house brings gains through intellectual pursuits and networking. Your social circle includes intelligent, communicative people.',
    12: 'Mercury in the 12th house gives a rich inner mental life, possible foreign communication-related work, and expenses on learning.',
  },
  rahu: {
    1: 'Rahu in the 1st house gives an unconventional personality with worldly ambitions. You may break social norms and forge a unique path. Foreign connections are beneficial.',
    2: 'Rahu in the 2nd house creates unusual patterns with wealth — sudden gains and losses. Speech may be unconventional. Foreign food and cultures attract you.',
    3: 'Rahu in the 3rd house gives courage through unconventional means. Communication through modern media is favored. Siblings may have unusual paths.',
    4: 'Rahu in the 4th house creates unique domestic situations. Property in foreign places is possible. Mother may be unconventional or from a different background.',
    5: 'Rahu in the 5th house gives unusual intelligence and unconventional approach to creativity. Children may follow unique paths. Speculation carries risk and reward.',
    6: 'Rahu in the 6th house is powerful for overcoming obstacles through unconventional methods. Victory over enemies and success in competitive fields.',
    7: 'Rahu in the 7th house may bring a spouse from a different culture or unconventional partnership. Business ventures with foreigners are favored.',
    8: 'Rahu in the 8th house gives fascination with the occult, sudden transformations, and potential for research in unconventional fields.',
    9: 'Rahu in the 9th house creates interest in foreign philosophies and unconventional spiritual paths. Long journeys to foreign lands are likely.',
    10: 'Rahu in the 10th house is powerful for career success through unconventional means. Fame, political ambition, and public recognition are indicated.',
    11: 'Rahu in the 11th house is excellent for fulfilling worldly desires. Large gains through technology, foreign connections, and networking.',
    12: 'Rahu in the 12th house indicates foreign residence, spiritual awakening through unconventional means, and expenses on travel.',
  },
  ketu: {
    1: 'Ketu in the 1st house gives a spiritual, detached personality with past-life wisdom. You may seem mysterious to others. Intuition is very strong.',
    2: 'Ketu in the 2nd house creates detachment from material wealth. Speech may be mystical or abstract. Family relationships have a karmic quality.',
    3: 'Ketu in the 3rd house gives spiritual courage and intuitive communication. Siblings may have spiritual inclinations. Past-life skills emerge naturally.',
    4: 'Ketu in the 4th house creates detachment from home and conventional domestic life. Spiritual practices at home bring peace.',
    5: 'Ketu in the 5th house gives mystical intelligence and spiritual merit from past lives. Children may be spiritually inclined.',
    6: 'Ketu in the 6th house helps overcome enemies through spiritual means. Healing abilities are strong. Service without attachment is natural.',
    7: 'Ketu in the 7th house creates detachment in relationships. Spouse may be spiritual. Partnerships have a karmic dimension.',
    8: 'Ketu in the 8th house is powerful for occult knowledge, meditation, and spiritual transformation. Moksha-oriented placement.',
    9: 'Ketu in the 9th house gives natural spiritual wisdom and dispassion. Religion is experienced internally. Father may be spiritual.',
    10: 'Ketu in the 10th house creates detachment from worldly ambition. Career may involve healing, spirituality, or research.',
    11: 'Ketu in the 11th house gives spiritual gains and detachment from material desires. True fulfillment comes through service and liberation.',
    12: 'Ketu in the 12th house is excellent for spiritual liberation (moksha). Strong meditation abilities. Past-life spiritual merit manifests.',
  },
};

export function getLagnaInterpretation(signIndex: number) {
  return LAGNA_INTERPRETATIONS[signIndex];
}

export function getPlanetInHouseInterpretation(planet: GrahaId, house: number): string {
  return PLANET_IN_HOUSE[planet]?.[house] ?? '';
}
