/**
 * Planet-in-house interpretive commentary (slim).
 *
 * Previously this file contained 218 lines covering LAGNA_INTERPRETATIONS,
 * PLANET_IN_HOUSE, and getter helpers — exported via the dead-code parallel
 * kundali engine at `src/lib/kundali/index.ts`. The parallel engine was
 * deleted in the 2026-06-01 ascendant-consolidation cleanup; only the
 * `PLANET_IN_HOUSE` constant survived because `sudarshana-interpretation.ts`
 * still consumes it.
 *
 * Anyone adding new interpretive commentary should prefer
 * `src/lib/kundali/tippanni-engine.ts` (the live narrative system).
 */

export const PLANET_IN_HOUSE: Record<string, Record<number, string>> = {
  sun: {
    1: 'Sun in the 1st house gives a strong sense of self, leadership ability, and vitality. You are confident and have a commanding presence. Government and authority figures play an important role in your life.',
    2: 'Sun in the 2nd house indicates wealth through government or authority. Your speech carries weight. Family values and financial security are important to your identity.',
    3: 'Sun in the 3rd house gives courage, energy, and success in efforts. You are self-motivated. Siblings (especially younger) may be a source of help.',
    4: 'Sun in the 4th house creates a strong-willed home environment. Father may have been dominant. Property and assets are gained through personal effort.',
    5: 'Sun in the 5th house is excellent for creativity, leadership in education, and authority over children. Speculative gains possible.',
    6: 'Sun in the 6th house gives victory over enemies, success in service, and good health. Government job possible. Father may have health concerns.',
    7: 'Sun in the 7th house brings authoritative partners. Marriage may be delayed. Spouse has strong personality. Public visibility is high.',
    8: 'Sun in the 8th house can stress vitality. Inheritance issues possible. Interest in occult and research. Father\'s health needs attention.',
    9: 'Sun in the 9th house is highly fortunate. Religious authority, philosophical depth, and success through father\'s blessings. Long-distance travel.',
    10: 'Sun in the 10th house is excellent for career and status. Natural leadership in profession. Government work or executive roles favored.',
    11: 'Sun in the 11th house brings income through authority figures. Large social network. Gains through father\'s connections.',
    12: 'Sun in the 12th house can dim vitality. Spiritual interests strong. Foreign residence possible. Father may live far away.',
  },
  moon: {
    1: 'Moon in the 1st house makes you emotional, intuitive, and nurturing. Mother\'s influence is strong. You change moods quickly. Public appeal is high.',
    2: 'Moon in the 2nd house gives sweet speech, family-oriented life, and changing financial fortunes. Wealth flows in cycles.',
    3: 'Moon in the 3rd house creates emotional bonds with siblings. Travel for emotional fulfillment. Communication is intuitive.',
    4: 'Moon in the 4th house is highly auspicious. Strong mother bond, peaceful home, emotional security. Property gains. Public popularity.',
    5: 'Moon in the 5th house gives creative imagination, love of children, romantic nature. Emotional intelligence in education.',
    6: 'Moon in the 6th house can cause emotional ups and downs through service and health. Mother may have illness. Pet companionship.',
    7: 'Moon in the 7th house brings emotional partnerships, often with someone nurturing. Public-facing career. Marriage strong if Moon is waxing.',
    8: 'Moon in the 8th house creates emotional intensity, interest in mysticism. Mother\'s longevity may be a concern. Sudden emotional changes.',
    9: 'Moon in the 9th house gives religious-philosophical bent. Long journeys connect to inner growth. Mother may be very spiritual.',
    10: 'Moon in the 10th house brings public career, work with masses (caring, healing, hospitality). Mother influences profession.',
    11: 'Moon in the 11th house creates many friends, income through women or public, multiple income sources. Emotional fulfillment via community.',
    12: 'Moon in the 12th house gives intuition, dreams, foreign connections. May feel emotionally isolated. Spiritual depth.',
  },
  mars: {
    1: 'Mars in the 1st house gives strength, athletic ability, courage. May have a sharp temper. Independent and assertive personality.',
    2: 'Mars in the 2nd house can cause sharp speech, financial volatility. Family disputes possible. Wealth through technical or military fields.',
    3: 'Mars in the 3rd house is excellent! Gives courage, technical skill, success through personal effort, supportive siblings. Sports ability.',
    4: 'Mars in the 4th house can disturb home peace, cause property disputes. Mother may face challenges. Need to manage anger at home.',
    5: 'Mars in the 5th house gives intelligent but argumentative nature. Children may be assertive. Stock market interest. Be cautious with speculation.',
    6: 'Mars in the 6th house gives victory over enemies, success in litigation, good in martial arts or surgery. Strong immunity.',
    7: 'Mars in the 7th house can create Manglik dosha (marital friction). Spouse is assertive. Late marriage often beneficial.',
    8: 'Mars in the 8th house creates Manglik dosha. Sudden events, accidents possible. Interest in surgery or occult. Manage anger carefully.',
    9: 'Mars in the 9th house gives bold philosophical/religious views, success in foreign lands, father may be assertive. Adventure-seeking.',
    10: 'Mars in the 10th house is excellent for career! Engineer, military, surgery, sports — fields requiring courage and energy thrive.',
    11: 'Mars in the 11th house brings income through technical work, real estate, or competitive fields. Many male friends.',
    12: 'Mars in the 12th house creates Manglik dosha. Hidden enemies. Foreign residence. Manage energy through spiritual practice.',
  },
  mercury: {
    1: 'Mercury in the 1st house gives intelligence, communication skills, business acumen. Youthful appearance. Multiple interests.',
    2: 'Mercury in the 2nd house is excellent for wealth through speech, writing, business. Eloquent. Family of educated people.',
    3: 'Mercury in the 3rd house gives writing/communication careers, good with siblings, short-distance travel. Curious and intelligent.',
    4: 'Mercury in the 4th house brings educated mother, intellectual home environment. Real estate or vehicle business possible.',
    5: 'Mercury in the 5th house gives intellectual creativity, success in education, stock market analysis, intelligent children.',
    6: 'Mercury in the 6th house excels in service, law, accounting, problem-solving. Mental work in technical fields.',
    7: 'Mercury in the 7th house brings intelligent spouse, business partnerships, success through negotiation. Trade and commerce favored.',
    8: 'Mercury in the 8th house creates interest in research, occult, depth psychology. Can give writer\'s abilities.',
    9: 'Mercury in the 9th house gives philosophical intelligence, success in publishing, law, higher education. Multilingual.',
    10: 'Mercury in the 10th house is excellent for career in communication, IT, business, writing, teaching. Multiple income streams.',
    11: 'Mercury in the 11th house brings income through intellect, networking, multiple sources. Younger friends. Online income.',
    12: 'Mercury in the 12th house gives interest in spirituality through study, foreign languages, behind-the-scenes intellectual work.',
  },
  jupiter: {
    1: 'Jupiter in the 1st house is highly auspicious! Wisdom, optimism, religious nature, good health, attractive personality.',
    2: 'Jupiter in the 2nd house brings wealth, sweet speech, supportive family, financial wisdom. Excellent for accumulating assets.',
    3: 'Jupiter in the 3rd house can dilute its effects but gives wise siblings, ethical communication, beneficial short journeys.',
    4: 'Jupiter in the 4th house is highly auspicious! Wise mother, beautiful home, property gains, peaceful inner life.',
    5: 'Jupiter in the 5th house is excellent! Intelligent children, success in education, creative wisdom, spiritual depth.',
    6: 'Jupiter in the 6th house gives victory over enemies through wisdom, success in law, healing professions. Service to elders.',
    7: 'Jupiter in the 7th house brings wise, religious spouse. Excellent business partnerships. Marriage is harmonious and lasting.',
    8: 'Jupiter in the 8th house gives interest in deep philosophy, longevity (if well-placed), inheritance. Spiritual transformations.',
    9: 'Jupiter in the 9th house is the BEST placement! Highly fortunate, deeply spiritual, philosophical wisdom, guru\'s grace.',
    10: 'Jupiter in the 10th house brings dharmic career: teacher, judge, priest, advisor. High respect in profession.',
    11: 'Jupiter in the 11th house gives substantial income, influential friends, multiple sources of wealth, big-picture thinking.',
    12: 'Jupiter in the 12th house gives spiritual liberation, charity, foreign travel for spiritual purposes. Ashram or monastery interest.',
  },
  venus: {
    1: 'Venus in the 1st house gives beauty, charm, artistic nature, refined tastes, love of luxury and pleasure.',
    2: 'Venus in the 2nd house brings wealth through beauty/art, sweet voice, eloquent speech, family harmony. Love of fine food.',
    3: 'Venus in the 3rd house gives artistic siblings, pleasant communication, creative writing. Travel for pleasure.',
    4: 'Venus in the 4th house creates beautiful home, vehicles, loving mother, harmonious family. Property gains.',
    5: 'Venus in the 5th house is excellent for creativity, romance, attractive children, success in arts and entertainment.',
    6: 'Venus in the 6th house can create relationship complications through work. Service in beauty/wellness industries.',
    7: 'Venus in the 7th house brings beautiful/charming spouse, harmonious marriage, success in business with women. Excellent placement.',
    8: 'Venus in the 8th house gives mystical sensuality, gains through spouse\'s wealth, longevity concerns for spouse.',
    9: 'Venus in the 9th house brings cultured higher education, beneficial foreign travel, fortunate marriage prospects.',
    10: 'Venus in the 10th house gives career in arts, entertainment, beauty, luxury. High social status. Diplomatic skill.',
    11: 'Venus in the 11th house brings income through arts/luxury, many female friends, fulfillment of desires.',
    12: 'Venus in the 12th house gives interest in mystical romance, foreign love affairs, comforts in bed, charitable spending.',
  },
  saturn: {
    1: 'Saturn in the 1st house gives a serious, disciplined personality. May feel older than years. Slow but steady success. Health needs care.',
    2: 'Saturn in the 2nd house brings slow wealth accumulation, family disputes possible, harsh speech may need refinement.',
    3: 'Saturn in the 3rd house is excellent! Disciplined effort brings success, hard-working siblings, technical skill.',
    4: 'Saturn in the 4th house can bring difficulties in home/mother area, but eventual property gains through hard work.',
    5: 'Saturn in the 5th house can delay children, intellectual discipline, traditional creative pursuits. Slow but solid in education.',
    6: 'Saturn in the 6th house is excellent! Defeats enemies through patience, success in service, government job, longevity.',
    7: 'Saturn in the 7th house delays marriage but brings disciplined spouse. Business partnerships with elders successful.',
    8: 'Saturn in the 8th house gives longevity, interest in occult, slow karmic transformation. Inheritance issues.',
    9: 'Saturn in the 9th house brings serious philosophical/religious nature. Late but profound spiritual development. Father may be strict.',
    10: 'Saturn in the 10th house is excellent for career! Long-lasting profession, government work, executive position through hard work.',
    11: 'Saturn in the 11th house brings income from older people, traditional industries. Patient gains through long-term effort.',
    12: 'Saturn in the 12th house can cause isolation, expenses, hospital/ashram stays. Karmic completion through suffering and service.',
  },
  rahu: {
    1: 'Rahu in the 1st house gives unconventional personality, ambitious nature, foreign element to self-image. Sudden rise possible.',
    2: 'Rahu in the 2nd house can disturb family relationships, sudden wealth gains/losses. Speech may be controversial.',
    3: 'Rahu in the 3rd house is excellent! Courage to break rules, success through unconventional efforts, technical innovation.',
    4: 'Rahu in the 4th house can disturb home life, frequent property changes, mother-related issues. Foreign property possible.',
    5: 'Rahu in the 5th house can complicate love life, give unconventional intelligence. Stock market gains/losses sudden.',
    6: 'Rahu in the 6th house is excellent for defeating enemies, success in foreign service, government job. Strong immunity.',
    7: 'Rahu in the 7th house creates unconventional partnerships, possible foreign spouse. Business in foreign goods.',
    8: 'Rahu in the 8th house gives interest in occult, sudden transformations, inheritance complications. Research abilities.',
    9: 'Rahu in the 9th house can challenge traditional religion. Foreign higher education. Unconventional spiritual path.',
    10: 'Rahu in the 10th house brings unconventional career, work with foreigners, sudden rises in profession. Innovation.',
    11: 'Rahu in the 11th house is excellent! Sudden income gains, foreign-connected wealth, large social circle.',
    12: 'Rahu in the 12th house brings foreign residence, hidden enemies, mysterious losses, spiritual research.',
  },
  ketu: {
    1: 'Ketu in the 1st house gives detachment from worldly identity, spiritual depth, may give physical sensitivity.',
    2: 'Ketu in the 2nd house can disturb family ties, detachment from material wealth, occult speech abilities.',
    3: 'Ketu in the 3rd house gives spiritual courage, detached relationship with siblings, mystical communication.',
    4: 'Ketu in the 4th house can give emotional detachment, mystical mother, frequent home changes, inner solitude.',
    5: 'Ketu in the 5th house can delay/complicate children, mystical intelligence, detached creativity. Past-life skills.',
    6: 'Ketu in the 6th house is excellent! Spiritual victory over enemies, healing abilities, detachment from petty conflicts.',
    7: 'Ketu in the 7th house can cause separation in marriage, spiritual partner, business complications.',
    8: 'Ketu in the 8th house gives strong occult/research abilities, mystical experiences, sudden spiritual transformations.',
    9: 'Ketu in the 9th house gives intuitive spiritual wisdom, mystical guru, detached from formal religion.',
    10: 'Ketu in the 10th house can cause career changes, spiritual profession, detachment from worldly success.',
    11: 'Ketu in the 11th house can disturb friendships, spiritual income sources, fulfillment through detachment.',
    12: 'Ketu in the 12th house is excellent for spiritual liberation (moksha). Strong meditation abilities. Past-life spiritual merit manifests.',
  },
};
