// Deep Lagna (Ascendant) interpretations — trilingual
// sign index is 1-based (1=Aries through 12=Pisces)

interface LagnaDeep {
  personality: { en: string; hi: string; sa: string };
  career: { en: string; hi: string; sa: string };
  health: { en: string; hi: string; sa: string };
  relationships: { en: string; hi: string; sa: string };
  finances: { en: string; hi: string; sa: string };
  spiritual: { en: string; hi: string; sa: string };
}

export const LAGNA_DEEP: Record<number, LagnaDeep> = {
  1: {
    personality: {
      en: 'You are naturally courageous, energetic, and pioneering. Your approach to life is direct and assertive — you prefer action over deliberation. Strong leadership qualities drive you to forge your own path. You have a quick temper but equally quick forgiveness. Your competitive spirit makes you excel when challenged, but impulsiveness can lead to premature decisions.',
      hi: 'आप स्वभाव से साहसी, ऊर्जावान और अग्रणी हैं। जीवन के प्रति आपका दृष्टिकोण प्रत्यक्ष और दृढ़ है। आप विचार-विमर्श से अधिक कर्म को प्राथमिकता देते हैं। आपमें नेतृत्व के उत्कृष्ट गुण हैं जो आपको अपना मार्ग बनाने की प्रेरणा देते हैं। क्रोध शीघ्र आता है पर क्षमा भी शीघ्र होती है।',
      sa: 'भवान् स्वभावतः शूरः ऊर्जावान् अग्रगामी च। जीवने भवतः दृष्टिकोणः प्रत्यक्षः दृढश्च। विमर्शात् कर्म प्रति भवतः प्राथमिकता वर्तते। नेतृत्वगुणाः भवन्तं स्वमार्गं निर्मातुं प्रेरयन्ति।',
    },
    career: {
      en: 'You excel in roles requiring initiative and decisive action — entrepreneurship, military, sports, surgery, engineering, or emergency services. You perform best when you can lead rather than follow. Stagnant environments drain you. Career peaks typically come through bold moves rather than gradual climbing. Self-employment and startups are strongly favored.',
      hi: 'आप पहल और निर्णायक कार्रवाई वाले क्षेत्रों में उत्कृष्ट होते हैं — उद्यमिता, सेना, खेल, शल्यचिकित्सा, अभियांत्रिकी। आप नेतृत्व करते हुए सर्वश्रेष्ठ प्रदर्शन करते हैं। स्थिर वातावरण आपकी ऊर्जा को क्षीण करता है। स्वरोजगार अत्यन्त अनुकूल है।',
      sa: 'उद्यमे सैन्ये क्रीडासु शल्यचिकित्सायां च भवान् उत्कृष्टः। नेतृत्वे भवतः श्रेष्ठं प्रदर्शनम्। स्वव्यवसायः अत्यन्तम् अनुकूलः।',
    },
    health: {
      en: 'Watch for headaches, inflammation, fevers, and injuries to the head and face. Your fiery constitution gives you strong recuperative powers but makes you prone to overexertion and burnout. Pitta-related conditions need management. Regular physical exercise is essential — without it, restlessness builds. Cooling foods and adequate rest balance your constitution.',
      hi: 'सिरदर्द, सूजन, बुखार और सिर-चेहरे की चोटों से सावधान रहें। आपकी अग्नि प्रकृति तीव्र पुनर्प्राप्ति शक्ति देती है पर अत्यधिक परिश्रम और थकान का खतरा रहता है। नियमित व्यायाम आवश्यक है। शीतल आहार और पर्याप्त विश्राम लाभदायक है।',
      sa: 'शिरोवेदना ज्वरः शिरसि मुखे च आघातः — एतेभ्यः सावधानता आवश्यकी। अग्निप्रकृतिः तीव्रां पुनर्प्राप्तिशक्तिं ददाति। नियमितव्यायामः अत्यावश्यकः।',
    },
    relationships: {
      en: 'In relationships, you are passionate, protective, and direct. You need a partner who can match your energy and independence without feeling overshadowed. Jealousy and possessiveness can surface if unchecked. Your ideal partner appreciates directness and shares your adventurous spirit. Marriage may happen early or impulsively.',
      hi: 'सम्बन्धों में आप भावुक, रक्षात्मक और प्रत्यक्ष हैं। आपको ऐसे साथी की आवश्यकता है जो आपकी ऊर्जा और स्वतन्त्रता से मेल खाए। ईर्ष्या और अधिकारभावना पर नियन्त्रण आवश्यक है। विवाह शीघ्र या आवेगपूर्ण हो सकता है।',
      sa: 'सम्बन्धेषु भवान् भावुकः रक्षकः प्रत्यक्षश्च। ऊर्जायां स्वातन्त्र्ये च समानं साथिनं भवान् अपेक्षते।',
    },
    finances: {
      en: 'You earn through bold initiatives and entrepreneurship. Money comes in bursts rather than steady streams. You tend to spend impulsively and must cultivate saving habits. Investments in real estate, sports, or defense sectors are favorable. Financial discipline improves significantly after age 35.',
      hi: 'आप साहसिक पहल और उद्यमिता से कमाते हैं। धन निरन्तर प्रवाह के बजाय लहरों में आता है। आवेगपूर्ण खर्च पर नियन्त्रण और बचत की आदत विकसित करना आवश्यक है। 35 वर्ष के बाद आर्थिक अनुशासन में सुधार होता है।',
      sa: 'साहसिकैः उद्यमैः भवान् अर्जयति। धनं निरन्तरप्रवाहात् भिन्नं तरङ्गेषु आगच्छति। पञ्चत्रिंशद्वर्षात् परम् आर्थिकानुशासनं सुधरति।',
    },
    spiritual: {
      en: 'Your spiritual path is one of action — Karma Yoga suits you best. You connect with the divine through heroic deeds, protecting the weak, and living with integrity. Mars-oriented deities (Hanuman, Kartikeya, Durga) resonate strongly. Meditation may be difficult initially but martial arts or dynamic meditation work well.',
      hi: 'आपका आध्यात्मिक मार्ग कर्मयोग है। आप वीरतापूर्ण कर्मों, दुर्बलों की रक्षा और सत्यनिष्ठा से ईश्वर से जुड़ते हैं। हनुमान, कार्तिकेय, दुर्गा — ये देवता आपके लिए विशेष अनुकूल हैं। गतिशील ध्यान और मार्शल आर्ट्स लाभदायक हैं।',
      sa: 'कर्मयोगः भवतः आध्यात्मिकमार्गः। शूरकर्मभिः दुर्बलरक्षणेन सत्यनिष्ठया च भवान् ईश्वरेण युज्यते। हनुमान् कार्तिकेयः दुर्गा च भवते विशेषानुकूलाः।',
    },
  },
  2: {
    personality: {
      en: 'You are grounded, patient, and value stability above all. With a deep appreciation for beauty and comfort, you build your life carefully and methodically. Your loyalty is unwavering and your determination immovable once committed. Stubbornness is your greatest challenge — you resist change even when beneficial. Sensual pleasures and material security form the foundation of your contentment.',
      hi: 'आप स्थिर, धैर्यवान और स्थायित्व को सर्वाधिक महत्व देते हैं। सौन्दर्य और आराम के प्रति गहरी रुचि के साथ आप जीवन को सावधानी और व्यवस्थित ढंग से बनाते हैं। आपकी निष्ठा अटल है। हठधर्मिता आपकी सबसे बड़ी चुनौती है।',
      sa: 'भवान् स्थिरः धैर्यवान् स्थायित्वं च सर्वाधिकं मन्यते। सौन्दर्यस्य सुखस्य च गहना अभिरुचिः। भवतः निष्ठा अचला।',
    },
    career: {
      en: 'Finance, agriculture, arts, music, luxury goods, real estate, food industry, and banking align with your nature. You build wealth steadily over time through patient effort. Creative fields involving beauty — interior design, fashion, culinary arts — are strongly favored. You prefer secure employment with clear growth paths over risky ventures.',
      hi: 'वित्त, कृषि, कला, संगीत, विलासिता, भूसम्पत्ति, खाद्य उद्योग और बैंकिंग आपकी प्रकृति के अनुकूल हैं। आप धैर्यपूर्ण प्रयास से स्थिर रूप से धन अर्जित करते हैं। सौन्दर्य से जुड़े रचनात्मक क्षेत्र विशेष अनुकूल हैं।',
      sa: 'वित्तं कृषिः कला सङ्गीतं विलासिता भूसम्पत्तिः — एतानि भवतः प्रकृत्यनुकूलानि। धैर्यपूर्णप्रयत्नेन स्थिरं धनम् अर्जयति।',
    },
    health: {
      en: 'Throat, thyroid, and neck issues need attention. Weight management is a lifelong focus — your love of good food combined with a tendency toward sedentary comfort can lead to metabolic issues. Strong constitution overall but slow to heal. Regular moderate exercise and portion control are key.',
      hi: 'गला, थायरॉइड और गर्दन सम्बन्धी समस्याओं पर ध्यान दें। वजन प्रबन्धन जीवनभर का ध्यान केन्द्र है। समग्र रूप से मजबूत संरचना परन्तु उपचार में धीमे। नियमित मध्यम व्यायाम और भोजन नियन्त्रण आवश्यक है।',
      sa: 'कण्ठः ग्रीवा च ध्यानम् अपेक्षते। भारप्रबन्धनं जीवनपर्यन्तं ध्यानकेन्द्रम्। सुदृढा काया परन्तु चिकित्सा मन्दगतिः।',
    },
    relationships: {
      en: 'Deeply devoted and sensual in love. You seek lasting, stable partnerships and are among the most loyal signs. Possessiveness can become an issue. You express love through material gifts and physical affection. Need a partner who values security and doesn\'t disrupt your routines.',
      hi: 'प्रेम में गहन समर्पित और भावुक। आप स्थायी, स्थिर साझेदारी चाहते हैं। अधिकारभावना एक समस्या बन सकती है। आप भौतिक उपहारों और स्नेह से प्रेम व्यक्त करते हैं।',
      sa: 'प्रेम्णि गहनसमर्पितः भावुकश्च। स्थायिनीं स्थिरां साझेदारीं भवान् इच्छति।',
    },
    finances: {
      en: 'Natural wealth accumulator. Patient investments in real estate, gold, and blue-chip stocks yield excellent returns. You rarely face poverty but must guard against hoarding. Financial security is paramount — you may sacrifice experiences for savings. Wealth grows steadily throughout life with major gains after 40.',
      hi: 'स्वाभाविक धन संचयकर्ता। भूसम्पत्ति, स्वर्ण और सुरक्षित निवेश में धैर्यपूर्ण निवेश उत्कृष्ट प्रतिफल देता है। आर्थिक सुरक्षा सर्वोपरि है। 40 के बाद बड़ा आर्थिक लाभ सम्भव है।',
      sa: 'स्वाभाविकः धनसञ्चयकर्ता। भूसम्पत्तौ स्वर्णे सुरक्षितनिवेशे च धैर्यपूर्णनिवेशः उत्कृष्टं प्रतिफलं ददाति।',
    },
    spiritual: {
      en: 'Your spiritual path is through devotion (Bhakti Yoga) and appreciation of divine beauty in nature. Venus-oriented practices — music, art, temple worship — bring deep peace. Lakshmi, Krishna, and nature deities resonate. Your groundedness is an asset in meditation.',
      hi: 'आपका आध्यात्मिक मार्ग भक्तियोग और प्रकृति में दिव्य सौन्दर्य की अनुभूति है। संगीत, कला, मन्दिर पूजा गहरी शान्ति लाते हैं। लक्ष्मी, कृष्ण और प्रकृति देवता अनुकूल हैं।',
      sa: 'भक्तियोगः भवतः आध्यात्मिकमार्गः। सङ्गीतं कला मन्दिरपूजा च गहनां शान्तिं आनयन्ति। लक्ष्मीः कृष्णश्च भवते अनुकूलौ।',
    },
  },
  3: {
    personality: {
      en: 'Quick-witted, communicative, and intellectually curious. You thrive on variety and mental stimulation. Your dual nature sees multiple perspectives simultaneously, making you adaptable but sometimes scattered. You collect information voraciously and communicate ideas brilliantly. Restlessness and difficulty committing to one path are key challenges.',
      hi: 'तीक्ष्ण बुद्धि, संवादशील और बौद्धिक रूप से जिज्ञासु। आप विविधता और मानसिक उत्तेजना पर पनपते हैं। आपकी द्वि-प्रकृति एक साथ कई दृष्टिकोण देखती है। आप विचारों को शानदार ढंग से संप्रेषित करते हैं। चंचलता और एक पथ पर टिकना चुनौती है।',
      sa: 'तीक्ष्णबुद्धिः संवादशीलः बौद्धिकजिज्ञासुश्च। विविधतायां मानसिकोत्तेजनायां च भवान् वर्धते। द्विप्रकृतिः बहुदृष्टिकोणान् एकदा पश्यति।',
    },
    career: {
      en: 'Writing, journalism, teaching, trading, technology, marketing, and communication fields suit you perfectly. Multi-tasking environments energize you. You may change careers multiple times. Media, publishing, and digital technology are especially favorable. Two simultaneous income sources are common.',
      hi: 'लेखन, पत्रकारिता, शिक्षण, व्यापार, प्रौद्योगिकी, विपणन और संचार क्षेत्र उपयुक्त हैं। बहुकार्य वातावरण आपको ऊर्जा देता है। कैरियर कई बार बदल सकता है। मीडिया और डिजिटल प्रौद्योगिकी विशेष अनुकूल।',
      sa: 'लेखनं पत्रकारिता शिक्षणं वाणिज्यं प्रौद्योगिकी च भवते उपयुक्तानि। बहुकार्यवातावरणं भवन्तम् ऊर्जयति।',
    },
    health: { en: 'Nervous system, lungs, arms, and shoulders need attention. Anxiety and overthinking can cause nervous exhaustion. Breathing exercises (Pranayama) are essential. You benefit from mental relaxation techniques. Avoid information overload.', hi: 'तन्त्रिका तन्त्र, फेफड़े, भुजाएँ ध्यान माँगते हैं। चिन्ता और अत्यधिक सोच तन्त्रिका थकान का कारण बन सकती है। प्राणायाम आवश्यक है।', sa: 'तन्त्रिकातन्त्रं फुप्फुसौ भुजे च ध्यानम् अपेक्षन्ते। प्राणायामः अत्यावश्यकः।' },
    relationships: { en: 'You need intellectual stimulation in relationships. Boredom is the biggest threat to your partnerships. Communication is your love language. You may have multiple significant relationships before settling. Need a partner who enjoys conversation and can keep up with your curiosity.', hi: 'सम्बन्धों में बौद्धिक उत्तेजना आवश्यक। ऊब आपकी साझेदारी का सबसे बड़ा खतरा है। संवाद आपकी प्रेम भाषा है।', sa: 'सम्बन्धेषु बौद्धिकोत्तेजना आवश्यकी। संवादः भवतः प्रेमभाषा।' },
    finances: { en: 'Multiple income streams through intellectual work. You are clever with money but may lack persistence in wealth building. Trading and quick-turnaround investments suit you. Financial fluctuations are common — diversification is key.', hi: 'बौद्धिक कार्य से विविध आय स्रोत। धन निर्माण में दृढ़ता की कमी हो सकती है। व्यापार और त्वरित निवेश अनुकूल।', sa: 'बौद्धिककार्यात् विविधाः आयस्रोतसः। वाणिज्यं त्वरितनिवेशश्च अनुकूलौ।' },
    spiritual: { en: 'Jnana Yoga — the path of knowledge — suits you best. Study of scriptures, philosophical debate, and intellectual spirituality appeal to you. Saraswati and Vishnu worship bring clarity. Mantra recitation calms your restless mind.', hi: 'ज्ञानयोग आपका सर्वोत्तम मार्ग। शास्त्र अध्ययन, दार्शनिक चर्चा। सरस्वती और विष्णु पूजा स्पष्टता लाती है। मन्त्र जप मन को शान्त करता है।', sa: 'ज्ञानयोगः भवतः श्रेष्ठमार्गः। शास्त्राध्ययनं दार्शनिकचर्चा च। सरस्वतीविष्णुपूजा स्पष्टतां आनयति।' },
  },
  4: {
    personality: {
      en: 'Deeply intuitive, nurturing, and emotionally intelligent. You have a strong connection to home, family, and roots. Your protective instincts make you a natural caregiver. Emotional security is your primary need. You experience life through feelings rather than logic. Moodiness and excessive attachment are challenges to overcome.',
      hi: 'गहन अन्तर्ज्ञान, पोषणकारी और भावनात्मक रूप से बुद्धिमान। घर, परिवार और जड़ों से गहरा सम्बन्ध। रक्षात्मक प्रवृत्ति आपको स्वाभाविक देखभालकर्ता बनाती है। भावनात्मक सुरक्षा आपकी प्राथमिक आवश्यकता है।',
      sa: 'गहनान्तर्ज्ञानी पोषकः भावनात्मकबुद्धिमान् च। गृहे कुटुम्बे मूलेषु च गहनः सम्बन्धः। भावनात्मिकी सुरक्षा भवतः प्राथमिकावश्यकता।',
    },
    career: { en: 'Healthcare, hospitality, real estate, counseling, food services, nursing, social work, and interior decoration. You thrive in caregiving roles. Working from home or running a home-based business is highly favorable. Emotional intelligence makes you an excellent manager of people.', hi: 'स्वास्थ्य सेवा, आतिथ्य, भूसम्पत्ति, परामर्श, खाद्य सेवाएँ। देखभाल भूमिकाओं में उत्कृष्ट। गृह-आधारित व्यवसाय अत्यन्त अनुकूल।', sa: 'स्वास्थ्यसेवा आतिथ्यं भूसम्पत्तिः परामर्शः — एतेषु भवान् उत्कृष्टः।' },
    health: { en: 'Digestive system, breasts, and chest area need attention. Emotional stress directly impacts physical health — psychosomatic ailments are common. Water retention and weight fluctuation. Nurturing yourself is as important as nurturing others. Emotional healing directly improves physical well-being.', hi: 'पाचन तन्त्र और छाती पर ध्यान दें। भावनात्मक तनाव शारीरिक स्वास्थ्य को सीधे प्रभावित करता है। जल प्रतिधारण और वजन उतार-चढ़ाव।', sa: 'पाचनतन्त्रं वक्षश्च ध्यानम् अपेक्षते। भावनात्मकतनावः शारीरिकस्वास्थ्यं साक्षात् प्रभावयति।' },
    relationships: { en: 'Deeply devoted partner who expresses love through nurturing. Family approval matters greatly. You create a warm, secure home environment. Over-mothering partners or emotional manipulation are pitfalls. Need a partner who provides emotional security and appreciates domesticity.', hi: 'गहन समर्पित साथी जो पोषण से प्रेम व्यक्त करता है। परिवार की स्वीकृति बहुत महत्वपूर्ण। भावनात्मक सुरक्षा प्रदान करने वाले साथी की आवश्यकता।', sa: 'गहनसमर्पितः साथी पोषणेन प्रेम प्रकटयति। कुटुम्बस्य अनुमोदनं महत्त्वपूर्णम्।' },
    finances: { en: 'Property, real estate, and food-related businesses build your wealth. Financial security is emotionally essential. You save well but may overspend on home and family. Inherited property is likely. Financial stability comes through stable employment rather than speculation.', hi: 'सम्पत्ति, भूसम्पत्ति और खाद्य व्यवसाय से धन निर्माण। आर्थिक सुरक्षा भावनात्मक रूप से आवश्यक। विरासत में सम्पत्ति सम्भव।', sa: 'सम्पत्त्या भूसम्पत्त्या खाद्यव्यवसायेन च धनसञ्चयः। आर्थिकसुरक्षा भावनात्मिकावश्यकता।' },
    spiritual: { en: 'Bhakti Yoga through devotion to the Divine Mother. Moon-oriented practices — fasting on Mondays, Moon meditation, and water rituals. Parvati, Durga, and Chandra worship bring emotional peace. Your intuition is a spiritual gift — trust it.', hi: 'दिव्य माता की भक्ति से भक्तियोग। सोमवार व्रत, चन्द्र ध्यान और जल अनुष्ठान। पार्वती, दुर्गा और चन्द्र पूजा भावनात्मक शान्ति लाते हैं।', sa: 'दिव्यमातुः भक्त्या भक्तियोगः। सोमवारव्रतं चन्द्रध्यानं जलानुष्ठानं च। पार्वतीदुर्गाचन्द्रपूजा भावनात्मिकीं शान्तिम् आनयति।' },
  },
  5: {
    personality: {
      en: 'Regal, confident, and generous. You have a natural magnetism that draws others to you. Your warmth and creativity inspire those around you. Pride and ego are your shadows. You need recognition and appreciation to thrive. Your presence commands attention in any room.',
      hi: 'राजसी, आत्मविश्वासी और उदार। स्वाभाविक आकर्षण जो दूसरों को आपकी ओर खींचता है। उष्णता और रचनात्मकता दूसरों को प्रेरित करती है। अहंकार आपकी छाया है। मान्यता और प्रशंसा आपकी आवश्यकता है।',
      sa: 'राजसी आत्मविश्वासी उदारश्च। स्वाभाविकम् आकर्षणं यत् अन्यान् भवतः समीपम् आकर्षयति। अहङ्कारः भवतः छाया।',
    },
    career: { en: 'Leadership, entertainment, politics, education, performing arts, luxury brands, and management. You must be in charge or center stage. Government positions and creative direction are strongly favored. Your charisma makes you a natural leader.', hi: 'नेतृत्व, मनोरंजन, राजनीति, शिक्षा, प्रदर्शन कला। आपको प्रभारी या केन्द्र में होना चाहिए। सरकारी पद और रचनात्मक निर्देशन अनुकूल।', sa: 'नेतृत्वं मनोरञ्जनं राजनीतिः शिक्षा च। भवता प्रभारिणा भवितव्यम्।' },
    health: { en: 'Heart, spine, and upper back need attention. Stress from excessive responsibility affects heart health. Vigorous exercise and joyful physical activity are essential. You heal faster when your spirit is uplifted. Avoid carrying the world on your shoulders.', hi: 'हृदय, रीढ़ और ऊपरी पीठ पर ध्यान दें। अत्यधिक जिम्मेदारी से तनाव हृदय स्वास्थ्य प्रभावित करता है। प्रसन्नतापूर्ण शारीरिक गतिविधि आवश्यक।', sa: 'हृदयं मेरुदण्डश्च ध्यानम् अपेक्षते। अत्यधिकोत्तरदायित्वात् तनावः हृदयस्वास्थ्यं प्रभावयति।' },
    relationships: { en: 'Romantic, generous, and dramatic in love. You shower partners with attention and gifts. Need admiration and loyalty. Can be dominating. Your ideal partner appreciates grand gestures and gives you the spotlight while being equally strong.', hi: 'प्रेम में रोमांटिक, उदार और नाटकीय। साथी पर ध्यान और उपहार बरसाते हैं। प्रशंसा और निष्ठा की आवश्यकता। आदर्श साथी भव्य भावों की सराहना करे।', sa: 'प्रेम्णि रोमाञ्चकः उदारः नाटकीयश्च। प्रशंसा निष्ठा च आवश्यके।' },
    finances: { en: 'You earn well and spend generously. Luxury spending can exceed earnings. Investments in entertainment, gold, and creative ventures prosper. You attract wealth through personality and connections. Speculative gains are possible but avoid gambling.', hi: 'अच्छी कमाई और उदारतापूर्वक खर्च। विलासिता पर खर्च आय से अधिक हो सकता है। मनोरंजन, स्वर्ण और रचनात्मक उद्यमों में निवेश सफल।', sa: 'सम्यक् अर्जनं उदारव्ययनं च। मनोरञ्जने स्वर्णे रचनात्मकोद्यमेषु च निवेशः सफलः।' },
    spiritual: { en: 'Raja Yoga — the royal path of self-mastery. Sun worship (Surya Namaskar, Gayatri Mantra) is most beneficial. Vishnu and Shiva as supreme lords resonate. Your spiritual growth comes through leading others toward light.', hi: 'राजयोग — आत्मनिपुणता का राजमार्ग। सूर्य पूजा (सूर्य नमस्कार, गायत्री मन्त्र) सर्वाधिक लाभदायक। विष्णु और शिव अनुकूल।', sa: 'राजयोगः — आत्मनिपुणतायाः राजमार्गः। सूर्यपूजा गायत्रीमन्त्रश्च सर्वाधिकं हितकरौ।' },
  },
  6: {
    personality: {
      en: 'Analytical, detail-oriented, and service-minded. You have a keen eye for improvement and a practical approach to solving problems. Perfectionism is both your strength and challenge. You notice flaws others miss and feel compelled to fix them. Self-criticism can become excessive if not managed.',
      hi: 'विश्लेषणात्मक, विस्तार-उन्मुख और सेवा-भावी। सुधार के लिए तीक्ष्ण दृष्टि और समस्या समाधान का व्यावहारिक दृष्टिकोण। पूर्णतावाद आपकी शक्ति और चुनौती दोनों है। आत्मालोचना अत्यधिक हो सकती है।',
      sa: 'विश्लेषणात्मकः विस्तारोन्मुखः सेवाभावी च। सुधाराय तीक्ष्णा दृष्टिः। पूर्णतावादः बलं चुनौती च।',
    },
    career: { en: 'Healthcare, analytics, accounting, research, quality control, editing, veterinary science, nutrition, and precision work. You excel in service-oriented roles. Detail work that others find tedious energizes you. Administrative and organizational positions suit you well.', hi: 'स्वास्थ्य, विश्लेषण, लेखा, शोध, गुणवत्ता नियन्त्रण, सम्पादन। सेवा-उन्मुख भूमिकाओं में उत्कृष्ट। प्रशासनिक और संगठनात्मक पद अनुकूल।', sa: 'स्वास्थ्यं विश्लेषणं लेखा शोधश्च। सेवोन्मुखभूमिकासु उत्कृष्टः।' },
    health: { en: 'Digestive system and intestines are vulnerable. Nervous tension manifests as stomach issues. Hypochondria is common — you may worry about health excessively. Clean eating, regular routines, and stress management are essential. You respond well to Ayurvedic and naturopathic approaches.', hi: 'पाचन तन्त्र और आँतें संवेदनशील। तन्त्रिका तनाव पेट की समस्याओं के रूप में प्रकट होता है। स्वच्छ आहार और नियमित दिनचर्या आवश्यक।', sa: 'पाचनतन्त्रम् आन्त्राणि च संवेदनशीलानि। स्वच्छाहारः नियमितदिनचर्या च आवश्यकौ।' },
    relationships: { en: 'Devoted but critical in relationships. You show love through acts of service. Can be overly analytical about partners. Need someone who appreciates your attention to detail without feeling constantly judged.', hi: 'सम्बन्धों में समर्पित परन्तु आलोचनात्मक। सेवाकर्मों से प्रेम प्रदर्शित करते हैं। ऐसे साथी की आवश्यकता जो विस्तार पर ध्यान की सराहना करे।', sa: 'सम्बन्धेषु समर्पितः परन्तु आलोचनात्मकः। सेवाकर्मभिः प्रेम प्रदर्शयति।' },
    finances: { en: 'Careful with money and excellent at budgeting. You build wealth through disciplined saving. Service-based income is stable. Avoid analysis paralysis in investments. Mutual funds and systematic investments suit your methodical nature.', hi: 'धन के साथ सावधान और बजट में उत्कृष्ट। अनुशासित बचत से धन निर्माण। व्यवस्थित निवेश आपकी प्रकृति के अनुकूल।', sa: 'धनेन सावधानः बजटे उत्कृष्टश्च। अनुशासितसञ्चयेन धनसञ्चयः।' },
    spiritual: { en: 'Seva (selfless service) is your highest spiritual practice. Karma Yoga through dedicated work. Dhanvantari, Vishnu, and healing deities resonate. Your analytical mind benefits from structured meditation practices like Vipassana.', hi: 'सेवा (निःस्वार्थ सेवा) आपकी सर्वोच्च आध्यात्मिक साधना। समर्पित कार्य से कर्मयोग। धन्वन्तरि और विष्णु अनुकूल। विपश्यना जैसी संरचित ध्यान पद्धतियाँ लाभदायक।', sa: 'सेवा भवतः सर्वोच्चा आध्यात्मिकसाधना। समर्पितकार्येण कर्मयोगः। धन्वन्तरिविष्णू अनुकूलौ।' },
  },
  7: {
    personality: {
      en: 'Diplomatic, aesthetic, and partnership-oriented. You seek balance and harmony in all things. Your social grace and fair-mindedness make you an excellent mediator. Indecisiveness is your greatest challenge — you weigh every option exhaustively. You see beauty where others don\'t and have refined tastes.',
      hi: 'कूटनीतिक, सौन्दर्यप्रिय और साझेदारी-उन्मुख। सन्तुलन और सामंजस्य की खोज। सामाजिक शिष्टाचार और निष्पक्षता आपको उत्कृष्ट मध्यस्थ बनाती है। अनिर्णय आपकी सबसे बड़ी चुनौती है।',
      sa: 'कूटनीतिकः सौन्दर्यप्रियः साझेदारीउन्मुखश्च। सन्तुलनस्य सामञ्जस्यस्य च अन्वेषणम्। अनिर्णयः भवतः महत्तमा चुनौती।',
    },
    career: { en: 'Law, diplomacy, design, fashion, art, counseling, public relations, and partnership ventures. You excel in roles requiring negotiation and aesthetic judgment. Fair-minded leadership in team environments. Judiciary and arbitration are strongly favored.', hi: 'कानून, कूटनीति, डिज़ाइन, फ़ैशन, कला, परामर्श। बातचीत और सौन्दर्य निर्णय वाली भूमिकाओं में उत्कृष्ट। न्यायपालिका और मध्यस्थता अनुकूल।', sa: 'विधिः कूटनीतिः रूपसज्जा कला परामर्शश्च। वार्तासु सौन्दर्यनिर्णये च उत्कृष्टः।' },
    health: { en: 'Kidneys, lower back, and skin need attention. Sugar imbalances and kidney issues. Emotional imbalance directly affects physical well-being. Maintaining harmony in relationships is literally medicine for you. Yoga and balanced routines essential.', hi: 'गुर्दे, कमर और त्वचा पर ध्यान दें। शर्करा असन्तुलन और गुर्दा समस्याएँ। भावनात्मक सन्तुलन शारीरिक स्वास्थ्य को प्रभावित करता है। योग और सन्तुलित दिनचर्या आवश्यक।', sa: 'वृक्कौ कटिः त्वक् च ध्यानम् अपेक्षन्ते। भावनात्मिकसन्तुलनं शारीरिकस्वास्थ्यं प्रभावयति।' },
    relationships: { en: 'Partnership is your primary focus in life. You feel incomplete alone and seek your "other half." Compromise comes naturally. You may sacrifice your own needs to maintain harmony. Need a partner who values equality and shares decision-making.', hi: 'साझेदारी जीवन का प्राथमिक केन्द्र। अकेले अपूर्ण अनुभव करते हैं। समझौता स्वाभाविक रूप से आता है। सामंजस्य बनाए रखने के लिए अपनी आवश्यकताओं का त्याग कर सकते हैं।', sa: 'साझेदारी जीवनस्य प्राथमिककेन्द्रम्। एकाकी अपूर्णम् अनुभवति। समाधानं स्वाभाविकम्।' },
    finances: { en: 'Partnerships and joint ventures build wealth. You spend on beauty, aesthetics, and social life. Financial decisions benefit from a partner\'s input. Legal and artistic ventures are profitable. Avoid financial dependency on partners.', hi: 'साझेदारी और संयुक्त उद्यम से धन निर्माण। सौन्दर्य और सामाजिक जीवन पर खर्च। कानूनी और कलात्मक उद्यम लाभदायक।', sa: 'साझेदारीसंयुक्तोद्यमाभ्यां धनसञ्चयः। विधिकलात्मकोद्यमौ लाभदायकौ।' },
    spiritual: { en: 'Your spiritual path involves relationships as teachers. Bhakti through partnership and service to others. Venus worship and devotional music bring peace. Radha-Krishna devotion is naturally aligned with your nature.', hi: 'सम्बन्ध शिक्षक के रूप में आपका आध्यात्मिक मार्ग। साझेदारी और सेवा से भक्ति। शुक्र पूजा और भक्ति संगीत शान्ति लाते हैं। राधा-कृष्ण भक्ति अनुकूल।', sa: 'सम्बन्धाः शिक्षकरूपेण भवतः आध्यात्मिकमार्गः। राधाकृष्णभक्तिः स्वाभाविकतया अनुकूला।' },
  },
  8: {
    personality: {
      en: 'Intense, perceptive, and transformative. You possess remarkable depth and determination. Your ability to see beneath surfaces gives you powerful insight into human nature. You are drawn to life\'s mysteries and hidden truths. Trust is hard-won but absolute. Obsessiveness and desire for control are shadows to overcome.',
      hi: 'तीव्र, सूक्ष्मदर्शी और परिवर्तनकारी। उल्लेखनीय गहराई और दृढ़ संकल्प। सतह के नीचे देखने की क्षमता मानव स्वभाव में शक्तिशाली अन्तर्दृष्टि देती है। जीवन के रहस्यों और छिपे सत्यों की ओर आकर्षण। विश्वास कठिनाई से मिलता है पर पूर्ण होता है।',
      sa: 'तीव्रः सूक्ष्मदर्शी परिवर्तनकारी च। उल्लेखनीया गहनता दृढसङ्कल्पश्च। जीवनरहस्यानां गूढसत्यानां च प्रति आकर्षणम्।',
    },
    career: { en: 'Research, psychology, surgery, detective work, occult sciences, insurance, crisis management, and investigative journalism. You excel in uncovering hidden information. Transformative roles — rehabilitation, therapy, forensics — are ideal. Power positions in large organizations suit you.', hi: 'शोध, मनोविज्ञान, शल्यचिकित्सा, गुप्तचर कार्य, गूढ़ विज्ञान। छिपी जानकारी उजागर करने में उत्कृष्ट। परिवर्तनकारी भूमिकाएँ आदर्श। बड़े संगठनों में शक्ति पद अनुकूल।', sa: 'शोधः मनोविज्ञानं शल्यचिकित्सा गूढविज्ञानं च। गूढसूचनोद्घाटने उत्कृष्टः।' },
    health: { en: 'Reproductive system, elimination organs, and chronic conditions need monitoring. Psychological health is crucial — repressed emotions manifest as physical illness. Regular detoxification (physical and emotional) is essential. You have remarkable recuperative powers once you commit to healing.', hi: 'प्रजनन तन्त्र और जीर्ण रोगों पर ध्यान। मनोवैज्ञानिक स्वास्थ्य महत्वपूर्ण — दबी भावनाएँ शारीरिक रोग बनती हैं। नियमित विषहरण आवश्यक।', sa: 'प्रजननतन्त्रं जीर्णरोगाश्च ध्यानम् अपेक्षन्ते। मानसिकस्वास्थ्यं महत्त्वपूर्णम्।' },
    relationships: { en: 'All or nothing in love. Deep emotional bonds with intense loyalty. Jealousy and possessiveness are significant challenges. Betrayal is never forgiven. Transformative relationships that change both partners. Need complete honesty and depth from a partner.', hi: 'प्रेम में सब या कुछ नहीं। तीव्र निष्ठा के साथ गहरे भावनात्मक बन्धन। ईर्ष्या और अधिकारभावना महत्वपूर्ण चुनौतियाँ।', sa: 'प्रेम्णि सर्वं वा शून्यं वा। तीव्रनिष्ठासहिताः गहनभावनात्मिकबन्धनाः।' },
    finances: { en: 'Wealth through inheritance, insurance, joint finances, and investments in crisis sectors. You have an instinct for financial power plays. Real estate and undervalued assets are your forte. Major financial transformations — both gains and losses — are part of your journey.', hi: 'विरासत, बीमा, संयुक्त वित्त से धन। आर्थिक शक्ति खेल की प्रवृत्ति। भूसम्पत्ति और अवमूल्यित सम्पत्तियाँ आपका विशेष क्षेत्र।', sa: 'उत्तराधिकारेण बीमेन संयुक्तवित्तेन च धनम्। भूसम्पत्तिः अवमूल्यितसम्पत्तयश्च भवतः विशेषक्षेत्रम्।' },
    spiritual: { en: 'Tantra, deep meditation, and transformative spiritual practices. Shiva worship, Kundalini Yoga, and practices that transmute lower energies into higher awareness. You have natural occult abilities. Spiritual transformation through facing your deepest fears.', hi: 'तन्त्र, गहन ध्यान और परिवर्तनकारी आध्यात्मिक साधनाएँ। शिव पूजा, कुण्डलिनी योग। निम्न ऊर्जाओं को उच्चतर चेतना में रूपान्तरित करने वाली साधनाएँ।', sa: 'तन्त्रं गहनध्यानं परिवर्तनकारीसाधनाश्च। शिवपूजा कुण्डलिनीयोगश्च। अधमर्जाओं उच्चतरचैतन्ये परिवर्तनम्।' },
  },
  9: {
    personality: {
      en: 'Optimistic, philosophical, and adventurous. You are a natural teacher and explorer, always seeking higher meaning. Your enthusiasm is contagious and your vision expansive. You see the big picture but may miss details. Over-promising and tactless honesty are your shadows.',
      hi: 'आशावादी, दार्शनिक और साहसिक। स्वाभाविक शिक्षक और अन्वेषक। सदैव उच्चतर अर्थ की खोज। उत्साह संक्रामक और दृष्टि विस्तृत। बड़ी तस्वीर देखते हैं पर विवरण चूक सकते हैं।',
      sa: 'आशावादी दार्शनिकः साहसिकश्च। स्वाभाविकः शिक्षकः अन्वेषकश्च। उच्चतरार्थस्य सदा अन्वेषणम्।',
    },
    career: { en: 'Education, law, publishing, travel, philosophy, religion, international business, and higher learning. You need freedom and expansion in your career. Teaching, preaching, and guiding others brings fulfillment. Long-distance commerce and foreign dealings are profitable.', hi: 'शिक्षा, कानून, प्रकाशन, यात्रा, दर्शन, धर्म, अन्तरराष्ट्रीय व्यापार। कैरियर में स्वतन्त्रता और विस्तार आवश्यक। शिक्षण और मार्गदर्शन सन्तुष्टि देता है।', sa: 'शिक्षा विधिः प्रकाशनं यात्रा दर्शनं धर्मश्च। जीविकायां स्वातन्त्र्यविस्तारौ आवश्यकौ।' },
    health: { en: 'Hips, thighs, liver, and sciatic nerve need attention. Excess in food, drink, and indulgence affects liver health. Active outdoor life is medicine — trekking, horse riding, sports. Your optimism aids recovery but you may ignore symptoms.', hi: 'कूल्हे, जाँघें, यकृत पर ध्यान दें। भोजन और पेय में अत्यधिकता यकृत को प्रभावित करती है। सक्रिय बाह्य जीवन औषधि है।', sa: 'कटिः ऊरू यकृत् च ध्यानम् अपेक्षन्ते। भोजनपाने अतिरेकः यकृतं प्रभावयति।' },
    relationships: { en: 'Freedom-loving in relationships. Need a partner who is equally adventurous and intellectually stimulating. Long-distance relationships are possible. Marriage may happen late or with someone from a different culture. Fidelity requires conscious effort.', hi: 'सम्बन्धों में स्वतन्त्रता-प्रेमी। समान रूप से साहसिक और बौद्धिक साथी की आवश्यकता। विवाह देर से या भिन्न संस्कृति से सम्भव।', sa: 'सम्बन्धेषु स्वातन्त्र्यप्रेमी। समानसाहसिकबौद्धिकसाथिनः आवश्यकता। विवाहः विलम्बेन वा भिन्नसंस्कृतेः सम्भवः।' },
    finances: { en: 'Wealth through education, law, publishing, and international ventures. Generous to a fault — you may give away more than you should. Lucky in speculation and long-term investments. Financial wisdom comes through travel and cross-cultural experiences.', hi: 'शिक्षा, कानून, प्रकाशन और अन्तरराष्ट्रीय उद्यमों से धन। अत्यधिक उदार — आवश्यकता से अधिक दे सकते हैं। सट्टे और दीर्घकालिक निवेश में भाग्यशाली।', sa: 'शिक्षया विधिना प्रकाशनेन अन्तरराष्ट्रियोद्यमैश्च धनम्। अत्यन्तम् उदारः।' },
    spiritual: { en: 'Natural spiritual seeker. Pilgrimage, scriptural study, and philosophical exploration. Jupiter worship and Guru devotion bring rapid spiritual growth. Vedanta, Buddhism, and universal spirituality attract you. You may become a spiritual teacher.', hi: 'स्वाभाविक आध्यात्मिक साधक। तीर्थयात्रा, शास्त्र अध्ययन और दार्शनिक अन्वेषण। बृहस्पति पूजा और गुरु भक्ति तीव्र आध्यात्मिक विकास लाते हैं।', sa: 'स्वाभाविकः आध्यात्मिकसाधकः। तीर्थयात्रा शास्त्राध्ययनं दार्शनिकान्वेषणं च। बृहस्पतिपूजा गुरुभक्तिश्च तीव्रम् आध्यात्मिकविकासम् आनयतः।' },
  },
  10: {
    personality: {
      en: 'Disciplined, ambitious, and responsible. You approach life with maturity and strategic thinking. Your patience and persistence lead to lasting achievements. Coldness and emotional suppression are your shadows. You age in reverse — becoming warmer and more relaxed with time.',
      hi: 'अनुशासित, महत्वाकांक्षी और जिम्मेदार। परिपक्वता और रणनीतिक सोच के साथ जीवन का दृष्टिकोण। धैर्य और दृढ़ता स्थायी उपलब्धियों की ओर ले जाते हैं। शीतलता और भावनात्मक दमन चुनौती है। समय के साथ अधिक उष्ण होते जाते हैं।',
      sa: 'अनुशासितः महत्त्वाकाङ्क्षी उत्तरदायी च। परिपक्वतया रणनीतिकचिन्तनेन च जीवनदृष्टिकोणः। धैर्यं दृढता च स्थायिसिद्धिं प्रति नयतः।',
    },
    career: { en: 'Government, management, construction, engineering, mining, and corporate leadership. You climb hierarchies patiently. Success comes after sustained effort. You excel in structured, traditional institutions. CEO material — you understand power and responsibility.', hi: 'सरकार, प्रबन्धन, निर्माण, अभियान्त्रिकी, कॉर्पोरेट नेतृत्व। पदानुक्रम में धैर्यपूर्वक चढ़ते हैं। निरन्तर प्रयास के बाद सफलता।', sa: 'शासनं प्रबन्धनं निर्माणं अभियान्त्रिकी च। पदानुक्रमे धैर्येण आरोहति। निरन्तरप्रयासात् सफलता।' },
    health: { en: 'Bones, joints (especially knees), teeth, and skin need attention. Arthritis and structural issues. Slow metabolism. Discipline in health routines pays off long-term. You actually get healthier with age. Cold-related ailments need prevention.', hi: 'हड्डियाँ, जोड़ (विशेषकर घुटने), दाँत और त्वचा पर ध्यान। गठिया और संरचनात्मक समस्याएँ। स्वास्थ्य दिनचर्या में अनुशासन दीर्घकालिक लाभ देता है। उम्र के साथ स्वास्थ्य सुधरता है।', sa: 'अस्थीनि सन्धयः दन्ताः त्वक् च ध्यानम् अपेक्षन्ते। वयसा सह स्वास्थ्यं सुधरति।' },
    relationships: { en: 'Cautious and reserved in love initially. You warm up slowly but form deep, lasting bonds. May marry late or for practical reasons. Emotional expression needs development. Your ideal partner understands your ambition and gives you space to achieve.', hi: 'प्रेम में प्रारम्भ में सतर्क और संयमित। धीरे-धीरे गहरे, स्थायी बन्धन बनाते हैं। विवाह देर से या व्यावहारिक कारणों से।', sa: 'प्रेम्णि प्रारम्भे सतर्कः संयमितश्च। शनैः शनैः गहनान् स्थायिबन्धनान् रचयति।' },
    finances: { en: 'Patient wealth builder. Real estate, government bonds, and long-term investments bring substantial returns. Frugal by nature but generous with family. Financial independence is achieved through decades of discipline. Major prosperity after 40-45.', hi: 'धैर्यवान धन निर्माता। भूसम्पत्ति, सरकारी बॉन्ड और दीर्घकालिक निवेश। स्वभाव से मितव्ययी। 40-45 के बाद प्रमुख समृद्धि।', sa: 'धैर्यवान् धननिर्माता। भूसम्पत्तिः शासकीयबन्धपत्राणि दीर्घकालिकनिवेशश्च। चत्वारिंशद्वर्षात् परं प्रमुखा समृद्धिः।' },
    spiritual: { en: 'Disciplined spiritual practice — consistent meditation, austerity, and traditional rituals. Shani (Saturn) worship and Hanuman devotion remove obstacles. Spiritual maturity comes later in life. Your path is through duty and righteous living.', hi: 'अनुशासित आध्यात्मिक साधना — निरन्तर ध्यान, तपस्या। शनि पूजा और हनुमान भक्ति बाधाएँ दूर करते हैं। जीवन में बाद में आध्यात्मिक परिपक्वता।', sa: 'अनुशासिता आध्यात्मिकसाधना। शनिपूजा हनुमद्भक्तिश्च बाधाः दूरीकुरुतः। कर्तव्येन धार्मिकजीवनेन च मार्गः।' },
  },
  11: {
    personality: {
      en: 'Innovative, humanitarian, and intellectually independent. You think ahead of your time and are drawn to social reform. Your unique perspective challenges convention. Emotional detachment and eccentricity can alienate you from others. You value friendship over romance.',
      hi: 'नवीन, मानवतावादी और बौद्धिक रूप से स्वतन्त्र। अपने समय से आगे सोचते हैं और सामाजिक सुधार की ओर आकर्षित। अद्वितीय दृष्टिकोण परम्परा को चुनौती देता है। भावनात्मक अलगाव और विलक्षणता दूसरों से दूर कर सकती है।',
      sa: 'नवीनः मानवतावादी बौद्धिकस्वतन्त्रश्च। स्वकालात् पुरतः चिन्तयति। अद्वितीयदृष्टिकोणः परम्पराम् आक्षिपति।',
    },
    career: { en: 'Technology, science, social work, invention, networking, humanitarian organizations, and progressive fields. Innovation and disruption are your specialties. Large organizations, NGOs, and tech startups are ideal. You excel when working for a cause larger than yourself.', hi: 'प्रौद्योगिकी, विज्ञान, सामाजिक कार्य, आविष्कार, नेटवर्किंग। नवाचार और व्यवधान आपकी विशेषता। बड़े संगठन, NGO और टेक स्टार्टअप आदर्श।', sa: 'प्रौद्योगिकी विज्ञानं सामाजिककार्यम् आविष्कारश्च। नवाचारः व्यवधानश्च भवतः विशेषता।' },
    health: { en: 'Circulation, ankles, and nervous system need attention. Unusual or hard-to-diagnose conditions. Electric and magnetic therapies may help. Regular walking and ankle exercises prevent issues. Mental health requires conscious attention — you may suppress emotions.', hi: 'रक्त संचार, टखने और तन्त्रिका तन्त्र पर ध्यान। असामान्य या कठिन-निदान स्थितियाँ। नियमित पैदल चलना। मानसिक स्वास्थ्य पर सचेत ध्यान आवश्यक।', sa: 'रक्तसञ्चारः गुल्फौ तन्त्रिकातन्त्रं च ध्यानम् अपेक्षन्ते। मानसिकस्वास्थ्ये सचेतं ध्यानम् आवश्यकम्।' },
    relationships: { en: 'Values freedom highly in relationships. Unconventional partnerships and friendships that evolve into love. May be emotionally distant or unpredictable. Need a partner who respects your independence and shares your ideals.', hi: 'सम्बन्धों में स्वतन्त्रता को अत्यधिक महत्व। अपरम्परागत साझेदारी। भावनात्मक रूप से दूर या अप्रत्याशित हो सकते हैं। स्वतन्त्रता का सम्मान करने वाले साथी की आवश्यकता।', sa: 'सम्बन्धेषु स्वातन्त्र्यम् अत्यन्तं मन्यते। अपरम्परागताः साझेदार्यः। स्वातन्त्र्यसम्मानिनः साथिनः आवश्यकता।' },
    finances: { en: 'Income through technology, networking, and group ventures. Sudden gains and losses possible. Cryptocurrency and futuristic investments attract you. Financial independence matters more than wealth accumulation. Social enterprises can be profitable.', hi: 'प्रौद्योगिकी, नेटवर्किंग और समूह उद्यमों से आय। अचानक लाभ और हानि सम्भव। आर्थिक स्वतन्त्रता धन संचय से अधिक महत्वपूर्ण।', sa: 'प्रौद्योगिक्या नेटवर्किंगेन समूहोद्यमैश्च आयः। आर्थिकस्वातन्त्र्यं धनसञ्चयात् अधिकं महत्त्वपूर्णम्।' },
    spiritual: { en: 'Universal spirituality transcending organized religion. Meditation on consciousness and unity. Saturn-oriented practices ground your cosmic awareness. Group meditation and spiritual communities suit you. Humanitarian service is your highest form of worship.', hi: 'संगठित धर्म से परे सार्वभौमिक आध्यात्मिकता। चेतना और एकता पर ध्यान। शनि साधनाएँ ब्रह्माण्डीय जागरूकता को भूमि देती हैं। सामूहिक ध्यान और आध्यात्मिक समुदाय अनुकूल।', sa: 'सङ्गठितधर्मात् परा सार्वभौमिकी आध्यात्मिकता। चैतन्ये ऐक्ये च ध्यानम्। मानवसेवा भवतः उच्चतमा पूजा।' },
  },
  12: {
    personality: {
      en: 'Compassionate, imaginative, and spiritually attuned. You experience life through a lens of empathy and intuition. Your creative vision transcends the ordinary. Boundary issues and escapist tendencies are challenges. You absorb others\' emotions like a sponge. Your inner world is rich beyond measure.',
      hi: 'करुणामय, कल्पनाशील और आध्यात्मिक रूप से जुड़े। सहानुभूति और अन्तर्ज्ञान के माध्यम से जीवन का अनुभव। रचनात्मक दृष्टि सामान्य से परे। सीमा के मुद्दे और पलायनवादी प्रवृत्तियाँ चुनौतियाँ हैं। आन्तरिक संसार अत्यन्त समृद्ध।',
      sa: 'करुणामयः कल्पनाशीलः आध्यात्मिकसंयुक्तश्च। सहानुभूत्या अन्तर्ज्ञानेन च जीवनानुभवः। रचनात्मकदृष्टिः सामान्यात् परा।',
    },
    career: { en: 'Healing arts, music, cinema, spirituality, marine industries, charitable work, hospitals, prisons, and any field where imagination and compassion are valued. Behind-the-scenes roles suit you. Creative fields like filmmaking, music composition, and photography.', hi: 'उपचार कला, संगीत, सिनेमा, आध्यात्मिकता, समुद्री उद्योग, दान कार्य। पर्दे के पीछे की भूमिकाएँ अनुकूल। फिल्म निर्माण, संगीत रचना और फोटोग्राफी।', sa: 'उपचारकला सङ्गीतं चलचित्रम् आध्यात्मिकता दानकार्यं च। पर्दापश्चिमभूमिकाः अनुकूलाः।' },
    health: { en: 'Feet, immune system, and lymphatic system need attention. Susceptibility to infections and allergies. Substance sensitivity — avoid alcohol and drugs. Water therapy, swimming, and rest are essential medicines. Your health is deeply connected to spiritual well-being.', hi: 'पैर, प्रतिरक्षा तन्त्र पर ध्यान। संक्रमण और एलर्जी की संवेदनशीलता। मादक पदार्थों से बचें। जल चिकित्सा, तैराकी और विश्राम आवश्यक।', sa: 'पादौ प्रतिरक्षातन्त्रं च ध्यानम् अपेक्षते। सङ्क्रमणस्य एलर्जीयाश्च संवेदनशीलता। जलचिकित्सा तरणं विश्रामश्च आवश्यकाः।' },
    relationships: { en: 'Deeply romantic and idealistic in love. You may idealize partners and be disappointed by reality. Boundaries in relationships need conscious attention. Soul-mate connections are important to you. Need a partner who appreciates your sensitivity and shares your spiritual depth.', hi: 'प्रेम में गहन रोमांटिक और आदर्शवादी। साथी को आदर्श बना सकते हैं। सम्बन्धों में सीमाओं पर सचेत ध्यान आवश्यक। आत्मसंगी सम्बन्ध महत्वपूर्ण।', sa: 'प्रेम्णि गहनरोमाञ्चकः आदर्शवादी च। सम्बन्धेषु सीमासु सचेतं ध्यानम् आवश्यकम्।' },
    finances: { en: 'Money flows in and out mysteriously. You may struggle with practical financial management. Earnings through creative, spiritual, or healing work. Foreign income is likely. You must guard against fraud and deception in financial dealings. Trust your intuition about money.', hi: 'धन रहस्यमय ढंग से आता-जाता है। व्यावहारिक वित्तीय प्रबन्धन में कठिनाई। रचनात्मक, आध्यात्मिक कार्य से आय। विदेशी आय सम्भव। वित्तीय मामलों में धोखे से सावधान।', sa: 'धनं रहस्यमयरीत्या आगच्छति गच्छति च। रचनात्मकाध्यात्मिककार्यात् आयः। विदेशात् आयः सम्भवः।' },
    spiritual: { en: 'The most naturally spiritual sign. Meditation, devotion, and surrender come naturally. All spiritual paths resonate. Vishnu, Krishna, and the Divine Mother are natural. Moksha (liberation) is attainable — your soul has accumulated much spiritual merit from past lives.', hi: 'सबसे स्वाभाविक आध्यात्मिक राशि। ध्यान, भक्ति और समर्पण स्वाभाविक। सभी आध्यात्मिक मार्ग अनुकूल। मोक्ष प्राप्य — पूर्वजन्मों से बहुत आध्यात्मिक पुण्य संचित।', sa: 'सर्वाधिकस्वाभाविकः आध्यात्मिकराशिः। ध्यानं भक्तिः समर्पणं च स्वाभाविकम्। मोक्षः प्राप्यः — पूर्वजन्मभ्यः बहु आध्यात्मिकपुण्यं सञ्चितम्।' },
  },
};
