'use client';

import { useState } from 'react';
import { useLocale } from 'next-intl';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from '@/lib/i18n/navigation';
import { BookOpen, ChevronDown, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';
import type { Locale, LocaleText } from '@/types/panchang';
import { tl } from '@/lib/utils/trilingual';
import { isDevanagariLocale } from '@/lib/utils/locale-fonts';

// ─── Text Data ──────────────────────────────────────────────────────────────

interface ClassicalText {
  id: string;
  name: Record<string, string>;
  author: Record<string, string>;
  date: string;
  chapters: number;
  verses: string;
  category: 'siddhanta' | 'hora';
  color: string;
  border: string;
  summary: Record<string, string>;
  keyContributions: { topic: string; detail: Record<string, string>; status: 'still_used' | 'superseded' | 'partially_valid' }[];
  accuracyHighlights?: { value: string; given: string; modern: string; error: string }[];
  uniqueConcepts: LocaleText[];
}

const TEXTS: ClassicalText[] = [
  {
    id: 'surya_siddhanta', category: 'siddhanta', chapters: 14, verses: '~500',
    name: { en: 'Surya Siddhanta', hi: 'सूर्य सिद्धान्त', sa: 'सूर्यसिद्धान्तः' },
    author: { en: 'Attributed to Surya (Sun God) via Maya Asura', hi: 'सूर्य देव द्वारा मय असुर को प्रकट', sa: 'सूर्य देव द्वारा मय असुर को प्रकट', mai: 'सूर्य देव द्वारा मय असुर को प्रकट', mr: 'सूर्य देव द्वारा मय असुर को प्रकट', ta: 'Attributed to Surya (Sun God) via Maya Asura', te: 'Attributed to Surya (Sun God) via Maya Asura', bn: 'Attributed to Surya (Sun God) via Maya Asura', kn: 'Attributed to Surya (Sun God) via Maya Asura', gu: 'Attributed to Surya (Sun God) via Maya Asura' },
    date: '~400 CE (current recension)',
    color: 'text-amber-400', border: 'border-amber-500/20',
    summary: { en: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.', hi: 'भारत का आधारभूत खगोलशास्त्रीय ग्रंथ। ग्रह स्थिति, ग्रहण और काल विभाग की गणना प्रणाली परिभाषित करता है। इसका संयुग्मी मास मान 0.08 सेकंड तक सटीक।', sa: 'भारत का आधारभूत खगोलशास्त्रीय ग्रंथ। ग्रह स्थिति, ग्रहण और काल विभाग की गणना प्रणाली परिभाषित करता है। इसका संयुग्मी मास मान 0.08 सेकंड तक सटीक।', mai: 'भारत का आधारभूत खगोलशास्त्रीय ग्रंथ। ग्रह स्थिति, ग्रहण और काल विभाग की गणना प्रणाली परिभाषित करता है। इसका संयुग्मी मास मान 0.08 सेकंड तक सटीक।', mr: 'भारत का आधारभूत खगोलशास्त्रीय ग्रंथ। ग्रह स्थिति, ग्रहण और काल विभाग की गणना प्रणाली परिभाषित करता है। इसका संयुग्मी मास मान 0.08 सेकंड तक सटीक।', ta: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.', te: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.', bn: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.', kn: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.', gu: 'The foundational astronomical treatise of India. Defines the computational framework for planetary positions, eclipses, and time divisions that all Hindu calendars still follow. Its synodic month value (29.530588 days) is accurate to 0.08 seconds.' },
    keyContributions: [
      { topic: 'Synodic Month', detail: { en: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.', hi: '29.530588 दिन — आधुनिक मान से 0.08 सेकंड तक सटीक। सभी पंचांगों में तिथि गणना का आधार।', sa: '29.530588 दिन — आधुनिक मान से 0.08 सेकंड तक सटीक। सभी पंचांगों में तिथि गणना का आधार।', mai: '29.530588 दिन — आधुनिक मान से 0.08 सेकंड तक सटीक। सभी पंचांगों में तिथि गणना का आधार।', mr: '29.530588 दिन — आधुनिक मान से 0.08 सेकंड तक सटीक। सभी पंचांगों में तिथि गणना का आधार।', ta: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.', te: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.', bn: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.', kn: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.', gu: '29.530588 days — accurate to 0.08 seconds vs modern value. The basis of Tithi calculation in all panchangs.' }, status: 'still_used' },
      { topic: 'Sidereal Year', detail: { en: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.', hi: '365.258756 दिन — आधुनिक मान से ~3.4 मिनट का अंतर। पारंपरिक पंचांग में अभी भी प्रयुक्त।', sa: '365.258756 दिन — आधुनिक मान से ~3.4 मिनट का अंतर। पारंपरिक पंचांग में अभी भी प्रयुक्त।', mai: '365.258756 दिन — आधुनिक मान से ~3.4 मिनट का अंतर। पारंपरिक पंचांग में अभी भी प्रयुक्त।', mr: '365.258756 दिन — आधुनिक मान से ~3.4 मिनट का अंतर। पारंपरिक पंचांग में अभी भी प्रयुक्त।', ta: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.', te: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.', bn: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.', kn: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.', gu: '365.258756 days — off by ~3.4 minutes from modern value. Still used in traditional panchang compilation.' }, status: 'partially_valid' },
      { topic: 'Sine Table (Jya)', detail: { en: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."', hi: '3.75° अंतराल पर 24 ज्या मान। "sine" शब्द संस्कृत "ज्या" से आया: ज्या → अरबी जीब → लैटिन sinus।', sa: '3.75° अंतराल पर 24 ज्या मान। "sine" शब्द संस्कृत "ज्या" से आया: ज्या → अरबी जीब → लैटिन sinus।', mai: '3.75° अंतराल पर 24 ज्या मान। "sine" शब्द संस्कृत "ज्या" से आया: ज्या → अरबी जीब → लैटिन sinus।', mr: '3.75° अंतराल पर 24 ज्या मान। "sine" शब्द संस्कृत "ज्या" से आया: ज्या → अरबी जीब → लैटिन sinus।', ta: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."', te: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."', bn: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."', kn: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."', gu: '24 sine values at 3.75° intervals with radius 3438. The word "sine" itself derives from Sanskrit "jya" via Arabic "jiba" → Latin "sinus."' }, status: 'still_used' },
      { topic: 'Rahu-Ketu as Mathematical Points', detail: { en: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.', hi: 'चंद्र नोड्स को गणितीय छाया पिंडों के रूप में माना — गणितीय रूप से सही। मध्य नोड गणना अभी भी प्रयुक्त।', sa: 'चंद्र नोड्स को गणितीय छाया पिंडों के रूप में माना — गणितीय रूप से सही। मध्य नोड गणना अभी भी प्रयुक्त।', mai: 'चंद्र नोड्स को गणितीय छाया पिंडों के रूप में माना — गणितीय रूप से सही। मध्य नोड गणना अभी भी प्रयुक्त।', mr: 'चंद्र नोड्स को गणितीय छाया पिंडों के रूप में माना — गणितीय रूप से सही। मध्य नोड गणना अभी भी प्रयुक्त।', ta: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.', te: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.', bn: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.', kn: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.', gu: 'Treated lunar nodes as computed shadow bodies rather than physical planets — mathematically correct. Mean node computation still used.' }, status: 'still_used' },
      { topic: 'Precession (Ayanamsha)', detail: { en: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.', hi: 'प्रिसेशन का वर्णन किया लेकिन त्रेपिडेशन मॉडल (दोलनी) प्रयोग किया जो गलत है। प्रिसेशन एकदिशीय ~50.3" प्रति वर्ष है।', sa: 'प्रिसेशन का वर्णन किया लेकिन त्रेपिडेशन मॉडल (दोलनी) प्रयोग किया जो गलत है। प्रिसेशन एकदिशीय ~50.3" प्रति वर्ष है।', mai: 'प्रिसेशन का वर्णन किया लेकिन त्रेपिडेशन मॉडल (दोलनी) प्रयोग किया जो गलत है। प्रिसेशन एकदिशीय ~50.3" प्रति वर्ष है।', mr: 'प्रिसेशन का वर्णन किया लेकिन त्रेपिडेशन मॉडल (दोलनी) प्रयोग किया जो गलत है। प्रिसेशन एकदिशीय ~50.3" प्रति वर्ष है।', ta: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.', te: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.', bn: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.', kn: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.', gu: 'Described precession but used a TREPIDATION model (oscillating back and forth) rather than steady precession. This is incorrect — precession increases monotonically at ~50.3"/year.' }, status: 'superseded' },
      { topic: 'Geocentric Model', detail: { en: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).', hi: 'पृथ्वी को केंद्र में रखा। सूर्यकेंद्रित मॉडल द्वारा प्रतिस्थापित।', sa: 'पृथ्वी को केंद्र में रखा। सूर्यकेंद्रित मॉडल द्वारा प्रतिस्थापित।', mai: 'पृथ्वी को केंद्र में रखा। सूर्यकेंद्रित मॉडल द्वारा प्रतिस्थापित।', mr: 'पृथ्वी को केंद्र में रखा। सूर्यकेंद्रित मॉडल द्वारा प्रतिस्थापित।', ta: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).', te: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).', bn: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).', kn: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).', gu: 'Placed Earth at center with epicyclic planetary orbits. Superseded by heliocentric model (Copernicus, Kepler).' }, status: 'superseded' },
    ],
    accuracyHighlights: [
      { value: 'Synodic month', given: '29.530588 d', modern: '29.530589 d', error: '0.08 sec' },
      { value: 'Sidereal month', given: '27.32167 d', modern: '27.32166 d', error: '0.09 sec' },
      { value: 'Sidereal year', given: '365.258756 d', modern: '365.256363 d', error: '3.4 min' },
    ],
    uniqueConcepts: [
      { en: 'Mean-to-true longitude computation framework for traditional panchangs', hi: 'पारंपरिक पंचांगों के लिए मध्य-से-स्पष्ट देशांतर गणना', sa: 'पारंपरिक पंचांगों के लिए मध्य-से-स्पष्ट देशांतर गणना', mai: 'पारंपरिक पंचांगों के लिए मध्य-से-स्पष्ट देशांतर गणना', mr: 'पारंपरिक पंचांगों के लिए मध्य-से-स्पष्ट देशांतर गणना', ta: 'Mean-to-true longitude computation framework for traditional panchangs', te: 'Mean-to-true longitude computation framework for traditional panchangs', bn: 'Mean-to-true longitude computation framework for traditional panchangs', kn: 'Mean-to-true longitude computation framework for traditional panchangs', gu: 'Mean-to-true longitude computation framework for traditional panchangs' },
      { en: 'Tithi, Nakshatra, Yoga, Karana definitions', hi: 'तिथि, नक्षत्र, योग, करण की परिभाषाएं', sa: 'तिथि, नक्षत्र, योग, करण की परिभाषाएं', mai: 'तिथि, नक्षत्र, योग, करण की परिभाषाएं', mr: 'तिथि, नक्षत्र, योग, करण की परिभाषाएं', ta: 'Tithi, Nakshatra, Yoga, Karana definitions', te: 'Tithi, Nakshatra, Yoga, Karana definitions', bn: 'Tithi, Nakshatra, Yoga, Karana definitions', kn: 'Tithi, Nakshatra, Yoga, Karana definitions', gu: 'Tithi, Nakshatra, Yoga, Karana definitions' },
      { en: 'Eclipse magnitude and duration computation methods', hi: 'ग्रहण परिमाण और अवधि गणना विधियाँ', sa: 'ग्रहण परिमाण और अवधि गणना विधियाँ', mai: 'ग्रहण परिमाण और अवधि गणना विधियाँ', mr: 'ग्रहण परिमाण और अवधि गणना विधियाँ', ta: 'Eclipse magnitude and duration computation methods', te: 'Eclipse magnitude and duration computation methods', bn: 'Eclipse magnitude and duration computation methods', kn: 'Eclipse magnitude and duration computation methods', gu: 'Eclipse magnitude and duration computation methods' },
    ],
  },
  {
    id: 'aryabhatiya', category: 'siddhanta', chapters: 4, verses: '121',
    name: { en: 'Aryabhatiya', hi: 'आर्यभटीय', sa: 'आर्यभटीयम्' },
    author: { en: 'Aryabhata I (born 476 CE, Kusumapura/Patna)', hi: 'आर्यभट (जन्म 476 ई., कुसुमपुर/पटना)', sa: 'आर्यभट (जन्म 476 ई., कुसुमपुर/पटना)', mai: 'आर्यभट (जन्म 476 ई., कुसुमपुर/पटना)', mr: 'आर्यभट (जन्म 476 ई., कुसुमपुर/पटना)', ta: 'Aryabhata I (born 476 CE, Kusumapura/Patna)', te: 'Aryabhata I (born 476 CE, Kusumapura/Patna)', bn: 'Aryabhata I (born 476 CE, Kusumapura/Patna)', kn: 'Aryabhata I (born 476 CE, Kusumapura/Patna)', gu: 'Aryabhata I (born 476 CE, Kusumapura/Patna)' },
    date: '499 CE (written at age 23)',
    color: 'text-emerald-400', border: 'border-emerald-500/20',
    summary: { en: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.', hi: '121 श्लोकों की क्रांतिकारी कृति। आर्यभट ने कहा कि पृथ्वी अपनी धुरी पर घूमती है — कॉपरनिकस से 1,000 वर्ष पहले। उनका पाई मान (3.1416) प्राचीन विश्व में सबसे सटीक था।', sa: '121 श्लोकों की क्रांतिकारी कृति। आर्यभट ने कहा कि पृथ्वी अपनी धुरी पर घूमती है — कॉपरनिकस से 1,000 वर्ष पहले। उनका पाई मान (3.1416) प्राचीन विश्व में सबसे सटीक था।', mai: '121 श्लोकों की क्रांतिकारी कृति। आर्यभट ने कहा कि पृथ्वी अपनी धुरी पर घूमती है — कॉपरनिकस से 1,000 वर्ष पहले। उनका पाई मान (3.1416) प्राचीन विश्व में सबसे सटीक था।', mr: '121 श्लोकों की क्रांतिकारी कृति। आर्यभट ने कहा कि पृथ्वी अपनी धुरी पर घूमती है — कॉपरनिकस से 1,000 वर्ष पहले। उनका पाई मान (3.1416) प्राचीन विश्व में सबसे सटीक था।', ta: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.', te: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.', bn: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.', kn: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.', gu: 'A revolutionary 121-verse masterwork covering mathematics and astronomy. Aryabhata stated that Earth rotates on its axis — 1,000 years before Copernicus. His pi approximation (3.1416) was the most accurate in the ancient world. The word "sine" itself comes from his work.' },
    keyContributions: [
      { topic: "Earth's Rotation", detail: { en: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.', hi: '"जैसे नाव में बैठा व्यक्ति स्थिर वस्तुओं को पीछे जाते देखता है, वैसे ही स्थिर तारे पश्चिम की ओर गतिमान दिखते हैं।" — कॉपरनिकस से 1,000 वर्ष पहले।', sa: '"जैसे नाव में बैठा व्यक्ति स्थिर वस्तुओं को पीछे जाते देखता है, वैसे ही स्थिर तारे पश्चिम की ओर गतिमान दिखते हैं।" — कॉपरनिकस से 1,000 वर्ष पहले।', mai: '"जैसे नाव में बैठा व्यक्ति स्थिर वस्तुओं को पीछे जाते देखता है, वैसे ही स्थिर तारे पश्चिम की ओर गतिमान दिखते हैं।" — कॉपरनिकस से 1,000 वर्ष पहले।', mr: '"जैसे नाव में बैठा व्यक्ति स्थिर वस्तुओं को पीछे जाते देखता है, वैसे ही स्थिर तारे पश्चिम की ओर गतिमान दिखते हैं।" — कॉपरनिकस से 1,000 वर्ष पहले।', ta: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.', te: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.', bn: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.', kn: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.', gu: '"As a man in a boat sees stationary objects moving backward, so the stationary stars are seen as moving westward." — Aryabhata correctly stated Earth rotates daily, 1,000 years before Copernicus. This was REVOLUTIONARY.' }, status: 'still_used' },
      { topic: 'Pi = 3.1416', detail: { en: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.', hi: '"20,000 व्यास के वृत्त की परिधि 62,832" → π = 3.1416, 4 दशमलव स्थान तक सटीक।', sa: '"20,000 व्यास के वृत्त की परिधि 62,832" → π = 3.1416, 4 दशमलव स्थान तक सटीक।', mai: '"20,000 व्यास के वृत्त की परिधि 62,832" → π = 3.1416, 4 दशमलव स्थान तक सटीक।', mr: '"20,000 व्यास के वृत्त की परिधि 62,832" → π = 3.1416, 4 दशमलव स्थान तक सटीक।', ta: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.', te: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.', bn: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.', kn: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.', gu: '"A circle of diameter 20,000 has circumference 62,832" → pi = 3.1416, accurate to 4 decimal places. Best approximation in the ancient world.' }, status: 'still_used' },
      { topic: 'Sine Function Origin', detail: { en: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.', hi: 'प्रथम व्यवस्थित ज्या-अंतर सारणी (अर्ध-ज्या)। शब्द यात्रा: अर्ध-ज्या → ज्या → अरबी जीब → लैटिन sinus → English sine।', sa: 'प्रथम व्यवस्थित ज्या-अंतर सारणी (अर्ध-ज्या)। शब्द यात्रा: अर्ध-ज्या → ज्या → अरबी जीब → लैटिन sinus → English sine।', mai: 'प्रथम व्यवस्थित ज्या-अंतर सारणी (अर्ध-ज्या)। शब्द यात्रा: अर्ध-ज्या → ज्या → अरबी जीब → लैटिन sinus → English sine।', mr: 'प्रथम व्यवस्थित ज्या-अंतर सारणी (अर्ध-ज्या)। शब्द यात्रा: अर्ध-ज्या → ज्या → अरबी जीब → लैटिन sinus → English sine।', ta: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.', te: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.', bn: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.', kn: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.', gu: 'Created the first systematic sine difference table (ardha-jya = half-chord). Term journey: ardha-jya → jya → Arabic "jiba" → Latin "sinus" → English "sine." India invented the sine function.' }, status: 'still_used' },
      { topic: "Earth's Circumference", detail: { en: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.', hi: '~39,736 किमी। आधुनिक: 40,075 किमी। त्रुटि: केवल 0.8%।', sa: '~39,736 किमी। आधुनिक: 40,075 किमी। त्रुटि: केवल 0.8%।', mai: '~39,736 किमी। आधुनिक: 40,075 किमी। त्रुटि: केवल 0.8%।', mr: '~39,736 किमी। आधुनिक: 40,075 किमी। त्रुटि: केवल 0.8%।', ta: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.', te: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.', bn: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.', kn: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.', gu: '~39,736 km (using his yojana ≈ 8 km). Modern: 40,075 km. Error: only 0.8%.' }, status: 'still_used' },
      { topic: 'Kuttaka Algorithm', detail: { en: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.', hi: 'कुट्टक विधि — अनिर्धार्य समीकरणों के लिए, कैलेंडर गणना में आवश्यक, आज भी संख्या सिद्धांत में प्रयुक्त।', sa: 'कुट्टक विधि — अनिर्धार्य समीकरणों के लिए, कैलेंडर गणना में आवश्यक, आज भी संख्या सिद्धांत में प्रयुक्त।', mai: 'कुट्टक विधि — अनिर्धार्य समीकरणों के लिए, कैलेंडर गणना में आवश्यक, आज भी संख्या सिद्धांत में प्रयुक्त।', mr: 'कुट्टक विधि — अनिर्धार्य समीकरणों के लिए, कैलेंडर गणना में आवश्यक, आज भी संख्या सिद्धांत में प्रयुक्त।', ta: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.', te: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.', bn: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.', kn: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.', gu: '"Pulverizer" method for solving Diophantine equations — essential for calendar computation, still used in number theory and cryptography.' }, status: 'still_used' },
      { topic: 'Epicyclic Planetary Model', detail: { en: 'Used epicycles for planetary motion prediction. Superseded by Kepler\'s elliptical orbits (1609).', hi: 'ग्रह गति के लिए अधिचक्र। केपलर की दीर्घवृत्ताकार कक्षाओं (1609) द्वारा प्रतिस्थापित।' }, status: 'superseded' },
    ],
    accuracyHighlights: [
      { value: 'Pi', given: '3.1416', modern: '3.14159...', error: '0.0003%' },
      { value: 'Earth circumference', given: '39,736 km', modern: '40,075 km', error: '0.8%' },
      { value: 'Sidereal year', given: '365.25694 d', modern: '365.25636 d', error: '~50 sec' },
    ],
    uniqueConcepts: [
      { en: 'Earth rotates on its axis (1,000 years before Copernicus)', hi: 'पृथ्वी अपनी धुरी पर घूमती है (कॉपरनिकस से 1,000 वर्ष पूर्व)', sa: 'पृथ्वी अपनी धुरी पर घूमती है (कॉपरनिकस से 1,000 वर्ष पूर्व)', mai: 'पृथ्वी अपनी धुरी पर घूमती है (कॉपरनिकस से 1,000 वर्ष पूर्व)', mr: 'पृथ्वी अपनी धुरी पर घूमती है (कॉपरनिकस से 1,000 वर्ष पूर्व)', ta: 'Earth rotates on its axis (1,000 years before Copernicus)', te: 'Earth rotates on its axis (1,000 years before Copernicus)', bn: 'Earth rotates on its axis (1,000 years before Copernicus)', kn: 'Earth rotates on its axis (1,000 years before Copernicus)', gu: 'Earth rotates on its axis (1,000 years before Copernicus)' },
      { en: 'Sine function — India\'s gift to world mathematics', hi: 'ज्या (Sine) — विश्व गणित को भारत का उपहार' },
      { en: 'Place-value number system with zero (implicit)', hi: 'शून्य सहित स्थानमान संख्या पद्धति', sa: 'शून्य सहित स्थानमान संख्या पद्धति', mai: 'शून्य सहित स्थानमान संख्या पद्धति', mr: 'शून्य सहित स्थानमान संख्या पद्धति', ta: 'Place-value number system with zero (implicit)', te: 'Place-value number system with zero (implicit)', bn: 'Place-value number system with zero (implicit)', kn: 'Place-value number system with zero (implicit)', gu: 'Place-value number system with zero (implicit)' },
    ],
  },
  {
    id: 'bphs', category: 'hora', chapters: 97, verses: '~4,000',
    name: { en: 'Brihat Parashara Hora Shastra', hi: 'बृहत् पाराशर होरा शास्त्र', sa: 'बृहत्पाराशरहोराशास्त्रम्' },
    author: { en: 'Maharshi Parashara (compiled over centuries)', hi: 'महर्षि पराशर (शताब्दियों में संकलित)', sa: 'महर्षि पराशर (शताब्दियों में संकलित)', mai: 'महर्षि पराशर (शताब्दियों में संकलित)', mr: 'महर्षि पराशर (शताब्दियों में संकलित)', ta: 'Maharshi Parashara (compiled over centuries)', te: 'Maharshi Parashara (compiled over centuries)', bn: 'Maharshi Parashara (compiled over centuries)', kn: 'Maharshi Parashara (compiled over centuries)', gu: 'Maharshi Parashara (compiled over centuries)' },
    date: '7th-12th CE (as known today)',
    color: 'text-gold-light', border: 'border-gold-primary/20',
    summary: { en: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.', hi: 'वैदिक ज्योतिष का "बाइबल"। 97 अध्याय — राशि वर्णन से 40+ दशा पद्धतियों से उपाय तक। विंशोत्तरी दशा, 16 वर्ग चार्ट, षड्बल, अष्टकवर्ग सब यहीं से हैं।', sa: 'वैदिक ज्योतिष का "बाइबल"। 97 अध्याय — राशि वर्णन से 40+ दशा पद्धतियों से उपाय तक। विंशोत्तरी दशा, 16 वर्ग चार्ट, षड्बल, अष्टकवर्ग सब यहीं से हैं।', mai: 'वैदिक ज्योतिष का "बाइबल"। 97 अध्याय — राशि वर्णन से 40+ दशा पद्धतियों से उपाय तक। विंशोत्तरी दशा, 16 वर्ग चार्ट, षड्बल, अष्टकवर्ग सब यहीं से हैं।', mr: 'वैदिक ज्योतिष का "बाइबल"। 97 अध्याय — राशि वर्णन से 40+ दशा पद्धतियों से उपाय तक। विंशोत्तरी दशा, 16 वर्ग चार्ट, षड्बल, अष्टकवर्ग सब यहीं से हैं।', ta: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.', te: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.', bn: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.', kn: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.', gu: 'The "Bible" of Vedic astrology. 97 chapters covering every aspect of Parashari Jyotish — from sign descriptions to 40+ dasha systems to remedies. The Vimshottari Dasha system, 16 divisional charts, Shadbala, and Ashtakavarga all originate here. Virtually every technique used in modern Jyotish traces back to BPHS.' },
    keyContributions: [
      { topic: 'Vimshottari Dasha (120-year cycle)', detail: { en: 'The most widely used predictive timing system in Jyotish. Divides life into planetary periods based on Moon\'s birth nakshatra. BPHS is the PRIMARY source.', hi: 'ज्योतिष में सर्वाधिक प्रयुक्त भविष्यवाणी प्रणाली। चंद्र नक्षत्र पर आधारित। BPHS प्राथमिक स्रोत।' }, status: 'still_used' },
      { topic: '16 Divisional Charts (Shodashavarga)', detail: { en: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.', hi: 'D1 से D60 — जीवन के विभिन्न क्षेत्रों के 16 वर्ग चार्ट। कोई अन्य ग्रंथ इतने पूर्ण नहीं।', sa: 'D1 से D60 — जीवन के विभिन्न क्षेत्रों के 16 वर्ग चार्ट। कोई अन्य ग्रंथ इतने पूर्ण नहीं।', mai: 'D1 से D60 — जीवन के विभिन्न क्षेत्रों के 16 वर्ग चार्ट। कोई अन्य ग्रंथ इतने पूर्ण नहीं।', mr: 'D1 से D60 — जीवन के विभिन्न क्षेत्रों के 16 वर्ग चार्ट। कोई अन्य ग्रंथ इतने पूर्ण नहीं।', ta: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.', te: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.', bn: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.', kn: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.', gu: 'D1 through D60 — the full system of 16 varga charts for analyzing different life areas. No other text has this complete. Our app computes all 19.' }, status: 'still_used' },
      { topic: 'Shadbala (6-fold strength)', detail: { en: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.', hi: 'ग्रह बल की 6 घटकों द्वारा व्यवस्थित गणना। आज भी वर्णित विधि से गणना।', sa: 'ग्रह बल की 6 घटकों द्वारा व्यवस्थित गणना। आज भी वर्णित विधि से गणना।', mai: 'ग्रह बल की 6 घटकों द्वारा व्यवस्थित गणना। आज भी वर्णित विधि से गणना।', mr: 'ग्रह बल की 6 घटकों द्वारा व्यवस्थित गणना। आज भी वर्णित विधि से गणना।', ta: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.', te: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.', bn: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.', kn: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.', gu: 'Systematic computation of planetary strength through 6 components: Sthana, Dig, Kaala, Cheshta, Naisargika, Drik Bala. Still computed exactly as described.' }, status: 'still_used' },
      { topic: 'Ashtakavarga System', detail: { en: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.', hi: 'प्रत्येक ग्रह-राशि के लिए 8 स्रोतीय बल विश्लेषण। गोचर भविष्यवाणी में प्रयुक्त।', sa: 'प्रत्येक ग्रह-राशि के लिए 8 स्रोतीय बल विश्लेषण। गोचर भविष्यवाणी में प्रयुक्त।', mai: 'प्रत्येक ग्रह-राशि के लिए 8 स्रोतीय बल विश्लेषण। गोचर भविष्यवाणी में प्रयुक्त।', mr: 'प्रत्येक ग्रह-राशि के लिए 8 स्रोतीय बल विश्लेषण। गोचर भविष्यवाणी में प्रयुक्त।', ta: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.', te: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.', bn: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.', kn: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.', gu: '8-source strength analysis for each planet in each sign. Used for transit predictions. BPHS provides the full bindu allocation rules.' }, status: 'still_used' },
      { topic: '40+ Dasha Systems', detail: { en: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.', hi: '40+ दशा पद्धतियों का सबसे व्यापक संग्रह। अधिकांश विंशोत्तरी प्रयोग करते हैं, उन्नत साधक नारायण, कालचक्र, योगिनी आदि भी।', sa: '40+ दशा पद्धतियों का सबसे व्यापक संग्रह। अधिकांश विंशोत्तरी प्रयोग करते हैं, उन्नत साधक नारायण, कालचक्र, योगिनी आदि भी।', mai: '40+ दशा पद्धतियों का सबसे व्यापक संग्रह। अधिकांश विंशोत्तरी प्रयोग करते हैं, उन्नत साधक नारायण, कालचक्र, योगिनी आदि भी।', mr: '40+ दशा पद्धतियों का सबसे व्यापक संग्रह। अधिकांश विंशोत्तरी प्रयोग करते हैं, उन्नत साधक नारायण, कालचक्र, योगिनी आदि भी।', ta: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.', te: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.', bn: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.', kn: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.', gu: 'The most comprehensive collection of dasha systems anywhere. Most astrologers use only Vimshottari, but advanced practitioners use Narayana, Kalachakra, Yogini, Ashtottari, and others — all from BPHS.' }, status: 'still_used' },
      { topic: 'Planetary Remedies', detail: { en: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.', hi: 'प्रत्येक ग्रह के लिए रत्न, मंत्र, दान और अनुष्ठान। ज्योतिष साहित्य की प्रथम व्यापक उपचार प्रणाली।', sa: 'प्रत्येक ग्रह के लिए रत्न, मंत्र, दान और अनुष्ठान। ज्योतिष साहित्य की प्रथम व्यापक उपचार प्रणाली।', mai: 'प्रत्येक ग्रह के लिए रत्न, मंत्र, दान और अनुष्ठान। ज्योतिष साहित्य की प्रथम व्यापक उपचार प्रणाली।', mr: 'प्रत्येक ग्रह के लिए रत्न, मंत्र, दान और अनुष्ठान। ज्योतिष साहित्य की प्रथम व्यापक उपचार प्रणाली।', ta: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.', te: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.', bn: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.', kn: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.', gu: 'Gemstones, mantras, charities, and rituals for each planet. The first comprehensive remedial system in Jyotish literature.' }, status: 'still_used' },
    ],
    uniqueConcepts: [
      { en: 'The entire predictive framework of Parashari Jyotish', hi: 'पाराशरी ज्योतिष का संपूर्ण भविष्यवाणी ढांचा', sa: 'पाराशरी ज्योतिष का संपूर्ण भविष्यवाणी ढांचा', mai: 'पाराशरी ज्योतिष का संपूर्ण भविष्यवाणी ढांचा', mr: 'पाराशरी ज्योतिष का संपूर्ण भविष्यवाणी ढांचा', ta: 'The entire predictive framework of Parashari Jyotish', te: 'The entire predictive framework of Parashari Jyotish', bn: 'The entire predictive framework of Parashari Jyotish', kn: 'The entire predictive framework of Parashari Jyotish', gu: 'The entire predictive framework of Parashari Jyotish' },
      { en: 'Argala (planetary intervention) theory', hi: 'अर्गला (ग्रह हस्तक्षेप) सिद्धांत', sa: 'अर्गला (ग्रह हस्तक्षेप) सिद्धांत', mai: 'अर्गला (ग्रह हस्तक्षेप) सिद्धांत', mr: 'अर्गला (ग्रह हस्तक्षेप) सिद्धांत', ta: 'Argala (planetary intervention) theory', te: 'Argala (planetary intervention) theory', bn: 'Argala (planetary intervention) theory', kn: 'Argala (planetary intervention) theory', gu: 'Argala (planetary intervention) theory' },
      { en: 'Vimshopaka Bala (20-point varga strength)', hi: 'विंशोपक बल (20 अंकीय वर्ग शक्ति)', sa: 'विंशोपक बल (20 अंकीय वर्ग शक्ति)', mai: 'विंशोपक बल (20 अंकीय वर्ग शक्ति)', mr: 'विंशोपक बल (20 अंकीय वर्ग शक्ति)', ta: 'Vimshopaka Bala (20-point varga strength)', te: 'Vimshopaka Bala (20-point varga strength)', bn: 'Vimshopaka Bala (20-point varga strength)', kn: 'Vimshopaka Bala (20-point varga strength)', gu: 'Vimshopaka Bala (20-point varga strength)' },
    ],
  },
  {
    id: 'phaladeepika', category: 'hora', chapters: 28, verses: '~600',
    name: { en: 'Phaladeepika', hi: 'फलदीपिका', sa: 'फलदीपिका' },
    author: { en: 'Mantreshwara (South India)', hi: 'मंत्रेश्वर (दक्षिण भारत)', sa: 'मंत्रेश्वर (दक्षिण भारत)', mai: 'मंत्रेश्वर (दक्षिण भारत)', mr: 'मंत्रेश्वर (दक्षिण भारत)', ta: 'Mantreshwara (South India)', te: 'Mantreshwara (South India)', bn: 'Mantreshwara (South India)', kn: 'Mantreshwara (South India)', gu: 'Mantreshwara (South India)' },
    date: '~13th century CE',
    color: 'text-blue-300', border: 'border-blue-500/20',
    summary: { en: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.', hi: 'ज्योतिष सीखने की "सर्वोत्तम पाठ्यपुस्तक"। BPHS के सार को 600 सुंदर श्लोकों में 28 अध्यायों में व्यवस्थित। नभस योग वर्गीकरण और आयुर्दय गणना के लिए प्रसिद्ध।', sa: 'ज्योतिष सीखने की "सर्वोत्तम पाठ्यपुस्तक"। BPHS के सार को 600 सुंदर श्लोकों में 28 अध्यायों में व्यवस्थित। नभस योग वर्गीकरण और आयुर्दय गणना के लिए प्रसिद्ध।', mai: 'ज्योतिष सीखने की "सर्वोत्तम पाठ्यपुस्तक"। BPHS के सार को 600 सुंदर श्लोकों में 28 अध्यायों में व्यवस्थित। नभस योग वर्गीकरण और आयुर्दय गणना के लिए प्रसिद्ध।', mr: 'ज्योतिष सीखने की "सर्वोत्तम पाठ्यपुस्तक"। BPHS के सार को 600 सुंदर श्लोकों में 28 अध्यायों में व्यवस्थित। नभस योग वर्गीकरण और आयुर्दय गणना के लिए प्रसिद्ध।', ta: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.', te: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.', bn: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.', kn: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.', gu: 'Called the "best textbook" for learning Jyotish. Mantreshwara condensed the essence of BPHS into 600 elegant verses organized in 28 clear chapters. Known for its systematic Nabhasa Yoga classification and the most detailed Ayurdaya (longevity) computation methods.' },
    keyContributions: [
      { topic: '32 Nabhasa Yogas', detail: { en: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.', hi: '4 श्रेणियों में व्यवस्थित वर्गीकरण: आश्रय (3), दल (2), आकृति (20), संख्या (7)। BPHS से स्पष्ट।', sa: '4 श्रेणियों में व्यवस्थित वर्गीकरण: आश्रय (3), दल (2), आकृति (20), संख्या (7)। BPHS से स्पष्ट।', mai: '4 श्रेणियों में व्यवस्थित वर्गीकरण: आश्रय (3), दल (2), आकृति (20), संख्या (7)। BPHS से स्पष्ट।', mr: '4 श्रेणियों में व्यवस्थित वर्गीकरण: आश्रय (3), दल (2), आकृति (20), संख्या (7)। BPHS से स्पष्ट।', ta: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.', te: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.', bn: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.', kn: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.', gu: 'Systematic classification into 4 categories: Aashraya (3), Dala (2), Akriti (20), Sankhya (7). Clearer organization than BPHS. Still the standard reference.' }, status: 'still_used' },
      { topic: 'Ayurdaya (Longevity)', detail: { en: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.', hi: 'अनेक विधियों द्वारा दीर्घायु गणना का सबसे व्यवस्थित उपचार।', sa: 'अनेक विधियों द्वारा दीर्घायु गणना का सबसे व्यवस्थित उपचार।', mai: 'अनेक विधियों द्वारा दीर्घायु गणना का सबसे व्यवस्थित उपचार।', mr: 'अनेक विधियों द्वारा दीर्घायु गणना का सबसे व्यवस्थित उपचार।', ta: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.', te: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.', bn: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.', kn: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.', gu: 'Most systematic treatment of longevity computation using multiple methods. Reconciles different approaches to arrive at accurate lifespan estimates.' }, status: 'still_used' },
      { topic: 'Nastha Jataka (Rectification)', detail: { en: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.', hi: 'जीवन घटनाओं से अज्ञात जन्म समय सुधारने की व्यावहारिक विधियाँ।', sa: 'जीवन घटनाओं से अज्ञात जन्म समय सुधारने की व्यावहारिक विधियाँ।', mai: 'जीवन घटनाओं से अज्ञात जन्म समय सुधारने की व्यावहारिक विधियाँ।', mr: 'जीवन घटनाओं से अज्ञात जन्म समय सुधारने की व्यावहारिक विधियाँ।', ta: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.', te: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.', bn: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.', kn: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.', gu: 'Practical methods for rectifying unknown birth times using life events — the predecessor of modern birth time rectification techniques.' }, status: 'still_used' },
    ],
    uniqueConcepts: [
      { en: 'The clearest single-author textbook for learning Jyotish', hi: 'ज्योतिष सीखने की सबसे स्पष्ट एकल-लेखक पाठ्यपुस्तक', sa: 'ज्योतिष सीखने की सबसे स्पष्ट एकल-लेखक पाठ्यपुस्तक', mai: 'ज्योतिष सीखने की सबसे स्पष्ट एकल-लेखक पाठ्यपुस्तक', mr: 'ज्योतिष सीखने की सबसे स्पष्ट एकल-लेखक पाठ्यपुस्तक', ta: 'The clearest single-author textbook for learning Jyotish', te: 'The clearest single-author textbook for learning Jyotish', bn: 'The clearest single-author textbook for learning Jyotish', kn: 'The clearest single-author textbook for learning Jyotish', gu: 'The clearest single-author textbook for learning Jyotish' },
      { en: 'Female horoscopy with different emphasis points', hi: 'विभिन्न बिंदुओं के साथ स्त्री ज्योतिष', sa: 'विभिन्न बिंदुओं के साथ स्त्री ज्योतिष', mai: 'विभिन्न बिंदुओं के साथ स्त्री ज्योतिष', mr: 'विभिन्न बिंदुओं के साथ स्त्री ज्योतिष', ta: 'Female horoscopy with different emphasis points', te: 'Female horoscopy with different emphasis points', bn: 'Female horoscopy with different emphasis points', kn: 'Female horoscopy with different emphasis points', gu: 'Female horoscopy with different emphasis points' },
    ],
  },
  {
    id: 'brihat_jataka', category: 'hora', chapters: 28, verses: '~400',
    name: { en: 'Brihat Jataka', hi: 'बृहत् जातक', sa: 'बृहज्जातकम्' },
    author: { en: 'Varahamihira (Ujjain, ~505-587 CE)', hi: 'वराहमिहिर (उज्जैन, ~505-587 ई.)', sa: 'वराहमिहिर (उज्जैन, ~505-587 ई.)', mai: 'वराहमिहिर (उज्जैन, ~505-587 ई.)', mr: 'वराहमिहिर (उज्जैन, ~505-587 ई.)', ta: 'Varahamihira (Ujjain, ~505-587 CE)', te: 'Varahamihira (Ujjain, ~505-587 CE)', bn: 'Varahamihira (Ujjain, ~505-587 CE)', kn: 'Varahamihira (Ujjain, ~505-587 CE)', gu: 'Varahamihira (Ujjain, ~505-587 CE)' },
    date: '~550 CE',
    color: 'text-violet-400', border: 'border-violet-500/20',
    summary: { en: 'Varahamihira — one of the "Nine Jewels" of King Vikramaditya\'s court — brought systematic rigor to Indian astrology. He organized Jyotish into three branches (Siddhanta, Hora, Samhita), defined the Pancha Maha Purusha Yogas, and in his separate work Pancha Siddhantika, compared 5 astronomical traditions including Greco-Roman ones.', hi: 'वराहमिहिर — राजा विक्रमादित्य के "नवरत्नों" में से एक — ने ज्योतिष में व्यवस्थित कठोरता लाई। ज्योतिष को तीन शाखाओं (सिद्धांत, होरा, संहिता) में विभाजित किया।' },
    keyContributions: [
      { topic: 'Pancha Maha Purusha Yogas', detail: { en: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.', hi: 'रुचक, भद्र, हंस, मालव्य, शश — स्व/उच्च राशि में केंद्र में। आज भी सबसे अधिक जांचे जाने वाले 5 योग।', sa: 'रुचक, भद्र, हंस, मालव्य, शश — स्व/उच्च राशि में केंद्र में। आज भी सबसे अधिक जांचे जाने वाले 5 योग।', mai: 'रुचक, भद्र, हंस, मालव्य, शश — स्व/उच्च राशि में केंद्र में। आज भी सबसे अधिक जांचे जाने वाले 5 योग।', mr: 'रुचक, भद्र, हंस, मालव्य, शश — स्व/उच्च राशि में केंद्र में। आज भी सबसे अधिक जांचे जाने वाले 5 योग।', ta: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.', te: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.', bn: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.', kn: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.', gu: 'Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), Shasha (Saturn) — planet in own/exalted sign in kendra. These 5 yogas are still THE most commonly checked yogas today.' }, status: 'still_used' },
      { topic: 'Three-Branch Division of Jyotish', detail: { en: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.', hi: 'सिद्धांत + होरा + संहिता। यह त्रिभागीय विभाजन आज भी ज्योतिष वर्गीकरण का मानक।', sa: 'सिद्धांत + होरा + संहिता। यह त्रिभागीय विभाजन आज भी ज्योतिष वर्गीकरण का मानक।', mai: 'सिद्धांत + होरा + संहिता। यह त्रिभागीय विभाजन आज भी ज्योतिष वर्गीकरण का मानक।', mr: 'सिद्धांत + होरा + संहिता। यह त्रिभागीय विभाजन आज भी ज्योतिष वर्गीकरण का मानक।', ta: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.', te: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.', bn: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.', kn: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.', gu: 'Siddhanta (mathematical astronomy) + Hora (natal/predictive) + Samhita (mundane/omens). This tripartite division is STILL the standard framework for categorizing Jyotish.' }, status: 'still_used' },
      { topic: 'Pancha Siddhantika (separate work)', detail: { en: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.', hi: '5 खगोलीय परंपराओं की तुलना — रोमक (रोमन) और पौलिश (ग्रीक) सहित। 4 खोए सिद्धांतों का एकमात्र उत्तरजीवी अभिलेख।', sa: '5 खगोलीय परंपराओं की तुलना — रोमक (रोमन) और पौलिश (ग्रीक) सहित। 4 खोए सिद्धांतों का एकमात्र उत्तरजीवी अभिलेख।', mai: '5 खगोलीय परंपराओं की तुलना — रोमक (रोमन) और पौलिश (ग्रीक) सहित। 4 खोए सिद्धांतों का एकमात्र उत्तरजीवी अभिलेख।', mr: '5 खगोलीय परंपराओं की तुलना — रोमक (रोमन) और पौलिश (ग्रीक) सहित। 4 खोए सिद्धांतों का एकमात्र उत्तरजीवी अभिलेख।', ta: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.', te: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.', bn: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.', kn: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.', gu: 'Compared 5 astronomical traditions including Romaka (Roman) and Paulisha (Greek). Proves Indian astronomers critically engaged with Hellenistic astronomy. The ONLY surviving record of 4 lost siddhantas.' }, status: 'still_used' },
    ],
    uniqueConcepts: [
      { en: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)', hi: 'ज्योतिष का त्रिभागीय विभाजन', sa: 'ज्योतिष का त्रिभागीय विभाजन', mai: 'ज्योतिष का त्रिभागीय विभाजन', mr: 'ज्योतिष का त्रिभागीय विभाजन', ta: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)', te: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)', bn: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)', kn: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)', gu: 'The tripartite division of Jyotish (Siddhanta, Hora, Samhita)' },
      { en: 'First systematic cross-cultural comparison of astronomical traditions', hi: 'खगोलीय परंपराओं की प्रथम व्यवस्थित अंतर-सांस्कृतिक तुलना', sa: 'खगोलीय परंपराओं की प्रथम व्यवस्थित अंतर-सांस्कृतिक तुलना', mai: 'खगोलीय परंपराओं की प्रथम व्यवस्थित अंतर-सांस्कृतिक तुलना', mr: 'खगोलीय परंपराओं की प्रथम व्यवस्थित अंतर-सांस्कृतिक तुलना', ta: 'First systematic cross-cultural comparison of astronomical traditions', te: 'First systematic cross-cultural comparison of astronomical traditions', bn: 'First systematic cross-cultural comparison of astronomical traditions', kn: 'First systematic cross-cultural comparison of astronomical traditions', gu: 'First systematic cross-cultural comparison of astronomical traditions' },
    ],
  },
  {
    id: 'saravali', category: 'hora', chapters: 54, verses: '~2,400',
    name: { en: 'Saravali', hi: 'सारावली', sa: 'सारावली' },
    author: { en: 'Kalyana Varma (King, Central India)', hi: 'कल्याण वर्मा (राजा, मध्य भारत)', sa: 'कल्याण वर्मा (राजा, मध्य भारत)', mai: 'कल्याण वर्मा (राजा, मध्य भारत)', mr: 'कल्याण वर्मा (राजा, मध्य भारत)', ta: 'Kalyana Varma (King, Central India)', te: 'Kalyana Varma (King, Central India)', bn: 'Kalyana Varma (King, Central India)', kn: 'Kalyana Varma (King, Central India)', gu: 'Kalyana Varma (King, Central India)' },
    date: '~800-900 CE',
    color: 'text-pink-300', border: 'border-pink-500/20',
    summary: { en: 'The "practitioner\'s handbook" — explicitly synthesizes Parashara and Varahamihira. Known for exhaustive planet-in-sign combinations (all 108), three-planet conjunction effects, and blunt, specific predictions. Emphasizes Moon sign (Chandra Lagna) analysis more than any other text.', hi: '"अभ्यासकर्ता की पुस्तिका" — पराशर और वराहमिहिर का स्पष्ट संश्लेषण। 108 ग्रह-राशि संयोगों और त्रि-ग्रह युति प्रभावों के लिए जाना जाता है।' },
    keyContributions: [
      { topic: '108 Planet-in-Sign Combinations', detail: { en: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.', hi: '9 ग्रह × 12 राशि = 108 संयोग, प्रत्येक अलग श्लोक में — सबसे विस्तृत।', sa: '9 ग्रह × 12 राशि = 108 संयोग, प्रत्येक अलग श्लोक में — सबसे विस्तृत।', mai: '9 ग्रह × 12 राशि = 108 संयोग, प्रत्येक अलग श्लोक में — सबसे विस्तृत।', mr: '9 ग्रह × 12 राशि = 108 संयोग, प्रत्येक अलग श्लोक में — सबसे विस्तृत।', ta: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.', te: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.', bn: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.', kn: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.', gu: 'All 9 planets × 12 signs described in individual verses — the most exhaustive treatment anywhere. Essential reference for interpreting planetary placements.' }, status: 'still_used' },
      { topic: 'Three-Planet Conjunctions', detail: { en: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.', hi: 'दो-ग्रह योगों से आगे — 3+ ग्रह युति के प्रभावों का वर्णन।', sa: 'दो-ग्रह योगों से आगे — 3+ ग्रह युति के प्रभावों का वर्णन।', mai: 'दो-ग्रह योगों से आगे — 3+ ग्रह युति के प्रभावों का वर्णन।', mr: 'दो-ग्रह योगों से आगे — 3+ ग्रह युति के प्रभावों का वर्णन।', ta: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.', te: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.', bn: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.', kn: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.', gu: 'Goes beyond two-planet yogas to describe effects when 3+ planets are conjunct — a combinatorial depth rare in other texts.' }, status: 'still_used' },
      { topic: 'Moon Sign Emphasis', detail: { en: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.', hi: 'चंद्र लग्न परिणामों का सबसे विकसित उपचार। भावनात्मक पैटर्न और सार्वजनिक छवि समझने में महत्वपूर्ण।', sa: 'चंद्र लग्न परिणामों का सबसे विकसित उपचार। भावनात्मक पैटर्न और सार्वजनिक छवि समझने में महत्वपूर्ण।', mai: 'चंद्र लग्न परिणामों का सबसे विकसित उपचार। भावनात्मक पैटर्न और सार्वजनिक छवि समझने में महत्वपूर्ण।', mr: 'चंद्र लग्न परिणामों का सबसे विकसित उपचार। भावनात्मक पैटर्न और सार्वजनिक छवि समझने में महत्वपूर्ण।', ta: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.', te: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.', bn: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.', kn: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.', gu: 'Most developed treatment of Chandra Lagna (Moon as Ascendant) results. Crucial for understanding emotional patterns and public perception.' }, status: 'still_used' },
    ],
    uniqueConcepts: [
      { en: 'Physical appearance prediction from planetary positions', hi: 'ग्रह स्थिति से शारीरिक बनावट की भविष्यवाणी', sa: 'ग्रह स्थिति से शारीरिक बनावट की भविष्यवाणी', mai: 'ग्रह स्थिति से शारीरिक बनावट की भविष्यवाणी', mr: 'ग्रह स्थिति से शारीरिक बनावट की भविष्यवाणी', ta: 'Physical appearance prediction from planetary positions', te: 'Physical appearance prediction from planetary positions', bn: 'Physical appearance prediction from planetary positions', kn: 'Physical appearance prediction from planetary positions', gu: 'Physical appearance prediction from planetary positions' },
      { en: 'Detailed planetary war (Graha Yuddha) effects', hi: 'विस्तृत ग्रह युद्ध प्रभाव', sa: 'विस्तृत ग्रह युद्ध प्रभाव', mai: 'विस्तृत ग्रह युद्ध प्रभाव', mr: 'विस्तृत ग्रह युद्ध प्रभाव', ta: 'Detailed planetary war (Graha Yuddha) effects', te: 'Detailed planetary war (Graha Yuddha) effects', bn: 'Detailed planetary war (Graha Yuddha) effects', kn: 'Detailed planetary war (Graha Yuddha) effects', gu: 'Detailed planetary war (Graha Yuddha) effects' },
    ],
  },
];

const STATUS_CONFIG = {
  still_used: { icon: CheckCircle, color: 'text-emerald-400', bg: 'bg-emerald-500/10', label: { en: 'Still Valid & Used', hi: 'अभी भी प्रयुक्त', sa: 'अभी भी प्रयुक्त', mai: 'अभी भी प्रयुक्त', mr: 'अभी भी प्रयुक्त', ta: 'Still Valid & Used', te: 'Still Valid & Used', bn: 'Still Valid & Used', kn: 'Still Valid & Used', gu: 'Still Valid & Used' } },
  superseded: { icon: XCircle, color: 'text-red-400', bg: 'bg-red-500/10', label: { en: 'Superseded', hi: 'प्रतिस्थापित', sa: 'प्रतिस्थापित', mai: 'प्रतिस्थापित', mr: 'प्रतिस्थापित', ta: 'Superseded', te: 'Superseded', bn: 'Superseded', kn: 'Superseded', gu: 'Superseded' } },
  partially_valid: { icon: AlertTriangle, color: 'text-amber-400', bg: 'bg-amber-500/10', label: { en: 'Partially Valid', hi: 'आंशिक रूप से मान्य', sa: 'आंशिक रूप से मान्य', mai: 'आंशिक रूप से मान्य', mr: 'आंशिक रूप से मान्य', ta: 'Partially Valid', te: 'Partially Valid', bn: 'Partially Valid', kn: 'Partially Valid', gu: 'Partially Valid' } },
};

export default function ClassicalTextsPage() {
  const locale = useLocale() as Locale;
  const isHi = isDevanagariLocale(locale);
  const hf = isHi ? { fontFamily: 'var(--font-devanagari-heading)' } : { fontFamily: 'var(--font-heading)' };
  const [expandedText, setExpandedText] = useState<string | null>('aryabhatiya');

  return (
    <div className="space-y-10">
      <div>
        <h2 className="text-3xl font-bold text-gold-gradient mb-3" style={hf}>
          {isHi ? 'शास्त्रीय ग्रंथ — प्राचीन ज्ञान का मूल्यांकन' : 'Classical Texts — Evaluating Ancient Knowledge'}
        </h2>
        <p className="text-text-secondary text-sm leading-relaxed max-w-3xl">
          {isHi
            ? 'वैदिक ज्योतिष 6 प्रमुख शास्त्रीय ग्रंथों पर आधारित है। यहाँ हम प्रत्येक ग्रंथ का मूल्यांकन करते हैं — क्या अभी भी सटीक है, क्या आधुनिक विज्ञान द्वारा प्रतिस्थापित हुआ है, और क्या विशिष्ट योगदान आज भी प्रयुक्त हैं।'
            : 'Vedic Jyotish rests on 6 major classical texts spanning astronomy and predictive astrology. Here we evaluate each — what\'s still accurate, what\'s been superseded by modern science, and what unique contributions are still used today. Every claim includes its source chapter.'}
        </p>
      </div>

      {/* Two traditions visual */}
      <div className="bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-2xl p-5">
        <h3 className="text-gold-light font-bold text-sm mb-3" style={hf}>{isHi ? 'दो परंपराएं' : 'Two Traditions'}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-amber-500/15">
            <div className="text-amber-400 font-bold text-sm mb-1">{isHi ? 'सिद्धांत (Astronomical)' : 'Siddhanta (Astronomical)'}</div>
            <p className="text-text-secondary text-xs mb-2">{isHi ? 'गणितीय खगोल विज्ञान — ग्रह कहाँ हैं की गणना' : 'Mathematical astronomy — computing WHERE planets are'}</p>
            <div className="text-text-tertiary text-xs">Surya Siddhanta, Aryabhatiya</div>
          </div>
          <div className="p-4 rounded-xl bg-gold-primary/5 border border-gold-primary/15">
            <div className="text-gold-light font-bold text-sm mb-1">{isHi ? 'होरा (Predictive)' : 'Hora (Predictive)'}</div>
            <p className="text-text-secondary text-xs mb-2">{isHi ? 'फलित ज्योतिष — ग्रहों का क्या अर्थ है' : 'Interpretive astrology — what planet positions MEAN'}</p>
            <div className="text-text-tertiary text-xs">BPHS, Brihat Jataka, Phaladeepika, Saravali</div>
          </div>
        </div>
      </div>

      {/* Status legend */}
      <div className="flex flex-wrap gap-3 text-xs">
        {Object.entries(STATUS_CONFIG).map(([key, cfg]) => {
          const Icon = cfg.icon;
          return (
            <div key={key} className="flex items-center gap-1.5"><Icon className={`w-3.5 h-3.5 ${cfg.color}`} /><span className="text-text-secondary">{isHi ? cfg.label.hi : cfg.label.en}</span></div>
          );
        })}
      </div>

      {/* Timeline */}
      <div className="bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-2xl p-5">
        <h3 className="text-gold-dark text-xs uppercase tracking-widest font-bold mb-3">{isHi ? 'कालक्रम' : 'Timeline'}</h3>
        <div className="flex flex-wrap gap-2 justify-center">
          {TEXTS.sort((a, b) => {
            const getYear = (d: string) => parseInt(d.replace(/[^0-9]/g, '')) || 500;
            return getYear(a.date) - getYear(b.date);
          }).map((t, i) => (
            <div key={i} className={`px-3 py-2 rounded-lg border ${t.border} text-center min-w-[100px]`}>
              <div className={`font-bold text-xs ${t.color}`}>{t.date}</div>
              <div className="text-text-secondary text-xs">{isHi ? t.name.hi : t.name.en}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Text cards */}
      <div className="space-y-4">
        {TEXTS.map((text) => {
          const isExpanded = expandedText === text.id;
          return (
            <div key={text.id} className={`bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-2xl border ${text.border} overflow-hidden`}>
              {/* Header */}
              <button onClick={() => setExpandedText(isExpanded ? null : text.id)}
                className="w-full flex items-center justify-between px-5 py-4 hover:bg-gold-primary/3 transition-colors">
                <div className="flex items-center gap-4">
                  <BookOpen className={`w-6 h-6 ${text.color} shrink-0`} />
                  <div className="text-left">
                    <div className={`font-bold text-lg ${text.color}`} style={hf}>{isHi ? text.name.hi : text.name.en}</div>
                    <div className="text-text-secondary text-xs">{isHi ? text.author.hi : text.author.en} · {text.date} · {text.chapters} {isHi ? 'अध्याय' : 'chapters'} · {text.verses} {isHi ? 'श्लोक' : 'verses'}</div>
                  </div>
                </div>
                <ChevronDown className={`w-5 h-5 text-text-secondary transition-transform shrink-0 ${isExpanded ? 'rotate-180' : ''}`} />
              </button>

              <AnimatePresence>
                {isExpanded && (
                  <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                    <div className="px-5 pb-6 space-y-5 border-t border-gold-primary/10 pt-4">
                      {/* Summary */}
                      <p className="text-text-secondary text-sm leading-relaxed">{isHi ? text.summary.hi : text.summary.en}</p>

                      {/* Accuracy table (if available) */}
                      {text.accuracyHighlights && (
                        <div>
                          <div className="text-emerald-400 text-xs uppercase tracking-widest font-bold mb-2">{isHi ? 'सटीकता' : 'Accuracy Highlights'}</div>
                          <div className="overflow-x-auto">
                            <table className="w-full text-xs">
                              <thead><tr className="border-b border-gold-primary/10"><th className="text-left py-1.5 px-2 text-gold-dark">Value</th><th className="text-left py-1.5 px-2 text-gold-dark">Given</th><th className="text-left py-1.5 px-2 text-gold-dark">Modern</th><th className="text-left py-1.5 px-2 text-gold-dark">Error</th></tr></thead>
                              <tbody className="divide-y divide-gold-primary/5">
                                {text.accuracyHighlights.map((a, i) => (
                                  <tr key={i}><td className="py-1.5 px-2 text-text-primary">{a.value}</td><td className="py-1.5 px-2 text-gold-light font-mono">{a.given}</td><td className="py-1.5 px-2 text-text-secondary font-mono">{a.modern}</td><td className="py-1.5 px-2 text-emerald-300 font-mono">{a.error}</td></tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        </div>
                      )}

                      {/* Key contributions with relevance status */}
                      <div>
                        <div className="text-gold-dark text-xs uppercase tracking-widest font-bold mb-2">{isHi ? 'प्रमुख योगदान एवं आज की प्रासंगिकता' : 'Key Contributions & Modern Relevance'}</div>
                        <div className="space-y-2">
                          {text.keyContributions.map((kc, i) => {
                            const status = STATUS_CONFIG[kc.status];
                            const Icon = status.icon;
                            return (
                              <div key={i} className={`p-3 rounded-xl ${status.bg} border ${text.border}`}>
                                <div className="flex items-start gap-2">
                                  <Icon className={`w-4 h-4 ${status.color} shrink-0 mt-0.5`} />
                                  <div className="flex-1">
                                    <div className="flex items-center gap-2 mb-1">
                                      <span className="text-text-primary font-bold text-xs">{kc.topic}</span>
                                      <span className={`text-xs px-1.5 py-0.5 rounded ${status.bg} ${status.color} border ${text.border}`}>{isHi ? status.label.hi : status.label.en}</span>
                                    </div>
                                    <p className="text-text-secondary text-xs leading-relaxed">{isHi ? kc.detail.hi : kc.detail.en}</p>
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>

                      {/* Unique concepts still used */}
                      <div>
                        <div className="text-gold-dark text-xs uppercase tracking-widest font-bold mb-2">{isHi ? 'विशिष्ट अवधारणाएं (आज भी प्रयुक्त)' : 'Unique Concepts (Still Used Today)'}</div>
                        <div className="space-y-1">
                          {text.uniqueConcepts.map((uc, i) => (
                            <div key={i} className="text-text-secondary text-xs flex gap-2"><span className="text-gold-dark shrink-0">•</span><span>{isHi ? uc.hi : uc.en}</span></div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>

      {/* Modern synthesis */}
      <div className="bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-2xl p-6 border border-gold-primary/20 bg-gradient-to-br from-gold-primary/5 to-transparent">
        <h3 className="text-gold-gradient font-bold text-xl mb-4" style={hf}>
          {isHi ? 'आधुनिक संश्लेषण — हमारा दृष्टिकोण' : 'Modern Synthesis — Our Approach'}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-xl bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-emerald-500/15">
            <div className="text-emerald-400 font-bold text-sm mb-2">{isHi ? 'हम क्या उपयोग करते हैं' : 'What We Use'}</div>
            <ul className="text-text-secondary space-y-1.5 leading-relaxed">
              <li>• {isHi ? 'Swiss Ephemeris (NASA JPL DE431) — उप-कोणीय-सेकंड सटीकता' : 'Swiss Ephemeris (NASA JPL DE431) — sub-arcsecond accuracy'}</li>
              <li>• {isHi ? 'Meeus एल्गोरिदम — सूर्य ~0.01°, चंद्र ~0.5° सटीक' : 'Meeus algorithms — Sun ~0.01°, Moon ~0.5° precision'}</li>
              <li>• {isHi ? 'BPHS संपूर्ण भविष्यवाणी प्रणाली — दशा, वर्ग, अष्टकवर्ग' : 'BPHS complete predictive framework — Dashas, Vargas, Ashtakavarga'}</li>
              <li>• {isHi ? 'लाहिरी अयनांश (भारत सरकार आधिकारिक)' : 'Lahiri Ayanamsha (Indian Govt official)'}</li>
            </ul>
          </div>
          <div className="p-4 rounded-xl bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-red-500/15">
            <div className="text-red-400 font-bold text-sm mb-2">{isHi ? 'हमने क्या बदला' : 'What We\'ve Updated'}</div>
            <ul className="text-text-secondary space-y-1.5 leading-relaxed">
              <li>• {isHi ? 'भूकेंद्रित → सूर्यकेंद्रित + केप्लर कक्षाएं (गणना में)' : 'Geocentric → Heliocentric + Keplerian orbits (for computation)'}</li>
              <li>• {isHi ? 'त्रेपिडेशन → एकदिशीय प्रिसेशन (~50.3"/वर्ष)' : 'Trepidation → Monotonic precession (~50.3"/year)'}</li>
              <li>• {isHi ? 'पौराणिक ब्रह्मांड विज्ञान → आधुनिक खगोल विज्ञान' : 'Mythological cosmography → Modern astronomy'}</li>
              <li>• {isHi ? 'अधिचक्र → NASA/JPL दीर्घवृत्ताकार कक्षा डेटा' : 'Epicycles → NASA/JPL elliptical orbit data'}</li>
            </ul>
          </div>
        </div>
        <p className="text-text-tertiary text-xs text-center mt-4">
          {isHi
            ? '💡 सूत्र: आधुनिक गणना (कहाँ) + शास्त्रीय व्याख्या (क्या अर्थ) = सर्वोत्तम ज्योतिष'
            : '💡 Formula: Modern computation (WHERE) + Classical interpretation (WHAT IT MEANS) = Best Jyotish'}
        </p>
      </div>
    </div>
  );
}
