/**
 * Runtime merger that overlays per-locale `festival-details-{locale}-overlay.json`
 * files onto FESTIVAL_DETAILS + CATEGORY_DETAILS, populating `.{locale}` fields
 * on each LocaleText object without mutating festival-details.ts.
 *
 * Overlay JSONs are generated by scripts/translate-festival-details-via-gemini.py.
 * Each is keyed by dotted path:
 *   `makar-sankranti.name`
 *   `makar-sankranti.mythology`
 *   `makar-sankranti.observance`
 *   `makar-sankranti.significance`
 *   `makar-sankranti.deity`
 *   `makar-sankranti.fastNote`
 *   `makar-sankranti.observationRule`
 *
 * Why runtime merge instead of mutating festival-details.ts directly:
 *  - Keeps the source-of-truth EN/HI constants reviewable as code
 *  - Each overlay JSON is a single file — easy to regenerate per locale
 *    when a festival's English copy changes (idempotent — refills only
 *    the empty cells)
 *  - Diff cost on `git diff` stays manageable as new locales land
 *
 * Empty overlay entries (or missing files for a locale that's not yet
 * translated) are no-ops: the rendering `tl()` helper falls back to .en
 * via the global LocaleText index signature.
 *
 * Consumers: switch `import { FESTIVAL_DETAILS } from '@/lib/constants/festival-details'`
 * to `from '@/lib/constants/festival-details-with-overlay'`. Same for
 * CATEGORY_DETAILS. Output shape is identical (re-exported) — only the
 * already-merged data differs from the source.
 *
 * Same lifecycle / spec as yoga-details-with-overlay.ts (state 2 → 3
 * promotion per docs/specs/2026-06-04-noindex-thin-translation-locales.md).
 */

import {
  FESTIVAL_DETAILS as RAW_FESTIVAL_DETAILS,
  CATEGORY_DETAILS as RAW_CATEGORY_DETAILS,
  EKADASHI_NAMES as RAW_EKADASHI_NAMES,
  type FestivalDetail,
} from './festival-details';

import taOverlayRaw from './festival-details-ta-overlay.json';
import teOverlayRaw from './festival-details-te-overlay.json';
import bnOverlayRaw from './festival-details-bn-overlay.json';
import guOverlayRaw from './festival-details-gu-overlay.json';
import knOverlayRaw from './festival-details-kn-overlay.json';
import maiOverlayRaw from './festival-details-mai-overlay.json';
import mrOverlayRaw from './festival-details-mr-overlay.json';
import saOverlayRaw from './festival-details-sa-overlay.json';

type OverlayLocale = 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mai' | 'mr' | 'sa';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
  sa: saOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['ta', 'te', 'bn', 'gu', 'kn', 'mai', 'mr', 'sa'];

// Fields on FestivalDetail that are LocaleText (translatable).
const TRANSLATABLE_FIELDS: ReadonlyArray<keyof FestivalDetail> = [
  'name',
  'mythology',
  'observance',
  'significance',
  'deity',
  'fastNote',
  'observationRule',
];

// Merge an overlay value into one LocaleText, if not already filled.
function attachToLocaleText(
  field: unknown,
  slug: string,
  fieldName: string,
): void {
  if (!field || typeof field !== 'object') return;
  const ft = field as Record<string, string | undefined>;
  const overlayKey = `${slug}.${fieldName}`;
  for (const locale of OVERLAY_LOCALES) {
    // Skip if already present in source (don't overwrite hand-authored)
    if (typeof ft[locale] === 'string' && ft[locale]!.trim()) continue;
    const overlayVal = OVERLAYS[locale][overlayKey];
    if (typeof overlayVal === 'string' && overlayVal.trim()) {
      ft[locale] = overlayVal;
    }
  }
}

// Apply overlays to one festival-or-category record.
function applyOverlays(slug: string, entry: FestivalDetail): FestivalDetail {
  // Clone shallowly so we don't mutate the imported source constant.
  // Each translatable field is shallow-cloned then mutated. Using
  // `unknown` intermediary because FestivalDetail lacks an index
  // signature — we know the cast is safe because `field` comes from
  // the typed key list above.
  const cloned: Record<string, unknown> = { ...entry };
  for (const field of TRANSLATABLE_FIELDS) {
    const v = cloned[field];
    if (!v || typeof v !== 'object') continue;
    const clonedField = { ...(v as Record<string, unknown>) };
    attachToLocaleText(clonedField, slug, field);
    cloned[field] = clonedField;
  }
  return cloned as unknown as FestivalDetail;
}

function applyToDict(
  dict: Record<string, FestivalDetail>,
): Record<string, FestivalDetail> {
  const out: Record<string, FestivalDetail> = {};
  for (const [slug, entry] of Object.entries(dict)) {
    out[slug] = applyOverlays(slug, entry);
  }
  return out;
}

export const FESTIVAL_DETAILS: Readonly<Record<string, FestivalDetail>> =
  applyToDict(RAW_FESTIVAL_DETAILS);

export const CATEGORY_DETAILS: Readonly<Record<string, FestivalDetail>> =
  applyToDict(RAW_CATEGORY_DETAILS);

// Pass-through: EKADASHI_NAMES is a different shape (per-month
// shukla/krishna) and not currently in the translation corpus.
export const EKADASHI_NAMES = RAW_EKADASHI_NAMES;

// Pass through the remaining named exports so a single import swap
// (festival-details → festival-details-with-overlay) is enough for
// every consumer. Lookups, helpers, and constants that don't carry
// translatable LocaleText fields are forwarded unchanged.
export {
  ADHIKA_MASA_EKADASHI,
  NAVRATRI_DAYS,
  getHinduMonth,
  getNextHinduMonth,
  getPreviousHinduMonth,
  getEkadashiName,
  resolveEkadashiDetail,
} from './festival-details';
export type { FestivalDetail, EkadashiDetail, NavratriDay } from './festival-details';
