// src/lib/constants/glossary.ts
import type { LocaleText } from '@/types/panchang';

export interface GlossaryEntry {
  id: string;
  term: LocaleText;
  pronunciation: string;
  shortDef: string;
  fullDef: string;
  westernEquivalent?: string;
  category: 'panchang' | 'kundali' | 'dasha' | 'yoga' | 'general';
  relatedTerms: string[];
  seeAlso?: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  // --- PANCHANG (12) ---
  {
    id: 'panchang',
    term: { en: 'Panchang', hi: 'पंचांग', sa: 'पञ्चाङ्गम्' },
    pronunciation: 'PUHN-chahng',
    shortDef: 'The five-limbed Vedic almanac: tithi, nakshatra, yoga, karana, and vara.',
    fullDef: 'Panchang literally means "five limbs" (pancha + anga). It is the traditional Vedic calendar and almanac that tracks five astronomical elements daily: Tithi (lunar day), Nakshatra (lunar mansion), Yoga (Sun-Moon angular relationship), Karana (half-tithi), and Vara (weekday). Unlike the Gregorian calendar which tracks only solar position, the Panchang integrates both solar and lunar cycles, providing a richer temporal map used for timing important activities.',
    westernEquivalent: 'Almanac / Ephemeris',
    category: 'panchang',
    relatedTerms: ['tithi', 'nakshatra', 'yoga', 'karana', 'vara'],
  },
  {
    id: 'tithi',
    term: { en: 'Tithi', hi: 'तिथि', sa: 'तिथिः' },
    pronunciation: 'TIH-thee',
    shortDef: 'A lunar day — each 12° angular separation between Sun and Moon.',
    fullDef: "A Tithi is one of 30 divisions of the synodic month, defined by the angular distance between the Sun and Moon. Each tithi spans exactly 12° of separation. Unlike solar days which are fixed at ~24 hours, tithis vary in duration from ~19 to ~26 hours because the Moon's orbital speed is not constant. The 30 tithis are split into two pakshas (fortnights): Shukla (waxing, 1-15) and Krishna (waning, 1-15). Each tithi has a distinct energetic quality used in Muhurta timing.",
    westernEquivalent: 'Lunar Day / Lunar Phase Division',
    category: 'panchang',
    relatedTerms: ['paksha', 'amavasya', 'purnima', 'panchang'],
  },
  {
    id: 'nakshatra',
    term: { en: 'Nakshatra', hi: 'नक्षत्र', sa: 'नक्षत्रम्' },
    pronunciation: 'NUHK-shuh-truh',
    shortDef: "One of 27 lunar mansions — divisions of the Moon's orbit mapping emotional patterns.",
    fullDef: "The 27 Nakshatras divide the ecliptic into 13°20' segments, each associated with a ruling deity, planet, symbol, and quality. While Western astrology relies solely on 12 zodiac signs (30° each), Vedic astrology adds this 27-fold lunar overlay, providing significantly higher resolution for personality and timing analysis. The Moon's nakshatra at birth is considered more important than the Sun sign in Vedic tradition — it determines the starting point of the Vimshottari Dasha cycle and shapes emotional instincts.",
    westernEquivalent: 'Lunar Mansion / Lunar Constellation',
    category: 'panchang',
    relatedTerms: ['rashi', 'panchang', 'dasha', 'vimshottari'],
  },
  {
    id: 'yoga',
    term: { en: 'Yoga (Astronomical)', hi: 'योग', sa: 'योगः' },
    pronunciation: 'YOH-guh',
    shortDef: 'One of 27 Sun-Moon angular combinations indicating daily energy quality.',
    fullDef: 'In the Panchang context, Yoga refers to one of 27 specific angular relationships between the Sun and Moon, calculated by adding their longitudes and dividing by 13°20\'. Each yoga has a name and quality (auspicious, neutral, or inauspicious) that influences the energetic tone of the day. Not to be confused with planetary yogas in Kundali analysis, which are specific combinations of planets in a birth chart.',
    westernEquivalent: 'Sun-Moon Angular Combination',
    category: 'panchang',
    relatedTerms: ['panchang', 'tithi', 'nakshatra'],
  },
  {
    id: 'karana',
    term: { en: 'Karana', hi: 'करण', sa: 'करणम्' },
    pronunciation: 'KUH-ruh-nuh',
    shortDef: "A half-tithi — one of 11 types that refine the lunar day's quality.",
    fullDef: 'A Karana is half of a Tithi, meaning each tithi contains two karanas. There are 11 karanas in total: 7 movable (Bava, Balava, Kaulava, Taitila, Gara, Vanija, Vishti) that cycle through the month, and 4 fixed (Shakuni, Chatushpada, Naga, Kimstughna) that occur only once per month. Vishti (also called Bhadra) is considered particularly inauspicious. Karanas refine the quality of a tithi for precise Muhurta timing.',
    westernEquivalent: 'Half Lunar Day',
    category: 'panchang',
    relatedTerms: ['tithi', 'panchang', 'muhurta'],
  },
  {
    id: 'vara',
    term: { en: 'Vara', hi: 'वार', sa: 'वारः' },
    pronunciation: 'VAH-ruh',
    shortDef: "The weekday — each ruled by a planet influencing the day's character.",
    fullDef: "Vara is the weekday component of the Panchang. Each of the 7 days is ruled by a planet: Sunday (Sun), Monday (Moon), Tuesday (Mars), Wednesday (Mercury), Thursday (Jupiter), Friday (Venus), Saturday (Saturn). The ruling planet colors the day's energy and is considered in Muhurta (auspicious timing) calculations. The Vara system is one of the oldest astronomical cycles still in daily use.",
    westernEquivalent: 'Weekday',
    category: 'panchang',
    relatedTerms: ['panchang', 'graha', 'muhurta'],
  },
  {
    id: 'masa',
    term: { en: 'Masa', hi: 'मास', sa: 'मासः' },
    pronunciation: 'MAH-suh',
    shortDef: 'A lunar month — from New Moon to New Moon (Amanta) or Full Moon to Full Moon (Purnimanta).',
    fullDef: 'Masa is the Vedic lunar month. Two systems exist: Amanta (month ends on Amavasya/New Moon, used in most of India) and Purnimanta (month ends on Purnima/Full Moon, used in North India). The 12 months are named after nakshatras where the Full Moon falls: Chaitra, Vaishakha, Jyeshtha, Ashadha, Shravana, Bhadrapada, Ashvina, Kartika, Margashirsha, Pausha, Magha, Phalguna. An intercalary month (Adhika Masa) is inserted roughly every 32.5 months to keep lunar and solar calendars aligned.',
    westernEquivalent: 'Lunar Month',
    category: 'panchang',
    relatedTerms: ['paksha', 'purnima', 'amavasya', 'samvatsara'],
  },
  {
    id: 'paksha',
    term: { en: 'Paksha', hi: 'पक्ष', sa: 'पक्षः' },
    pronunciation: 'PUHK-shuh',
    shortDef: 'A lunar fortnight — Shukla (waxing, bright) or Krishna (waning, dark).',
    fullDef: 'Each lunar month is divided into two Pakshas of ~15 days each. Shukla Paksha (bright half) runs from New Moon to Full Moon as the Moon waxes. Krishna Paksha (dark half) runs from Full Moon to New Moon as the Moon wanes. The Paksha determines the numbering of tithis: Shukla Pratipada (1st day of waxing) through Purnima (Full Moon), then Krishna Pratipada through Amavasya (New Moon).',
    westernEquivalent: 'Lunar Fortnight (Waxing / Waning)',
    category: 'panchang',
    relatedTerms: ['tithi', 'masa', 'purnima', 'amavasya'],
  },
  {
    id: 'amavasya',
    term: { en: 'Amavasya', hi: 'अमावस्या', sa: 'अमावास्या' },
    pronunciation: 'uh-MAH-vus-yah',
    shortDef: 'New Moon — the 30th tithi when Moon is conjunct Sun. A natural reset point.',
    fullDef: 'Amavasya is the New Moon, the last tithi of Krishna Paksha when the Moon is invisible, conjunct with the Sun. In the Amanta calendar system, it marks the end of the lunar month. Traditionally considered a day of introspection, ancestor remembrance (Pitru Tarpana), and setting intentions. The word literally means "dwelling together" (ama + vasya), referring to Sun and Moon occupying the same degree.',
    westernEquivalent: 'New Moon',
    category: 'panchang',
    relatedTerms: ['paksha', 'purnima', 'tithi', 'masa'],
  },
  {
    id: 'purnima',
    term: { en: 'Purnima', hi: 'पूर्णिमा', sa: 'पूर्णिमा' },
    pronunciation: 'POOR-nih-mah',
    shortDef: 'Full Moon — the 15th tithi of Shukla Paksha. Peak lunar energy.',
    fullDef: 'Purnima is the Full Moon, the 15th tithi of Shukla Paksha when the Moon is fully illuminated and exactly opposite the Sun. In the Purnimanta calendar system, it marks the end of the lunar month. Considered the most energetically charged day of the month — emotions, creativity, and social energy peak. Many festivals (Holi, Guru Purnima, Sharad Purnima) fall on Purnima.',
    westernEquivalent: 'Full Moon',
    category: 'panchang',
    relatedTerms: ['paksha', 'amavasya', 'tithi', 'masa'],
  },
  {
    id: 'samvatsara',
    term: { en: 'Samvatsara', hi: 'संवत्सर', sa: 'संवत्सरः' },
    pronunciation: 'suhm-VUHT-suh-ruh',
    shortDef: 'A Vedic year in the 60-year Jupiter cycle — each with a distinct character.',
    fullDef: "Samvatsara is the Vedic year, part of a 60-year cycle based on Jupiter's ~12-year orbital period combined with the 5-year Yuga cycle (12 x 5 = 60). Each Samvatsara has a unique name (Prabhava, Vibhava, Shukla, etc.) and is believed to carry a distinctive quality that influences events during that year. The current cycle began with Prabhava and is tracked in both North Indian (Vikram) and South Indian (Shalivahana) eras.",
    westernEquivalent: 'Jupiter Cycle Year',
    category: 'panchang',
    relatedTerms: ['masa', 'ayana'],
  },
  {
    id: 'ayana',
    term: { en: 'Ayana', hi: 'अयन', sa: 'अयनम्' },
    pronunciation: 'UH-yuh-nuh',
    shortDef: "A 6-month solar half-year — Uttarayana (northward) or Dakshinayana (southward).",
    fullDef: "Ayana divides the solar year into two halves based on the Sun's apparent north-south movement. Uttarayana (northward journey, ~Jan 14 to Jul 14) begins at Makara Sankranti when the Sun enters Capricorn. Dakshinayana (southward journey, ~Jul 14 to Jan 14) begins when the Sun enters Cancer. Uttarayana is traditionally considered more auspicious for new ventures, while Dakshinayana is associated with inner work and spiritual practice.",
    westernEquivalent: 'Solar Half-Year / Solstice Period',
    category: 'panchang',
    relatedTerms: ['samvatsara', 'panchang'],
  },

  // --- KUNDALI (14) ---
  {
    id: 'kundali',
    term: { en: 'Kundali', hi: 'कुंडली', sa: 'कुण्डली' },
    pronunciation: 'KOON-duh-lee',
    shortDef: 'A Vedic birth chart — the map of planetary positions at the moment of birth.',
    fullDef: 'Kundali (also Janampatri or Janam Kundali) is the Vedic birth chart, a precise map of all planetary positions as seen from the birth location at the exact moment of birth. Unlike Western charts which use the tropical zodiac, Kundali uses the sidereal zodiac corrected by Ayanamsha to align with actual constellation positions. The chart contains 12 houses (Bhavas), 9 planets (Grahas), and forms the basis for all predictive and personality analysis in Jyotish.',
    westernEquivalent: 'Birth Chart / Natal Chart / Horoscope',
    category: 'kundali',
    relatedTerms: ['lagna', 'rashi', 'graha', 'bhava', 'ayanamsha'],
  },
  {
    id: 'lagna',
    term: { en: 'Lagna', hi: 'लग्न', sa: 'लग्नम्' },
    pronunciation: 'LUHG-nuh',
    shortDef: 'The Ascendant — the zodiac sign rising on the eastern horizon at birth.',
    fullDef: "Lagna is the exact degree of the zodiac rising on the eastern horizon at the moment of birth. It changes approximately every 2 hours, making it the most time-sensitive point in the chart. The Lagna sign becomes the 1st house and determines the entire house layout. It represents the native's physical constitution, personality, and how they present to the world. In Vedic astrology, Lagna is considered more important than the Sun sign.",
    westernEquivalent: 'Ascendant / Rising Sign',
    category: 'kundali',
    relatedTerms: ['kundali', 'bhava', 'rashi'],
  },
  {
    id: 'rashi',
    term: { en: 'Rashi', hi: 'राशि', sa: 'राशिः' },
    pronunciation: 'RAH-shee',
    shortDef: 'A zodiac sign — one of 12 sidereal divisions of 30° each along the ecliptic.',
    fullDef: 'Rashi refers to one of the 12 zodiac signs in Vedic astrology. The 12 Rashis are: Mesha (Aries), Vrishabha (Taurus), Mithuna (Gemini), Karka (Cancer), Simha (Leo), Kanya (Virgo), Tula (Libra), Vrishchika (Scorpio), Dhanu (Sagittarius), Makara (Capricorn), Kumbha (Aquarius), Meena (Pisces). Critically, Vedic Rashis use the sidereal zodiac (aligned to actual constellations), not the tropical zodiac used in Western astrology — the two systems are currently offset by ~24°.',
    westernEquivalent: 'Zodiac Sign (Sidereal)',
    category: 'kundali',
    relatedTerms: ['kundali', 'lagna', 'graha', 'ayanamsha'],
  },
  {
    id: 'graha',
    term: { en: 'Graha', hi: 'ग्रह', sa: 'ग्रहः' },
    pronunciation: 'GRUH-huh',
    shortDef: 'A celestial influencer — the 9 Vedic planets including shadow planets Rahu and Ketu.',
    fullDef: "Graha literally means \"seizer\" — that which seizes or influences. The 9 Vedic Grahas are: Surya (Sun), Chandra (Moon), Mangal (Mars), Budha (Mercury), Guru (Jupiter), Shukra (Venus), Shani (Saturn), Rahu (North Lunar Node), and Ketu (South Lunar Node). Unlike Western astrology which added Uranus, Neptune, and Pluto, Vedic astrology uses these 9 bodies exclusively. Rahu and Ketu are mathematical points (the Moon's orbital nodes) that cause eclipses — they have no physical body but are considered powerful karmic indicators.",
    westernEquivalent: 'Planet (including Lunar Nodes)',
    category: 'kundali',
    relatedTerms: ['kundali', 'rashi', 'bhava', 'dasha'],
  },
  {
    id: 'bhava',
    term: { en: 'Bhava', hi: 'भाव', sa: 'भावः' },
    pronunciation: 'BHAH-vuh',
    shortDef: 'A house — one of 12 life domains in the birth chart (career, relationships, etc.).',
    fullDef: 'Bhava means "state of being" and refers to one of the 12 houses in the Kundali, each governing a specific life domain: 1st (self), 2nd (wealth/speech), 3rd (siblings/courage), 4th (home/mother), 5th (children/creativity), 6th (enemies/health), 7th (spouse/partnerships), 8th (transformation/longevity), 9th (luck/dharma), 10th (career/status), 11th (gains/community), 12th (loss/liberation). The Lagna determines which sign occupies the 1st house, cascading the rest.',
    westernEquivalent: 'House',
    category: 'kundali',
    relatedTerms: ['kundali', 'lagna', 'rashi', 'graha'],
  },
  {
    id: 'navamsha',
    term: { en: 'Navamsha', hi: 'नवांश', sa: 'नवांशः' },
    pronunciation: 'nuh-VAHM-shuh',
    shortDef: "The D9 divisional chart — reveals marriage potential and the soul's deeper purpose.",
    fullDef: "Navamsha (D9) is the most important divisional chart after the birth chart (D1). Each sign is divided into 9 parts of 3°20', and each part maps to a sign in the Navamsha chart. It is primarily used to assess marriage/partnership potential and the deeper spiritual nature of the native. A planet strong in D1 but weak in D9 may not deliver its full promise. Many Jyotish practitioners consider a reading incomplete without Navamsha analysis.",
    westernEquivalent: 'Harmonic Chart (9th Harmonic)',
    category: 'kundali',
    relatedTerms: ['kundali', 'varga', 'rashi'],
  },
  {
    id: 'ayanamsha',
    term: { en: 'Ayanamsha', hi: 'अयनांश', sa: 'अयनांशः' },
    pronunciation: 'UH-yuh-NAHM-shuh',
    shortDef: "The angular offset (~24°) between tropical and sidereal zodiacs due to Earth's axial precession.",
    fullDef: "Ayanamsha is the angular difference between the tropical zodiac (used in Western astrology, anchored to the spring equinox) and the sidereal zodiac (used in Vedic astrology, anchored to fixed stars). Due to the precession of Earth's rotational axis, this offset increases by ~50.3 arc-seconds per year. Currently ~24.2° (Lahiri), it means your Vedic sign placements are typically one sign behind your Western placements. Multiple ayanamsha systems exist (Lahiri, Raman, KP) with slightly different reference points.",
    westernEquivalent: 'Precession Offset',
    category: 'kundali',
    relatedTerms: ['rashi', 'kundali', 'sidereal_tropical'],
  },
  {
    id: 'hora',
    term: { en: 'Hora', hi: 'होरा', sa: 'होरा' },
    pronunciation: 'HOH-rah',
    shortDef: 'A planetary hour — each hour of the day ruled by a specific planet.',
    fullDef: "Hora divides each day into planetary hours, each ruled by one of the 7 visible planets. The sequence follows the Chaldean order: Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon. The first hora of each day is ruled by the day's lord (Sunday = Sun, Monday = Moon, etc.). Horas are used in Muhurta to fine-tune the timing of activities — a Jupiter hora is favorable for education and spirituality, while a Venus hora suits creative and romantic pursuits.",
    westernEquivalent: 'Planetary Hour',
    category: 'kundali',
    relatedTerms: ['muhurta', 'graha', 'vara'],
  },
  {
    id: 'drekkana',
    term: { en: 'Drekkana', hi: 'द्रेक्काण', sa: 'द्रेक्काणः' },
    pronunciation: 'DREK-kah-nuh',
    shortDef: 'The D3 divisional chart — each sign split into three 10° parts for sibling/courage analysis.',
    fullDef: 'Drekkana (D3) is a divisional chart where each 30° sign is divided into three 10° portions. The 1st decanate maps to the sign itself, the 2nd to the 5th sign from it, and the 3rd to the 9th sign. Traditionally used to analyze siblings, courage, and short journeys. It also provides supplementary information about the native\'s initiative and self-effort.',
    westernEquivalent: 'Decanate / Decan',
    category: 'kundali',
    relatedTerms: ['varga', 'navamsha', 'rashi'],
  },
  {
    id: 'varga',
    term: { en: 'Varga', hi: 'वर्ग', sa: 'वर्गः' },
    pronunciation: 'VUHR-guh',
    shortDef: 'A divisional chart — sub-divisions of signs that reveal specific life areas in detail.',
    fullDef: 'Varga charts (also called Amsha or divisional charts) are derived by subdividing each sign into smaller portions and remapping them. The main birth chart (D1/Rashi) is supplemented by 15 standard Vargas: D2 (Hora/wealth), D3 (Drekkana/siblings), D7 (Saptamsha/children), D9 (Navamsha/marriage), D10 (Dashamsha/career), D12 (Dwadashamsha/parents), and others up to D60. Each provides focused insight into a specific life domain, like zooming into a section of the birth chart.',
    westernEquivalent: 'Harmonic Chart',
    category: 'kundali',
    relatedTerms: ['navamsha', 'drekkana', 'kundali'],
  },
  {
    id: 'sphuta',
    term: { en: 'Sphuta', hi: 'स्फुट', sa: 'स्फुटः' },
    pronunciation: 'SFOO-tuh',
    shortDef: 'A corrected/exact planetary longitude — the precise degree-minute-second position.',
    fullDef: 'Sphuta means "corrected" or "exact" and refers to the precisely computed longitude of a planet after applying all corrections (ayanamsha, equation of center, etc.). In classical Jyotish, various Sphutas are calculated: Graha Sphuta (planet positions), Lagna Sphuta (exact ascendant), Yogi Sphuta (auspicious degree), Avayogi Sphuta (inauspicious degree), and Bhrigu Bindu (midpoint of Rahu and Moon). These exact degrees are crucial for divisional chart computation.',
    westernEquivalent: 'Exact Planetary Position (Longitude)',
    category: 'kundali',
    relatedTerms: ['kundali', 'graha', 'ayanamsha'],
  },
  {
    id: 'ashtakavarga',
    term: { en: 'Ashtakavarga', hi: 'अष्टकवर्ग', sa: 'अष्टकवर्गः' },
    pronunciation: 'uhsh-tuh-kuh-VUHR-guh',
    shortDef: 'An 8-source scoring system rating each sign\'s strength from 0-8 benefic points.',
    fullDef: 'Ashtakavarga is a unique Vedic scoring system where each of the 7 planets and the Lagna contribute benefic (bindus) or malefic (rekhas) points to every sign. Each planet gets a score from 0-8 in each sign. The aggregate (Sarvashtakavarga) shows which signs are generally strong (high points) or weak (low points) in a chart. Transiting planets give better results when passing through signs with higher Ashtakavarga scores. It quantifies planetary support in a way no Western technique replicates.',
    westernEquivalent: 'Benefic Point Scoring System',
    category: 'kundali',
    relatedTerms: ['kundali', 'graha', 'rashi'],
  },
  {
    id: 'bhava_chalit',
    term: { en: 'Bhava Chalit', hi: 'भाव चलित', sa: 'भावचलितम्' },
    pronunciation: 'BHAH-vuh CHAH-lit',
    shortDef: 'The house-shifted chart — adjusts planet placement based on actual house cusps.',
    fullDef: 'Bhava Chalit is a chart where planets are placed according to the actual house cusp boundaries rather than the equal-sign system used in the Rashi chart. Because the Lagna can fall at any degree within a sign, some planets near house boundaries may shift from one house to another in the Bhava Chalit. This chart is considered more accurate for house-based predictions (which house a planet influences), while the Rashi chart is used for sign-based analysis (dignity, aspects).',
    westernEquivalent: 'House-Based Chart (similar to Placidus)',
    category: 'kundali',
    relatedTerms: ['bhava', 'lagna', 'kundali'],
  },
  {
    id: 'divisional_chart',
    term: { en: 'Divisional Chart', hi: 'वर्ग चार्ट', sa: 'वर्गचक्रम्' },
    pronunciation: 'dih-VIH-zhuh-nul chart',
    shortDef: 'A sub-chart derived by dividing signs — zooms into specific life areas.',
    fullDef: 'Divisional charts (Varga charts) are derived charts created by mathematically subdividing each zodiac sign and remapping the portions. The D9 (Navamsha) divides each sign into 9 parts, the D10 (Dashamsha) into 10, and so on up to D60. Each divisional chart focuses on a specific life domain: D9 for marriage, D10 for career, D7 for children, D12 for parents. A planet that is strong in both the birth chart (D1) and the relevant divisional chart is most likely to deliver its promise in that life area.',
    westernEquivalent: 'Harmonic Chart',
    category: 'kundali',
    relatedTerms: ['varga', 'navamsha', 'drekkana'],
  },

  // --- DASHA (6) ---
  {
    id: 'dasha',
    term: { en: 'Dasha', hi: 'दशा', sa: 'दशा' },
    pronunciation: 'DUH-shah',
    shortDef: "A planetary time period — each planet rules a chapter of your life.",
    fullDef: "Dasha is Vedic astrology's unique timing system where specific planets sequentially govern chapters of a person's life. Unlike Western astrology's transits (which overlay current sky positions onto the birth chart), Dashas are an unfolding sequence determined at birth by the Moon's nakshatra position. During a planet's Dasha, that planet's themes, house rulerships, and condition in the birth chart become activated. The most widely used system (Vimshottari) spans 120 years across 9 planetary periods.",
    westernEquivalent: 'Planetary Time Period (no Western equivalent)',
    category: 'dasha',
    relatedTerms: ['mahadasha', 'antardasha', 'vimshottari', 'nakshatra'],
  },
  {
    id: 'mahadasha',
    term: { en: 'Mahadasha', hi: 'महादशा', sa: 'महादशा' },
    pronunciation: 'muh-HAH-duh-shah',
    shortDef: 'The major planetary period — the dominant life chapter lasting 6-20 years.',
    fullDef: "Mahadasha is the major period in the Dasha system. In Vimshottari Dasha, each of the 9 planets rules a Mahadasha of fixed length: Sun (6 years), Moon (10), Mars (7), Rahu (18), Jupiter (16), Saturn (19), Mercury (17), Ketu (7), Venus (20). The Mahadasha lord's condition in the birth chart — its sign, house, aspects, and dignity — strongly colors the entire period. Transitions between Mahadashas (Dasha Sandhi) often coincide with significant life shifts.",
    westernEquivalent: 'Major Planetary Period',
    category: 'dasha',
    relatedTerms: ['dasha', 'antardasha', 'vimshottari', 'dasha_sandhi'],
  },
  {
    id: 'antardasha',
    term: { en: 'Antardasha', hi: 'अन्तर्दशा', sa: 'अन्तर्दशा' },
    pronunciation: 'UHN-tuhr-duh-shah',
    shortDef: 'The sub-period within a Mahadasha — a finer timing layer lasting months to years.',
    fullDef: "Antardasha (also called Bhukti) is the sub-period within a Mahadasha. Each Mahadasha is divided into 9 Antardashas, one for each planet, proportionally distributed. For example, within Jupiter Mahadasha (16 years), the Jupiter-Jupiter Antardasha is ~2.5 years, Jupiter-Saturn is ~2.7 years, etc. The Antardasha lord modifies the Mahadasha theme — Jupiter Mahadasha with Mars Antardasha activates both Jupiter's wisdom themes and Mars's action/conflict themes simultaneously.",
    westernEquivalent: 'Sub-Period',
    category: 'dasha',
    relatedTerms: ['dasha', 'mahadasha', 'pratyantar'],
  },
  {
    id: 'pratyantar',
    term: { en: 'Pratyantar Dasha', hi: 'प्रत्यन्तर दशा', sa: 'प्रत्यन्तरदशा' },
    pronunciation: 'PRUHT-yuhn-tuhr DUH-shah',
    shortDef: 'The sub-sub-period — a third timing layer lasting weeks to months.',
    fullDef: 'Pratyantar Dasha is the third level of the Dasha hierarchy, subdividing each Antardasha into 9 further periods. At this level, timing becomes very precise — each Pratyantar lasts from a few weeks to a few months. Astrologers use this level to pinpoint specific events within a broader period. For extremely precise timing, even finer levels exist (Sookshma and Prana Dasha), though these are less commonly used.',
    westernEquivalent: 'Sub-Sub-Period',
    category: 'dasha',
    relatedTerms: ['dasha', 'antardasha', 'mahadasha'],
  },
  {
    id: 'vimshottari',
    term: { en: 'Vimshottari', hi: 'विंशोत्तरी', sa: 'विंशोत्तरी' },
    pronunciation: 'vim-SHOHT-uh-ree',
    shortDef: 'The 120-year Dasha system — the most widely used planetary timing cycle.',
    fullDef: "Vimshottari Dasha is the most commonly used Dasha system, spanning 120 years (vimshottari = \"one hundred and twenty\"). The starting point is determined by the Moon's nakshatra at birth — each of the 27 nakshatras is ruled by one of the 9 planets, and the proportion of nakshatra already traversed by the Moon determines how much of the first Dasha has elapsed at birth. The sequence is fixed: Ketu, Venus, Sun, Moon, Mars, Rahu, Jupiter, Saturn, Mercury.",
    westernEquivalent: '120-Year Planetary Cycle',
    category: 'dasha',
    relatedTerms: ['dasha', 'mahadasha', 'nakshatra'],
  },
  {
    id: 'dasha_sandhi',
    term: { en: 'Dasha Sandhi', hi: 'दशा सन्धि', sa: 'दशासन्धिः' },
    pronunciation: 'DUH-shah SUHN-dhee',
    shortDef: 'The transition zone between two Dashas — a period of change and adjustment.',
    fullDef: 'Dasha Sandhi is the junction period when one Dasha is ending and the next is beginning. Like the transition between seasons, this period (typically spanning a few months around the changeover date) can bring uncertainty, significant life changes, or a noticeable shift in focus and circumstances. The magnitude of the shift depends on how different the two Dasha lords are — a transition from Jupiter to Saturn represents a more dramatic shift than Moon to Mars.',
    westernEquivalent: 'Period Transition',
    category: 'dasha',
    relatedTerms: ['dasha', 'mahadasha'],
  },

  // --- YOGA (7) ---
  {
    id: 'yoga_combination',
    term: { en: 'Yoga (Combination)', hi: 'योग', sa: 'योगः' },
    pronunciation: 'YOH-guh',
    shortDef: 'A specific planetary combination in a birth chart that produces distinct life effects.',
    fullDef: 'In Kundali analysis, Yoga refers to specific combinations of planets, signs, and houses that produce notable effects. Unlike the Panchang Yoga (which is a daily Sun-Moon calculation), chart Yogas are permanent features of a birth chart. Hundreds are catalogued in classical texts. They range from highly auspicious (Raja Yoga = power/authority, Dhana Yoga = wealth) to challenging (Kemadruma = emotional isolation, Daridra = financial difficulty). A chart typically has multiple yogas active simultaneously.',
    westernEquivalent: 'Planetary Configuration / Aspect Pattern',
    category: 'yoga',
    relatedTerms: ['raja_yoga', 'dhana_yoga', 'dosha', 'kundali'],
  },
  {
    id: 'dosha',
    term: { en: 'Dosha', hi: 'दोष', sa: 'दोषः' },
    pronunciation: 'DOH-shuh',
    shortDef: 'A challenging planetary condition in a chart — an area requiring conscious attention.',
    fullDef: 'Dosha means "fault" or "blemish" and refers to challenging planetary configurations in a birth chart. Common Doshas include Manglik/Kuja Dosha (Mars in specific houses affecting marriage), Kaal Sarpa (all planets between Rahu-Ketu axis), and Pitru Dosha (ancestral karma indicators). Important: Doshas are not "curses" — they are areas where extra awareness is needed. Most Doshas have cancellation conditions (Bhanga) that reduce or eliminate their effects.',
    westernEquivalent: 'Challenging Aspect / Hard Configuration',
    category: 'yoga',
    relatedTerms: ['yoga_combination', 'manglik', 'kundali'],
  },
  {
    id: 'raja_yoga',
    term: { en: 'Raja Yoga', hi: 'राज योग', sa: 'राजयोगः' },
    pronunciation: 'RAH-juh YOH-guh',
    shortDef: 'A "royal combination" — planetary placements indicating authority, success, or leadership.',
    fullDef: 'Raja Yoga ("royal combination") forms when lords of Kendra houses (1, 4, 7, 10) and Trikona houses (1, 5, 9) are connected through conjunction, mutual aspect, or exchange. The combination of angular power (Kendra) and fortune (Trikona) produces exceptional results in career, authority, and social status. The strength depends on the specific houses involved, the dignity of the planets, and whether they are activated by the current Dasha period.',
    westernEquivalent: 'Grand Trine / Angular Configurations',
    category: 'yoga',
    relatedTerms: ['yoga_combination', 'kundali', 'dasha'],
  },
  {
    id: 'dhana_yoga',
    term: { en: 'Dhana Yoga', hi: 'धन योग', sa: 'धनयोगः' },
    pronunciation: 'DHUH-nuh YOH-guh',
    shortDef: 'A wealth combination — planetary connections indicating financial prosperity.',
    fullDef: 'Dhana Yoga forms through connections between lords of wealth houses (2nd = accumulated wealth, 11th = gains) and supporting houses (1st = self, 5th = speculative gains, 9th = fortune). Multiple Dhana Yogas in a chart amplify wealth potential. However, the timing of wealth manifestation depends on the Dasha — a strong Dhana Yoga may only produce results during the Dasha of the involved planet.',
    westernEquivalent: 'Wealth Configuration',
    category: 'yoga',
    relatedTerms: ['yoga_combination', 'raja_yoga', 'kundali'],
  },
  {
    id: 'manglik',
    term: { en: 'Manglik Dosha', hi: 'मांगलिक दोष', sa: 'माङ्गलिकदोषः' },
    pronunciation: 'MAHNG-lik DOH-shuh',
    shortDef: 'Mars in houses 1, 2, 4, 7, 8, or 12 — traditionally affects marriage compatibility.',
    fullDef: "Manglik Dosha (also Kuja Dosha) occurs when Mars occupies the 1st, 2nd, 4th, 7th, 8th, or 12th house from the Lagna, Moon, or Venus. Mars's aggressive energy in these partnership-sensitive houses is traditionally believed to create friction in marriage. However, many cancellation conditions exist: both partners being Manglik cancels the effect, Mars in its own sign or exaltation reduces severity, and age past 28 is traditionally said to reduce the dosha. It is one of the most checked factors in Kundali matching.",
    westernEquivalent: 'Mars affliction to partnership houses',
    category: 'yoga',
    relatedTerms: ['dosha', 'ashta_kuta', 'kundali'],
  },
  {
    id: 'sade_sati',
    term: { en: 'Sade Sati', hi: 'साढ़े साती', sa: 'साडेसाति' },
    pronunciation: 'SAH-day SAH-tee',
    shortDef: "Saturn's 7.5-year transit over your Moon sign — a period of deep transformation.",
    fullDef: "Sade Sati is the 7.5-year period when Saturn transits through the sign before, the sign of, and the sign after your natal Moon. Since Saturn takes ~2.5 years per sign, the total duration is ~7.5 years (sade sati = \"seven and a half\"). It occurs 2-3 times in a lifetime and is associated with emotional challenges, responsibility, and deep personal growth. The second pass (12th house phase) is considered most intense. Despite its reputation, Sade Sati often produces lasting positive transformation through pressure.",
    westernEquivalent: 'Saturn Conjunct Moon Transit (extended)',
    category: 'yoga',
    relatedTerms: ['graha', 'rashi', 'kundali'],
  },
  {
    id: 'pancha_mahapurusha',
    term: { en: 'Pancha Mahapurusha', hi: 'पंच महापुरुष', sa: 'पञ्चमहापुरुषः' },
    pronunciation: 'PUHN-chuh muh-HAH-poo-roo-shuh',
    shortDef: 'Five "great person" yogas — Mars, Mercury, Jupiter, Venus, or Saturn in own/exalted sign in a Kendra.',
    fullDef: 'Pancha Mahapurusha Yogas are five powerful combinations where a non-luminary planet (Mars, Mercury, Jupiter, Venus, or Saturn) is in its own sign or exaltation sign AND placed in a Kendra house (1, 4, 7, or 10). The five yogas are: Ruchaka (Mars), Bhadra (Mercury), Hamsa (Jupiter), Malavya (Venus), and Shasha (Saturn). Each grants distinctive qualities related to the planet — Hamsa gives wisdom and spiritual inclination, Ruchaka gives physical strength and leadership.',
    westernEquivalent: 'Planet in Dignity in Angular House',
    category: 'yoga',
    relatedTerms: ['yoga_combination', 'raja_yoga', 'graha'],
  },

  // --- GENERAL (6) ---
  {
    id: 'jyotish',
    term: { en: 'Jyotish', hi: 'ज्योतिष', sa: 'ज्योतिषम्' },
    pronunciation: 'JOH-tish',
    shortDef: 'Vedic astrology — the ancient Indian system of astronomical observation and interpretation.',
    fullDef: 'Jyotish (from jyoti = "light" + isha = "lord") is the traditional Hindu system of astrology, one of the six Vedangas (limbs of the Vedas). It encompasses three branches: Siddhanta (astronomical computation), Samhita (mundane astrology, weather, omens), and Hora (predictive astrology, birth charts). Jyotish uses the sidereal zodiac, the Dasha timing system, and 27 Nakshatras — features absent from Western astrology — providing what practitioners consider a higher-resolution framework for understanding time and personality.',
    westernEquivalent: 'Vedic / Hindu / Indian Astrology',
    category: 'general',
    relatedTerms: ['kundali', 'panchang', 'nakshatra', 'dasha'],
  },
  {
    id: 'muhurta',
    term: { en: 'Muhurta', hi: 'मुहूर्त', sa: 'मुहूर्तः' },
    pronunciation: 'moo-HOOR-tuh',
    shortDef: 'Electional astrology — finding the ideal time to begin important activities.',
    fullDef: "Muhurta is the branch of Jyotish concerned with selecting auspicious moments for important activities: starting a business, marriage ceremony, house construction, travel, etc. It evaluates multiple factors simultaneously: tithi, nakshatra, yoga, karana, planetary hora, Rahu Kaal, Yamaganda, and the specific activity's requirements. A \"Muhurta\" is also a Vedic time unit (~48 minutes), and 30 Muhurtas make up a full day from sunrise to sunrise.",
    westernEquivalent: 'Electional Astrology / Auspicious Timing',
    category: 'general',
    relatedTerms: ['panchang', 'tithi', 'nakshatra', 'hora'],
  },
  {
    id: 'guna_milan',
    term: { en: 'Guna Milan', hi: 'गुण मिलान', sa: 'गुणमिलनम्' },
    pronunciation: 'GOO-nuh mee-LAHN',
    shortDef: 'The 36-point compatibility scoring system used in Vedic marriage matching.',
    fullDef: "Guna Milan (also called Kundali Milan) is the Vedic compatibility assessment for marriage, scoring up to 36 points across 8 factors (Ashta Kuta). The assessment is based primarily on the Moon's nakshatra and rashi in both charts. Scores above 18 are considered acceptable, above 24 good, and above 28 excellent. While the numerical score provides a quick assessment, experienced practitioners also examine planetary aspects, Dasha alignment, and specific Doshas for a complete compatibility picture.",
    westernEquivalent: 'Synastry / Compatibility Analysis',
    category: 'general',
    relatedTerms: ['ashta_kuta', 'nakshatra', 'rashi', 'manglik'],
  },
  {
    id: 'ashta_kuta',
    term: { en: 'Ashta Kuta', hi: 'अष्ट कूट', sa: 'अष्टकूटम्' },
    pronunciation: 'UHSH-tuh KOO-tuh',
    shortDef: 'The 8 compatibility factors in Guna Milan — from temperament to vital energy.',
    fullDef: 'Ashta Kuta ("eight peaks") is the framework of 8 specific factors evaluated in Guna Milan: Varna (spiritual compatibility, 1 point), Vashya (mutual attraction, 2 points), Tara (birth star harmony, 3 points), Yoni (instinctive compatibility, 4 points), Graha Maitri (planetary friendship, 5 points), Gana (temperament match, 6 points), Bhakoot (emotional compatibility, 7 points), and Nadi (vital energy compatibility, 8 points). Each factor tests a different dimension of relationship compatibility, totaling 36 points maximum.',
    westernEquivalent: 'Eight-Factor Compatibility Assessment',
    category: 'general',
    relatedTerms: ['guna_milan', 'nakshatra', 'rashi'],
  },
  {
    id: 'vedic',
    term: { en: 'Vedic', hi: 'वैदिक', sa: 'वैदिकम्' },
    pronunciation: 'VAY-dik',
    shortDef: 'Relating to the Vedas — the foundational texts of Indian knowledge systems.',
    fullDef: 'Vedic refers to anything derived from or related to the Vedas, the oldest layer of Sanskrit literature and the foundational scriptures of Hinduism. The four Vedas (Rig, Yajur, Sama, Atharva) were composed between 1500-500 BCE and contain hymns, philosophy, and practical knowledge including astronomy and mathematics. "Vedic astrology" (Jyotish) is one of six Vedangas — auxiliary disciplines considered essential for understanding the Vedas. The term positions this knowledge system as one of the world\'s oldest continuous intellectual traditions.',
    westernEquivalent: 'Classical Indian / Ancient Sanskrit',
    category: 'general',
    relatedTerms: ['jyotish'],
  },
  {
    id: 'sidereal_tropical',
    term: { en: 'Sidereal vs Tropical', hi: 'निरयन बनाम सायन', sa: 'निरयनं सायनं च' },
    pronunciation: 'sy-DEER-ee-ul / TROP-ih-kul',
    shortDef: 'Two zodiac systems — sidereal (fixed stars, Vedic) vs tropical (equinox-anchored, Western).',
    fullDef: "The sidereal zodiac aligns signs with their namesake constellations using fixed star references. The tropical zodiac anchors 0° Aries to the spring equinox point, which precesses westward through the constellations over a ~26,000-year cycle. When the systems were designed (~285 AD), they were aligned. Today, the tropical zodiac is ~24° ahead of the sidereal, meaning most people's Western sign placements are one sign ahead of their Vedic placements. Neither system is \"wrong\" — they measure different things. Sidereal tracks your relationship to the fixed stars; tropical tracks your relationship to Earth's seasonal cycle.",
    westernEquivalent: 'Fixed-Star vs Equinox-Based Zodiac',
    category: 'general',
    relatedTerms: ['ayanamsha', 'rashi', 'jyotish'],
  },
];

// Lookup helpers
export function getGlossaryEntry(id: string): GlossaryEntry | undefined {
  return GLOSSARY.find(e => e.id === id);
}

export function getGlossaryByCategory(category: GlossaryEntry['category']): GlossaryEntry[] {
  return GLOSSARY.filter(e => e.category === category);
}

export function searchGlossary(query: string): GlossaryEntry[] {
  const q = query.toLowerCase();
  return GLOSSARY.filter(e =>
    e.id.includes(q) ||
    e.term.en.toLowerCase().includes(q) ||
    e.shortDef.toLowerCase().includes(q)
  );
}
