/**
 * Runtime merger that overlays per-locale `muhurta-{locale}-overlay.json`
 * files onto MUHURTA_TYPES, populating `.{locale}` fields on each
 * LocaleText object without mutating muhurta-types.ts.
 *
 * Same pattern as festival-details-with-overlay.ts. Overlay JSONs are
 * generated by scripts/translate-muhurta-via-gemini.py.
 *
 * Switch consumers from `from '@/lib/constants/muhurta-types'` to
 * `from '@/lib/constants/muhurta-types-with-overlay'`. Type and
 * function exports are re-exported unchanged.
 */
import {
  MUHURTA_TYPES as RAW_MUHURTA_TYPES,
  type MuhurtaTypeInfo,
} from './muhurta-types';

import taOverlayRaw from './muhurta-ta-overlay.json';
import teOverlayRaw from './muhurta-te-overlay.json';
import bnOverlayRaw from './muhurta-bn-overlay.json';
import guOverlayRaw from './muhurta-gu-overlay.json';
import knOverlayRaw from './muhurta-kn-overlay.json';
import maiOverlayRaw from './muhurta-mai-overlay.json';
import mrOverlayRaw from './muhurta-mr-overlay.json';

type OverlayLocale = 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mai' | 'mr';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['ta', 'te', 'bn', 'gu', 'kn', 'mai', 'mr'];

const TRANSLATABLE_FIELDS: ReadonlyArray<keyof MuhurtaTypeInfo> = [
  'name',
  'subtitle',
  'description',
];

function attachToLocaleText(field: unknown, slug: string, fieldName: string): void {
  if (!field || typeof field !== 'object') return;
  const ft = field as Record<string, string | undefined>;
  const overlayKey = `${slug}.${fieldName}`;
  for (const locale of OVERLAY_LOCALES) {
    if (typeof ft[locale] === 'string' && ft[locale]!.trim()) continue;
    const overlayVal = OVERLAYS[locale][overlayKey];
    if (typeof overlayVal === 'string' && overlayVal.trim()) {
      ft[locale] = overlayVal;
    }
  }
}

function applyOverlays(entry: MuhurtaTypeInfo): MuhurtaTypeInfo {
  const slug = entry.slug;
  const cloned: Record<string, unknown> = { ...entry };
  for (const field of TRANSLATABLE_FIELDS) {
    const v = cloned[field as string];
    if (!v || typeof v !== 'object') continue;
    const clonedField = { ...(v as Record<string, unknown>) };
    attachToLocaleText(clonedField, slug, field as string);
    cloned[field as string] = clonedField;
  }
  return cloned as unknown as MuhurtaTypeInfo;
}

export const MUHURTA_TYPES: readonly MuhurtaTypeInfo[] = RAW_MUHURTA_TYPES.map(applyOverlays);

export function getMuhurtaType(slug: string): MuhurtaTypeInfo | undefined {
  return MUHURTA_TYPES.find((t) => t.slug === slug);
}

export function getMuhurtaTypeSlugs(): string[] {
  return MUHURTA_TYPES.map((t) => t.slug);
}

// Re-export types unchanged.
export type {
  MuhurtaTypeFAQ,
  MuhurtaTypeDate,
  MuhurtaTypeInfo,
} from './muhurta-types';
