/**
 * Traditional name syllables for each Nakshatra pada
 * Each nakshatra has 4 padas, each pada has a specific starting syllable
 */

export interface NakshatraSyllable {
  nakshatraId: number;
  pada: number;
  syllables: { en: string; hi: string; sa: string }[];
}

// Nakshatra → Pada → Starting syllables for baby names
export const NAKSHATRA_SYLLABLES: Record<number, { en: string; hi: string }[]> = {
  1:  [{ en: 'Chu', hi: 'चू' }, { en: 'Che', hi: 'चे' }, { en: 'Cho', hi: 'चो' }, { en: 'La', hi: 'ला' }],
  2:  [{ en: 'Li', hi: 'ली' }, { en: 'Lu', hi: 'लू' }, { en: 'Le', hi: 'ले' }, { en: 'Lo', hi: 'लो' }],
  3:  [{ en: 'A', hi: 'अ' }, { en: 'I', hi: 'ई' }, { en: 'U', hi: 'उ' }, { en: 'E', hi: 'ए' }],
  4:  [{ en: 'O', hi: 'ओ' }, { en: 'Va', hi: 'वा' }, { en: 'Vi', hi: 'वि' }, { en: 'Vu', hi: 'वु' }],
  5:  [{ en: 'Ve', hi: 'वे' }, { en: 'Vo', hi: 'वो' }, { en: 'Ka', hi: 'का' }, { en: 'Ki', hi: 'की' }],
  6:  [{ en: 'Ku', hi: 'कु' }, { en: 'Gha', hi: 'घ' }, { en: 'Ng', hi: 'ङ' }, { en: 'Na', hi: 'ना' }],
  7:  [{ en: 'Ke', hi: 'के' }, { en: 'Ko', hi: 'को' }, { en: 'Ha', hi: 'हा' }, { en: 'Hi', hi: 'ही' }],
  8:  [{ en: 'Hu', hi: 'हू' }, { en: 'He', hi: 'हे' }, { en: 'Ho', hi: 'हो' }, { en: 'Da', hi: 'डा' }],
  9:  [{ en: 'Di', hi: 'डी' }, { en: 'Du', hi: 'डू' }, { en: 'De', hi: 'डे' }, { en: 'Do', hi: 'डो' }],
  10: [{ en: 'Ma', hi: 'मा' }, { en: 'Mi', hi: 'मी' }, { en: 'Mu', hi: 'मू' }, { en: 'Me', hi: 'मे' }],
  11: [{ en: 'Mo', hi: 'मो' }, { en: 'Ta', hi: 'टा' }, { en: 'Ti', hi: 'टी' }, { en: 'Tu', hi: 'टू' }],
  12: [{ en: 'Te', hi: 'टे' }, { en: 'To', hi: 'टो' }, { en: 'Pa', hi: 'पा' }, { en: 'Pi', hi: 'पी' }],
  13: [{ en: 'Pu', hi: 'पू' }, { en: 'Sha', hi: 'ष' }, { en: 'Na', hi: 'ण' }, { en: 'Tha', hi: 'ठ' }],
  14: [{ en: 'Pe', hi: 'पे' }, { en: 'Po', hi: 'पो' }, { en: 'Ra', hi: 'रा' }, { en: 'Ri', hi: 'री' }],
  15: [{ en: 'Ru', hi: 'रू' }, { en: 'Re', hi: 'रे' }, { en: 'Ro', hi: 'रो' }, { en: 'Ta', hi: 'ता' }],
  16: [{ en: 'Ti', hi: 'ती' }, { en: 'Tu', hi: 'तू' }, { en: 'Te', hi: 'ते' }, { en: 'To', hi: 'तो' }],
  17: [{ en: 'Na', hi: 'ना' }, { en: 'Ni', hi: 'नी' }, { en: 'Nu', hi: 'नू' }, { en: 'Ne', hi: 'ने' }],
  18: [{ en: 'No', hi: 'नो' }, { en: 'Ya', hi: 'या' }, { en: 'Yi', hi: 'यी' }, { en: 'Yu', hi: 'यू' }],
  19: [{ en: 'Ye', hi: 'ये' }, { en: 'Yo', hi: 'यो' }, { en: 'Bha', hi: 'भा' }, { en: 'Bhi', hi: 'भी' }],
  20: [{ en: 'Bhu', hi: 'भू' }, { en: 'Dha', hi: 'धा' }, { en: 'Pha', hi: 'फा' }, { en: 'Dha', hi: 'ढा' }],
  21: [{ en: 'Bhe', hi: 'भे' }, { en: 'Bho', hi: 'भो' }, { en: 'Ja', hi: 'जा' }, { en: 'Ji', hi: 'जी' }],
  22: [{ en: 'Ju/Khi', hi: 'खी' }, { en: 'Je/Khu', hi: 'खू' }, { en: 'Jo/Khe', hi: 'खे' }, { en: 'Gha', hi: 'खो' }],
  23: [{ en: 'Ga', hi: 'गा' }, { en: 'Gi', hi: 'गी' }, { en: 'Gu', hi: 'गू' }, { en: 'Ge', hi: 'गे' }],
  24: [{ en: 'Go', hi: 'गो' }, { en: 'Sa', hi: 'सा' }, { en: 'Si', hi: 'सी' }, { en: 'Su', hi: 'सू' }],
  25: [{ en: 'Se', hi: 'से' }, { en: 'So', hi: 'सो' }, { en: 'Da', hi: 'दा' }, { en: 'Di', hi: 'दी' }],
  26: [{ en: 'Du', hi: 'दू' }, { en: 'Tha', hi: 'थ' }, { en: 'Jha', hi: 'झ' }, { en: 'Da', hi: 'ञ' }],
  27: [{ en: 'De', hi: 'दे' }, { en: 'Do', hi: 'दो' }, { en: 'Cha', hi: 'चा' }, { en: 'Chi', hi: 'ची' }],
};

// Sample names for each syllable group (curated)
export const SAMPLE_NAMES: Record<string, string[]> = {
  'Chu': ['Chudamani', 'Chulbuli'],
  'Che': ['Chetana', 'Chetan'],
  'Cho': ['Chokhi', 'Chola'],
  'La': ['Lakshmi', 'Lata', 'Lavanya', 'Lalita'],
  'Li': ['Lila', 'Lilavati'],
  'Lu': ['Lubdha'],
  'Le': ['Leela', 'Lekha'],
  'Lo': ['Lokesh', 'Lochana'],
  'A': ['Arjun', 'Aarav', 'Aanya', 'Ananya', 'Ashwin', 'Aditya', 'Aditi'],
  'I': ['Isha', 'Ishaan', 'Indira'],
  'U': ['Uma', 'Uday', 'Udaya'],
  'E': ['Ekta', 'Esha'],
  'O': ['Om', 'Omkar', 'Ojas'],
  'Va': ['Varun', 'Vasundhara', 'Vansh', 'Vani'],
  'Vi': ['Virat', 'Vidya', 'Vivaan', 'Vinay'],
  'Vu': ['Vruddhi'],
  'Ve': ['Vedant', 'Veena', 'Veer'],
  'Vo': ['Vojit'],
  'Ka': ['Karan', 'Kavya', 'Kashvi', 'Kartik'],
  'Ki': ['Kiara', 'Kishan', 'Kiran'],
  'Ku': ['Kunal', 'Kumari', 'Kundan'],
  'Ke': ['Keshav', 'Ketaki'],
  'Ko': ['Komal', 'Kovid'],
  'Ha': ['Harsh', 'Harini', 'Hansika'],
  'Hi': ['Hitesh', 'Himani', 'Hiral'],
  'Hu': ['Humira'],
  'He': ['Hema', 'Hemant'],
  'Ho': ['Homi'],
  'Da': ['Daksh', 'Darsh', 'Darpan'],
  'Ma': ['Manish', 'Manvi', 'Madhav', 'Maya'],
  'Mi': ['Mihir', 'Mira', 'Milan'],
  'Mu': ['Mukesh', 'Mukti', 'Mudit'],
  'Me': ['Meera', 'Medha', 'Megha'],
  'Mo': ['Mohit', 'Moksha', 'Mohan'],
  'Ta': ['Tanvi', 'Tarun', 'Tara'],
  'Ti': ['Tithi', 'Tirth'],
  'Tu': ['Tulsi', 'Tushar'],
  'Te': ['Tej', 'Tejas'],
  'To': ['Toshit'],
  'Pa': ['Pari', 'Parth', 'Pallavi', 'Param'],
  'Pi': ['Piyush', 'Pinki'],
  'Pu': ['Puja', 'Pulkit', 'Puneet', 'Pushkar'],
  'Pe': ['Prem'],
  'Po': ['Pooja'],
  'Ra': ['Raghav', 'Radha', 'Rajan', 'Raksha'],
  'Ri': ['Rishi', 'Richa', 'Ridhi', 'Ritik'],
  'Ru': ['Rudra', 'Ruchi', 'Rupal'],
  'Re': ['Reema', 'Revant'],
  'Ro': ['Rohan', 'Roshni', 'Roma'],
  'Na': ['Navya', 'Naman', 'Nandini', 'Nakul'],
  'Ni': ['Nikhil', 'Nisha', 'Nidhi', 'Nirav'],
  'Nu': ['Nutan'],
  'Ne': ['Neha', 'Neel'],
  'No': ['Nosheen'],
  'Ya': ['Yash', 'Yamini', 'Yashvi'],
  'Yi': ['Yitendra'],
  'Yu': ['Yuvan', 'Yukti'],
  'Ye': ['Yeshoda'],
  'Yo': ['Yogesh', 'Yogini', 'Yogi'],
  'Bha': ['Bhavya', 'Bharat', 'Bhavana'],
  'Bhi': ['Bhima'],
  'Bhu': ['Bhuvan', 'Bhumi'],
  'Dha': ['Dhanvi', 'Dharma', 'Dhanya'],
  'Bhe': ['Bhekhar'],
  'Bho': ['Bhola'],
  'Ja': ['Jayant', 'Jaya', 'Janvi'],
  'Ji': ['Jigna', 'Jiya', 'Jitesh'],
  'Ga': ['Gaurav', 'Garima', 'Gautam'],
  'Gi': ['Girish', 'Gita'],
  'Gu': ['Gunjan', 'Gulab'],
  'Ge': ['Geeta'],
  'Go': ['Govind', 'Gopal'],
  'Sa': ['Saanvi', 'Sahil', 'Sakshi', 'Sameer'],
  'Si': ['Siddharth', 'Simran', 'Sita'],
  'Su': ['Suraj', 'Sunita', 'Suresh', 'Sudha'],
  'Se': ['Seema'],
  'So': ['Sonal', 'Soham', 'Sonia'],
  'De': ['Dev', 'Deepak', 'Devika'],
  'Do': ['Dolly'],
  'Cha': ['Chandra', 'Chaitanya'],
  'Chi': ['Chinmay', 'Chitra'],
  'Sha': ['Shankar', 'Shanti', 'Shashi'],
  'Pha': ['Phalgun'],
};
