/**
 * Runtime merger that attaches per-locale `planet-in-house-verses-{locale}-overlay.json`
 * translations onto PLANET_HOUSE_VERSES' `verse` and `interpretation`
 * LocaleText fields, populating ta/te/bn/gu/kn/mai/mr without mutating
 * the source `planet-in-house-verses.ts`.
 *
 * Overlay JSONs are generated by
 * scripts/translate-planet-house-verses-via-gemini.py. Each is keyed by
 * `"<planetId>-<house>.<field>"` (e.g. `"0-1.verse"`,
 * `"4-9.interpretation"`).
 *
 * Consumers: switch
 *   import { PLANET_HOUSE_VERSES } from '@/lib/constants/planet-in-house-verses'
 * to
 *   import { PLANET_HOUSE_VERSES } from '@/lib/constants/planet-in-house-verses-with-overlay'
 *
 * Same lifecycle as the festival/puja/transit-articles overlay
 * mergers — spec docs/specs/2026-06-04-noindex-thin-translation-locales.md
 * state 2→3.
 */

import {
  PLANET_HOUSE_VERSES as RAW_PLANET_HOUSE_VERSES,
  type PlanetHouseVerse,
} from './planet-in-house-verses';

import taOverlayRaw from './planet-in-house-verses-ta-overlay.json';
import teOverlayRaw from './planet-in-house-verses-te-overlay.json';
import bnOverlayRaw from './planet-in-house-verses-bn-overlay.json';
import guOverlayRaw from './planet-in-house-verses-gu-overlay.json';
import knOverlayRaw from './planet-in-house-verses-kn-overlay.json';
import maiOverlayRaw from './planet-in-house-verses-mai-overlay.json';
import mrOverlayRaw from './planet-in-house-verses-mr-overlay.json';

type OverlayLocale = 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mai' | 'mr';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['ta', 'te', 'bn', 'gu', 'kn', 'mai', 'mr'];

function applyOverlay(entry: PlanetHouseVerse): PlanetHouseVerse {
  const key = `${entry.planetId}-${entry.house}`;
  const verse = { ...entry.verse } as Record<string, string>;
  const interpretation = { ...entry.interpretation } as Record<string, string>;
  for (const locale of OVERLAY_LOCALES) {
    const overlay = OVERLAYS[locale];
    const vKey = `${key}.verse`;
    const iKey = `${key}.interpretation`;
    if (overlay[vKey] && !verse[locale]) {
      verse[locale] = overlay[vKey];
    }
    if (overlay[iKey] && !interpretation[locale]) {
      interpretation[locale] = overlay[iKey];
    }
  }
  return {
    ...entry,
    verse: verse as PlanetHouseVerse['verse'],
    interpretation: interpretation as PlanetHouseVerse['interpretation'],
  };
}

export const PLANET_HOUSE_VERSES: readonly PlanetHouseVerse[] =
  RAW_PLANET_HOUSE_VERSES.map(applyOverlay);

export type { PlanetHouseVerse } from './planet-in-house-verses';
