/**
 * Runtime merger that overlays per-locale `puja-vidhi-{locale}-overlay.json`
 * files onto PUJA_VIDHIS, attaching translated strings to the nested
 * LocaleText fields (deity, sankalpa, samagri[].name, vidhiSteps[].title,
 * vidhiSteps[].description, mantras[].meaning, etc.) without mutating
 * the per-puja source TS files.
 *
 * Overlay JSONs are generated by scripts/translate-puja-vidhi-via-gemini.py.
 * Each is keyed by dotted+bracketed path matching what the extract walker
 * emitted:
 *   `diwali.deity`
 *   `diwali.samagri[3].name`
 *   `diwali.samagri[3].substitutions[0].item`
 *   `diwali.vidhiSteps[7].description`
 *   `diwali.mantras[0].meaning`
 *   `diwali.precautions[2]`
 *   `diwali.aarti.name`
 *
 * Sacred Devanagari + IAST mantra/aarti/stotra text are NOT in the
 * overlay corpus (the extract walker only emits LocaleText paths;
 * `mantras[i].devanagari` etc. are plain strings, so they're skipped).
 * They stay AS-IS, locale-independent.
 *
 * Consumers: switch
 *   import { PUJA_VIDHIS, getPujaVidhiBySlug } from '@/lib/constants/puja-vidhi'
 * to
 *   import { PUJA_VIDHIS, getPujaVidhiBySlug } from '@/lib/constants/puja-vidhi-with-overlay'
 *
 * Type imports from `@/lib/constants/puja-vidhi/types` stay unchanged
 * (overlay doesn't change shapes).
 *
 * Mirrors festival-details-with-overlay.ts; spec
 * docs/specs/2026-06-04-noindex-thin-translation-locales.md state 2→3.
 */

import {
  PUJA_VIDHIS as RAW_PUJA_VIDHIS,
  getPujaVidhiBySlug as rawGetPujaVidhiBySlug,
} from './puja-vidhi';
import type { PujaVidhi } from './puja-vidhi/types';

import taOverlayRaw from './puja-vidhi-ta-overlay.json';
import teOverlayRaw from './puja-vidhi-te-overlay.json';
import bnOverlayRaw from './puja-vidhi-bn-overlay.json';
import guOverlayRaw from './puja-vidhi-gu-overlay.json';
import knOverlayRaw from './puja-vidhi-kn-overlay.json';
import maiOverlayRaw from './puja-vidhi-mai-overlay.json';
import mrOverlayRaw from './puja-vidhi-mr-overlay.json';

type OverlayLocale = 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mai' | 'mr';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['ta', 'te', 'bn', 'gu', 'kn', 'mai', 'mr'];

/**
 * Walk a path like `samagri[3].substitutions[0].item` into an object,
 * returning the leaf object (the LocaleText). Returns null when any
 * segment misses — the overlay key references a path that doesn't
 * exist in this puja (stale overlay), which is a no-op at runtime.
 */
function resolveLocaleText(root: unknown, path: string): Record<string, string> | null {
  // Tokenise path. ".foo" or "[N]" segments.
  const tokens = path.match(/[^.[\]]+|\[\d+\]/g);
  if (!tokens) return null;
  let cur: unknown = root;
  for (const tok of tokens) {
    if (cur === null || typeof cur !== 'object') return null;
    if (tok.startsWith('[')) {
      const idx = Number(tok.slice(1, -1));
      if (!Array.isArray(cur) || idx >= cur.length) return null;
      cur = cur[idx];
    } else {
      cur = (cur as Record<string, unknown>)[tok];
    }
  }
  if (cur === null || typeof cur !== 'object' || Array.isArray(cur)) return null;
  // Must look like LocaleText: has a string `en` (the walker only
  // emits paths whose leaf is LocaleText; defensive check here keeps
  // a stale or malformed overlay key from corrupting an arbitrary
  // nested object).
  const obj = cur as Record<string, unknown>;
  if (typeof obj.en !== 'string') return null;
  return obj as Record<string, string>;
}

/**
 * Deep-clone the puja so we don't mutate the source TS constants.
 * Plain JSON.parse(JSON.stringify(x)) is fine here — puja-vidhi has
 * no functions, dates, or symbols anywhere in the shape.
 */
function clone(p: PujaVidhi): PujaVidhi {
  return JSON.parse(JSON.stringify(p));
}

function applyOverlays(slug: string, vidhi: PujaVidhi): PujaVidhi {
  const cloned = clone(vidhi);
  for (const locale of OVERLAY_LOCALES) {
    const overlay = OVERLAYS[locale];
    for (const [key, value] of Object.entries(overlay)) {
      if (!key.startsWith(`${slug}.`)) continue;
      if (typeof value !== 'string' || !value.trim()) continue;
      const path = key.slice(slug.length + 1);
      const target = resolveLocaleText(cloned, path);
      if (!target) continue;
      // Don't overwrite hand-authored values; only fill gaps.
      if (typeof target[locale] === 'string' && target[locale].trim()) continue;
      target[locale] = value;
    }
  }
  return cloned;
}

const merged: Record<string, PujaVidhi> = {};
for (const [slug, vidhi] of Object.entries(RAW_PUJA_VIDHIS)) {
  merged[slug] = applyOverlays(slug, vidhi);
}

export const PUJA_VIDHIS: Readonly<Record<string, PujaVidhi>> = merged;

export function getPujaVidhiBySlug(slug: string): PujaVidhi | undefined {
  // Forward to merged map. Don't fall back to raw — that would defeat
  // the overlay for any consumer that uses the helper.
  return merged[slug] ?? rawGetPujaVidhiBySlug(slug);
}

// Re-export types so a single import-path swap is enough.
export type {
  PujaVidhi,
  MantraDetail,
  VidhiStep,
  SamagriItem,
  AartiText,
  StotraReference,
  ParanaRule,
  MuhurtaWindowType,
} from './puja-vidhi/types';
