import { Rashi } from '@/types/panchang';

export const RASHIS: Rashi[] = [
  { id: 1, name: { en: 'Aries', hi: 'मेष', sa: 'मेषः', ta: 'மேஷம்' }, symbol: '♈', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः', ta: 'செவ்வாய்' }, startDeg: 0, endDeg: 30, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர' } },
  { id: 2, name: { en: 'Taurus', hi: 'वृषभ', sa: 'वृषभः', ta: 'ரிஷபம்' }, symbol: '♉', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः', ta: 'சுக்கிரன்' }, startDeg: 30, endDeg: 60, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர' } },
  { id: 3, name: { en: 'Gemini', hi: 'मिथुन', sa: 'मिथुनम्', ta: 'மிதுனம்' }, symbol: '♊', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः', ta: 'புதன்' }, startDeg: 60, endDeg: 90, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய' } },
  { id: 4, name: { en: 'Cancer', hi: 'कर्क', sa: 'कर्कटः', ta: 'கடகம்' }, symbol: '♋', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்' }, ruler: 'Moon', rulerName: { en: 'Moon', hi: 'चन्द्र', sa: 'चन्द्रः', ta: 'சந்திரன்' }, startDeg: 90, endDeg: 120, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர' } },
  { id: 5, name: { en: 'Leo', hi: 'सिंह', sa: 'सिंहः', ta: 'சிம்மம்' }, symbol: '♌', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு' }, ruler: 'Sun', rulerName: { en: 'Sun', hi: 'सूर्य', sa: 'सूर्यः', ta: 'சூரியன்' }, startDeg: 120, endDeg: 150, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர' } },
  { id: 6, name: { en: 'Virgo', hi: 'कन्या', sa: 'कन्या', ta: 'கன்னி' }, symbol: '♍', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः', ta: 'புதன்' }, startDeg: 150, endDeg: 180, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய' } },
  { id: 7, name: { en: 'Libra', hi: 'तुला', sa: 'तुला', ta: 'துலாம்' }, symbol: '♎', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः', ta: 'சுக்கிரன்' }, startDeg: 180, endDeg: 210, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர' } },
  { id: 8, name: { en: 'Scorpio', hi: 'वृश्चिक', sa: 'वृश्चिकः', ta: 'விருச்சிகம்' }, symbol: '♏', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः', ta: 'செவ்வாய்' }, startDeg: 210, endDeg: 240, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர' } },
  { id: 9, name: { en: 'Sagittarius', hi: 'धनु', sa: 'धनुः', ta: 'தனுசு' }, symbol: '♐', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः', ta: 'குரு' }, startDeg: 240, endDeg: 270, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய' } },
  { id: 10, name: { en: 'Capricorn', hi: 'मकर', sa: 'मकरः', ta: 'மகரம்' }, symbol: '♑', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः', ta: 'சனி' }, startDeg: 270, endDeg: 300, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர' } },
  { id: 11, name: { en: 'Aquarius', hi: 'कुम्भ', sa: 'कुम्भः', ta: 'கும்பம்' }, symbol: '♒', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः', ta: 'சனி' }, startDeg: 300, endDeg: 330, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர' } },
  { id: 12, name: { en: 'Pisces', hi: 'मीन', sa: 'मीनः', ta: 'மீனம்' }, symbol: '♓', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः', ta: 'குரு' }, startDeg: 330, endDeg: 360, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய' } },
];
