import { Rashi } from '@/types/panchang';

export const RASHIS: Rashi[] = [
  { id: 1, name: { en: 'Aries', hi: 'मेष', sa: 'मेषः' }, symbol: '♈', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः' }, startDeg: 0, endDeg: 30, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्' } },
  { id: 2, name: { en: 'Taurus', hi: 'वृषभ', sa: 'वृषभः' }, symbol: '♉', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः' }, startDeg: 30, endDeg: 60, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्' } },
  { id: 3, name: { en: 'Gemini', hi: 'मिथुन', sa: 'मिथुनम्' }, symbol: '♊', element: { en: 'Air', hi: 'वायु', sa: 'वायुः' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः' }, startDeg: 60, endDeg: 90, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्' } },
  { id: 4, name: { en: 'Cancer', hi: 'कर्क', sa: 'कर्कटः' }, symbol: '♋', element: { en: 'Water', hi: 'जल', sa: 'जलम्' }, ruler: 'Moon', rulerName: { en: 'Moon', hi: 'चन्द्र', sa: 'चन्द्रः' }, startDeg: 90, endDeg: 120, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्' } },
  { id: 5, name: { en: 'Leo', hi: 'सिंह', sa: 'सिंहः' }, symbol: '♌', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः' }, ruler: 'Sun', rulerName: { en: 'Sun', hi: 'सूर्य', sa: 'सूर्यः' }, startDeg: 120, endDeg: 150, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्' } },
  { id: 6, name: { en: 'Virgo', hi: 'कन्या', sa: 'कन्या' }, symbol: '♍', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः' }, startDeg: 150, endDeg: 180, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्' } },
  { id: 7, name: { en: 'Libra', hi: 'तुला', sa: 'तुला' }, symbol: '♎', element: { en: 'Air', hi: 'वायु', sa: 'वायुः' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः' }, startDeg: 180, endDeg: 210, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्' } },
  { id: 8, name: { en: 'Scorpio', hi: 'वृश्चिक', sa: 'वृश्चिकः' }, symbol: '♏', element: { en: 'Water', hi: 'जल', sa: 'जलम्' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः' }, startDeg: 210, endDeg: 240, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्' } },
  { id: 9, name: { en: 'Sagittarius', hi: 'धनु', sa: 'धनुः' }, symbol: '♐', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः' }, startDeg: 240, endDeg: 270, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्' } },
  { id: 10, name: { en: 'Capricorn', hi: 'मकर', sa: 'मकरः' }, symbol: '♑', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः' }, startDeg: 270, endDeg: 300, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्' } },
  { id: 11, name: { en: 'Aquarius', hi: 'कुम्भ', sa: 'कुम्भः' }, symbol: '♒', element: { en: 'Air', hi: 'वायु', sa: 'वायुः' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः' }, startDeg: 300, endDeg: 330, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्' } },
  { id: 12, name: { en: 'Pisces', hi: 'मीन', sa: 'मीनः' }, symbol: '♓', element: { en: 'Water', hi: 'जल', sa: 'जलम्' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः' }, startDeg: 330, endDeg: 360, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्' } },
];
