import { Rashi } from '@/types/panchang';

export const RASHIS: Rashi[] = [
  { id: 1, slug: 'mesh', name: { en: 'Aries', hi: 'मेष', sa: 'मेषः', ta: 'மேஷம்', te: 'మేషం', bn: 'মেষ', kn: 'ಮೇಷ', mr: 'मेष', gu: 'મેષ', mai: 'मेष' }, symbol: '♈', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு', te: 'అగ్ని', bn: 'অগ্নি', kn: 'ಅಗ್ನಿ', mr: 'अग्नि', gu: 'અગ્નિ', mai: 'अग्नि' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः', ta: 'செவ்வாய்', te: 'కుజుడు', bn: 'মঙ্গল', kn: 'ಮಂಗಳ', mr: 'मंगळ', gu: 'મંગળ', mai: 'मंगल' }, startDeg: 0, endDeg: 30, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர', te: 'చర', bn: 'চর', kn: 'ಚರ', mr: 'चर', gu: 'ચર', mai: 'चर' } },
  { id: 2, slug: 'vrishabh', name: { en: 'Taurus', hi: 'वृषभ', sa: 'वृषभः', ta: 'ரிஷபம்', te: 'వృషభం', bn: 'বৃষ', kn: 'ವೃಷಭ', mr: 'वृषभ', gu: 'વૃષભ', mai: 'वृषभ' }, symbol: '♉', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்', te: 'భూమి', bn: 'পৃথিবী', kn: 'ಭೂಮಿ', mr: 'पृथ्वी', gu: 'પૃથ્વી', mai: 'पृथ्वी' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः', ta: 'சுக்கிரன்', te: 'శుక్రుడు', bn: 'শুক্র', kn: 'ಶುಕ್ರ', mr: 'शुक्र', gu: 'શુક્ર', mai: 'शुक्र' }, startDeg: 30, endDeg: 60, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர', te: 'స్థిర', bn: 'স্থির', kn: 'ಸ್ಥಿರ', mr: 'स्थिर', gu: 'સ્થિર', mai: 'स्थिर' } },
  { id: 3, slug: 'mithun', name: { en: 'Gemini', hi: 'मिथुन', sa: 'मिथुनम्', ta: 'மிதுனம்', te: 'మిథునం', bn: 'মিথুন', kn: 'ಮಿಥುನ', mr: 'मिथुन', gu: 'મિથુન', mai: 'मिथुन' }, symbol: '♊', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று', te: 'వాయువు', bn: 'বায়ু', kn: 'ವಾಯು', mr: 'वायु', gu: 'વાયુ', mai: 'वायु' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः', ta: 'புதன்', te: 'బుధుడు', bn: 'বুধ', kn: 'ಬುಧ', mr: 'बुध', gu: 'બુધ', mai: 'बुध' }, startDeg: 60, endDeg: 90, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய', te: 'ద్విస్వభావ', bn: 'দ্বিস্বভাব', kn: 'ದ್ವಿಸ್ವಭಾವ', mr: 'द्विस्वभाव', gu: 'દ્વિસ્વભાવ', mai: 'द्विस्वभाव' } },
  { id: 4, slug: 'kark', name: { en: 'Cancer', hi: 'कर्क', sa: 'कर्कटः', ta: 'கடகம்', te: 'కర్కాటకం', bn: 'কর্কট', kn: 'ಕರ್ಕಾಟಕ', mr: 'कर्क', gu: 'કર્ક', mai: 'कर्क' }, symbol: '♋', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்', te: 'నీరు', bn: 'জল', kn: 'ನೀರು', mr: 'जल', gu: 'જળ', mai: 'जल' }, ruler: 'Moon', rulerName: { en: 'Moon', hi: 'चन्द्र', sa: 'चन्द्रः', ta: 'சந்திரன்', te: 'చంద్రుడు', bn: 'চন্দ্র', kn: 'ಚಂದ್ರ', mr: 'चन्द्र', gu: 'ચંદ્ર', mai: 'चन्द्र' }, startDeg: 90, endDeg: 120, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர', te: 'చర', bn: 'চর', kn: 'ಚರ', mr: 'चर', gu: 'ચર', mai: 'चर' } },
  { id: 5, slug: 'simha', name: { en: 'Leo', hi: 'सिंह', sa: 'सिंहः', ta: 'சிம்மம்', te: 'సింహం', bn: 'সিংহ', kn: 'ಸಿಂಹ', mr: 'सिंह', gu: 'સિંહ', mai: 'सिंह' }, symbol: '♌', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு', te: 'అగ్ని', bn: 'অগ্নি', kn: 'ಅಗ್ನಿ', mr: 'अग्नि', gu: 'અગ્નિ', mai: 'अग्नि' }, ruler: 'Sun', rulerName: { en: 'Sun', hi: 'सूर्य', sa: 'सूर्यः', ta: 'சூரியன்', te: 'సూర్యుడు', bn: 'সূর্য', kn: 'ಸೂರ್ಯ', mr: 'सूर्य', gu: 'સૂર્ય', mai: 'सूर्य' }, startDeg: 120, endDeg: 150, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர', te: 'స్థిర', bn: 'স্থির', kn: 'ಸ್ಥಿರ', mr: 'स्थिर', gu: 'સ્થિર', mai: 'स्थिर' } },
  { id: 6, slug: 'kanya', name: { en: 'Virgo', hi: 'कन्या', sa: 'कन्या', ta: 'கன்னி', te: 'కన్య', bn: 'কন্যা', kn: 'ಕನ್ಯಾ', mr: 'कन्या', gu: 'કન્યા', mai: 'कन्या' }, symbol: '♍', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்', te: 'భూమి', bn: 'পৃথিবী', kn: 'ಭೂಮಿ', mr: 'पृथ्वी', gu: 'પૃથ્વી', mai: 'पृथ्वी' }, ruler: 'Mercury', rulerName: { en: 'Mercury', hi: 'बुध', sa: 'बुधः', ta: 'புதன்', te: 'బుధుడు', bn: 'বুধ', kn: 'ಬುಧ', mr: 'बुध', gu: 'બુધ', mai: 'बुध' }, startDeg: 150, endDeg: 180, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய', te: 'ద్విస్వభావ', bn: 'দ্বিস্বভাব', kn: 'ದ್ವಿಸ್ವಭಾವ', mr: 'द्विस्वभाव', gu: 'દ્વિસ્વભાવ', mai: 'द्विस्वभाव' } },
  { id: 7, slug: 'tula', name: { en: 'Libra', hi: 'तुला', sa: 'तुला', ta: 'துலாம்', te: 'తులా', bn: 'তুলা', kn: 'ತುಲಾ', mr: 'तूळ', gu: 'તુલા', mai: 'तुला' }, symbol: '♎', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று', te: 'వాయువు', bn: 'বায়ু', kn: 'ವಾಯು', mr: 'वायु', gu: 'વાયુ', mai: 'वायु' }, ruler: 'Venus', rulerName: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्रः', ta: 'சுக்கிரன்', te: 'శుక్రుడు', bn: 'শুক্র', kn: 'ಶುಕ್ರ', mr: 'शुक्र', gu: 'શુક્ર', mai: 'शुक्र' }, startDeg: 180, endDeg: 210, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர', te: 'చర', bn: 'চর', kn: 'ಚರ', mr: 'चर', gu: 'ચર', mai: 'चर' } },
  { id: 8, slug: 'vrishchik', name: { en: 'Scorpio', hi: 'वृश्चिक', sa: 'वृश्चिकः', ta: 'விருச்சிகம்', te: 'వృశ్చికం', bn: 'বৃশ্চিক', kn: 'ವೃಶ್ಚಿಕ', mr: 'वृश्चिक', gu: 'વૃશ્ચિક', mai: 'वृश्चिक' }, symbol: '♏', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்', te: 'నీరు', bn: 'জল', kn: 'ನೀರು', mr: 'जल', gu: 'જળ', mai: 'जल' }, ruler: 'Mars', rulerName: { en: 'Mars', hi: 'मंगल', sa: 'मङ्गलः', ta: 'செவ்வாய்', te: 'కుజుడు', bn: 'মঙ্গল', kn: 'ಮಂಗಳ', mr: 'मंगळ', gu: 'મંગળ', mai: 'मंगल' }, startDeg: 210, endDeg: 240, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர', te: 'స్థిర', bn: 'স্থির', kn: 'ಸ್ಥಿರ', mr: 'स्थिर', gu: 'સ્થિર', mai: 'स्थिर' } },
  { id: 9, slug: 'dhanu', name: { en: 'Sagittarius', hi: 'धनु', sa: 'धनुः', ta: 'தனுசு', te: 'ధనుస్సు', bn: 'ধনু', kn: 'ಧನು', mr: 'धनु', gu: 'ધનુ', mai: 'धनु' }, symbol: '♐', element: { en: 'Fire', hi: 'अग्नि', sa: 'अग्निः', ta: 'நெருப்பு', te: 'అగ్ని', bn: 'অগ্নি', kn: 'ಅಗ್ನಿ', mr: 'अग्नि', gu: 'અગ્નિ', mai: 'अग्नि' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः', ta: 'குரு', te: 'గురు', bn: 'বৃহস্পতি', kn: 'ಗುರು', mr: 'बृहस्पति', gu: 'બૃહસ્પતિ', mai: 'बृहस्पति' }, startDeg: 240, endDeg: 270, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய', te: 'ద్విస్వభావ', bn: 'দ্বিস্বভাব', kn: 'ದ್ವಿಸ್ವಭಾವ', mr: 'द्विस्वभाव', gu: 'દ્વિસ્વભાવ', mai: 'द्विस्वभाव' } },
  { id: 10, slug: 'makar', name: { en: 'Capricorn', hi: 'मकर', sa: 'मकरः', ta: 'மகரம்', te: 'మకరం', bn: 'মকর', kn: 'ಮಕರ', mr: 'मकर', gu: 'મકર', mai: 'मकर' }, symbol: '♑', element: { en: 'Earth', hi: 'पृथ्वी', sa: 'पृथिवी', ta: 'நிலம்', te: 'భూమి', bn: 'পৃথিবী', kn: 'ಭೂಮಿ', mr: 'पृथ्वी', gu: 'પૃથ્વી', mai: 'पृथ्वी' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः', ta: 'சனி', te: 'శని', bn: 'শনি', kn: 'ಶನಿ', mr: 'शनि', gu: 'શનિ', mai: 'शनि' }, startDeg: 270, endDeg: 300, quality: { en: 'Cardinal', hi: 'चर', sa: 'चरम्', ta: 'சர', te: 'చర', bn: 'চর', kn: 'ಚರ', mr: 'चर', gu: 'ચર', mai: 'चर' } },
  { id: 11, slug: 'kumbh', name: { en: 'Aquarius', hi: 'कुम्भ', sa: 'कुम्भः', ta: 'கும்பம்', te: 'కుంభం', bn: 'কুম্ভ', kn: 'ಕುಂಭ', mr: 'कुम्भ', gu: 'કુમ્ભ', mai: 'कुम्भ' }, symbol: '♒', element: { en: 'Air', hi: 'वायु', sa: 'वायुः', ta: 'காற்று', te: 'వాయువు', bn: 'বায়ু', kn: 'ವಾಯು', mr: 'वायु', gu: 'વાયુ', mai: 'वायु' }, ruler: 'Saturn', rulerName: { en: 'Saturn', hi: 'शनि', sa: 'शनिः', ta: 'சனி', te: 'శని', bn: 'শনি', kn: 'ಶನಿ', mr: 'शनि', gu: 'શનિ', mai: 'शनि' }, startDeg: 300, endDeg: 330, quality: { en: 'Fixed', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'ஸ்திர', te: 'స్థిర', bn: 'স্থির', kn: 'ಸ್ಥಿರ', mr: 'स्थिर', gu: 'સ્થિર', mai: 'स्थिर' } },
  { id: 12, slug: 'meen', name: { en: 'Pisces', hi: 'मीन', sa: 'मीनः', ta: 'மீனம்', te: 'మీనం', bn: 'মীন', kn: 'ಮೀನ', mr: 'मीन', gu: 'મીન', mai: 'मीन' }, symbol: '♓', element: { en: 'Water', hi: 'जल', sa: 'जलम्', ta: 'நீர்', te: 'నీరు', bn: 'জল', kn: 'ನೀರು', mr: 'जल', gu: 'જળ', mai: 'जल' }, ruler: 'Jupiter', rulerName: { en: 'Jupiter', hi: 'बृहस्पति', sa: 'बृहस्पतिः', ta: 'குரு', te: 'గురు', bn: 'বৃহস্পতি', kn: 'ಗುರು', mr: 'बृहस्पति', gu: 'બૃહસ્પતિ', mai: 'बृहस्पति' }, startDeg: 330, endDeg: 360, quality: { en: 'Mutable', hi: 'द्विस्वभाव', sa: 'द्विस्वभावम्', ta: 'உபய', te: 'ద్విస్వభావ', bn: 'দ্বিস্বভাব', kn: 'ದ್ವಿಸ್ವಭಾವ', mr: 'द्विस्वभाव', gu: 'દ્વિસ્વભાવ', mai: 'द्विस्वभाव' } },
];
