import { Tithi } from '@/types/panchang';

export const TITHIS: Tithi[] = [
  { number: 1, name: { en: 'Pratipada', hi: 'प्रतिपदा', sa: 'प्रतिपदा', ta: 'பிரதமை' }, paksha: 'shukla', deity: { en: 'Agni', hi: 'अग्नि', sa: 'अग्निः', ta: 'அக்னி' } },
  { number: 2, name: { en: 'Dwitiya', hi: 'द्वितीया', sa: 'द्वितीया', ta: 'துவிதியை' }, paksha: 'shukla', deity: { en: 'Brahma', hi: 'ब्रह्मा', sa: 'ब्रह्मा', ta: 'பிரம்மா' } },
  { number: 3, name: { en: 'Tritiya', hi: 'तृतीया', sa: 'तृतीया', ta: 'திருதியை' }, paksha: 'shukla', deity: { en: 'Gauri', hi: 'गौरी', sa: 'गौरी', ta: 'கௌரி' } },
  { number: 4, name: { en: 'Chaturthi', hi: 'चतुर्थी', sa: 'चतुर्थी', ta: 'சதுர்த்தி' }, paksha: 'shukla', deity: { en: 'Ganesha', hi: 'गणेश', sa: 'गणेशः', ta: 'கணேசன்' } },
  { number: 5, name: { en: 'Panchami', hi: 'पंचमी', sa: 'पञ्चमी', ta: 'பஞ்சமி' }, paksha: 'shukla', deity: { en: 'Sarpa (Nagas)', hi: 'सर्प (नाग)', sa: 'सर्पाः', ta: 'சர்ப்பம் (நாகம்)' } },
  { number: 6, name: { en: 'Shashthi', hi: 'षष्ठी', sa: 'षष्ठी', ta: 'சஷ்டி' }, paksha: 'shukla', deity: { en: 'Kartikeya', hi: 'कार्तिकेय', sa: 'कार्तिकेयः', ta: 'கார்த்திகேயன்' } },
  { number: 7, name: { en: 'Saptami', hi: 'सप्तमी', sa: 'सप्तमी', ta: 'சப்தமி' }, paksha: 'shukla', deity: { en: 'Surya', hi: 'सूर्य', sa: 'सूर्यः', ta: 'சூரியன்' } },
  { number: 8, name: { en: 'Ashtami', hi: 'अष्टमी', sa: 'अष्टमी', ta: 'அஷ்டமி' }, paksha: 'shukla', deity: { en: 'Rudra', hi: 'रुद्र', sa: 'रुद्रः', ta: 'ருத்திரன்' } },
  { number: 9, name: { en: 'Navami', hi: 'नवमी', sa: 'नवमी', ta: 'நவமி' }, paksha: 'shukla', deity: { en: 'Durga', hi: 'दुर्गा', sa: 'दुर्गा', ta: 'துர்கா' } },
  { number: 10, name: { en: 'Dashami', hi: 'दशमी', sa: 'दशमी', ta: 'தசமி' }, paksha: 'shukla', deity: { en: 'Dharma', hi: 'धर्म', sa: 'धर्मः', ta: 'தர்மம்' } },
  { number: 11, name: { en: 'Ekadashi', hi: 'एकादशी', sa: 'एकादशी', ta: 'ஏகாதசி' }, paksha: 'shukla', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः', ta: 'விஷ்ணு' } },
  { number: 12, name: { en: 'Dwadashi', hi: 'द्वादशी', sa: 'द्वादशी', ta: 'துவாதசி' }, paksha: 'shukla', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः', ta: 'விஷ்ணு' } },
  { number: 13, name: { en: 'Trayodashi', hi: 'त्रयोदशी', sa: 'त्रयोदशी', ta: 'திரயோதசி' }, paksha: 'shukla', deity: { en: 'Kamadeva', hi: 'कामदेव', sa: 'कामदेवः', ta: 'காமதேவன்' } },
  { number: 14, name: { en: 'Chaturdashi', hi: 'चतुर्दशी', sa: 'चतुर्दशी', ta: 'சதுர்த்தசி' }, paksha: 'shukla', deity: { en: 'Shiva', hi: 'शिव', sa: 'शिवः', ta: 'சிவன்' } },
  { number: 15, name: { en: 'Purnima', hi: 'पूर्णिमा', sa: 'पूर्णिमा', ta: 'பௌர்ணமி' }, paksha: 'shukla', deity: { en: 'Chandra', hi: 'चन्द्र', sa: 'चन्द्रः', ta: 'சந்திரன்' } },
  { number: 16, name: { en: 'Pratipada', hi: 'प्रतिपदा', sa: 'प्रतिपदा', ta: 'பிரதமை' }, paksha: 'krishna', deity: { en: 'Agni', hi: 'अग्नि', sa: 'अग्निः', ta: 'அக்னி' } },
  { number: 17, name: { en: 'Dwitiya', hi: 'द्वितीया', sa: 'द्वितीया', ta: 'துவிதியை' }, paksha: 'krishna', deity: { en: 'Brahma', hi: 'ब्रह्मा', sa: 'ब्रह्मा', ta: 'பிரம்மா' } },
  { number: 18, name: { en: 'Tritiya', hi: 'तृतीया', sa: 'तृतीया', ta: 'திருதியை' }, paksha: 'krishna', deity: { en: 'Gauri', hi: 'गौरी', sa: 'गौरी', ta: 'கௌரி' } },
  { number: 19, name: { en: 'Chaturthi', hi: 'चतुर्थी', sa: 'चतुर्थी', ta: 'சதுர்த்தி' }, paksha: 'krishna', deity: { en: 'Ganesha', hi: 'गणेश', sa: 'गणेशः', ta: 'கணேசன்' } },
  { number: 20, name: { en: 'Panchami', hi: 'पंचमी', sa: 'पञ्चमी', ta: 'பஞ்சமி' }, paksha: 'krishna', deity: { en: 'Sarpa', hi: 'सर्प', sa: 'सर्पाः', ta: 'சர்ப்பம்' } },
  { number: 21, name: { en: 'Shashthi', hi: 'षष्ठी', sa: 'षष्ठी', ta: 'சஷ்டி' }, paksha: 'krishna', deity: { en: 'Kartikeya', hi: 'कार्तिकेय', sa: 'कार्तिकेयः', ta: 'கார்த்திகேயன்' } },
  { number: 22, name: { en: 'Saptami', hi: 'सप्तमी', sa: 'सप्तमी', ta: 'சப்தமி' }, paksha: 'krishna', deity: { en: 'Surya', hi: 'सूर्य', sa: 'सूर्यः', ta: 'சூரியன்' } },
  { number: 23, name: { en: 'Ashtami', hi: 'अष्टमी', sa: 'अष्टमी', ta: 'அஷ்டமி' }, paksha: 'krishna', deity: { en: 'Rudra', hi: 'रुद्र', sa: 'रुद्रः', ta: 'ருத்திரன்' } },
  { number: 24, name: { en: 'Navami', hi: 'नवमी', sa: 'नवमी', ta: 'நவமி' }, paksha: 'krishna', deity: { en: 'Durga', hi: 'दुर्गा', sa: 'दुर्गा', ta: 'துர்கா' } },
  { number: 25, name: { en: 'Dashami', hi: 'दशमी', sa: 'दशमी', ta: 'தசமி' }, paksha: 'krishna', deity: { en: 'Dharma', hi: 'धर्म', sa: 'धर्मः', ta: 'தர்மம்' } },
  { number: 26, name: { en: 'Ekadashi', hi: 'एकादशी', sa: 'एकादशी', ta: 'ஏகாதசி' }, paksha: 'krishna', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः', ta: 'விஷ்ணு' } },
  { number: 27, name: { en: 'Dwadashi', hi: 'द्वादशी', sa: 'द्वादशी', ta: 'துவாதசி' }, paksha: 'krishna', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः', ta: 'விஷ்ணு' } },
  { number: 28, name: { en: 'Trayodashi', hi: 'त्रयोदशी', sa: 'त्रयोदशी', ta: 'திரயோதசி' }, paksha: 'krishna', deity: { en: 'Kamadeva', hi: 'कामदेव', sa: 'कामदेवः', ta: 'காமதேவன்' } },
  { number: 29, name: { en: 'Chaturdashi', hi: 'चतुर्दशी', sa: 'चतुर्दशी', ta: 'சதுர்த்தசி' }, paksha: 'krishna', deity: { en: 'Shiva', hi: 'शिव', sa: 'शिवः', ta: 'சிவன்' } },
  { number: 30, name: { en: 'Amavasya', hi: 'अमावस्या', sa: 'अमावस्या', ta: 'அமாவாசை' }, paksha: 'krishna', deity: { en: 'Pitris', hi: 'पितर', sa: 'पितरः', ta: 'பித்ருக்கள்' } },
];
