import { Tithi } from '@/types/panchang';

export const TITHIS: Tithi[] = [
  { number: 1, name: { en: 'Pratipada', hi: 'प्रतिपदा', sa: 'प्रतिपदा' }, paksha: 'shukla', deity: { en: 'Agni', hi: 'अग्नि', sa: 'अग्निः' } },
  { number: 2, name: { en: 'Dwitiya', hi: 'द्वितीया', sa: 'द्वितीया' }, paksha: 'shukla', deity: { en: 'Brahma', hi: 'ब्रह्मा', sa: 'ब्रह्मा' } },
  { number: 3, name: { en: 'Tritiya', hi: 'तृतीया', sa: 'तृतीया' }, paksha: 'shukla', deity: { en: 'Gauri', hi: 'गौरी', sa: 'गौरी' } },
  { number: 4, name: { en: 'Chaturthi', hi: 'चतुर्थी', sa: 'चतुर्थी' }, paksha: 'shukla', deity: { en: 'Ganesha', hi: 'गणेश', sa: 'गणेशः' } },
  { number: 5, name: { en: 'Panchami', hi: 'पंचमी', sa: 'पञ्चमी' }, paksha: 'shukla', deity: { en: 'Sarpa (Nagas)', hi: 'सर्प (नाग)', sa: 'सर्पाः' } },
  { number: 6, name: { en: 'Shashthi', hi: 'षष्ठी', sa: 'षष्ठी' }, paksha: 'shukla', deity: { en: 'Kartikeya', hi: 'कार्तिकेय', sa: 'कार्तिकेयः' } },
  { number: 7, name: { en: 'Saptami', hi: 'सप्तमी', sa: 'सप्तमी' }, paksha: 'shukla', deity: { en: 'Surya', hi: 'सूर्य', sa: 'सूर्यः' } },
  { number: 8, name: { en: 'Ashtami', hi: 'अष्टमी', sa: 'अष्टमी' }, paksha: 'shukla', deity: { en: 'Rudra', hi: 'रुद्र', sa: 'रुद्रः' } },
  { number: 9, name: { en: 'Navami', hi: 'नवमी', sa: 'नवमी' }, paksha: 'shukla', deity: { en: 'Durga', hi: 'दुर्गा', sa: 'दुर्गा' } },
  { number: 10, name: { en: 'Dashami', hi: 'दशमी', sa: 'दशमी' }, paksha: 'shukla', deity: { en: 'Dharma', hi: 'धर्म', sa: 'धर्मः' } },
  { number: 11, name: { en: 'Ekadashi', hi: 'एकादशी', sa: 'एकादशी' }, paksha: 'shukla', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः' } },
  { number: 12, name: { en: 'Dwadashi', hi: 'द्वादशी', sa: 'द्वादशी' }, paksha: 'shukla', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः' } },
  { number: 13, name: { en: 'Trayodashi', hi: 'त्रयोदशी', sa: 'त्रयोदशी' }, paksha: 'shukla', deity: { en: 'Kamadeva', hi: 'कामदेव', sa: 'कामदेवः' } },
  { number: 14, name: { en: 'Chaturdashi', hi: 'चतुर्दशी', sa: 'चतुर्दशी' }, paksha: 'shukla', deity: { en: 'Shiva', hi: 'शिव', sa: 'शिवः' } },
  { number: 15, name: { en: 'Purnima', hi: 'पूर्णिमा', sa: 'पूर्णिमा' }, paksha: 'shukla', deity: { en: 'Chandra', hi: 'चन्द्र', sa: 'चन्द्रः' } },
  { number: 16, name: { en: 'Pratipada', hi: 'प्रतिपदा', sa: 'प्रतिपदा' }, paksha: 'krishna', deity: { en: 'Agni', hi: 'अग्नि', sa: 'अग्निः' } },
  { number: 17, name: { en: 'Dwitiya', hi: 'द्वितीया', sa: 'द्वितीया' }, paksha: 'krishna', deity: { en: 'Brahma', hi: 'ब्रह्मा', sa: 'ब्रह्मा' } },
  { number: 18, name: { en: 'Tritiya', hi: 'तृतीया', sa: 'तृतीया' }, paksha: 'krishna', deity: { en: 'Gauri', hi: 'गौरी', sa: 'गौरी' } },
  { number: 19, name: { en: 'Chaturthi', hi: 'चतुर्थी', sa: 'चतुर्थी' }, paksha: 'krishna', deity: { en: 'Ganesha', hi: 'गणेश', sa: 'गणेशः' } },
  { number: 20, name: { en: 'Panchami', hi: 'पंचमी', sa: 'पञ्चमी' }, paksha: 'krishna', deity: { en: 'Sarpa', hi: 'सर्प', sa: 'सर्पाः' } },
  { number: 21, name: { en: 'Shashthi', hi: 'षष्ठी', sa: 'षष्ठी' }, paksha: 'krishna', deity: { en: 'Kartikeya', hi: 'कार्तिकेय', sa: 'कार्तिकेयः' } },
  { number: 22, name: { en: 'Saptami', hi: 'सप्तमी', sa: 'सप्तमी' }, paksha: 'krishna', deity: { en: 'Surya', hi: 'सूर्य', sa: 'सूर्यः' } },
  { number: 23, name: { en: 'Ashtami', hi: 'अष्टमी', sa: 'अष्टमी' }, paksha: 'krishna', deity: { en: 'Rudra', hi: 'रुद्र', sa: 'रुद्रः' } },
  { number: 24, name: { en: 'Navami', hi: 'नवमी', sa: 'नवमी' }, paksha: 'krishna', deity: { en: 'Durga', hi: 'दुर्गा', sa: 'दुर्गा' } },
  { number: 25, name: { en: 'Dashami', hi: 'दशमी', sa: 'दशमी' }, paksha: 'krishna', deity: { en: 'Dharma', hi: 'धर्म', sa: 'धर्मः' } },
  { number: 26, name: { en: 'Ekadashi', hi: 'एकादशी', sa: 'एकादशी' }, paksha: 'krishna', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः' } },
  { number: 27, name: { en: 'Dwadashi', hi: 'द्वादशी', sa: 'द्वादशी' }, paksha: 'krishna', deity: { en: 'Vishnu', hi: 'विष्णु', sa: 'विष्णुः' } },
  { number: 28, name: { en: 'Trayodashi', hi: 'त्रयोदशी', sa: 'त्रयोदशी' }, paksha: 'krishna', deity: { en: 'Kamadeva', hi: 'कामदेव', sa: 'कामदेवः' } },
  { number: 29, name: { en: 'Chaturdashi', hi: 'चतुर्दशी', sa: 'चतुर्दशी' }, paksha: 'krishna', deity: { en: 'Shiva', hi: 'शिव', sa: 'शिवः' } },
  { number: 30, name: { en: 'Amavasya', hi: 'अमावस्या', sa: 'अमावस्या' }, paksha: 'krishna', deity: { en: 'Pitris', hi: 'पितर', sa: 'पितरः' } },
];
