/**
 * Runtime merger that overlays per-locale `yoga-{locale}-overlay.json`
 * files onto YOGA_DETAIL_DATA, populating `.{locale}` fields on each
 * LocaleText object without touching the canonical yoga-details.ts.
 *
 * Overlay JSONs are generated by /tmp/translate-yoga-mai-anthropic.ts
 * (Maithili) and /tmp/translate-yoga-multi.ts (the other 6 regional
 * Indic locales). Each is keyed by dotted path:
 *   `gajakesari.formationRule`
 *   `gajakesari.detailedDescription.0` … `.3`
 *   `gajakesari.effects.0.area` / `.0.description` …
 *   `gajakesari.cancellations.0` …
 *   `gajakesari.remedies.gemstone` / `.charity`
 *
 * Why runtime merge instead of mutating yoga-details.ts directly:
 * - Keeps the source-of-truth EN/HI constants reviewable as code
 * - Each overlay JSON is a single file — easy to regenerate per locale
 * - Diff cost on `git diff` stays manageable as new locales land
 *
 * Empty overlay files (e.g. `{}`) are no-ops: yogas with no overlay
 * entries for a given locale fall back to .en via the rendering
 * `tl()` helper (which extends global LocaleText's index signature).
 *
 * Consumers: `src/app/[locale]/learn/yoga/[slug]/page.tsx` switches
 * its import from `yoga-details` to this module. For locales with
 * no overlay entry, the merged structure is identical to the original.
 *
 * Spec docs/specs/2026-06-04-noindex-thin-translation-locales.md §3
 * (lifecycle state 2 → 3 — promotion).
 */

import { YOGA_DETAIL_DATA, type YogaDetailEntry } from './yoga-details';
import maiOverlayRaw from './yoga-mai-overlay.json';
import taOverlayRaw from './yoga-ta-overlay.json';
import teOverlayRaw from './yoga-te-overlay.json';
import bnOverlayRaw from './yoga-bn-overlay.json';
import guOverlayRaw from './yoga-gu-overlay.json';
import knOverlayRaw from './yoga-kn-overlay.json';
import mrOverlayRaw from './yoga-mr-overlay.json';

// Expansion overlays — adds 4 new narrative sections per slug
// (realWorldManifestation, strengthFactors, activationTiming,
// practicalGuidance). EN authoritative; regional locales attach via
// the same dotted-key scheme. Generated by
// `scripts/generate-yoga-expansions-via-gemini.py` then translated
// per-locale by the existing translate-yoga-* scripts.
import expEnRaw from './yoga-expansions-en-overlay.json';
import expHiRaw from './yoga-expansions-hi-overlay.json';
import expMaiRaw from './yoga-expansions-mai-overlay.json';
import expMrRaw from './yoga-expansions-mr-overlay.json';
import expTaRaw from './yoga-expansions-ta-overlay.json';
import expTeRaw from './yoga-expansions-te-overlay.json';
import expBnRaw from './yoga-expansions-bn-overlay.json';
import expGuRaw from './yoga-expansions-gu-overlay.json';
import expKnRaw from './yoga-expansions-kn-overlay.json';

type OverlayLocale = 'mai' | 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'mr';

const OVERLAYS: Record<OverlayLocale, Readonly<Record<string, string>>> = {
  mai: maiOverlayRaw as Readonly<Record<string, string>>,
  ta: taOverlayRaw as Readonly<Record<string, string>>,
  te: teOverlayRaw as Readonly<Record<string, string>>,
  bn: bnOverlayRaw as Readonly<Record<string, string>>,
  gu: guOverlayRaw as Readonly<Record<string, string>>,
  kn: knOverlayRaw as Readonly<Record<string, string>>,
  mr: mrOverlayRaw as Readonly<Record<string, string>>,
};

const OVERLAY_LOCALES: readonly OverlayLocale[] = ['mai', 'ta', 'te', 'bn', 'gu', 'kn', 'mr'];

// Expansion overlay set — includes EN/HI because expansions are NEW
// fields not present in the canonical YOGA_DETAIL_DATA. EN is the
// source-of-truth (authored by Gemini); HI + 7 regional locales come
// from translation passes.
type ExpansionLocale = 'en' | 'hi' | OverlayLocale;
const EXPANSION_OVERLAYS: Record<ExpansionLocale, Readonly<Record<string, string>>> = {
  en: expEnRaw as Readonly<Record<string, string>>,
  hi: expHiRaw as Readonly<Record<string, string>>,
  mai: expMaiRaw as Readonly<Record<string, string>>,
  mr: expMrRaw as Readonly<Record<string, string>>,
  ta: expTaRaw as Readonly<Record<string, string>>,
  te: expTeRaw as Readonly<Record<string, string>>,
  bn: expBnRaw as Readonly<Record<string, string>>,
  gu: expGuRaw as Readonly<Record<string, string>>,
  kn: expKnRaw as Readonly<Record<string, string>>,
};
const EXPANSION_LOCALES: readonly ExpansionLocale[] = ['en', 'hi', 'mai', 'mr', 'ta', 'te', 'bn', 'gu', 'kn'];

function attachOverlayString(
  obj: { en: string; hi: string } | undefined,
  slug: string,
  pathSuffix: string,
): void {
  if (!obj) return;
  const key = `${slug}.${pathSuffix}`;
  for (const locale of OVERLAY_LOCALES) {
    const value = OVERLAYS[locale][key];
    if (value) (obj as Record<string, string | undefined>)[locale] = value;
  }
}

function mergeOverlaysInto(slug: string, yoga: YogaDetailEntry): YogaDetailEntry {
  // Deep-clone so we don't mutate the imported YOGA_DETAIL_DATA reference.
  // structuredClone exists in Node 17+; Next.js runtime is Node 22.
  const cloned: YogaDetailEntry = structuredClone(yoga);

  attachOverlayString(cloned.formationRule, slug, 'formationRule');

  // detailedDescription — populate `<locale>: string[]` from `.0`, `.1`, ... entries.
  if (cloned.detailedDescription) {
    for (const locale of OVERLAY_LOCALES) {
      const overlay = OVERLAYS[locale];
      const arr: string[] = [];
      for (let i = 0; ; i++) {
        const v = overlay[`${slug}.detailedDescription.${i}`];
        if (v === undefined) break;
        arr.push(v);
      }
      if (arr.length > 0) {
        (cloned.detailedDescription as Record<string, string[] | undefined>)[locale] = arr;
      }
    }
  }

  if (cloned.effects) {
    cloned.effects.forEach((eff, i) => {
      attachOverlayString(eff.area, slug, `effects.${i}.area`);
      attachOverlayString(eff.description, slug, `effects.${i}.description`);
    });
  }

  if (cloned.cancellations) {
    cloned.cancellations.forEach((c, i) => {
      attachOverlayString(c, slug, `cancellations.${i}`);
    });
  }

  if (cloned.remedies) {
    attachOverlayString(cloned.remedies.gemstone, slug, 'remedies.gemstone');
    attachOverlayString(cloned.remedies.charity, slug, 'remedies.charity');
    // mantra is Sanskrit — intentionally not translated.
  }

  attachExpansions(slug, cloned);

  return cloned;
}

/**
 * Attach EN + per-locale expansion fields (realWorldManifestation,
 * strengthFactors[], activationTiming, practicalGuidance[]) onto the
 * cloned yoga. EN values populate the field for the first time
 * (creating the LocaleText). Other locale values attach via the
 * dotted index/key scheme used by the source overlays.
 *
 * Field absence at the EN layer = field stays undefined → UI skips
 * the corresponding render block entirely. No empty sections.
 */
function attachExpansions(slug: string, yoga: YogaDetailEntry): void {
  const enEntry = EXPANSION_OVERLAYS.en;

  // realWorldManifestation — scalar LocaleText.
  const rwmEn = enEntry[`${slug}.realWorldManifestation`];
  if (typeof rwmEn === 'string' && rwmEn.length > 0) {
    const obj: Record<string, string> = { en: rwmEn, hi: rwmEn };
    for (const locale of EXPANSION_LOCALES) {
      const v = EXPANSION_OVERLAYS[locale][`${slug}.realWorldManifestation`];
      if (typeof v === 'string' && v.length > 0) obj[locale] = v;
    }
    yoga.realWorldManifestation = obj as YogaDetailEntry['realWorldManifestation'];
  }

  // activationTiming — scalar LocaleText.
  const atEn = enEntry[`${slug}.activationTiming`];
  if (typeof atEn === 'string' && atEn.length > 0) {
    const obj: Record<string, string> = { en: atEn, hi: atEn };
    for (const locale of EXPANSION_LOCALES) {
      const v = EXPANSION_OVERLAYS[locale][`${slug}.activationTiming`];
      if (typeof v === 'string' && v.length > 0) obj[locale] = v;
    }
    yoga.activationTiming = obj as YogaDetailEntry['activationTiming'];
  }

  // strengthFactors — LocaleText[].
  const sfList = buildExpansionArray(slug, 'strengthFactors');
  if (sfList.length > 0) yoga.strengthFactors = sfList as YogaDetailEntry['strengthFactors'];

  // practicalGuidance — LocaleText[].
  const pgList = buildExpansionArray(slug, 'practicalGuidance');
  if (pgList.length > 0) yoga.practicalGuidance = pgList as YogaDetailEntry['practicalGuidance'];
}

function buildExpansionArray(slug: string, fieldName: string): Array<Record<string, string>> {
  const enEntry = EXPANSION_OVERLAYS.en;
  const result: Array<Record<string, string>> = [];
  for (let i = 0; ; i++) {
    const enValue = enEntry[`${slug}.${fieldName}.${i}`];
    if (typeof enValue !== 'string' || enValue.length === 0) break;
    const obj: Record<string, string> = { en: enValue, hi: enValue };
    for (const locale of EXPANSION_LOCALES) {
      const v = EXPANSION_OVERLAYS[locale][`${slug}.${fieldName}.${i}`];
      if (typeof v === 'string' && v.length > 0) obj[locale] = v;
    }
    result.push(obj);
  }
  return result;
}

/**
 * YOGA_DETAIL_DATA with all available regional-locale translations
 * merged in from the per-locale overlay JSON files. For locales with
 * empty overlays (or yogas missing from an overlay), the resulting
 * structure carries the original EN/HI fields — `tl()` then falls
 * back via its existing en-default behaviour.
 */
export const YOGA_DETAIL_DATA_WITH_OVERLAY: Readonly<Record<string, YogaDetailEntry>> = Object.freeze(
  Object.fromEntries(
    Object.entries(YOGA_DETAIL_DATA).map(([slug, yoga]) => [slug, mergeOverlaysInto(slug, yoga)]),
  ),
);

/** Re-export the canonical type so consumers don't need a second import. */
export type { YogaDetailEntry, YogaChartPosition } from './yoga-details';

/** Locale set covered by the overlay system (excludes the EN/HI source). */
export { OVERLAY_LOCALES };
