import { Yoga } from '@/types/panchang';

export const YOGAS: Yoga[] = [
  { number: 1, name: { en: 'Vishkambha', hi: 'विष्कम्भ', sa: 'विष्कम्भः' }, nature: 'inauspicious', meaning: { en: 'Obstacle', hi: 'बाधा', sa: 'बाधा' } },
  { number: 2, name: { en: 'Priti', hi: 'प्रीति', sa: 'प्रीतिः' }, nature: 'auspicious', meaning: { en: 'Love', hi: 'प्रेम', sa: 'प्रेम' } },
  { number: 3, name: { en: 'Ayushman', hi: 'आयुष्मान्', sa: 'आयुष्मान्' }, nature: 'auspicious', meaning: { en: 'Long life', hi: 'दीर्घ आयु', sa: 'दीर्घायुः' } },
  { number: 4, name: { en: 'Saubhagya', hi: 'सौभाग्य', sa: 'सौभाग्यम्' }, nature: 'auspicious', meaning: { en: 'Good fortune', hi: 'सौभाग्य', sa: 'सौभाग्यम्' } },
  { number: 5, name: { en: 'Shobhana', hi: 'शोभन', sa: 'शोभनम्' }, nature: 'auspicious', meaning: { en: 'Splendor', hi: 'शोभा', sa: 'शोभा' } },
  { number: 6, name: { en: 'Atiganda', hi: 'अतिगण्ड', sa: 'अतिगण्डः' }, nature: 'inauspicious', meaning: { en: 'Great danger', hi: 'महा संकट', sa: 'महासङ्कटः' } },
  { number: 7, name: { en: 'Sukarma', hi: 'सुकर्मा', sa: 'सुकर्मा' }, nature: 'auspicious', meaning: { en: 'Good deeds', hi: 'शुभ कर्म', sa: 'शुभकर्म' } },
  { number: 8, name: { en: 'Dhriti', hi: 'धृति', sa: 'धृतिः' }, nature: 'auspicious', meaning: { en: 'Firmness', hi: 'धैर्य', sa: 'धैर्यम्' } },
  { number: 9, name: { en: 'Shula', hi: 'शूल', sa: 'शूलम्' }, nature: 'inauspicious', meaning: { en: 'Thorn/Pain', hi: 'कष्ट', sa: 'कष्टम्' } },
  { number: 10, name: { en: 'Ganda', hi: 'गण्ड', sa: 'गण्डः' }, nature: 'inauspicious', meaning: { en: 'Danger', hi: 'संकट', sa: 'सङ्कटः' } },
  { number: 11, name: { en: 'Vriddhi', hi: 'वृद्धि', sa: 'वृद्धिः' }, nature: 'auspicious', meaning: { en: 'Growth', hi: 'वृद्धि', sa: 'वृद्धिः' } },
  { number: 12, name: { en: 'Dhruva', hi: 'ध्रुव', sa: 'ध्रुवः' }, nature: 'auspicious', meaning: { en: 'Constant', hi: 'स्थिर', sa: 'स्थिरम्' } },
  { number: 13, name: { en: 'Vyaghata', hi: 'व्याघात', sa: 'व्याघातः' }, nature: 'inauspicious', meaning: { en: 'Calamity', hi: 'विपत्ति', sa: 'विपत्तिः' } },
  { number: 14, name: { en: 'Harshana', hi: 'हर्षण', sa: 'हर्षणम्' }, nature: 'auspicious', meaning: { en: 'Joy', hi: 'हर्ष', sa: 'हर्षः' } },
  { number: 15, name: { en: 'Vajra', hi: 'वज्र', sa: 'वज्रम्' }, nature: 'neutral', meaning: { en: 'Thunderbolt', hi: 'वज्र', sa: 'वज्रम्' } },
  { number: 16, name: { en: 'Siddhi', hi: 'सिद्धि', sa: 'सिद्धिः' }, nature: 'auspicious', meaning: { en: 'Accomplishment', hi: 'सिद्धि', sa: 'सिद्धिः' } },
  { number: 17, name: { en: 'Vyatipata', hi: 'व्यतीपात', sa: 'व्यतीपातः' }, nature: 'inauspicious', meaning: { en: 'Misfortune', hi: 'दुर्भाग्य', sa: 'दुर्भाग्यम्' } },
  { number: 18, name: { en: 'Variyan', hi: 'वरीयान्', sa: 'वरीयान्' }, nature: 'auspicious', meaning: { en: 'Excellent', hi: 'श्रेष्ठ', sa: 'श्रेष्ठम्' } },
  { number: 19, name: { en: 'Parigha', hi: 'परिघ', sa: 'परिघः' }, nature: 'inauspicious', meaning: { en: 'Obstruction', hi: 'अवरोध', sa: 'अवरोधः' } },
  { number: 20, name: { en: 'Shiva', hi: 'शिव', sa: 'शिवम्' }, nature: 'auspicious', meaning: { en: 'Auspicious', hi: 'शुभ', sa: 'शुभम्' } },
  { number: 21, name: { en: 'Siddha', hi: 'सिद्ध', sa: 'सिद्धः' }, nature: 'auspicious', meaning: { en: 'Accomplished', hi: 'सिद्ध', sa: 'सिद्धः' } },
  { number: 22, name: { en: 'Sadhya', hi: 'साध्य', sa: 'साध्यम्' }, nature: 'auspicious', meaning: { en: 'Achievable', hi: 'साध्य', sa: 'साध्यम्' } },
  { number: 23, name: { en: 'Shubha', hi: 'शुभ', sa: 'शुभम्' }, nature: 'auspicious', meaning: { en: 'Auspicious', hi: 'शुभ', sa: 'शुभम्' } },
  { number: 24, name: { en: 'Shukla', hi: 'शुक्ल', sa: 'शुक्लम्' }, nature: 'auspicious', meaning: { en: 'Bright', hi: 'उज्ज्वल', sa: 'उज्ज्वलम्' } },
  { number: 25, name: { en: 'Brahma', hi: 'ब्रह्म', sa: 'ब्रह्म' }, nature: 'auspicious', meaning: { en: 'Divine', hi: 'दिव्य', sa: 'दिव्यम्' } },
  { number: 26, name: { en: 'Indra', hi: 'ऐन्द्र', sa: 'ऐन्द्रम्' }, nature: 'auspicious', meaning: { en: 'Powerful', hi: 'शक्तिशाली', sa: 'शक्तिमत्' } },
  { number: 27, name: { en: 'Vaidhriti', hi: 'वैधृति', sa: 'वैधृतिः' }, nature: 'inauspicious', meaning: { en: 'Inauspicious', hi: 'अशुभ', sa: 'अशुभम्' } },
];
