/**
 * Runtime merger that overlays `yoga-mai-overlay.json` onto
 * YOGA_DETAIL_DATA, populating the `.mai` fields without touching
 * the canonical yoga-details.ts source.
 *
 * The overlay JSON is generated by /tmp/translate-yoga-mai-gemini.ts
 * (Gemini 2.5 Flash + astrology glossary, see spec §3 — option A pilot).
 * Keys are dotted paths:
 *   `gajakesari.formationRule`
 *   `gajakesari.detailedDescription.0` … `.3`
 *   `gajakesari.effects.0.area` / `.0.description` …
 *   `gajakesari.cancellations.0` …
 *   `gajakesari.remedies.gemstone` / `.charity`
 *
 * Why runtime merge instead of mutating yoga-details.ts directly:
 * - Keeps the source-of-truth EN/HI constants reviewable as code
 * - Mai overlay is a single JSON file — easy to swap or regenerate
 * - Diff cost on `git diff` stays manageable
 *
 * Consumers: `src/app/[locale]/learn/yoga/[slug]/page.tsx` switches
 * its import from `yoga-details` to this module + replaces
 * `isHi ? text.hi : text.en` with `tl(text, locale)`. For non-mai
 * locales the merged structure is identical to the original.
 *
 * Spec docs/specs/2026-06-04-noindex-thin-translation-locales.md §3
 * (lifecycle state 2 → 3 — promotion).
 */

import { YOGA_DETAIL_DATA, type YogaDetailEntry } from './yoga-details';
import maiOverlayRaw from './yoga-mai-overlay.json';

const maiOverlay = maiOverlayRaw as Readonly<Record<string, string>>;

function maybeAttachMai(
  obj: { en: string; hi: string } | undefined,
  key: string,
): void {
  if (!obj) return;
  const mai = maiOverlay[key];
  if (mai) (obj as { mai?: string }).mai = mai;
}

function mergeMaithiliInto(slug: string, yoga: YogaDetailEntry): YogaDetailEntry {
  // Deep-clone so we don't mutate the imported YOGA_DETAIL_DATA reference.
  // structuredClone exists in Node 17+ and modern browsers; Next.js's
  // server runtime is Node 22, so this is safe.
  const cloned: YogaDetailEntry = structuredClone(yoga);

  maybeAttachMai(cloned.formationRule, `${slug}.formationRule`);

  // detailedDescription — populate `mai: string[]` from `.0`, `.1`, ... entries
  if (cloned.detailedDescription) {
    const maiArr: string[] = [];
    for (let i = 0; ; i++) {
      const v = maiOverlay[`${slug}.detailedDescription.${i}`];
      if (v === undefined) break;
      maiArr.push(v);
    }
    if (maiArr.length > 0) cloned.detailedDescription.mai = maiArr;
  }

  // effects[i].area + effects[i].description
  if (cloned.effects) {
    cloned.effects.forEach((eff, i) => {
      maybeAttachMai(eff.area, `${slug}.effects.${i}.area`);
      maybeAttachMai(eff.description, `${slug}.effects.${i}.description`);
    });
  }

  // cancellations[i]
  if (cloned.cancellations) {
    cloned.cancellations.forEach((c, i) => {
      maybeAttachMai(c, `${slug}.cancellations.${i}`);
    });
  }

  // remedies
  if (cloned.remedies) {
    maybeAttachMai(cloned.remedies.gemstone, `${slug}.remedies.gemstone`);
    maybeAttachMai(cloned.remedies.charity, `${slug}.remedies.charity`);
    // mantra is Sanskrit — intentionally not translated.
  }

  return cloned;
}

/**
 * YOGA_DETAIL_DATA with Maithili translations merged in from
 * yoga-mai-overlay.json. For yogas with no overlay entries (or when
 * the overlay file is empty), the result is structurally identical
 * to the imported YOGA_DETAIL_DATA — `tl()` falls back to .en.
 */
export const YOGA_DETAIL_DATA_WITH_OVERLAY: Readonly<Record<string, YogaDetailEntry>> = Object.freeze(
  Object.fromEntries(
    Object.entries(YOGA_DETAIL_DATA).map(([slug, yoga]) => [slug, mergeMaithiliInto(slug, yoga)]),
  ),
);

/** Re-export the canonical type so consumers don't need a second import. */
export type { YogaDetailEntry, YogaChartPosition } from './yoga-details';
