import { Yoga } from '@/types/panchang';

export const YOGAS: Yoga[] = [
  { number: 1, name: { en: 'Vishkambha', hi: 'विष्कम्भ', sa: 'विष्कम्भः', ta: 'விஷ்கம்பம்' }, nature: 'inauspicious', meaning: { en: 'Obstacle', hi: 'बाधा', sa: 'बाधा', ta: 'தடை' } },
  { number: 2, name: { en: 'Priti', hi: 'प्रीति', sa: 'प्रीतिः', ta: 'பிரீதி' }, nature: 'auspicious', meaning: { en: 'Love', hi: 'प्रेम', sa: 'प्रेम', ta: 'அன்பு' } },
  { number: 3, name: { en: 'Ayushman', hi: 'आयुष्मान्', sa: 'आयुष्मान्', ta: 'ஆயுஷ்மான்' }, nature: 'auspicious', meaning: { en: 'Long life', hi: 'दीर्घ आयु', sa: 'दीर्घायुः', ta: 'நீண்ட ஆயுள்' } },
  { number: 4, name: { en: 'Saubhagya', hi: 'सौभाग्य', sa: 'सौभाग्यम्', ta: 'சௌபாக்கியம்' }, nature: 'auspicious', meaning: { en: 'Good fortune', hi: 'सौभाग्य', sa: 'सौभाग्यम्', ta: 'நல்ல அதிர்ஷ்டம்' } },
  { number: 5, name: { en: 'Shobhana', hi: 'शोभन', sa: 'शोभनम्', ta: 'சோபனம்' }, nature: 'auspicious', meaning: { en: 'Splendor', hi: 'शोभा', sa: 'शोभा', ta: 'பிரகாசம்' } },
  { number: 6, name: { en: 'Atiganda', hi: 'अतिगण्ड', sa: 'अतिगण्डः', ta: 'அதிகண்டம்' }, nature: 'inauspicious', meaning: { en: 'Great danger', hi: 'महा संकट', sa: 'महासङ्कटः', ta: 'பெரும் ஆபத்து' } },
  { number: 7, name: { en: 'Sukarma', hi: 'सुकर्मा', sa: 'सुकर्मा', ta: 'சுகர்மா' }, nature: 'auspicious', meaning: { en: 'Good deeds', hi: 'शुभ कर्म', sa: 'शुभकर्म', ta: 'நற்செயல்' } },
  { number: 8, name: { en: 'Dhriti', hi: 'धृति', sa: 'धृतिः', ta: 'திருதி' }, nature: 'auspicious', meaning: { en: 'Firmness', hi: 'धैर्य', sa: 'धैर्यम्', ta: 'உறுதி' } },
  { number: 9, name: { en: 'Shula', hi: 'शूल', sa: 'शूलम्', ta: 'சூலம்' }, nature: 'inauspicious', meaning: { en: 'Thorn/Pain', hi: 'कष्ट', sa: 'कष्टम्', ta: 'வலி' } },
  { number: 10, name: { en: 'Ganda', hi: 'गण्ड', sa: 'गण्डः', ta: 'கண்டம்' }, nature: 'inauspicious', meaning: { en: 'Danger', hi: 'संकट', sa: 'सङ्कटः', ta: 'ஆபத்து' } },
  { number: 11, name: { en: 'Vriddhi', hi: 'वृद्धि', sa: 'वृद्धिः', ta: 'விருத்தி' }, nature: 'auspicious', meaning: { en: 'Growth', hi: 'वृद्धि', sa: 'वृद्धिः', ta: 'வளர்ச்சி' } },
  { number: 12, name: { en: 'Dhruva', hi: 'ध्रुव', sa: 'ध्रुवः', ta: 'த்ருவம்' }, nature: 'auspicious', meaning: { en: 'Constant', hi: 'स्थिर', sa: 'स्थिरम्', ta: 'நிலையான' } },
  { number: 13, name: { en: 'Vyaghata', hi: 'व्याघात', sa: 'व्याघातः', ta: 'வியாகாதம்' }, nature: 'inauspicious', meaning: { en: 'Calamity', hi: 'विपत्ति', sa: 'विपत्तिः', ta: 'பேரிடர்' } },
  { number: 14, name: { en: 'Harshana', hi: 'हर्षण', sa: 'हर्षणम्', ta: 'ஹர்ஷணம்' }, nature: 'auspicious', meaning: { en: 'Joy', hi: 'हर्ष', sa: 'हर्षः', ta: 'மகிழ்ச்சி' } },
  { number: 15, name: { en: 'Vajra', hi: 'वज्र', sa: 'वज्रम्', ta: 'வஜ்ரம்' }, nature: 'neutral', meaning: { en: 'Thunderbolt', hi: 'वज्र', sa: 'वज्रम्', ta: 'வஜ்ராயுதம்' } },
  { number: 16, name: { en: 'Siddhi', hi: 'सिद्धि', sa: 'सिद्धिः', ta: 'சித்தி' }, nature: 'auspicious', meaning: { en: 'Accomplishment', hi: 'सिद्धि', sa: 'सिद्धिः', ta: 'சாதனை' } },
  { number: 17, name: { en: 'Vyatipata', hi: 'व्यतीपात', sa: 'व्यतीपातः', ta: 'வியதீபாதம்' }, nature: 'inauspicious', meaning: { en: 'Misfortune', hi: 'दुर्भाग्य', sa: 'दुर्भाग्यम्', ta: 'துர்பாக்கியம்' } },
  { number: 18, name: { en: 'Variyan', hi: 'वरीयान्', sa: 'वरीयान्', ta: 'வரீயான்' }, nature: 'auspicious', meaning: { en: 'Excellent', hi: 'श्रेष्ठ', sa: 'श्रेष्ठम्', ta: 'சிறந்த' } },
  { number: 19, name: { en: 'Parigha', hi: 'परिघ', sa: 'परिघः', ta: 'பரிகம்' }, nature: 'inauspicious', meaning: { en: 'Obstruction', hi: 'अवरोध', sa: 'अवरोधः', ta: 'தடங்கல்' } },
  { number: 20, name: { en: 'Shiva', hi: 'शिव', sa: 'शिवम्', ta: 'சிவம்' }, nature: 'auspicious', meaning: { en: 'Auspicious', hi: 'शुभ', sa: 'शुभम्', ta: 'சுபம்' } },
  { number: 21, name: { en: 'Siddha', hi: 'सिद्ध', sa: 'सिद्धः', ta: 'சித்தம்' }, nature: 'auspicious', meaning: { en: 'Accomplished', hi: 'सिद्ध', sa: 'सिद्धः', ta: 'நிறைவேறிய' } },
  { number: 22, name: { en: 'Sadhya', hi: 'साध्य', sa: 'साध्यम्', ta: 'சாத்தியம்' }, nature: 'auspicious', meaning: { en: 'Achievable', hi: 'साध्य', sa: 'साध्यम्', ta: 'அடையக்கூடிய' } },
  { number: 23, name: { en: 'Shubha', hi: 'शुभ', sa: 'शुभम्', ta: 'சுபம்' }, nature: 'auspicious', meaning: { en: 'Auspicious', hi: 'शुभ', sa: 'शुभम्', ta: 'சுபம்' } },
  { number: 24, name: { en: 'Shukla', hi: 'शुक्ल', sa: 'शुक्लम्', ta: 'சுக்லம்' }, nature: 'auspicious', meaning: { en: 'Bright', hi: 'उज्ज्वल', sa: 'उज्ज्वलम्', ta: 'ஒளிர்வான' } },
  { number: 25, name: { en: 'Brahma', hi: 'ब्रह्म', sa: 'ब्रह्म', ta: 'பிரம்மம்' }, nature: 'auspicious', meaning: { en: 'Divine', hi: 'दिव्य', sa: 'दिव्यम्', ta: 'தெய்வீகம்' } },
  { number: 26, name: { en: 'Indra', hi: 'ऐन्द्र', sa: 'ऐन्द्रम्', ta: 'ஐந்திரம்' }, nature: 'auspicious', meaning: { en: 'Powerful', hi: 'शक्तिशाली', sa: 'शक्तिमत्', ta: 'சக்திவாய்ந்த' } },
  { number: 27, name: { en: 'Vaidhriti', hi: 'वैधृति', sa: 'वैधृतिः', ta: 'வைத்ருதி' }, nature: 'inauspicious', meaning: { en: 'Inauspicious', hi: 'अशुभ', sa: 'अशुभम्', ta: 'அசுபம்' } },
];
