import jsPDF from 'jspdf';
import type { KundaliData, PlanetPosition } from '@/types/kundali';
import type { Locale } from '@/types/panchang';
import type { TippanniContent } from '@/lib/kundali/tippanni-types';
import { GRAHAS, GRAHA_ABBREVIATIONS } from '@/lib/constants/grahas';
import { RASHIS } from '@/lib/constants/rashis';
import { computePersonalTransits, computeUpcomingTransitions } from '@/lib/transit/personal-transits';
import type { ConvergenceResult } from '@/lib/tippanni/convergence/types';

// ─── Theme constants ────────────────────────────────────────────────────────
const GOLD = '#d4a853';
const GOLD_LIGHT = '#f0d48a';
const NAVY = '#0a0e27';
const NAVY_ROW = '#0e122d';
const NAVY_HEADER = '#111638';
const TEXT_PRIMARY = '#e8e6e3';
const TEXT_SECONDARY = '#9b97a0';

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 14;
const CONTENT_W = PAGE_W - 2 * MARGIN;
const MAX_Y = 265;

// ─── Helpers ────────────────────────────────────────────────────────────────

let pageNum = 1;

function t(obj: { en: string; hi?: string; sa?: string } | undefined, locale: Locale): string {
  if (!obj) return '-';
  return (obj as Record<string, string>)[locale] || obj.en || '-';
}

function addPageBackground(doc: jsPDF) {
  doc.setFillColor(10, 14, 39);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.5);
  doc.rect(8, 8, PAGE_W - 16, PAGE_H - 16);
}

function addPageFooter(doc: jsPDF, pn: number) {
  doc.setFontSize(7);
  doc.setTextColor(155, 151, 160);
  doc.text('Generated by Dekho Panchang — dekhopanchang.com', PAGE_W / 2, 285, { align: 'center' });
  doc.text(`Page ${pn}`, PAGE_W - MARGIN - 2, 285, { align: 'right' });
}

function addContinuationHeader(doc: jsPDF): number {
  doc.setFontSize(11);
  doc.setTextColor(212, 168, 83);
  doc.text('Dekho Panchang — Kundali Report (continued)', PAGE_W / 2, 22, { align: 'center' });
  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.2);
  doc.line(30, 26, 180, 26);
  return 34;
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > MAX_Y) {
    addPageFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    addPageBackground(doc);
    return addContinuationHeader(doc);
  }
  return y;
}

function goldHeading(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(13);
  doc.setTextColor(212, 168, 83);
  doc.text(text, MARGIN, y);
  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y + 2, MARGIN + CONTENT_W, y + 2);
  return y + 8;
}

function subHeading(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(10);
  doc.setTextColor(240, 212, 138);
  doc.text(text, MARGIN, y);
  return y + 6;
}

function drawTableHeader(doc: jsPDF, headers: string[], colWidths: number[], y: number): number {
  doc.setFillColor(17, 22, 56);
  doc.rect(MARGIN, y - 4, CONTENT_W, 7, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(212, 168, 83);
  let x = MARGIN;
  headers.forEach((h, i) => {
    doc.text(h, x + 1, y);
    x += colWidths[i];
  });
  return y + 7;
}

function drawTableRow(doc: jsPDF, cells: string[], colWidths: number[], y: number, isEven: boolean): number {
  if (isEven) {
    doc.setFillColor(14, 18, 45);
    doc.rect(MARGIN, y - 4, CONTENT_W, 6.5, 'F');
  }
  doc.setFontSize(7);
  doc.setTextColor(232, 230, 227);
  let x = MARGIN;
  cells.forEach((cell, i) => {
    doc.text(cell.substring(0, Math.floor(colWidths[i] / 1.8)), x + 1, y);
    x += colWidths[i];
  });
  return y + 6.5;
}

function wrapText(doc: jsPDF, text: string, maxWidth: number, fontSize: number): string[] {
  doc.setFontSize(fontSize);
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (doc.getTextWidth(test) > maxWidth) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function drawWrappedText(doc: jsPDF, text: string, y: number, maxWidth: number, fontSize: number, color: string): number {
  const [r, g, b] = hexToRgb(color);
  doc.setTextColor(r, g, b);
  const lines = wrapText(doc, text, maxWidth, fontSize);
  for (const line of lines) {
    y = ensureSpace(doc, y, 5);
    doc.text(line, MARGIN + 2, y);
    y += 4.5;
  }
  return y;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)];
}

// ─── Page 1: Cover + Birth Details + Planet Positions ───────────────────────

function renderPage1(doc: jsPDF, kundali: KundaliData, locale: Locale): number {
  addPageBackground(doc);

  // Title
  doc.setFontSize(24);
  doc.setTextColor(212, 168, 83);
  doc.text('Dekho Panchang', PAGE_W / 2, 25, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(240, 212, 138);
  doc.text('Kundali Report', PAGE_W / 2, 33, { align: 'center' });

  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.3);
  doc.line(30, 38, 180, 38);

  // Birth details
  const bd = kundali.birthData;
  doc.setFontSize(10);
  doc.setTextColor(232, 230, 227);
  const details = [
    `Name: ${bd.name}`,
    `Date: ${bd.date}  |  Time: ${bd.time}`,
    `Place: ${bd.place} (${bd.lat.toFixed(4)}, ${bd.lng.toFixed(4)})`,
    `Ayanamsha: ${bd.ayanamsha} (${kundali.ayanamshaValue.toFixed(4)})`,
  ];
  details.forEach((line, i) => {
    doc.text(line, PAGE_W / 2, 47 + i * 6, { align: 'center' });
  });

  // Ascendant
  let y = 73;
  doc.setFontSize(10);
  doc.setTextColor(240, 212, 138);
  const ascSign = t(kundali.ascendant.signName, locale);
  const ascDeg = kundali.ascendant.degree.toFixed(2);
  doc.text(`Ascendant: ${ascSign} ${ascDeg}°`, PAGE_W / 2, y, { align: 'center' });

  y = 82;
  y = goldHeading(doc, 'Planetary Positions', y);

  const headers = ['Planet', 'R', 'C', 'Sign', 'Degree', 'Nakshatra/Pada', 'House', 'Speed', 'Lat'];
  const colWidths = [22, 8, 8, 22, 22, 36, 14, 24, 26];
  y = drawTableHeader(doc, headers, colWidths, y);

  kundali.planets.forEach((p, idx) => {
    const row = [
      t(p.planet.name, locale),
      p.isRetrograde ? 'R' : '',
      p.isCombust ? 'C' : '',
      t(p.signName, locale),
      p.degree,
      `${t(p.nakshatra.name, locale)} / ${p.pada}`,
      `${p.house}`,
      p.speed.toFixed(4),
      p.latitude.toFixed(2),
    ];
    y = drawTableRow(doc, row, colWidths, y, idx % 2 === 0);
  });

  addPageFooter(doc, pageNum);
  return y;
}

// ─── Page 2: Graha Details (Extended) ───────────────────────────────────────

function renderPage2(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  // Graha Details
  if (kundali.grahaDetails && kundali.grahaDetails.length > 0) {
    y = goldHeading(doc, 'Graha Details (Extended)', y);
    const headers = ['Planet', 'R/C', 'Longitude', 'Nakshatra/Swami', 'Raw Long', 'Lat', 'RA', 'Dec', 'Speed'];
    const colWidths = [22, 10, 22, 36, 20, 18, 18, 18, 18];
    y = drawTableHeader(doc, headers, colWidths, y);

    kundali.grahaDetails.forEach((g, idx) => {
      const rc = [g.isRetrograde ? 'R' : '', g.isCombust ? 'C' : ''].filter(Boolean).join('/') || '-';
      const row = [
        t(g.planetName, locale),
        rc,
        g.signDegree,
        `${t(g.nakshatraName, locale)}/${t(g.nakshatraLord, locale)}`,
        g.longitude.toFixed(2),
        g.latitude.toFixed(2),
        g.rightAscension.toFixed(2),
        g.declination.toFixed(2),
        g.speed.toFixed(4),
      ];
      y = ensureSpace(doc, y, 7);
      y = drawTableRow(doc, row, colWidths, y, idx % 2 === 0);
    });
  } else {
    y = goldHeading(doc, 'Graha Details', y);
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Extended graha details not available for this chart.', MARGIN + 2, y);
    y += 8;
  }

  // Upagraha positions
  y += 4;
  if (kundali.upagrahas && kundali.upagrahas.length > 0) {
    y = ensureSpace(doc, y, 20);
    y = goldHeading(doc, 'Upagraha Positions', y);
    const uHeaders = ['Upagraha', 'Sign', 'Degree', 'Nakshatra', 'Longitude'];
    const uColWidths = [36, 30, 30, 40, 46];
    y = drawTableHeader(doc, uHeaders, uColWidths, y);

    kundali.upagrahas.forEach((u, idx) => {
      const row = [
        t(u.name, locale),
        t(u.signName, locale),
        u.degree,
        t(u.nakshatra, locale),
        u.longitude.toFixed(2),
      ];
      y = ensureSpace(doc, y, 7);
      y = drawTableRow(doc, row, uColWidths, y, idx % 2 === 0);
    });
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 3: House Cusps + Divisional Charts ────────────────────────────────

function renderPage3(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  // House Cusps
  y = goldHeading(doc, 'House Cusps', y);
  const hHeaders = ['House', 'Sign', 'Degree', 'Lord'];
  const hColWidths = [30, 46, 46, 60];
  y = drawTableHeader(doc, hHeaders, hColWidths, y);

  kundali.houses.forEach((h, idx) => {
    const row = [
      `${h.house}`,
      t(h.signName, locale),
      `${h.degree.toFixed(2)}°`,
      t(h.lordName, locale),
    ];
    y = ensureSpace(doc, y, 7);
    y = drawTableRow(doc, row, hColWidths, y, idx % 2 === 0);
  });

  y += 6;

  // Divisional Charts Overview
  y = ensureSpace(doc, y, 20);
  y = goldHeading(doc, 'Divisional Charts Overview', y);

  if (kundali.divisionalCharts && Object.keys(kundali.divisionalCharts).length > 0) {
    const abbr = GRAHA_ABBREVIATIONS;
    const entries = Object.entries(kundali.divisionalCharts);

    for (const [key, chart] of entries) {
      y = ensureSpace(doc, y, 14);

      const ascSignId = chart.ascendantSign;
      const ascRashi = RASHIS.find(r => r.id === ascSignId);
      const ascName = ascRashi ? t(ascRashi.name, locale) : `Sign ${ascSignId}`;

      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      const label = t(chart.label, locale);
      doc.text(`${key.toUpperCase()} (${label}) — Asc: ${ascName}`, MARGIN + 2, y);
      y += 5;

      // Compact house placements
      const parts: string[] = [];
      chart.houses.forEach((planetIds, hIdx) => {
        if (planetIds.length > 0) {
          const names = planetIds.map(pid => abbr[pid] || `P${pid}`).join(',');
          parts.push(`H${hIdx + 1}: ${names}`);
        }
      });
      const line = parts.length > 0 ? parts.join(' | ') : 'No planets placed';
      const wrapped = wrapText(doc, line, CONTENT_W - 4, 7);
      doc.setFontSize(7);
      doc.setTextColor(232, 230, 227);
      for (const wl of wrapped) {
        y = ensureSpace(doc, y, 5);
        doc.text(wl, MARGIN + 4, y);
        y += 4.5;
      }
      y += 2;
    }
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Divisional chart data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 4: Yogas ──────────────────────────────────────────────────────────

function renderPage4(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Yogas', y);

  if (kundali.yogasComplete && kundali.yogasComplete.length > 0) {
    const presentYogas = kundali.yogasComplete.filter(yg => yg.present);

    if (presentYogas.length === 0) {
      doc.setFontSize(8);
      doc.setTextColor(155, 151, 160);
      doc.text('No yogas detected in this chart.', MARGIN + 2, y);
      y += 8;
    } else {
      const yHeaders = ['Yoga Name', 'Category', 'Auspicious', 'Strength'];
      const yColWidths = [56, 40, 36, 50];
      y = drawTableHeader(doc, yHeaders, yColWidths, y);

      presentYogas.forEach((yg, idx) => {
        y = ensureSpace(doc, y, 7);
        const row = [
          t(yg.name, locale),
          yg.category,
          yg.isAuspicious ? 'Yes' : 'No',
          yg.strength,
        ];
        y = drawTableRow(doc, row, yColWidths, y, idx % 2 === 0);
      });
    }
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Yoga analysis data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 5: Shadbala ───────────────────────────────────────────────────────

function renderPage5(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Shadbala Strength', y);

  if (kundali.fullShadbala && kundali.fullShadbala.length > 0) {
    const sHeaders = ['Planet', 'Sthana', 'Dig', 'Kala', 'Chesta', 'Naisargika', 'Drik', 'Total', 'Rupas', 'Ratio'];
    const sColWidths = [22, 17, 17, 17, 17, 22, 17, 17, 17, 19];
    y = drawTableHeader(doc, sHeaders, sColWidths, y);

    kundali.fullShadbala.forEach((sb, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [
        sb.planet,
        sb.sthanaBala.toFixed(1),
        sb.digBala.toFixed(1),
        sb.kalaBala.toFixed(1),
        sb.cheshtaBala.toFixed(1),
        sb.naisargikaBala.toFixed(1),
        sb.drikBala.toFixed(1),
        sb.totalPinda.toFixed(1),
        sb.rupas.toFixed(2),
        sb.strengthRatio.toFixed(2),
      ];
      y = drawTableRow(doc, row, sColWidths, y, idx % 2 === 0);
    });

    // Ishta/Kashta Phala
    y += 6;
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Ishta / Kashta Phala', y);
    const ikHeaders = ['Planet', 'Ishta Phala', 'Kashta Phala'];
    const ikColWidths = [60, 61, 61];
    y = drawTableHeader(doc, ikHeaders, ikColWidths, y);

    kundali.fullShadbala.forEach((sb, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [sb.planet, sb.ishtaPhala.toFixed(2), sb.kashtaPhala.toFixed(2)];
      y = drawTableRow(doc, row, ikColWidths, y, idx % 2 === 0);
    });

  } else if (kundali.shadbala && kundali.shadbala.length > 0) {
    // Fallback to basic shadbala
    const sHeaders = ['Planet', 'Sthana', 'Dig', 'Kala', 'Chesta', 'Naisargika', 'Drik', 'Total'];
    const sColWidths = [28, 22, 22, 22, 22, 26, 22, 18];
    y = drawTableHeader(doc, sHeaders, sColWidths, y);

    kundali.shadbala.forEach((sb, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [
        t(sb.planetName, locale),
        sb.sthanaBala.toFixed(1),
        sb.digBala.toFixed(1),
        sb.kalaBala.toFixed(1),
        sb.cheshtaBala.toFixed(1),
        sb.naisargikaBala.toFixed(1),
        sb.drikBala.toFixed(1),
        sb.totalStrength.toFixed(1),
      ];
      y = drawTableRow(doc, row, sColWidths, y, idx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Shadbala data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 6: Bhavabala ──────────────────────────────────────────────────────

function renderPage6(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Bhavabala (House Strength)', y);

  if (kundali.bhavabala && kundali.bhavabala.length > 0) {
    const bHeaders = ['Bhava', 'Lord', 'Lord Bala', 'Dig Bala', 'Drishti', 'Total', '%'];
    const bColWidths = [22, 30, 26, 26, 26, 26, 26];
    y = drawTableHeader(doc, bHeaders, bColWidths, y);

    kundali.bhavabala.forEach((bb, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [
        `${bb.bhava}`,
        bb.lordName,
        bb.bhavadhipatiBala.toFixed(1),
        bb.bhavaDigBala.toFixed(1),
        bb.bhavaDrishtiBala.toFixed(1),
        bb.total.toFixed(1),
        `${bb.strengthPercent.toFixed(1)}%`,
      ];
      y = drawTableRow(doc, row, bColWidths, y, idx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Bhavabala data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 7: Dasha Systems ──────────────────────────────────────────────────

function renderDashaSection(
  doc: jsPDF,
  title: string,
  dashas: { planetName?: { en: string; hi?: string; sa?: string }; planet?: string; signName?: { en: string; hi?: string; sa?: string }; startDate: string; endDate: string; level?: string; subPeriods?: unknown[] }[],
  locale: Locale,
  y: number,
  showAntar: boolean = false,
): number {
  y = ensureSpace(doc, y, 14);
  y = subHeading(doc, title, y);

  const mainEntries = dashas.filter(d => !('level' in d) || d.level === 'maha' || !d.level);

  mainEntries.forEach((md, idx) => {
    y = ensureSpace(doc, y, 7);
    const name = md.planetName ? t(md.planetName, locale) : (md.signName ? t(md.signName, locale) : (md.planet || '-'));

    if (idx % 2 === 0) {
      doc.setFillColor(14, 18, 45);
      doc.rect(MARGIN, y - 4, CONTENT_W, 6.5, 'F');
    }
    doc.setFontSize(8);
    doc.setTextColor(240, 212, 138);
    doc.text(name, MARGIN + 2, y);
    doc.setTextColor(155, 151, 160);
    doc.text(`${md.startDate} — ${md.endDate}`, 80, y);
    y += 6.5;

    // Antardasha sub-periods
    if (showAntar && md.subPeriods && Array.isArray(md.subPeriods)) {
      const subs = md.subPeriods as { planetName?: { en: string; hi?: string; sa?: string }; planet?: string; startDate: string; endDate: string }[];
      subs.forEach((sub) => {
        y = ensureSpace(doc, y, 6);
        const subName = sub.planetName ? t(sub.planetName, locale) : (sub.planet || '-');
        doc.setFontSize(6.5);
        doc.setTextColor(232, 230, 227);
        doc.text(`    ${subName}`, MARGIN + 6, y);
        doc.setTextColor(155, 151, 160);
        doc.text(`${sub.startDate} — ${sub.endDate}`, 80, y);
        y += 5.5;
      });
    }
  });

  return y + 4;
}

function renderPage7(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Dasha Systems', y);

  // Vimshottari Dasha with Mahadasha + Antardasha
  if (kundali.dashas && kundali.dashas.length > 0) {
    y = renderDashaSection(doc, 'Vimshottari Dasha', kundali.dashas, locale, y, true);
  }

  // Yogini Dasha
  if (kundali.yoginiDashas && kundali.yoginiDashas.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = renderDashaSection(doc, 'Yogini Dasha', kundali.yoginiDashas, locale, y, false);
  }

  // Ashtottari Dasha
  if (kundali.ashtottariDashas && kundali.ashtottariDashas.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = renderDashaSection(doc, 'Ashtottari Dasha', kundali.ashtottariDashas, locale, y, false);
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 8: Ashtakavarga ───────────────────────────────────────────────────

function renderPage8(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Ashtakavarga', y);

  if (kundali.ashtakavarga) {
    const av = kundali.ashtakavarga;

    // SAV table
    y = subHeading(doc, 'Sarvashtakavarga (SAV)', y);
    const signNames = RASHIS.map(r => t(r.name, locale).substring(0, 3));

    // Sign header row
    const savColW = CONTENT_W / 13;
    const savHeaders = ['', ...signNames];
    const savColWidths = Array(13).fill(savColW);
    y = drawTableHeader(doc, savHeaders, savColWidths, y);

    // SAV totals
    const savRow = ['Total', ...av.savTable.map(v => `${v}`)];
    y = drawTableRow(doc, savRow, savColWidths, y, true);

    y += 8;

    // BPI table
    y = ensureSpace(doc, y, 30);
    y = subHeading(doc, 'Bhinnashtakavarga (BPI)', y);

    const bpiColW = CONTENT_W / 13;
    const bpiHeaders = ['Planet', ...signNames];
    const bpiColWidths = Array(13).fill(bpiColW);
    y = drawTableHeader(doc, bpiHeaders, bpiColWidths, y);

    av.bpiTable.forEach((row, pIdx) => {
      y = ensureSpace(doc, y, 7);
      const planetName = av.planetNames[pIdx] || GRAHAS[pIdx]?.name?.en || `P${pIdx}`;
      const cells = [planetName.substring(0, 4), ...row.map(v => `${v}`)];
      y = drawTableRow(doc, cells, bpiColWidths, y, pIdx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Ashtakavarga data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 9: Jaimini System ─────────────────────────────────────────────────

function renderPage9(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Jaimini System', y);

  if (kundali.jaimini) {
    const j = kundali.jaimini;

    // Chara Karakas
    y = subHeading(doc, 'Chara Karakas', y);
    const ckHeaders = ['Planet', 'Karaka', 'Degree'];
    const ckColWidths = [60, 60, 62];
    y = drawTableHeader(doc, ckHeaders, ckColWidths, y);

    j.charaKarakas.forEach((ck, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [
        t(ck.planetName, locale),
        t(ck.karakaName, locale),
        ck.degree.toFixed(2),
      ];
      y = drawTableRow(doc, row, ckColWidths, y, idx % 2 === 0);
    });

    y += 6;

    // Karakamsha
    y = ensureSpace(doc, y, 12);
    y = subHeading(doc, 'Karakamsha', y);
    doc.setFontSize(8);
    doc.setTextColor(232, 230, 227);
    doc.text(`Karakamsha Sign: ${t(j.karakamsha.signName, locale)}`, MARGIN + 2, y);
    y += 8;

    // Arudha Padas
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Arudha Padas', y);
    const apHeaders = ['House', 'Label', 'Sign'];
    const apColWidths = [40, 72, 70];
    y = drawTableHeader(doc, apHeaders, apColWidths, y);

    j.arudhaPadas.forEach((ap, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [`${ap.house}`, t(ap.label, locale), t(ap.signName, locale)];
      y = drawTableRow(doc, row, apColWidths, y, idx % 2 === 0);
    });

    y += 6;

    // Chara Dasha
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Chara Dasha', y);
    const cdHeaders = ['Sign', 'Years', 'Start', 'End'];
    const cdColWidths = [46, 30, 53, 53];
    y = drawTableHeader(doc, cdHeaders, cdColWidths, y);

    j.charaDasha.forEach((cd, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [t(cd.signName, locale), `${cd.years}`, cd.startDate, cd.endDate];
      y = drawTableRow(doc, row, cdColWidths, y, idx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Jaimini system data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ─── Sade Sati Analysis ─────────────────────────────────────────────────────

function renderSadeSati(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Sade Sati Analysis', y);

  const ss = kundali.sadeSati!;
  const lk = (locale === 'hi' || locale === 'sa') ? 'hi' as const : 'en' as const;

  // Status
  if (ss.isActive) {
    const phaseLabel = ss.currentPhase === 'rising' ? 'Rising' : ss.currentPhase === 'peak' ? 'Peak' : 'Setting';
    y = subHeading(doc, `Status: ACTIVE — ${phaseLabel} Phase`, y);
    doc.setFontSize(8);
    doc.setTextColor(232, 230, 227);
    doc.text(`Cycle: ${ss.cycleStart} — ${ss.cycleEnd}  |  Progress: ${Math.round(ss.phaseProgress * 100)}%`, MARGIN + 2, y);
    y += 7;

    // Intensity
    y = ensureSpace(doc, y, 12);
    y = subHeading(doc, `Intensity: ${ss.overallIntensity.toFixed(1)} / 10`, y);

    if (ss.intensityFactors.length > 0) {
      ss.intensityFactors.forEach(f => {
        y = ensureSpace(doc, y, 5);
        doc.setFontSize(7);
        doc.setTextColor(155, 151, 160);
        doc.text(`  ${f.description[lk]}  —  ${f.score.toFixed(0)}/10`, MARGIN + 2, y);
        y += 4.5;
      });
      y += 3;
    }
  } else {
    y = subHeading(doc, 'Status: Not Active', y);
    const nextCycle = ss.allCycles.find(c => !c.isActive && c.startYear > new Date().getFullYear());
    if (nextCycle) {
      doc.setFontSize(8);
      doc.setTextColor(232, 230, 227);
      doc.text(`Next cycle: ${nextCycle.startYear} — ${nextCycle.endYear}`, MARGIN + 2, y);
      y += 7;
    }
  }

  // Summary interpretation
  const summary = ss.interpretation.summary[lk];
  if (summary) {
    y = ensureSpace(doc, y, 15);
    y = subHeading(doc, 'Summary', y);
    y = drawWrappedText(doc, summary, y, CONTENT_W - 4, 7.5, TEXT_PRIMARY);
    y += 4;
  }

  // Saturn nature + moon strength (if active)
  if (ss.isActive) {
    const saturnText = ss.interpretation.saturnNature[lk];
    if (saturnText) {
      y = ensureSpace(doc, y, 15);
      y = subHeading(doc, "Saturn's Nature for Ascendant", y);
      y = drawWrappedText(doc, saturnText, y, CONTENT_W - 4, 7.5, TEXT_PRIMARY);
      y += 4;
    }
    const moonText = ss.interpretation.moonStrength[lk];
    if (moonText) {
      y = ensureSpace(doc, y, 15);
      y = subHeading(doc, 'Moon Strength', y);
      y = drawWrappedText(doc, moonText, y, CONTENT_W - 4, 7.5, TEXT_PRIMARY);
      y += 4;
    }
  }

  // Timeline — compact
  if (ss.allCycles.length > 0) {
    y = ensureSpace(doc, y, 15);
    y = subHeading(doc, 'Timeline', y);
    ss.allCycles.forEach(cycle => {
      y = ensureSpace(doc, y, 5);
      doc.setFontSize(7.5);
      const activePhase = cycle.isActive && ss.currentPhase ? ` [ACTIVE - ${ss.currentPhase.charAt(0).toUpperCase() + ss.currentPhase.slice(1)}]` : '';
      if (cycle.isActive) {
        doc.setTextColor(212, 168, 83);
      } else {
        doc.setTextColor(155, 151, 160);
      }
      doc.text(`${cycle.startYear} — ${cycle.endYear}${activePhase}`, MARGIN + 2, y);
      y += 5;
    });
    y += 3;
  }

  // Remedies (if active)
  if (ss.isActive && ss.remedies.length > 0) {
    y = ensureSpace(doc, y, 15);
    y = subHeading(doc, 'Remedies', y);

    for (const r of ss.remedies) {
      y = ensureSpace(doc, y, 12);
      const priorityTag = `[${r.priority.toUpperCase()}]`;
      doc.setFontSize(7.5);
      doc.setTextColor(240, 212, 138);
      doc.text(`${priorityTag} ${r.title[lk]}`, MARGIN + 2, y);
      y += 4.5;
      y = drawWrappedText(doc, r.description[lk], y, CONTENT_W - 8, 7, TEXT_SECONDARY);
      y += 2;
    }
  }

  addPageFooter(doc, pageNum);
}

// ─── Transit Radar ─────────────────────────────────────────────────────────

function renderTransitRadar(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Current Transit Analysis', y);

  const ascSign = kundali.ascendant.sign;
  const savTable = kundali.ashtakavarga?.savTable;

  if (!savTable || !ascSign) {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('Transit analysis requires Ashtakavarga data. Not available for this chart.', MARGIN + 2, y);
    y += 8;
    addPageFooter(doc, pageNum);
    return;
  }

  const transits = computePersonalTransits(ascSign, savTable);

  if (transits.length === 0) {
    doc.setFontSize(8);
    doc.setTextColor(155, 151, 160);
    doc.text('No transit data computed.', MARGIN + 2, y);
    y += 8;
    addPageFooter(doc, pageNum);
    return;
  }

  // Transit table
  const tHeaders = ['Planet', 'Sign', 'House', 'SAV Bindus', 'Quality'];
  const tColWidths = [36, 36, 24, 30, 56];
  y = drawTableHeader(doc, tHeaders, tColWidths, y);

  transits.forEach((tr, idx) => {
    y = ensureSpace(doc, y, 7);
    const qualityLabel = tr.quality === 'strong' ? 'Favorable'
      : tr.quality === 'weak' ? 'Challenging' : 'Moderate';
    const row = [
      t(tr.planetName, locale),
      t(tr.signName, locale),
      `${tr.house}`,
      `${tr.savBindu}`,
      qualityLabel,
    ];

    // Custom row with quality color
    const isEven = idx % 2 === 0;
    if (isEven) {
      doc.setFillColor(14, 18, 45);
      doc.rect(MARGIN, y - 4, CONTENT_W, 6.5, 'F');
    }
    doc.setFontSize(7);
    doc.setTextColor(232, 230, 227);
    let x = MARGIN;
    row.forEach((cell, ci) => {
      if (ci === 4) {
        // Color the quality text
        if (tr.quality === 'strong') {
          doc.setTextColor(100, 200, 120); // green
        } else if (tr.quality === 'weak') {
          doc.setTextColor(220, 100, 100); // red
        } else {
          doc.setTextColor(212, 168, 83); // gold for neutral
        }
      }
      doc.text(cell.substring(0, Math.floor(tColWidths[ci] / 1.8)), x + 1, y);
      if (ci === 4) {
        doc.setTextColor(232, 230, 227); // reset
      }
      x += tColWidths[ci];
    });
    y += 6.5;
  });

  // Interpretations
  y += 4;
  y = ensureSpace(doc, y, 14);
  y = subHeading(doc, 'Transit Interpretations', y);

  transits.forEach(tr => {
    y = ensureSpace(doc, y, 10);
    const interp = t(tr.interpretation, locale);
    y = drawWrappedText(doc, interp, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
    y += 2;
  });

  // Upcoming transitions
  const upcoming = computeUpcomingTransitions();
  if (upcoming.length > 0) {
    y += 4;
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Upcoming Sign Changes', y);

    const uHeaders = ['Planet', 'From', 'To', 'Approx. Date'];
    const uColWidths = [40, 40, 40, 62];
    y = drawTableHeader(doc, uHeaders, uColWidths, y);

    upcoming.forEach((u, idx) => {
      y = ensureSpace(doc, y, 7);
      const row = [
        t(u.planetName, locale),
        t(u.fromSign, locale),
        t(u.toSign, locale),
        u.approximateDate,
      ];
      y = drawTableRow(doc, row, uColWidths, y, idx % 2 === 0);
    });
  }

  addPageFooter(doc, pageNum);
}

// ─── Convergence Insights ──────────────────────────────────────────────────

function renderConvergenceInsights(doc: jsPDF, convergence: ConvergenceResult, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Chart Synthesis — Convergence Insights', y);

  const lk = (locale === 'hi' || locale === 'sa') ? 'hi' as const : 'en' as const;
  const exec = convergence.executive;

  // Overall tone
  const toneLabel = exec.tone.charAt(0).toUpperCase() + exec.tone.slice(1);
  doc.setFontSize(9);
  doc.setTextColor(240, 212, 138);
  doc.text(`Overall Tone: ${toneLabel}  |  Activation: ${exec.activation}/10  |  Favorability: ${exec.favorability}/10`, MARGIN + 2, y);
  y += 8;

  // Executive insights
  if (exec.insights.length > 0) {
    y = subHeading(doc, 'Key Insights', y);

    exec.insights.forEach(ins => {
      y = ensureSpace(doc, y, 16);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(`${ins.theme} (${ins.temporalFrame})`, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, ins.summary[lk], y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      if (ins.advice[lk]) {
        y = drawWrappedText(doc, `Advice: ${ins.advice[lk]}`, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
      }
      y += 3;
    });
  }

  // Urgent flags
  if (exec.urgentFlags.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Urgent Flags', y);

    exec.urgentFlags.forEach(flag => {
      y = ensureSpace(doc, y, 10);
      const severityLabel = flag.severity === 3 ? 'HIGH' : flag.severity === 2 ? 'MEDIUM' : 'LOW';
      doc.setFontSize(7.5);
      // Color by severity
      if (flag.severity === 3) {
        doc.setTextColor(220, 100, 100);
      } else if (flag.severity === 2) {
        doc.setTextColor(212, 168, 83);
      } else {
        doc.setTextColor(155, 151, 160);
      }
      doc.text(`[${severityLabel}]`, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, flag.message[lk], y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 2;
    });
  }

  // Meta-insights (convergence interactions)
  if (exec.metaInsights.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Meta-Interactions', y);

    exec.metaInsights.forEach(mi => {
      y = ensureSpace(doc, y, 10);
      const severityLabel = mi.severity === 3 ? 'HIGH' : mi.severity === 2 ? 'MEDIUM' : 'LOW';
      doc.setFontSize(7.5);
      if (mi.severity === 3) {
        doc.setTextColor(220, 100, 100);
      } else if (mi.severity === 2) {
        doc.setTextColor(212, 168, 83);
      } else {
        doc.setTextColor(155, 151, 160);
      }
      doc.text(`[${severityLabel}]`, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, mi.text[lk], y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 3;
    });
  }

  addPageFooter(doc, pageNum);
}

// ─── Page 10+: Tippanni (Interpretations) ───────────────────────────────────

function renderTippanni(doc: jsPDF, tippanni: TippanniContent, locale: Locale) {
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  let y = addContinuationHeader(doc);

  y = goldHeading(doc, 'Tippanni — Interpretive Analysis', y);

  // Personality
  if (tippanni.personality) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Personality', y);

    const pers = tippanni.personality;
    if (pers.lagna) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(pers.lagna.title, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, pers.lagna.content, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 2;
    }
    if (pers.moonSign) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(pers.moonSign.title, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, pers.moonSign.content, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 2;
    }
    if (pers.sunSign) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(pers.sunSign.title, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, pers.sunSign.content, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 2;
    }
    if (pers.summary) {
      y = ensureSpace(doc, y, 10);
      y = drawWrappedText(doc, pers.summary, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
      y += 4;
    }
  }

  // Planet Insights
  if (tippanni.planetInsights && tippanni.planetInsights.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Planet Insights', y);

    tippanni.planetInsights.forEach(pi => {
      y = ensureSpace(doc, y, 16);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(`${pi.planetName} in ${pi.signName} (House ${pi.house})`, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, pi.description, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      if (pi.implications) {
        y = drawWrappedText(doc, pi.implications, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
      }
      if (pi.retrogradeEffect) {
        y = drawWrappedText(doc, `Retrograde: ${pi.retrogradeEffect}`, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
      }
      y += 3;
    });
  }

  // Yoga Insights
  if (tippanni.yogas && tippanni.yogas.length > 0) {
    const presentYogas = tippanni.yogas.filter(yg => yg.present);
    if (presentYogas.length > 0) {
      y = ensureSpace(doc, y, 14);
      y = subHeading(doc, 'Yoga Insights', y);

      presentYogas.forEach(yg => {
        y = ensureSpace(doc, y, 12);
        doc.setFontSize(8);
        doc.setTextColor(240, 212, 138);
        doc.text(`${yg.name} (${yg.type}, ${yg.strength})`, MARGIN + 2, y);
        y += 5;
        y = drawWrappedText(doc, yg.description, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
        if (yg.implications) {
          y = drawWrappedText(doc, yg.implications, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
        }
        y += 2;
      });
    }
  }

  // Dosha Insights
  if (tippanni.doshas && tippanni.doshas.length > 0) {
    const presentDoshas = tippanni.doshas.filter(d => d.present);
    if (presentDoshas.length > 0) {
      y = ensureSpace(doc, y, 14);
      y = subHeading(doc, 'Dosha Insights', y);

      presentDoshas.forEach(d => {
        y = ensureSpace(doc, y, 12);
        doc.setFontSize(8);
        doc.setTextColor(240, 212, 138);
        doc.text(`${d.name} — Severity: ${d.severity}`, MARGIN + 2, y);
        y += 5;
        y = drawWrappedText(doc, d.description, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
        if (d.remedies) {
          y = drawWrappedText(doc, `Remedies: ${d.remedies}`, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
        }
        y += 2;
      });
    }
  }

  // Life Areas
  if (tippanni.lifeAreas) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Life Areas', y);

    const areas = tippanni.lifeAreas;
    const areaList: { label: string; data: typeof areas.career }[] = [
      { label: 'Career', data: areas.career },
      { label: 'Wealth', data: areas.wealth },
      { label: 'Marriage', data: areas.marriage },
      { label: 'Health', data: areas.health },
      { label: 'Education', data: areas.education },
    ];

    areaList.forEach(({ label, data }) => {
      if (!data) return;
      y = ensureSpace(doc, y, 12);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text(`${label} — Rating: ${data.rating}/10`, MARGIN + 2, y);
      y += 5;
      y = drawWrappedText(doc, data.summary, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
      y += 2;
    });
  }

  // Dasha Analysis
  if (tippanni.dashaInsight) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Dasha Analysis', y);

    const di = tippanni.dashaInsight;
    doc.setFontSize(8);
    doc.setTextColor(240, 212, 138);
    y = ensureSpace(doc, y, 8);
    doc.text(`Current Mahadasha: ${di.currentMaha}`, MARGIN + 2, y);
    y += 5;
    y = drawWrappedText(doc, di.currentMahaAnalysis, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
    y += 2;

    y = ensureSpace(doc, y, 8);
    doc.setFontSize(8);
    doc.setTextColor(240, 212, 138);
    doc.text(`Current Antardasha: ${di.currentAntar}`, MARGIN + 2, y);
    y += 5;
    y = drawWrappedText(doc, di.currentAntarAnalysis, y, CONTENT_W - 4, 7, TEXT_PRIMARY);
    y += 2;

    if (di.upcoming) {
      y = ensureSpace(doc, y, 8);
      y = drawWrappedText(doc, `Upcoming: ${di.upcoming}`, y, CONTENT_W - 4, 7, TEXT_SECONDARY);
      y += 2;
    }
  }

  // Remedies
  if (tippanni.remedies) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Remedies', y);

    const rem = tippanni.remedies;

    if (rem.gemstones && rem.gemstones.length > 0) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text('Gemstones:', MARGIN + 2, y);
      y += 5;
      rem.gemstones.forEach(g => {
        y = ensureSpace(doc, y, 8);
        y = drawWrappedText(doc, `${g.name} (${g.planet}): ${g.description}`, y, CONTENT_W - 8, 7, TEXT_PRIMARY);
        y += 1;
      });
      y += 2;
    }

    if (rem.mantras && rem.mantras.length > 0) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text('Mantras:', MARGIN + 2, y);
      y += 5;
      rem.mantras.forEach(m => {
        y = ensureSpace(doc, y, 8);
        y = drawWrappedText(doc, `${m.name} (${m.planet}): ${m.description}`, y, CONTENT_W - 8, 7, TEXT_PRIMARY);
        y += 1;
      });
      y += 2;
    }

    if (rem.practices && rem.practices.length > 0) {
      y = ensureSpace(doc, y, 10);
      doc.setFontSize(8);
      doc.setTextColor(240, 212, 138);
      doc.text('Practices:', MARGIN + 2, y);
      y += 5;
      rem.practices.forEach(p => {
        y = ensureSpace(doc, y, 8);
        y = drawWrappedText(doc, `${p.name} (${p.planet}): ${p.description}`, y, CONTENT_W - 8, 7, TEXT_PRIMARY);
        y += 1;
      });
    }
  }

  addPageFooter(doc, pageNum);
}

// ─── Main Export Function ───────────────────────────────────────────────────

export function exportKundaliPDF(
  kundali: KundaliData,
  locale: Locale = 'en',
  tippanni?: TippanniContent,
): void {
  pageNum = 1;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Page 1: Cover + Birth Details + Planet Positions
  renderPage1(doc, kundali, locale);

  // Page 2: Graha Details (Extended)
  renderPage2(doc, kundali, locale);

  // Page 3: House Cusps + Divisional Charts
  renderPage3(doc, kundali, locale);

  // Page 4: Yogas
  renderPage4(doc, kundali, locale);

  // Page 5: Shadbala
  renderPage5(doc, kundali, locale);

  // Page 6: Bhavabala
  renderPage6(doc, kundali, locale);

  // Page 7: Dasha Systems
  renderPage7(doc, kundali, locale);

  // Page 8: Ashtakavarga
  renderPage8(doc, kundali, locale);

  // Page 9: Jaimini System
  renderPage9(doc, kundali, locale);

  // Sade Sati Analysis
  if (kundali.sadeSati) {
    renderSadeSati(doc, kundali, locale);
  }

  // Transit Radar
  if (kundali.ashtakavarga?.savTable && kundali.ascendant?.sign) {
    renderTransitRadar(doc, kundali, locale);
  }

  // Convergence Insights
  if (tippanni?.convergence) {
    renderConvergenceInsights(doc, tippanni.convergence, locale);
  }

  // Page 10+: Tippanni (Interpretations)
  if (tippanni) {
    renderTippanni(doc, tippanni, locale);
  }

  // Save PDF
  const name = kundali.birthData.name.replace(/[^a-zA-Z0-9]/g, '_') || 'kundali';
  doc.save(`${name}_kundali_report.pdf`);
}
