import jsPDF from 'jspdf';
import type { PanchangData, Locale } from '@/types/panchang';
import { RASHIS } from '@/lib/constants/rashis';

export function exportPanchangPDF(data: PanchangData, locale: Locale = 'en') {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Background
  doc.setFillColor(10, 14, 39);
  doc.rect(0, 0, 210, 297, 'F');

  // Gold border
  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.5);
  doc.rect(8, 8, 194, 281);

  // Title
  doc.setTextColor(212, 168, 83);
  doc.setFontSize(24);
  doc.text('Daily Panchang', 105, 25, { align: 'center' });

  // Date & location
  doc.setFontSize(11);
  doc.setTextColor(240, 212, 138);
  const locationStr = typeof data.location === 'string' ? data.location : data.location?.name || '';
  doc.text(`${data.date} | ${locationStr}`, 105, 33, { align: 'center' });

  // Divider
  doc.setDrawColor(212, 168, 83);
  doc.setLineWidth(0.3);
  doc.line(30, 38, 180, 38);

  // Core panchang elements
  const elements = [
    ['Vara (Day)', data.vara.name[locale] || data.vara.name.en],
    ['Tithi', data.tithi.name[locale] || data.tithi.name.en],
    ['Nakshatra', data.nakshatra.name[locale] || data.nakshatra.name.en],
    ['Yoga', data.yoga.name[locale] || data.yoga.name.en],
    ['Karana', data.karana.name[locale] || data.karana.name.en],
    ['Sunrise', data.sunrise],
    ['Sunset', data.sunset],
  ];

  let y = 50;
  doc.setFontSize(10);

  elements.forEach(([label, value], idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(17, 22, 56);
      doc.rect(14, y - 4, 182, 8, 'F');
    }
    doc.setTextColor(212, 168, 83);
    doc.text(label, 20, y);
    doc.setTextColor(232, 230, 227);
    doc.text(value, 80, y);
    y += 8;
  });

  // Planet positions
  if (data.planets && data.planets.length > 0) {
    y += 8;
    doc.setFontSize(12);
    doc.setTextColor(212, 168, 83);
    doc.text('Planetary Positions', 14, y);
    y += 8;

    doc.setFontSize(8);
    data.planets.forEach((p, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(14, 18, 45);
        doc.rect(14, y - 4, 182, 6.5, 'F');
      }
      doc.setTextColor(240, 212, 138);
      doc.text(p.name[locale] || p.name.en, 16, y);
      doc.setTextColor(232, 230, 227);
      const sign = p.rashi != null && RASHIS[p.rashi - 1] ? (RASHIS[p.rashi - 1].name[locale] || RASHIS[p.rashi - 1].name.en) : '';
      const deg = p.longitude != null ? `${p.longitude.toFixed(2)}°` : '';
      doc.text(`${sign}  ${deg}  ${p.isRetrograde ? '(R)' : ''}`, 55, y);
      y += 6.5;
    });
  }

  // Muhurtas
  if (data.muhurtas && data.muhurtas.length > 0) {
    y += 8;
    if (y > 240) {
      doc.addPage();
      doc.setFillColor(10, 14, 39);
      doc.rect(0, 0, 210, 297, 'F');
      doc.setDrawColor(212, 168, 83);
      doc.setLineWidth(0.5);
      doc.rect(8, 8, 194, 281);
      y = 25;
    }

    doc.setFontSize(12);
    doc.setTextColor(212, 168, 83);
    doc.text('Muhurtas', 14, y);
    y += 8;

    doc.setFontSize(7.5);
    data.muhurtas.forEach((m, idx) => {
      if (y > 280) return; // safety
      if (idx % 2 === 0) {
        doc.setFillColor(14, 18, 45);
        doc.rect(14, y - 4, 182, 6, 'F');
      }
      doc.setTextColor(240, 212, 138);
      doc.text(m.name[locale] || m.name.en, 16, y);
      doc.setTextColor(155, 151, 160);
      doc.text(`${m.startTime} - ${m.endTime}`, 70, y);
      doc.setTextColor(232, 230, 227);
      const quality = m.nature === 'auspicious' ? 'Shubh' : m.nature === 'inauspicious' ? 'Ashubh' : 'Neutral';
      doc.text(quality, 120, y);
      y += 6;
    });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(155, 151, 160);
  doc.text('Generated by Dekho Panchang — dekhopanchang.com', 105, 285, { align: 'center' });

  doc.save(`panchang_${data.date}.pdf`);
}
