import jsPDF from 'jspdf';
import type { KundaliData, PlanetPosition } from '@/types/kundali';
import type { Locale } from '@/types/panchang';
import type { TippanniContent } from '@/lib/kundali/tippanni-types';
import { GRAHAS, GRAHA_ABBREVIATIONS } from '@/lib/constants/grahas';
import { RASHIS } from '@/lib/constants/rashis';
import { computePersonalTransits, computeUpcomingTransitions } from '@/lib/transit/personal-transits';
import type { ConvergenceResult } from '@/lib/tippanni/convergence/types';

// ─── Theme Constants ───────────────────────────────────────────────────────
const NAVY       = [10, 14, 39]   as const;  // #0a0e27
const NAVY_CARD  = [14, 18, 50]   as const;  // card fill
const NAVY_ROW   = [14, 18, 45]   as const;  // alternating rows
const NAVY_HDR   = [17, 22, 56]   as const;  // table header
const GOLD       = [212, 168, 83] as const;  // #d4a853
const GOLD_LIGHT = [240, 212, 138] as const; // #f0d48a
const GOLD_DARK  = [138, 109, 43] as const;  // #8a6d2b
const WHITE      = [232, 230, 227] as const; // text-primary
const MUTED      = [155, 151, 160] as const; // text-secondary
const GREEN      = [100, 200, 120] as const;
const RED        = [220, 100, 100] as const;
const BLUE       = [100, 160, 230] as const;
const AMBER      = [230, 180, 80]  as const;

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 14;
const CONTENT_W = PAGE_W - 2 * MARGIN;
const MAX_Y = 268;

// ─── State ─────────────────────────────────────────────────────────────────
let pageNum = 1;

// ─── Trilingual Helper ─────────────────────────────────────────────────────
function t(obj: { en: string; hi?: string; sa?: string } | undefined, locale: Locale): string {
  if (!obj) return '-';
  return (obj as Record<string, string>)[locale] || obj.en || '-';
}

// ─── Color Helpers ─────────────────────────────────────────────────────────
function setFill(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setFillColor(c[0], c[1], c[2]);
}
function setText(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setTextColor(c[0], c[1], c[2]);
}
function setDraw(doc: jsPDF, c: readonly [number, number, number]) {
  doc.setDrawColor(c[0], c[1], c[2]);
}

// ─── Page Infrastructure ───────────────────────────────────────────────────

function addPageBackground(doc: jsPDF) {
  setFill(doc, NAVY);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  // Thin gold border inset
  setDraw(doc, GOLD_DARK);
  doc.setLineWidth(0.3);
  doc.rect(8, 8, PAGE_W - 16, PAGE_H - 16);
}

function addPageFooter(doc: jsPDF, pn: number) {
  // Thin rule
  setDraw(doc, GOLD_DARK);
  doc.setLineWidth(0.15);
  doc.line(MARGIN, 280, PAGE_W - MARGIN, 280);
  doc.setFontSize(6.5);
  setText(doc, MUTED);
  doc.text('Generated by Dekho Panchang  |  dekhopanchang.com', PAGE_W / 2, 284, { align: 'center' });
  doc.text(`${pn}`, PAGE_W - MARGIN - 2, 284, { align: 'right' });
}

function addContinuationHeader(doc: jsPDF): number {
  doc.setFont('times', 'italic');
  doc.setFontSize(9);
  setText(doc, GOLD_DARK);
  doc.text('Dekho Panchang — Kundali Report', PAGE_W / 2, 18, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  setDraw(doc, GOLD_DARK);
  doc.setLineWidth(0.15);
  doc.line(40, 21, PAGE_W - 40, 21);
  return 30;
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > MAX_Y) {
    addPageFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    addPageBackground(doc);
    return addContinuationHeader(doc);
  }
  return y;
}

function newPage(doc: jsPDF): number {
  addPageFooter(doc, pageNum);
  doc.addPage();
  pageNum++;
  addPageBackground(doc);
  return addContinuationHeader(doc);
}

// ─── Drawing Primitives ────────────────────────────────────────────────────

function drawCard(
  doc: jsPDF, x: number, y: number, w: number, h: number,
  opts: { fill?: readonly [number, number, number]; border?: readonly [number, number, number]; radius?: number } = {},
) {
  const r = opts.radius ?? 2;
  if (opts.fill) {
    setFill(doc, opts.fill);
    doc.roundedRect(x, y, w, h, r, r, 'F');
  }
  if (opts.border) {
    setDraw(doc, opts.border);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, w, h, r, r, 'S');
  }
}

function drawBadge(
  doc: jsPDF, text: string, x: number, y: number,
  color: readonly [number, number, number],
) {
  doc.setFontSize(6);
  const tw = doc.getTextWidth(text) + 4;
  const h = 4.5;
  // Badge background (semi-transparent via darker shade)
  setFill(doc, [Math.round(color[0] * 0.3), Math.round(color[1] * 0.3), Math.round(color[2] * 0.3)]);
  doc.roundedRect(x, y - 3.2, tw, h, 1.2, 1.2, 'F');
  // Badge border
  setDraw(doc, color);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y - 3.2, tw, h, 1.2, 1.2, 'S');
  // Text
  setText(doc, color);
  doc.text(text, x + 2, y);
  return tw;
}

function drawBar(
  doc: jsPDF, x: number, y: number, value: number, maxWidth: number,
  color: readonly [number, number, number],
) {
  const barW = Math.max(2, Math.min(value, maxWidth));
  // Bar background track
  setFill(doc, NAVY_CARD);
  doc.roundedRect(x, y, maxWidth, 4, 1, 1, 'F');
  // Bar fill
  setFill(doc, color);
  doc.roundedRect(x, y, barW, 4, 1, 1, 'F');
}

function drawRatingDots(
  doc: jsPDF, rating: number, maxRating: number, x: number, y: number,
) {
  const dotR = 1.2;
  const gap = 4;
  for (let i = 0; i < maxRating; i++) {
    const cx = x + i * gap + dotR;
    if (i < rating) {
      setFill(doc, GOLD);
    } else {
      setFill(doc, GOLD_DARK);
    }
    doc.circle(cx, y, dotR, 'F');
  }
}

// ─── Text Helpers ──────────────────────────────────────────────────────────

function truncateToWidth(doc: jsPDF, text: string, maxWidth: number): string {
  if (doc.getTextWidth(text) <= maxWidth - 2) return text;
  let truncated = text;
  while (truncated.length > 0 && doc.getTextWidth(truncated + '...') > maxWidth - 2) {
    truncated = truncated.slice(0, -1);
  }
  return truncated + '...';
}

function wrapText(doc: jsPDF, text: string, maxWidth: number, fontSize: number): string[] {
  doc.setFontSize(fontSize);
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (doc.getTextWidth(test) > maxWidth) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines.length > 0 ? lines : [''];
}

function drawWrapped(
  doc: jsPDF, text: string, x: number, y: number, maxWidth: number,
  fontSize: number, color: readonly [number, number, number],
): number {
  setText(doc, color);
  const lines = wrapText(doc, text, maxWidth, fontSize);
  for (const line of lines) {
    y = ensureSpace(doc, y, 4.5);
    doc.text(line, x, y);
    y += 4.5;
  }
  return y;
}

// ─── Section Headings ──────────────────────────────────────────────────────

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  y = ensureSpace(doc, y, 12);
  doc.setFont('times', 'bold');
  doc.setFontSize(13);
  setText(doc, GOLD);
  doc.text(text, MARGIN, y);
  // Gold underline
  setDraw(doc, GOLD);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y + 2.5, MARGIN + CONTENT_W, y + 2.5);
  doc.setFont('helvetica', 'normal');
  return y + 10;
}

function subHeading(doc: jsPDF, text: string, y: number): number {
  y = ensureSpace(doc, y, 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  setText(doc, GOLD_LIGHT);
  doc.text(text, MARGIN + 1, y);
  doc.setFont('helvetica', 'normal');
  return y + 6;
}

// ─── Table Drawing ─────────────────────────────────────────────────────────

function drawTableHeader(doc: jsPDF, headers: string[], colWidths: number[], y: number): number {
  setFill(doc, NAVY_HDR);
  doc.roundedRect(MARGIN, y - 4.5, CONTENT_W, 8, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  setText(doc, GOLD);
  let x = MARGIN;
  headers.forEach((h, i) => {
    doc.text(truncateToWidth(doc, h, colWidths[i]), x + 2, y);
    x += colWidths[i];
  });
  doc.setFont('helvetica', 'normal');
  return y + 7;
}

function drawTableRow(doc: jsPDF, cells: string[], colWidths: number[], y: number, isEven: boolean): number {
  if (isEven) {
    setFill(doc, NAVY_ROW);
    doc.roundedRect(MARGIN, y - 4, CONTENT_W, 8, 0.5, 0.5, 'F');
  }
  doc.setFontSize(7);
  setText(doc, WHITE);
  let x = MARGIN;
  cells.forEach((cell, i) => {
    doc.text(truncateToWidth(doc, cell, colWidths[i]), x + 2, y);
    x += colWidths[i];
  });
  return y + 8;
}

// ─── North Indian Chart ────────────────────────────────────────────────────

function drawNorthChart(
  doc: jsPDF,
  chartData: { houses: number[][]; ascendantSign: number },
  x: number, y: number, size: number,
) {
  const cx = x + size / 2;
  const cy = y + size / 2;
  const half = size / 2;

  // Outer square
  setDraw(doc, GOLD);
  doc.setLineWidth(0.6);
  doc.rect(x, y, size, size);

  // Diamond (inner rotated square)
  doc.setLineWidth(0.4);
  // Top to Right
  doc.line(cx, y, x + size, cy);
  // Right to Bottom
  doc.line(x + size, cy, cx, y + size);
  // Bottom to Left
  doc.line(cx, y + size, x, cy);
  // Left to Top
  doc.line(x, cy, cx, y);

  // Cross lines for inner triangles
  // Top-left: horizontal and vertical
  doc.setLineWidth(0.25);
  setDraw(doc, GOLD_DARK);
  // Top horizontal
  doc.line(x, y, x + size, y);
  doc.line(x, y + size, x + size, y + size);
  doc.line(x, y, x, y + size);
  doc.line(x + size, y, x + size, y + size);

  // Inner divider lines for the 12 houses
  // House corners (North Indian diamond style):
  // The diamond divides outer square corners into triangles
  // Additional lines from midpoints
  const mx = cx;    // midpoints
  const my = cy;

  // Top-left to mid-left, mid-top
  doc.line(x, y, mx, my);       // diagonal TL to center — already drawn
  doc.line(x + size, y, mx, my); // diagonal TR to center
  doc.line(x + size, y + size, mx, my); // diagonal BR to center
  doc.line(x, y + size, mx, my); // diagonal BL to center

  // North Indian standard house layout (Asc in top diamond = house 1)
  // House positions relative to center:
  // The 12 houses in North Indian chart go clockwise from top center
  // House 1 = top center diamond
  // House mapping: standard positions for text placement
  const q = size / 4;
  const housePositions: [number, number][] = [
    [cx, y + q * 0.9],              // H1 — top center
    [x + q * 0.7, y + q * 0.7],    // H12 — top-left triangle
    [x + q * 0.7, cy],              // H11 — left-top
    [x + q * 0.7, cy + q * 0.9],   // H10 — left-bottom
    [x + q * 0.7, y + size - q * 0.6], // H9 — bottom-left triangle
    [cx, y + size - q * 0.8],       // H8 — bottom center
    [x + size - q * 0.7, y + size - q * 0.6], // H7 — bottom-right triangle
    [x + size - q * 0.7, cy + q * 0.9],       // H6 — right-bottom
    [x + size - q * 0.7, cy],       // H5 — right-top
    [x + size - q * 0.7, y + q * 0.7], // H4 — top-right triangle
    [cx + q * 1.1, y + q * 0.9],   // H3 — (top-right of center)
    [cx - q * 1.1, y + q * 0.9],   // H2 — (top-left of center)
  ];

  // Reorder: index 0=H1, so actual house numbers:
  // N. Indian: positions go 1(top), 12(upper-left), 11(left-upper), 10(left-lower),
  //            9(lower-left), 8(bottom), 7(lower-right), 6(right-lower),
  //            5(right-upper), 4(upper-right), 3, 2
  // Standard mapping: housePositions[i] is for house (arrangement[i])
  const houseOrder = [1, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2];

  const abbr = GRAHA_ABBREVIATIONS;

  doc.setFontSize(5);
  setText(doc, WHITE);

  houseOrder.forEach((houseNum, posIdx) => {
    // chartData.houses is 0-indexed (houses[0] = house 1 planets)
    const planetsInHouse = chartData.houses[houseNum - 1] || [];
    if (planetsInHouse.length === 0) return;

    const labels = planetsInHouse.map(pid => abbr[pid] || `P${pid}`);
    const text = labels.join(' ');
    const [px, py] = housePositions[posIdx];
    doc.text(truncateToWidth(doc, text, q * 1.5), px, py, { align: 'center' });
  });

  // "Asc" label in house 1
  doc.setFontSize(4.5);
  setText(doc, GOLD_LIGHT);
  doc.text('Asc', cx, y + q * 0.4, { align: 'center' });
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 1: COVER
// ═══════════════════════════════════════════════════════════════════════════

function renderCoverPage(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  addPageBackground(doc);

  // Extra decorative double border
  setDraw(doc, GOLD);
  doc.setLineWidth(0.2);
  doc.rect(11, 11, PAGE_W - 22, PAGE_H - 22);

  let y = 36;

  // Logo text
  doc.setFont('times', 'bold');
  doc.setFontSize(30);
  setText(doc, GOLD);
  doc.text('Dekho Panchang', PAGE_W / 2, y, { align: 'center' });
  y += 10;

  // Subtitle
  doc.setFont('times', 'italic');
  doc.setFontSize(16);
  setText(doc, GOLD_LIGHT);
  doc.text('Kundali Report', PAGE_W / 2, y, { align: 'center' });
  y += 8;

  // Gold divider
  setDraw(doc, GOLD);
  doc.setLineWidth(0.5);
  doc.line(55, y, PAGE_W - 55, y);
  y += 12;

  // Birth details
  const bd = kundali.birthData;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  setText(doc, WHITE);

  const lines = [
    bd.name,
    '',
    `${bd.date}  |  ${bd.time}`,
    bd.place,
    `${bd.lat.toFixed(4)}°N, ${bd.lng.toFixed(4)}°E`,
  ];
  lines.forEach(line => {
    if (line === '') { y += 3; return; }
    doc.text(line, PAGE_W / 2, y, { align: 'center' });
    y += 7;
  });

  y += 4;

  // Ascendant info card
  const ascSign = t(kundali.ascendant.signName, locale);
  const ascDeg = kundali.ascendant.degree.toFixed(2);
  drawCard(doc, PAGE_W / 2 - 40, y - 4, 80, 12, { fill: NAVY_CARD, border: GOLD_DARK });
  doc.setFontSize(10);
  setText(doc, GOLD_LIGHT);
  doc.text(`Ascendant: ${ascSign} ${ascDeg}°`, PAGE_W / 2, y + 3, { align: 'center' });
  y += 18;

  // Ayanamsha
  doc.setFontSize(8);
  setText(doc, MUTED);
  doc.text(`Ayanamsha: ${bd.ayanamsha} (${kundali.ayanamshaValue.toFixed(4)}°)`, PAGE_W / 2, y, { align: 'center' });
  y += 14;

  // ─── North Indian Chart ───────────────────────────────────────────
  const chartSize = 100;
  const chartX = (PAGE_W - chartSize) / 2;
  const chartY = y;

  drawCard(doc, chartX - 6, chartY - 6, chartSize + 12, chartSize + 12, { fill: NAVY_CARD, border: GOLD_DARK, radius: 3 });
  drawNorthChart(doc, kundali.chart, chartX, chartY, chartSize);

  y = chartY + chartSize + 18;

  // Chart label
  doc.setFontSize(8);
  setText(doc, MUTED);
  doc.text('Rashi Chart (D1)', PAGE_W / 2, y, { align: 'center' });

  // Generation date at bottom
  doc.setFontSize(7);
  setText(doc, MUTED);
  const now = new Date();
  doc.text(
    `Report generated on ${now.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    PAGE_W / 2, 272, { align: 'center' },
  );

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 2: PLANET POSITIONS
// ═══════════════════════════════════════════════════════════════════════════

function getPlanetDignity(p: PlanetPosition): { label: string; color: readonly [number, number, number] } | null {
  if (p.isExalted) return { label: 'Exalted', color: GREEN };
  if (p.isDebilitated) return { label: 'Debili.', color: RED };
  if (p.isOwnSign) return { label: 'Own', color: BLUE };
  return null;
}

function renderPlanetPositions(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Planetary Positions', y);

  // Table
  const headers = ['Planet', 'Sign', 'Degree', 'Nakshatra / Pada', 'House', 'Status'];
  const colWidths = [28, 28, 24, 46, 16, 40];
  y = drawTableHeader(doc, headers, colWidths, y);

  kundali.planets.forEach((p, idx) => {
    y = ensureSpace(doc, y, 9);

    const isEven = idx % 2 === 0;
    if (isEven) {
      setFill(doc, NAVY_ROW);
      doc.roundedRect(MARGIN, y - 4.5, CONTENT_W, 8, 0.5, 0.5, 'F');
    }

    doc.setFontSize(7);
    let x = MARGIN;

    // Planet name
    setText(doc, GOLD_LIGHT);
    doc.text(truncateToWidth(doc, t(p.planet.name, locale), colWidths[0]), x + 2, y);
    x += colWidths[0];

    // Sign
    setText(doc, WHITE);
    doc.text(truncateToWidth(doc, t(p.signName, locale), colWidths[1]), x + 2, y);
    x += colWidths[1];

    // Degree
    doc.text(truncateToWidth(doc, p.degree, colWidths[2]), x + 2, y);
    x += colWidths[2];

    // Nakshatra/Pada
    const nakPada = `${t(p.nakshatra.name, locale)} / ${p.pada}`;
    doc.text(truncateToWidth(doc, nakPada, colWidths[3]), x + 2, y);
    x += colWidths[3];

    // House
    doc.text(`${p.house}`, x + 2, y);
    x += colWidths[4];

    // Status badges
    let bx = x + 2;
    const dignity = getPlanetDignity(p);
    if (dignity) {
      bx += drawBadge(doc, dignity.label, bx, y, dignity.color) + 1.5;
    }
    if (p.isRetrograde) {
      bx += drawBadge(doc, 'Retro', bx, y, AMBER) + 1.5;
    }
    if (p.isCombust) {
      drawBadge(doc, 'Combust', bx, y, RED);
    }

    y += 8;
  });

  // Vargottama / special flags summary
  const specials = kundali.planets.filter(p => p.isVargottama || p.isMrityuBhaga || p.isPushkarNavamsha);
  if (specials.length > 0) {
    y += 4;
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Special Dignities', y);
    specials.forEach(p => {
      y = ensureSpace(doc, y, 5);
      doc.setFontSize(7);
      setText(doc, MUTED);
      const flags: string[] = [];
      if (p.isVargottama) flags.push('Vargottama');
      if (p.isMrityuBhaga) flags.push('Mrityu Bhaga');
      if (p.isPushkarNavamsha) flags.push('Pushkar Navamsha');
      if (p.isPushkarBhaga) flags.push('Pushkar Bhaga');
      doc.text(`${t(p.planet.name, locale)}: ${flags.join(', ')}`, MARGIN + 2, y);
      y += 5;
    });
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 3: HOUSE CUSPS + KEY YOGAS
// ═══════════════════════════════════════════════════════════════════════════

function renderHousesAndYogas(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  // ─── House Cusps ──────────────────────────────────────────────────
  y = sectionHeading(doc, 'House Cusps (Bhava)', y);
  const hHeaders = ['House', 'Sign', 'Degree', 'Lord'];
  const hColWidths = [24, 50, 50, 58];
  y = drawTableHeader(doc, hHeaders, hColWidths, y);

  kundali.houses.forEach((h, idx) => {
    y = ensureSpace(doc, y, 8);
    const row = [`${h.house}`, t(h.signName, locale), `${h.degree.toFixed(2)}°`, t(h.lordName, locale)];
    y = drawTableRow(doc, row, hColWidths, y, idx % 2 === 0);
  });

  y += 8;

  // ─── Key Yogas ────────────────────────────────────────────────────
  y = ensureSpace(doc, y, 20);
  y = sectionHeading(doc, 'Key Yogas', y);

  if (kundali.yogasComplete && kundali.yogasComplete.length > 0) {
    const presentYogas = kundali.yogasComplete.filter(yg => yg.present);

    if (presentYogas.length === 0) {
      doc.setFontSize(8);
      setText(doc, MUTED);
      doc.text('No classical yogas detected in this chart.', MARGIN + 2, y);
      y += 8;
    } else {
      // Render as mini-cards
      for (const yg of presentYogas) {
        y = ensureSpace(doc, y, 18);
        const cardH = 14;
        drawCard(doc, MARGIN, y - 3, CONTENT_W, cardH, { fill: NAVY_CARD, border: GOLD_DARK, radius: 2 });

        // Yoga name in gold
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        setText(doc, GOLD_LIGHT);
        doc.text(t(yg.name, locale), MARGIN + 3, y + 1);
        doc.setFont('helvetica', 'normal');

        // Category badge
        let bx = MARGIN + 3 + doc.getTextWidth(t(yg.name, locale)) + 4;
        const catColor = yg.isAuspicious ? GREEN : RED;
        bx += drawBadge(doc, yg.category, bx, y + 1, catColor) + 2;

        // Strength badge
        const strColor = yg.strength === 'Strong' ? GREEN : yg.strength === 'Moderate' ? AMBER : RED;
        drawBadge(doc, yg.strength, bx, y + 1, strColor);

        // Description (if there's tippanni yoga data, we use it later)
        doc.setFontSize(6.5);
        setText(doc, MUTED);
        const descText = yg.description ? t(yg.description, locale) : '';
        if (descText) {
          doc.text(truncateToWidth(doc, descText, CONTENT_W - 6), MARGIN + 3, y + 7);
        }

        y += cardH + 2;
      }
    }
  } else {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Yoga analysis data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 4: SHADBALA STRENGTH
// ═══════════════════════════════════════════════════════════════════════════

function renderShadbala(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Shadbala Strength', y);

  if (kundali.fullShadbala && kundali.fullShadbala.length > 0) {
    // ─── Bar chart visualization ────────────────────────────────────
    y = subHeading(doc, 'Strength Ratio (min 1.0 required)', y);
    y += 2;

    const barMaxW = 90;
    const labelW = 32;

    kundali.fullShadbala.forEach(sb => {
      y = ensureSpace(doc, y, 10);

      // Planet label
      doc.setFontSize(8);
      setText(doc, GOLD_LIGHT);
      doc.text(sb.planet, MARGIN + 2, y + 3);

      // Determine color
      const ratio = sb.strengthRatio;
      const barColor = ratio >= 1.5 ? GREEN : ratio >= 1.0 ? AMBER : RED;

      // Scale: ratio up to ~3.0 fills full bar
      const barVal = (ratio / 3.0) * barMaxW;
      drawBar(doc, MARGIN + labelW, y, barVal, barMaxW, barColor);

      // Ratio text at end
      doc.setFontSize(7);
      setText(doc, WHITE);
      doc.text(ratio.toFixed(2), MARGIN + labelW + barMaxW + 3, y + 3);

      // Rupas
      setText(doc, MUTED);
      doc.text(`${sb.rupas.toFixed(1)} R`, MARGIN + labelW + barMaxW + 16, y + 3);

      y += 8;
    });

    // ─── Detailed table ─────────────────────────────────────────────
    y += 6;
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Component Breakdown', y);
    const sHeaders = ['Planet', 'Sthana', 'Dig', 'Kala', 'Chesta', 'Naisargika', 'Drik', 'Total'];
    const sColWidths = [28, 22, 20, 22, 22, 26, 20, 22];
    y = drawTableHeader(doc, sHeaders, sColWidths, y);

    kundali.fullShadbala.forEach((sb, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [
        sb.planet,
        sb.sthanaBala.toFixed(1),
        sb.digBala.toFixed(1),
        sb.kalaBala.toFixed(1),
        sb.cheshtaBala.toFixed(1),
        sb.naisargikaBala.toFixed(1),
        sb.drikBala.toFixed(1),
        sb.totalPinda.toFixed(1),
      ];
      y = drawTableRow(doc, row, sColWidths, y, idx % 2 === 0);
    });

  } else if (kundali.shadbala && kundali.shadbala.length > 0) {
    const sHeaders = ['Planet', 'Sthana', 'Dig', 'Kala', 'Chesta', 'Naisargika', 'Drik', 'Total'];
    const sColWidths = [28, 22, 22, 22, 22, 26, 22, 18];
    y = drawTableHeader(doc, sHeaders, sColWidths, y);

    kundali.shadbala.forEach((sb, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [
        t(sb.planetName, locale),
        sb.sthanaBala.toFixed(1), sb.digBala.toFixed(1), sb.kalaBala.toFixed(1),
        sb.cheshtaBala.toFixed(1), sb.naisargikaBala.toFixed(1), sb.drikBala.toFixed(1),
        sb.totalStrength.toFixed(1),
      ];
      y = drawTableRow(doc, row, sColWidths, y, idx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Shadbala data not available.', MARGIN + 2, y);
    y += 8;
  }

  // ─── Bhavabala compact ────────────────────────────────────────────
  if (kundali.bhavabala && kundali.bhavabala.length > 0) {
    y += 8;
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Bhavabala (House Strength)', y);
    const bHeaders = ['Bhava', 'Lord', 'Total', 'Strength %'];
    const bColWidths = [24, 50, 44, 64];
    y = drawTableHeader(doc, bHeaders, bColWidths, y);

    kundali.bhavabala.forEach((bb, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [`${bb.bhava}`, bb.lordName, bb.total.toFixed(1), `${bb.strengthPercent.toFixed(1)}%`];
      y = drawTableRow(doc, row, bColWidths, y, idx % 2 === 0);
    });
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 5: DASHA TIMELINE
// ═══════════════════════════════════════════════════════════════════════════

function renderDashaTimeline(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Dasha Timeline', y);

  if (!kundali.dashas || kundali.dashas.length === 0) {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Dasha data not available.', MARGIN + 2, y);
    addPageFooter(doc, pageNum);
    return;
  }

  // Find current Maha Dasha
  const today = new Date().toISOString().split('T')[0];
  const mahas = kundali.dashas.filter(d => !d.level || d.level === 'maha');

  // ─── Current Dasha highlight box ──────────────────────────────────
  const currentMaha = mahas.find(d => d.startDate <= today && d.endDate >= today);
  if (currentMaha) {
    y = ensureSpace(doc, y, 22);
    drawCard(doc, MARGIN, y - 4, CONTENT_W, 18, { fill: NAVY_CARD, border: GOLD, radius: 3 });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    setText(doc, GOLD);
    const mahaName = currentMaha.planetName ? t(currentMaha.planetName, locale) : (currentMaha.planet || '-');
    doc.text(`Current Mahadasha: ${mahaName}`, MARGIN + 4, y + 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    setText(doc, WHITE);
    doc.text(`${currentMaha.startDate}  to  ${currentMaha.endDate}`, MARGIN + 4, y + 9);
    y += 22;
  }

  // ─── Visual timeline bars ─────────────────────────────────────────
  y = ensureSpace(doc, y, 14);
  y = subHeading(doc, 'Mahadasha Periods', y);
  y += 2;

  // Calculate total span for proportional widths
  const barAreaW = CONTENT_W - 40; // leave room for labels

  // Parse dates for proportional bar widths
  const dashaSpans = mahas.map(d => {
    const start = new Date(d.startDate).getTime();
    const end = new Date(d.endDate).getTime();
    return { ...d, startMs: start, endMs: end, durationMs: end - start };
  });
  const totalMs = dashaSpans.reduce((sum, d) => sum + d.durationMs, 0);

  dashaSpans.forEach(d => {
    y = ensureSpace(doc, y, 10);

    const name = d.planetName ? t(d.planetName, locale) : (d.planet || '-');
    const isCurrent = d.startDate <= today && d.endDate >= today;

    // Planet label
    doc.setFontSize(7);
    setText(doc, isCurrent ? GOLD : MUTED);
    doc.text(name, MARGIN + 2, y + 3);

    // Proportional bar
    const barW = Math.max(4, (d.durationMs / totalMs) * barAreaW);
    const barColor = isCurrent ? GOLD : GOLD_DARK;
    drawBar(doc, MARGIN + 22, y, barW, barAreaW, barColor);

    // Date range
    doc.setFontSize(5.5);
    setText(doc, MUTED);
    const dateLabel = `${d.startDate.substring(0, 7)} - ${d.endDate.substring(0, 7)}`;
    doc.text(dateLabel, MARGIN + 22, y + 7);

    y += 10;
  });

  // ─── Current Antar Dasha sub-periods ──────────────────────────────
  if (currentMaha && currentMaha.subPeriods && currentMaha.subPeriods.length > 0) {
    y += 4;
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Antardasha (Current Mahadasha Sub-Periods)', y);

    const aHeaders = ['Antardasha', 'Start', 'End'];
    const aColWidths = [60, 61, 61];
    y = drawTableHeader(doc, aHeaders, aColWidths, y);

    const subs = currentMaha.subPeriods as { planetName?: { en: string; hi?: string; sa?: string }; planet?: string; startDate: string; endDate: string }[];
    subs.forEach((sub, idx) => {
      y = ensureSpace(doc, y, 8);
      const subName = sub.planetName ? t(sub.planetName, locale) : (sub.planet || '-');
      const isCurrAntar = sub.startDate <= today && sub.endDate >= today;

      if (isCurrAntar) {
        // Highlight current
        setFill(doc, [20, 25, 55]);
        doc.roundedRect(MARGIN, y - 4.5, CONTENT_W, 8, 0.5, 0.5, 'F');
        setDraw(doc, GOLD_DARK);
        doc.setLineWidth(0.2);
        doc.roundedRect(MARGIN, y - 4.5, CONTENT_W, 8, 0.5, 0.5, 'S');
      } else if (idx % 2 === 0) {
        setFill(doc, NAVY_ROW);
        doc.roundedRect(MARGIN, y - 4.5, CONTENT_W, 8, 0.5, 0.5, 'F');
      }

      doc.setFontSize(7);
      setText(doc, isCurrAntar ? GOLD_LIGHT : WHITE);
      doc.text(truncateToWidth(doc, subName, aColWidths[0]), MARGIN + 2, y);
      setText(doc, isCurrAntar ? WHITE : MUTED);
      doc.text(sub.startDate, MARGIN + aColWidths[0] + 2, y);
      doc.text(sub.endDate, MARGIN + aColWidths[0] + aColWidths[1] + 2, y);

      y += 8;
    });
  }

  // ─── Additional Dasha Systems (compact) ───────────────────────────
  const additionalDashas: { label: string; data: typeof kundali.dashas }[] = [];
  if (kundali.yoginiDashas?.length) additionalDashas.push({ label: 'Yogini Dasha', data: kundali.yoginiDashas });
  if (kundali.ashtottariDashas?.length) additionalDashas.push({ label: 'Ashtottari Dasha', data: kundali.ashtottariDashas });

  for (const { label, data } of additionalDashas) {
    y += 6;
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, label, y);

    const entries = data.filter(d => !d.level || d.level === 'maha');
    entries.forEach((d, idx) => {
      y = ensureSpace(doc, y, 6);
      const name = d.planetName ? t(d.planetName, locale) : (d.planet || '-');

      if (idx % 2 === 0) {
        setFill(doc, NAVY_ROW);
        doc.roundedRect(MARGIN, y - 4, CONTENT_W, 6.5, 0.5, 0.5, 'F');
      }
      doc.setFontSize(7);
      setText(doc, GOLD_LIGHT);
      doc.text(name, MARGIN + 2, y);
      setText(doc, MUTED);
      doc.text(`${d.startDate}  —  ${d.endDate}`, MARGIN + 50, y);
      y += 6.5;
    });
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 6: ASHTAKAVARGA
// ═══════════════════════════════════════════════════════════════════════════

function renderAshtakavarga(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Ashtakavarga', y);

  if (!kundali.ashtakavarga) {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Ashtakavarga data not available.', MARGIN + 2, y);
    addPageFooter(doc, pageNum);
    return;
  }

  const av = kundali.ashtakavarga;
  const signAbbr = RASHIS.map(r => t(r.name, locale).substring(0, 3));

  // ─── SAV Heat Map ─────────────────────────────────────────────────
  y = subHeading(doc, 'Sarvashtakavarga (SAV)', y);
  y += 2;

  const cellW = CONTENT_W / 12;
  const cellH = 10;

  // Sign headers
  doc.setFontSize(5.5);
  setText(doc, GOLD);
  signAbbr.forEach((name, i) => {
    doc.text(name, MARGIN + i * cellW + cellW / 2, y, { align: 'center' });
  });
  y += 4;

  // SAV value cells with heat-map coloring
  av.savTable.forEach((val, i) => {
    const cx = MARGIN + i * cellW;
    // Color: green for high (28+), red for low (<22), neutral otherwise
    if (val >= 28) {
      setFill(doc, [20, 60, 30]);
    } else if (val < 22) {
      setFill(doc, [60, 20, 20]);
    } else {
      setFill(doc, NAVY_CARD);
    }
    doc.roundedRect(cx + 0.5, y, cellW - 1, cellH, 1, 1, 'F');
    setDraw(doc, GOLD_DARK);
    doc.setLineWidth(0.15);
    doc.roundedRect(cx + 0.5, y, cellW - 1, cellH, 1, 1, 'S');

    // Value
    doc.setFontSize(8);
    setText(doc, val >= 28 ? GREEN : val < 22 ? RED : WHITE);
    doc.text(`${val}`, cx + cellW / 2, y + cellH / 2 + 1.5, { align: 'center' });
  });
  y += cellH + 8;

  // ─── BPI Table ────────────────────────────────────────────────────
  y = ensureSpace(doc, y, 30);
  y = subHeading(doc, 'Bhinnashtakavarga (Planet-wise)', y);

  const bpiColW = CONTENT_W / 13;
  const bpiHeaders = ['', ...signAbbr];
  const bpiColWidths = Array(13).fill(bpiColW);
  y = drawTableHeader(doc, bpiHeaders, bpiColWidths, y);

  av.bpiTable.forEach((row, pIdx) => {
    y = ensureSpace(doc, y, 8);
    const planetName = av.planetNames[pIdx] || GRAHAS[pIdx]?.name?.en || `P${pIdx}`;
    const cells = [planetName.substring(0, 4), ...row.map(v => `${v}`)];
    y = drawTableRow(doc, cells, bpiColWidths, y, pIdx % 2 === 0);
  });

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// PAGE 7: DIVISIONAL CHARTS + JAIMINI
// ═══════════════════════════════════════════════════════════════════════════

function renderDivisionalAndJaimini(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  // ─── Divisional Charts Overview ───────────────────────────────────
  y = sectionHeading(doc, 'Divisional Charts Overview', y);

  if (kundali.divisionalCharts && Object.keys(kundali.divisionalCharts).length > 0) {
    const abbr = GRAHA_ABBREVIATIONS;
    const entries = Object.entries(kundali.divisionalCharts);

    for (const [key, chart] of entries) {
      y = ensureSpace(doc, y, 16);

      const ascSignId = chart.ascendantSign;
      const ascRashi = RASHIS.find(r => r.id === ascSignId);
      const ascName = ascRashi ? t(ascRashi.name, locale) : `Sign ${ascSignId}`;

      // Mini card for each chart
      drawCard(doc, MARGIN, y - 3, CONTENT_W, 12, { fill: NAVY_CARD, radius: 1.5 });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      setText(doc, GOLD_LIGHT);
      const label = t(chart.label, locale);
      doc.text(`${key.toUpperCase()} (${label})`, MARGIN + 3, y + 1);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      setText(doc, MUTED);
      doc.text(`Asc: ${ascName}`, MARGIN + 3, y + 5.5);

      // Planet placements
      const parts: string[] = [];
      chart.houses.forEach((planetIds, hIdx) => {
        if (planetIds.length > 0) {
          const names = planetIds.map(pid => abbr[pid] || `P${pid}`).join(',');
          parts.push(`H${hIdx + 1}:${names}`);
        }
      });
      const placeLine = parts.length > 0 ? parts.join('  ') : 'No planets';
      setText(doc, WHITE);
      doc.text(truncateToWidth(doc, placeLine, CONTENT_W - 80), MARGIN + 60, y + 1);

      y += 14;
    }
  } else {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Divisional chart data not available.', MARGIN + 2, y);
    y += 8;
  }

  // ─── Jaimini System ───────────────────────────────────────────────
  y += 4;
  y = ensureSpace(doc, y, 20);
  y = sectionHeading(doc, 'Jaimini System', y);

  if (kundali.jaimini) {
    const j = kundali.jaimini;

    // Chara Karakas
    y = subHeading(doc, 'Chara Karakas', y);
    const ckHeaders = ['Planet', 'Karaka', 'Degree'];
    const ckColWidths = [60, 60, 62];
    y = drawTableHeader(doc, ckHeaders, ckColWidths, y);

    j.charaKarakas.forEach((ck, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [t(ck.planetName, locale), t(ck.karakaName, locale), ck.degree.toFixed(2)];
      y = drawTableRow(doc, row, ckColWidths, y, idx % 2 === 0);
    });

    y += 4;

    // Karakamsha
    y = ensureSpace(doc, y, 10);
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 10, { fill: NAVY_CARD, border: GOLD_DARK, radius: 2 });
    doc.setFontSize(8);
    setText(doc, GOLD_LIGHT);
    doc.text(`Karakamsha: ${t(j.karakamsha.signName, locale)}`, MARGIN + 4, y + 3);
    y += 14;

    // Chara Dasha (compact)
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Chara Dasha', y);
    const cdHeaders = ['Sign', 'Years', 'Start', 'End'];
    const cdColWidths = [46, 30, 53, 53];
    y = drawTableHeader(doc, cdHeaders, cdColWidths, y);

    j.charaDasha.forEach((cd, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [t(cd.signName, locale), `${cd.years}`, cd.startDate, cd.endDate];
      y = drawTableRow(doc, row, cdColWidths, y, idx % 2 === 0);
    });
  } else {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Jaimini system data not available.', MARGIN + 2, y);
    y += 8;
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// SADE SATI ANALYSIS
// ═══════════════════════════════════════════════════════════════════════════

function renderSadeSati(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Sade Sati Analysis', y);

  const ss = kundali.sadeSati!;
  const lk = (locale === 'hi' || locale === 'sa') ? 'hi' as const : 'en' as const;

  // Status card
  if (ss.isActive) {
    const phaseLabel = ss.currentPhase === 'rising' ? 'Rising' : ss.currentPhase === 'peak' ? 'Peak' : 'Setting';
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 20, { fill: NAVY_CARD, border: GOLD, radius: 3 });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    setText(doc, GOLD);
    doc.text(`ACTIVE — ${phaseLabel} Phase`, MARGIN + 4, y + 3);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    setText(doc, WHITE);
    doc.text(`Cycle: ${ss.cycleStart} — ${ss.cycleEnd}  |  Progress: ${Math.round(ss.phaseProgress * 100)}%`, MARGIN + 4, y + 10);
    doc.text(`Intensity: ${ss.overallIntensity.toFixed(1)} / 10`, MARGIN + 4, y + 15);
    y += 26;
  } else {
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 12, { fill: NAVY_CARD, radius: 2 });
    doc.setFontSize(9);
    setText(doc, MUTED);
    doc.text('Sade Sati: Not Active', MARGIN + 4, y + 4);
    const nextCycle = ss.allCycles.find(c => !c.isActive && c.startYear > new Date().getFullYear());
    if (nextCycle) {
      doc.setFontSize(7);
      doc.text(`Next cycle: ${nextCycle.startYear} — ${nextCycle.endYear}`, MARGIN + 80, y + 4);
    }
    y += 16;
  }

  // Summary
  const summary = ss.interpretation.summary[lk];
  if (summary) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Summary', y);
    y = drawWrapped(doc, summary, MARGIN + 2, y, CONTENT_W - 4, 7.5, WHITE);
    y += 4;
  }

  // Timeline
  if (ss.allCycles.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'All Cycles', y);
    ss.allCycles.forEach(cycle => {
      y = ensureSpace(doc, y, 6);
      doc.setFontSize(7.5);
      const activePhase = cycle.isActive && ss.currentPhase
        ? ` [ACTIVE - ${ss.currentPhase.charAt(0).toUpperCase() + ss.currentPhase.slice(1)}]`
        : '';
      setText(doc, cycle.isActive ? GOLD : MUTED);
      doc.text(`${cycle.startYear} — ${cycle.endYear}${activePhase}`, MARGIN + 2, y);
      y += 5.5;
    });
    y += 3;
  }

  // Remedies
  if (ss.isActive && ss.remedies.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Remedies', y);
    for (const r of ss.remedies) {
      y = ensureSpace(doc, y, 14);
      drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 1 });
      const priorityColor = r.priority === 'essential' ? RED : r.priority === 'recommended' ? AMBER : MUTED;
      drawBadge(doc, r.priority.toUpperCase(), MARGIN + 2, y, priorityColor);
      doc.setFontSize(7.5);
      setText(doc, GOLD_LIGHT);
      doc.text(r.title[lk] || "", MARGIN + 20, y);
      y += 5;
      y = drawWrapped(doc, r.description[lk] || "", MARGIN + 4, y, CONTENT_W - 8, 7, MUTED);
      y += 2;
    }
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// TRANSIT RADAR
// ═══════════════════════════════════════════════════════════════════════════

function renderTransitRadar(doc: jsPDF, kundali: KundaliData, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Current Transit Analysis', y);

  const ascSign = kundali.ascendant.sign;
  const savTable = kundali.ashtakavarga?.savTable;

  if (!savTable || !ascSign) {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('Transit analysis requires Ashtakavarga data.', MARGIN + 2, y);
    addPageFooter(doc, pageNum);
    return;
  }

  const transits = computePersonalTransits(ascSign, savTable);

  if (transits.length === 0) {
    doc.setFontSize(8);
    setText(doc, MUTED);
    doc.text('No transit data computed.', MARGIN + 2, y);
    addPageFooter(doc, pageNum);
    return;
  }

  // Transit cards
  for (const tr of transits) {
    y = ensureSpace(doc, y, 20);

    const qualityColor = tr.quality === 'strong' ? GREEN : tr.quality === 'weak' ? RED : AMBER;
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 16, { fill: NAVY_CARD, border: GOLD_DARK, radius: 2 });

    // Planet name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    setText(doc, GOLD_LIGHT);
    doc.text(t(tr.planetName, locale), MARGIN + 4, y + 1.5);
    doc.setFont('helvetica', 'normal');

    // Sign + House
    doc.setFontSize(7);
    setText(doc, WHITE);
    doc.text(`in ${t(tr.signName, locale)} (House ${tr.house})`, MARGIN + 35, y + 1.5);

    // SAV + Quality badge
    setText(doc, MUTED);
    doc.text(`SAV: ${tr.savBindu}`, MARGIN + 100, y + 1.5);
    const qualityLabel = tr.quality === 'strong' ? 'Favorable' : tr.quality === 'weak' ? 'Challenging' : 'Moderate';
    drawBadge(doc, qualityLabel, MARGIN + 120, y + 1.5, qualityColor);

    // Interpretation
    const interp = t(tr.interpretation, locale);
    doc.setFontSize(6.5);
    setText(doc, MUTED);
    const interpLines = wrapText(doc, interp, CONTENT_W - 10, 6.5);
    interpLines.slice(0, 2).forEach((line, li) => {
      doc.text(line, MARGIN + 4, y + 7 + li * 4);
    });

    y += 18;
  }

  // Upcoming transitions
  const upcoming = computeUpcomingTransitions();
  if (upcoming.length > 0) {
    y += 4;
    y = ensureSpace(doc, y, 20);
    y = subHeading(doc, 'Upcoming Sign Changes', y);
    const uHeaders = ['Planet', 'From', 'To', 'Approx. Date'];
    const uColWidths = [40, 40, 40, 62];
    y = drawTableHeader(doc, uHeaders, uColWidths, y);

    upcoming.forEach((u, idx) => {
      y = ensureSpace(doc, y, 8);
      const row = [t(u.planetName, locale), t(u.fromSign, locale), t(u.toSign, locale), u.approximateDate];
      y = drawTableRow(doc, row, uColWidths, y, idx % 2 === 0);
    });
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// CONVERGENCE INSIGHTS
// ═══════════════════════════════════════════════════════════════════════════

function renderConvergenceInsights(doc: jsPDF, convergence: ConvergenceResult, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Chart Synthesis — Convergence', y);

  const lk = (locale === 'hi' || locale === 'sa') ? 'hi' as const : 'en' as const;
  const exec = convergence.executive;

  // Overview card
  const toneLabel = exec.tone.charAt(0).toUpperCase() + exec.tone.slice(1);
  drawCard(doc, MARGIN, y - 3, CONTENT_W, 14, { fill: NAVY_CARD, border: GOLD_DARK, radius: 3 });
  doc.setFontSize(9);
  setText(doc, GOLD_LIGHT);
  doc.text(`Tone: ${toneLabel}`, MARGIN + 4, y + 2);
  doc.setFontSize(8);
  setText(doc, WHITE);
  doc.text(`Activation: ${exec.activation}/10  |  Favorability: ${exec.favorability}/10`, MARGIN + 4, y + 8);
  y += 18;

  // Key Insights
  if (exec.insights.length > 0) {
    y = subHeading(doc, 'Key Insights', y);

    for (const ins of exec.insights) {
      y = ensureSpace(doc, y, 18);
      drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 1.5 });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      setText(doc, GOLD_LIGHT);
      doc.text(ins.theme, MARGIN + 3, y);
      doc.setFont('helvetica', 'normal');
      drawBadge(doc, ins.temporalFrame, MARGIN + 3 + doc.getTextWidth(ins.theme) + 4, y, GOLD_DARK);
      y += 5;
      y = drawWrapped(doc, ins.summary[lk] || "", MARGIN + 3, y, CONTENT_W - 8, 7, WHITE);
      if (ins.advice[lk]) {
        y = drawWrapped(doc, `Advice: ${ins.advice[lk]}`, MARGIN + 3, y, CONTENT_W - 8, 6.5, MUTED);
      }
      y += 3;
    }
  }

  // Urgent flags
  if (exec.urgentFlags.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Urgent Flags', y);

    for (const flag of exec.urgentFlags) {
      y = ensureSpace(doc, y, 14);
      const sevColor = flag.severity === 3 ? RED : flag.severity === 2 ? AMBER : MUTED;
      const sevLabel = flag.severity === 3 ? 'HIGH' : flag.severity === 2 ? 'MEDIUM' : 'LOW';
      drawBadge(doc, sevLabel, MARGIN + 2, y, sevColor);
      y += 5;
      y = drawWrapped(doc, flag.message[lk] || "", MARGIN + 3, y, CONTENT_W - 6, 7, WHITE);
      y += 2;
    }
  }

  // Meta-insights
  if (exec.metaInsights.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Meta-Interactions', y);

    for (const mi of exec.metaInsights) {
      y = ensureSpace(doc, y, 14);
      const sevColor = mi.severity === 3 ? RED : mi.severity === 2 ? AMBER : MUTED;
      const sevLabel = mi.severity === 3 ? 'HIGH' : mi.severity === 2 ? 'MEDIUM' : 'LOW';
      drawBadge(doc, sevLabel, MARGIN + 2, y, sevColor);
      y += 5;
      y = drawWrapped(doc, mi.text[lk] || '', MARGIN + 3, y, CONTENT_W - 6, 7, WHITE);
      y += 3;
    }
  }

  addPageFooter(doc, pageNum);
}

// ═══════════════════════════════════════════════════════════════════════════
// TIPPANNI — INTERPRETIVE ANALYSIS
// ═══════════════════════════════════════════════════════════════════════════

function renderTippanni(doc: jsPDF, tippanni: TippanniContent, locale: Locale) {
  let y = newPage(doc);

  y = sectionHeading(doc, 'Tippanni — Interpretive Analysis', y);

  // ─── Personality ──────────────────────────────────────────────────
  if (tippanni.personality) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Personality Profile', y);

    const pers = tippanni.personality;
    const blocks = [pers.lagna, pers.moonSign, pers.sunSign].filter(Boolean);

    for (const block of blocks) {
      if (!block) continue;
      y = ensureSpace(doc, y, 20);

      // Card for each personality block
      const contentLines = wrapText(doc, block.content, CONTENT_W - 10, 7);
      const cardH = Math.max(14, 8 + contentLines.length * 4.5);

      drawCard(doc, MARGIN, y - 3, CONTENT_W, cardH, { fill: NAVY_CARD, border: GOLD_DARK, radius: 2 });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      setText(doc, GOLD_LIGHT);
      doc.text(block.title, MARGIN + 4, y + 1);
      doc.setFont('helvetica', 'normal');

      doc.setFontSize(7);
      setText(doc, WHITE);
      let textY = y + 6;
      for (const line of contentLines) {
        textY = ensureSpace(doc, textY, 4.5);
        doc.text(line, MARGIN + 4, textY);
        textY += 4.5;
      }

      y += cardH + 3;
    }

    if (pers.summary) {
      y = ensureSpace(doc, y, 10);
      y = drawWrapped(doc, pers.summary, MARGIN + 2, y, CONTENT_W - 4, 7, MUTED);
      y += 4;
    }
  }

  // ─── Planet Insights ──────────────────────────────────────────────
  if (tippanni.planetInsights && tippanni.planetInsights.length > 0) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Planet Insights', y);

    for (const pi of tippanni.planetInsights) {
      y = ensureSpace(doc, y, 22);

      // Mini card per planet
      drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 1.5 });

      // Planet name with color dot
      const pColor = hexToRgb(pi.planetColor || '#d4a853');
      setFill(doc, pColor);
      doc.circle(MARGIN + 4, y - 0.5, 1.3, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      setText(doc, GOLD_LIGHT);
      doc.text(`${pi.planetName} in ${pi.signName} (House ${pi.house})`, MARGIN + 8, y);
      doc.setFont('helvetica', 'normal');

      // Dignity badge
      if (pi.dignity) {
        const digColor = pi.dignity === 'Exalted' ? GREEN : pi.dignity === 'Debilitated' ? RED : pi.dignity === 'Own Sign' ? BLUE : AMBER;
        drawBadge(doc, pi.dignity, MARGIN + 8 + doc.getTextWidth(`${pi.planetName} in ${pi.signName} (House ${pi.house})`) + 3, y, digColor);
      }

      y += 5;
      y = drawWrapped(doc, pi.description, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);

      if (pi.implications) {
        y = drawWrapped(doc, pi.implications, MARGIN + 4, y, CONTENT_W - 8, 6.5, MUTED);
      }
      if (pi.retrogradeEffect) {
        y = drawWrapped(doc, `Retrograde: ${pi.retrogradeEffect}`, MARGIN + 4, y, CONTENT_W - 8, 6.5, AMBER);
      }
      y += 3;
    }
  }

  // ─── Yoga Insights ────────────────────────────────────────────────
  if (tippanni.yogas && tippanni.yogas.length > 0) {
    const presentYogas = tippanni.yogas.filter(yg => yg.present);
    if (presentYogas.length > 0) {
      y = ensureSpace(doc, y, 14);
      y = subHeading(doc, 'Yoga Insights', y);

      for (const yg of presentYogas) {
        y = ensureSpace(doc, y, 16);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        setText(doc, GOLD_LIGHT);
        doc.text(yg.name, MARGIN + 2, y);
        doc.setFont('helvetica', 'normal');

        // Type + Strength badges
        let bx = MARGIN + 2 + doc.getTextWidth(yg.name) + 4;
        drawBadge(doc, yg.type, bx, y, GOLD_DARK);
        bx += doc.getTextWidth(yg.type) + 8;
        const strColor = yg.strength === 'Strong' ? GREEN : yg.strength === 'Moderate' ? AMBER : RED;
        drawBadge(doc, yg.strength, bx, y, strColor);

        y += 5;
        y = drawWrapped(doc, yg.description, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);
        if (yg.implications) {
          y = drawWrapped(doc, yg.implications, MARGIN + 4, y, CONTENT_W - 8, 6.5, MUTED);
        }
        y += 3;
      }
    }
  }

  // ─── Doshas ───────────────────────────────────────────────────────
  if (tippanni.doshas && tippanni.doshas.length > 0) {
    const presentDoshas = tippanni.doshas.filter(d => d.present);
    if (presentDoshas.length > 0) {
      y = ensureSpace(doc, y, 14);
      y = subHeading(doc, 'Dosha Analysis', y);

      for (const d of presentDoshas) {
        y = ensureSpace(doc, y, 16);

        // Severity indicator
        const sevColor = d.severity === 'severe' ? RED : d.severity === 'moderate' ? AMBER : d.severity === 'mild' ? GOLD_DARK : MUTED;
        drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 1.5 });

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        setText(doc, GOLD_LIGHT);
        doc.text(d.name, MARGIN + 3, y);
        doc.setFont('helvetica', 'normal');

        drawBadge(doc, d.severity.toUpperCase(), MARGIN + 3 + doc.getTextWidth(d.name) + 4, y, sevColor);

        if (d.effectiveSeverity && d.effectiveSeverity !== 'full') {
          drawBadge(doc, d.effectiveSeverity, MARGIN + 3 + doc.getTextWidth(d.name) + doc.getTextWidth(d.severity.toUpperCase()) + 14, y, BLUE);
        }

        y += 5;
        y = drawWrapped(doc, d.description, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);
        if (d.remedies) {
          y = drawWrapped(doc, `Remedies: ${d.remedies}`, MARGIN + 4, y, CONTENT_W - 8, 6.5, MUTED);
        }
        y += 3;
      }
    }
  }

  // ─── Life Areas ───────────────────────────────────────────────────
  if (tippanni.lifeAreas) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Life Areas', y);

    const areas = tippanni.lifeAreas;
    const areaList: { label: string; data: typeof areas.career }[] = [
      { label: 'Career', data: areas.career },
      { label: 'Wealth', data: areas.wealth },
      { label: 'Marriage', data: areas.marriage },
      { label: 'Health', data: areas.health },
      { label: 'Education', data: areas.education },
    ];

    for (const { label, data } of areaList) {
      if (!data) continue;
      y = ensureSpace(doc, y, 16);

      drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 1.5 });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      setText(doc, GOLD_LIGHT);
      doc.text(label, MARGIN + 3, y);
      doc.setFont('helvetica', 'normal');

      // Rating dots
      drawRatingDots(doc, Math.round(data.rating / 2), 5, MARGIN + 35, y - 0.5);

      // Numeric rating
      doc.setFontSize(6.5);
      setText(doc, MUTED);
      doc.text(`${data.rating}/10`, MARGIN + 58, y);

      y += 5;
      y = drawWrapped(doc, data.summary, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);
      y += 2;
    }
  }

  // ─── Dasha Analysis ───────────────────────────────────────────────
  if (tippanni.dashaInsight) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Dasha Analysis', y);

    const di = tippanni.dashaInsight;

    // Current Mahadasha card
    y = ensureSpace(doc, y, 18);
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, border: GOLD_DARK, radius: 2 });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    setText(doc, GOLD);
    doc.text(`Mahadasha: ${di.currentMaha}`, MARGIN + 4, y);
    doc.setFont('helvetica', 'normal');
    y += 5;
    y = drawWrapped(doc, di.currentMahaAnalysis, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);
    y += 3;

    // Current Antardasha
    y = ensureSpace(doc, y, 14);
    drawCard(doc, MARGIN, y - 3, CONTENT_W, 4, { fill: NAVY_CARD, radius: 2 });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    setText(doc, GOLD_LIGHT);
    doc.text(`Antardasha: ${di.currentAntar}`, MARGIN + 4, y);
    doc.setFont('helvetica', 'normal');
    y += 5;
    y = drawWrapped(doc, di.currentAntarAnalysis, MARGIN + 4, y, CONTENT_W - 8, 7, WHITE);
    y += 3;

    if (di.upcoming) {
      y = ensureSpace(doc, y, 8);
      y = drawWrapped(doc, `Upcoming: ${di.upcoming}`, MARGIN + 4, y, CONTENT_W - 8, 7, MUTED);
      y += 2;
    }
  }

  // ─── Remedies ─────────────────────────────────────────────────────
  if (tippanni.remedies) {
    y = ensureSpace(doc, y, 14);
    y = subHeading(doc, 'Remedies', y);

    const rem = tippanni.remedies;

    const remedyGroups: { title: string; items: typeof rem.gemstones }[] = [
      { title: 'Gemstones', items: rem.gemstones },
      { title: 'Mantras', items: rem.mantras },
      { title: 'Practices', items: rem.practices },
    ];

    for (const group of remedyGroups) {
      if (!group.items || group.items.length === 0) continue;

      y = ensureSpace(doc, y, 14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      setText(doc, GOLD_LIGHT);
      doc.text(group.title, MARGIN + 2, y);
      doc.setFont('helvetica', 'normal');
      y += 5;

      for (const item of group.items) {
        y = ensureSpace(doc, y, 10);
        drawCard(doc, MARGIN + 2, y - 3, CONTENT_W - 4, 4, { fill: NAVY_CARD, radius: 1 });

        doc.setFontSize(7.5);
        setText(doc, WHITE);
        doc.text(`${item.name} (${item.planet})`, MARGIN + 5, y);
        y += 4.5;
        y = drawWrapped(doc, item.description, MARGIN + 5, y, CONTENT_W - 12, 6.5, MUTED);
        y += 2;
      }
      y += 2;
    }
  }

  addPageFooter(doc, pageNum);
}

// ─── Hex to RGB helper ─────────────────────────────────────────────────────

function hexToRgb(hex: string): readonly [number, number, number] {
  const h = hex.replace('#', '');
  return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)] as const;
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN EXPORT
// ═══════════════════════════════════════════════════════════════════════════

export function exportKundaliPDF(
  kundali: KundaliData,
  locale: Locale = 'en',
  tippanni?: TippanniContent,
): void {
  pageNum = 1;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Page 1: Cover with chart diagram
  renderCoverPage(doc, kundali, locale);

  // Page 2: Planet Positions with dignity badges
  renderPlanetPositions(doc, kundali, locale);

  // Page 3: House Cusps + Key Yogas
  renderHousesAndYogas(doc, kundali, locale);

  // Page 4: Shadbala bar chart + Bhavabala
  renderShadbala(doc, kundali, locale);

  // Page 5: Dasha Timeline with visual bars
  renderDashaTimeline(doc, kundali, locale);

  // Page 6: Ashtakavarga heat map
  renderAshtakavarga(doc, kundali, locale);

  // Page 7: Divisional Charts + Jaimini
  renderDivisionalAndJaimini(doc, kundali, locale);

  // Conditional sections
  if (kundali.sadeSati) {
    renderSadeSati(doc, kundali, locale);
  }

  if (kundali.ashtakavarga?.savTable && kundali.ascendant?.sign) {
    renderTransitRadar(doc, kundali, locale);
  }

  if (tippanni?.convergence) {
    renderConvergenceInsights(doc, tippanni.convergence, locale);
  }

  // Tippanni (multi-page interpretations)
  if (tippanni) {
    renderTippanni(doc, tippanni, locale);
  }

  // Save
  const name = kundali.birthData.name.replace(/[^a-zA-Z0-9]/g, '_') || 'kundali';
  doc.save(`${name}_kundali_report.pdf`);
}
