/**
 * Storage abstraction for the precompute pipeline.
 *
 * One interface, three backends:
 *   - LocalFsStorage      — laptop dev / scripts. Reads/writes
 *                            data/precompute/v1/{key}.json (gitignored).
 *   - InMemoryStorage     — vitest. No file I/O, test-isolated.
 *                            Pass a Map<string,string> in for golden fixtures.
 *   - VercelBlobStorage   — production. Wraps @vercel/blob put/head/get.
 *                            (Stub here; wire to @vercel/blob in Phase 0.1.)
 *
 * The selection is env-driven via PRECOMPUTE_STORAGE:
 *   - 'local'  → LocalFsStorage   (laptop dev / scripts default)
 *   - 'memory' → InMemoryStorage  (tests inject their own instance)
 *   - 'blob'   → VercelBlobStorage (Vercel runtime default)
 *
 * Writers and readers BOTH consume `getStorage()`, so the same precompute
 * script works on the laptop (writing fs) and in GH Actions (writing Blob)
 * without code changes — only the env flips.
 *
 * Closes "issue D" from the plan self-review: backfill resumability comes
 * for free because every backend implements `exists(key)`; writers skip
 * when present.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';

export interface PrecomputeStorage {
  /** Read a key. Returns null if absent (NOT throwing — fallback path). */
  get(key: string): Promise<string | null>;

  /** Write a key. Overwrites unconditionally. */
  put(key: string, json: string): Promise<void>;

  /** Cheap existence check. Backfill scripts use this for resumability. */
  exists(key: string): Promise<boolean>;
}

// ─── Local filesystem ────────────────────────────────────────────────────────

const DEFAULT_LOCAL_ROOT = path.resolve(process.cwd(), 'data/precompute/v1');

export class LocalFsStorage implements PrecomputeStorage {
  constructor(private root: string = DEFAULT_LOCAL_ROOT) {}

  private pathFor(key: string): string {
    // key is a forward-slash logical path; map to fs.
    // Reject `..` to prevent path traversal (defence-in-depth; keys are
    // generated by trusted code but the abstraction is the boundary).
    if (key.includes('..')) throw new Error(`[storage] illegal key: ${key}`);
    return path.join(this.root, `${key}.json`);
  }

  async get(key: string): Promise<string | null> {
    try {
      return await fs.readFile(this.pathFor(key), 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  }

  async put(key: string, json: string): Promise<void> {
    const p = this.pathFor(key);
    await fs.mkdir(path.dirname(p), { recursive: true });
    await fs.writeFile(p, json, 'utf8');
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }
}

// ─── In-memory (tests) ───────────────────────────────────────────────────────

export class InMemoryStorage implements PrecomputeStorage {
  // Public so tests can inspect / seed.
  readonly store = new Map<string, string>();

  async get(key: string): Promise<string | null> {
    return this.store.get(key) ?? null;
  }

  async put(key: string, json: string): Promise<void> {
    this.store.set(key, json);
  }

  async exists(key: string): Promise<boolean> {
    return this.store.has(key);
  }
}

// ─── Vercel Blob (stub for spike) ───────────────────────────────────────────
//
// Real implementation will wrap @vercel/blob put/head/get. We're keeping it
// as a throw-on-call stub during the spike so the laptop-test path is the
// only one exercised — the Blob wiring is a separate (small) ticket that
// can land independently once the abstraction is settled.

export class VercelBlobStorage implements PrecomputeStorage {
  async get(_key: string): Promise<string | null> {
    throw new Error('[storage] VercelBlobStorage not wired yet (spike stub)');
  }
  async put(_key: string, _json: string): Promise<void> {
    throw new Error('[storage] VercelBlobStorage not wired yet (spike stub)');
  }
  async exists(_key: string): Promise<boolean> {
    throw new Error('[storage] VercelBlobStorage not wired yet (spike stub)');
  }
}

// ─── Selector ───────────────────────────────────────────────────────────────

let _testOverride: PrecomputeStorage | null = null;

/** Test-only — inject a specific storage instance. */
export function __setStorageForTests(storage: PrecomputeStorage | null): void {
  _testOverride = storage;
}

export function getStorage(): PrecomputeStorage {
  if (_testOverride) return _testOverride;
  switch (process.env.PRECOMPUTE_STORAGE) {
    case 'local':
      return new LocalFsStorage();
    case 'memory':
      return new InMemoryStorage();
    case 'blob':
      return new VercelBlobStorage();
    default:
      // Default to local on laptop, throw in production to prevent silent
      // dev-config bleed.
      if (process.env.VERCEL === '1') {
        throw new Error('[storage] PRECOMPUTE_STORAGE not set in Vercel — refusing to default');
      }
      return new LocalFsStorage();
  }
}
