/**
 * Storage abstraction for the precompute pipeline.
 *
 * One interface, three backends:
 *   - LocalFsStorage      — laptop dev / scripts. Reads/writes
 *                            data/precompute/v1/{key}.json (gitignored).
 *   - InMemoryStorage     — vitest. No file I/O, test-isolated.
 *                            Pass a Map<string,string> in for golden fixtures.
 *   - VercelBlobStorage   — production. Wraps @vercel/blob put/head/get.
 *                            (Stub here; wire to @vercel/blob in Phase 0.1.)
 *
 * The selection is env-driven via PRECOMPUTE_STORAGE:
 *   - 'local'  → LocalFsStorage   (laptop dev / scripts default)
 *   - 'memory' → InMemoryStorage  (tests inject their own instance)
 *   - 'blob'   → VercelBlobStorage (Vercel runtime default)
 *
 * Writers and readers BOTH consume `getStorage()`, so the same precompute
 * script works on the laptop (writing fs) and in GH Actions (writing Blob)
 * without code changes — only the env flips.
 *
 * Closes "issue D" from the plan self-review: backfill resumability comes
 * for free because every backend implements `exists(key)`; writers skip
 * when present.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';

export interface PrecomputeStorage {
  /** Read a key. Returns null if absent (NOT throwing — fallback path). */
  get(key: string): Promise<string | null>;

  /** Write a key. Overwrites unconditionally. */
  put(key: string, json: string): Promise<void>;

  /** Cheap existence check. Backfill scripts use this for resumability. */
  exists(key: string): Promise<boolean>;
}

// ─── Local filesystem ────────────────────────────────────────────────────────

const DEFAULT_LOCAL_ROOT = path.resolve(process.cwd(), 'data/precompute/v1');

export class LocalFsStorage implements PrecomputeStorage {
  constructor(private root: string = DEFAULT_LOCAL_ROOT) {}

  private pathFor(key: string): string {
    // key is a forward-slash logical path; map to fs.
    // Defence-in-depth: keys are generated by trusted code (keys.ts has
    // regex validators), but the abstraction itself is the boundary that
    // must be safe in isolation. `path.resolve` + `path.relative` covers
    // `..`, absolute paths, and Windows-style separators in one check —
    // a `..` substring filter (Gemini #470 finding #2) catches none of
    // those edge cases (e.g. an absolute `/etc/passwd` key would write
    // outside the root, despite containing no `..`).
    const resolved = path.resolve(this.root, `${key}.json`);
    const rel = path.relative(this.root, resolved);
    if (rel.startsWith('..') || path.isAbsolute(rel)) {
      throw new Error(`[storage] illegal key: ${key}`);
    }
    return resolved;
  }

  async get(key: string): Promise<string | null> {
    try {
      return await fs.readFile(this.pathFor(key), 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  }

  async put(key: string, json: string): Promise<void> {
    const p = this.pathFor(key);
    await fs.mkdir(path.dirname(p), { recursive: true });
    await fs.writeFile(p, json, 'utf8');
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }
}

// ─── In-memory (tests) ───────────────────────────────────────────────────────

export class InMemoryStorage implements PrecomputeStorage {
  // Public so tests can inspect / seed.
  readonly store = new Map<string, string>();

  async get(key: string): Promise<string | null> {
    return this.store.get(key) ?? null;
  }

  async put(key: string, json: string): Promise<void> {
    this.store.set(key, json);
  }

  async exists(key: string): Promise<boolean> {
    return this.store.has(key);
  }
}

// ─── Vercel Blob ────────────────────────────────────────────────────────────
//
// Production backend. Wraps @vercel/blob put / head / fetch.
//
// Key shape: precompute/v1/{logical-key}.json
//   - precompute/ prefix isolates from any other Blob use in the project
//   - v1/ allows schema-version partitioning (closes plan issue J:
//     bump to v2 to ship a parallel-write transition without breaking
//     deployed readers)
//   - .json suffix for human-readable URLs + correct Content-Type
//
// Access model:
//   - access: 'public' — these Blobs hold deterministic public content
//     (panchang/choghadiya). No PII, no auth gate, no reason to slow them
//     behind get(). Public Blobs are fetchable by any client.
//   - addRandomSuffix: false — URLs must be predictable so the GH Action
//     can write a key and the reader can derive the same URL pattern
//     without consulting a manifest.
//   - allowOverwrite: true — daily cron overwrites the same key for
//     rolling-window dates.
//
// Exists check via head(): BlobNotFoundError → false, anything else
// bubbles up. The reader's outer try/catch turns transient blob errors
// into fallback-to-live-compute (closes plan issue E + cycle-1 #5).

const VERCEL_BLOB_PATH_PREFIX = 'precompute/v1/';

export class VercelBlobStorage implements PrecomputeStorage {
  // Process-singleton URL cache. Vercel Blob URLs are deterministic per
  // key (put() uses addRandomSuffix:false + allowOverwrite:true), so the
  // head() roundtrip to resolve URL → real Blob URL only needs to happen
  // ONCE per (process, key). On Fluid Compute the same instance handles
  // many requests, so this avoids ~5-20ms of Blob CDN latency per
  // page-rebuild after the first. (Negligible per request, but compounds
  // at scale.)
  //
  // Safety: cache entries only become stale if Vercel changes the URL
  // scheme for an existing key — not the same as the Blob's CONTENT
  // changing, which is handled by the Next.js Data Cache tag below. A
  // schema change is a Vercel platform event, not a normal write path.
  // If it ever happens, restarting the function instance clears the
  // Map; there is no in-band invalidation needed.
  //
  // Not cached: the absence path. If head() throws BlobNotFoundError on
  // a key we then later write, the next get() must re-head() to learn
  // the new URL. A negative-cache here would silently return null after
  // the write.
  private urlCache = new Map<string, string>();

  // Lazy-loaded so tests using InMemoryStorage / LocalFs don't pay
  // the import cost. The dynamic import also keeps the @vercel/blob
  // dependency out of any environment that doesn't need it.
  private async loadSdk() {
    return await import('@vercel/blob');
  }

  private pathFor(key: string): string {
    if (key.includes('..')) throw new Error(`[storage] illegal key: ${key}`);
    return `${VERCEL_BLOB_PATH_PREFIX}${key}.json`;
  }

  async put(key: string, json: string): Promise<void> {
    const { put } = await this.loadSdk();
    await put(this.pathFor(key), json, {
      access: 'public',
      addRandomSuffix: false,
      allowOverwrite: true,
      contentType: 'application/json',
    });
  }

  async get(key: string): Promise<string | null> {
    let url = this.urlCache.get(key);
    if (url === undefined) {
      const { head, BlobNotFoundError } = await this.loadSdk();
      try {
        const meta = await head(this.pathFor(key));
        url = meta.url;
        this.urlCache.set(key, url);
      } catch (err) {
        if (err instanceof BlobNotFoundError) return null;
        throw err;
      }
    }
    // `cache: 'force-cache'` (NOT 'no-store') because Next.js 15+ treats
    // any fetch with cache:'no-store' as a dynamic-rendering opt-in for
    // the calling route. The choghadiya/[date] and panchang/date/[date]
    // pages both call this via getPrecomputed() during render — with
    // no-store they were rendered fully dynamic, emitting `cache-control:
    // private, no-cache, no-store, must-revalidate` and bypassing the
    // Vercel edge cache on every request. (Verified 2026-06-07 post-#505
    // deploy: /en/choghadiya/[date] and /en/panchang/date/[date] were the
    // only route families still showing x-vercel-cache: MISS; all other
    // locale-tree routes returned PRERENDER thanks to the cookie-
    // poisoning fix.)
    //
    // `next: { tags: [...] }` is paired with force-cache so a Blob
    // rewrite can bust the Data Cache surgically. Without the tag,
    // revalidatePath would invalidate the Full Route Cache (page HTML)
    // but the inner fetch would still hit the Data Cache and return the
    // OLD Blob body, so the rebuilt page would render stale content.
    // The /api/precompute/revalidate webhook accepts a tags[] field
    // (alongside the existing paths[]) and calls updateTag on each;
    // the nightly cron at .github/workflows/precompute-nightly.yml now
    // sends both the page paths AND the per-Blob tags so the two cache
    // layers flip together.
    const res = await fetch(url, {
      cache: 'force-cache',
      next: { tags: [`precompute:${key}`] },
    });
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`[storage] blob fetch ${res.status} for ${key}`);
    return await res.text();
  }

  async exists(key: string): Promise<boolean> {
    const { head, BlobNotFoundError } = await this.loadSdk();
    try {
      await head(this.pathFor(key));
      return true;
    } catch (err) {
      if (err instanceof BlobNotFoundError) return false;
      throw err;
    }
  }
}

// ─── Selector ───────────────────────────────────────────────────────────────

let _testOverride: PrecomputeStorage | null = null;
let _cachedInstance: PrecomputeStorage | null = null;

/**
 * Test-only — inject a specific storage instance. Also clears the
 * singleton cache so subsequent getStorage() calls re-resolve against
 * the new override / env (avoids cross-test leaks).
 */
export function __setStorageForTests(storage: PrecomputeStorage | null): void {
  _testOverride = storage;
  _cachedInstance = null;
}

/**
 * Resolves the storage backend lazily and caches as a process-level
 * singleton (Gemini #470 finding #3). Prevents per-call allocation —
 * material once VercelBlobStorage owns a real HTTP client + connection
 * pool. The test override path bypasses the cache entirely.
 */
export function getStorage(): PrecomputeStorage {
  if (_testOverride) return _testOverride;
  if (_cachedInstance) return _cachedInstance;

  switch (process.env.PRECOMPUTE_STORAGE) {
    case 'local':
      _cachedInstance = new LocalFsStorage();
      break;
    case 'memory':
      _cachedInstance = new InMemoryStorage();
      break;
    case 'blob':
      _cachedInstance = new VercelBlobStorage();
      break;
    default:
      // Default to local on laptop, throw in production to prevent silent
      // dev-config bleed.
      if (process.env.VERCEL === '1') {
        throw new Error('[storage] PRECOMPUTE_STORAGE not set in Vercel — refusing to default');
      }
      _cachedInstance = new LocalFsStorage();
  }
  return _cachedInstance;
}
