/**
 * Nation Chart Database for Mundane Astrology
 *
 * Foundation/independence chart data for 22 nations.
 * Sources: historical records, Mundane Astrology (Baigent/Campion/Harvey),
 * Nicholas Campion "The Book of World Horoscopes".
 */

export interface NationChart {
  id: string;
  name: {
    en: string;
    hi: string;
    ta: string;
    bn: string;
  };
  date: string;    // ISO: 'YYYY-MM-DD'
  time: string;    // 'HH:MM' local time
  lat: number;
  lng: number;
  timezone: string; // IANA timezone
  capitalCity: string;
  source: string;   // Historical reference
  notes?: string;   // Rectification notes
  flagEmoji?: string;
}

export const NATION_CHARTS: NationChart[] = [
  {
    id: 'india',
    name: { en: 'India', hi: 'भारत', ta: 'இந்தியா', bn: 'ভারত' },
    date: '1947-08-15',
    time: '00:00',
    lat: 28.6139,
    lng: 77.2090,
    timezone: 'Asia/Kolkata',
    capitalCity: 'New Delhi',
    source: 'Indian Independence Act 1947 — midnight transfer of power, New Delhi',
    notes: 'Traditional chart used by most Vedic astrologers. Lagna falls in Taurus.',
    flagEmoji: '🇮🇳',
  },
  {
    id: 'pakistan',
    name: { en: 'Pakistan', hi: 'पाकिस्तान', ta: 'பாகிஸ்தான்', bn: 'পাকিস্তান' },
    date: '1947-08-14',
    time: '09:30',
    lat: 33.7294,
    lng: 73.0931,
    timezone: 'Asia/Karachi',
    capitalCity: 'Islamabad',
    source: 'Pakistan Independence — Aug 14 1947, 9:30 AM Karachi (Campion #188)',
    notes: 'Some astrologers use midnight Aug 14; 9:30 AM is the commonly cited rectified time.',
    flagEmoji: '🇵🇰',
  },
  {
    id: 'usa',
    name: { en: 'United States', hi: 'संयुक्त राज्य अमेरिका', ta: 'அமெரிக்கா', bn: 'আমেরিকা' },
    date: '1776-07-04',
    time: '17:10',
    lat: 39.9526,
    lng: -75.1652,
    timezone: 'America/New_York',
    capitalCity: 'Philadelphia',
    source: 'Sibly chart — Declaration of Independence, Philadelphia, Jul 4 1776, 5:10 PM LMT',
    notes: 'The Sibly chart (Sagittarius rising) is the most widely used by western mundane astrologers.',
    flagEmoji: '🇺🇸',
  },
  {
    id: 'uk',
    name: { en: 'United Kingdom', hi: 'यूनाइटेड किंगडम', ta: 'ஐக்கிய இராஜ்யம்', bn: 'যুক্তরাজ্য' },
    date: '1801-01-01',
    time: '00:00',
    lat: 51.5074,
    lng: -0.1278,
    timezone: 'Europe/London',
    capitalCity: 'London',
    source: 'Act of Union (Great Britain + Ireland) — Jan 1 1801, midnight GMT, London',
    notes: 'Traditional UK chart; Libra rising.',
    flagEmoji: '🇬🇧',
  },
  {
    id: 'china',
    name: { en: "China (PRC)", hi: 'चीन', ta: 'சீனா', bn: 'চীন' },
    date: '1949-10-01',
    time: '15:00',
    lat: 39.9042,
    lng: 116.4074,
    timezone: 'Asia/Shanghai',
    capitalCity: 'Beijing',
    source: "Mao Zedong's proclamation of the PRC — Oct 1 1949, 3:00 PM CST, Beijing (Campion #67)",
    notes: 'Capricorn rising chart.',
    flagEmoji: '🇨🇳',
  },
  {
    id: 'russia',
    name: { en: 'Russia', hi: 'रूस', ta: 'ரஷ்யா', bn: 'রাশিয়া' },
    date: '1991-12-25',
    time: '19:38',
    lat: 55.7558,
    lng: 37.6173,
    timezone: 'Europe/Moscow',
    capitalCity: 'Moscow',
    source: "Gorbachev's resignation dissolving the USSR — Dec 25 1991, 7:38 PM MSK, Moscow",
    notes: 'Russian Federation chart from Soviet dissolution.',
    flagEmoji: '🇷🇺',
  },
  {
    id: 'france',
    name: { en: 'France', hi: 'फ्रांस', ta: 'பிரான்ஸ்', bn: 'ফ্রান্স' },
    date: '1792-09-22',
    time: '00:00',
    lat: 48.8566,
    lng: 2.3522,
    timezone: 'Europe/Paris',
    capitalCity: 'Paris',
    source: 'First French Republic proclaimed — Sep 22 1792, midnight, Paris',
    notes: 'Beginning of the republican era; Libra Sun.',
    flagEmoji: '🇫🇷',
  },
  {
    id: 'germany',
    name: { en: 'Germany', hi: 'जर्मनी', ta: 'ஜெர்மனி', bn: 'জার্মানি' },
    date: '1990-10-03',
    time: '00:00',
    lat: 52.5200,
    lng: 13.4050,
    timezone: 'Europe/Berlin',
    capitalCity: 'Berlin',
    source: 'German Reunification — Oct 3 1990, midnight, Berlin',
    notes: 'Reunified Germany chart.',
    flagEmoji: '🇩🇪',
  },
  {
    id: 'japan',
    name: { en: 'Japan', hi: 'जापान', ta: 'ஜப்பான்', bn: 'জাপান' },
    date: '1947-05-03',
    time: '00:00',
    lat: 35.6762,
    lng: 139.6503,
    timezone: 'Asia/Tokyo',
    capitalCity: 'Tokyo',
    source: 'Japanese Constitution — May 3 1947, midnight JST, Tokyo',
    notes: 'Post-war constitutional Japan.',
    flagEmoji: '🇯🇵',
  },
  {
    id: 'israel',
    name: { en: 'Israel', hi: 'इज़राइल', ta: 'இஸ்ரேல்', bn: 'ইসরায়েল' },
    date: '1948-05-14',
    time: '16:00',
    lat: 31.7683,
    lng: 35.2137,
    timezone: 'Asia/Jerusalem',
    capitalCity: 'Jerusalem',
    source: "Ben-Gurion's proclamation — May 14 1948, 4:00 PM, Tel Aviv (Campion #119)",
    notes: 'Taurus rising; scroll ceremony concluded at 4 PM.',
    flagEmoji: '🇮🇱',
  },
  {
    id: 'australia',
    name: { en: 'Australia', hi: 'ऑस्ट्रेलिया', ta: 'ஆஸ்திரேலியா', bn: 'অস্ট্রেলিয়া' },
    date: '1901-01-01',
    time: '13:35',
    lat: -33.8688,
    lng: 151.2093,
    timezone: 'Australia/Sydney',
    capitalCity: 'Sydney',
    source: 'Commonwealth of Australia — Jan 1 1901, 1:35 PM, Sydney (Campion #15)',
    notes: 'Federation chart.',
    flagEmoji: '🇦🇺',
  },
  {
    id: 'canada',
    name: { en: 'Canada', hi: 'कनाडा', ta: 'கனடா', bn: 'কানাডা' },
    date: '1867-07-01',
    time: '00:00',
    lat: 45.4215,
    lng: -75.6972,
    timezone: 'America/Toronto',
    capitalCity: 'Ottawa',
    source: 'British North America Act — Jul 1 1867, midnight, Ottawa (Campion #52)',
    notes: 'Canadian Confederation chart.',
    flagEmoji: '🇨🇦',
  },
  {
    id: 'brazil',
    name: { en: 'Brazil', hi: 'ब्राज़ील', ta: 'பிரேசில்', bn: 'ব্রাজিল' },
    date: '1822-09-07',
    time: '16:30',
    lat: -23.5505,
    lng: -46.6333,
    timezone: 'America/Sao_Paulo',
    capitalCity: 'São Paulo',
    source: "Pedro I's Cry of Ipiranga — Sep 7 1822, ~4:30 PM, São Paulo",
    notes: 'Independence declaration by Prince Pedro.',
    flagEmoji: '🇧🇷',
  },
  {
    id: 'south_africa',
    name: { en: 'South Africa', hi: 'दक्षिण अफ्रीका', ta: 'தென் ஆப்பிரிக்கா', bn: 'দক্ষিণ আফ্রিকা' },
    date: '1910-05-31',
    time: '00:00',
    lat: -25.7479,
    lng: 28.2293,
    timezone: 'Africa/Johannesburg',
    capitalCity: 'Pretoria',
    source: 'Union of South Africa — May 31 1910, midnight, Pretoria (Campion #229)',
    notes: 'Original union; post-apartheid democracy chart also used (Apr 27 1994).',
    flagEmoji: '🇿🇦',
  },
  {
    id: 'switzerland',
    name: { en: 'Switzerland', hi: 'स्विट्ज़रलैंड', ta: 'சுவிட்சர்லாந்து', bn: 'সুইজারল্যান্ড' },
    date: '1291-08-01',
    time: '00:00',
    lat: 46.8182,
    lng: 8.2275,
    timezone: 'Europe/Zurich',
    capitalCity: 'Bern',
    source: 'Federal Charter of 1291 — Aug 1 1291 (traditional founding date)',
    notes: 'Traditional founding date of Swiss Confederation.',
    flagEmoji: '🇨🇭',
  },
  {
    id: 'eu',
    name: { en: 'European Union', hi: 'यूरोपीय संघ', ta: 'ஐரோப்பிய ஒன்றியம்', bn: 'ইউরোপীয় ইউনিয়ন' },
    date: '1993-11-01',
    time: '00:00',
    lat: 50.8503,
    lng: 4.3517,
    timezone: 'Europe/Brussels',
    capitalCity: 'Brussels',
    source: 'Maastricht Treaty — Nov 1 1993, midnight, Brussels',
    notes: 'Formal establishment of the European Union.',
    flagEmoji: '🇪🇺',
  },
  {
    id: 'nepal',
    name: { en: 'Nepal', hi: 'नेपाल', ta: 'நேபாளம்', bn: 'নেপাল' },
    date: '1768-09-25',
    time: '12:00',
    lat: 27.7172,
    lng: 85.3240,
    timezone: 'Asia/Kathmandu',
    capitalCity: 'Kathmandu',
    source: "Prithvi Narayan Shah's unification of Nepal — Sep 25 1768 (traditional)",
    notes: 'Unification of Nepal by Shah dynasty.',
    flagEmoji: '🇳🇵',
  },
  {
    id: 'sri_lanka',
    name: { en: 'Sri Lanka', hi: 'श्रीलंका', ta: 'இலங்கை', bn: 'শ্রীলঙ্কা' },
    date: '1948-02-04',
    time: '00:00',
    lat: 6.9271,
    lng: 79.8612,
    timezone: 'Asia/Colombo',
    capitalCity: 'Colombo',
    source: 'Ceylon Independence Act — Feb 4 1948, midnight, Colombo',
    notes: 'Independence from Britain (then Ceylon, renamed Sri Lanka 1972).',
    flagEmoji: '🇱🇰',
  },
  {
    id: 'bangladesh',
    name: { en: 'Bangladesh', hi: 'बांग्लादेश', ta: 'வங்களாதேசம்', bn: 'বাংলাদেশ' },
    date: '1971-03-26',
    time: '00:00',
    lat: 23.8103,
    lng: 90.4125,
    timezone: 'Asia/Dhaka',
    capitalCity: 'Dhaka',
    source: 'Bangladesh Declaration of Independence — Mar 26 1971, midnight, Dhaka',
    notes: 'Independence from Pakistan; Mujibur Rahman proclamation.',
    flagEmoji: '🇧🇩',
  },
  {
    id: 'iran',
    name: { en: 'Iran', hi: 'ईरान', ta: 'ஈரான்', bn: 'ইরান' },
    date: '1979-02-11',
    time: '09:00',
    lat: 35.6892,
    lng: 51.3890,
    timezone: 'Asia/Tehran',
    capitalCity: 'Tehran',
    source: 'Islamic Republic of Iran — Feb 11 1979, 9:00 AM, Tehran (Revolution)',
    notes: 'Khomeini Islamic Revolution; monarchical government fell on this date.',
    flagEmoji: '🇮🇷',
  },
  {
    id: 'turkey',
    name: { en: 'Turkey', hi: 'तुर्की', ta: 'துருக்கி', bn: 'তুরস্ক' },
    date: '1923-10-29',
    time: '20:30',
    lat: 39.9334,
    lng: 32.8597,
    timezone: 'Europe/Istanbul',
    capitalCity: 'Ankara',
    source: 'Turkish Republic proclaimed — Oct 29 1923, 8:30 PM, Ankara (Campion #258)',
    notes: "Ataturk's proclamation of the Republic.",
    flagEmoji: '🇹🇷',
  },
  {
    id: 'indonesia',
    name: { en: 'Indonesia', hi: 'इंडोनेशिया', ta: 'இந்தோனேசியா', bn: 'ইন্দোনেশিয়া' },
    date: '1945-08-17',
    time: '10:00',
    lat: -6.2088,
    lng: 106.8456,
    timezone: 'Asia/Jakarta',
    capitalCity: 'Jakarta',
    source: "Sukarno's independence proclamation — Aug 17 1945, 10:00 AM WIB, Jakarta",
    notes: 'Independence from Netherlands.',
    flagEmoji: '🇮🇩',
  },
];

/** Look up a nation by ID */
export function getNationById(id: string): NationChart | undefined {
  return NATION_CHARTS.find((n) => n.id === id);
}

/** All nation IDs for validation */
export const NATION_IDS = NATION_CHARTS.map((n) => n.id);
