'use client';

import { useLocale } from 'next-intl';
import { motion } from 'framer-motion';
import LessonSection from '@/components/learn/LessonSection';
import SanskritTermCard from '@/components/learn/SanskritTermCard';
import { Link } from '@/lib/i18n/navigation';
import { lt } from '@/lib/learn/translations';
import type { LocaleText } from '@/lib/learn/translations';
import LJ from '@/messages/learn/lagna.json';
import { getHeadingFont, getBodyFont, isIndicLocale } from '@/lib/utils/locale-fonts';

const t_ = LJ as unknown as Record<string, LocaleText>;

/* ── Inline array data (not in JSON — kept as local constants) ── */
const INLINE_CALCSTEPS = [
  { en: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset', hi: '1. जन्म समय को UTC में बदलें (समयक्षेत्र घटाकर)', sa: '1. जन्म समय को UTC में बदलें (समयक्षेत्र घटाकर)', mai: '1. जन्म समय को UTC में बदलें (समयक्षेत्र घटाकर)', mr: '1. जन्म समय को UTC में बदलें (समयक्षेत्र घटाकर)', ta: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset', te: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset', bn: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset', kn: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset', gu: '1. Convert birth time to Universal Time (UT) by subtracting the timezone offset' },
  { en: '2. Calculate the Julian Day Number (JD) from the date and UT', hi: '2. तिथि और UT से जूलियन दिवस संख्या (JD) निकालें', sa: '2. तिथि और UT से जूलियन दिवस संख्या (JD) निकालें', mai: '2. तिथि और UT से जूलियन दिवस संख्या (JD) निकालें', mr: '2. तिथि और UT से जूलियन दिवस संख्या (JD) निकालें', ta: '2. Calculate the Julian Day Number (JD) from the date and UT', te: '2. Calculate the Julian Day Number (JD) from the date and UT', bn: '2. Calculate the Julian Day Number (JD) from the date and UT', kn: '2. Calculate the Julian Day Number (JD) from the date and UT', gu: '2. Calculate the Julian Day Number (JD) from the date and UT' },
  { en: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude', hi: '3. JD + भौगोलिक देशान्तर से स्थानीय नाक्षत्र काल (LST) निकालें', sa: '3. JD + भौगोलिक देशान्तर से स्थानीय नाक्षत्र काल (LST) निकालें', mai: '3. JD + भौगोलिक देशान्तर से स्थानीय नाक्षत्र काल (LST) निकालें', mr: '3. JD + भौगोलिक देशान्तर से स्थानीय नाक्षत्र काल (LST) निकालें', ta: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude', te: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude', bn: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude', kn: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude', gu: '3. Compute the Local Sidereal Time (LST) from JD + geographic longitude' },
  { en: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', hi: '4. लग्न सूत्र: tan(लग्न) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', sa: '4. लग्न सूत्र: tan(लग्न) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', mai: '4. लग्न सूत्र: tan(लग्न) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', mr: '4. लग्न सूत्र: tan(लग्न) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', ta: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', te: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', bn: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', kn: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]', gu: '4. Apply the ascendant formula: tan(Lagna) = cos(LST) / [-sin(LST)*cos(e) + tan(f)*sin(e)]' },
  { en: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna', hi: '5. उष्णकटिबन्धीय से सायन (वैदिक) लग्न में बदलने हेतु अयनांश घटाएं', sa: '5. उष्णकटिबन्धीय से सायन (वैदिक) लग्न में बदलने हेतु अयनांश घटाएं', mai: '5. उष्णकटिबन्धीय से सायन (वैदिक) लग्न में बदलने हेतु अयनांश घटाएं', mr: '5. उष्णकटिबन्धीय से सायन (वैदिक) लग्न में बदलने हेतु अयनांश घटाएं', ta: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna', te: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna', bn: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna', kn: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna', gu: '5. Subtract the Ayanamsha to convert from tropical to sidereal (Vedic) Lagna' },
];

const INLINE_LAGNAS = [
  { sign: { en: 'Aries (Mesha)', hi: 'मेष', sa: 'मेष', mai: 'मेष', mr: 'मेष', ta: 'மேஷம் (மேஷம்)', te: 'మేషం (మేషం)', bn: 'মেষ (মেষ)', kn: 'ಮೇಷ (ಮೇಷ)', gu: 'મેષ (મેષ)' }, lord: { en: 'Mars', hi: 'मंगल', sa: 'मंगल', mai: 'मंगल', mr: 'मंगल', ta: 'செவ்வாய்', te: 'కుజుడు', bn: 'মঙ্গল', kn: 'ಕುಜ', gu: 'મંગળ' }, traits: { en: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.', hi: 'अग्रदूत, साहसी, आवेगी, खिलाड़ी शरीर, सिर/चेहरे पर निशान, स्वाभाविक नेता।', sa: 'अग्रदूत, साहसी, आवेगी, खिलाड़ी शरीर, सिर/चेहरे पर निशान, स्वाभाविक नेता।', mai: 'अग्रदूत, साहसी, आवेगी, खिलाड़ी शरीर, सिर/चेहरे पर निशान, स्वाभाविक नेता।', mr: 'अग्रदूत, साहसी, आवेगी, खिलाड़ी शरीर, सिर/चेहरे पर निशान, स्वाभाविक नेता।', ta: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.', te: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.', bn: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.', kn: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.', gu: 'Pioneer, courageous, impulsive, athletic build, scar on head/face likely, natural leader. Life theme: self-assertion and initiative.' } },
  { sign: { en: 'Taurus (Vrishabha)', hi: 'वृषभ', sa: 'वृषभ', mai: 'वृषभ', mr: 'वृषभ', ta: 'ரிஷபம் (வ்ருஷபம்)', te: 'వృషభం (వృషభం)', bn: 'বৃষ (বৃষভ)', kn: 'ವೃಷಭ (ವೃಷಭ)', gu: 'વૃષભ (વૃષભ)' }, lord: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्र', mai: 'शुक्र', mr: 'शुक्र', ta: 'சுக்கிரன்', te: 'శుక్రుడు', bn: 'শুক্র', kn: 'ಶುಕ್ರ', gu: 'શુક્ર' }, traits: { en: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.', hi: 'स्थिर, कलात्मक, संवेदनशील, मजबूत शरीर, सुन्दर आँखें, सुख-प्रेमी।', sa: 'स्थिर, कलात्मक, संवेदनशील, मजबूत शरीर, सुन्दर आँखें, सुख-प्रेमी।', mai: 'स्थिर, कलात्मक, संवेदनशील, मजबूत शरीर, सुन्दर आँखें, सुख-प्रेमी।', mr: 'स्थिर, कलात्मक, संवेदनशील, मजबूत शरीर, सुन्दर आँखें, सुख-प्रेमी।', ta: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.', te: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.', bn: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.', kn: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.', gu: 'Steady, artistic, sensual, stocky/solid build, beautiful eyes, loves comfort. Life theme: building security and beauty.' } },
  { sign: { en: 'Gemini (Mithuna)', hi: 'मिथुन', sa: 'मिथुन', mai: 'मिथुन', mr: 'मिथुन', ta: 'மிதுனம் (மிதுனம்)', te: 'మిథునం (మిథునం)', bn: 'মিথুন (মিথুন)', kn: 'ಮಿಥುನ (ಮಿಥುನ)', gu: 'મિથુન (મિથુન)' }, lord: { en: 'Mercury', hi: 'बुध', sa: 'बुध', mai: 'बुध', mr: 'बुध', ta: 'புதன்', te: 'బుధుడు', bn: 'বুধ', kn: 'ಬುಧ', gu: 'બુધ' }, traits: { en: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.', hi: 'बौद्धिक, संवादकुशल, बहुमुखी, दुबला शरीर, युवा दिखावट, द्विस्वभाव।', sa: 'बौद्धिक, संवादकुशल, बहुमुखी, दुबला शरीर, युवा दिखावट, द्विस्वभाव।', mai: 'बौद्धिक, संवादकुशल, बहुमुखी, दुबला शरीर, युवा दिखावट, द्विस्वभाव।', mr: 'बौद्धिक, संवादकुशल, बहुमुखी, दुबला शरीर, युवा दिखावट, द्विस्वभाव।', ta: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.', te: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.', bn: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.', kn: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.', gu: 'Intellectual, communicative, versatile, slender build, youthful appearance, dual nature. Life theme: learning and connecting.' } },
  { sign: { en: 'Cancer (Karka)', hi: 'कर्क', sa: 'कर्क', mai: 'कर्क', mr: 'कर्क', ta: 'கடகம் (கர்க)', te: 'కర్కాటకం (కర్కాటకం)', bn: 'কর্কট (কর্কট)', kn: 'ಕರ್ಕಾಟಕ (ಕರ್ಕಾಟಕ)', gu: 'કર્ક (કર્ક)' }, lord: { en: 'Moon', hi: 'चन्द्र', sa: 'चन्द्र', mai: 'चन्द्र', mr: 'चन्द्र', ta: 'சந்திரன்', te: 'చంద్రుడు', bn: 'চন্দ্র', kn: 'ಚಂದ್ರ', gu: 'ચંદ્ર' }, traits: { en: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.', hi: 'पालनकर्ता, भावुक, सहजज्ञानी, गोल चेहरा, गृह और परिवार प्रेमी।', sa: 'पालनकर्ता, भावुक, सहजज्ञानी, गोल चेहरा, गृह और परिवार प्रेमी।', mai: 'पालनकर्ता, भावुक, सहजज्ञानी, गोल चेहरा, गृह और परिवार प्रेमी।', mr: 'पालनकर्ता, भावुक, सहजज्ञानी, गोल चेहरा, गृह और परिवार प्रेमी।', ta: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.', te: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.', bn: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.', kn: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.', gu: 'Nurturing, emotional, intuitive, round face, love of home and family. Life theme: emotional security and caregiving.' } },
  { sign: { en: 'Leo (Simha)', hi: 'सिंह', sa: 'सिंह', mai: 'सिंह', mr: 'सिंह', ta: 'சிம்மம் (சிம்மம்)', te: 'సింహం (సింహం)', bn: 'সিংহ (সিংহ)', kn: 'ಸಿಂಹ (ಸಿಂಹ)', gu: 'સિંહ (સિંહ)' }, lord: { en: 'Sun', hi: 'सूर्य', sa: 'सूर्य', mai: 'सूर्य', mr: 'सूर्य', ta: 'சூரியன்', te: 'సూర్యుడు', bn: 'সূর্য', kn: 'ಸೂರ್ಯ', gu: 'સૂર્ય' }, traits: { en: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.', hi: 'राजसी, आत्मविश्वासी, उदार, चौड़ी छाती, प्रमुख ललाट, आकर्षक उपस्थिति।', sa: 'राजसी, आत्मविश्वासी, उदार, चौड़ी छाती, प्रमुख ललाट, आकर्षक उपस्थिति।', mai: 'राजसी, आत्मविश्वासी, उदार, चौड़ी छाती, प्रमुख ललाट, आकर्षक उपस्थिति।', mr: 'राजसी, आत्मविश्वासी, उदार, चौड़ी छाती, प्रमुख ललाट, आकर्षक उपस्थिति।', ta: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.', te: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.', bn: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.', kn: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.', gu: 'Regal, confident, generous, broad chest, prominent forehead, charismatic presence. Life theme: self-expression and leadership.' } },
  { sign: { en: 'Virgo (Kanya)', hi: 'कन्या', sa: 'कन्या', mai: 'कन्या', mr: 'कन्या', ta: 'கன்னி (கன்யா)', te: 'కన్య (కన్య)', bn: 'কন্যা (কন্যা)', kn: 'ಕನ್ಯಾ (ಕನ್ಯಾ)', gu: 'કન્યા (કન્યા)' }, lord: { en: 'Mercury', hi: 'बुध', sa: 'बुध', mai: 'बुध', mr: 'बुध', ta: 'புதன்', te: 'బుధుడు', bn: 'বুধ', kn: 'ಬುಧ', gu: 'બુધ' }, traits: { en: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.', hi: 'विश्लेषणात्मक, पूर्णतावादी, स्वास्थ्य-सजग, दुबला, सेवा-उन्मुख।', sa: 'विश्लेषणात्मक, पूर्णतावादी, स्वास्थ्य-सजग, दुबला, सेवा-उन्मुख।', mai: 'विश्लेषणात्मक, पूर्णतावादी, स्वास्थ्य-सजग, दुबला, सेवा-उन्मुख।', mr: 'विश्लेषणात्मक, पूर्णतावादी, स्वास्थ्य-सजग, दुबला, सेवा-उन्मुख।', ta: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.', te: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.', bn: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.', kn: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.', gu: 'Analytical, perfectionist, health-conscious, slender build, youthful, service-oriented. Life theme: analysis and improvement.' } },
  { sign: { en: 'Libra (Tula)', hi: 'तुला', sa: 'तुला', mai: 'तुला', mr: 'तुला', ta: 'துலாம் (துலா)', te: 'తులా (తులా)', bn: 'তুলা (তুলা)', kn: 'ತುಲಾ (ತುಲಾ)', gu: 'તુલા (તુલા)' }, lord: { en: 'Venus', hi: 'शुक्र', sa: 'शुक्र', mai: 'शुक्र', mr: 'शुक्र', ta: 'சுக்கிரன்', te: 'శుక్రుడు', bn: 'শুক্র', kn: 'ಶುಕ್ರ', gu: 'શુક્ર' }, traits: { en: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.', hi: 'कूटनीतिक, सौन्दर्यप्रेमी, साझेदारी-खोजी, आकर्षक, सन्तुलित।', sa: 'कूटनीतिक, सौन्दर्यप्रेमी, साझेदारी-खोजी, आकर्षक, सन्तुलित।', mai: 'कूटनीतिक, सौन्दर्यप्रेमी, साझेदारी-खोजी, आकर्षक, सन्तुलित।', mr: 'कूटनीतिक, सौन्दर्यप्रेमी, साझेदारी-खोजी, आकर्षक, सन्तुलित।', ta: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.', te: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.', bn: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.', kn: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.', gu: 'Diplomatic, aesthetic, partnership-seeking, attractive features, balanced build. Life theme: harmony and relationships.' } },
  { sign: { en: 'Scorpio (Vrishchika)', hi: 'वृश्चिक', sa: 'वृश्चिक', mai: 'वृश्चिक', mr: 'वृश्चिक', ta: 'விருச்சிகம் (வ்ருச்சிகம்)', te: 'వృశ్చికం (వృశ్చికం)', bn: 'বৃশ্চিক (বৃশ্চিক)', kn: 'ವೃಶ್ಚಿಕ (ವೃಶ್ಚಿಕ)', gu: 'વૃશ્ચિક (વૃશ્ચિક)' }, lord: { en: 'Mars', hi: 'मंगल', sa: 'मंगल', mai: 'मंगल', mr: 'मंगल', ta: 'செவ்வாய்', te: 'కుజుడు', bn: 'মঙ্গল', kn: 'ಕುಜ', gu: 'મંગળ' }, traits: { en: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.', hi: 'तीव्र, गुप्त, परिवर्तनशील, चुम्बकीय आँखें, पेशीय, अन्वेषी मन।', sa: 'तीव्र, गुप्त, परिवर्तनशील, चुम्बकीय आँखें, पेशीय, अन्वेषी मन।', mai: 'तीव्र, गुप्त, परिवर्तनशील, चुम्बकीय आँखें, पेशीय, अन्वेषी मन।', mr: 'तीव्र, गुप्त, परिवर्तनशील, चुम्बकीय आँखें, पेशीय, अन्वेषी मन।', ta: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.', te: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.', bn: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.', kn: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.', gu: 'Intense, secretive, transformative, magnetic eyes, muscular build, investigative mind. Life theme: transformation and power.' } },
  { sign: { en: 'Sagittarius (Dhanu)', hi: 'धनु', sa: 'धनु', mai: 'धनु', mr: 'धनु', ta: 'தனுசு (தனுசு)', te: 'ధనుస్సు (ధనుస్సు)', bn: 'ধনু (ধনু)', kn: 'ಧನು (ಧನು)', gu: 'ધનુ (ધનુ)' }, lord: { en: 'Jupiter', hi: 'गुरु', sa: 'गुरु', mai: 'गुरु', mr: 'गुरु', ta: 'குரு', te: 'గురువు', bn: 'বৃহস্পতি', kn: 'ಗುರು', gu: 'ગુરુ' }, traits: { en: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.', hi: 'दार्शनिक, साहसिक, आशावादी, लम्बा/बड़ा शरीर, गुरु स्वरूप।', sa: 'दार्शनिक, साहसिक, आशावादी, लम्बा/बड़ा शरीर, गुरु स्वरूप।', mai: 'दार्शनिक, साहसिक, आशावादी, लम्बा/बड़ा शरीर, गुरु स्वरूप।', mr: 'दार्शनिक, साहसिक, आशावादी, लम्बा/बड़ा शरीर, गुरु स्वरूप।', ta: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.', te: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.', bn: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.', kn: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.', gu: 'Philosophical, adventurous, optimistic, tall/large frame, prominent thighs, teacher archetype. Life theme: wisdom and expansion.' } },
  { sign: { en: 'Capricorn (Makara)', hi: 'मकर', sa: 'मकर', mai: 'मकर', mr: 'मकर', ta: 'மகரம் (மகரம்)', te: 'మకరం (మకరం)', bn: 'মকর (মকর)', kn: 'ಮಕರ (ಮಕರ)', gu: 'મકર (મકર)' }, lord: { en: 'Saturn', hi: 'शनि', sa: 'शनि', mai: 'शनि', mr: 'शनि', ta: 'சனி', te: 'శని', bn: 'শনি', kn: 'ಶನಿ', gu: 'શનિ' }, traits: { en: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.', hi: 'अनुशासित, महत्वाकांक्षी, धैर्यवान, दुबला, प्रमुख हड्डियाँ, उलटी उम्र।', sa: 'अनुशासित, महत्वाकांक्षी, धैर्यवान, दुबला, प्रमुख हड्डियाँ, उलटी उम्र।', mai: 'अनुशासित, महत्वाकांक्षी, धैर्यवान, दुबला, प्रमुख हड्डियाँ, उलटी उम्र।', mr: 'अनुशासित, महत्वाकांक्षी, धैर्यवान, दुबला, प्रमुख हड्डियाँ, उलटी उम्र।', ta: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.', te: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.', bn: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.', kn: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.', gu: 'Disciplined, ambitious, patient, lean build, prominent bones/knees, ages in reverse. Life theme: achievement through persistence.' } },
  { sign: { en: 'Aquarius (Kumbha)', hi: 'कुम्भ', sa: 'कुम्भ', mai: 'कुम्भ', mr: 'कुम्भ', ta: 'கும்பம் (கும்பம்)', te: 'కుంభం (కుంభం)', bn: 'কুম্ভ (কুম্ভ)', kn: 'ಕುಂಭ (ಕುಂಭ)', gu: 'કુંભ (કુંભ)' }, lord: { en: 'Saturn', hi: 'शनि', sa: 'शनि', mai: 'शनि', mr: 'शनि', ta: 'சனி', te: 'శని', bn: 'শনি', kn: 'ಶನಿ', gu: 'શનિ' }, traits: { en: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.', hi: 'मानवतावादी, विलक्षण, वैज्ञानिक, लम्बा, आदर्शवादी पर विरक्त।', sa: 'मानवतावादी, विलक्षण, वैज्ञानिक, लम्बा, आदर्शवादी पर विरक्त।', mai: 'मानवतावादी, विलक्षण, वैज्ञानिक, लम्बा, आदर्शवादी पर विरक्त।', mr: 'मानवतावादी, विलक्षण, वैज्ञानिक, लम्बा, आदर्शवादी पर विरक्त।', ta: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.', te: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.', bn: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.', kn: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.', gu: 'Humanitarian, eccentric, scientific, tall, prominent calves, detached yet idealistic. Life theme: innovation and social reform.' } },
  { sign: { en: 'Pisces (Meena)', hi: 'मीन', sa: 'मीन', mai: 'मीन', mr: 'मीन', ta: 'மீனம் (மீனம்)', te: 'మీనం (మీనం)', bn: 'মীন (মীন)', kn: 'ಮೀನ (ಮೀನ)', gu: 'મીન (મીન)' }, lord: { en: 'Jupiter', hi: 'गुरु', sa: 'गुरु', mai: 'गुरु', mr: 'गुरु', ta: 'குரு', te: 'గురువు', bn: 'বৃহস্পতি', kn: 'ಗುರು', gu: 'ગુરુ' }, traits: { en: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.', hi: 'रहस्यमय, करुणामय, सृजनात्मक, कोमल, स्वप्निल आँखें, आध्यात्मिक।', sa: 'रहस्यमय, करुणामय, सृजनात्मक, कोमल, स्वप्निल आँखें, आध्यात्मिक।', mai: 'रहस्यमय, करुणामय, सृजनात्मक, कोमल, स्वप्निल आँखें, आध्यात्मिक।', mr: 'रहस्यमय, करुणामय, सृजनात्मक, कोमल, स्वप्निल आँखें, आध्यात्मिक।', ta: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.', te: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.', bn: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.', kn: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.', gu: 'Mystical, compassionate, creative, soft features, dreamy eyes, spiritual inclination. Life theme: transcendence and spiritual growth.' } },
];

const INLINE_SPECIALLAGNAS = [
  { name: { en: 'Chandra Lagna (Moon Ascendant)', hi: 'चन्द्र लग्न', sa: 'चन्द्र लग्न', mai: 'चन्द्र लग्न', mr: 'चन्द्र लग्न', ta: 'சந்திர லக்னம்', te: 'చంద్ర లగ్నం', bn: 'চন্দ্র লগ্ন', kn: 'ಚಂದ್ರ ಲಗ್ನ', gu: 'ચંદ્ર લગ્ન' }, desc: { en: 'Using the Moon\'s sign as the 1st house. Reveals the emotional and mental landscape.', hi: 'चन्द्रमा की राशि को प्रथम भाव मानकर। भावनात्मक और मानसिक परिदृश्य उजागर करता है।' } },
  { name: { en: 'Surya Lagna (Sun Ascendant)', hi: 'सूर्य लग्न', sa: 'सूर्य लग्न', mai: 'सूर्य लग्न', mr: 'सूर्य लग्न', ta: 'சூரிய லக்னம்', te: 'సూర్య లగ్నం', bn: 'সূর্য লগ্ন', kn: 'ಸೂರ್ಯ ಲಗ್ನ', gu: 'સૂર્ય લગ્ન' }, desc: { en: 'Using the Sun\'s sign as the 1st house. Illuminates career, authority, and the soul\'s purpose.', hi: 'सूर्य की राशि को प्रथम भाव मानकर। कैरियर, अधिकार और आत्मा का उद्देश्य प्रकाशित करता है।' } },
  { name: { en: 'Hora Lagna', hi: 'होरा लग्न', sa: 'होरा लग्न', mai: 'होरा लग्न', mr: 'होरा लग्न', ta: 'ஹோரா லக்னம்', te: 'హోరా లగ్నం', bn: 'হোরা লগ্ন', kn: 'ಹೋರಾ ಲಗ್ನ', gu: 'હોરા લગ્ન' }, desc: { en: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.', hi: 'सूर्योदय से प्रति घण्टा एक राशि बढ़ता है। धन क्षमता और वित्तीय गति उजागर करता है।', sa: 'सूर्योदय से प्रति घण्टा एक राशि बढ़ता है। धन क्षमता और वित्तीय गति उजागर करता है।', mai: 'सूर्योदय से प्रति घण्टा एक राशि बढ़ता है। धन क्षमता और वित्तीय गति उजागर करता है।', mr: 'सूर्योदय से प्रति घण्टा एक राशि बढ़ता है। धन क्षमता और वित्तीय गति उजागर करता है।', ta: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.', te: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.', bn: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.', kn: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.', gu: 'Advances at the rate of one sign per hour from sunrise. Reveals wealth potential and financial trajectory.' } },
  { name: { en: 'Ghati Lagna (Ghatika Lagna)', hi: 'घटी लग्न', sa: 'घटी लग्न', mai: 'घटी लग्न', mr: 'घटी लग्न', ta: 'காடி லக்னம் (காடிகா லக்னம்)', te: 'ఘటి లగ్నం (ఘటికా లగ్నం)', bn: 'ঘটি লগ্ন (ঘটিকা লগ্ন)', kn: 'ಘಟಿ ಲಗ್ನ (ಘಟಿಕಾ ಲಗ್ನ)', gu: 'ઘટી લગ્ન (ઘટિકા લગ્ન)' }, desc: { en: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.', hi: 'प्रति घटी (24 मिनट) एक राशि बढ़ता है। शक्ति, अधिकार और सार्वजनिक प्रतिष्ठा से सम्बन्धित।', sa: 'प्रति घटी (24 मिनट) एक राशि बढ़ता है। शक्ति, अधिकार और सार्वजनिक प्रतिष्ठा से सम्बन्धित।', mai: 'प्रति घटी (24 मिनट) एक राशि बढ़ता है। शक्ति, अधिकार और सार्वजनिक प्रतिष्ठा से सम्बन्धित।', mr: 'प्रति घटी (24 मिनट) एक राशि बढ़ता है। शक्ति, अधिकार और सार्वजनिक प्रतिष्ठा से सम्बन्धित।', ta: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.', te: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.', bn: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.', kn: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.', gu: 'Advances at the rate of one sign per ghati (24 minutes). Related to power, authority, and public reputation.' } },
  { name: { en: 'Varnada Lagna', hi: 'वर्णद लग्न', sa: 'वर्णद लग्न', mai: 'वर्णद लग्न', mr: 'वर्णद लग्न', ta: 'வர்ணத லக்னம்', te: 'వర్ణద లగ్నం', bn: 'বর্ণদ লগ্ন', kn: 'ವರ್ಣದ ಲಗ್ನ', gu: 'વર્ણદ લગ્ન' }, desc: { en: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.', hi: 'लग्न और होरा लग्न की अन्तर्क्रिया से गणना। जैमिनी ज्योतिष में वर्ण और दीर्घायु निर्धारण हेतु।', sa: 'लग्न और होरा लग्न की अन्तर्क्रिया से गणना। जैमिनी ज्योतिष में वर्ण और दीर्घायु निर्धारण हेतु।', mai: 'लग्न और होरा लग्न की अन्तर्क्रिया से गणना। जैमिनी ज्योतिष में वर्ण और दीर्घायु निर्धारण हेतु।', mr: 'लग्न और होरा लग्न की अन्तर्क्रिया से गणना। जैमिनी ज्योतिष में वर्ण और दीर्घायु निर्धारण हेतु।', ta: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.', te: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.', bn: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.', kn: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.', gu: 'Computed from the interaction of Lagna and Hora Lagna. Used in Jaimini astrology for determining varna and longevity.' } },
  { name: { en: 'Arudha Lagna (Pada Lagna)', hi: 'आरूढ लग्न (पद लग्न)', sa: 'आरूढ लग्न (पद लग्न)', mai: 'आरूढ लग्न (पद लग्न)', mr: 'आरूढ लग्न (पद लग्न)', ta: 'ஆருட லக்னம் (பாத லக்னம்)', te: 'ఆరూఢ లగ్నం (పాద లగ్నం)', bn: 'আরূঢ় লগ্ন (পাদ লগ্ন)', kn: 'ಆರೂಢ ಲಗ್ನ (ಪಾದ ಲಗ್ನ)', gu: 'આરૂઢ લગ્ન (પાદ લગ્ન)' }, desc: { en: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.', hi: 'प्रतिबिम्ब लग्न -- दिखाता है कि संसार आपको कैसे देखता है बनाम आप वास्तव में कौन हैं।', sa: 'प्रतिबिम्ब लग्न -- दिखाता है कि संसार आपको कैसे देखता है बनाम आप वास्तव में कौन हैं।', mai: 'प्रतिबिम्ब लग्न -- दिखाता है कि संसार आपको कैसे देखता है बनाम आप वास्तव में कौन हैं।', mr: 'प्रतिबिम्ब लग्न -- दिखाता है कि संसार आपको कैसे देखता है बनाम आप वास्तव में कौन हैं।', ta: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.', te: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.', bn: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.', kn: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.', gu: 'The "image" lagna -- shows how the world perceives you versus who you actually are. Crucial in Jaimini system.' } },
];

const INLINE_RECTMETHODS = [
  { en: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna', hi: 'तत्त्व शोधन -- लग्न के शासक तत्व से जन्म समय की जाँच', sa: 'तत्त्व शोधन -- लग्न के शासक तत्व से जन्म समय की जाँच', mai: 'तत्त्व शोधन -- लग्न के शासक तत्व से जन्म समय की जाँच', mr: 'तत्त्व शोधन -- लग्न के शासक तत्व से जन्म समय की जाँच', ta: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna', te: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna', bn: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna', kn: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna', gu: 'Tattwa Shodhana -- checking birth-time against the ruling element of the Lagna' },
  { en: 'Pranapada -- verifying using the Pranapada Lagna position', hi: 'प्राणपद -- प्राणपद लग्न स्थिति से सत्यापन', sa: 'प्राणपद -- प्राणपद लग्न स्थिति से सत्यापन', mai: 'प्राणपद -- प्राणपद लग्न स्थिति से सत्यापन', mr: 'प्राणपद -- प्राणपद लग्न स्थिति से सत्यापन', ta: 'Pranapada -- verifying using the Pranapada Lagna position', te: 'Pranapada -- verifying using the Pranapada Lagna position', bn: 'Pranapada -- verifying using the Pranapada Lagna position', kn: 'Pranapada -- verifying using the Pranapada Lagna position', gu: 'Pranapada -- verifying using the Pranapada Lagna position' },
  { en: 'Event-based -- matching major life events to dasha transitions', hi: 'घटना-आधारित -- प्रमुख जीवन घटनाओं को दशा परिवर्तनों से मिलान', sa: 'घटना-आधारित -- प्रमुख जीवन घटनाओं को दशा परिवर्तनों से मिलान', mai: 'घटना-आधारित -- प्रमुख जीवन घटनाओं को दशा परिवर्तनों से मिलान', mr: 'घटना-आधारित -- प्रमुख जीवन घटनाओं को दशा परिवर्तनों से मिलान', ta: 'Event-based -- matching major life events to dasha transitions', te: 'Event-based -- matching major life events to dasha transitions', bn: 'Event-based -- matching major life events to dasha transitions', kn: 'Event-based -- matching major life events to dasha transitions', gu: 'Event-based -- matching major life events to dasha transitions' },
  { en: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns', hi: 'नवांश सत्यापन -- D9 कुण्डली विवाह और धार्मिक जीवन पैटर्न से सुसंगत है', sa: 'नवांश सत्यापन -- D9 कुण्डली विवाह और धार्मिक जीवन पैटर्न से सुसंगत है', mai: 'नवांश सत्यापन -- D9 कुण्डली विवाह और धार्मिक जीवन पैटर्न से सुसंगत है', mr: 'नवांश सत्यापन -- D9 कुण्डली विवाह और धार्मिक जीवन पैटर्न से सुसंगत है', ta: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns', te: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns', bn: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns', kn: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns', gu: 'Navamsha verification -- ensuring D9 chart consistency with marriage and dharmic patterns' },
];

const INLINE_COMPARISON = [
  { aspect: { en: 'Lagna (Ascendant)', hi: 'लग्न', sa: 'लग्न', mai: 'लग्न', mr: 'लग्न', ta: 'லக்னம் (அசன்டண்ட்)', te: 'లగ్నం (ఉదయలగ్నం)', bn: 'লগ্ন (উদয়লগ্ন)', kn: 'ಲಗ್ನ (ಉದಯಲಗ್ನ)', gu: 'લગ્ન (ઉદયલગ્ન)' }, governs: { en: 'Physical body, appearance, personality, overall life direction, health, longevity', hi: 'शारीरिक शरीर, रूप, व्यक्तित्व, जीवन दिशा, स्वास्थ्य', sa: 'शारीरिक शरीर, रूप, व्यक्तित्व, जीवन दिशा, स्वास्थ्य', mai: 'शारीरिक शरीर, रूप, व्यक्तित्व, जीवन दिशा, स्वास्थ्य', mr: 'शारीरिक शरीर, रूप, व्यक्तित्व, जीवन दिशा, स्वास्थ्य', ta: 'உடல், தோற்றம், ஆளுமை, ஒட்டுமொத்த வாழ்க்கை திசை, ஆரோக்கியம், ஆயுள்', te: 'శరీరం, రూపం, వ్యక్తిత్వం, జీవిత దిశ, ఆరోగ్యం, ఆయుష్షు', bn: 'শরীর, চেহারা, ব্যক্তিত্ব, জীবনের দিক, স্বাস্থ্য, আয়ু', kn: 'ದೇಹ, ರೂಪ, ವ್ಯಕ್ತಿತ್ವ, ಜೀವನ ದಿಕ್ಕು, ಆರೋಗ್ಯ, ಆಯುಷ್ಯ', gu: 'શરીર, દેખાવ, વ્યક્તિત્વ, જીવનની દિશા, આરોગ્ય, આયુષ્ય' }, changes: { en: 'Every ~2 hours', hi: 'हर ~2 घण्टे', sa: 'हर ~2 घण्टे', mai: 'हर ~2 घण्टे', mr: 'हर ~2 घण्टे', ta: 'ஒவ்வொரு ~2 மணி நேரமும்', te: 'ప్రతి ~2 గంటలకు', bn: 'প্রতি ~২ ঘণ্টায়', kn: 'ಪ್ರತಿ ~2 ಗಂಟೆಗೆ', gu: 'દર ~2 કલાકે' } },
  { aspect: { en: 'Moon Sign (Rashi)', hi: 'चन्द्र राशि', sa: 'चन्द्र राशि', mai: 'चन्द्र राशि', mr: 'चन्द्र राशि', ta: 'சந்திர ராசி', te: 'చంద్ర రాశి', bn: 'চন্দ্র রাশি', kn: 'ಚಂದ್ರ ರಾಶಿ', gu: 'ચંદ્ર રાશિ' }, governs: { en: 'Mind, emotions, instincts, habits, comfort zone, mother', hi: 'मन, भावनाएँ, सहज वृत्तियाँ, आदतें, माता', sa: 'मन, भावनाएँ, सहज वृत्तियाँ, आदतें, माता', mai: 'मन, भावनाएँ, सहज वृत्तियाँ, आदतें, माता', mr: 'मन, भावनाएँ, सहज वृत्तियाँ, आदतें, माता', ta: 'மனம், உணர்வுகள், உள்ளுணர்வு, பழக்கங்கள், ஆறுதல் வலயம், தாய்', te: 'మనస్సు, భావాలు, అంతర్జ్ఞానం, అలవాట్లు, సౌకర్య మండలం, తల్లి', bn: 'মন, আবেগ, সহজাত প্রবৃত্তি, অভ্যাস, স্বাচ্ছন্দ্য অঞ্চল, মাতা', kn: 'ಮನಸ್ಸು, ಭಾವನೆಗಳು, ಸಹಜ ಪ್ರವೃತ್ತಿ, ಅಭ್ಯಾಸ, ಸೌಕರ್ಯ ವಲಯ, ತಾಯಿ', gu: 'મન, લાગણીઓ, સહજવૃત્તિ, ટેવો, આરામ ક્ષેત્ર, માતા' }, changes: { en: 'Every ~2.5 days', hi: 'हर ~2.5 दिन', sa: 'हर ~2.5 दिन', mai: 'हर ~2.5 दिन', mr: 'हर ~2.5 दिन', ta: 'ஒவ்வொரு ~2.5 நாளும்', te: 'ప్రతి ~2.5 రోజులకు', bn: 'প্রতি ~২.৫ দিনে', kn: 'ಪ್ರತಿ ~2.5 ದಿನಕ್ಕೆ', gu: 'દર ~2.5 દિવસે' } },
  { aspect: { en: 'Sun Sign (Rashi)', hi: 'सूर्य राशि', sa: 'सूर्य राशि', mai: 'सूर्य राशि', mr: 'सूर्य राशि', ta: 'சூரிய ராசி', te: 'సూర్య రాశి', bn: 'সূর্য রাশি', kn: 'ಸೂರ್ಯ ರಾಶಿ', gu: 'સૂર્ય રાશિ' }, governs: { en: 'Soul, ego, authority, father, government, vitality', hi: 'आत्मा, अहंकार, अधिकार, पिता, सरकार', sa: 'आत्मा, अहंकार, अधिकार, पिता, सरकार', mai: 'आत्मा, अहंकार, अधिकार, पिता, सरकार', mr: 'आत्मा, अहंकार, अधिकार, पिता, सरकार', ta: 'ஆன்மா, அகம், அதிகாரம், தந்தை, அரசு, உயிர்ச்சக்தி', te: 'ఆత్మ, అహం, అధికారం, తండ్రి, ప్రభుత్వం, జీవశక్తి', bn: 'আত্মা, অহং, কর্তৃত্ব, পিতা, সরকার, প্রাণশক্তি', kn: 'ಆತ್ಮ, ಅಹಂ, ಅಧಿಕಾರ, ತಂದೆ, ಸರ್ಕಾರ, ಜೀವಶಕ್ತಿ', gu: 'આત્મા, અહં, સત્તા, પિતા, સરકાર, જીવનશક્તિ' }, changes: { en: 'Every ~30 days', hi: 'हर ~30 दिन', sa: 'हर ~30 दिन', mai: 'हर ~30 दिन', mr: 'हर ~30 दिन', ta: 'ஒவ்வொரு ~30 நாளும்', te: 'ప్రతి ~30 రోజులకు', bn: 'প্রতি ~৩০ দিনে', kn: 'ಪ್ರತಿ ~30 ದಿನಕ್ಕೆ', gu: 'દર ~30 દિવસે' } },
];

const INLINE_MISCONCEPTIONS = [
  { myth: { en: '"My Sun sign is my main sign"', hi: '"मेरी सूर्य राशि मेरी मुख्य राशि है"', sa: '"मेरी सूर्य राशि मेरी मुख्य राशि है"', mai: '"मेरी सूर्य राशि मेरी मुख्य राशि है"', mr: '"मेरी सूर्य राशि मेरी मुख्य राशि है"', ta: '"My Sun sign is my main sign"', te: '"My Sun sign is my main sign"', bn: '"My Sun sign is my main sign"', kn: '"My Sun sign is my main sign"', gu: '"My Sun sign is my main sign"' }, truth: { en: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.', hi: 'वैदिक ज्योतिष में लग्न और चन्द्र राशि सूर्य राशि से कहीं अधिक महत्वपूर्ण हैं।', sa: 'वैदिक ज्योतिष में लग्न और चन्द्र राशि सूर्य राशि से कहीं अधिक महत्वपूर्ण हैं।', mai: 'वैदिक ज्योतिष में लग्न और चन्द्र राशि सूर्य राशि से कहीं अधिक महत्वपूर्ण हैं।', mr: 'वैदिक ज्योतिष में लग्न और चन्द्र राशि सूर्य राशि से कहीं अधिक महत्वपूर्ण हैं।', ta: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.', te: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.', bn: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.', kn: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.', gu: 'In Vedic astrology, the Lagna and Moon sign are far more important than the Sun sign.' } },
  { myth: { en: '"The Lagna is just one of 12 houses"', hi: '"लग्न केवल 12 भावों में से एक है"', sa: '"लग्न केवल 12 भावों में से एक है"', mai: '"लग्न केवल 12 भावों में से एक है"', mr: '"लग्न केवल 12 भावों में से एक है"', ta: '"The Lagna is just one of 12 houses"', te: '"The Lagna is just one of 12 houses"', bn: '"The Lagna is just one of 12 houses"', kn: '"The Lagna is just one of 12 houses"', gu: '"The Lagna is just one of 12 houses"' }, truth: { en: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.', hi: 'लग्न सभी 12 भावों का आधार है। सही लग्न के बिना, प्रत्येक भाव विश्लेषण गलत है।', sa: 'लग्न सभी 12 भावों का आधार है। सही लग्न के बिना, प्रत्येक भाव विश्लेषण गलत है।', mai: 'लग्न सभी 12 भावों का आधार है। सही लग्न के बिना, प्रत्येक भाव विश्लेषण गलत है।', mr: 'लग्न सभी 12 भावों का आधार है। सही लग्न के बिना, प्रत्येक भाव विश्लेषण गलत है।', ta: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.', te: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.', bn: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.', kn: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.', gu: 'The Lagna is the ANCHOR of all 12 houses. Without a correct Lagna, every house analysis is wrong.' } },
  { myth: { en: '"Birth time doesn\'t matter much"', hi: '"जन्म समय ज्यादा मायने नहीं रखता"' }, truth: { en: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.', hi: 'जन्म समय में 4 मिनट की त्रुटि लग्न को 1 अंश खिसकाती है -- नवांश बदलने के लिए पर्याप्त।', sa: 'जन्म समय में 4 मिनट की त्रुटि लग्न को 1 अंश खिसकाती है -- नवांश बदलने के लिए पर्याप्त।', mai: 'जन्म समय में 4 मिनट की त्रुटि लग्न को 1 अंश खिसकाती है -- नवांश बदलने के लिए पर्याप्त।', mr: 'जन्म समय में 4 मिनट की त्रुटि लग्न को 1 अंश खिसकाती है -- नवांश बदलने के लिए पर्याप्त।', ta: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.', te: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.', bn: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.', kn: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.', gu: 'A 4-minute error shifts Lagna by 1 degree -- enough to change the Navamsha division entirely.' } },
  { myth: { en: '"Twins have the same chart"', hi: '"जुड़वों की कुण्डली समान होती है"', sa: '"जुड़वों की कुण्डली समान होती है"', mai: '"जुड़वों की कुण्डली समान होती है"', mr: '"जुड़वों की कुण्डली समान होती है"', ta: '"Twins have the same chart"', te: '"Twins have the same chart"', bn: '"Twins have the same chart"', kn: '"Twins have the same chart"', gu: '"Twins have the same chart"' }, truth: { en: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.', hi: 'कुछ मिनटों का अन्तर भी लग्न अंश, नवांश, दशा सन्तुलन बदल सकता है।', sa: 'कुछ मिनटों का अन्तर भी लग्न अंश, नवांश, दशा सन्तुलन बदल सकता है।', mai: 'कुछ मिनटों का अन्तर भी लग्न अंश, नवांश, दशा सन्तुलन बदल सकता है।', mr: 'कुछ मिनटों का अन्तर भी लग्न अंश, नवांश, दशा सन्तुलन बदल सकता है।', ta: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.', te: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.', bn: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.', kn: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.', gu: 'Even a few minutes difference can change the Lagna degree, Navamsha, dasha balance, and sub-lord.' } },
];

const INLINE_MUHURTALAGNAS = [
  { sign: { en: 'Taurus (Vrishabha)', hi: 'वृषभ', sa: 'वृषभ', mai: 'वृषभ', mr: 'वृषभ', ta: 'ரிஷபம் (வ்ருஷபம்)', te: 'వృషభం (వృషభం)', bn: 'বৃষ (বৃষভ)', kn: 'ವೃಷಭ (ವೃಷಭ)', gu: 'વૃષભ (વૃષભ)' }, use: { en: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled', hi: 'लक्ष्मी पूजा, धन अनुष्ठान, वित्तीय उद्यम -- शुक्र-शासित', sa: 'लक्ष्मी पूजा, धन अनुष्ठान, वित्तीय उद्यम -- शुक्र-शासित', mai: 'लक्ष्मी पूजा, धन अनुष्ठान, वित्तीय उद्यम -- शुक्र-शासित', mr: 'लक्ष्मी पूजा, धन अनुष्ठान, वित्तीय उद्यम -- शुक्र-शासित', ta: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled', te: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled', bn: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled', kn: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled', gu: 'Lakshmi Puja, wealth rituals, financial ventures -- Venus-ruled' } },
  { sign: { en: 'Leo (Simha)', hi: 'सिंह', sa: 'सिंह', mai: 'सिंह', mr: 'सिंह', ta: 'சிம்மம் (சிம்மம்)', te: 'సింహం (సింహం)', bn: 'সিংহ (সিংহ)', kn: 'ಸಿಂಹ (ಸಿಂಹ)', gu: 'સિંહ (સિંહ)' }, use: { en: 'Government work, authority rituals, Surya puja -- Sun-ruled', hi: 'सरकारी कार्य, अधिकार अनुष्ठान, सूर्य पूजा -- सूर्य-शासित', sa: 'सरकारी कार्य, अधिकार अनुष्ठान, सूर्य पूजा -- सूर्य-शासित', mai: 'सरकारी कार्य, अधिकार अनुष्ठान, सूर्य पूजा -- सूर्य-शासित', mr: 'सरकारी कार्य, अधिकार अनुष्ठान, सूर्य पूजा -- सूर्य-शासित', ta: 'Government work, authority rituals, Surya puja -- Sun-ruled', te: 'Government work, authority rituals, Surya puja -- Sun-ruled', bn: 'Government work, authority rituals, Surya puja -- Sun-ruled', kn: 'Government work, authority rituals, Surya puja -- Sun-ruled', gu: 'Government work, authority rituals, Surya puja -- Sun-ruled' } },
  { sign: { en: 'Sagittarius (Dhanu)', hi: 'धनु', sa: 'धनु', mai: 'धनु', mr: 'धनु', ta: 'தனுசு (தனுசு)', te: 'ధనుస్సు (ధనుస్సు)', bn: 'ধনু (ধনু)', kn: 'ಧನು (ಧನು)', gu: 'ધનુ (ધનુ)' }, use: { en: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled', hi: 'सत्यनारायण कथा, शैक्षिक आयोजन, गुरु पूजा -- गुरु-शासित', sa: 'सत्यनारायण कथा, शैक्षिक आयोजन, गुरु पूजा -- गुरु-शासित', mai: 'सत्यनारायण कथा, शैक्षिक आयोजन, गुरु पूजा -- गुरु-शासित', mr: 'सत्यनारायण कथा, शैक्षिक आयोजन, गुरु पूजा -- गुरु-शासित', ta: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled', te: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled', bn: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled', kn: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled', gu: 'Satyanarayan Katha, educational events, guru puja -- Jupiter-ruled' } },
  { sign: { en: 'Cancer (Karka)', hi: 'कर्क', sa: 'कर्क', mai: 'कर्क', mr: 'कर्क', ta: 'கடகம் (கர்க)', te: 'కర్కాటకం (కర్కాటకం)', bn: 'কর্কট (কর্কট)', kn: 'ಕರ್ಕಾಟಕ (ಕರ್ಕಾಟಕ)', gu: 'કર્ક (કર્ક)' }, use: { en: 'Griha Pravesh, domestic rituals -- Moon-ruled', hi: 'गृह प्रवेश, घरेलू अनुष्ठान -- चन्द्र-शासित', sa: 'गृह प्रवेश, घरेलू अनुष्ठान -- चन्द्र-शासित', mai: 'गृह प्रवेश, घरेलू अनुष्ठान -- चन्द्र-शासित', mr: 'गृह प्रवेश, घरेलू अनुष्ठान -- चन्द्र-शासित', ta: 'Griha Pravesh, domestic rituals -- Moon-ruled', te: 'Griha Pravesh, domestic rituals -- Moon-ruled', bn: 'Griha Pravesh, domestic rituals -- Moon-ruled', kn: 'Griha Pravesh, domestic rituals -- Moon-ruled', gu: 'Griha Pravesh, domestic rituals -- Moon-ruled' } },
  { sign: { en: 'Virgo (Kanya)', hi: 'कन्या', sa: 'कन्या', mai: 'कन्या', mr: 'कन्या', ta: 'கன்னி (கன்யா)', te: 'కన్య (కన్య)', bn: 'কন্যা (কন্যা)', kn: 'ಕನ್ಯಾ (ಕನ್ಯಾ)', gu: 'કન્યા (કન્યા)' }, use: { en: 'Medical procedures, health rituals -- Mercury-ruled', hi: 'चिकित्सा प्रक्रियाएँ, स्वास्थ्य अनुष्ठान -- बुध-शासित', sa: 'चिकित्सा प्रक्रियाएँ, स्वास्थ्य अनुष्ठान -- बुध-शासित', mai: 'चिकित्सा प्रक्रियाएँ, स्वास्थ्य अनुष्ठान -- बुध-शासित', mr: 'चिकित्सा प्रक्रियाएँ, स्वास्थ्य अनुष्ठान -- बुध-शासित', ta: 'Medical procedures, health rituals -- Mercury-ruled', te: 'Medical procedures, health rituals -- Mercury-ruled', bn: 'Medical procedures, health rituals -- Mercury-ruled', kn: 'Medical procedures, health rituals -- Mercury-ruled', gu: 'Medical procedures, health rituals -- Mercury-ruled' } },
  { sign: { en: 'Libra (Tula)', hi: 'तुला', sa: 'तुला', mai: 'तुला', mr: 'तुला', ta: 'துலாம் (துலா)', te: 'తులా (తులా)', bn: 'তুলা (তুলা)', kn: 'ತುಲಾ (ತುಲಾ)', gu: 'તુલા (તુલા)' }, use: { en: 'Marriage ceremonies, partnerships -- Venus-ruled', hi: 'विवाह संस्कार, साझेदारी -- शुक्र-शासित', sa: 'विवाह संस्कार, साझेदारी -- शुक्र-शासित', mai: 'विवाह संस्कार, साझेदारी -- शुक्र-शासित', mr: 'विवाह संस्कार, साझेदारी -- शुक्र-शासित', ta: 'Marriage ceremonies, partnerships -- Venus-ruled', te: 'Marriage ceremonies, partnerships -- Venus-ruled', bn: 'Marriage ceremonies, partnerships -- Venus-ruled', kn: 'Marriage ceremonies, partnerships -- Venus-ruled', gu: 'Marriage ceremonies, partnerships -- Venus-ruled' } },
];

export default function LagnaPage() {
  const locale = useLocale();
  const headingFont = getHeadingFont(locale);
  const bodyFont = getBodyFont(locale);
  const t = (key: string) => lt(t_[key], locale);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tObj = (obj: any) => (obj as Record<string, string>)[locale] || obj?.en || '';

  return (
    <div className="max-w-4xl mx-auto space-y-10">
      {/* Title */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
        <h1 className="text-4xl sm:text-5xl font-bold text-gold-gradient mb-4" style={headingFont}>{t('title')}</h1>
        <p className="text-text-secondary text-lg max-w-2xl mx-auto" style={bodyFont}>{t('subtitle')}</p>
        <SanskritTermCard term="लग्नम्" transliteration="Lagnam" meaning={t('sanskritMeaning')} />
      </motion.div>

      {/* What is Lagna */}
      <LessonSection title={t('whatTitle')}>
        <p className="text-text-secondary leading-relaxed" style={bodyFont}>{t('whatContent')}</p>
      </LessonSection>

      {/* Why Lagna is Supreme */}
      <LessonSection title={t('whyTitle')}>
        <p className="text-text-secondary leading-relaxed" style={bodyFont}>{t('whyContent')}</p>
      </LessonSection>

      {/* How Lagna is Calculated */}
      <LessonSection title={t('calcTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('calcContent')}</p>
        <div className="space-y-2 mb-4">
          {INLINE_CALCSTEPS.map((step, i) => (
            <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.25 + i * 0.05 }}
              className="p-3 bg-bg-primary/30 rounded-lg border border-gold-primary/10 text-text-secondary text-sm" style={bodyFont}>
              {tObj(step)}
            </motion.div>
          ))}
        </div>
        <div className="p-3 bg-gold-primary/5 rounded-lg border border-gold-primary/20">
          <p className="text-gold-primary/80 text-xs" style={bodyFont}>{t('calcNote')}</p>
        </div>
      </LessonSection>

      {/* How Fast Does Lagna Change */}
      <LessonSection title={t('changeTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('changeContent')}</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="p-4 bg-orange-500/5 rounded-lg border border-orange-500/10">
            <p className="text-orange-400 text-sm font-semibold mb-1">{t('longAscLabel')}</p>
            <p className="text-text-secondary text-sm" style={bodyFont}>{t('longAsc')}</p>
          </div>
          <div className="p-4 bg-blue-500/5 rounded-lg border border-blue-500/10">
            <p className="text-blue-400 text-sm font-semibold mb-1">{t('shortAscLabel')}</p>
            <p className="text-text-secondary text-sm" style={bodyFont}>{t('shortAsc')}</p>
          </div>
        </div>
      </LessonSection>

      {/* 12 Lagnas */}
      <LessonSection title={t('twelveLagnaTitle')}>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {INLINE_LAGNAS.map((lagna, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 + i * 0.03 }}
              className="p-4 bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-xl">
              <div className="flex items-center justify-between mb-2">
                <span className="text-gold-light font-semibold" style={headingFont}>{tObj(lagna.sign)}</span>
                <span className="text-text-tertiary text-xs">{t('lordLabel')}: {tObj(lagna.lord)}</span>
              </div>
              <p className="text-text-secondary text-sm" style={bodyFont}>{tObj(lagna.traits)}</p>
            </motion.div>
          ))}
        </div>
      </LessonSection>

      {/* Lagna Lord */}
      <LessonSection title={t('lagnaLordTitle')}>
        <p className="text-text-secondary leading-relaxed" style={bodyFont}>{t('lagnaLordContent')}</p>
      </LessonSection>

      {/* Special Lagnas */}
      <LessonSection title={t('specialTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('specialContent')}</p>
        <div className="space-y-3">
          {INLINE_SPECIALLAGNAS.map((sl, i) => (
            <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.45 + i * 0.05 }}
              className="p-4 bg-bg-primary/30 rounded-lg border border-gold-primary/10">
              <h4 className="text-gold-primary font-semibold text-sm mb-1" style={headingFont}>{tObj(sl.name)}</h4>
              <p className="text-text-secondary text-sm" style={bodyFont}>{tObj(sl.desc)}</p>
            </motion.div>
          ))}
        </div>
      </LessonSection>

      {/* Birth Time Rectification */}
      <LessonSection title={t('rectTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('rectContent')}</p>
        <div className="space-y-2">
          {INLINE_RECTMETHODS.map((method, i) => (
            <div key={i} className="flex items-start gap-2 text-sm">
              <span className="text-gold-primary mt-0.5">&#x2022;</span>
              <span className="text-text-secondary" style={bodyFont}>{tObj(method)}</span>
            </div>
          ))}
        </div>
      </LessonSection>

      {/* Lagna in Muhurta / Puja Timing */}
      <LessonSection title={t('muhurtaTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('muhurtaContent')}</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
          {INLINE_MUHURTALAGNAS.map((ml, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 + i * 0.04 }}
              className="p-4 bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-xl">
              <span className="text-gold-light font-semibold text-sm" style={headingFont}>{tObj(ml.sign)}</span>
              <p className="text-text-secondary text-xs mt-1" style={bodyFont}>{tObj(ml.use)}</p>
            </motion.div>
          ))}
        </div>
        <div className="p-3 bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] rounded-lg border border-red-500/10 mb-3">
          <p className="text-red-400/80 text-sm" style={bodyFont}>{t('muhurtaAvoid')}</p>
        </div>
        <div className="p-3 bg-gold-primary/5 rounded-lg border border-gold-primary/20">
          <p className="text-gold-primary/80 text-sm" style={bodyFont}>
            {t('muhurtaOurTool')}{' '}
            <Link href="/panchang" className="text-gold-light underline hover:text-gold-primary">{t('viewLagnaWindows')}</Link>
          </p>
        </div>
      </LessonSection>

      {/* Lagna vs Moon vs Sun */}
      <LessonSection title={t('lagnaVsMoonTitle')}>
        <p className="text-text-secondary leading-relaxed mb-4" style={bodyFont}>{t('lagnaVsMoonContent')}</p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-gold-primary border-b border-gold-primary/10">
                <th className="text-left py-2 px-3">{t('tableReference')}</th>
                <th className="text-left py-2 px-3">{t('tableGoverns')}</th>
                <th className="text-right py-2 px-3">{t('tableChanges')}</th>
              </tr>
            </thead>
            <tbody>
              {INLINE_COMPARISON.map((row, i) => (
                <tr key={i} className="border-b border-gold-primary/5 text-text-secondary">
                  <td className="py-2 px-3 text-gold-light font-semibold" style={headingFont}>{tObj(row.aspect)}</td>
                  <td className="py-2 px-3" style={bodyFont}>{tObj(row.governs)}</td>
                  <td className="py-2 px-3 text-right text-text-tertiary">{tObj(row.changes)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </LessonSection>

      {/* Misconceptions */}
      <LessonSection title={t('misconceptionsTitle')}>
        <div className="space-y-4">
          {INLINE_MISCONCEPTIONS.map((mc, i) => (
            <div key={i} className="p-4 bg-bg-primary/30 rounded-lg border border-gold-primary/10">
              <p className="text-red-400 text-sm font-semibold mb-1" style={bodyFont}>{tObj(mc.myth)}</p>
              <p className="text-text-secondary text-sm" style={bodyFont}>{tObj(mc.truth)}</p>
            </div>
          ))}
        </div>
      </LessonSection>

      {/* Classical References */}
      <LessonSection title={t('classicalTitle')}>
        <p className="text-text-secondary leading-relaxed" style={bodyFont}>{t('classicalContent')}</p>
      </LessonSection>

      {/* Cross-references */}
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.65 }}
        className="bg-gradient-to-br from-[#2d1b69]/40 via-[#1a1040]/50 to-[#0a0e27] border border-gold-primary/12 rounded-xl p-6 text-center space-y-3">
        <h3 className="text-gold-gradient text-lg font-bold" style={headingFont}>{t('continueLearning')}</h3>
        <div className="flex flex-wrap gap-3 justify-center">
          {[
            { href: '/learn/bhavas', label: t('linkBhavas') },
            { href: '/learn/grahas', label: t('linkGrahas') },
            { href: '/learn/kundali', label: t('linkKundali') },
            { href: '/learn/rashis', label: t('linkRashis') },
            { href: '/learn/vargas', label: t('linkVargas') },
          ].map(link => (
            <Link key={link.href} href={link.href}
              className="px-4 py-2 rounded-lg border border-gold-primary/20 text-gold-primary text-sm hover:bg-gold-primary/10 transition-colors">
              {link.label}
            </Link>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
