/**
 * Disclaimer System — Standard + Contextual (EN + HI)
 */

import type { QueryCategory, Verdict } from '../types';

const STANDARD: Record<string, string> = {
  en: `This reading is generated by our AI Pandit, grounded in classical Vedic texts including Brihat Parashara Hora Shastra, Phaladeepika, and Saravali. All planetary positions are computed using the Swiss Ephemeris astronomical engine.

This is for guidance and self-reflection. Jyotish describes tendencies and karmic patterns — not fixed destiny. Important life decisions should consider multiple sources of wisdom.

Tradition: Parashari (BPHS) | Engine: Swiss Ephemeris`,

  hi: `यह विश्लेषण हमारे AI पंडित द्वारा तैयार किया गया है, जो बृहत् पाराशर होरा शास्त्र, फलदीपिका और सारावली जैसे शास्त्रीय ग्रंथों पर आधारित है। सभी ग्रह स्थितियों की गणना स्विस एफेमेरिस खगोलीय इंजन द्वारा की गई है।

यह मार्गदर्शन और आत्मचिंतन के लिए है। ज्योतिष कर्म प्रवृत्तियों का वर्णन करता है — निश्चित भाग्य का नहीं। महत्वपूर्ण जीवन निर्णयों में अनेक स्रोतों से विचार करें।

परंपरा: पाराशरी (बृहत् पाराशर होरा शास्त्र) | गणना: स्विस एफेमेरिस`,
};

const CONTEXTUAL: Record<string, Record<string, string>> = {
  health: {
    en: 'Health indications in Jyotish reflect karmic tendencies. They are not medical diagnoses. Please consult a healthcare professional for medical concerns.',
    hi: 'ज्योतिष में स्वास्थ्य संकेत कर्म प्रवृत्तियों को दर्शाते हैं। ये चिकित्सकीय निदान नहीं हैं। चिकित्सा संबंधी चिंताओं के लिए कृपया योग्य चिकित्सक से परामर्श करें।',
  },
  wealth: {
    en: 'Astrological timing can inform but should not replace professional financial advice.',
    hi: 'ज्योतिषीय समय मार्गदर्शन दे सकता है, किन्तु यह पेशेवर वित्तीय सलाह का विकल्प नहीं है।',
  },
  relationship: {
    en: 'Compatibility readings highlight karmic patterns. Every relationship is shaped by both karma and conscious effort.',
    hi: 'संगतता विश्लेषण कर्म प्रवृत्तियों को दर्शाता है। प्रत्येक संबंध कर्म और सचेत प्रयास दोनों से आकार लेता है।',
  },
  challenging: {
    en: 'Challenging planetary periods are opportunities for growth. Classical texts prescribe remedies precisely because difficult periods are workable.',
    hi: 'कठिन ग्रह काल विकास के अवसर हैं। शास्त्रों में उपाय इसीलिए बताए गए हैं क्योंकि कठिन काल निवारण योग्य होते हैं।',
  },
};

export function getDisclaimer(
  category: QueryCategory,
  verdict: Verdict,
  locale: string,
): string {
  const loc = locale === 'hi' ? 'hi' : 'en';
  let disclaimer = STANDARD[loc];

  if (CONTEXTUAL[category]?.[loc]) {
    disclaimer += '\n\n' + CONTEXTUAL[category][loc];
  }

  if ((verdict === 'CAUTION' || verdict === 'CHALLENGING') && CONTEXTUAL.challenging?.[loc]) {
    disclaimer += '\n\n' + CONTEXTUAL.challenging[loc];
  }

  return disclaimer;
}
