-- 055 — Pandit pricing + unlinked-client cap enforcement
--
-- Adds two tiers to the existing `subscriptions.tier` constraint
-- (`pandit_pro`, `pandit_unlimited`) so the same payments table can carry
-- Pandit subscriptions. The webhook handler at
-- /api/webhooks/stripe/route.ts already trusts the server-bound `tier`
-- from `pending_checkouts` (which has no constraint on its `tier`
-- column), so no handler changes are needed once this constraint is
-- relaxed.
--
-- Cap enforcement: free-tier Pandits may have at most 5 UNLINKED
-- clients on their roster at any time. "Unlinked" here means
-- link_state IN ('unlinked','invited') — clients who haven't yet
-- joined the platform. Linked, paused, declined, and archived clients
-- DO NOT count against the cap. This is the user-facing UX nudge: by
-- inviting clients onto the platform, Pandits both unlock more roster
-- slots AND grow the platform's user base.
--
-- The trigger is BEFORE INSERT OR UPDATE OF link_state — covers both:
--   1. Direct INSERT of a new client (the common case)
--   2. UPDATE that flips a client back into the unlinked/invited bucket
--      (e.g., a paused/archived client being restored)
--
-- Paid tiers (`pandit_pro`, `pandit_unlimited`) bypass the cap. The
-- distinction between Pro and Unlimited is currently UX-only (positioning
-- + price); both tiers grant unlimited unlinked clients. The Unlimited
-- tier exists as a placeholder for future per-client billing / advanced
-- features. Spec §10.
--
-- Pandit CRM P10.

-- 1. Relax the subscriptions.tier constraint to admit Pandit tiers.
--    The existing constraint is named `subscriptions_tier_check` (auto-
--    generated by Postgres for a column-level CHECK).
ALTER TABLE public.subscriptions
  DROP CONSTRAINT IF EXISTS subscriptions_tier_check;

ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_tier_check
  CHECK (tier IN ('free', 'pro', 'jyotishi', 'pandit_pro', 'pandit_unlimited'));

COMMENT ON CONSTRAINT subscriptions_tier_check ON public.subscriptions IS
  'Subscription tiers. Seeker: free, pro, jyotishi. Pandit: pandit_pro, pandit_unlimited. Mutually exclusive — a user is on exactly one tier at a time. Pandit CRM P10.';

-- 2. Cap enforcement trigger.
CREATE OR REPLACE FUNCTION public.enforce_pandit_unlinked_client_cap()
RETURNS TRIGGER AS $$
DECLARE
  v_pandit_tier TEXT;
  v_unlinked_count INT;
  -- Free tier allows up to 5 unlinked clients. Keep in sync with
  -- src/lib/pandit/subscription.ts FREE_TIER_UNLINKED_CAP.
  k_free_cap CONSTANT INT := 5;
BEGIN
  -- Only enforce when the new row sits in the unlinked/invited bucket.
  -- Linked, paused, declined, archived clients do not count.
  IF NEW.link_state NOT IN ('unlinked','invited') THEN
    RETURN NEW;
  END IF;

  -- On UPDATE, skip if the row was ALREADY in the counted bucket — the
  -- cap was checked at INSERT (or at the previous transition) and the
  -- row's continued presence isn't a new charge.
  IF TG_OP = 'UPDATE' AND OLD.link_state IN ('unlinked','invited') THEN
    RETURN NEW;
  END IF;

  -- Resolve the Pandit's current tier. NULL row = free tier.
  SELECT s.tier INTO v_pandit_tier
    FROM public.subscriptions s
    WHERE s.user_id = NEW.pandit_user_id
      AND s.status IN ('active','trialing')
    ORDER BY s.updated_at DESC NULLS LAST
    LIMIT 1;

  IF v_pandit_tier IN ('pandit_pro','pandit_unlimited') THEN
    -- Paid Pandit tier — no cap.
    RETURN NEW;
  END IF;

  -- Free tier (or any non-Pandit tier the user is somehow on) — count
  -- their current unlinked roster. Exclude the row we're inserting/
  -- updating from the count when it's an UPDATE; on INSERT the row
  -- doesn't exist yet so the count is naturally pre-insert.
  SELECT COUNT(*) INTO v_unlinked_count
    FROM public.pandit_clients pc
    WHERE pc.pandit_user_id = NEW.pandit_user_id
      AND pc.link_state IN ('unlinked','invited')
      AND (TG_OP = 'INSERT' OR pc.id <> NEW.id);

  IF v_unlinked_count >= k_free_cap THEN
    -- Surface a stable, parseable error so the API layer can map this
    -- to a 402 Payment Required + paywall modal trigger. The ERRCODE
    -- 'P0001' is the standard Postgres "raise_exception" code; the
    -- MESSAGE text is the stable contract — the route handler matches
    -- on the exact prefix `pandit_cap_exceeded:`.
    RAISE EXCEPTION 'pandit_cap_exceeded: free tier allows up to % unlinked clients', k_free_cap
      USING ERRCODE = 'P0001',
            HINT = 'Upgrade to Pandit Pro for unlimited clients, or invite an existing unlinked client onto the platform (linked clients don''t count against your cap).';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

COMMENT ON FUNCTION public.enforce_pandit_unlinked_client_cap() IS
  'Pandit CRM P10. Caps free-tier Pandits at 5 unlinked-or-invited clients. Linked/paused/declined clients do not count. Paid tiers (pandit_pro, pandit_unlimited) bypass the cap.';

DROP TRIGGER IF EXISTS pandit_clients_cap_check ON public.pandit_clients;

CREATE TRIGGER pandit_clients_cap_check
  BEFORE INSERT OR UPDATE OF link_state ON public.pandit_clients
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_pandit_unlinked_client_cap();

-- 3. Supporting index for the cap-count query. The existing
--    pandit_clients_pandit_user_id_idx (from migration 049) only indexes
--    pandit_user_id; adding link_state lets the cap-count run an index-
--    only scan instead of a heap scan on tenant rows.
CREATE INDEX IF NOT EXISTS pandit_clients_cap_lookup_idx
  ON public.pandit_clients (pandit_user_id, link_state);
