/**
 * Bilingual text template pools for daily horoscope generation.
 * Each area has 3 quality tiers (good / mixed / challenging),
 * with 6 templates per tier. Total: 5 areas x 3 tiers x 6 = 90 templates.
 *
 * Templates are deterministically selected using (date + moonSign) as a seed.
 */

import type { LocaleText } from '@/types/panchang';

export type BilingualText = LocaleText;

export type QualityTier = 'good' | 'mixed' | 'challenging';
export type LifeArea = 'career' | 'love' | 'health' | 'finance' | 'spirituality';

// ─────────────────────────────────────────────────────────────
// CAREER
// ─────────────────────────────────────────────────────────────
const CAREER_GOOD: BilingualText[] = [
  { en: 'Professional momentum builds today — take initiative on pending projects.', hi: 'आज कार्यक्षेत्र में गति बनती है — लंबित परियोजनाओं में पहल करें।', sa: 'आज कार्यक्षेत्र में गति बनती है — लंबित परियोजनाओं में पहल करें।', mai: 'आज कार्यक्षेत्र में गति बनती है — लंबित परियोजनाओं में पहल करें।', mr: 'आज कार्यक्षेत्र में गति बनती है — लंबित परियोजनाओं में पहल करें।', ta: 'Professional momentum builds today — take initiative on pending projects.', te: 'Professional momentum builds today — take initiative on pending projects.', bn: 'Professional momentum builds today — take initiative on pending projects.', kn: 'Professional momentum builds today — take initiative on pending projects.', gu: 'Professional momentum builds today — take initiative on pending projects.' },
  { en: 'Authority figures notice your efforts. Present your ideas with confidence.', hi: 'अधिकारी आपके प्रयासों को देख रहे हैं। अपने विचार आत्मविश्वास से रखें।', sa: 'अधिकारी आपके प्रयासों को देख रहे हैं। अपने विचार आत्मविश्वास से रखें।', mai: 'अधिकारी आपके प्रयासों को देख रहे हैं। अपने विचार आत्मविश्वास से रखें।', mr: 'अधिकारी आपके प्रयासों को देख रहे हैं। अपने विचार आत्मविश्वास से रखें।', ta: 'Authority figures notice your efforts. Present your ideas with confidence.', te: 'Authority figures notice your efforts. Present your ideas with confidence.', bn: 'Authority figures notice your efforts. Present your ideas with confidence.', kn: 'Authority figures notice your efforts. Present your ideas with confidence.', gu: 'Authority figures notice your efforts. Present your ideas with confidence.' },
  { en: 'New opportunities align with your skills. Stay open to unexpected proposals.', hi: 'नए अवसर आपकी क्षमताओं से मेल खाते हैं। अप्रत्याशित प्रस्तावों के लिए तैयार रहें।', sa: 'नए अवसर आपकी क्षमताओं से मेल खाते हैं। अप्रत्याशित प्रस्तावों के लिए तैयार रहें।', mai: 'नए अवसर आपकी क्षमताओं से मेल खाते हैं। अप्रत्याशित प्रस्तावों के लिए तैयार रहें।', mr: 'नए अवसर आपकी क्षमताओं से मेल खाते हैं। अप्रत्याशित प्रस्तावों के लिए तैयार रहें।', ta: 'New opportunities align with your skills. Stay open to unexpected proposals.', te: 'New opportunities align with your skills. Stay open to unexpected proposals.', bn: 'New opportunities align with your skills. Stay open to unexpected proposals.', kn: 'New opportunities align with your skills. Stay open to unexpected proposals.', gu: 'New opportunities align with your skills. Stay open to unexpected proposals.' },
  { en: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.', hi: 'सहकार्य फलता-फूलता है। सामूहिक प्रयासों से मान्यता एवं पुरस्कार मिलता है।', sa: 'सहकार्य फलता-फूलता है। सामूहिक प्रयासों से मान्यता एवं पुरस्कार मिलता है।', mai: 'सहकार्य फलता-फूलता है। सामूहिक प्रयासों से मान्यता एवं पुरस्कार मिलता है।', mr: 'सहकार्य फलता-फूलता है। सामूहिक प्रयासों से मान्यता एवं पुरस्कार मिलता है।', ta: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.', te: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.', bn: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.', kn: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.', gu: 'Teamwork flourishes. Collaborative efforts bring recognition and reward.' },
  { en: 'A strategic decision you make today could accelerate your career trajectory.', hi: 'आज लिया गया एक रणनीतिक निर्णय आपकी करियर गति को तेज़ कर सकता है।', sa: 'आज लिया गया एक रणनीतिक निर्णय आपकी करियर गति को तेज़ कर सकता है।', mai: 'आज लिया गया एक रणनीतिक निर्णय आपकी करियर गति को तेज़ कर सकता है।', mr: 'आज लिया गया एक रणनीतिक निर्णय आपकी करियर गति को तेज़ कर सकता है।', ta: 'A strategic decision you make today could accelerate your career trajectory.', te: 'A strategic decision you make today could accelerate your career trajectory.', bn: 'A strategic decision you make today could accelerate your career trajectory.', kn: 'A strategic decision you make today could accelerate your career trajectory.', gu: 'A strategic decision you make today could accelerate your career trajectory.' },
  { en: 'Your expertise is valued. Share knowledge generously and watch doors open.', hi: 'आपकी विशेषज्ञता मूल्यवान है। ज्ञान साझा करें और नए द्वार खुलते देखें।', sa: 'आपकी विशेषज्ञता मूल्यवान है। ज्ञान साझा करें और नए द्वार खुलते देखें।', mai: 'आपकी विशेषज्ञता मूल्यवान है। ज्ञान साझा करें और नए द्वार खुलते देखें।', mr: 'आपकी विशेषज्ञता मूल्यवान है। ज्ञान साझा करें और नए द्वार खुलते देखें।', ta: 'Your expertise is valued. Share knowledge generously and watch doors open.', te: 'Your expertise is valued. Share knowledge generously and watch doors open.', bn: 'Your expertise is valued. Share knowledge generously and watch doors open.', kn: 'Your expertise is valued. Share knowledge generously and watch doors open.', gu: 'Your expertise is valued. Share knowledge generously and watch doors open.' },
];

const CAREER_MIXED: BilingualText[] = [
  { en: 'Steady day — focus on routine tasks and clearing your backlog.', hi: 'स्थिर दिन — नियमित कार्यों और बकाया काम को निपटाने पर ध्यान दें।', sa: 'स्थिर दिन — नियमित कार्यों और बकाया काम को निपटाने पर ध्यान दें।', mai: 'स्थिर दिन — नियमित कार्यों और बकाया काम को निपटाने पर ध्यान दें।', mr: 'स्थिर दिन — नियमित कार्यों और बकाया काम को निपटाने पर ध्यान दें।', ta: 'Steady day — focus on routine tasks and clearing your backlog.', te: 'Steady day — focus on routine tasks and clearing your backlog.', bn: 'Steady day — focus on routine tasks and clearing your backlog.', kn: 'Steady day — focus on routine tasks and clearing your backlog.', gu: 'Steady day — focus on routine tasks and clearing your backlog.' },
  { en: 'Avoid major decisions until clarity arrives. Gather more information first.', hi: 'स्पष्टता आने तक बड़े निर्णयों से बचें। पहले अधिक जानकारी एकत्र करें।', sa: 'स्पष्टता आने तक बड़े निर्णयों से बचें। पहले अधिक जानकारी एकत्र करें।', mai: 'स्पष्टता आने तक बड़े निर्णयों से बचें। पहले अधिक जानकारी एकत्र करें।', mr: 'स्पष्टता आने तक बड़े निर्णयों से बचें। पहले अधिक जानकारी एकत्र करें।', ta: 'Avoid major decisions until clarity arrives. Gather more information first.', te: 'Avoid major decisions until clarity arrives. Gather more information first.', bn: 'Avoid major decisions until clarity arrives. Gather more information first.', kn: 'Avoid major decisions until clarity arrives. Gather more information first.', gu: 'Avoid major decisions until clarity arrives. Gather more information first.' },
  { en: 'Colleagues may need extra patience today. Lead with empathy.', hi: 'आज सहकर्मियों को अतिरिक्त धैर्य की आवश्यकता हो सकती है। सहानुभूति से नेतृत्व करें।', sa: 'आज सहकर्मियों को अतिरिक्त धैर्य की आवश्यकता हो सकती है। सहानुभूति से नेतृत्व करें।', mai: 'आज सहकर्मियों को अतिरिक्त धैर्य की आवश्यकता हो सकती है। सहानुभूति से नेतृत्व करें।', mr: 'आज सहकर्मियों को अतिरिक्त धैर्य की आवश्यकता हो सकती है। सहानुभूति से नेतृत्व करें।', ta: 'Colleagues may need extra patience today. Lead with empathy.', te: 'Colleagues may need extra patience today. Lead with empathy.', bn: 'Colleagues may need extra patience today. Lead with empathy.', kn: 'Colleagues may need extra patience today. Lead with empathy.', gu: 'Colleagues may need extra patience today. Lead with empathy.' },
  { en: 'Progress is slow but steady. Trust the process and stay consistent.', hi: 'प्रगति धीमी लेकिन स्थिर है। प्रक्रिया पर विश्वास रखें और निरंतर रहें।', sa: 'प्रगति धीमी लेकिन स्थिर है। प्रक्रिया पर विश्वास रखें और निरंतर रहें।', mai: 'प्रगति धीमी लेकिन स्थिर है। प्रक्रिया पर विश्वास रखें और निरंतर रहें।', mr: 'प्रगति धीमी लेकिन स्थिर है। प्रक्रिया पर विश्वास रखें और निरंतर रहें।', ta: 'Progress is slow but steady. Trust the process and stay consistent.', te: 'Progress is slow but steady. Trust the process and stay consistent.', bn: 'Progress is slow but steady. Trust the process and stay consistent.', kn: 'Progress is slow but steady. Trust the process and stay consistent.', gu: 'Progress is slow but steady. Trust the process and stay consistent.' },
  { en: 'Good day for planning rather than execution. Strategize for the week ahead.', hi: 'कार्यान्वयन की बजाय योजना बनाने का अच्छा दिन। आगामी सप्ताह की रणनीति बनाएँ।', sa: 'कार्यान्वयन की बजाय योजना बनाने का अच्छा दिन। आगामी सप्ताह की रणनीति बनाएँ।', mai: 'कार्यान्वयन की बजाय योजना बनाने का अच्छा दिन। आगामी सप्ताह की रणनीति बनाएँ।', mr: 'कार्यान्वयन की बजाय योजना बनाने का अच्छा दिन। आगामी सप्ताह की रणनीति बनाएँ।', ta: 'Good day for planning rather than execution. Strategize for the week ahead.', te: 'Good day for planning rather than execution. Strategize for the week ahead.', bn: 'Good day for planning rather than execution. Strategize for the week ahead.', kn: 'Good day for planning rather than execution. Strategize for the week ahead.', gu: 'Good day for planning rather than execution. Strategize for the week ahead.' },
  { en: 'Minor workplace friction is temporary. Stay professional and it will pass.', hi: 'कार्यस्थल पर मामूली घर्षण अस्थायी है। पेशेवर बने रहें, यह बीत जाएगा।', sa: 'कार्यस्थल पर मामूली घर्षण अस्थायी है। पेशेवर बने रहें, यह बीत जाएगा।', mai: 'कार्यस्थल पर मामूली घर्षण अस्थायी है। पेशेवर बने रहें, यह बीत जाएगा।', mr: 'कार्यस्थल पर मामूली घर्षण अस्थायी है। पेशेवर बने रहें, यह बीत जाएगा।', ta: 'Minor workplace friction is temporary. Stay professional and it will pass.', te: 'Minor workplace friction is temporary. Stay professional and it will pass.', bn: 'Minor workplace friction is temporary. Stay professional and it will pass.', kn: 'Minor workplace friction is temporary. Stay professional and it will pass.', gu: 'Minor workplace friction is temporary. Stay professional and it will pass.' },
];

const CAREER_CHALLENGING: BilingualText[] = [
  { en: 'Workplace tension requires diplomatic handling. Choose words carefully.', hi: 'कार्यस्थल का तनाव कूटनीतिक संभालने की माँग करता है। शब्दों का चयन सावधानी से करें।', sa: 'कार्यस्थल का तनाव कूटनीतिक संभालने की माँग करता है। शब्दों का चयन सावधानी से करें।', mai: 'कार्यस्थल का तनाव कूटनीतिक संभालने की माँग करता है। शब्दों का चयन सावधानी से करें।', mr: 'कार्यस्थल का तनाव कूटनीतिक संभालने की माँग करता है। शब्दों का चयन सावधानी से करें।', ta: 'Workplace tension requires diplomatic handling. Choose words carefully.', te: 'Workplace tension requires diplomatic handling. Choose words carefully.', bn: 'Workplace tension requires diplomatic handling. Choose words carefully.', kn: 'Workplace tension requires diplomatic handling. Choose words carefully.', gu: 'Workplace tension requires diplomatic handling. Choose words carefully.' },
  { en: 'Delay important meetings if possible. The energy favors reflection over action.', hi: 'यदि संभव हो तो महत्वपूर्ण बैठकें टालें। ऊर्जा कार्रवाई से अधिक चिंतन का साथ देती है।', sa: 'यदि संभव हो तो महत्वपूर्ण बैठकें टालें। ऊर्जा कार्रवाई से अधिक चिंतन का साथ देती है।', mai: 'यदि संभव हो तो महत्वपूर्ण बैठकें टालें। ऊर्जा कार्रवाई से अधिक चिंतन का साथ देती है।', mr: 'यदि संभव हो तो महत्वपूर्ण बैठकें टालें। ऊर्जा कार्रवाई से अधिक चिंतन का साथ देती है।', ta: 'Delay important meetings if possible. The energy favors reflection over action.', te: 'Delay important meetings if possible. The energy favors reflection over action.', bn: 'Delay important meetings if possible. The energy favors reflection over action.', kn: 'Delay important meetings if possible. The energy favors reflection over action.', gu: 'Delay important meetings if possible. The energy favors reflection over action.' },
  { en: 'Review before committing to new projects. Hidden details may surface later.', hi: 'नई परियोजनाओं में शामिल होने से पहले समीक्षा करें। छिपे विवरण बाद में सामने आ सकते हैं।', sa: 'नई परियोजनाओं में शामिल होने से पहले समीक्षा करें। छिपे विवरण बाद में सामने आ सकते हैं।', mai: 'नई परियोजनाओं में शामिल होने से पहले समीक्षा करें। छिपे विवरण बाद में सामने आ सकते हैं।', mr: 'नई परियोजनाओं में शामिल होने से पहले समीक्षा करें। छिपे विवरण बाद में सामने आ सकते हैं।', ta: 'Review before committing to new projects. Hidden details may surface later.', te: 'Review before committing to new projects. Hidden details may surface later.', bn: 'Review before committing to new projects. Hidden details may surface later.', kn: 'Review before committing to new projects. Hidden details may surface later.', gu: 'Review before committing to new projects. Hidden details may surface later.' },
  { en: 'Authority conflicts may arise. Maintain composure and document everything.', hi: 'अधिकार संघर्ष हो सकते हैं। संयम बनाए रखें और सब कुछ दस्तावेज़ करें।', sa: 'अधिकार संघर्ष हो सकते हैं। संयम बनाए रखें और सब कुछ दस्तावेज़ करें।', mai: 'अधिकार संघर्ष हो सकते हैं। संयम बनाए रखें और सब कुछ दस्तावेज़ करें।', mr: 'अधिकार संघर्ष हो सकते हैं। संयम बनाए रखें और सब कुछ दस्तावेज़ करें।', ta: 'Authority conflicts may arise. Maintain composure and document everything.', te: 'Authority conflicts may arise. Maintain composure and document everything.', bn: 'Authority conflicts may arise. Maintain composure and document everything.', kn: 'Authority conflicts may arise. Maintain composure and document everything.', gu: 'Authority conflicts may arise. Maintain composure and document everything.' },
  { en: 'Not the best day for negotiations. Postpone salary or contract discussions.', hi: 'बातचीत के लिए सर्वोत्तम दिन नहीं। वेतन या अनुबंध चर्चाएँ स्थगित करें।', sa: 'बातचीत के लिए सर्वोत्तम दिन नहीं। वेतन या अनुबंध चर्चाएँ स्थगित करें।', mai: 'बातचीत के लिए सर्वोत्तम दिन नहीं। वेतन या अनुबंध चर्चाएँ स्थगित करें।', mr: 'बातचीत के लिए सर्वोत्तम दिन नहीं। वेतन या अनुबंध चर्चाएँ स्थगित करें।', ta: 'Not the best day for negotiations. Postpone salary or contract discussions.', te: 'Not the best day for negotiations. Postpone salary or contract discussions.', bn: 'Not the best day for negotiations. Postpone salary or contract discussions.', kn: 'Not the best day for negotiations. Postpone salary or contract discussions.', gu: 'Not the best day for negotiations. Postpone salary or contract discussions.' },
  { en: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.', hi: 'ऊर्जा बिखरी महसूस हो सकती है। कठोर प्राथमिकता दें और एक समय में एक कार्य करें।', sa: 'ऊर्जा बिखरी महसूस हो सकती है। कठोर प्राथमिकता दें और एक समय में एक कार्य करें।', mai: 'ऊर्जा बिखरी महसूस हो सकती है। कठोर प्राथमिकता दें और एक समय में एक कार्य करें।', mr: 'ऊर्जा बिखरी महसूस हो सकती है। कठोर प्राथमिकता दें और एक समय में एक कार्य करें।', ta: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.', te: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.', bn: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.', kn: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.', gu: 'Energy may feel scattered. Prioritize ruthlessly and tackle one task at a time.' },
];

// ─────────────────────────────────────────────────────────────
// LOVE
// ─────────────────────────────────────────────────────────────
const LOVE_GOOD: BilingualText[] = [
  { en: 'Emotional bonds deepen today. Express your feelings openly and honestly.', hi: 'आज भावनात्मक बंधन गहरे होते हैं। अपनी भावनाएँ खुलकर और ईमानदारी से व्यक्त करें।', sa: 'आज भावनात्मक बंधन गहरे होते हैं। अपनी भावनाएँ खुलकर और ईमानदारी से व्यक्त करें।', mai: 'आज भावनात्मक बंधन गहरे होते हैं। अपनी भावनाएँ खुलकर और ईमानदारी से व्यक्त करें।', mr: 'आज भावनात्मक बंधन गहरे होते हैं। अपनी भावनाएँ खुलकर और ईमानदारी से व्यक्त करें।', ta: 'Emotional bonds deepen today. Express your feelings openly and honestly.', te: 'Emotional bonds deepen today. Express your feelings openly and honestly.', bn: 'Emotional bonds deepen today. Express your feelings openly and honestly.', kn: 'Emotional bonds deepen today. Express your feelings openly and honestly.', gu: 'Emotional bonds deepen today. Express your feelings openly and honestly.' },
  { en: 'Harmonious energy surrounds relationships. Plan something special with loved ones.', hi: 'रिश्तों के चारों ओर सामंजस्यपूर्ण ऊर्जा है। प्रियजनों के साथ कुछ विशेष योजना बनाएँ।', sa: 'रिश्तों के चारों ओर सामंजस्यपूर्ण ऊर्जा है। प्रियजनों के साथ कुछ विशेष योजना बनाएँ।', mai: 'रिश्तों के चारों ओर सामंजस्यपूर्ण ऊर्जा है। प्रियजनों के साथ कुछ विशेष योजना बनाएँ।', mr: 'रिश्तों के चारों ओर सामंजस्यपूर्ण ऊर्जा है। प्रियजनों के साथ कुछ विशेष योजना बनाएँ।', ta: 'Harmonious energy surrounds relationships. Plan something special with loved ones.', te: 'Harmonious energy surrounds relationships. Plan something special with loved ones.', bn: 'Harmonious energy surrounds relationships. Plan something special with loved ones.', kn: 'Harmonious energy surrounds relationships. Plan something special with loved ones.', gu: 'Harmonious energy surrounds relationships. Plan something special with loved ones.' },
  { en: 'Singles may encounter a meaningful connection. Stay socially engaged.', hi: 'अकेले लोगों को एक सार्थक संबंध मिल सकता है। सामाजिक रूप से सक्रिय रहें।', sa: 'अकेले लोगों को एक सार्थक संबंध मिल सकता है। सामाजिक रूप से सक्रिय रहें।', mai: 'अकेले लोगों को एक सार्थक संबंध मिल सकता है। सामाजिक रूप से सक्रिय रहें।', mr: 'अकेले लोगों को एक सार्थक संबंध मिल सकता है। सामाजिक रूप से सक्रिय रहें।', ta: 'Singles may encounter a meaningful connection. Stay socially engaged.', te: 'Singles may encounter a meaningful connection. Stay socially engaged.', bn: 'Singles may encounter a meaningful connection. Stay socially engaged.', kn: 'Singles may encounter a meaningful connection. Stay socially engaged.', gu: 'Singles may encounter a meaningful connection. Stay socially engaged.' },
  { en: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.', hi: 'क्षमा और समझ सहजता से बहती है। किसी भी लंबित गलतफहमी का समाधान करें।', sa: 'क्षमा और समझ सहजता से बहती है। किसी भी लंबित गलतफहमी का समाधान करें।', mai: 'क्षमा और समझ सहजता से बहती है। किसी भी लंबित गलतफहमी का समाधान करें।', mr: 'क्षमा और समझ सहजता से बहती है। किसी भी लंबित गलतफहमी का समाधान करें।', ta: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.', te: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.', bn: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.', kn: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.', gu: 'Forgiveness and understanding flow easily. Resolve any lingering misunderstandings.' },
  { en: 'Romance is in the air. Small gestures of love carry great significance today.', hi: 'प्रेम वातावरण में है। प्यार के छोटे इशारे आज बड़ा महत्व रखते हैं।', sa: 'प्रेम वातावरण में है। प्यार के छोटे इशारे आज बड़ा महत्व रखते हैं।', mai: 'प्रेम वातावरण में है। प्यार के छोटे इशारे आज बड़ा महत्व रखते हैं।', mr: 'प्रेम वातावरण में है। प्यार के छोटे इशारे आज बड़ा महत्व रखते हैं।', ta: 'Romance is in the air. Small gestures of love carry great significance today.', te: 'Romance is in the air. Small gestures of love carry great significance today.', bn: 'Romance is in the air. Small gestures of love carry great significance today.', kn: 'Romance is in the air. Small gestures of love carry great significance today.', gu: 'Romance is in the air. Small gestures of love carry great significance today.' },
  { en: 'Family relationships bring comfort and joy. Spend quality time at home.', hi: 'पारिवारिक रिश्ते आराम और खुशी लाते हैं। घर पर गुणवत्तापूर्ण समय बिताएँ।', sa: 'पारिवारिक रिश्ते आराम और खुशी लाते हैं। घर पर गुणवत्तापूर्ण समय बिताएँ।', mai: 'पारिवारिक रिश्ते आराम और खुशी लाते हैं। घर पर गुणवत्तापूर्ण समय बिताएँ।', mr: 'पारिवारिक रिश्ते आराम और खुशी लाते हैं। घर पर गुणवत्तापूर्ण समय बिताएँ।', ta: 'Family relationships bring comfort and joy. Spend quality time at home.', te: 'Family relationships bring comfort and joy. Spend quality time at home.', bn: 'Family relationships bring comfort and joy. Spend quality time at home.', kn: 'Family relationships bring comfort and joy. Spend quality time at home.', gu: 'Family relationships bring comfort and joy. Spend quality time at home.' },
];

const LOVE_MIXED: BilingualText[] = [
  { en: 'Relationships need gentle attention. Listen more than you speak today.', hi: 'रिश्तों को कोमल ध्यान की आवश्यकता है। आज बोलने से अधिक सुनें।', sa: 'रिश्तों को कोमल ध्यान की आवश्यकता है। आज बोलने से अधिक सुनें।', mai: 'रिश्तों को कोमल ध्यान की आवश्यकता है। आज बोलने से अधिक सुनें।', mr: 'रिश्तों को कोमल ध्यान की आवश्यकता है। आज बोलने से अधिक सुनें।', ta: 'Relationships need gentle attention. Listen more than you speak today.', te: 'Relationships need gentle attention. Listen more than you speak today.', bn: 'Relationships need gentle attention. Listen more than you speak today.', kn: 'Relationships need gentle attention. Listen more than you speak today.', gu: 'Relationships need gentle attention. Listen more than you speak today.' },
  { en: 'Emotional clarity may be elusive. Give yourself and others space to process.', hi: 'भावनात्मक स्पष्टता अस्पष्ट हो सकती है। स्वयं को और दूसरों को समझने का स्थान दें।', sa: 'भावनात्मक स्पष्टता अस्पष्ट हो सकती है। स्वयं को और दूसरों को समझने का स्थान दें।', mai: 'भावनात्मक स्पष्टता अस्पष्ट हो सकती है। स्वयं को और दूसरों को समझने का स्थान दें।', mr: 'भावनात्मक स्पष्टता अस्पष्ट हो सकती है। स्वयं को और दूसरों को समझने का स्थान दें।', ta: 'Emotional clarity may be elusive. Give yourself and others space to process.', te: 'Emotional clarity may be elusive. Give yourself and others space to process.', bn: 'Emotional clarity may be elusive. Give yourself and others space to process.', kn: 'Emotional clarity may be elusive. Give yourself and others space to process.', gu: 'Emotional clarity may be elusive. Give yourself and others space to process.' },
  { en: 'Balance personal needs with partnership demands. Neither should be neglected.', hi: 'व्यक्तिगत आवश्यकताओं को साझेदारी की माँगों के साथ संतुलित करें।', sa: 'व्यक्तिगत आवश्यकताओं को साझेदारी की माँगों के साथ संतुलित करें।', mai: 'व्यक्तिगत आवश्यकताओं को साझेदारी की माँगों के साथ संतुलित करें।', mr: 'व्यक्तिगत आवश्यकताओं को साझेदारी की माँगों के साथ संतुलित करें।', ta: 'Balance personal needs with partnership demands. Neither should be neglected.', te: 'Balance personal needs with partnership demands. Neither should be neglected.', bn: 'Balance personal needs with partnership demands. Neither should be neglected.', kn: 'Balance personal needs with partnership demands. Neither should be neglected.', gu: 'Balance personal needs with partnership demands. Neither should be neglected.' },
  { en: 'A calm, honest conversation can prevent a small issue from growing.', hi: 'एक शांत, ईमानदार बातचीत छोटी समस्या को बढ़ने से रोक सकती है।', sa: 'एक शांत, ईमानदार बातचीत छोटी समस्या को बढ़ने से रोक सकती है।', mai: 'एक शांत, ईमानदार बातचीत छोटी समस्या को बढ़ने से रोक सकती है।', mr: 'एक शांत, ईमानदार बातचीत छोटी समस्या को बढ़ने से रोक सकती है।', ta: 'A calm, honest conversation can prevent a small issue from growing.', te: 'A calm, honest conversation can prevent a small issue from growing.', bn: 'A calm, honest conversation can prevent a small issue from growing.', kn: 'A calm, honest conversation can prevent a small issue from growing.', gu: 'A calm, honest conversation can prevent a small issue from growing.' },
  { en: 'Social energy is moderate. Choose quality interactions over quantity.', hi: 'सामाजिक ऊर्जा मध्यम है। मात्रा से अधिक गुणवत्तापूर्ण संवाद चुनें।', sa: 'सामाजिक ऊर्जा मध्यम है। मात्रा से अधिक गुणवत्तापूर्ण संवाद चुनें।', mai: 'सामाजिक ऊर्जा मध्यम है। मात्रा से अधिक गुणवत्तापूर्ण संवाद चुनें।', mr: 'सामाजिक ऊर्जा मध्यम है। मात्रा से अधिक गुणवत्तापूर्ण संवाद चुनें।', ta: 'Social energy is moderate. Choose quality interactions over quantity.', te: 'Social energy is moderate. Choose quality interactions over quantity.', bn: 'Social energy is moderate. Choose quality interactions over quantity.', kn: 'Social energy is moderate. Choose quality interactions over quantity.', gu: 'Social energy is moderate. Choose quality interactions over quantity.' },
  { en: 'Old memories may resurface. Process them with compassion, not attachment.', hi: 'पुरानी यादें सतह पर आ सकती हैं। उन्हें करुणा से संसाधित करें, आसक्ति से नहीं।', sa: 'पुरानी यादें सतह पर आ सकती हैं। उन्हें करुणा से संसाधित करें, आसक्ति से नहीं।', mai: 'पुरानी यादें सतह पर आ सकती हैं। उन्हें करुणा से संसाधित करें, आसक्ति से नहीं।', mr: 'पुरानी यादें सतह पर आ सकती हैं। उन्हें करुणा से संसाधित करें, आसक्ति से नहीं।', ta: 'Old memories may resurface. Process them with compassion, not attachment.', te: 'Old memories may resurface. Process them with compassion, not attachment.', bn: 'Old memories may resurface. Process them with compassion, not attachment.', kn: 'Old memories may resurface. Process them with compassion, not attachment.', gu: 'Old memories may resurface. Process them with compassion, not attachment.' },
];

const LOVE_CHALLENGING: BilingualText[] = [
  { en: 'Avoid sensitive conversations today. Emotions run high and words may wound.', hi: 'आज संवेदनशील बातचीत से बचें। भावनाएँ तीव्र हैं और शब्द घाव दे सकते हैं।', sa: 'आज संवेदनशील बातचीत से बचें। भावनाएँ तीव्र हैं और शब्द घाव दे सकते हैं।', mai: 'आज संवेदनशील बातचीत से बचें। भावनाएँ तीव्र हैं और शब्द घाव दे सकते हैं।', mr: 'आज संवेदनशील बातचीत से बचें। भावनाएँ तीव्र हैं और शब्द घाव दे सकते हैं।', ta: 'Avoid sensitive conversations today. Emotions run high and words may wound.', te: 'Avoid sensitive conversations today. Emotions run high and words may wound.', bn: 'Avoid sensitive conversations today. Emotions run high and words may wound.', kn: 'Avoid sensitive conversations today. Emotions run high and words may wound.', gu: 'Avoid sensitive conversations today. Emotions run high and words may wound.' },
  { en: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.', hi: 'गलतफहमी की संभावना है। भावनात्मक रूप से प्रतिक्रिया देने से पहले इरादे स्पष्ट करें।', sa: 'गलतफहमी की संभावना है। भावनात्मक रूप से प्रतिक्रिया देने से पहले इरादे स्पष्ट करें।', mai: 'गलतफहमी की संभावना है। भावनात्मक रूप से प्रतिक्रिया देने से पहले इरादे स्पष्ट करें।', mr: 'गलतफहमी की संभावना है। भावनात्मक रूप से प्रतिक्रिया देने से पहले इरादे स्पष्ट करें।', ta: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.', te: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.', bn: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.', kn: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.', gu: 'Misunderstandings are likely. Clarify intentions before reacting emotionally.' },
  { en: 'Personal space is important today. Respect boundaries — yours and others.', hi: 'आज व्यक्तिगत स्थान महत्वपूर्ण है। सीमाओं का सम्मान करें — अपनी और दूसरों की।', sa: 'आज व्यक्तिगत स्थान महत्वपूर्ण है। सीमाओं का सम्मान करें — अपनी और दूसरों की।', mai: 'आज व्यक्तिगत स्थान महत्वपूर्ण है। सीमाओं का सम्मान करें — अपनी और दूसरों की।', mr: 'आज व्यक्तिगत स्थान महत्वपूर्ण है। सीमाओं का सम्मान करें — अपनी और दूसरों की।', ta: 'Personal space is important today. Respect boundaries — yours and others.', te: 'Personal space is important today. Respect boundaries — yours and others.', bn: 'Personal space is important today. Respect boundaries — yours and others.', kn: 'Personal space is important today. Respect boundaries — yours and others.', gu: 'Personal space is important today. Respect boundaries — yours and others.' },
  { en: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.', hi: 'अकेलापन महसूस हो सकता है। अलग-थलग रहने के बजाय किसी विश्वसनीय मित्र से संपर्क करें।', sa: 'अकेलापन महसूस हो सकता है। अलग-थलग रहने के बजाय किसी विश्वसनीय मित्र से संपर्क करें।', mai: 'अकेलापन महसूस हो सकता है। अलग-थलग रहने के बजाय किसी विश्वसनीय मित्र से संपर्क करें।', mr: 'अकेलापन महसूस हो सकता है। अलग-थलग रहने के बजाय किसी विश्वसनीय मित्र से संपर्क करें।', ta: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.', te: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.', bn: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.', kn: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.', gu: 'Loneliness may surface. Reach out to a trusted friend rather than isolating.' },
  { en: 'Jealousy or possessiveness could create friction. Practice detachment and trust.', hi: 'ईर्ष्या या अधिकार भावना घर्षण पैदा कर सकती है। वैराग्य और विश्वास का अभ्यास करें।', sa: 'ईर्ष्या या अधिकार भावना घर्षण पैदा कर सकती है। वैराग्य और विश्वास का अभ्यास करें।', mai: 'ईर्ष्या या अधिकार भावना घर्षण पैदा कर सकती है। वैराग्य और विश्वास का अभ्यास करें।', mr: 'ईर्ष्या या अधिकार भावना घर्षण पैदा कर सकती है। वैराग्य और विश्वास का अभ्यास करें।', ta: 'Jealousy or possessiveness could create friction. Practice detachment and trust.', te: 'Jealousy or possessiveness could create friction. Practice detachment and trust.', bn: 'Jealousy or possessiveness could create friction. Practice detachment and trust.', kn: 'Jealousy or possessiveness could create friction. Practice detachment and trust.', gu: 'Jealousy or possessiveness could create friction. Practice detachment and trust.' },
  { en: 'Family disagreements need patience, not forceful resolution. Let things cool down.', hi: 'पारिवारिक असहमतियों में धैर्य चाहिए, बलपूर्वक समाधान नहीं। चीज़ों को शांत होने दें।', sa: 'पारिवारिक असहमतियों में धैर्य चाहिए, बलपूर्वक समाधान नहीं। चीज़ों को शांत होने दें।', mai: 'पारिवारिक असहमतियों में धैर्य चाहिए, बलपूर्वक समाधान नहीं। चीज़ों को शांत होने दें।', mr: 'पारिवारिक असहमतियों में धैर्य चाहिए, बलपूर्वक समाधान नहीं। चीज़ों को शांत होने दें।', ta: 'Family disagreements need patience, not forceful resolution. Let things cool down.', te: 'Family disagreements need patience, not forceful resolution. Let things cool down.', bn: 'Family disagreements need patience, not forceful resolution. Let things cool down.', kn: 'Family disagreements need patience, not forceful resolution. Let things cool down.', gu: 'Family disagreements need patience, not forceful resolution. Let things cool down.' },
];

// ─────────────────────────────────────────────────────────────
// HEALTH
// ─────────────────────────────────────────────────────────────
const HEALTH_GOOD: BilingualText[] = [
  { en: 'Vitality is high. Channel this energy into exercise or outdoor activities.', hi: 'जीवन शक्ति उच्च है। इस ऊर्जा को व्यायाम या बाहरी गतिविधियों में लगाएँ।', sa: 'जीवन शक्ति उच्च है। इस ऊर्जा को व्यायाम या बाहरी गतिविधियों में लगाएँ।', mai: 'जीवन शक्ति उच्च है। इस ऊर्जा को व्यायाम या बाहरी गतिविधियों में लगाएँ।', mr: 'जीवन शक्ति उच्च है। इस ऊर्जा को व्यायाम या बाहरी गतिविधियों में लगाएँ।', ta: 'Vitality is high. Channel this energy into exercise or outdoor activities.', te: 'Vitality is high. Channel this energy into exercise or outdoor activities.', bn: 'Vitality is high. Channel this energy into exercise or outdoor activities.', kn: 'Vitality is high. Channel this energy into exercise or outdoor activities.', gu: 'Vitality is high. Channel this energy into exercise or outdoor activities.' },
  { en: 'Excellent day for starting a new health routine or wellness practice.', hi: 'नई स्वास्थ्य दिनचर्या या कल्याण अभ्यास शुरू करने के लिए उत्कृष्ट दिन।', sa: 'नई स्वास्थ्य दिनचर्या या कल्याण अभ्यास शुरू करने के लिए उत्कृष्ट दिन।', mai: 'नई स्वास्थ्य दिनचर्या या कल्याण अभ्यास शुरू करने के लिए उत्कृष्ट दिन।', mr: 'नई स्वास्थ्य दिनचर्या या कल्याण अभ्यास शुरू करने के लिए उत्कृष्ट दिन।', ta: 'Excellent day for starting a new health routine or wellness practice.', te: 'Excellent day for starting a new health routine or wellness practice.', bn: 'Excellent day for starting a new health routine or wellness practice.', kn: 'Excellent day for starting a new health routine or wellness practice.', gu: 'Excellent day for starting a new health routine or wellness practice.' },
  { en: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.', hi: 'मन-शरीर का संबंध मजबूत है। योग या ध्यान विशेष रूप से फलदायी होगा।', sa: 'मन-शरीर का संबंध मजबूत है। योग या ध्यान विशेष रूप से फलदायी होगा।', mai: 'मन-शरीर का संबंध मजबूत है। योग या ध्यान विशेष रूप से फलदायी होगा।', mr: 'मन-शरीर का संबंध मजबूत है। योग या ध्यान विशेष रूप से फलदायी होगा।', ta: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.', te: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.', bn: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.', kn: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.', gu: 'Mind-body connection is strong. Yoga or meditation will be especially rewarding.' },
  { en: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.', hi: 'पाचन अग्नि संतुलित है। पौष्टिक भोजन का आनंद लें और अच्छी तरह जलयोजित रहें।', sa: 'पाचन अग्नि संतुलित है। पौष्टिक भोजन का आनंद लें और अच्छी तरह जलयोजित रहें।', mai: 'पाचन अग्नि संतुलित है। पौष्टिक भोजन का आनंद लें और अच्छी तरह जलयोजित रहें।', mr: 'पाचन अग्नि संतुलित है। पौष्टिक भोजन का आनंद लें और अच्छी तरह जलयोजित रहें।', ta: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.', te: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.', bn: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.', kn: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.', gu: 'Digestive fire is balanced. Enjoy nourishing meals and stay well-hydrated.' },
  { en: 'Sleep quality improves tonight. Establish a calming evening routine.', hi: 'आज रात नींद की गुणवत्ता सुधरती है। एक शांत शाम की दिनचर्या स्थापित करें।', sa: 'आज रात नींद की गुणवत्ता सुधरती है। एक शांत शाम की दिनचर्या स्थापित करें।', mai: 'आज रात नींद की गुणवत्ता सुधरती है। एक शांत शाम की दिनचर्या स्थापित करें।', mr: 'आज रात नींद की गुणवत्ता सुधरती है। एक शांत शाम की दिनचर्या स्थापित करें।', ta: 'Sleep quality improves tonight. Establish a calming evening routine.', te: 'Sleep quality improves tonight. Establish a calming evening routine.', bn: 'Sleep quality improves tonight. Establish a calming evening routine.', kn: 'Sleep quality improves tonight. Establish a calming evening routine.', gu: 'Sleep quality improves tonight. Establish a calming evening routine.' },
  { en: 'Physical resilience peaks. A good day for challenging workouts or sports.', hi: 'शारीरिक सहनशक्ति चरम पर है। चुनौतीपूर्ण कसरत या खेल के लिए अच्छा दिन।', sa: 'शारीरिक सहनशक्ति चरम पर है। चुनौतीपूर्ण कसरत या खेल के लिए अच्छा दिन।', mai: 'शारीरिक सहनशक्ति चरम पर है। चुनौतीपूर्ण कसरत या खेल के लिए अच्छा दिन।', mr: 'शारीरिक सहनशक्ति चरम पर है। चुनौतीपूर्ण कसरत या खेल के लिए अच्छा दिन।', ta: 'Physical resilience peaks. A good day for challenging workouts or sports.', te: 'Physical resilience peaks. A good day for challenging workouts or sports.', bn: 'Physical resilience peaks. A good day for challenging workouts or sports.', kn: 'Physical resilience peaks. A good day for challenging workouts or sports.', gu: 'Physical resilience peaks. A good day for challenging workouts or sports.' },
];

const HEALTH_MIXED: BilingualText[] = [
  { en: 'Energy fluctuates through the day. Pace yourself and take regular breaks.', hi: 'दिन भर ऊर्जा में उतार-चढ़ाव रहता है। अपनी गति बनाए रखें और नियमित विश्राम लें।', sa: 'दिन भर ऊर्जा में उतार-चढ़ाव रहता है। अपनी गति बनाए रखें और नियमित विश्राम लें।', mai: 'दिन भर ऊर्जा में उतार-चढ़ाव रहता है। अपनी गति बनाए रखें और नियमित विश्राम लें।', mr: 'दिन भर ऊर्जा में उतार-चढ़ाव रहता है। अपनी गति बनाए रखें और नियमित विश्राम लें।', ta: 'Energy fluctuates through the day. Pace yourself and take regular breaks.', te: 'Energy fluctuates through the day. Pace yourself and take regular breaks.', bn: 'Energy fluctuates through the day. Pace yourself and take regular breaks.', kn: 'Energy fluctuates through the day. Pace yourself and take regular breaks.', gu: 'Energy fluctuates through the day. Pace yourself and take regular breaks.' },
  { en: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.', hi: 'हल्के दर्द या तनाव हो सकता है। हल्की स्ट्रेचिंग और गर्म पेय सहायक हैं।', sa: 'हल्के दर्द या तनाव हो सकता है। हल्की स्ट्रेचिंग और गर्म पेय सहायक हैं।', mai: 'हल्के दर्द या तनाव हो सकता है। हल्की स्ट्रेचिंग और गर्म पेय सहायक हैं।', mr: 'हल्के दर्द या तनाव हो सकता है। हल्की स्ट्रेचिंग और गर्म पेय सहायक हैं।', ta: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.', te: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.', bn: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.', kn: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.', gu: 'Minor aches or tension may arise. Gentle stretching and warm drinks help.' },
  { en: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.', hi: 'आज अपने आहार को संयमित रखें। भारी या अपरिचित भोजन से बचें।', sa: 'आज अपने आहार को संयमित रखें। भारी या अपरिचित भोजन से बचें।', mai: 'आज अपने आहार को संयमित रखें। भारी या अपरिचित भोजन से बचें।', mr: 'आज अपने आहार को संयमित रखें। भारी या अपरिचित भोजन से बचें।', ta: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.', te: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.', bn: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.', kn: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.', gu: 'Moderate your diet today. Avoid heavy or unfamiliar foods that tax digestion.' },
  { en: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.', hi: 'दोपहर में मानसिक धुंधलापन संभव है। एक छोटी सैर स्पष्टता ताज़ा करती है।', sa: 'दोपहर में मानसिक धुंधलापन संभव है। एक छोटी सैर स्पष्टता ताज़ा करती है।', mai: 'दोपहर में मानसिक धुंधलापन संभव है। एक छोटी सैर स्पष्टता ताज़ा करती है।', mr: 'दोपहर में मानसिक धुंधलापन संभव है। एक छोटी सैर स्पष्टता ताज़ा करती है।', ta: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.', te: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.', bn: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.', kn: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.', gu: 'Mental fog is possible in the afternoon. A short walk refreshes clarity.' },
  { en: 'Adequate rest is essential today. Do not overcommit your physical energy.', hi: 'आज पर्याप्त आराम आवश्यक है। अपनी शारीरिक ऊर्जा पर अत्यधिक भार न डालें।', sa: 'आज पर्याप्त आराम आवश्यक है। अपनी शारीरिक ऊर्जा पर अत्यधिक भार न डालें।', mai: 'आज पर्याप्त आराम आवश्यक है। अपनी शारीरिक ऊर्जा पर अत्यधिक भार न डालें।', mr: 'आज पर्याप्त आराम आवश्यक है। अपनी शारीरिक ऊर्जा पर अत्यधिक भार न डालें।', ta: 'Adequate rest is essential today. Do not overcommit your physical energy.', te: 'Adequate rest is essential today. Do not overcommit your physical energy.', bn: 'Adequate rest is essential today. Do not overcommit your physical energy.', kn: 'Adequate rest is essential today. Do not overcommit your physical energy.', gu: 'Adequate rest is essential today. Do not overcommit your physical energy.' },
  { en: 'Hydration and fresh air are your best allies. Step outside if desk-bound.', hi: 'जलयोजन और ताज़ी हवा आपके सर्वोत्तम साथी हैं। डेस्क पर हों तो बाहर निकलें।', sa: 'जलयोजन और ताज़ी हवा आपके सर्वोत्तम साथी हैं। डेस्क पर हों तो बाहर निकलें।', mai: 'जलयोजन और ताज़ी हवा आपके सर्वोत्तम साथी हैं। डेस्क पर हों तो बाहर निकलें।', mr: 'जलयोजन और ताज़ी हवा आपके सर्वोत्तम साथी हैं। डेस्क पर हों तो बाहर निकलें।', ta: 'Hydration and fresh air are your best allies. Step outside if desk-bound.', te: 'Hydration and fresh air are your best allies. Step outside if desk-bound.', bn: 'Hydration and fresh air are your best allies. Step outside if desk-bound.', kn: 'Hydration and fresh air are your best allies. Step outside if desk-bound.', gu: 'Hydration and fresh air are your best allies. Step outside if desk-bound.' },
];

const HEALTH_CHALLENGING: BilingualText[] = [
  { en: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.', hi: 'थकान जल्दी आ सकती है। ऊर्जा बचाएँ और केवल आवश्यक कार्यों को प्राथमिकता दें।', sa: 'थकान जल्दी आ सकती है। ऊर्जा बचाएँ और केवल आवश्यक कार्यों को प्राथमिकता दें।', mai: 'थकान जल्दी आ सकती है। ऊर्जा बचाएँ और केवल आवश्यक कार्यों को प्राथमिकता दें।', mr: 'थकान जल्दी आ सकती है। ऊर्जा बचाएँ और केवल आवश्यक कार्यों को प्राथमिकता दें।', ta: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.', te: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.', bn: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.', kn: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.', gu: 'Fatigue may set in early. Conserve energy and prioritize essential tasks only.' },
  { en: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.', hi: 'तनाव का स्तर बढ़ा हुआ है। दिन भर प्राणायाम या गहरी साँस का अभ्यास करें।', sa: 'तनाव का स्तर बढ़ा हुआ है। दिन भर प्राणायाम या गहरी साँस का अभ्यास करें।', mai: 'तनाव का स्तर बढ़ा हुआ है। दिन भर प्राणायाम या गहरी साँस का अभ्यास करें।', mr: 'तनाव का स्तर बढ़ा हुआ है। दिन भर प्राणायाम या गहरी साँस का अभ्यास करें।', ta: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.', te: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.', bn: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.', kn: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.', gu: 'Stress levels are elevated. Practice pranayama or deep breathing throughout the day.' },
  { en: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.', hi: 'कठिन व्यायाम से बचें। इसके बजाय हल्की पुनर्स्थापनात्मक गतिविधि चुनें।', sa: 'कठिन व्यायाम से बचें। इसके बजाय हल्की पुनर्स्थापनात्मक गतिविधि चुनें।', mai: 'कठिन व्यायाम से बचें। इसके बजाय हल्की पुनर्स्थापनात्मक गतिविधि चुनें।', mr: 'कठिन व्यायाम से बचें। इसके बजाय हल्की पुनर्स्थापनात्मक गतिविधि चुनें।', ta: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.', te: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.', bn: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.', kn: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.', gu: 'Avoid strenuous exercise. Opt for gentle restorative movement instead.' },
  { en: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.', hi: 'सिरदर्द या आँखों के तनाव पर ध्यान दें। हर 30 मिनट में स्क्रीन से विश्राम लें।', sa: 'सिरदर्द या आँखों के तनाव पर ध्यान दें। हर 30 मिनट में स्क्रीन से विश्राम लें।', mai: 'सिरदर्द या आँखों के तनाव पर ध्यान दें। हर 30 मिनट में स्क्रीन से विश्राम लें।', mr: 'सिरदर्द या आँखों के तनाव पर ध्यान दें। हर 30 मिनट में स्क्रीन से विश्राम लें।', ta: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.', te: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.', bn: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.', kn: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.', gu: 'Watch for headaches or eye strain. Take screen breaks every 30 minutes.' },
  { en: 'Immunity needs support. Warm, light foods and early sleep are recommended.', hi: 'प्रतिरक्षा को सहारे की आवश्यकता है। गर्म, हल्का भोजन और जल्दी सोना उचित है।', sa: 'प्रतिरक्षा को सहारे की आवश्यकता है। गर्म, हल्का भोजन और जल्दी सोना उचित है।', mai: 'प्रतिरक्षा को सहारे की आवश्यकता है। गर्म, हल्का भोजन और जल्दी सोना उचित है।', mr: 'प्रतिरक्षा को सहारे की आवश्यकता है। गर्म, हल्का भोजन और जल्दी सोना उचित है।', ta: 'Immunity needs support. Warm, light foods and early sleep are recommended.', te: 'Immunity needs support. Warm, light foods and early sleep are recommended.', bn: 'Immunity needs support. Warm, light foods and early sleep are recommended.', kn: 'Immunity needs support. Warm, light foods and early sleep are recommended.', gu: 'Immunity needs support. Warm, light foods and early sleep are recommended.' },
  { en: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.', hi: 'भावनात्मक स्वास्थ्य पर ध्यान देना आवश्यक है। लेखन या किसी से बात करना भावनाओं को संसाधित करने में सहायक है।', sa: 'भावनात्मक स्वास्थ्य पर ध्यान देना आवश्यक है। लेखन या किसी से बात करना भावनाओं को संसाधित करने में सहायक है।', mai: 'भावनात्मक स्वास्थ्य पर ध्यान देना आवश्यक है। लेखन या किसी से बात करना भावनाओं को संसाधित करने में सहायक है।', mr: 'भावनात्मक स्वास्थ्य पर ध्यान देना आवश्यक है। लेखन या किसी से बात करना भावनाओं को संसाधित करने में सहायक है।', ta: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.', te: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.', bn: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.', kn: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.', gu: 'Emotional health requires attention. Journaling or talking to someone helps process feelings.' },
];

// ─────────────────────────────────────────────────────────────
// FINANCE
// ─────────────────────────────────────────────────────────────
const FINANCE_GOOD: BilingualText[] = [
  { en: 'Financial gains are indicated. Investments made today carry favorable energy.', hi: 'आर्थिक लाभ संकेतित है। आज किए गए निवेश अनुकूल ऊर्जा रखते हैं।', sa: 'आर्थिक लाभ संकेतित है। आज किए गए निवेश अनुकूल ऊर्जा रखते हैं।', mai: 'आर्थिक लाभ संकेतित है। आज किए गए निवेश अनुकूल ऊर्जा रखते हैं।', mr: 'आर्थिक लाभ संकेतित है। आज किए गए निवेश अनुकूल ऊर्जा रखते हैं।', ta: 'Financial gains are indicated. Investments made today carry favorable energy.', te: 'Financial gains are indicated. Investments made today carry favorable energy.', bn: 'Financial gains are indicated. Investments made today carry favorable energy.', kn: 'Financial gains are indicated. Investments made today carry favorable energy.', gu: 'Financial gains are indicated. Investments made today carry favorable energy.' },
  { en: 'Good day to negotiate deals or finalize contracts with monetary implications.', hi: 'सौदों पर बातचीत या आर्थिक प्रभाव वाले अनुबंधों को अंतिम रूप देने का अच्छा दिन।', sa: 'सौदों पर बातचीत या आर्थिक प्रभाव वाले अनुबंधों को अंतिम रूप देने का अच्छा दिन।', mai: 'सौदों पर बातचीत या आर्थिक प्रभाव वाले अनुबंधों को अंतिम रूप देने का अच्छा दिन।', mr: 'सौदों पर बातचीत या आर्थिक प्रभाव वाले अनुबंधों को अंतिम रूप देने का अच्छा दिन।', ta: 'Good day to negotiate deals or finalize contracts with monetary implications.', te: 'Good day to negotiate deals or finalize contracts with monetary implications.', bn: 'Good day to negotiate deals or finalize contracts with monetary implications.', kn: 'Good day to negotiate deals or finalize contracts with monetary implications.', gu: 'Good day to negotiate deals or finalize contracts with monetary implications.' },
  { en: 'Unexpected income or a financial opportunity may present itself. Stay alert.', hi: 'अप्रत्याशित आय या वित्तीय अवसर स्वयं प्रस्तुत हो सकता है। सतर्क रहें।', sa: 'अप्रत्याशित आय या वित्तीय अवसर स्वयं प्रस्तुत हो सकता है। सतर्क रहें।', mai: 'अप्रत्याशित आय या वित्तीय अवसर स्वयं प्रस्तुत हो सकता है। सतर्क रहें।', mr: 'अप्रत्याशित आय या वित्तीय अवसर स्वयं प्रस्तुत हो सकता है। सतर्क रहें।', ta: 'Unexpected income or a financial opportunity may present itself. Stay alert.', te: 'Unexpected income or a financial opportunity may present itself. Stay alert.', bn: 'Unexpected income or a financial opportunity may present itself. Stay alert.', kn: 'Unexpected income or a financial opportunity may present itself. Stay alert.', gu: 'Unexpected income or a financial opportunity may present itself. Stay alert.' },
  { en: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.', hi: 'बचत के प्रयास फल देते हैं। अपने पोर्टफोलियो की समीक्षा करें।', sa: 'बचत के प्रयास फल देते हैं। अपने पोर्टफोलियो की समीक्षा करें।', mai: 'बचत के प्रयास फल देते हैं। अपने पोर्टफोलियो की समीक्षा करें।', mr: 'बचत के प्रयास फल देते हैं। अपने पोर्टफोलियो की समीक्षा करें।', ta: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.', te: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.', bn: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.', kn: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.', gu: 'Savings efforts pay off. Review your portfolio and reinforce winning positions.' },
  { en: 'Property or asset-related decisions are well-supported today.', hi: 'संपत्ति या परिसंपत्ति संबंधी निर्णयों को आज अच्छा समर्थन मिलता है।', sa: 'संपत्ति या परिसंपत्ति संबंधी निर्णयों को आज अच्छा समर्थन मिलता है।', mai: 'संपत्ति या परिसंपत्ति संबंधी निर्णयों को आज अच्छा समर्थन मिलता है।', mr: 'संपत्ति या परिसंपत्ति संबंधी निर्णयों को आज अच्छा समर्थन मिलता है।', ta: 'Property or asset-related decisions are well-supported today.', te: 'Property or asset-related decisions are well-supported today.', bn: 'Property or asset-related decisions are well-supported today.', kn: 'Property or asset-related decisions are well-supported today.', gu: 'Property or asset-related decisions are well-supported today.' },
  { en: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.', hi: 'उदारता प्रचुरता को आकर्षित करती है। संसाधन साझा करें और समृद्धि का चक्र जारी रहे।', sa: 'उदारता प्रचुरता को आकर्षित करती है। संसाधन साझा करें और समृद्धि का चक्र जारी रहे।', mai: 'उदारता प्रचुरता को आकर्षित करती है। संसाधन साझा करें और समृद्धि का चक्र जारी रहे।', mr: 'उदारता प्रचुरता को आकर्षित करती है। संसाधन साझा करें और समृद्धि का चक्र जारी रहे।', ta: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.', te: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.', bn: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.', kn: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.', gu: 'Generosity attracts abundance. Share resources and the cycle of prosperity continues.' },
];

const FINANCE_MIXED: BilingualText[] = [
  { en: 'Financial decisions require extra deliberation today. Do not rush.', hi: 'आज वित्तीय निर्णयों में अतिरिक्त विचार-विमर्श आवश्यक है। जल्दबाज़ी न करें।', sa: 'आज वित्तीय निर्णयों में अतिरिक्त विचार-विमर्श आवश्यक है। जल्दबाज़ी न करें।', mai: 'आज वित्तीय निर्णयों में अतिरिक्त विचार-विमर्श आवश्यक है। जल्दबाज़ी न करें।', mr: 'आज वित्तीय निर्णयों में अतिरिक्त विचार-विमर्श आवश्यक है। जल्दबाज़ी न करें।', ta: 'Financial decisions require extra deliberation today. Do not rush.', te: 'Financial decisions require extra deliberation today. Do not rush.', bn: 'Financial decisions require extra deliberation today. Do not rush.', kn: 'Financial decisions require extra deliberation today. Do not rush.', gu: 'Financial decisions require extra deliberation today. Do not rush.' },
  { en: 'Small, steady steps serve better than bold financial moves right now.', hi: 'अभी बड़े वित्तीय कदमों से बेहतर छोटे, स्थिर कदम काम करते हैं।', sa: 'अभी बड़े वित्तीय कदमों से बेहतर छोटे, स्थिर कदम काम करते हैं।', mai: 'अभी बड़े वित्तीय कदमों से बेहतर छोटे, स्थिर कदम काम करते हैं।', mr: 'अभी बड़े वित्तीय कदमों से बेहतर छोटे, स्थिर कदम काम करते हैं।', ta: 'Small, steady steps serve better than bold financial moves right now.', te: 'Small, steady steps serve better than bold financial moves right now.', bn: 'Small, steady steps serve better than bold financial moves right now.', kn: 'Small, steady steps serve better than bold financial moves right now.', gu: 'Small, steady steps serve better than bold financial moves right now.' },
  { en: 'Review expenses and eliminate unnecessary subscriptions or commitments.', hi: 'खर्चों की समीक्षा करें और अनावश्यक सदस्यता या प्रतिबद्धताएँ समाप्त करें।', sa: 'खर्चों की समीक्षा करें और अनावश्यक सदस्यता या प्रतिबद्धताएँ समाप्त करें।', mai: 'खर्चों की समीक्षा करें और अनावश्यक सदस्यता या प्रतिबद्धताएँ समाप्त करें।', mr: 'खर्चों की समीक्षा करें और अनावश्यक सदस्यता या प्रतिबद्धताएँ समाप्त करें।', ta: 'Review expenses and eliminate unnecessary subscriptions or commitments.', te: 'Review expenses and eliminate unnecessary subscriptions or commitments.', bn: 'Review expenses and eliminate unnecessary subscriptions or commitments.', kn: 'Review expenses and eliminate unnecessary subscriptions or commitments.', gu: 'Review expenses and eliminate unnecessary subscriptions or commitments.' },
  { en: 'Lending or borrowing money today may complicate relationships. Be cautious.', hi: 'आज धन उधार देना या लेना रिश्तों को जटिल कर सकता है। सतर्क रहें।', sa: 'आज धन उधार देना या लेना रिश्तों को जटिल कर सकता है। सतर्क रहें।', mai: 'आज धन उधार देना या लेना रिश्तों को जटिल कर सकता है। सतर्क रहें।', mr: 'आज धन उधार देना या लेना रिश्तों को जटिल कर सकता है। सतर्क रहें।', ta: 'Lending or borrowing money today may complicate relationships. Be cautious.', te: 'Lending or borrowing money today may complicate relationships. Be cautious.', bn: 'Lending or borrowing money today may complicate relationships. Be cautious.', kn: 'Lending or borrowing money today may complicate relationships. Be cautious.', gu: 'Lending or borrowing money today may complicate relationships. Be cautious.' },
  { en: 'Income remains stable but growth requires patience. Focus on long-term plans.', hi: 'आय स्थिर रहती है लेकिन वृद्धि में धैर्य चाहिए। दीर्घकालिक योजनाओं पर ध्यान दें।', sa: 'आय स्थिर रहती है लेकिन वृद्धि में धैर्य चाहिए। दीर्घकालिक योजनाओं पर ध्यान दें।', mai: 'आय स्थिर रहती है लेकिन वृद्धि में धैर्य चाहिए। दीर्घकालिक योजनाओं पर ध्यान दें।', mr: 'आय स्थिर रहती है लेकिन वृद्धि में धैर्य चाहिए। दीर्घकालिक योजनाओं पर ध्यान दें।', ta: 'Income remains stable but growth requires patience. Focus on long-term plans.', te: 'Income remains stable but growth requires patience. Focus on long-term plans.', bn: 'Income remains stable but growth requires patience. Focus on long-term plans.', kn: 'Income remains stable but growth requires patience. Focus on long-term plans.', gu: 'Income remains stable but growth requires patience. Focus on long-term plans.' },
  { en: 'A moderate approach to spending serves you well. Avoid impulse purchases.', hi: 'खर्च के प्रति संयमित दृष्टिकोण आपकी सेवा करता है। आवेगी खरीदारी से बचें।', sa: 'खर्च के प्रति संयमित दृष्टिकोण आपकी सेवा करता है। आवेगी खरीदारी से बचें।', mai: 'खर्च के प्रति संयमित दृष्टिकोण आपकी सेवा करता है। आवेगी खरीदारी से बचें।', mr: 'खर्च के प्रति संयमित दृष्टिकोण आपकी सेवा करता है। आवेगी खरीदारी से बचें।', ta: 'A moderate approach to spending serves you well. Avoid impulse purchases.', te: 'A moderate approach to spending serves you well. Avoid impulse purchases.', bn: 'A moderate approach to spending serves you well. Avoid impulse purchases.', kn: 'A moderate approach to spending serves you well. Avoid impulse purchases.', gu: 'A moderate approach to spending serves you well. Avoid impulse purchases.' },
];

const FINANCE_CHALLENGING: BilingualText[] = [
  { en: 'Avoid major financial commitments today. The energy does not support risk-taking.', hi: 'आज बड़ी वित्तीय प्रतिबद्धताओं से बचें। ऊर्जा जोखिम लेने का समर्थन नहीं करती।', sa: 'आज बड़ी वित्तीय प्रतिबद्धताओं से बचें। ऊर्जा जोखिम लेने का समर्थन नहीं करती।', mai: 'आज बड़ी वित्तीय प्रतिबद्धताओं से बचें। ऊर्जा जोखिम लेने का समर्थन नहीं करती।', mr: 'आज बड़ी वित्तीय प्रतिबद्धताओं से बचें। ऊर्जा जोखिम लेने का समर्थन नहीं करती।', ta: 'Avoid major financial commitments today. The energy does not support risk-taking.', te: 'Avoid major financial commitments today. The energy does not support risk-taking.', bn: 'Avoid major financial commitments today. The energy does not support risk-taking.', kn: 'Avoid major financial commitments today. The energy does not support risk-taking.', gu: 'Avoid major financial commitments today. The energy does not support risk-taking.' },
  { en: 'Unexpected expenses may surface. Keep an emergency buffer accessible.', hi: 'अप्रत्याशित खर्च सामने आ सकते हैं। आपातकालीन बफर सुलभ रखें।', sa: 'अप्रत्याशित खर्च सामने आ सकते हैं। आपातकालीन बफर सुलभ रखें।', mai: 'अप्रत्याशित खर्च सामने आ सकते हैं। आपातकालीन बफर सुलभ रखें।', mr: 'अप्रत्याशित खर्च सामने आ सकते हैं। आपातकालीन बफर सुलभ रखें।', ta: 'Unexpected expenses may surface. Keep an emergency buffer accessible.', te: 'Unexpected expenses may surface. Keep an emergency buffer accessible.', bn: 'Unexpected expenses may surface. Keep an emergency buffer accessible.', kn: 'Unexpected expenses may surface. Keep an emergency buffer accessible.', gu: 'Unexpected expenses may surface. Keep an emergency buffer accessible.' },
  { en: 'Speculative investments are particularly risky now. Preserve capital.', hi: 'सट्टा निवेश अभी विशेष रूप से जोखिम भरे हैं। पूँजी सुरक्षित रखें।', sa: 'सट्टा निवेश अभी विशेष रूप से जोखिम भरे हैं। पूँजी सुरक्षित रखें।', mai: 'सट्टा निवेश अभी विशेष रूप से जोखिम भरे हैं। पूँजी सुरक्षित रखें।', mr: 'सट्टा निवेश अभी विशेष रूप से जोखिम भरे हैं। पूँजी सुरक्षित रखें।', ta: 'Speculative investments are particularly risky now. Preserve capital.', te: 'Speculative investments are particularly risky now. Preserve capital.', bn: 'Speculative investments are particularly risky now. Preserve capital.', kn: 'Speculative investments are particularly risky now. Preserve capital.', gu: 'Speculative investments are particularly risky now. Preserve capital.' },
  { en: 'Financial documents need careful review. Double-check before signing anything.', hi: 'वित्तीय दस्तावेज़ों की सावधानीपूर्वक समीक्षा आवश्यक है। कुछ भी हस्ताक्षर करने से पहले दोबारा जाँचें।', sa: 'वित्तीय दस्तावेज़ों की सावधानीपूर्वक समीक्षा आवश्यक है। कुछ भी हस्ताक्षर करने से पहले दोबारा जाँचें।', mai: 'वित्तीय दस्तावेज़ों की सावधानीपूर्वक समीक्षा आवश्यक है। कुछ भी हस्ताक्षर करने से पहले दोबारा जाँचें।', mr: 'वित्तीय दस्तावेज़ों की सावधानीपूर्वक समीक्षा आवश्यक है। कुछ भी हस्ताक्षर करने से पहले दोबारा जाँचें।', ta: 'Financial documents need careful review. Double-check before signing anything.', te: 'Financial documents need careful review. Double-check before signing anything.', bn: 'Financial documents need careful review. Double-check before signing anything.', kn: 'Financial documents need careful review. Double-check before signing anything.', gu: 'Financial documents need careful review. Double-check before signing anything.' },
  { en: 'Delays in expected payments or returns are possible. Plan for contingencies.', hi: 'अपेक्षित भुगतान या रिटर्न में देरी संभव है। आकस्मिकताओं की योजना बनाएँ।', sa: 'अपेक्षित भुगतान या रिटर्न में देरी संभव है। आकस्मिकताओं की योजना बनाएँ।', mai: 'अपेक्षित भुगतान या रिटर्न में देरी संभव है। आकस्मिकताओं की योजना बनाएँ।', mr: 'अपेक्षित भुगतान या रिटर्न में देरी संभव है। आकस्मिकताओं की योजना बनाएँ।', ta: 'Delays in expected payments or returns are possible. Plan for contingencies.', te: 'Delays in expected payments or returns are possible. Plan for contingencies.', bn: 'Delays in expected payments or returns are possible. Plan for contingencies.', kn: 'Delays in expected payments or returns are possible. Plan for contingencies.', gu: 'Delays in expected payments or returns are possible. Plan for contingencies.' },
  { en: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.', hi: 'वित्तीय धोखाधड़ी या अत्यधिक आकर्षक प्रस्तावों से सावधान रहें। सब कुछ सत्यापित करें।', sa: 'वित्तीय धोखाधड़ी या अत्यधिक आकर्षक प्रस्तावों से सावधान रहें। सब कुछ सत्यापित करें।', mai: 'वित्तीय धोखाधड़ी या अत्यधिक आकर्षक प्रस्तावों से सावधान रहें। सब कुछ सत्यापित करें।', mr: 'वित्तीय धोखाधड़ी या अत्यधिक आकर्षक प्रस्तावों से सावधान रहें। सब कुछ सत्यापित करें।', ta: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.', te: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.', bn: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.', kn: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.', gu: 'Guard against financial fraud or too-good-to-be-true offers. Verify everything.' },
];

// ─────────────────────────────────────────────────────────────
// SPIRITUALITY
// ─────────────────────────────────────────────────────────────
const SPIRITUALITY_GOOD: BilingualText[] = [
  { en: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.', hi: 'आध्यात्मिक जागरूकता बढ़ती है। ध्यान और मंत्र जप गहरी शांति लाते हैं।', sa: 'आध्यात्मिक जागरूकता बढ़ती है। ध्यान और मंत्र जप गहरी शांति लाते हैं।', mai: 'आध्यात्मिक जागरूकता बढ़ती है। ध्यान और मंत्र जप गहरी शांति लाते हैं।', mr: 'आध्यात्मिक जागरूकता बढ़ती है। ध्यान और मंत्र जप गहरी शांति लाते हैं।', ta: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.', te: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.', bn: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.', kn: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.', gu: 'Spiritual awareness heightens. Meditation and mantra japa bring deep peace.' },
  { en: 'Intuition is sharp. Trust your inner guidance for important decisions.', hi: 'अंतर्ज्ञान तीव्र है। महत्वपूर्ण निर्णयों के लिए अपने आंतरिक मार्गदर्शन पर भरोसा करें।', sa: 'अंतर्ज्ञान तीव्र है। महत्वपूर्ण निर्णयों के लिए अपने आंतरिक मार्गदर्शन पर भरोसा करें।', mai: 'अंतर्ज्ञान तीव्र है। महत्वपूर्ण निर्णयों के लिए अपने आंतरिक मार्गदर्शन पर भरोसा करें।', mr: 'अंतर्ज्ञान तीव्र है। महत्वपूर्ण निर्णयों के लिए अपने आंतरिक मार्गदर्शन पर भरोसा करें।', ta: 'Intuition is sharp. Trust your inner guidance for important decisions.', te: 'Intuition is sharp. Trust your inner guidance for important decisions.', bn: 'Intuition is sharp. Trust your inner guidance for important decisions.', kn: 'Intuition is sharp. Trust your inner guidance for important decisions.', gu: 'Intuition is sharp. Trust your inner guidance for important decisions.' },
  { en: 'Temple visits or sacred rituals carry amplified blessings today.', hi: 'मंदिर दर्शन या पवित्र अनुष्ठान आज विशेष आशीर्वाद लाते हैं।', sa: 'मंदिर दर्शन या पवित्र अनुष्ठान आज विशेष आशीर्वाद लाते हैं।', mai: 'मंदिर दर्शन या पवित्र अनुष्ठान आज विशेष आशीर्वाद लाते हैं।', mr: 'मंदिर दर्शन या पवित्र अनुष्ठान आज विशेष आशीर्वाद लाते हैं।', ta: 'Temple visits or sacred rituals carry amplified blessings today.', te: 'Temple visits or sacred rituals carry amplified blessings today.', bn: 'Temple visits or sacred rituals carry amplified blessings today.', kn: 'Temple visits or sacred rituals carry amplified blessings today.', gu: 'Temple visits or sacred rituals carry amplified blessings today.' },
  { en: 'A moment of gratitude transforms your entire day. Begin with thankfulness.', hi: 'कृतज्ञता का एक क्षण आपके पूरे दिन को बदल देता है। आभार से शुरू करें।', sa: 'कृतज्ञता का एक क्षण आपके पूरे दिन को बदल देता है। आभार से शुरू करें।', mai: 'कृतज्ञता का एक क्षण आपके पूरे दिन को बदल देता है। आभार से शुरू करें।', mr: 'कृतज्ञता का एक क्षण आपके पूरे दिन को बदल देता है। आभार से शुरू करें।', ta: 'A moment of gratitude transforms your entire day. Begin with thankfulness.', te: 'A moment of gratitude transforms your entire day. Begin with thankfulness.', bn: 'A moment of gratitude transforms your entire day. Begin with thankfulness.', kn: 'A moment of gratitude transforms your entire day. Begin with thankfulness.', gu: 'A moment of gratitude transforms your entire day. Begin with thankfulness.' },
  { en: 'Connection with your guru or spiritual teacher is especially potent now.', hi: 'अपने गुरु या आध्यात्मिक शिक्षक के साथ संबंध अभी विशेष रूप से शक्तिशाली है।', sa: 'अपने गुरु या आध्यात्मिक शिक्षक के साथ संबंध अभी विशेष रूप से शक्तिशाली है।', mai: 'अपने गुरु या आध्यात्मिक शिक्षक के साथ संबंध अभी विशेष रूप से शक्तिशाली है।', mr: 'अपने गुरु या आध्यात्मिक शिक्षक के साथ संबंध अभी विशेष रूप से शक्तिशाली है।', ta: 'Connection with your guru or spiritual teacher is especially potent now.', te: 'Connection with your guru or spiritual teacher is especially potent now.', bn: 'Connection with your guru or spiritual teacher is especially potent now.', kn: 'Connection with your guru or spiritual teacher is especially potent now.', gu: 'Connection with your guru or spiritual teacher is especially potent now.' },
  { en: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.', hi: 'सेवा (निःस्वार्थ सेवा) के कार्य कर्म आशीर्वाद और आंतरिक संतुष्टि लाते हैं।', sa: 'सेवा (निःस्वार्थ सेवा) के कार्य कर्म आशीर्वाद और आंतरिक संतुष्टि लाते हैं।', mai: 'सेवा (निःस्वार्थ सेवा) के कार्य कर्म आशीर्वाद और आंतरिक संतुष्टि लाते हैं।', mr: 'सेवा (निःस्वार्थ सेवा) के कार्य कर्म आशीर्वाद और आंतरिक संतुष्टि लाते हैं।', ta: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.', te: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.', bn: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.', kn: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.', gu: 'Acts of seva (selfless service) bring karmic blessings and inner fulfillment.' },
];

const SPIRITUALITY_MIXED: BilingualText[] = [
  { en: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.', hi: 'आध्यात्मिक अभ्यास आज नियमित लगता है। भक्ति को पुनर्जीवित करने के लिए अलग दृष्टिकोण आज़माएँ।', sa: 'आध्यात्मिक अभ्यास आज नियमित लगता है। भक्ति को पुनर्जीवित करने के लिए अलग दृष्टिकोण आज़माएँ।', mai: 'आध्यात्मिक अभ्यास आज नियमित लगता है। भक्ति को पुनर्जीवित करने के लिए अलग दृष्टिकोण आज़माएँ।', mr: 'आध्यात्मिक अभ्यास आज नियमित लगता है। भक्ति को पुनर्जीवित करने के लिए अलग दृष्टिकोण आज़माएँ।', ta: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.', te: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.', bn: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.', kn: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.', gu: 'Spiritual practice feels routine today. Try a different approach to rekindle devotion.' },
  { en: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.', hi: 'ध्यान के दौरान मन भटकता है। धैर्य रखें — हर प्रयास अभ्यास को मजबूत करता है।', sa: 'ध्यान के दौरान मन भटकता है। धैर्य रखें — हर प्रयास अभ्यास को मजबूत करता है।', mai: 'ध्यान के दौरान मन भटकता है। धैर्य रखें — हर प्रयास अभ्यास को मजबूत करता है।', mr: 'ध्यान के दौरान मन भटकता है। धैर्य रखें — हर प्रयास अभ्यास को मजबूत करता है।', ta: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.', te: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.', bn: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.', kn: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.', gu: 'The mind wanders during meditation. Be patient — every attempt strengthens the practice.' },
  { en: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.', hi: 'भौतिक और आध्यात्मिक लक्ष्यों को संतुलित करें। किसी को दूसरे के लिए त्यागने की आवश्यकता नहीं।', sa: 'भौतिक और आध्यात्मिक लक्ष्यों को संतुलित करें। किसी को दूसरे के लिए त्यागने की आवश्यकता नहीं।', mai: 'भौतिक और आध्यात्मिक लक्ष्यों को संतुलित करें। किसी को दूसरे के लिए त्यागने की आवश्यकता नहीं।', mr: 'भौतिक और आध्यात्मिक लक्ष्यों को संतुलित करें। किसी को दूसरे के लिए त्यागने की आवश्यकता नहीं।', ta: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.', te: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.', bn: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.', kn: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.', gu: 'Balance material and spiritual pursuits. Neither need be sacrificed for the other.' },
  { en: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.', hi: 'प्रकृति में कुछ शांत मिनट बिताएँ। प्राकृतिक सुंदरता आपको दिव्य से जोड़ती है।', sa: 'प्रकृति में कुछ शांत मिनट बिताएँ। प्राकृतिक सुंदरता आपको दिव्य से जोड़ती है।', mai: 'प्रकृति में कुछ शांत मिनट बिताएँ। प्राकृतिक सुंदरता आपको दिव्य से जोड़ती है।', mr: 'प्रकृति में कुछ शांत मिनट बिताएँ। प्राकृतिक सुंदरता आपको दिव्य से जोड़ती है।', ta: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.', te: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.', bn: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.', kn: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.', gu: 'Spend a few quiet minutes in nature. Natural beauty reconnects you to the divine.' },
  { en: 'Reading a sacred text or shloka can shift your perspective during a flat day.', hi: 'एक पवित्र ग्रंथ या श्लोक पढ़ना एक सपाट दिन में आपके दृष्टिकोण को बदल सकता है।', sa: 'एक पवित्र ग्रंथ या श्लोक पढ़ना एक सपाट दिन में आपके दृष्टिकोण को बदल सकता है।', mai: 'एक पवित्र ग्रंथ या श्लोक पढ़ना एक सपाट दिन में आपके दृष्टिकोण को बदल सकता है।', mr: 'एक पवित्र ग्रंथ या श्लोक पढ़ना एक सपाट दिन में आपके दृष्टिकोण को बदल सकता है।', ta: 'Reading a sacred text or shloka can shift your perspective during a flat day.', te: 'Reading a sacred text or shloka can shift your perspective during a flat day.', bn: 'Reading a sacred text or shloka can shift your perspective during a flat day.', kn: 'Reading a sacred text or shloka can shift your perspective during a flat day.', gu: 'Reading a sacred text or shloka can shift your perspective during a flat day.' },
  { en: 'Karma awareness grows. Reflect on recent actions and their ripple effects.', hi: 'कर्म जागरूकता बढ़ती है। हाल के कार्यों और उनके प्रभावों पर चिंतन करें।', sa: 'कर्म जागरूकता बढ़ती है। हाल के कार्यों और उनके प्रभावों पर चिंतन करें।', mai: 'कर्म जागरूकता बढ़ती है। हाल के कार्यों और उनके प्रभावों पर चिंतन करें।', mr: 'कर्म जागरूकता बढ़ती है। हाल के कार्यों और उनके प्रभावों पर चिंतन करें।', ta: 'Karma awareness grows. Reflect on recent actions and their ripple effects.', te: 'Karma awareness grows. Reflect on recent actions and their ripple effects.', bn: 'Karma awareness grows. Reflect on recent actions and their ripple effects.', kn: 'Karma awareness grows. Reflect on recent actions and their ripple effects.', gu: 'Karma awareness grows. Reflect on recent actions and their ripple effects.' },
];

const SPIRITUALITY_CHALLENGING: BilingualText[] = [
  { en: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.', hi: 'आंतरिक बेचैनी आध्यात्मिक अभ्यास को कठिन बनाती है। बिना निर्णय के स्वीकार करें।', sa: 'आंतरिक बेचैनी आध्यात्मिक अभ्यास को कठिन बनाती है। बिना निर्णय के स्वीकार करें।', mai: 'आंतरिक बेचैनी आध्यात्मिक अभ्यास को कठिन बनाती है। बिना निर्णय के स्वीकार करें।', mr: 'आंतरिक बेचैनी आध्यात्मिक अभ्यास को कठिन बनाती है। बिना निर्णय के स्वीकार करें।', ta: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.', te: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.', bn: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.', kn: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.', gu: 'Inner restlessness makes spiritual practice difficult. Accept it without judgment.' },
  { en: 'Doubts about your path may arise. This is part of growth — keep walking.', hi: 'आपके मार्ग के बारे में संदेह उत्पन्न हो सकते हैं। यह विकास का हिस्सा है — चलते रहें।', sa: 'आपके मार्ग के बारे में संदेह उत्पन्न हो सकते हैं। यह विकास का हिस्सा है — चलते रहें।', mai: 'आपके मार्ग के बारे में संदेह उत्पन्न हो सकते हैं। यह विकास का हिस्सा है — चलते रहें।', mr: 'आपके मार्ग के बारे में संदेह उत्पन्न हो सकते हैं। यह विकास का हिस्सा है — चलते रहें।', ta: 'Doubts about your path may arise. This is part of growth — keep walking.', te: 'Doubts about your path may arise. This is part of growth — keep walking.', bn: 'Doubts about your path may arise. This is part of growth — keep walking.', kn: 'Doubts about your path may arise. This is part of growth — keep walking.', gu: 'Doubts about your path may arise. This is part of growth — keep walking.' },
  { en: 'Ego may dominate today. Practice humility and remember your deeper purpose.', hi: 'आज अहंकार प्रबल हो सकता है। विनम्रता का अभ्यास करें और अपने गहरे उद्देश्य को याद रखें।', sa: 'आज अहंकार प्रबल हो सकता है। विनम्रता का अभ्यास करें और अपने गहरे उद्देश्य को याद रखें।', mai: 'आज अहंकार प्रबल हो सकता है। विनम्रता का अभ्यास करें और अपने गहरे उद्देश्य को याद रखें।', mr: 'आज अहंकार प्रबल हो सकता है। विनम्रता का अभ्यास करें और अपने गहरे उद्देश्य को याद रखें।', ta: 'Ego may dominate today. Practice humility and remember your deeper purpose.', te: 'Ego may dominate today. Practice humility and remember your deeper purpose.', bn: 'Ego may dominate today. Practice humility and remember your deeper purpose.', kn: 'Ego may dominate today. Practice humility and remember your deeper purpose.', gu: 'Ego may dominate today. Practice humility and remember your deeper purpose.' },
  { en: 'External distractions pull you from center. Set firm boundaries for sacred time.', hi: 'बाहरी विकर्षण आपको केंद्र से खींचते हैं। पवित्र समय के लिए दृढ़ सीमाएँ निर्धारित करें।', sa: 'बाहरी विकर्षण आपको केंद्र से खींचते हैं। पवित्र समय के लिए दृढ़ सीमाएँ निर्धारित करें।', mai: 'बाहरी विकर्षण आपको केंद्र से खींचते हैं। पवित्र समय के लिए दृढ़ सीमाएँ निर्धारित करें।', mr: 'बाहरी विकर्षण आपको केंद्र से खींचते हैं। पवित्र समय के लिए दृढ़ सीमाएँ निर्धारित करें।', ta: 'External distractions pull you from center. Set firm boundaries for sacred time.', te: 'External distractions pull you from center. Set firm boundaries for sacred time.', bn: 'External distractions pull you from center. Set firm boundaries for sacred time.', kn: 'External distractions pull you from center. Set firm boundaries for sacred time.', gu: 'External distractions pull you from center. Set firm boundaries for sacred time.' },
  { en: 'Past regrets may surface during quiet moments. Release them through breath and prayer.', hi: 'शांत क्षणों में पिछले पछतावे सतह पर आ सकते हैं। साँस और प्रार्थना से उन्हें मुक्त करें।', sa: 'शांत क्षणों में पिछले पछतावे सतह पर आ सकते हैं। साँस और प्रार्थना से उन्हें मुक्त करें।', mai: 'शांत क्षणों में पिछले पछतावे सतह पर आ सकते हैं। साँस और प्रार्थना से उन्हें मुक्त करें।', mr: 'शांत क्षणों में पिछले पछतावे सतह पर आ सकते हैं। साँस और प्रार्थना से उन्हें मुक्त करें।', ta: 'Past regrets may surface during quiet moments. Release them through breath and prayer.', te: 'Past regrets may surface during quiet moments. Release them through breath and prayer.', bn: 'Past regrets may surface during quiet moments. Release them through breath and prayer.', kn: 'Past regrets may surface during quiet moments. Release them through breath and prayer.', gu: 'Past regrets may surface during quiet moments. Release them through breath and prayer.' },
  { en: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.', hi: 'आज आध्यात्मिक बायपासिंग का जोखिम है। कठिन भावनाओं को पार करने के बजाय उनका सामना करें।', sa: 'आज आध्यात्मिक बायपासिंग का जोखिम है। कठिन भावनाओं को पार करने के बजाय उनका सामना करें।', mai: 'आज आध्यात्मिक बायपासिंग का जोखिम है। कठिन भावनाओं को पार करने के बजाय उनका सामना करें।', mr: 'आज आध्यात्मिक बायपासिंग का जोखिम है। कठिन भावनाओं को पार करने के बजाय उनका सामना करें।', ta: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.', te: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.', bn: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.', kn: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.', gu: 'Spiritual bypassing is a risk today. Face difficult emotions rather than transcending them.' },
];

// ─────────────────────────────────────────────────────────────
// Daily insight (one-liner) pools
// ─────────────────────────────────────────────────────────────
export const INSIGHT_GOOD: BilingualText[] = [
  { en: 'The stars align in your favor today — seize the moment with intention.', hi: 'आज तारे आपके पक्ष में हैं — इरादे के साथ इस क्षण को पकड़ें।', sa: 'आज तारे आपके पक्ष में हैं — इरादे के साथ इस क्षण को पकड़ें।', mai: 'आज तारे आपके पक्ष में हैं — इरादे के साथ इस क्षण को पकड़ें।', mr: 'आज तारे आपके पक्ष में हैं — इरादे के साथ इस क्षण को पकड़ें।', ta: 'The stars align in your favor today — seize the moment with intention.', te: 'The stars align in your favor today — seize the moment with intention.', bn: 'The stars align in your favor today — seize the moment with intention.', kn: 'The stars align in your favor today — seize the moment with intention.', gu: 'The stars align in your favor today — seize the moment with intention.' },
  { en: 'Cosmic currents carry you forward. Trust and flow.', hi: 'ब्रह्माण्डीय धाराएँ आपको आगे ले जाती हैं। विश्वास करें और प्रवाह में रहें।', sa: 'ब्रह्माण्डीय धाराएँ आपको आगे ले जाती हैं। विश्वास करें और प्रवाह में रहें।', mai: 'ब्रह्माण्डीय धाराएँ आपको आगे ले जाती हैं। विश्वास करें और प्रवाह में रहें।', mr: 'ब्रह्माण्डीय धाराएँ आपको आगे ले जाती हैं। विश्वास करें और प्रवाह में रहें।', ta: 'Cosmic currents carry you forward. Trust and flow.', te: 'Cosmic currents carry you forward. Trust and flow.', bn: 'Cosmic currents carry you forward. Trust and flow.', kn: 'Cosmic currents carry you forward. Trust and flow.', gu: 'Cosmic currents carry you forward. Trust and flow.' },
  { en: 'Today rewards courage and clarity. Step boldly into your truth.', hi: 'आज साहस और स्पष्टता को पुरस्कृत करता है। अपने सत्य में साहसपूर्वक कदम रखें।', sa: 'आज साहस और स्पष्टता को पुरस्कृत करता है। अपने सत्य में साहसपूर्वक कदम रखें।', mai: 'आज साहस और स्पष्टता को पुरस्कृत करता है। अपने सत्य में साहसपूर्वक कदम रखें।', mr: 'आज साहस और स्पष्टता को पुरस्कृत करता है। अपने सत्य में साहसपूर्वक कदम रखें।', ta: 'Today rewards courage and clarity. Step boldly into your truth.', te: 'Today rewards courage and clarity. Step boldly into your truth.', bn: 'Today rewards courage and clarity. Step boldly into your truth.', kn: 'Today rewards courage and clarity. Step boldly into your truth.', gu: 'Today rewards courage and clarity. Step boldly into your truth.' },
  { en: 'Abundance surrounds you — open your heart to receive.', hi: 'प्रचुरता आपको घेरे हुए है — प्राप्त करने के लिए अपना हृदय खोलें।', sa: 'प्रचुरता आपको घेरे हुए है — प्राप्त करने के लिए अपना हृदय खोलें।', mai: 'प्रचुरता आपको घेरे हुए है — प्राप्त करने के लिए अपना हृदय खोलें।', mr: 'प्रचुरता आपको घेरे हुए है — प्राप्त करने के लिए अपना हृदय खोलें।', ta: 'Abundance surrounds you — open your heart to receive.', te: 'Abundance surrounds you — open your heart to receive.', bn: 'Abundance surrounds you — open your heart to receive.', kn: 'Abundance surrounds you — open your heart to receive.', gu: 'Abundance surrounds you — open your heart to receive.' },
  { en: 'A day of positive momentum. Your efforts bear fruit.', hi: 'सकारात्मक गति का दिन। आपके प्रयास फल देते हैं।', sa: 'सकारात्मक गति का दिन। आपके प्रयास फल देते हैं।', mai: 'सकारात्मक गति का दिन। आपके प्रयास फल देते हैं।', mr: 'सकारात्मक गति का दिन। आपके प्रयास फल देते हैं।', ta: 'A day of positive momentum. Your efforts bear fruit.', te: 'A day of positive momentum. Your efforts bear fruit.', bn: 'A day of positive momentum. Your efforts bear fruit.', kn: 'A day of positive momentum. Your efforts bear fruit.', gu: 'A day of positive momentum. Your efforts bear fruit.' },
  { en: 'Grace and good fortune walk beside you today.', hi: 'आज कृपा और सौभाग्य आपके साथ चलते हैं।', sa: 'आज कृपा और सौभाग्य आपके साथ चलते हैं।', mai: 'आज कृपा और सौभाग्य आपके साथ चलते हैं।', mr: 'आज कृपा और सौभाग्य आपके साथ चलते हैं।', ta: 'Grace and good fortune walk beside you today.', te: 'Grace and good fortune walk beside you today.', bn: 'Grace and good fortune walk beside you today.', kn: 'Grace and good fortune walk beside you today.', gu: 'Grace and good fortune walk beside you today.' },
];

export const INSIGHT_MIXED: BilingualText[] = [
  { en: 'A day of contrasts — navigate with awareness and adaptability.', hi: 'विरोधाभासों का दिन — जागरूकता और अनुकूलनशीलता से नेविगेट करें।', sa: 'विरोधाभासों का दिन — जागरूकता और अनुकूलनशीलता से नेविगेट करें।', mai: 'विरोधाभासों का दिन — जागरूकता और अनुकूलनशीलता से नेविगेट करें।', mr: 'विरोधाभासों का दिन — जागरूकता और अनुकूलनशीलता से नेविगेट करें।', ta: 'A day of contrasts — navigate with awareness and adaptability.', te: 'A day of contrasts — navigate with awareness and adaptability.', bn: 'A day of contrasts — navigate with awareness and adaptability.', kn: 'A day of contrasts — navigate with awareness and adaptability.', gu: 'A day of contrasts — navigate with awareness and adaptability.' },
  { en: 'Balance is your superpower today. Hold the center amid shifting energies.', hi: 'आज संतुलन आपकी महाशक्ति है। बदलती ऊर्जाओं के बीच केंद्र में रहें।', sa: 'आज संतुलन आपकी महाशक्ति है। बदलती ऊर्जाओं के बीच केंद्र में रहें।', mai: 'आज संतुलन आपकी महाशक्ति है। बदलती ऊर्जाओं के बीच केंद्र में रहें।', mr: 'आज संतुलन आपकी महाशक्ति है। बदलती ऊर्जाओं के बीच केंद्र में रहें।', ta: 'Balance is your superpower today. Hold the center amid shifting energies.', te: 'Balance is your superpower today. Hold the center amid shifting energies.', bn: 'Balance is your superpower today. Hold the center amid shifting energies.', kn: 'Balance is your superpower today. Hold the center amid shifting energies.', gu: 'Balance is your superpower today. Hold the center amid shifting energies.' },
  { en: 'Patience transforms ordinary moments into opportunities for growth.', hi: 'धैर्य साधारण क्षणों को विकास के अवसरों में बदलता है।', sa: 'धैर्य साधारण क्षणों को विकास के अवसरों में बदलता है।', mai: 'धैर्य साधारण क्षणों को विकास के अवसरों में बदलता है।', mr: 'धैर्य साधारण क्षणों को विकास के अवसरों में बदलता है।', ta: 'Patience transforms ordinary moments into opportunities for growth.', te: 'Patience transforms ordinary moments into opportunities for growth.', bn: 'Patience transforms ordinary moments into opportunities for growth.', kn: 'Patience transforms ordinary moments into opportunities for growth.', gu: 'Patience transforms ordinary moments into opportunities for growth.' },
  { en: 'Not every day needs to be extraordinary. Find peace in the ordinary.', hi: 'हर दिन असाधारण होना आवश्यक नहीं। साधारण में शांति खोजें।', sa: 'हर दिन असाधारण होना आवश्यक नहीं। साधारण में शांति खोजें।', mai: 'हर दिन असाधारण होना आवश्यक नहीं। साधारण में शांति खोजें।', mr: 'हर दिन असाधारण होना आवश्यक नहीं। साधारण में शांति खोजें।', ta: 'Not every day needs to be extraordinary. Find peace in the ordinary.', te: 'Not every day needs to be extraordinary. Find peace in the ordinary.', bn: 'Not every day needs to be extraordinary. Find peace in the ordinary.', kn: 'Not every day needs to be extraordinary. Find peace in the ordinary.', gu: 'Not every day needs to be extraordinary. Find peace in the ordinary.' },
  { en: 'Mixed planetary signals suggest observing before acting.', hi: 'मिश्रित ग्रहीय संकेत कार्रवाई से पहले अवलोकन का सुझाव देते हैं।', sa: 'मिश्रित ग्रहीय संकेत कार्रवाई से पहले अवलोकन का सुझाव देते हैं।', mai: 'मिश्रित ग्रहीय संकेत कार्रवाई से पहले अवलोकन का सुझाव देते हैं।', mr: 'मिश्रित ग्रहीय संकेत कार्रवाई से पहले अवलोकन का सुझाव देते हैं।', ta: 'Mixed planetary signals suggest observing before acting.', te: 'Mixed planetary signals suggest observing before acting.', bn: 'Mixed planetary signals suggest observing before acting.', kn: 'Mixed planetary signals suggest observing before acting.', gu: 'Mixed planetary signals suggest observing before acting.' },
  { en: 'Stay grounded — clarity emerges by evening.', hi: 'स्थिर रहें — शाम तक स्पष्टता उभरती है।', sa: 'स्थिर रहें — शाम तक स्पष्टता उभरती है।', mai: 'स्थिर रहें — शाम तक स्पष्टता उभरती है।', mr: 'स्थिर रहें — शाम तक स्पष्टता उभरती है।', ta: 'Stay grounded — clarity emerges by evening.', te: 'Stay grounded — clarity emerges by evening.', bn: 'Stay grounded — clarity emerges by evening.', kn: 'Stay grounded — clarity emerges by evening.', gu: 'Stay grounded — clarity emerges by evening.' },
];

export const INSIGHT_CHALLENGING: BilingualText[] = [
  { en: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.', hi: 'चुनौतीपूर्ण ऊर्जाएँ अतिरिक्त सावधानी की माँग करती हैं। धीरे और सोच-समझकर चलें।', sa: 'चुनौतीपूर्ण ऊर्जाएँ अतिरिक्त सावधानी की माँग करती हैं। धीरे और सोच-समझकर चलें।', mai: 'चुनौतीपूर्ण ऊर्जाएँ अतिरिक्त सावधानी की माँग करती हैं। धीरे और सोच-समझकर चलें।', mr: 'चुनौतीपूर्ण ऊर्जाएँ अतिरिक्त सावधानी की माँग करती हैं। धीरे और सोच-समझकर चलें।', ta: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.', te: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.', bn: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.', kn: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.', gu: 'Challenging energies demand extra mindfulness. Move slowly and deliberately.' },
  { en: 'Resistance is a teacher. What frustrates you today reveals what matters most.', hi: 'प्रतिरोध एक शिक्षक है। आज जो निराश करता है, वह बताता है कि सबसे महत्वपूर्ण क्या है।', sa: 'प्रतिरोध एक शिक्षक है। आज जो निराश करता है, वह बताता है कि सबसे महत्वपूर्ण क्या है।', mai: 'प्रतिरोध एक शिक्षक है। आज जो निराश करता है, वह बताता है कि सबसे महत्वपूर्ण क्या है।', mr: 'प्रतिरोध एक शिक्षक है। आज जो निराश करता है, वह बताता है कि सबसे महत्वपूर्ण क्या है।', ta: 'Resistance is a teacher. What frustrates you today reveals what matters most.', te: 'Resistance is a teacher. What frustrates you today reveals what matters most.', bn: 'Resistance is a teacher. What frustrates you today reveals what matters most.', kn: 'Resistance is a teacher. What frustrates you today reveals what matters most.', gu: 'Resistance is a teacher. What frustrates you today reveals what matters most.' },
  { en: 'This too shall pass. Focus on what you can control and release the rest.', hi: 'यह भी बीत जाएगा। जो नियंत्रित कर सकते हैं उस पर ध्यान दें, शेष छोड़ दें।', sa: 'यह भी बीत जाएगा। जो नियंत्रित कर सकते हैं उस पर ध्यान दें, शेष छोड़ दें।', mai: 'यह भी बीत जाएगा। जो नियंत्रित कर सकते हैं उस पर ध्यान दें, शेष छोड़ दें।', mr: 'यह भी बीत जाएगा। जो नियंत्रित कर सकते हैं उस पर ध्यान दें, शेष छोड़ दें।', ta: 'This too shall pass. Focus on what you can control and release the rest.', te: 'This too shall pass. Focus on what you can control and release the rest.', bn: 'This too shall pass. Focus on what you can control and release the rest.', kn: 'This too shall pass. Focus on what you can control and release the rest.', gu: 'This too shall pass. Focus on what you can control and release the rest.' },
  { en: 'A day for inner work rather than outer achievement. Go within.', hi: 'बाहरी उपलब्धि के बजाय आंतरिक कार्य का दिन। भीतर जाएँ।', sa: 'बाहरी उपलब्धि के बजाय आंतरिक कार्य का दिन। भीतर जाएँ।', mai: 'बाहरी उपलब्धि के बजाय आंतरिक कार्य का दिन। भीतर जाएँ।', mr: 'बाहरी उपलब्धि के बजाय आंतरिक कार्य का दिन। भीतर जाएँ।', ta: 'A day for inner work rather than outer achievement. Go within.', te: 'A day for inner work rather than outer achievement. Go within.', bn: 'A day for inner work rather than outer achievement. Go within.', kn: 'A day for inner work rather than outer achievement. Go within.', gu: 'A day for inner work rather than outer achievement. Go within.' },
  { en: 'Planetary tensions create growth opportunities in disguise. Stay resilient.', hi: 'ग्रहीय तनाव छिपे हुए विकास के अवसर बनाते हैं। दृढ़ बने रहें।', sa: 'ग्रहीय तनाव छिपे हुए विकास के अवसर बनाते हैं। दृढ़ बने रहें।', mai: 'ग्रहीय तनाव छिपे हुए विकास के अवसर बनाते हैं। दृढ़ बने रहें।', mr: 'ग्रहीय तनाव छिपे हुए विकास के अवसर बनाते हैं। दृढ़ बने रहें।', ta: 'Planetary tensions create growth opportunities in disguise. Stay resilient.', te: 'Planetary tensions create growth opportunities in disguise. Stay resilient.', bn: 'Planetary tensions create growth opportunities in disguise. Stay resilient.', kn: 'Planetary tensions create growth opportunities in disguise. Stay resilient.', gu: 'Planetary tensions create growth opportunities in disguise. Stay resilient.' },
  { en: 'Slow down, breathe deeply, and let the cosmic storm pass around you.', hi: 'धीमे हों, गहरी साँस लें, और ब्रह्माण्डीय तूफान को अपने चारों ओर से गुज़रने दें।', sa: 'धीमे हों, गहरी साँस लें, और ब्रह्माण्डीय तूफान को अपने चारों ओर से गुज़रने दें।', mai: 'धीमे हों, गहरी साँस लें, और ब्रह्माण्डीय तूफान को अपने चारों ओर से गुज़रने दें।', mr: 'धीमे हों, गहरी साँस लें, और ब्रह्माण्डीय तूफान को अपने चारों ओर से गुज़रने दें।', ta: 'Slow down, breathe deeply, and let the cosmic storm pass around you.', te: 'Slow down, breathe deeply, and let the cosmic storm pass around you.', bn: 'Slow down, breathe deeply, and let the cosmic storm pass around you.', kn: 'Slow down, breathe deeply, and let the cosmic storm pass around you.', gu: 'Slow down, breathe deeply, and let the cosmic storm pass around you.' },
];

// ─────────────────────────────────────────────────────────────
// Lucky colors
// ─────────────────────────────────────────────────────────────
export const LUCKY_COLORS: BilingualText[] = [
  { en: 'Red', hi: 'लाल', sa: 'लाल', mai: 'लाल', mr: 'लाल', ta: 'Red', te: 'Red', bn: 'Red', kn: 'Red', gu: 'Red' },
  { en: 'Orange', hi: 'नारंगी', sa: 'नारंगी', mai: 'नारंगी', mr: 'नारंगी', ta: 'Orange', te: 'Orange', bn: 'Orange', kn: 'Orange', gu: 'Orange' },
  { en: 'Yellow', hi: 'पीला', sa: 'पीला', mai: 'पीला', mr: 'पीला', ta: 'Yellow', te: 'Yellow', bn: 'Yellow', kn: 'Yellow', gu: 'Yellow' },
  { en: 'Green', hi: 'हरा', sa: 'हरा', mai: 'हरा', mr: 'हरा', ta: 'Green', te: 'Green', bn: 'Green', kn: 'Green', gu: 'Green' },
  { en: 'Blue', hi: 'नीला', sa: 'नीला', mai: 'नीला', mr: 'नीला', ta: 'Blue', te: 'Blue', bn: 'Blue', kn: 'Blue', gu: 'Blue' },
  { en: 'White', hi: 'सफ़ेद', sa: 'सफ़ेद', mai: 'सफ़ेद', mr: 'सफ़ेद', ta: 'White', te: 'White', bn: 'White', kn: 'White', gu: 'White' },
  { en: 'Purple', hi: 'बैंगनी', sa: 'बैंगनी', mai: 'बैंगनी', mr: 'बैंगनी', ta: 'Purple', te: 'Purple', bn: 'Purple', kn: 'Purple', gu: 'Purple' },
  { en: 'Gold', hi: 'सुनहरा', sa: 'सुनहरा', mai: 'सुनहरा', mr: 'सुनहरा', ta: 'Gold', te: 'Gold', bn: 'Gold', kn: 'Gold', gu: 'Gold' },
  { en: 'Silver', hi: 'चाँदी', sa: 'चाँदी', mai: 'चाँदी', mr: 'चाँदी', ta: 'Silver', te: 'Silver', bn: 'Silver', kn: 'Silver', gu: 'Silver' },
  { en: 'Cream', hi: 'क्रीम', sa: 'क्रीम', mai: 'क्रीम', mr: 'क्रीम', ta: 'Cream', te: 'Cream', bn: 'Cream', kn: 'Cream', gu: 'Cream' },
  { en: 'Saffron', hi: 'केसरिया', sa: 'केसरिया', mai: 'केसरिया', mr: 'केसरिया', ta: 'Saffron', te: 'Saffron', bn: 'Saffron', kn: 'Saffron', gu: 'Saffron' },
  { en: 'Maroon', hi: 'मैरून', sa: 'मैरून', mai: 'मैरून', mr: 'मैरून', ta: 'Maroon', te: 'Maroon', bn: 'Maroon', kn: 'Maroon', gu: 'Maroon' },
];

// ─────────────────────────────────────────────────────────────
// Indexed access
// ─────────────────────────────────────────────────────────────
export const TEMPLATES: Record<LifeArea, Record<QualityTier, BilingualText[]>> = {
  career:       { good: CAREER_GOOD,       mixed: CAREER_MIXED,       challenging: CAREER_CHALLENGING },
  love:         { good: LOVE_GOOD,         mixed: LOVE_MIXED,         challenging: LOVE_CHALLENGING },
  health:       { good: HEALTH_GOOD,       mixed: HEALTH_MIXED,       challenging: HEALTH_CHALLENGING },
  finance:      { good: FINANCE_GOOD,      mixed: FINANCE_MIXED,      challenging: FINANCE_CHALLENGING },
  spirituality: { good: SPIRITUALITY_GOOD, mixed: SPIRITUALITY_MIXED, challenging: SPIRITUALITY_CHALLENGING },
};
