// src/lib/kundali/health-diagnosis/element-catalog.ts
import type { ElementId, ElementMetadata } from './types';

export const ELEMENT_CATALOG: Record<ElementId, ElementMetadata> = {
  // Category 'longevity' is deliberate — per spec §4.1 and §8.1, vitality
  // (Ayushya) shares its primary significators with the longevity element
  // (8th house, Saturn, lagna lord). Two elements live in this category:
  // vitality (default-visible) and longevity (opt-in).
  vitality: {
    id: 'vitality',
    name: { en: 'Vitality', hi: 'जीवन शक्ति' },
    category: 'longevity',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 4, 6], houses: [1, 3, 8] },
    sources: ['BPHS-24', 'Phala-Deepika-9', 'Saravali-33'],
  },
  mental: {
    id: 'mental',
    name: { en: 'Mental Health', hi: 'मानसिक स्वास्थ्य' },
    category: 'mental',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [1, 3, 4, 7, 8], houses: [3, 4, 5, 12] },
    sources: ['BPHS-4', 'Saravali-5', 'Charaka-manasika-roga'],
  },
  digestive: {
    id: 'digestive',
    name: { en: 'Digestive System', hi: 'पाचन तंत्र' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 1, 2, 3, 4], houses: [2, 5, 6], signs: [4, 6] },
    sources: ['BPHS-24', 'Sarvartha-Chintamani-4', 'Charaka-Sutra', 'Ashtanga-Hridayam'],
  },
  cardiac: {
    id: 'cardiac',
    name: { en: 'Cardiac System', hi: 'हृदय प्रणाली' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 1, 2], houses: [4], signs: [5, 4] },
    sources: ['BPHS-24', 'Saravali-5', 'Charaka'],
  },
  respiratory: {
    id: 'respiratory',
    name: { en: 'Respiratory System', hi: 'श्वसन प्रणाली' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [3, 4, 6], houses: [3, 4], signs: [3, 4] },
    sources: ['BPHS-12', 'BPHS-24', 'Saravali-5', 'Ashtanga-Hridayam'],
  },
  nervous: {
    id: 'nervous',
    name: { en: 'Nervous System', hi: 'तंत्रिका तंत्र' },
    category: 'systemic',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [3, 6, 7], houses: [1, 3, 11] },
    sources: ['BPHS-24', 'Saravali-5', 'Charaka-Vatavyadhi'],
  },
  skeletal: {
    id: 'skeletal',
    name: { en: 'Bones & Joints', hi: 'अस्थि एवं संधि' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 6], houses: [8, 9, 10, 11], signs: [10, 11] },
    sources: ['BPHS-4', 'BPHS-24', 'Charaka', 'Saravali'],
  },
  muscular: {
    id: 'muscular',
    name: { en: 'Muscular & Inflammation', hi: 'मांसपेशी एवं सूजन' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 2, 7], houses: [1, 3, 6] },
    sources: ['BPHS-4', 'BPHS-24', 'Charaka-Raktapitta'],
  },
  skin: {
    id: 'skin',
    name: { en: 'Skin & Hair', hi: 'त्वचा एवं केश' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [2, 3, 5, 6], houses: [2, 6, 8], signs: [4, 6] },
    sources: ['BPHS-24', 'Saravali-5'],
  },
  eyes: {
    id: 'eyes',
    name: { en: 'Eyes & Vision', hi: 'नेत्र एवं दृष्टि' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 1, 3, 5], houses: [2, 6, 12] },
    sources: ['BPHS-12', 'BPHS-24', 'Sarvartha-Chintamani-4', 'Saravali-5'],
  },
  reproductive: {
    id: 'reproductive',
    name: { en: 'Reproductive Health', hi: 'प्रजनन स्वास्थ्य' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [1, 2, 4, 5], houses: [5, 7, 8], signs: [8] },
    sources: ['BPHS-4', 'BPHS-12', 'BPHS-24', 'Charaka-Shukravaha-Srotas', 'Sarvartha-Chintamani'],
  },
  endocrine: {
    id: 'endocrine',
    name: { en: 'Endocrine / Hormonal', hi: 'अंतःस्रावी / हार्मोनल' },
    category: 'systemic',
    badge: 'inferential',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [1, 4, 5], houses: [5] },
    sources: ['Jataka-Parijata-5', 'Saravali-5'],
  },
  immunity: {
    id: 'immunity',
    name: { en: 'Immunity / Ojas', hi: 'रोग प्रतिरोधक क्षमता' },
    category: 'systemic',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [0, 4], houses: [1, 8] },
    sources: ['Charaka-Sutra', 'Jaimini', 'BPHS'],
  },
  chronic: {
    id: 'chronic',
    name: { en: 'Chronic / Hidden Disease', hi: 'दीर्घकालिक / गुप्त रोग' },
    category: 'systemic',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [6, 7, 8], houses: [6, 8, 12] },
    sources: ['BPHS-24', 'Saravali-5', 'Phala-Deepika-9'],
  },
  accidents: {
    id: 'accidents',
    name: { en: 'Accidents & Injury', hi: 'दुर्घटनाएँ एवं चोट' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [2, 7, 8], houses: [4, 6, 8] },
    sources: ['BPHS-24', 'Phala-Deepika-9'],
  },
  surgery: {
    id: 'surgery',
    name: { en: 'Surgery & Hospitalisation', hi: 'शल्य एवं चिकित्सालय' },
    category: 'physical',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [2, 6, 8], houses: [8, 12] },
    sources: ['BPHS-24', 'Saravali'],
  },
  psychiatric: {
    id: 'psychiatric',
    name: { en: 'Severe Mental Illness', hi: 'गंभीर मानसिक रोग' },
    category: 'mental',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: true,
    primarySignificators: { planets: [1, 3, 7, 8], houses: [4, 5, 12] },
    sources: ['Saravali-5', 'Sarvartha-Chintamani', 'Charaka-Unmada'],
  },
  addictions: {
    id: 'addictions',
    name: { en: 'Addiction Vulnerability', hi: 'व्यसन की प्रवृत्ति' },
    category: 'mental',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [1, 2, 5, 7, 8], houses: [6, 8, 12] },
    sources: ['Saravali', 'Sarvartha-Chintamani'],
  },
  sleep: {
    id: 'sleep',
    name: { en: 'Sleep & Dreams', hi: 'निद्रा एवं स्वप्न' },
    category: 'mental',
    badge: 'classical',
    defaultVisible: true,
    requiresDisclaimer: false,
    primarySignificators: { planets: [1, 3, 6, 8], houses: [12] },
    sources: ['BPHS-12', 'Saravali'],
  },
  allergies: {
    id: 'allergies',
    name: { en: 'Allergies & Autoimmune', hi: 'एलर्जी एवं स्व-प्रतिरक्षा' },
    category: 'systemic',
    badge: 'inferential',
    defaultVisible: false,
    requiresDisclaimer: false,
    primarySignificators: { planets: [3, 7, 8], houses: [1, 6] },
    sources: ['Saravali'],
  },
  cancer: {
    id: 'cancer',
    name: { en: 'Cancer Diathesis', hi: 'कैंसर की प्रवृत्ति' },
    category: 'systemic',
    badge: 'mixed',
    defaultVisible: false,
    requiresDisclaimer: true,
    primarySignificators: { planets: [2, 6, 7], houses: [6, 8] },
    sources: ['Saravali-5', 'Bhrigu-Samhita', 'Sarvartha-Chintamani'],
  },
  longevity: {
    id: 'longevity',
    name: { en: 'Longevity Classification', hi: 'आयु वर्गीकरण' },
    category: 'longevity',
    badge: 'classical',
    defaultVisible: false,
    requiresDisclaimer: true,
    primarySignificators: { planets: [6], houses: [2, 3, 7, 8] },
    sources: ['BPHS-Ayur', 'Phala-Deepika-9', 'Hora-Sara'],
  },
};

export const ELEMENT_IDS: ElementId[] = Object.keys(ELEMENT_CATALOG) as ElementId[];
export const DEFAULT_VISIBLE_IDS: ElementId[] = ELEMENT_IDS.filter(id => ELEMENT_CATALOG[id].defaultVisible);
export const EXTENDED_IDS: ElementId[] = ELEMENT_IDS.filter(id => !ELEMENT_CATALOG[id].defaultVisible);
