'use client';
import { useCallback } from 'react';
import { Printer } from 'lucide-react';

interface PrintButtonProps {
  contentRef?: React.RefObject<HTMLElement | null>;
  contentHtml?: string;
  title?: string;
  label?: string;
  className?: string;
}

export default function PrintButton({ contentRef, contentHtml, title = 'Dekho Panchang', label = 'Print / PDF', className }: PrintButtonProps) {
  const handlePrint = useCallback(() => {
    const html = contentHtml || contentRef?.current?.innerHTML || '';
    if (!html) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <meta charset="utf-8" />
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Tiro+Devanagari+Sanskrit&family=Noto+Sans+Devanagari:wght@400;600;700&family=Inter:wght@400;500;600;700&display=swap');

    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', 'Noto Sans Devanagari', sans-serif;
      color: #1a1a2e;
      background: #fff;
      padding: 40px;
      font-size: 12px;
      line-height: 1.6;
    }
    h1, h2, h3 { font-family: 'Tiro Devanagari Sanskrit', serif; color: #8B6914; margin-bottom: 8px; }
    h1 { font-size: 24px; text-align: center; border-bottom: 2px solid #d4a853; padding-bottom: 12px; margin-bottom: 20px; }
    h2 { font-size: 18px; margin-top: 16px; }
    h3 { font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 11px; }
    th { background: #f5f0e0; font-weight: 600; color: #8B6914; }
    .gold { color: #8B6914; }
    .section { margin-bottom: 16px; padding: 12px; border: 1px solid #e5e5e5; border-radius: 8px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; background: #f5f0e0; color: #8B6914; }
    .footer { text-align: center; margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 10px; color: #999; }
    .devanagari { font-family: 'Tiro Devanagari Sanskrit', 'Noto Sans Devanagari', serif; }

    @media print {
      body { padding: 20px; }
      @page { margin: 15mm; size: A4; }
    }
  </style>
</head>
<body>
  ${html}
  <div class="footer">Generated by Dekho Panchang — dekhopanchang.com</div>
</body>
</html>`);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }, [contentRef, contentHtml, title]);

  return (
    <button
      onClick={handlePrint}
      className={className || 'inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-gold-primary/20 text-text-secondary text-sm hover:text-gold-light hover:bg-gold-primary/5 transition-colors'}
    >
      <Printer className="w-4 h-4" />
      {label}
    </button>
  );
}
